### ISSUE TITLE
No se puede buscar concursos por descripcion

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1002]
> ¿Hay alguna manera de buscar un concurso en específico?. Por ejemplo, los examenes de la Pre o las OMIs
> Antes pues solo lo buscaba con Ctrl F, pero como ya estan por paginas pues subió la dificultad

Ahora que los concursos estan paginados, ya no se puede buscar por un concurso .

**Comment by elendil326** [comment]
@alanboy @lhchavez Esto no está solucionado con la búsqueda de keywords?

**Comment by elendil326** [comment]
Esto aún es necesario.

**Comment by pabo99** [comment]
![sd 27](https://user-images.githubusercontent.com/3230352/31784189-6c36dc8a-b4c6-11e7-819b-5308bd0ec780.png)

@npave ¿ Está bien el buscador de concursos en esa posición ?

**Comment by pabo99** [comment]
Así es como quedaría:

![sd 27 ok](https://user-images.githubusercontent.com/3230352/31805419-384a009a-b526-11e7-8d4b-90804bf69b75.png)

**Comment by npave** [comment]
@pabo99 me parece bien tu propuesta. Cómo tienes pensado mostrar los resultados de la búsqueda?

**Comment by pabo99** [comment]
@npave  por el momento se muestran en el mismo listado, sin ningún estilo. Si tienes una propuesta, compártemela para agregar los cambios correspondientes.
