### ISSUE TITLE
[OfS] Faltan operaciones UPDATE para assignments

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1019]
En particular, ahorita no se puede cambiar hora/fecho de inicio/fin.

**Comment by npave** [comment]
Aquí está el mockup de como debería quedar la interfaz, [ofsMockups.zip](https://github.com/omegaup/omegaup/files/769150/ofsMockups.zip)

**Comment by joemmanuel** [comment]
Falta la UI.

**Comment by lhchavez** [comment]
Arreglado en 9b718e1b1455550b3f71f447a6afddb19ce5e46c
