### ISSUE TITLE
[OfS] No se puede eliminar estudiantes de un curso

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1020]
Desde la vista de Schools. Como la implementacion de fondo es un Group. Si se puede ir a la interfaz de groups y eliminarlos ahi. Pero estaria bien tener la funcionalidad completa en la UI de cursos

**Comment by lhchavez** [comment]
Arreglado en https://github.com/omegaup/omegaup/commit/e2c1f5d31e77ed74269b43426230c93aed4c13b2
