### ISSUE TITLE
[OfS] Implementar scoreboard para cursos

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1022]
La idea es usar la funcionalidad de `GroupScoreboard` para ver la tabla completa de calificaciones de estudiantes en los diferentes assignments de un curso.
Pero GroupScoreboard esta muy atado a concursos todavia, hay que enseniarle a trabajar con Problemsets.

*Pero* como la funcionalidad que aporta tiene mucho traslape con "View progress" (#1021) que es mas sencillo de implementar. Podemos usar solo "View progress" por el momento.

**Comment by joemmanuel** [comment]
@pabloaguilar, en https://github.com/omegaup/omegaup/pull/1148 estoy implementando el scoreboard por assignment y la idea (por feedback de Germán) es mostarlo en la arena de cada assignment. Crees que hacerlo así reemplace la idea del `GroupScoreboard` ?

**Comment by pabloaguilar** [comment]
Supongo que se puede remplazar, si. Scoreboard por assignments + view progress por curso.

**Comment by joemmanuel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1022 Implementar scoreboard](https://trello.com/c/tikOmBeb/1-1022-implementar-scoreboard)

**Comment by elendil326** [comment]
@joemmanuel @lhchavez Que procede con este feature?
