### ISSUE TITLE
Cuando se crea un nuevo problema y hay un error, el problema se vuelve público

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1034]
Si estás haciendo un nuevo problema y al darle crear te lo rechaza (e.g. zip incorrecto), todos los campos se preservan, salvo el toggle de público/privado, que se vuelve público siempre sin importar la elección anterior.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/594
