### ISSUE TITLE
Unir Scoreboards

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1050]
Me percato que tengo acceso a esta opcion, en el menu Concursos. Es un nuevo feature publico?
Cuando seleccionas varios concursos la tabla se desborda del margen.

**Comment by elendil326** [comment]
@lhchavez sabes si esto seguiría haciendo repro?

@samdsmx puedes dar más detalles del repro?

**Comment by elendil326** [comment]
Esto aún hace repro. Basta con seleccionar suficientes concursos dependiendo de la resolución de tu pantalla para hacerle repro:

![repro_omegaup](https://user-images.githubusercontent.com/3783894/30463988-c7aa2350-9983-11e7-85af-609078e0cc48.png)

**Comment by pabo99** [comment]
![captura de pantalla 2017-10-18 a la s 20 16 11](https://user-images.githubusercontent.com/3230352/31749720-57f77ebc-b441-11e7-9a6e-fe60a7e5fbd7.png)

Se agregan los estilos para que la tabla no se desborde cuando se agreguen muchos concursos en el Scoreboard
