### ISSUE TITLE
preferred_language vs  prefered_language

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1052]
https://github.com/omegaup/omegaup/blob/2a60ff560705a150accaff37dcf0eee370185bf4/frontend/www/libinteractive/index.php

if (in_array('HTTP_ACCEPT_LANGUAGE', $_SERVER)) { 

nunca es true y por eso no te das cuenta que la llamada dentro es a una funcion que no existe: 
preferred_language vs 
prefered_language

**Comment by elendil326** [comment]
@alanboy @lhchavez aún hay problemas con esto?

**Comment by elendil326** [comment]
Seguir el diseño de la paginación de problemas (Número de renglones por mostrar, etc).
