### ISSUE TITLE
OFSHACKATHON: Course start date is incorrectly saved

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1056]
Steps to repro:
* Create a Course (http://sandbox.omegaup.com/course/new)
* Choose a start date
* Save it
* **The start date will be one day before the date you chose**
* Go to the "Edit course" section
* Choose a start date
* Save it
* Refresh
* **The start date will be one day before the date you chose**

Notes:
* Reproduced this issue at 12:26PM Pacific Time

**Comment by pabloaguilar** [comment]
@rcxr Todavia puedes reproducir este issue? Segun yo ya quedo arreglado con varios cambios que hicimos respecto al manejo de fechas en la interfaz vs. el servidor

**Comment by lhchavez** [comment]
Sí, esto ya se debió haber arreglado en https://github.com/omegaup/omegaup/commit/130c6e20ab55e7562e6104dd790bbee46e0123a3
