### ISSUE TITLE
OFSHACKATHON: Show scoreboard cannot be updated

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1057]
Steps to repro:
* Go to the "Edit course" section
* Change the value of "Show scoreboard"
* Save it
* Refresh
* **The "Show scoreboard" value is the old value**

**Comment by elendil326** [comment]
Bloqueado por issue #1022

**Comment by tvanessa** [comment]
#1022 ya se resolvió

**Comment by pabo99** [comment]
Parece que en ese cambio también se arregló que se actualizara el valor de "Show scoreboard".

Ya se puede cerrar este issue
