### ISSUE TITLE
OFSHACKATHON: No hay mensaje de error para HTTP403 en el dashboard del curso

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1060]
[minor]
Repro:
* Con una cuenta sin permisos de alumno o profesor para algun curso intenta acceder al dashboard
* Sólo se ve el banner de omegaUp y nada más
* No es claro que el problema fue un problema de permisos ni ninguna sugerencia como: "Pide acceso al profesor de este curso (contacto del profesor)"

**Comment by pabloaguilar** [comment]
Esto ya esta arreglado, probablemente con el PR que agrego .fail a todas las API calls.
Ahorita se muestra el top nav y un mensaje de error "User is not allowed to perform action."
