### ISSUE TITLE
OFSHACKATHON: No hay mensaje de error para HTTP404 en el dashboard del curso

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1061]
[minor]
Repro:
* Accede al dashboard de un curso inexistente (http://sandbox.omegaup.com/course/estecursonoexiste)
* Sólo se ve el banner de omegaUp y nada más
* No es claro que el problema fue que el curso no existe, tal vez tuviste un typo en la URL

**Comment by pabloaguilar** [comment]
Ya esta arreglado. El link de reproduccion muestra "curso no encontrado"
