### ISSUE TITLE
OFSHACKATHON: No hay mensajes de error en el edit dashboard del curso

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1064]
[minor]
Repro:
* Con un usuario sin privilegios de maestro accede al edit dashboard de un curso (http://sandbox.omegaup.com/course/yourcourseid/edit)
* No hay ningún mensaje de error (aunque hubo un HTTP403)
* Intenta acceder al edit dashboard de un curso inexistente (http://sandbox.omegaup.com/course/estecursonoexiste/edit)
* No hay ningún mensaje de error (aunque hubo un HTTP404)

**Comment by pabloaguilar** [comment]
Ya se arreglo via mostrar los .fail en todas las llamadas a la API #1114
