### ISSUE TITLE
OFSHACKATHON: Possible bug with chrome cookies or google credentials

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1065]
Repro steps:

1. In Google Chrome, log in your Google account.
2. Go to sandbox.omegaup.com -> Log in
3. Log in with valid credentials.

Expected: Redirection to OmegaUp home with proper credentials.

Actual: Redirection to OmegaUp home **with no credentials**, so log in failed.

**Comment by erosethan** [comment]
De hecho, creo que lo que no funciona es el log in.

He intentado acceder con un usuario proporcionado por el gdoc, tambien me redirecciona al inicio sin credenciales.

He intentado acceder con un usuario y contrasena inexistente, esto si proporciona un mensaje de error, dado que no existen esas credenciales.

**Comment by joemmanuel** [comment]
👍  Este bug fue nominado para el más interesante.

**Comment by pabloaguilar** [comment]
El paso 3 es login con user/passowrd nativo o con el login button de Google?

**Comment by elendil326** [comment]
No repro
