### ISSUE TITLE
[BUG] El calendario para las fechas esta en ingles aunque omegaup esta en espanol

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1067]
![image](https://cloud.githubusercontent.com/assets/527987/23282674/1c4e2016-f9d7-11e6-8be9-bd66505acc5e.png)

**Comment by lhchavez** [comment]
Lo que falta:

* DatePicker parece que no tiene soporte para localizacion.
* Otros usos de DateTimePicker (fuera de Schools)

**Comment by elendil326** [comment]
Matemos DatePicker y reemplacemoslo por DateTimePicker.

**Comment by lhchavez** [comment]
Los componentes de DateTimePicker y DatePicker ya están usando controles nativos de HTML, que siempre se despliegan usando el locale del navegador. Sólo falta arreglar el que está en `contest.new.tpl`, y ese se va a arreglar en cuanto se Vue-ifique esa vista (https://github.com/omegaup/omegaup/issues/3682).

Cerrando esto porque lo único que falta es ese issue.
