### ISSUE TITLE
OFSHACKATHON: El titulo del tab "Agregar tarea" debe ser "agregar tarea o examen"

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1071]
http://sandbox.omegaup.com/course/algoritmos1/edit/#add-assignment

solo me di cuenta que puedo crear examentes al expandir la opcion de "tipo de tarea"

**Comment by pabloaguilar** [comment]
Debe ser solo "Tareas/examenes" porque en esa misma pantalla se agregan y borran tareas y examenes. 9.11 en el dashboard
