### ISSUE TITLE
OFSHACKATHON: Updating language does nothing

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1075]
Repro steps:

1. Log in and go to profile edition.
2. Change the preferred language.
3. Click on save changes.

Expected: An confirmation messages shows and the content in the site are reloaded in the selected language.

Actual: Edit page reloads, the content is not in the selected language, no confirmation message and the language that you chose is not displayed on the "Language" field.

**Comment by pabloaguilar** [comment]
Esto ya funciona
