### ISSUE TITLE
OFSHACKATHON: links a los perfiles de los estudiantes no jalan en "Add Student"

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1081]
Repro:
* Ve al "Add Students" de un curso (http://sandbox.omegaup.com/course/yourcourseid/edit/#add-students)
* Agrega un estudiante
* Intenta dar clic al link del estudiante en la tabla
* No pasa nada

**Comment by pabloaguilar** [comment]
Esto ya funciona. Lleva al perfil del estudiante dentro del curso (no al perfil publico del estudiante)
