### ISSUE TITLE
OFSHACKATHON: El reporte en "Course progress" no es claro

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1083]
Repro:
* Crea un curso
* Crea un test
* Crea dos homeworks
* Ve a "Course Progress" (http://sandbox.omegaup.com/course/yourcourseid/edit/#view-progress)
* La lista no se entiende
  * En la columna homeworks aparece 1/2 (no debería ser 0/2?) para todos los estudiantes
  * En la columna tests aparece 1/1 (no debería ser 0/1?) para todos los estudiantes

**Comment by elendil326** [comment]
@rcxr @lhchavez necesitamos más detalles de lo que se espera que aparezca.

**Comment by pabloaguilar** [comment]
El dejar 1/N hardcodeado fue para poder probar la lista durante el hackathon de schools.
Ya se arreglo y las puntuaciones que se ven son las correctas.
