### ISSUE TITLE
OFSHACKATHON: Just can't create assignment

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1084]
Refer to screenshot:
![fdsafdsa](https://cloud.githubusercontent.com/assets/2381031/23283615/be51a794-f9db-11e6-89e5-c9a3931d8095.png)

Expected: Assignment created.

Actual: Nothing happens.

**Comment by pabloaguilar** [comment]
Creo que esto se arreglo con #1114

**Comment by elendil326** [comment]
@pabloaguilar @lhchavez que procede? Fixed? No repro? TBD?

**Comment by pabloaguilar** [comment]
Yo no lo puedo reproducir
Lo voy a marcar Fixed.
