### ISSUE TITLE
OFSHACKATHON: En "Add Problem" no se pueden ver ni editar ninguno de los problemas antes agregados

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1085]
Repro:
* Crea un curso
* Crea un test
* Agrega un problema al test
* No hay forma de ver ese problema
* No hay mensaje de error al intentar agregar ese problema de nuevo
* No hay forma de borrar ese problema del test

**Comment by joemmanuel** [comment]
Paso 1: Hacer apiRemoveProblem

**Comment by rcxr** [comment]
Done al paso que sugirió @joemmanuel (https://github.com/omegaup/omegaup/pull/1093)

Para el siguiente paso, voy a usar CourseController::apiAssignmentDetails para obtener los problems relacionados a un assigment, y con eso terminar la UI de
http://sandbox.omegaup.com/course/test1/edit#add-problems

**Comment by rcxr** [comment]
Fixed by #1103
