### ISSUE TITLE
OFSHACKATHON: El tooltip de estudiante en add-students esta en ingles (y tiene falta de ortografia)

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1086]
En http://sandbox.omegaup.com/course/algoritmos1/edit/#add-students

![image](https://cloud.githubusercontent.com/assets/527987/23283686/48a6398c-f9dc-11e6-9edf-50d0dd260e11.png)

*their

**Comment by lhchavez** [comment]
Fixed in https://github.com/omegaup/omegaup/commit/593e2313b2f74633cc2857b181e18ee86801f183
