### ISSUE TITLE
OFSHACKATHON: Create course with no credentials does nothing

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1087]
Repro steps:

1. Log in into OmegaUp.
2. Open a second tab and go to /course/new
3. Fill out the course form with correct information.
4. In the first tab, log out.
5. In the second tab, click "Schedule contest".

Expected: You are redirected to log in page.

Actual: Nothing happens.

**Comment by pabloaguilar** [comment]
Arreglado en #1114 
Ahorita se muestra un mensaje "You need to login to perform that action."
