### ISSUE TITLE
OFSHACKATHON: No 404 error for non-existent courses

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1088]
Repro steps:

1. Go to /course/enter-a-non-existent-course/edit

Expected: 404 Error message.

Actual: A blank form is presented.

**Comment by joemmanuel** [comment]
Muy parecido a https://github.com/omegaup/omegaup/issues/1061, pero no _exactamente_ igual. Lo dejo como válido.

**Comment by pabloaguilar** [comment]
Ya se arreglo via mostrar los .fail en todas las llamadas a la API #1114
