### ISSUE TITLE
OFSHACKATHON: Added problem to assignment, but it does not show on select box

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1089]
Repro steps:

1. Create a course, an assignment and go to add problem.
2. Select an assignment and a valid problem.
3. Click on "Add problems".

Expected: Problem is added to assignment and appears on the above selection box.

Actual: Problem is **actually added**, but it is not displayed in selection box.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1085
