### ISSUE TITLE
OFSHACKATHON: Not handling correctly adding non-existing problems

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1090]
Repro steps:

1. Create a course, an assignment and go to add problem.
2. In the problem input, type a non-existing problem.
2a. Alternatively, type an actual problem, followed by another valid problem (it states "Add problems", but does not specify how to add several problems.
3. Click on "Add problems".

Expected: Error message saying that it was not possible to add problems.

Actual: No error message and problem input gets in blank.

**Comment by pabloaguilar** [comment]
Casi resuelto con #1114 pero todavia esta el problema de que  la pagina de agregar problemas es muy alta y el status message se muestra hasta arriba, de manera que el usuario no se entera que hubo un error.

Eso deberia arreglarse en #1338
