### ISSUE TITLE
OFSHACKATHON: 1/0 progress in course

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1091]
When course does not have tests (guess it works same way with homework) the progress of students in test is undefined (or 1/0 if you are too much geeky).

![untitled](https://cloud.githubusercontent.com/assets/2381031/23284608/3d5f04f0-f9e1-11e6-9139-529dbefe8192.png)

**Comment by joemmanuel** [comment]
Fixed: https://github.com/omegaup/omegaup/issues/1021
