### ISSUE TITLE
OFSHACKATHON: Accessing a problem in course with no credentials causes a infinite loading page

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1092]
Repro steps:

1. Copy to clipboard a link to a valid problem in an assignment in a course.
2. Log out of OmegaUp.
3. Go to the link you copied.

Expected: Site redirects to log in page.

Actual: Blank page with the ccw loading gif never stopping.

**Comment by pabloaguilar** [comment]
Interesante. Se muestra un error en el status, pero esttus no esta visible porque esta el overline del spinner y root no esta visible.
