### ISSUE TITLE
OFSHACKATHON

### ISSUE THREAD

**Issue by cruzjorgesalazar** [omegaup/omegaup#1096]
Cuando editas tu perfil y pones el idioma al momento lo escriba en el capo, pero cuando le das en guardar cambios no se guarda el idioma y si cambias a otro idioma no hay cambios en el lenguaje,

**Comment by alanboy** [comment]
dup de https://github.com/omegaup/omegaup/issues/676 ya quedo arreglado

**Comment by cruzjorgesalazar** [comment]
![2017-02-24](https://cloud.githubusercontent.com/assets/26012714/23318946/29724d30-fa9a-11e6-9ffa-543be5b31079.png)

Nose si sea porque hay muchos envios pero el problema ya lleva mucho tiempo en new sin dar ningun informe

**Comment by alanboy** [comment]
eso es un problema aparte, lo ideal seria abrir otro bug, pero te responderé por aquí: esto pasa por idiosincrasia de sandbox.omegaup.com, no sirven los envios :(
