### ISSUE TITLE
[BUG] Problema al iniciar sesion

### ISSUE THREAD

**Issue by cruzjorgesalazar** [omegaup/omegaup#1097]
Cuando ya tienes un usuario y contraseña ya no puedes volver a ingresar, cuando le das iniciar sesion te envia un mensaje que es necesario iniciar sesion.

Ahora como inicio sesion?

**Comment by alanboy** [comment]
puedes volver a intentar con una ventana incógnito ?

**Comment by elendil326** [comment]
@alanboy @lhchavez no repro?
