### ISSUE TITLE
OFSHACKATHON: Render no funciona bien poniendo el screen de lado izquierdo y derecho

### ISSUE THREAD

**Issue by pacopedraza** [omegaup/omegaup#1105]
1. Ingresa a Omegaup: http://sandbox.omegaup.com/
2. Coloca la ventana de la pagina a la derecha o a la izquierda

RESULTADO ACTUAL:
Los elementos no se visualizan correctamente, ( incluida la imagen del user)

RESULTADO ESPERADO:
Los elementos se deberian visualizar correctamente.
![render_omegaup](https://cloud.githubusercontent.com/assets/11931152/23328134/3029dca6-fae0-11e6-814f-57d56a306a4a.png)

**Comment by lhchavez** [comment]
Esto es así por diseño :( Lo que pasa es que si el menú de arriba ya no cabe en la pantalla a lo ancho, se colapsa verticalmente en vez de horizontalmente.

**Comment by alanboy** [comment]
Esto pasa muy seguido, y es incómodo cuando estás desarrollando omegaup y quieres poner el navegador de un lado y el editor del otro.

**Comment by lhchavez** [comment]
piensa en los usuarios móviles: necesitan que este comportamiento se mantenga o es inusable
