### ISSUE TITLE
OFSHACKATHON: Boton "Next" agrega ids aunque no hay elementos en la pagina rank

### ISSUE THREAD

**Issue by pacopedraza** [omegaup/omegaup#1106]
1. Ingresa a Omegaup http://sandbox.omegaup.com
2. Click en el link: " View full rank "
3. Da click varias veces en "Next"

RESULTADO ACTUAL:
La aplicacion agrega id's en la barra de navegador aunque no halla elementos de rank para ese user.
![nextpage_omegaup](https://cloud.githubusercontent.com/assets/11931152/23328205/875ffc84-fae1-11e6-95f9-588deb57a1f3.png)

**Comment by joemmanuel** [comment]
👍  Este bug fue nominado para el más interesante.

**Comment by pacopedraza** [comment]
¡Me habría Gustado tener mas tiempo de probar la plataforma ! Seguro
encuentro más cosas :p
Saludos
Paco
BTW: durante el registro creí que "Joemmanuel" era un bot Jaja, ya después
me di cuenta de que no. Hasta pensé que era la tarjeta Intel del Alan boy
chateando

**Comment by joemmanuel** [comment]
@pacopedraza haha! Muchas gracias a tí por participar!. Estas totalmente invitado a loggear más bugs si te los encuentras. Ya te agregué a la lista de voluntarios para que te lleguen los anuncios de los próximos eventos.
