### ISSUE TITLE
OFSHACKATHON: Curso es listado múltiples veces

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1107]
En http://sandbox.omegaup.com/course/
Con el usuario: OMIP2017-064
Contraseña: Y2NTHEms

La lista tiene múltiples veces el mismo curso.
![image](https://cloud.githubusercontent.com/assets/684205/23332987/3ba787b0-fb38-11e6-8dff-30916fdc6aa2.png)

**Comment by joemmanuel** [comment]
👍  Este bug fue nominado para el más interesante.
