### ISSUE TITLE
OFSHACKATHON: Caché no borra datos de envío de archivo en página de problemas

### ISSUE THREAD

**Issue by pacopedraza** [omegaup/omegaup#1111]
1. Entra a omega up
2. Logeate
3. Click en en drop down de problems
4. Click en "bugbash"
5. Click en "New Submission"
6. Click en "Choose" file y adjunta tu archivo.
7. Click en "Submit"
8. Vuelve a dar click en "New Submission"

RESULTADO ACTUAL
1. El archivo previamente enviado sigue apareciendo.

**Comment by pabloaguilar** [comment]
Funcionaba...
Pero parece que la solucion, de donde tomamos la solucion nosotros, ya no jala tampoco:
https://stackoverflow.com/a/1043969/334852
http://jsfiddle.net/jonathansampson/dAQVM/
