### ISSUE TITLE
OFSHACKATHON: No valida correctamente el nombre del archivo "Main.extension" en página de problemas

### ISSUE THREAD

**Issue by pacopedraza** [omegaup/omegaup#1112]
1. Entra a omega up
2. Logeate
3. Click en en drop down de problems
4. Click en "bugbash"
5. Click en "New Submission"
6. Click en "Choose" file y adjunta tu archivo (Ponle un nombre diferente a main por ejemplo prueba.txt)
7. Click en "Submit"

RESULTADO ACTUAL
1. La página no envía ningún error diciendo que el nombre del archivo no es "Main.extensión"
![main_prob_omegaup](https://cloud.githubusercontent.com/assets/11931152/23334685/9ff2bb1e-fb69-11e6-93d1-1618ce2f2d9f.png)

**Comment by lhchavez** [comment]
eso no necesita una validación, porque sólo es una advertencia de que lo que sea que envíes se va a guardar con ese nombre.

creo que es mejor no validarlo porque es más fácil guardar tu programa localmente con el nombre que quieras. sería un relajo para la gran mayoría de la gente :(
