### ISSUE TITLE
[OfS] Autocomplete en agregar user a group no funciona correctamente

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1129]
Este es el reporte verbatim, hay que investigar más:

2017-03-10 9:23 GMT-08:00 Nancy Pacheco <nancydanielap@gmail.com>:
Darle click en la opción que muestra el autocomplete tampoco funciona, por eso sugerí que no se utilizará el autocomplete. Se necesita escribir el nombre completo para que se agregue el usuario correcto. Usar autocomplete es engañosos porque agrega un usuario que coincide hasta donde se tecleo. 

Saludos  

2017-03-10 8:49 GMT-08:00 Joemmanuel Ponce Galindo <joemmanuel@gmail.com>:
+ lhchavez, 
Germán, posiblemente tenemos un bug en el autocomplete... en lo que revisamos de nuestro lado, puedes intentar darle explícitamente click a la opción que muestra el autocomplete? 

2017-03-09 22:48 GMT-08:00 Nancy Pacheco <nancydanielap@gmail.com>:
Luis, estás utilizando el auto-complete? Esto no está funcionando bien. Estamos investigando cual es el problema. Podrías continuar agregando estudiantes sin utilizar el auto-complete, por favor?

Gracias
Nancy

2017-03-09 12:55 GMT-08:00 Nancy Pacheco <nancydanielap@gmail.com>:
Hola Luis,

Excelente que ya estés utilizando la plataforma.

Si actualizas la página y tratas de agregar más estudiantes, te marca el mismo error?

Saludos
Nancy

On Mar 9, 2017 12:35 PM, "Luis German" <licgerman@gmail.com> wrote:
Hola Nancy.

Tengo un problema, ya generé el grupo pero me marca un error cuando quiero agregar usuarios al grupo. El sistema me permitió agregar unos tres o cuatro y luego marcó error con varios usuarios al momento de agregar.

Adjunto la imagen.

Saludos.

-- 
LUIS GERMAN GUTIERREZ TORRES

-- 
Nancy Pacheco
http://www.nancypacheco.me

**Comment by pabloaguilar** [comment]
Auto complete y Vue no se llevan bien.
Parece que auto complete crea un segundo input transparente encima del input correcto que no esta adecuadamente conectado via v-model
