### ISSUE TITLE
[FEATURE] Añadir opción de agregar el nombre de la escuela al crear un curso

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1141]
hacer eso nos permitira saber que escuelas estan usando schools

**Comment by elendil326** [comment]
@alanboy @lhchavez que se requiere del UI? mostrar la escuela en la búsqueda? mostrar la escuela en los detalles del curso?

**Comment by tvanessa** [comment]
El formulario tiene un campo para poner la escuela

![Screen Shot 2020-04-06 at 5 05 04 PM](https://user-images.githubusercontent.com/13296248/78616342-cf4a4f00-7828-11ea-90af-1c4fab57f5ea.png)
