### ISSUE TITLE
[FEATURE] Navegar a lista de cursos desde un curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#1154]
Falta agregar un link en la página de un curso para regresar a la lista de cursos. Ahorita tienes que dar clic en _Schools_ en el _Top menu_ y después en _Start using Schools._

**Comment by rcxr** [comment]
Tomando este issue :)

**Comment by elendil326** [comment]
@lhchavez @npave requiere diseño de UI mínimo

**Comment by tvanessa** [comment]
Añadir un path como se muestra en la imagen

![Screen Shot 2020-06-20 at 5 55 10 PM](https://user-images.githubusercontent.com/13296248/85214444-5040bf00-b31f-11ea-8357-efcfb517f545.png)

**Comment by pabo99** [comment]
Sería buen momento para decidir si agregamos un breadcrums en todo omegaUp. Por lo pronto, en este cambio lo colocaré donde indica @tvanessa
