### ISSUE TITLE
Permitir agregar co-administradores a un curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#1156]
Ahorita solo el dueño del curso puede editar la información del curso, pero en ocasiones el curso es impartido por varios profesores.

**Comment by lhchavez** [comment]
Los cursos ya tienen un ACL de administración: `Courses.acl_id`. La idea es solamente hacer la interfaz para agregar más gente a ese ACL y mover `api{Add,Remove}{,Group}Admin` de `ContestController.php` a otro lugar donde todas las cosas que tengan ACLs lo puedan usar.

**Comment by npave** [comment]
La idea sería agregar un botón para agregar "co-administradores" en la pantalla de cada curso, algo así:

![co-admin2](https://cloud.githubusercontent.com/assets/940007/26422551/3639e822-407f-11e7-9c1a-14cf5f9663e8.png)
En editar curso, necesitamos agregar un tab "Co-administradores", algo así:

![co-admin1](https://cloud.githubusercontent.com/assets/940007/26422552/363abd88-407f-11e7-9804-606a442931b2.png)

**Comment by lhchavez** [comment]
Ya estaba trabajando en ello y se parece a tu diseño :D

**Comment by elendil326** [comment]
@lhchavez esto aún no está implementado?

**Comment by lhchavez** [comment]
no, todavía no termino :/

**Comment by lhchavez** [comment]
Aquí está lo que llevaba :S https://github.com/lhchavez/omegaup/tree/schoolsadmin 

para aplicarlo en el ambiente local, se puede hacer

    curl https://github.com/lhchavez/omegaup/commit/1cfc8463a7980bfa12cc6e5e954c7ab872491284.patch | git am

**Comment by lhchavez** [comment]
Detalles de implementación para los controladores:

* cambiar el esquema de la base de datos para agregar una columna: `Courses.admin_group_id`.
* agregar una entrada en `Groups` por cada `Course` donde el `Groups.acl_id = Courses.acl_id`.
* agregar una entrada en `Groups_Roles` donde el `Groups_Roles.group_id = Groups.group_id` (el que se creó en el paso anterior) y `Groups_Roles.role_id = Authorization::ADMIN_ROLE`.
* actualizar `Courses.admin_group_id`con el `Groups.group_id` del paso anterior.

una vez que esté hecho todo eso, es cuestión de agregar/quitar gente de ese grupo.

**Comment by pabo99** [comment]
Duda, ¿cómo hago los cambios en el esquema de la base de datos?

**Comment by lhchavez** [comment]
En el Pull Request hay que hacer un cambio tanto a `frontend/database/schema.sql` como hacer un script de migración (en el caso de este issue, ese script de migración debe hacer todo lo descrito en mi comentario en formato SQL). Aquí hay un ejemplo: https://github.com/omegaup/omegaup/commit/adfd4d17fcc1f09cd0838654bf56592094dc0342
