### ISSUE TITLE
Error en el tiempo

### ISSUE THREAD

**Issue by luisrodolfo** [omegaup/omegaup#1164]
Equipo omegaUp,

Durante los concursos de preselección de México, dos de nuestros competidores tuvieron problemas porque el examen les mostraba que empezaba y terminaba antes. Esto ocasiono que el concurso se les cerrara una hora antes de que terminara.  Revisamos los relojes de sus maquinas y la configuración y estaban con la hora correcta y la zona de tiempo de México. ¿Por qué ocurrió esto?

La solución momentánea que aplicamos durante el examen, fue retrasar una hora el reloj de la computadora de los competidores. 

Adjunto la imagen de lo ocurrido.

Saludos

- 
![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/12162641/25045683/118526c8-20f3-11e7-96dc-cab09dededeb.jpg)
Luis Rodolfo

**Comment by pabo99** [comment]
No logro reproducir el escenario que se reporta. Quizás se requiere de más información, cómo Sistema Operativo, versión de navegador, etc.

**Comment by elendil326** [comment]
Cerrando como "No repro"
