### ISSUE TITLE
(Calidad): Soportar promocion/democion de problemas

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1168]
Hablando con @lhchavez, proponemos un feature para que los reviewers del Edu Committee puedan promocionar o democionar los problemas. El esquema propone que todos los problemas tengan una clasificacion o nivel que determine en que lista(s) aparecen en OmegaUp, a continuacion se detallan las clasificaciones:

* *Problemas baneados* (-1). Son problemas que deben ser eliminados de la plataforma por presentar contenido ofensivo o inapropiado.
* *Problemas privados* (0). Estos problemas solo pueden ser visualizados por el autor, usuarios y grupos con acceso explicito al problema y administradores. Un problema se _debería_ mantener privado si:
    * La redaccion/casos no son correctos o son inconsistentes entre si.
    * El problema es un duplicado de otro problema.
    * La calidad del problema no es apropiada para su publicacion.
* *Problemas publicos* (1). Los problemas publicos aparecen en la lista global de OmegaUp visibles a todos los usuarios.
* *Problemas recomendados* (2). Estos problemas son seleccionados por el Edu Committee por ser de alta calidad y brindar la mejor experiencia de aprendizaje en OmegaUp (idealmente **todos** estos problemas tienen editorial).

**Comment by Fer-OmegaUp** [comment]
Esto es duplicado. Cerrando.
