### ISSUE TITLE
(Calidad): Limitar modificacion de visibilidad de problemas

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1169]
Permitir que solo los usuarios con rol de reviewers puedan modificar la visibilidad de un problema.

**Comment by lhchavez** [comment]
La discusión alrededor de https://github.com/omegaup/omegaup/issues/1168 fue que los reviewers / admins son los únicos que pueden transicionar 1<->2 y 0<->-1.

**Comment by erosethan** [comment]
Si, aunque en caso de que se haga la transicion a -1, solo un reviewer puede traer un -1 de vuelta a la vida.

**Comment by lhchavez** [comment]
sí, eso dije :P cool, tenemos consenso entonces!

**Comment by Fer-OmegaUp** [comment]
@heduenas otro mas duplicado?

**Comment by heduenas** [comment]
No es duplicado, pero si esta resuelto https://github.com/omegaup/omegaup/blob/fa0c9ff0bf396816dadf84e7b105ab799dfde402/frontend/server/controllers/ProblemController.php#L64
