### ISSUE TITLE
(Calidad)" Promotion/Demotion queue

### ISSUE THREAD

**Issue by erosethan** [omegaup/omegaup#1170]
Cuando solo el rol de reviewer pueda modificar la visibilidad de un problema, debemos permitir que los autores soliciten que sus problemas sean considerados para su publicacion en la lista de OmegaUp, incluso que sean sugeridos en la lista de problemas recomendados.

Se propone la implementacion de una promotion queue. Los autores pueden solicitar que la visibilidad de un problema cambie, mientras que los reviwers pueden gestionar estas solicitudes.

**Comment by Fer-OmegaUp** [comment]
@heduenas creo que este no es dup?

**Comment by heduenas** [comment]
A esté le falta buena parte de promotion. Pero lo de promotion no está en nuestros planes cercanos. Así que yo creo que hay que conservarlo como low priority  y no hay que incluirlo en el proyecto del MVP.

**Comment by heduenas** [comment]
La demotion queue ya esta funcionando y promotion fue abandonado.
