### ISSUE TITLE
Ocultar los site-admins de los problemas/concursos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1185]
Entiendo que es por transparencia, pero no creo que tener los site-admins ayude en mucho a los editores de problemas - qué opinan de removerlos?

**Comment by alanboy** [comment]
+1

**Comment by elendil326** [comment]
@joemmanuel esto es solo quitarlos del UI? o hay cambios en permisos?

**Comment by lhchavez** [comment]
sólo quitarlos del UI

**Comment by elendil326** [comment]
@npave puedes checar este y decrinos que opinas?

**Comment by elendil326** [comment]
Poniendo como ready con el signoff de Nancy

**Comment by pabo99** [comment]
¿Cuáles son los site-admins? ¿de donde y donde hay que quitarlos?

**Comment by lhchavez** [comment]
espera, y el signoff de @npave ? por qué le pusiste ready?

en fin, los site-admins son todos los usuarios que tienen poderes de administración global en el sitio. Si vas a https://localhost:8080/problem/sumas/edit#admins, vas a ver que `omegaup` se muestra como `owner`, pero en producción hay varios usuarios que se muestran como `site-admin`.

mi propuesta es ocultarlos no permanentemente sino debajo de algo que se pueda desplegar. ya sea un checkbox o algo colapsable. ahí es donde Nancy viene a rescatarnos :D

**Comment by pabo99** [comment]
ok, quedo en espera del signoff de @npave

**Comment by elendil326** [comment]
Este es el signoff de Nancy por slack, pero como menciona @lhchavez falta definir como ocultarlos. CC @npave 

![image](https://user-images.githubusercontent.com/3783894/31669509-25d9b54a-b30a-11e7-91cd-c6d84f92b0f2.png)

**Comment by pabo99** [comment]
![captura de pantalla 2017-10-18 a la s 09 28 48](https://user-images.githubusercontent.com/3230352/31724647-f188d080-b3e7-11e7-84a5-78d6fccc53f4.png)

@npave te agrada la idea de que se muestren-oculten los site-admin con un checkbox?
