### ISSUE TITLE
Duplicado de problemas resueltos.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1196]
En "tus problemas" al ver "problemas que administro" se duplican.

**Comment by pabo99** [comment]
@MiguelRomero, ¿aún puedes reproducir este bug? De ser así, ¿Me puedes dar más información?

**Comment by pabo99** [comment]
Lo intenté reproducir pero no me fue posible por falta de información. Además veo que el query cuenta con un `GROUP BY problem_id`. Así que asumo que alguien ya lo había corregido antes.
