### ISSUE TITLE
[FEATURE] Crear el concepto de cursos públicos recomendados 

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1198]
Cursos es una forma excelente de organizar los problemas. Habrá cursos (OMI, OMIP/S, OIEG y el Torneo Latinoamericano) que sería bueno hacer público para cualquier usuario y que se le mostrara en su página princpal de cursos.

**Comment by pabloaguilar** [comment]
Fixed. Tenemos cursos publicos en el carousel de la página principal
