### ISSUE TITLE
Dejar que los usuarios vean la solución/diff de casos a problemas *muy* sencillos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1199]
Feedback de pláticas con los maestros: El primer punto de frustración para maestros y alumnos con omegaUp es "atinarle" al formato del output esperado: Más bien, para maestros/alumnos no familiarizados con programación competitiva necesitan ayuda para darse cuenta que el evaluador no es flexible con la respuesta esperada.
Una opción es "regalar" un conjunto de problemas introductorios (A+B like) donde el usuario pueda ver a detalle el diff con los casos esperados.

**Comment by lhchavez** [comment]
Dupe de #990
