### ISSUE TITLE
Hacer el manual de "Cómo crear problemas" más visible

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1200]
Hasta a mí me tocó 40 segundos encontrarlo D:  Se aceptan sugerencias.

**Comment by npave** [comment]
Qué les parece así?

![comocrearproblemavisible](https://cloud.githubusercontent.com/assets/940007/25934747/7ac007d4-35d4-11e7-99f3-9412ef724b9f.png)

**Comment by pabloaguilar** [comment]
Se ve bien.

**Comment by elendil326** [comment]
Esto es mover el link de "¿Cómo crear problemas?" como muestra el boceto de Nancy.
