### ISSUE TITLE
Avisar a los concursantes que al salirse de la página, perderán acceso a sus códigos en modo arena

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1213]
Esto evitará confusiones en un futuro. Esto depende de https://github.com/omegaup/omegaup/issues/1195 para que puedan ver actualizaciones sin necesidad de perder sus códigos.

**Comment by elendil326** [comment]
@lhchavez un poco de diseño requerido para las palabras a usarse, el pop-up, etc.

**Comment by lhchavez** [comment]
esto basta con un messagebox normal que diga, cuando se está en [modo lockdown](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/arena/arena.js#L50), que diga

   Advertencia: en modo lockdown, tus envíos ya no serán accesibles si te sales de la página.

**Comment by elendil326** [comment]
#1542 le dará seguimiento a este issue
