### ISSUE TITLE
[BUG] Coder del mes en curso aparece 2 veces en la lista de Coders del mes

### ISSUE THREAD

**Issue by JuanM97** [omegaup/omegaup#1214]
Durante el mes de mayo, el coder del mes aparece 2 veces en la lista https://omegaup.com/coderofthemonth/

**Comment by alanboy** [comment]
Tambien pasa con `2015-02-01`.

**Comment by tvanessa** [comment]
![whatsapp image 2018-03-29 at 12 45 06 am](https://user-images.githubusercontent.com/13296248/38076488-9cfa823e-32ea-11e8-86ef-6cca1a0d4d12.jpeg)
![whatsapp image 2018-03-29 at 12 44 45 am](https://user-images.githubusercontent.com/13296248/38076489-9d16608a-32ea-11e8-9aa9-02ce897f8649.jpeg)

**Comment by tvanessa** [comment]
It seems that it's not working
![index](https://user-images.githubusercontent.com/13296248/38591739-15141210-3ced-11e8-8e89-74bea28f2331.jpeg)

**Comment by tvanessa** [comment]
Ping

**Comment by tvanessa** [comment]
Duplicado #3149
