### ISSUE TITLE
Mail de bienvenida sin logo y con problemas de encoding.

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1221]
![image](https://cloud.githubusercontent.com/assets/527987/26479426/feebc908-4187-11e7-9248-19a2c5fb108b.png)

**Comment by pabloaguilar** [comment]
Tambien hay que averiguar cual es la mejor forma de escoger lenguaje. Se le pregunta al usuario cuando crea su cuenta? Si no, mandamos bienvenida en multiples lenguajes?

**Comment by lhchavez** [comment]
Una buena heurística es la configuración del navegador del usuario, que ya debe tener `Accept-Languages`. Esto ya se propaga a la plantilla de Smarty que usamos para elegir el lenguaje, así que con hacer ` $smarty->getTemplateVars('WELCOME_EMAIL')` o algo así debería ser suficiente.
