### ISSUE TITLE
No es posible completar perfil si no se selecciona México

### ISSUE THREAD

**Issue by alculquicondor** [omegaup/omegaup#1226]
Pasos para reproducir:
1. Iniciar sesión
2. Ir a https://omegaup.com/profile/edit/
3. Seleccionar un país distinto de México
4. Guardar Cambios

Error
```
El campo debe ser un número: state_id
```

**Comment by alculquicondor** [comment]
Al visualizar un perfil, se completa con los estados de USA. Por ejemplo, en vez de salir "Arequipa", sale "Arkansas", en el caso de Peru.

**Comment by lhchavez** [comment]
afortunadamente es un error cosmético: la información se puede reconstruir correctamente de la base de datos.

espero esta semana terminar https://github.com/omegaup/omegaup/issues/1228 , que va a arreglar este problema de raíz. por lo tanto voy a cerrar este issue porque _ya_ es posible completar un perfil si no se selecciona México :D
