### ISSUE TITLE
[OfS] Profesores necesitan ver las soluciones de sus alumnos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1231]
Feedback del profesor de CBTIS 139:

_Entre otras cosas, perdón por la molestia pero hay algo que no he podido hacer en omegaUp , el seguimiento de alumnos o progreso como es llamado, solo me permite ver una calificación pero hasta ahora no se como ver, cuales son los ejercicios resueltos por cada o ver el código que envían en caso de que tengan alguna dificultad poder hacerles sugerencias o aclaraciones.
Es decir, no encuentro como hacer lo mismo que con los concursos, ver el número de envíos, cuales enviaron o detectar errores específicos de los alumnos con mayor retraso en actividad.
El reporte que se puede descargar es muy bueno, ojalá tuviera un poco mas de información._

**Comment by pabloaguilar** [comment]
Esto ya se puede. Aqui estan los pasos:
* Ir a la vista principal del curso
* Dar click en "Progreso de los estudiantes"
* Dar click en el link del estudiante
* Seleccionar la tarea/examen para la cual se quieren ver envios de ese estudiante
* Ver el codigo!

![image](https://user-images.githubusercontent.com/189223/27992184-5a5dcbce-6442-11e7-934b-39cdfcd39b5e.png)
