### ISSUE TITLE
Tagear todos los problemas de Karel para que sea facil encontrarlos

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1236]
Ahora que Karel en la OMI solo es para niños de primaria y secundaria, es muy importante que puedan tener acceso a todos los problemas existentes de karel. sobre todo por que los maestros que los están preparando son los maestros de sus escuelas y casi no han tenido contacto la olimpiada.

**Comment by lhchavez** [comment]
Voy a hacer esto más general: reservaré las etiquetas `karel`, `lenguaje`, `solo-salida`, `interactivo` y cada que se modifique un problema voy a forzar la pertenencia/no-pertenencia de esos tags en dicho problema.
