### ISSUE TITLE
EDU: [Promotion/Demotion queue] Usuario quiere nominar un problema para el Promotion/Demotion queue. (Controller)

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1237]
Complementario al trabajo en la interfaz (ver #1238 )

1. Actualizar [problems.php](https://github.com/omegaup/omegaup/blob/292415f749370c8fcfae2a9c68421b4c50c4b130/frontend/www/arena/problem.php) para declarar las banderas $is_problem_solved y $is_problem_nominated
2. Estas banderas obtendrán su valor del nuevo controller QualityNominationController.
 * La bandera $is_problem_solved puede ser llenada con la información existente ($result['solvers'])
 * Método IsProblemNominatedByUser(problemId, userId) en el QualityNominationController regreserá la información para la bandera $is_problem_nominated
3. Para el pop-up de la forma de nominación, el submit será incluido en [arena.js](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/arena/arena.js).
4. QualityNominationController tendrá los métodos Promote(problemId, userId) y Demote(problemId, userId). Estos internamente llamarán al mismo método privado SetQuality(problemId, userId, action) donde action es el enum "promotion" o "demotion". Los métodos publicos serán expuestos en el API [api.js](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/api.js)

**Comment by lhchavez** [comment]
> La bandera $is_problem_solved puede ser llenada con la información existente ($result['solvers'])

esto únicamente muestra los mejores 10 envíos, así que hay que hacer otro método para esto.

> Método IsProblemNominatedByUser(problemId, userId) en el QualityNominationController regreserá la información para la bandera $is_problem_nominated

ya tienes que hacer otro método, así que mejor cámbialo por `getNominationStatus(Problems $problem, Users $user)` que te regrese ambas banderas.

> Para el pop-up de la forma de nominación, el submit será incluido en arena.js.

El pop-up de la forma mejor hay que hacerlo en Vue.

> QualityNominationController tendrá los métodos Promote(problemId, userId) y Demote(problemId, userId). Estos internamente llamarán al mismo método privado SetQuality(problemId, userId, action) donde action es el enum "promotion" o "demotion". Los métodos publicos serán expuestos en el API api.js

Mejor haz un sólo método `apiNominateProblem` que reciba el `problem_alias`, `username` (no exponemos IDs en el API), y todos los demás campos de `QualityNominations`.
