### ISSUE TITLE
EDU: [Promotion/Demotion queue] Usuario quiere nominar un problema para el Promotion queue. (Interfaz)

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1238]
Ver comentarios para más detalles.

**Comment by heduenas** [comment]
Escenarios del usuario:
Cuando el usuario ha resuelto un problema (AC) le aparecera un mensaje felicitandolo por resolverlo y una liga invitandolo a nominar el problema:
![screenshot from 2017-05-30 23-10-18](https://cloud.githubusercontent.com/assets/597815/26618931/1e9c056c-4591-11e7-97f6-93118c9a7db6.png)
Después le aparecerá un formulario con tres campos:
* "Descripción (markdown)".
* "Fuente (URL / cita)".
* "Etiquetas (temas y dificultad)".
* "Observaciones".

Todos los campos cargaran los valores que el usuario ingresó en su última nominación (suponiendo que lo había nominado antes). Si no lo había nominado antes, se cargaran los valores almacenados en la base de datos de problemas.

**Comment by elendil326** [comment]
Bosquejo de implementación:

Añadir un if tag en [arena.problem.tpl](https://github.com/omegaup/omegaup/blob/master/frontend/templates/arena.problem.tpl) que leerá las banderas del controller:
* $is_problem_solved
* $is_problem_nominated

  * Si ambos true, mostrar un mensaje de agradecimiento por nominar este problema
  * Si solo problem_solved es true, mostrar botón para desplegar pop-up del formulario descrito en el escenario del ususario. El pop-up será un nuevo template, el comportamiento de pop-up será similar al arena.runsubmit.tpl.
  * No es posible el caso en el que solo is_problem_nominated es true
  * Si ninguno es true, no mostrar nada.

El nuevo template tendrá el formulario y el controller se encargará de la lógica de nominación.

**Comment by alanboy** [comment]
>Si ambos true, mostrar un mensaje de agradecimiento por nominar este problema

Estaria genial que dijera algo como "Tu promoviste esto a la cola de ..."

>Si solo problem_solved es true, mostrar botón para desplegar pop-up del formulario descrito en el escenario del ususario. El pop-up será un nuevo template, el comportamiento de pop-up será similar al arena.runsubmit.tpl.

En cuanto creemos un pop-up te apuesto que mucha gente se va a quejar. O por lo menos no hay que hacerlo en concursos ? No se...

>No es posible el caso en el que solo is_problem_nominated es true
>Si ninguno es true, no mostrar nada.

A menos que seas super-admin?

**Comment by npave** [comment]
Qué les parece si en lugar de un mensaje arriba de los Envíos, implementamos algo así?

![evaluacionproblemas](https://cloud.githubusercontent.com/assets/940007/26667030/fdd5614e-4657-11e7-87ff-939407e6fe40.png)

- Creo que para una persona que no tiene todo el contexto que nosotros tenemos no va a entender la pregunta "¿Quieres nominar este problema al distintivo de Calidad?", qué tienen pensado hacer para que el usuario sepa que es distintivo de Calidad?

- Si el usuario decide que si quiere nominar el problema, entonces se muestra un formulario: 
       - falta mejorar la redacción de cada pregunta, no se entiende que es lo que se pide  
       - la respuesta a las preguntas serán un Si/No, escala Likert, pregunta abierta? 

- Qué pasa si después de llegar al formulario el usuario decide que siempre no quiere hacer la nominación?
