### ISSUE TITLE
(Calidad) [Promotion/Demotion queue] Pool de reviewers quiere ver el Promotion/Demotion queue. (Interfaz)

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1240]
TODO:

**Comment by heduenas** [comment]
![screenshot from 2017-05-31 00-23-54](https://cloud.githubusercontent.com/assets/597815/26620701/b67221ee-4598-11e7-9181-10c148a8574c.png)
Si el usuario está registrado en el pool de reviewers, entonces mostrar la opción "Ver cola de nominaciones" en el menú de Problemas.
"Ver nominaciones" abre una página tabla con una fila por nominación/{reporte de contenido inapropiado}. Cada fila tendrá los campos:
* Tipo. (Promoción o Democión)
* Alias del problema.
* Nombre del usuario que nominó / reportó.
* Fecha de envío de la solicitud.
* Juez asignado.
* Estado. ("Pendiente" o "Completado (Aceptado)" o "Completado (Denegado)")
* Botón de "Ver".

**Comment by elendil326** [comment]
Bosquejo de implementación:

Crear un nuevo Vue para la nueva lista de problemas nominados.
Las variables para llenar la lista vendrán del nuevo qualitynominations.php. Este archivo consumirá de ProblemsDAO y del nuevo QualityNominationsDAO para accesar la información del a base de datos.

Modificar el dropdown para incluir la nueva opción si y solo si el usuario es admin.

**Comment by lhchavez** [comment]
> Al dar click en Ver nominaciones, se despliega una tabla con la lista de nominaciones e información relevante al respecto. Si el usuario tiene revisiones pendientes al inicio de la página se despliega un mensaje “Tienes n revisiones pendientes.” Al dar click ahí se muestran las nominaciones con evaluación pendiente al inicio de la tabla.
> Además, se puede agregar un botón “Mis revisiones” que ordene la información en la tabla y muestre las revisiones de este usuario al principio.

~@npave
