### ISSUE TITLE
(Calidad): [Promotion/Demotion queue] Usuario quiere nominar problema para  Demotion queue. (Interfaz)

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1242]
TODO:

**Comment by heduenas** [comment]
Escenario del usuario:

Cuando el usuario está viendo un problema al final de la página habrá un link con el texto "Reportar contenido ofensivo o inapropiado".
Al dar clic, se abre un dialog box con una etiqueta que diga "¿Por qué consideras inapropiado este problema?", un textarea para que el usuario escriba sus razones, un boton "Reportar" que envía el reporte y un botón "Cancelar".
Al dar clic en el botón "Reportar", se muestra una etiqueta que diga algo como "Gracias por enviar tu reporte. En un plazo de 72 horas tu reporte será revisado por un juez."

**Comment by Fer-OmegaUp** [comment]
@heduenas dup?

**Comment by heduenas** [comment]
Duplicado y terminado
