### ISSUE TITLE
EDU: [Promotion/Demotion queue] Administrar pool de reviewers (Controller)

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1243]
TODO:

**Comment by pabloaguilar** [comment]
Veo dos caminos aqui:
Hacerlo con roles/permissions:
* agregar un nuevo rol ReviewerAdmin
* o agregar un permiso "AddRemove Reviewers"

O hacerlo con grupos
* agregarle ACLs a grupos (ahorita solo tienen owner_id)
* crear dos perma-groups:
  - quality-reviewers
  - quality-reviewers-admin
* Super admins pueden agregar/quitar gente de quality-reviewer-admin
* quality-reviewers-admin tiene write-permissions sobre el ACL de quality-reviewers

Me inclino por el segundo porque:
* la interfaz de administracion seria la misma de grupos, i.e. #1244 estaria hecho por default
* encaja en el framework de ACLs sin necesidad de agregar un nuevo special case para revisores
* agregarle ACLs a grupos mata dos pajaros de un tiro porque tambien lo necesitamos para schools

Que opinan?

**Comment by heduenas** [comment]
Dos preguntas:
* ¿Qué es ACL?
* ¿Cuáles sería los beneficios de la primer solución?

**Comment by pabloaguilar** [comment]
* ACL: Access Control List. Es el mecanismo que usamos para manejar acceso a otros objetos en el sistema, como problemsets, concursos y cursos. Parece que se nos paso migrar grupos al sistema de ACLs
* Beneficios:
  - No requerimos las instancias especiales de grupos que siempre existan en la BD.
  - El permiso se define a nivel sistema (como realmente es) y no a nivel un grupo especial.

**Comment by heduenas** [comment]
Suena a que la segunda forma es la forma correcta de hacerlo.

**Comment by lhchavez** [comment]
Tenemos consenso! La segunda será.
