### ISSUE TITLE
EDU: [Promotion/Demotion queue] Reviewer quiere ver su queue individual. (Controller).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1245]
TODO:

**Comment by lhchavez** [comment]
Se decidió que se va a implementar junto con https://github.com/omegaup/omegaup/issues/1241

**Comment by lhchavez** [comment]
Al final se hizo por separado la parte del controlador.

**Comment by lhchavez** [comment]
Al final sí lo hice junto con #1241 para evitar código duplicado ;P
