### ISSUE TITLE
EDU: [Promotion/Demotion queue] Reviewer quiere ver su queue individual. (Interfaz).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1246]
TODO:

**Comment by heduenas** [comment]
Este escenario es casi idéntico al de #1240 excepto que mostrará sólo las revisiones asignadas al usuario loggeado.

![screenshot from 2017-05-31 00-23-54](https://cloud.githubusercontent.com/assets/597815/26667264/1ae405f0-4659-11e7-8094-d5b253d8375d.png)
Si el usuario está registrado en el pool de reviewers, entonces mostrar la opción "Ver mis revisiones pendientes" en el menú de Problemas.
"Ver mis revisiones pendientes" abre una página tabla con una fila por nominación/{reporte de contenido inapropiado}. Cada fila tendrá los campos:

Tipo. (Promoción o Democión)
Alias del problema.
Nombre del usuario que nominó / reportó.
Fecha de envío de la solicitud.
Juez asignado.
Estado. ("Pendiente" o "Completado (Aceptado)" o "Completado (Denegado)")
Botón de "Ver".

**Comment by lhchavez** [comment]
Al final se decidió juntar con https://github.com/omegaup/omegaup/issues/1240
