### ISSUE TITLE
(Calidad): [Promotion/Demotion queue] Reviewer ve una nominación (Interfaz).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1249]
TODO:

**Comment by heduenas** [comment]
Cuando un usuario ve {la cola completa} o {su propia} cola de revisiones y hace clic en "Ver" alguna:

Si es una nominación a distintivo de calidad:
* Si la nominación ha sido asignada al usuario que esta loggeado y tiene estado pending entonces se muestran los campos:
    * Los campos de la aplicación rellenados por el usuario:
        * Liga al problema en omegaup.com/arena/problem/{alias}.
        * Descripción (markdown)
        * Tags
        * Fuente
        * Observaciones
    * Dos campos accionables para el juez:
        * Un dropdown con veredicto (Aceptado o Denegado).
        * Un campo de texto para feedback al usuario que nominó el problema.
* Si la nominación ha sido asignada a un usuario que no es el que esta loggeado o es una nominación que no tiene estado "pending" entonces se muestran los mismos campos, pero grayed-out.

Si es reporte de problema inapropiado:
* Si el reporte tiene estado pending (sea o el juez al que ha sido asignado) entonces se muestran los campos:
    * Los campos de la aplicación rellenados por el usuario:
        * Liga al problema en omegaup.com/arena/problem/{alias}.
        * Texto del usuario que describe por qué considera inapropiado el problema.
    * Dos campos accionables para el juez:
        * Un dropdown con veredicto (Aceptado o Denegado).
        * Un campo de texto para feedback al usuario que nominó el problema.

En ambos casos habrá un botón de enviar con un pop-up que pida confirmar que se desea el enviar el formulario.

**Comment by Fer-OmegaUp** [comment]
@heduenas duplicado y completado?

**Comment by heduenas** [comment]
Completado, pero no estoy seguro si duplicado.
