### ISSUE TITLE
(Calidad): [Promotion/Demotion queue] El usuario ve estado de TODAS (activas, resultas, etc.) sus nominaciones (Interfaz).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1251]
TODO

**Comment by heduenas** [comment]
![screenshot from 2017-05-31 00-23-54](https://cloud.githubusercontent.com/assets/597815/26620383/72f35b00-4597-11e7-9cd5-030d6d2a5a6c.png)
* En el menú de Problemas se añadirá una nueva opción "Mis nominaciones". La cuál será visible solamente si el usuario ha hecho alguna nominación.
* Al hacer click en "Mis nominaciones" se abrirá una tabla con una fila por nominación, cada fila con 5 campos: 
    * Veredicto juez 1 [Nombre del juez] (Aprobado o Denegado)
    * Retroalimentación juez [Nombre del juez]
    * Veredicto juez 2 [Nombre del juez] (Aprobado o Denegado)
    * Retroalimentación juez 2 [Nombre del juez]
    * Siguientes pasos. Si ambos veredictos son aprobados, mostrar "Felicidades, tu nominación ha sido aceptada por el comité de jueces". Si alguno de los veredictos fue denegado, mostrar "Desafortunadamente tu problema todavía no está listo para ser considerado de calidad. Por favor integra la retroalimentación dada por los jueces y envía de nuevo tu nominación."

**Comment by elendil326** [comment]
Bosquejo de implementación:

Se usará el mismo Vue que el de los admins (ver #1240). Con menos opciones de acción.

**Comment by npave** [comment]
En Veredicto juez n hay que considerar la opción Pendiente para mostrar cuando el problema aún está en proceso de revisión.

A qué se refieren con _Retroalimentación juez n_, retroalimentación del problema o retroalimentación de la nominación? Qué se espera que haga el usuario si la nominación es denegada? 

Es mucha la información que se quiere mostrar en el último campo (Siguientes pasos), consideren que esto se mostrará para cada nominación del usuario. Sería mejor si solo se pone Aceptada/Denegada. Si se quiere indicar al usuario que hacer si su nominación fue denegada, se puede poner un mensaje al inicio de la página, así esta información solo aparecería una vez.

**Comment by heduenas** [comment]
El feedback del juez va a ser el conjunto de directrices que el problema no cumple en caso de que se haya denegado. Si la nominacion fue aceptada, puede ser un mensaje de agradecimiento o cualquier otro feedback que pueda querer dar el juez.
Si es denegada el usuario debe de incorporar el feedback a su nominacion y mandarla de nuevo de la misma forma que la mando la primera vez.

**Comment by npave** [comment]
cómo se va a incorporar el feedback si el nominador no es el dueño del problema?

**Comment by heduenas** [comment]
A través de los campos
* "Descripción (markdown)".
* "Fuente (URL / cita)".
* "Etiquetas (temas y dificultad)".
* "Observaciones".
que el usuario debe de llenar cuando nómina un problema.

**Comment by pabloaguilar** [comment]
@heduenas No me es claro por que el nominador es el que tiene que corregir el problema. Como participante, resuelvo un problema, me gusta, lo nomino, pero al momento que me pides que me ponga a trabajar, me voy y espero que otro lo haga. Peor si se van a usar inputs abiertos para la descripcion o etiquetas.

Y es que creo que la motivacion de corregir el problema deberia ser del problemsetter, quien es el que va a llevar el credito de tener un problema de calidad.

**Comment by lhchavez** [comment]
esa es la cosa, los problemsetters no son muy responsivos. hay montones de problemas abandonados :(

también esa es la motivación de darle crédito al nominador del problema, incentivarlo a que corrija esto.

**Comment by Fer-OmegaUp** [comment]
@heduenas lo agrego al queue de comite educativo?

**Comment by heduenas** [comment]
Este ya está resuelto
