### ISSUE TITLE
EDU: [Soportar promocion/democion de problemas] El ususario puede ver todos los problemas de cálidad (filtrar o diferente vista) (Interfaz).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1258]
Ver comentarios para detalles del escenario del usuario y el bosquejo de diseño:

**Comment by heduenas** [comment]
* En la lista de problemas, se verá un icono distintivo al inicio de la fila de un problema con distintivo de calidad.
* Hasta arriba de la página de problemas habrá un botón para filtrar los problemas con distintivo de calidad.

![screenshot from 2017-05-30 23-56-53](https://cloud.githubusercontent.com/assets/597815/26619748/a874ddc4-4594-11e7-8bf2-eab725a35eab.png)

**Comment by elendil326** [comment]
Bosquejo de diseño:

La variable $problem inlcuirá información de laa visibilidad del problema (2 =recomended): [problem.list.tpl](https://github.com/omegaup/omegaup/blob/master/frontend/templates/problem.list.tpl).

Es cosa de agregar un if tag y verificar la propiedad "visibility" del problema. Si es recomended, entonces agregar un div con el ícono de recomended.

Pregunta abierta. Donde agregar ese icono en git?

**Comment by alanboy** [comment]
Yo de verdad, de verdad sugiero que no hagamos esto, o que este encendido por default. Entre menos opciones, decisiones tenga el usuario es mucho mejor. Mostrar todos los problemas de calidad y *DESPUES* o solo si el usuario lo selecciona (cambiar el boton a "Mostrar problemas sin evaluacion de calidad") mostrar los demas problemas. El golden path debe ser que el usuario de click en "Problemas" y ver inmediatamente problemas de calidad.

**Comment by heduenas** [comment]
Que tal dejarlo asi mientras que conseguimos una cantidad considerable de problemas de calidad y cuando la tengamos, entonces lo encendemos por default. Cuantos problemas les late para hacer el switch?

**Comment by alanboy** [comment]
yo digo que sea transparente... el usuario final no tiene por que conocer/entender el concepto de calidad... simplemente hacemos sort por calidad en el listado de problemas... primero apareceran los problemas con calidad... que ahorita seran exactamente cero. luego siguen los problemas que no son de calidad... conforme vayamos agregando problemas de calidad iran saliendo mas y mas al principio sin que el usuario tenga que hacer nada.

**Comment by lhchavez** [comment]
estoy parcialmente de acuerdo con alan: mostrar todos los problemas de calidad por default y mostrarlos todos si explícitamente elige verlos todos. pero no me gusta la idea de la transparencia total: explícito es mejor que implícito.

el darles el distintivo también es un incentivo. hay que presumirlo o se pierde su valor.
