### ISSUE TITLE
EDU; [Soportar promocion/democion de problemas] El problema refleja su estado (promovido o baneado) (Interfaz).

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1260]
Ver comentarios para escenario del ususario y bosquejo de diseño

**Comment by heduenas** [comment]
* Cuando un problema ha sido banneado no será visible para ningún usuario non-admin. Será visible para los usuarios admin del problema, estará marcado como privado y estará desactivada la opción para convertirlo en público.
* Cuando a un problema le ha sido otorgado el distintivo de calidad, tendrá al inicio de su título un icono distitivo de calidad (ver imagen). Cuando el usuario pasa el mouse sobre el icono, se mostrar un mensaje "Este problema ha sido reconocido como un Problema de Calidad por un comité de jueces de omegaUp".
![screenshot from 2017-05-31 00-09-07](https://cloud.githubusercontent.com/assets/597815/26619948/9555da9e-4595-11e7-986f-03d45da2b36c.png)

**Comment by elendil326** [comment]
Bosquejo de diseño:

La variable $problem contendrá la información de la visbilidad del problema (2 = recommended). Usar esta información para decidir si mostrar el icono, el texto o limitar la visibilidad del problema a non-admins.
