### ISSUE TITLE
[OfS] Como profesor, quiero ordenar los problemas en un assignment para guiar la dificultad  de los alumnos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1270]
## Comportamiento Esperado

_Los problemas que me sugeriste son muy buenos, creo que es responsabilidad nuestra ordenar para la complejidad o dificultad.....
Crees que sería posible que en la configuración de la tarea se pueda poner algo que los ordene.... En los concursos si se puede,  pero no encontré como hacerlo en la tarea,  así que mis problemas me quedan en desorden.el orden permite a los chicos ir escalando._

## Comportamiento Actual

No se pueden ordenar los problemas en un assignment.

## Posible Solución

Replicar lo que tenemos en concursos

## Contexto
<descrito arriba>

**Comment by pabloaguilar** [comment]
Dupe de #1367
