### ISSUE TITLE
Los profesores necesitan ver el codigo de sus estudiantes aunque el problema no sea suyo

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1273]
Los profesores han comentado que cuando se usan problemas de otros usuarios, no pueden ver los códigos enviados. Por eso, cuando les gusta un problema, clonan el problema (copiar/pegar desc) y es por eso que tenemos tantos problemas duplicados!!

Durante mi visita a la OMI y del cual MMUUUUCHOS profesores/delegados se quejaron.

Discusión interna:
que se pueda ver codigo para quienes ya resolvieron el problema, y que puedas ver solo el codigo a tu concurso/curso (y algun dia implementamos la cosa mas fancy de desactivar puntos ya que viste el codigo de otra gente)

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1274
