### ISSUE TITLE
Abrir visibilidad del codigo de envios a dueños de problemsets

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1274]
## Comportamiento Esperado

Un admin de un problemset debe poder ver el codigo de envios que se han hecho a _problemas en su problemset_ cuando:
* sea admin del problema (funcionalidad actual)
* ya haya resuelto el problema (funcionalidad propuesta)

Es la propuesta de soulcion para #1231

## Comportamiento Actual

Solo los admins de problemas pueden ver el codigo de envios a sus problemas.
La idea es evitar que la gente pueda hacer trampa creando un concurso paralelo que incluya el mismo problema y esperar que otra gente mande sus soluciones ahi.
Con esta propuesta, dado que es requisito haber resuelto el problema, no se puede usar para hacer trampa.

## Contexto

Una causa de problemas repetidos en omegaup.com es que organizadores de cursos/concursos no tienen acceso al codigo de sus alumnos/participantes. Entonces se ven obligados a crear copias de problemas para ser ellos los admins y asi tener visibilidad de sus envios.

**Comment by pabloaguilar** [comment]
Estoy probando esto en Sandbox y no puedo reproducir el problema.
Aqui esta lo que estoy haciendo:
* entre a sandbox como un usuario
* cree un concurso https://sandbox.omegaup.com/arena/pvc
* le agregue un problema, `picos`
* entre en una ventana de icognito y cree un usuario nuevo, `contestant`
* entre al concurso e hice un envio
* regreso a la ventana del duenio del concurso; voy a `mis concursos`
* doy click en `envios`
* voy al tab `envios`
* doy click en detalles del envio del usuario `contestant`:
https://sandbox.omegaup.com/arena/pvc/admin/#runs/show-run:d99964a5521e1dcde83f604b38c4edb5
* y me sale el codigo fuente del envio

Notese que el usuario que creo el concurso *no es admin del problema*.
Segun entiendo el codigo, hay una funcion, `canViewRun` y esa aplica si uno es duenio del envio o es duenio del problemset al que se hizo el envio:
https://github.com/omegaup/omegaup/blob/b4dacffd1b3d84a2936e294c95807bf5b1b76ad0/frontend/server/controllers/RunController.php#L581

Sera que el problema esta en la visibilidad del link para ver los envios?
Otros si pueden reproducir el problema?

**Comment by lhchavez** [comment]
pues `CanViewRun` lleva 5 años comportándose así :/ https://github.com/omegaup/omegaup/blob/4fe50a700a6d6cdacba634aa10ae2ff2edac85dc/frontend/server/libs/Authorization.php#L25 y el comportamiento actual de mostrar el botón de ver detalles lleva casi un año: https://github.com/omegaup/omegaup/commit/648999d6c5682190158f8c24eba556e66c0980b1

muy posiblemente esto es cargo-culting de un problema que ya fue resuelto.
