### ISSUE TITLE
(Calidad): [Promotion/Demotion queue] Usuario quiere proponer cambios a al enunciado, tags o fuente del problema

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1289]
Continuación de https://github.com/omegaup/omegaup/issues/1238

## Comportamiento Esperado
Al momento de recomendar un problema, el usuario debe poder sugerir cambios al enunciado del problema, tags y la fuente.

## Comportamiento Actual
No hay forma de sugerir cambios específicos

## Posible Solución
Agregar un formulario opcional en el popup de pregunta de recomendación

**Comment by heduenas** [comment]
Este también es parte de promotions, hay que mantenerlos como low priority y no hay que incluirlo en el MVP.
