### ISSUE TITLE
EDU: [Promotion/Demotion queue] Usuario puede dar más detalles sobre por qué recomienda un problema

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1290]
Continuación de #1238

## Comportamiento Esperado
El usuario puede dar más detalles sobre por qué nomina un problema, aparte del texto de `rationale`

## Comportamiento Actual
Sólo preguntamos por rationale

## Posible Solución
*Hay muchas posibles*, por favor pongan la solución final aquí  @npave @erosethan @heduenas :)

**Comment by heduenas** [comment]
Mocks de @npave:
![image](https://cloud.githubusercontent.com/assets/597815/26757986/86a77010-4884-11e7-87d8-94ab1ca4eb07.png)
![image](https://cloud.githubusercontent.com/assets/597815/26757987/8b2e034c-4884-11e7-96f1-3be6e3a2d97c.png)
Todos los elementos de la lista de etiquetas deben de tener un checkbox para que se pueda seleccionar un subconjunto de ellas.
![image](https://cloud.githubusercontent.com/assets/597815/26757988/8dc15e1a-4884-11e7-86f2-6bc4e2ce9347.png)
Sería mejor hacer el input box de "Por qué te gustaría recomendar este problema" multilinea para que sea fácil escribir más?

Si el usuario marca algún checkbox de "Sugerencias para mejorar la calidad del problema" entonces se le abre un nuevo tab con campos para editar fuente o redacción del problema.
