### ISSUE TITLE
Refactor de Identidad

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1300]
## Comportamiento Esperado

Necesitamos tener un mecanismo para asignar identidades por-concurso a los usuarios.

## Comportamiento Actual

Actualmente se generan usuarios sintéticos. Se necesita hacer deploy con una semana de anticipación para poder realizar esta acción.

## Contexto

Al pre-asignar una lista de identidades (username _a mostrar_, nombre _a mostrar_) -> (concurso, username / email), podemos evitar la proliferación de usuarios sintéticos, los errores de cambios de nombre entre concursos relacionados (`OMIPS2017-GUA-1` es una persona distinta en el selectivo que en la final), y le permite a los usuarios conservar sus envíos una vez terminado el concurso.

## Documento de diseño

https://docs.google.com/document/d/1COTwqOYNvuYER5jkeKZWJXxSdVn_2X-CjoDolmEiQ1Y/edit#

**Comment by pacharrin** [comment]
Qué tan factible es tener este listo para antes de Febrero?

**Comment by lhchavez** [comment]
welp, no mucho :( ocuparíamos mucha ayuda.

**Comment by alanboy** [comment]
Feature: Refactor de Identidad  -- SPEC?
	* Partir el problema en 2
	* HAcer el spec del problema que resuelve usuarios autogenerados
	* No es el feature en si solo el spec.

**Comment by lhchavez** [comment]
Design doc listo! @elendil326 me puedes echar la mano haciendo sub-issues para esto?

**Comment by pabo99** [comment]
Para terminar este issue faltan tres cosas:

- Issue #2910 Eliminar campos duplicados en la tabla `Users`. Ya está en revisión el PR #2915 
- Issue #2664 Ya se agregaron la mayor parte de las pruebas en selenium, sólo faltan las pruebas de las restricciones. Ya está en revisión el PR #2749 
- Issue #2667 Apagar el experimento de `Identities`. Esto se podrá hacer hasta cerrar los issues anteriores o quizás después de que se comience a usar.

**Comment by pabo99** [comment]
Parece que ya esstán concluidas las tareas para el refactor de identidad:

> * Issue #2910 Eliminar campos duplicados en la tabla `Users`. Ya está en revisión el PR #2915
Ya se aprobó el Pull Request.
 
> * Issue #2664 Ya se agregaron la mayor parte de las pruebas en selenium, sólo faltan las pruebas de las restricciones. Ya está en revisión el PR #2749
Ya se aprobó el Pull Request.

> * Issue #2667 Apagar el experimento de `Identities`. Esto se podrá hacer hasta cerrar los issues anteriores o quizás después de que se comience a usar.
Este experimento se puede quitar después de que usuarios hayan utilizado el feature.

¿Ya se puede cerrar este issue?

**Comment by lhchavez** [comment]
sí, ya hasta se prendió en producción :O
