### ISSUE TITLE
CIIC: OmegaUp no permite enviar una solución si la hora local de la PC indica que la competencia terminó

### ISSUE THREAD

**Issue by elsantodel90** [omegaup/omegaup#1302]
Se debería utilizar para todo la hora central del server.

En cambio si la hora local de la PC está mal (en el futuro por ejemplo), se muestra tiempo disponible 0 y no se puede enviar.

Si en cambio la hora local está en el pasado, se muestra que el concurso no empezó y "falta mucho para que empiece".

Manifestado durante CIIC 2017 (argentina).

Ambiente: Firefox 48.0 , sobre una máquina virtual xubuntu 16.04 de 32 bits.

**Comment by lhchavez** [comment]
había una confusión entre los dos clock sources: la hora local y la hora remota. se estaba haciendo doble ajuste en el caso de las horas locales y eso estaba causando un montón de problemas.

la solución fue convertir todo a la hora local (que era la intención originalmente).
