### ISSUE TITLE
Los pre-upload hooks no validan que los archivos de internacionalización hayan sido regenerados

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1319]
Es hora de convertir `i18n.py` en un validador/arreglador de verdad.

**Comment by pabo99** [comment]
Queda pendiente la manera de solucionarlo

**Comment by pabo99** [comment]
@lhchavez: por lo que entiendo, hay que agregar un método en el archivo `linters.py` que haga lo que está haciendo actualmente el archivo `i18n.py`. ¿Es correcto?
