### ISSUE TITLE
java.io.BufferedReader#close() causa un RuntimeException

### ISSUE THREAD

**Issue by luis-avina** [omegaup/omegaup#1325]
Al realizar un envío de código en Java, si hago uso de

`BufferedReader input = new BufferedReader(new InputStreamReader(System.in));`

Está generandose un error al momento de cerrar el `BufferedReader`

Ejemplo

```java
import java.io.BufferedReader;
import java.io.IOException;

public class Main {
  public static void main(String args[]){
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    input.close(); // Esto genera un RuntimeException
  }
}
```

<img width="1329" alt="screen shot 2017-06-21 at 17 37 22" src="https://user-images.githubusercontent.com/1093224/27409666-4f26ad04-56a8-11e7-8063-c9a6b9f7d591.png">

**Comment by lhchavez** [comment]
Listo, ya encontré qué lo causa: cuando Java cierra `System.in`, silenciosamente lo [redirige](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/solaris/native/java/io/io_util_md.c#l117) a `/dev/null`, y no estamos permitiendo el acceso a este archivo en el sandbox.
