### ISSUE TITLE
EDU: [Promotion/Demotion queue] Hacer la ventana "peer review" dismissible.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1342]
La ventana actualmente tiene un botón para el usuario pueda decir que no quiere recomendar el problema, pero cuando se actualiza la página vuelve a aparecer el mismo mensaje.

Idealmente el mensaje debería de desaparecer para siempre cuando se hace clic en "no" y tal vez aparecer un botón pequeño en el cuerpo del problema que diga "recomendar problema a otros usuarios" que haga que reaparezca la ventana.

También debería de ser más pequeña la ventana. Actualmente ocupa una gran porción de la pantalla y su contenido es muy pequeño:
![image](https://user-images.githubusercontent.com/597815/28128926-3919da74-66e6-11e7-8880-b9484845faaa.png)

**Comment by lhchavez** [comment]
se aceptan pull requests :)

**Comment by heduenas** [comment]
@tvanessa está en eso ;)
