### ISSUE TITLE
Short title (alias) unintuitive without hovering over info icon

### ISSUE THREAD

**Issue by tiqtok** [omegaup/omegaup#1343]
As a person who feels confident in my own ability to fill out a web forms and who hesitates to use info tools, I would like to rely on my own intuition when using an application.  

##Steps to reproduce

1. Entered "Short Title Alias " into "Short title (alias)"

Error returned - Parameter can only contain letters, digits, and _.: alias

Does not indicate "Spaces not allowed" or something specific to the error. 

![image](https://user-images.githubusercontent.com/15961789/28137071-d11d37c0-6700-11e7-99e5-39b8adeec77d.png)

**Comment by lhchavez** [comment]
Esto necesita una actualización de `parameterInvalidAlias` en `frontend/templates/*.lang`
