### ISSUE TITLE
Error Message does not match respective Form Title

### ISSUE THREAD

**Issue by tiqtok** [omegaup/omegaup#1344]
Did not fill out "Title" but error message indicates "Empty parameter.: name"

![image](https://user-images.githubusercontent.com/15961789/28137170-29698e06-6701-11e7-9768-6af7db1e2778.png)

**Comment by lhchavez** [comment]
Esto necesita cambiar https://github.com/omegaup/omegaup/blob/eceb4ddea02ce0f915c2a5372410d6a2b0d2bc26/frontend/www/js/omegaup/components/course/Details.vue#L12 por `wordsName`
