### ISSUE TITLE
Exponer el país de las escuelas en el Ranking

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1345]
Como cualquier tipo de usuario (no loggeado), quiero saber a qué país pertenece una escuela.

**Comment by MiguelRomero** [comment]
Podemos agregar un campo de país para la escuela no? Ya existe? Y si no existe puedo crearlo? así sería facil hacer una llamada directa a la api (No se si tenemos api) donde me regrese el dato y pintar en una imagen la bandera dependiendo de lo que me regrese ya sea MX, etc. cambiar el src de esa etiquetita de imagen a la de la bandera en storage.

**Comment by lhchavez** [comment]
ya existe: https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L581

**Comment by lhchavez** [comment]
La banderita se puede renderear usando https://github.com/omegaup/omegaup/blob/82facadafdd44ad39b6885343484dbf5dfcb3c2d/frontend/www/js/omegaup/ui.js#L215, tal vez haya que modificar los Controllers para que regresen los códigos de países. Por ejemplo https://github.com/omegaup/omegaup/blob/09d4b9f120d3ce192a4da228575eca386d741b14/frontend/server/controllers/SchoolController.php#L34 y https://github.com/omegaup/omegaup/blob/bd9145f6026912397f3fc106e9143d4434e65d18/frontend/server/libs/dao/Schools.dao.php#L57 , pero no se dónde más haya que agregarlo.

**Comment by pabo99** [comment]
Pregunta: ¿Dónde puedo ver este Ranking de escuelas? Sólo logro ver el Ranking de usuarios, y estos ya cuentan con la bandera correspondiente a su país.

**Comment by lhchavez** [comment]
En el homepage: https://omegaup.com/ acá está en los templates https://github.com/omegaup/omegaup/blob/1687c5db6bda30fae2b07af120aa43acb48cb15f/frontend/templates/index.tpl#L35-L46 y acá en los Vue https://github.com/omegaup/omegaup/blob/172636e12e910661aa82a9462ddcd22b60655297/frontend/www/js/omegaup/components/schools/Rank.vue
