### ISSUE TITLE
La tabla en https://omegaup.com/rank/ ya no muestra la columna Solved Problems

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1346]
## Comportamiento Esperado
La tabla del ranking mostraba una columna con el número de problemas resueltos.

## Comportamiento Actual
![image](https://user-images.githubusercontent.com/207097/28236650-e49adc72-68df-11e7-8ba3-3223687bc14e.png)

## Posible Solución
Sospecho que fue el upgrade a bootstrap. De paso, la tabla en el index perdió el borde en la derecha:
![image](https://user-images.githubusercontent.com/207097/28236658-08852d9a-68e0-11e7-91c9-30c4242a3ab8.png)

**Comment by samdsmx** [comment]
Esto ya se puede cerrar...

**Comment by pabloaguilar** [comment]
Fixed in #1381
