### ISSUE TITLE
Verification email currently in Spanish

### ISSUE THREAD

**Issue by tiqtok** [omegaup/omegaup#1347]
# Bug

## Comportamiento Esperado

*Cuando un usuario hace una cuenta nueva en Omegaup, deben de recibir un email de verificacion con instruciones en Ingles. 

## Comportamiento Actual

*Cuando un user hace una cuenta nueva, reciben el email de verification con texto en Español. Para un miembro de LEAP, esto se parece raro por que van estar esperando instruciones en Ingles*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Usuarios hacen una cuenta nueva.
2. Reciben email de verificacion con texto en Español. 

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): NA 
* Sistema Operativo y versión (escritorio o móbil): NA
* Link al sitio en el que este problema pasa: NA
* Captura de pantalla:

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1221
