### ISSUE TITLE
Como un concursante, quiero poder ver en qué concursos estoy participando

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1353]
## Comportamiento Esperado

al iniciar sesión, poder ver en la pagina principal los concursos en los que estoy participando

## Comportamiento Actual

tener que entrar a arena y recordar qué nombre tenía tal concurso

**Comment by pabo99** [comment]
Al iniciar sesión, se muestra un listado de Próximos concursos en la página principal. ¿Cual sería la diferencia con el que ya existe?

**Comment by lhchavez** [comment]
próximos concursos son concursos públicos en los que _puedes_ participar. la diferencia es que quieres los concursos donde ya eres participante.
