### ISSUE TITLE
Cuando intento mandar una clarificación al curso, de pronto la ventana donde escribes la pregunta se cierra y no se envía

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1354]
"Buenas Noches Rodolfo,
Nomas queria preguntarte que algo raro pasa con el sistema de clarificaciones. Cuando intento mandar una clarificación al curso, de pronto la ventana donde escribes la pregunta se cierra y no se envía. Para asegurarme de que fuera un problema con el evaluador y no con mi maquina, le pregunte a otros competidores y tienen el mismo problema. Que procede?"

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1419
