### ISSUE TITLE
Agregar visualizacion de progreso

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1355]
* Quiero ver graficas de progreso para tanto estar informado como para usarlo de motivacion

## Comportamiento Esperado

Que un usuario pueda ver su grafica de progreso con respecto al tiempo. Es decir, problemas resueltos (o todas las clasificaciones, realmente) como un stacked bar chart por unidades de tiempo personalizable. Por ejemplo, algo como:
Por meses;
2017-01 => 5 AC | 5 TLE | 10 WA (un mes normal)
2017-02 => 1 AC | 0 TLE | 1 WA (lento por inicio de clases)
2017-03 => 20 AC | 10 TLE | 30 WA (entrenando para un concurso en abril)

## Comportamiento Actual

La vista de perfil que tenemos ahorita muestra mi progreso (o interacciones con el sistema) en este preciso momento. Este feature request es para mostrarlo a traves del tiempo.

## Contexto

Creo que una visualizacion de "que tan activo he estado?" y "que tanto he avanzado?" puede servir como motivacion para algunos usuarios.

**Comment by alanboy** [comment]
+1!! 


Algunas ideas:
![image](https://user-images.githubusercontent.com/527987/28810660-c3e0c4fc-763f-11e7-892f-f609a6757931.png)

![image](https://user-images.githubusercontent.com/527987/28810672-d972fa56-763f-11e7-9045-61ed3366b0eb.png)

**Comment by pabloaguilar** [comment]
Esta es la idea que yo tenia en mente:
https://docs.google.com/a/omegaup.com/spreadsheets/d/15ZRx1AJnBNaKap2dZjfi207bSRxqz6L0_DKcQMyRQGo/edit?usp=sharing

Delta:
![image](https://user-images.githubusercontent.com/189223/28811052-bdb03ec6-7641-11e7-98f3-12209e0fd765.png)

Cumulativo:
![image](https://user-images.githubusercontent.com/189223/28811069-d3c91cfa-7641-11e7-9d90-ec2e1098a32e.png)

**Comment by sandyAL** [comment]
+1
Me parece genial la idea, incluso podríamos combinarla con las medallas, para que el usuario pueda ver que tanto le falta para alcanzar alguna medalla o si sigue el mismo ritmo en cuanto tiempo podría alcanzar los siguientes niveles.

**Comment by elendil326** [comment]
@npave puedes hacer un bosquejo o dar guidelines de donde poner las gráficas en la página del perfil. Podemos mantener el scope de este escenario a las métricas que Pablo puso en el archivo de google drive. Después podemos agregarle más features como las medallas y demás.

**Comment by npave** [comment]
Sería excelente que pudiéramos actualizar la página del perfil del usuario ya que andamos aquí, esta es mi propuesta. La idea es que las gráficas de este issue queden en el bloque de "Stats".

![issue 1355](https://user-images.githubusercontent.com/940007/31001133-54cc3ab2-a496-11e7-8f49-46538722251b.png)

En el bloque de "Stats", estuve platicando con @pabloaguilar sobre su idea y llegamos a la propuesta que dejo enseguida.  El usuario puede elegir el tipo de gráfica que desea ver, tiene tres opciones (_radioButton_): Delta, Cumulativo, Total. Además puede elegir de una lista (_comboBox_) los veredictos que desea ver en la gráfica. Otra opción que tiene el usuario es elegir los bloques de tiempo como quiere ver su información, tiene cuatro opciones: día, semana, mes, año. Por ejemplo, si elige por día, se desplegará los veredictos que ha obtenido el usuario cada día desde que inició a participar en omegUp hasta la fecha. Si elige por semana se verá la información agrupada por semana y así sucesivamente.

![graficaveredictos](https://user-images.githubusercontent.com/940007/31004483-74c26a7c-a4a9-11e7-9880-a4a3579df3d4.png)

Finalmente, le pedí al comité de media que nos ayudara a crear una paleta de colores que defina mejor cada veredicto. Agrego esta información una vez que la tenga.

**Comment by elendil326** [comment]
@lhchavez puedes ponerle la prioridad?

**Comment by elendil326** [comment]
@pabo99 para revisar esquema de base de datos para ver si se tiene que hacer algún cambio ahí para soportar esto con mayor facilidad o si es solo un cambio en la UI. Después, cambiará el infinito por un estimado. Después, @lhchavez asignará prioridad

**Comment by pabo99** [comment]
Veo que no es necesario hacer cambios en el esquema de base de datos, sólo es cuestión de definir los queries y los cambios en la UI.

**Comment by pabo99** [comment]
@lhchavez ¿nos puedes ayudar con la prioridad de este issue?

**Comment by elendil326** [comment]
Blocked by #1605
