### ISSUE TITLE
SD: P1 API para crear/editar contenidos.

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1364]

**Comment by Fer-OmegaUp** [comment]
Los cursos son una coleccion de problemas, un problema ''gratis" que solo es de lectura para la descripcion
ahorita no hay manera de deshacer o crear contenidos  (texto intermedio que va entre problema y problema)

**Comment by Fer-OmegaUp** [comment]
Esto depende de que este feature este completo, cambiando prioridad: https://github.com/omegaup/omegaup/issues/1361

**Comment by Fer-OmegaUp** [comment]
@frcepeda puedes dar status en este item?
