### ISSUE TITLE
[FEATURE] Hacer 3 cursos públicos

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1368]
Básico de programación - merge entre LEAP & Coding Rush, quizás hasta recursión?
Aprende Karel - básico para OMIPS
Stretch goal: OMI básico, podemos tomar problemas de la categoría bronze o problemsets fáciles de años pasados.

**Comment by tvanessa** [comment]
![Screen Shot 2020-06-20 at 5 51 17 PM](https://user-images.githubusercontent.com/13296248/85214407-aeb96d80-b31e-11ea-92c2-5c79546e64c6.png)
