### ISSUE TITLE
(Controller) Hacer problema privado

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1374]
API para hacer problema privado cuando un reviewer decide que un problema reportado es inapropiado.

**Comment by heduenas** [comment]
Un reviewer ya puede hacer privado el problema con el API de problems (gracias a https://github.com/omegaup/omegaup/pull/1162) solo falta notificar al usuario.

**Comment by alanboy** [comment]
Pull request pendiente : https://github.com/omegaup/omegaup/pull/1384

**Comment by lhchavez** [comment]
Ese pull request no resuelve este issue porque no notifica al usuario.

**Comment by lhchavez** [comment]
Se separó la notificación a https://github.com/omegaup/omegaup/issues/1458 para poder cerrar la mitad de este issue.
