### ISSUE TITLE
El ambiente de desarrollo deberia incluir un administrador de BD

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1375]
*En el caso de un feature, provee un título en el siguiente formato:*

*Como un dev, quiero ver datos y editar campos   para no tener que hacerlo desde la consola mientras desarrollo en omegaUp.

puede ser pma, http://phpminiadmin.sourceforge.net/ o similar

**Comment by lhchavez** [comment]
Hay que hacer esto en github.com/omegaup/puppet

**Comment by lhchavez** [comment]
Uno de los chamacos de GSoC ocupaba esto entonces me lo aventé.
