### ISSUE TITLE
[BUG] 3 out of 14 users were unable to be added to course after they created an account.

### ISSUE THREAD

**Issue by tiqtok** [omegaup/omegaup#1382]
## Comportamiento Esperado

As a user who signs up, I expect to be able to be assigned to a course once my email is provided to an administrator. 

## Comportamiento Actual

Three out of 14 users who signed up for leap were unable to be assigned to the course because their usernames or emails did not show up despite various attempts when I tried adding them to the course. Some of them ended up having to create a new account in order to be added. 

tomchang93@gmail.com (toma)

santiti28@gmail.com (santiti28)

v-cagrac@microsoft.com (carla)

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

1. Have users create new accounts. 
2. Try to add them to a course - most will work. Some will not. Reason is unknown. 

https://omegaup.com/course/C_sharp_intro_1/assignment/c_sharp_functions#problems

**Comment by pabloaguilar** [comment]
Was there no error message shown whatsoever?

**Comment by tiqtok** [comment]
When trying to add the user, their username and email (searched for separately) did not appear in the list of usernames to choose from. The error message was something like no username / email exists, or something like that.

**Comment by pabloaguilar** [comment]
My first guess is that they hadn't activated their accounts. I tried with `toma` and I stil don't see them in the UI.
@lhchavez @joemmanuel @alanboy can any of you help me verify this theory?

**Comment by lhchavez** [comment]
`toma` has been verified :( so is the API returning an empty result?

**Comment by pabloaguilar** [comment]
I think it's the same issue we've had in the past, where if one doesn't select an entry from the autocomplete list, the request is sent with an empty field.
For `toma` in particular, there are enough suggestions with that substring already that their user name is probably beyond the max number of suggestions.
I'll take a look.. again.. that autocomplete thing keeps coming up with creative ways of breaking

Note that the above explanation covers `carla` and `toma` but not `santiti28`. Is the latter also verified?

**Comment by tiqtok** [comment]
@pabloaguilar It's difficult to say at this point, but I can see if the user will be willing to look into that. As far as I remember I tried making sure that everyone was verified if they were having trouble.

**Comment by lhchavez** [comment]
We'll update the Typeahead library in https://github.com/omegaup/omegaup/pull/1676, maybe it will be fixed by it.

Once that's done, we'll update this thread to see if it's still reproducible.

**Comment by heduenas** [comment]
Does this still repro?
