### ISSUE TITLE
Como maestro, Me gustaría tener la opción de poder crear un curso en omegaup for schools donde pueda ser administrado por varios maestros

### ISSUE THREAD

**Issue by LaloRio** [omegaup/omegaup#1397]
## Contexto
Hola que tal, dentro de la escuela donde trabajo en la ciudad de chihuahua vemos un bloque con temas sobre karel el robot y me gustaría poder realizar un curso donde lo pueda compartir con mis compañeros que no están muy involucrados con la programación y la plataforma para que puedan utilizarlo. La idea seria yo crear todo el curso y hacer administradores a los maestros para que ellos puedan crear su grupo con sus alumnos y ellos trabajen con ellos sin la necesidad de que nos empalmemos todos dentro del mismo curso. les dejo mi correo por si hay alguna duda. laloriora@gmail.com asesor de la OMI en chihuahua

**Comment by pabloaguilar** [comment]
Para ver si entendi correctamente:
Quieres crear el contenido del curso una vez y que otros maestros puedan usar el mismo contenido en grupos distintos, manteniendo puntajes y progreso separado por grupo. Correcto?

Ese feature estaba planeado utilizando clones. Es decir, se crea el curso una vez, y se crean multiples clones, uno por cada grupo que lo vaya a tomar. El detalle es que una vez creada la copia los cursos se "desconectan", es decir, los cambios en cualquiera de ellos (en particular, en el original) no se ven reflejados en ninguno de los demas grupos. @LaloRio Es aceptable esta funcionalidad para tu caso de uso?

**Comment by LaloRio** [comment]
si es exactamente eso, suena genial!
