### ISSUE TITLE
Error al correr yarn run dev

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1402]
Al paracer algunos vue files estan reportando error..
![screenshot 2017-08-27 12 34 34](https://user-images.githubusercontent.com/5838427/29753340-6f4342c2-8b24-11e7-95d0-9bacc1fd585f.png)

**Comment by lhchavez** [comment]
Están super raros tus paths. En ningún lugar del path deberían haber `!`, y el hecho de que tengas un `./~/` me hace sospechar que tu ambiente de desarrollo se hizo de manera no-estándar.

cómo llegasta a esa situación? puedes destruir la máquina virtual y volverla a crear?

**Comment by lhchavez** [comment]
Cerrando este issue como no-repro. Creé una VM Xenial desde cero hace rato y no me topé con esto.
