### ISSUE TITLE
Sincronia del top5 y top100 del rank de escuelas

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1403]
El rank de escuelas top100 se actualiza mientras que el top5 no.

**Comment by lhchavez** [comment]
Puedes dar un poco más de información para poder arreglar esto? Tienes un bosquejo de cómo se deberia resolver?

**Comment by samdsmx** [comment]
EL problema lo presencie en mi ambiente de desarrollo, Genero usuaarios con escuelas y empiezo a subir AC con ellos, y me percato que la tabla del top5 de eescuelas en el homepage no se actualiza. Mientras que    ingresando a la tabla general top100 si aparecen los resultados. Vease, que si se estaba actualizando la tabla del top5 de usuarios.
