### ISSUE TITLE
Posibilidad de volver a ser Coder del Mes despues de 1 año de haber ganado.

### ISSUE THREAD

**Issue by JuanM97** [omegaup/omegaup#1404]
Para darle la posibilidad a Coders del Mes anteriores de ser premiados gracias al programa de Mentores, necesitamos hacer posible que cualqueir usuario tenga la posibilidad de ser coder del mes multiples veces, cumpliendo la siguiente condicion:
 * Una vez que un usuario sea coder del mes, no puede volver a recibir ese reconocimiento durante los siguientes 12 meses.

**Comment by lhchavez** [comment]
La solución sería cambiar esta condición https://github.com/omegaup/omegaup/blob/bd9145f6026912397f3fc106e9143d4434e65d18/frontend/server/libs/dao/Coder_Of_The_Month.dao.php#L63 por algo así como `cm.user_id IS NULL OR "diferencia entre la fecha actual y la fecha del coder del mes supera un año"`.
