### ISSUE TITLE
El juez de C# utiliza mucha más memoria que lo esperado

### ISSUE THREAD

**Issue by flabordec** [omegaup/omegaup#1407]
## Comportamiento Esperado

Tengo el siguiente programa de C# para resolver [este problema]( https://omegaup.com/arena/problem/Repository-Management-Tool/#problems)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

class OmegaUp_RepositoryManagementTool
{
	static void Main(string[] args)
	{
		var packages = new HashSet<string>();
		string[] splitLine;
		int n = int.Parse(Console.ReadLine());
		
		for (int i = 0; i < n; i++)
		{
			splitLine = Console.ReadLine().Split(' ');
			int packageCount = Convert.ToInt32(splitLine[1]);
			for (int j = 0; j < packageCount; j++)
			{
				string package = Console.ReadLine();
				packages.Add(package);
			}
		}

		var orderedPackages = packages.OrderBy(
			s =>
			{
				string[] split = s.Split(' ');
				string name = split[0];
				int version = Convert.ToInt32(split[1]);
				return new Tuple<string, int>(name, version);
			});
		Console.WriteLine(string.Join("\n", orderedPackages));
	}
}
```

El juez reporta el uso de memoria como 40 MB, pero correrlo en mi computadora (usando el .NET Framework 4.5.2) usa 15 MB (probé en modo debug y release para ver si eso hacía diferencia y básicamente no).

## Comportamiento Actual

El juez reporta que la cantidad de memoria usada son 40 MB.

## Posible Solución

Supongo que esto tiene que ver con qué interprete se esté usando. Si tuviera que adivinar, esto podría resolverse más o menos fácil migrando a .NET Core ¿quizás?

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Ir a [este problema]( https://omegaup.com/arena/problem/Repository-Management-Tool/#problems)
2. Submittear el código que pegué arriba
3. Ver que el uso de memoria es de 40 MB
4. Correr lo mismo en Visual Studio
5. Ver que el uso de memoria es ~15MB

## Contexto

*Mi workaround actual es nada más duplicar la cantidad de memoria máxima que puede utilizar el juez. En general me gustaría hacer los límites más pequeños para no abusar del juez. 

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome 60.0.3112.101 (Official Build) (64-bit) (cohort: Stable)
* Sistema Operativo y versión (escritorio o móbil): Windows 10 (Build 10240) escritorio 
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/Repository-Management-Tool/#problems

**Comment by lhchavez** [comment]
Ya estamos usando .NET Core :( pero estamos usando la versión 1.4 en vez de la 2.0 que acaba de salir de Beta. Vamos a migrarnos a esa versión pronto, así que podremos ver qué tanto mejora.

**Comment by lhchavez** [comment]
Pues aún con .NET Core seguimos reportando más de los 15MB que reporta Visual Studio. Supongo que porque en Windows todas las librerías de .NET ya están pre-cargadas y compartidas con el resto del sistema operativo hace que naturalmente el equivalente del resident set size sea más bajo. También no descarto que haya diferencias de implementación por aquí y por allá que causen / empeoren las diferencias entre sistemas operativos.

Habiendo dicho eso, hice un pequeño cambio para _no_ contabilizar la memoria de la máquina virtual para fines de envíos, lo cual baja la memoria que se reporta en ese problema a ~20MB. Supongo que eso es lo más que vamos a poder bajarlo sin ayuda de msft :(
