### ISSUE TITLE
No sé puede entrar a un curso

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1411]
> Una nueva pregunta ha sido realizada por ______:
> 
> No puedo visualizar mi curso creado, me dice que no encuentra la página
> 
> No puedo visualizar mi curso creado, me dice que no encuentra la página. El link es el siguiente: https://omegaup.com/course/1OTI-ES17

**Comment by alanboy** [comment]
https://m.facebook.com/story.php?story_fbid=1817759701597796&id=177965472243902&comment_id=1818101684896931&notif_t=feed_comment&notif_id=1504061558023704&ref=m_notif

**Comment by lhchavez** [comment]
FWIW nunca hemos soportado eliminar cosas. Hay que decidir qué hacer con
todos los datos enlazados (llaves foráneas y así).

**Comment by lhchavez** [comment]
Arreglado con https://github.com/omegaup/omegaup/commit/b48c7ef6672a75f1161625d7aa95becfaa122fb2
