### ISSUE TITLE
Cuando un usuario hace demotion a un problema se convierte en reviewer del mismo automáticamente.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#1412]
Al momento de que un usuario hace demotion a un problema, el usuario se hace reviewer del problema y puede decidir conservarlo o suspenderlo.

Añadiendo imagen del bug:

![image](https://user-images.githubusercontent.com/6158469/29886522-f4098d1a-8d7f-11e7-8988-d4c2f91f1add.png)

**Comment by pabo99** [comment]
Anteriormente sólo se verificaba si el tipo del problema reportado era 'demotion' para mostrar los botones de acciones. Ahora también se validará que el usuario sea reviewer.

Los botones se encuentran en el archivo: frontend/www/js/omegaup/components/qualitynomination/Details.vue

El controlador es el siguiente: frontend/server/controllers/QualityNominationController.php y el método donde se agrega la propiedad 'reviewer' es apiDetails
