### ISSUE TITLE
No se puede añadir usuario a un curso o concurso de omegaup.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#1413]
El usuario "Luis_Fernando" no puede ser añadido a un curso de OmegaUp o a algun concurso.

**Comment by pabo99** [comment]
Hay que revisar si esto sucede en todos los concursos o sólo fue un caso especial

**Comment by pabo99** [comment]
La forma de revisar es crear un usuario con un (_) y tratar de agregarlo en un concurso
