### ISSUE TITLE
Desactivar link de clarificaciones en OfS mientras no funciona

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1419]
Tenemos un par de reportes:
https://github.com/omegaup/omegaup/issues/1354
y
https://omegaup.com/preguntas/1181/problema-con-clarificaciones-en-omegaup-escuelas
De que clarificaciones no funciona. Y lo deberiamo simplementar, pero mientras, deberiamos esconder el boton para evitar confundir a mas personas.

**Comment by lhchavez** [comment]
Esta línea https://github.com/omegaup/omegaup/blob/bd9145f6026912397f3fc106e9143d4434e65d18/frontend/templates/arena.contest.tpl#L24 necesita un `showClarifications` así como todas las demás opciones. Se debe hacer algo así como https://github.com/omegaup/omegaup/commit/851a6c3f5dc262bda2e34cd2f6ceafd5f2d09d76 donde `showClarifications` debe ser `true` en todos lados excepto en https://github.com/omegaup/omegaup/blob/9422198a0d1da1b9622c71b19ce0ad2a93a6a006/frontend/www/course.php#L53
