### ISSUE TITLE
La apiCoderOfTheMonth me devuelve un error cuando no encuentra coder del mes

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1427]
Al ejecutar las pruebas de coder del mes me percaté de que al no encontrarse un coder del mes, la API manda un error de `parameterInvalid`, el cual no se debería de arrojar.

**Comment by pabo99** [comment]
Duda, al no encontrar coder del mes,  ¿Que dato es el que podemos mandar como respuesta?

**Comment by lhchavez** [comment]
si no hay coder del mes, lo más apropiado es regresar algo que represente la ausencia de coder del mes. `null` es la única opción.
