### ISSUE TITLE
Hay concursos futuros listados en "Concursos actuales" en /arena/

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1433]
![image](https://user-images.githubusercontent.com/527987/30360918-0dd3e9fa-9809-11e7-83bf-c9cbcca3e282.png)

**Comment by lhchavez** [comment]
reabriendo porque dejamos un `TODO` para la interfaz

**Comment by pabo99** [comment]
¿En que consiste el cambio de la interfaz?

**Comment by lhchavez** [comment]
Agregar una pestaña nueva para los concursos futuros

**Comment by pabo99** [comment]
Hice push de estos cambios, pero creo que ya se había cerrado el pull request. ¿Que es lo correcto en estos casos?

**Comment by lhchavez** [comment]
lo reabrí. haz otro pull request con este mismo issue.
