### ISSUE TITLE
(Calidad) No mostrar 'dismissal' ni 'suggestion' en https://omegaup.com/nomination/

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1447]
Los dismissals y suggestions están siendo mostrados en la lista de nominaciones, pero no deberían:
https://omegaup.com/nomination/

Tampoco mostrar los que ya estan resueltos

**Comment by elendil326** [comment]
Esto es quitarlos de la lista para siempre o permitir al ususario mostrarlos o no mostrarlos mediante un check box? @heduenas @npave

**Comment by heduenas** [comment]
Quitarlos definitivamente. No veo razones por las cuales querriamos mostrar los suggestions o los dismissals a los usuarios o a los reviewers. Ya estoy trabajando en este issue.
