### ISSUE TITLE
(Calidad) Clarificar el botón de Show all nominations en https://omegaup.com/nomination/

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1448]
El botón de Show all nominations debería de mostrar (e.g. en un tooltip) cuál es su funcionalidad
https://omegaup.com/nomination/

**Comment by elendil326** [comment]
Tienes un ejemplo de que podría decir en el tooltip?

**Comment by Fer-OmegaUp** [comment]
Hay que investigar quien puso el boton y asignar este item a la persona

**Comment by alanboy** [comment]
![image](https://user-images.githubusercontent.com/527987/32082867-617622c6-ba73-11e7-8860-f295d35ec61b.png)

**Comment by alanboy** [comment]
@elendil326 no sabemos nosotros tampoco, por eso el bug :) 

@pabloaguilar recuerdas para que es esto?

**Comment by pabloaguilar** [comment]
Creo que era para cambiar entre "la nominaciones que tengo pendientes de
revisar" y "las nominaciones que hay en el sistema"

**Comment by heduenas** [comment]
Parece que más bien es para cambiar entre "mis nominaciones" y "las nominaciones de cualquier usuario":
https://github.com/omegaup/omegaup/blob/64c5ee6709fbedd5cca7ce84d0774cbfea6d3de3/frontend/www/js/omegaup/components/qualitynomination/List.vue#L68
