### ISSUE TITLE
(Calidad) Invertir el orden de la lista de nominaciones en https://omegaup.com/nomination/

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1449]
La lista de nominaciones se está mostrando en orden cronológico con las más antiguas hasta arriba. Necesitamos invertir el orden.
https://omegaup.com/nomination/

**Comment by elendil326** [comment]
No sería mejor habilitar el ordenamiento por encabezado en la tabla? @heduenas @npave @lhchavez

**Comment by Fer-OmegaUp** [comment]
Mas que mostrar en orden cronologico deberia de mostrarte los que ya se resolvieron

**Comment by alanboy** [comment]
Cerrando para hacer esto mismo en #1447
