### ISSUE TITLE
(Calidad) No se están mostrando los campos correctos de contents en nomination Details

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1450]
En https://omegaup.com/nomination/[nomination id]/ no se está mostrando correctamente el campo de contents que contiene todo el input del usuario.
Necesitamos investigar si se está guardando en lo absoluto en la base de datos. Si no, es urgente arreglarlo.

**Comment by alanboy** [comment]
Es posible que se este perdiendo la informacion que los usuarios nos dan :/

**Comment by pabo99** [comment]
Revisando el código, no se está perdiendo la información. La pregunta es, ¿que información se debe mostrar? Ya que actualmente se arma un array con los siguientes datos: 
`statement`, `source` y  `tags`. No se incluye el input del usuario.

**Comment by elendil326** [comment]
ping @heduenas @npave para responder la pregunta de Juan Pablo

**Comment by heduenas** [comment]
Cuando el tipo de nominacion es 'suggestion' debe de haber:
* 'quality'
* y/o 'difficulty'
* y/o 'tags'

Cuando el tipo de nomiancion es 'demotion' debe de haber:
* 'reason'
* y opcialmente 'rationale'

**Comment by Fer-OmegaUp** [comment]
Esto esta bloqueando el feature de demotion para calidad

**Comment by Fer-OmegaUp** [comment]
@galloska puedes asignarte este item y ayudarnos a investiga :En el issue dice Juan Pablo que se encuentra está armando un arreglo con los campos de contents que se van a mostrar. Hay que cambiar esa lista de campos para que incluya los datos relevantes para las sugerencias. O tal vez sería mejor simplemente regresar todo el contenido de 'contents' crudo.
