### ISSUE TITLE
El correo de recuperación de contraseña tiene caracteres inválidos

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1452]
![image](https://user-images.githubusercontent.com/527987/30847281-c9756c9c-a24f-11e7-9921-3fe6d1d71220.png)

También debería ser omegaUp, no OmegaUp.

**Comment by rcxr** [comment]
"clic" es la forma correcta de escribirlo en español ([RAE: click](http://dle.rae.es/?id=9SZ4Kat)) 
+1 a arreglar OmegaUp!

**Comment by lhchavez** [comment]
Falta ponerle bien el encoding a https://github.com/omegaup/omegaup/blob/master/frontend/server/controllers/ResetController.php#L11
así como en https://github.com/omegaup/omegaup/blob/9ca8107cb039646dee8afc8640a9c2795b6cb942/frontend/server/controllers/UserController.php#L317
