### ISSUE TITLE
La última actualización del sistema operativo hizo que los problemas con límite de <8MB memoria ya no puedan cargar libc.so.6

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1455]
## Comportamiento Actual
De un usuario de omegaUp:
> Creo que hay un problema con el evaluador
> Reenvié soluciones que antes daban 100 y ahora dan 0 pts con error de ejecución
> Los problemas son IOI 1994 - Los relojes y IOI 1994 - El castillo

Links a problemas:
[IOI 1994 - El Castillo](https://omegaup.com/arena/problem/IOI-1994---El-Castillo#problems)
[IOI 1994 - Los Relojes](https://omegaup.com/arena/problem/relojes#problems)

**Comment by rcxr** [comment]
Se le solicitó al usuario su usuario y ids de envíos para continuar la investigación ❓

**Comment by kishtarn555** [comment]
Castillo
-668dd14044be86c176a298c5b9ed09b8
-fb9b4b1f6f5f90733077b1e78bb9fede     
Los relojes
-edc702624b19a083834422c35d6d033c    
-e1c60c8f6f9a186889be3ef6e31feb0a

**Comment by lhchavez** [comment]
los límites de memoria de ese problema son muy bajos y el solo hecho de intentar cargar la librería de C está haciendo que se termine la memoria.

creo que hay que relajar un poco los límites.
