### ISSUE TITLE
Restaurar correctamente visibilidad de problema al des-bannear.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1456]
Guardar visibilididad del problema antes de bannear y restaurarla cuando se des-bannea un problema.

Actualmente estamos convertiendo a los problemas desbaneados en "PRIVADOS" independientemente de su visibilidad antes de ser banneados.

**Comment by Fer-OmegaUp** [comment]
@heduenas, si lo convertimos a privado significa que el creador aun puede verlo y editarlo, correcto? puede cambiar otra vez de privado a algo mas?

**Comment by Fer-OmegaUp** [comment]
@pabo99 ya estas haciendo tu este issue? vi que lo moviste a inreview pero no tiene a nadie asignado

**Comment by pabo99** [comment]
Si, olvidé asignarmelo. Ya quedó
