### ISSUE TITLE
(Calidad) Notificar al usuario de bans

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1458]
Originalmente parte de https://github.com/omegaup/omegaup/issues/1374, se decidió separar porque el scope era muy grande.

Se necesita agregar soporte en los controladores para enviar un correo al autor original de un problema cuando su problema sea banneado explicando claramente cómo arreglarlo para des-bannearlo.

**Comment by pabo99** [comment]
@lhchavez ¿quién me puede apoyar con la redacción del correo?

**Comment by heduenas** [comment]
Tal vez @Fer-OmegaUp ?

**Comment by Fer-OmegaUp** [comment]
@pabo99, si, yo te ayudo con la redacción del correo. déjame escribir un par de drafts y te los paso mañana en la noche.

**Comment by pabo99** [comment]
gracias

**Comment by Fer-OmegaUp** [comment]
@pabo99 @heduenas [aqui ](https://docs.google.com/a/omegaup.com/document/d/10PKnlyYP-XjMpUJLBDQN0uqE9dmY1Si6nWMUYMlmvR4/edit?usp=sharing
)esta un draft con la redaccion del correo. Que les parece?

Otra pregunta, lo necesitamos en otro idioma ademas de espanol? (ingles y portugues?)

**Comment by heduenas** [comment]
@Fer-OmegaUp Si lo necesitamos localizado. Aunque no diria que son tan importantes las traducciones justo ahora.

**Comment by lhchavez** [comment]
necesitamos aunque sea una versión preliminar en los otros lenguajes para poderle dar commit (o los linters se van a quejar amargamente por la falta de traducciones).

no hay prisa, solo quiero que estén conscientes de la dependencia.

**Comment by Fer-OmegaUp** [comment]
ok, una vez que estemos todos contentos con el draft en español traduzco a portugués e inglés. algún otro idioma que necesitemos?

**Comment by elendil326** [comment]
#1543 le dará seguimiento
