### ISSUE TITLE
Relacionar el idioma de un problema (e.g. inglés, español, etc) con el problema en la base de datos

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1463]
## Comportamiento Esperado

Como prerequisito para poder filtrar los problemas por su idioma (issue #842) necesitamos relacionarlos primero en la base de datos

## Comportamiento Actual

La relación existe, pero es tomada desde el sistema de archivos. Esto no nos permite filtrar.

## Contexto

Prerequisito para el issue #842 . Es preciso mencionar que una vez hecho este cambio, se tendrá que llenar la información de los problemas ya existentes usando la información del sistema de archivos, así como habilitar el controlador para subir problemas que llene la información a la base de datos.

**Comment by pabo99** [comment]
En la base de datos existe una tabla llamada Problems_Languages, que relaciona al problema con su idioma, además los relaciona con el id del usuario que lo traduce o eso es lo que entiendo. Esta tabla está vacía y en el código no veo que se utilice para algo. Como sugerencia, esta tabla podría servir para lo que se requiere, sólo se tendría que eliminar la columna de translator_id, o en su caso, asignarle el id 1
