### ISSUE TITLE
"Tiempo límite excedido" cuando debe ser "Error en ejecución"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#1468]
Hola a todos, hace poco reporté un error en el que "TLE" se reportaba como "EE" y viceversa. Ya arreglaron el reporte de"TLE" pero sigue habiendo problemas con "EE".

Por ejemplo, para el problema https://omegaup.com/arena/problem/Una-serie-poco-interesante/#problems acabo de subir el siguiente código (GUID d6572e9f)

```
#include <cstdlib>
#include <iostream>

int main( )
{
   int* p = nullptr;
   *p = 0xDEADBEEF;
   std::cout << *p << "\n";
 }
```
y marca TLE con tiempo >0.05s

**Comment by lhchavez** [comment]
Efectivamente había un bug, _pero_ en el caso de ese problema, el tiempo límite es _tan_ justo que a veces cuando hay errores en la ejecución, se pasa del tiempo límite porque el proceso intenta comunicarse con el sandbox para notificarle de su muerte, y eso es bastante lento (básicamente porque es un escenario que no vale la pena optimizar).

si quieres mantener el tiempo límite de 100ms, intenta subirle al "Extra time for libinteractive (ms)", que le agrega un colchón de tiempo wall al límite de tiempo. con otros 100ms que le agregues a ese ya debe darte RTE correctamente.

**Comment by darkmx** [comment]
vale, entendido y gracias :)
