### ISSUE TITLE
Error al crear un nuevo branch e intentar empujarlo a GitHub

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1483]
Al crear un branch, no puedo empujarlo a Github.

## Comportamiento Esperado

Crear una rama y sincronizarla con omega up 

Empujar la nueva rama a GitHub

## Comportamiento Actual

Consigo un mensaje de error al empujar mi branch a GitHub

## Pasos para reproducir 

Al crear la rama e intentar sincronizarla me aparece lo siguiente:
```M	stuff/hook_tools```

Después ejecuto el siguiente comando:
`git submodule update`

Y me marca lo siguiente:
```Submodule path 'stuff/hook_tools': checked out 'db96b5d0126c9c2b380111be3e46ed587549e779'```

Al intentar empujar mi branch a GitHub me aparece el siguiente error:
```Traceback (most recent call last):
  File "/opt/omegaup/stuff/database_schema.py", line 92, in <module>
    main()
  File "/opt/omegaup/stuff/database_schema.py", line 64, in main
    expected = _expected_database_schema(dbname=args.database, auth=auth)
  File "/opt/omegaup/stuff/database_schema.py", line 20, in _expected_database_schema
    schema = database_utils.mysqldump(dbname=dbname, auth=auth)
  File "/opt/omegaup/stuff/database_utils.py", line 60, in mysqldump
    return subprocess.check_output(args, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 949, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 2682: invalid continuation byte
error: failed to push some refs to 'git@github.com:pabo99/omegaup.git'```

**Comment by lhchavez** [comment]
El problema era que faltó el paso de "sincronizarlo con omegaUp":

    git checkout master && git reset --hard upstream/master && git push -f

debe sincronizar tu copia de `master` con `master` de omegaUp. Una vez hayas hecho eso, todas las ramas que crees después de ese punto van a empezar con ese commit al que sincronizaste.
