### ISSUE TITLE
Como usuario de omegaUp, quiero ver un listado de los tags más relevantes debajo de un problema en la lista para evitar clutter visual cuando un problema tiene muchos tags

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1491]
## Comportamiento Esperado

Cuando voy al listado de problemas en omegaUp, quisiera ver una cantidad limitada de tags debajo de cada problema (3 a 5 quizá). Estos serían los tags más relevantes para el problema. La relevancia de un tag podría ser determinada por los admins, o podría ser igual para todos los problemas.

## Comportamiento Actual

Hoy, se muestra la lista de todos los tags debajo de cada problema. Si un problema tiene más de 7 tags, se ve muy conglomerado.

## Posible Solución

- Dar semántica a los tags para poder mostrar uno de cada "grupo"
- Determinar que tags deben ser mostrados por todos los problemas, o permitir al administrador del problema decidir que tags mostrar
- Limitar el número de tags a mostrar por su grupo.

## Contexto

Este es un paso para resolver el escenario descrito en el issue #672

**Comment by heduenas** [comment]
Queda cubierto con el proyecto de feedback
