### ISSUE TITLE
Como usuario, quiero poder asignar un tag a un problema sin tener que ser el dueño del problema para colaborar en el mantenimiento de omegaUp

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1492]
## Comportamiento Esperado

Como usuario, quiero ser capaz de abrir un problema y asignarle tags que describan mejor al problema. Esto permitirá a otros usuarios encontrar problemas relacionados a este. Esta bien que algunos tags sean reservados para admins del sitio, pero quiero poder crear mis propios tags únicos para poder asignarlos.

## Comportamiento Actual

No puedo asignar tags a problemas de los cuales no soy dueño

## Posible Solución

- Separar admin tags de user tags
- Categorizar tags automáticamente para no requerir esta información del usuario, o habilitar a los admins una función para hacer esto manualmente
- Mostrar los tags existentes para facilitar la asignación, así como evitar duplicados (e.g. "C#" y "C #")

## Contexto

Este issue es parte del escenario #672

**Comment by elendil326** [comment]
#669 y #670 tienen discusión relacionada con esto.

**Comment by heduenas** [comment]
Queda cubierto con el feedback.
