### ISSUE TITLE
Como usuario, quiero poder ver una lista de tags existentes para poder filtrar los problemas en base a ellos

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1493]
## Comportamiento Esperado

Al acceder a la lista de problemas en omegaUp, quiero poder ver un listado de tags existentes, ordenados por su categoría, para poder filtrar con ellos la lista de problemas

## Comportamiento Actual

Como usuario, no puedo ver que tags existen, y por ende, no pudo usarlos para filtrar. Puedo navegar a un problema que tenga un tag específico, dar click en ese tag y así obtener una lista de problemas con ese tag. Esto es laborioso y consume tiempo. 

## Posible Solución

Tomado de @npave de la discusión original:

> Estaría bien dar semántica a los tags cómo lenguaje de programación, idioma, dificultad, tema... Después podríamos utilizar esta información para crear un sidebar con diferentes opciones para que el usuario encuentre los problemas que se adecuen a sus necesidades.

## Contexto

Este issue es parte del escenario #672

**Comment by nvzard** [comment]
I'd like to work on this issue :)

**Comment by heduenas** [comment]
@lhchavez can you assign this issue to @nvzard

**Comment by heduenas** [comment]
This has been solved by @carlosabcs' problem finder.
