### ISSUE TITLE
No hay una página de acceso prohibido

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1498]
Como usuario con rol de concursante común, al ingresar a una página que cual no tengo permisos, me aparece una página con el mensaje del navegador: No se encuentra esta página omegaup.com (404)

## Comportamiento Esperado

Como sugerencia, me gustaría ver una página con la plantilla de omegaUp que me diga que no tengo acceso y que me ponga una forma de regresar a donde estaba.

## Comportamiento Actual

La diferencia entre el comportamiento actual y el deseado es que el usuario no tenga la impresión de que algo tronó en omegaUp, sino que se de cuenta que no puede acceder a lugares donde no tiene permitido.

**Comment by elendil326** [comment]
Bloqueado hasta que estemos en AWS

**Comment by lhchavez** [comment]
Esto hay que hacerlo en github.com/omegaup/puppet

**Comment by pabo99** [comment]
@lhchavez, ¿Me puedes explicar cómo hacer el cambio en https://github.com/omegaup/puppet por favor?

**Comment by pabo99** [comment]
Sólo se va a revisar donde aparece un texto de `404` cuando entras a un concurso, para que te mande a la página principal
