### ISSUE TITLE
Estandarización de tablas en omegaUp

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1499]
He notado que en la plataforma existen diversas tablas y estas no están estandarizadas. Cada que se ocupa una nueva, se tiene que meter en código toda la estructura así como todas sus funcionalidades. 

## Comportamiento Esperado

Lo ideal es que desde el backend siempre se armen objetos con la misma estructura y que estos sean leídos por algún plugin o componente en vue, para que estos sean los que realicen toda la interacción con el usuario.

## Comportamiento Actual

La diferencia es con el comportamiento actual sería que ahorraríamos tiempo en el desarrollo de nuevas funcionalidades donde se involucren tablas, y a su vez, el usuario final se familiarizaría mucho más rápido con la plataforma.

## Posible Solución

Se me ocurren algunas posibles soluciones, que van desde crear nuestro propio plugin con ayuda del subcomité de diseño (esto llevaría algo de tiempo), o implementar uno ya existente (hay muchos y muy buenos que ya traen los estilos de bootstrap). Es cuestión de tomar la decisión si una u otra opción son viables

**Comment by lhchavez** [comment]
Después de discutirlo un poco, decidimos mejor no hacerlo porque nos quitaría mucha flexibilidad. Además, Vue hace que esto sea bastante más sencillo.
