### ISSUE TITLE
(Calidad) Agregar UI para mostrar dificultad de problemas

### ISSUE THREAD

**Issue by Fer-OmegaUp** [omegaup/omegaup#1500]
Mostrar la dificultad de un problema segun el siguiente spec: https://docs.google.com/document/d/1bfrCe9vEva1UAwjiss-BaYAy4nNH59lpeicJl_dOFDk/edit#bookmark=id.q2mghpxwtjmv

**Comment by heduenas** [comment]
Spec: https://docs.google.com/document/d/1bfrCe9vEva1UAwjiss-BaYAy4nNH59lpeicJl_dOFDk/edit#bookmark=id.q2mghpxwtjmv

**Comment by alanboy** [comment]
No hay nadie asignado en el issue, pero creo que @heduenas ya comenzo a trabajar en esto.

**Comment by heduenas** [comment]
Parte de esto esta resuelta con #1530

**Comment by heduenas** [comment]
Esto se resolvio con los histogramas de @carlosabcs
