### ISSUE TITLE
El validador de schema.sql se vuelve loco en mi VM

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1503]
## Comportamiento Esperado

Al correr `stuff/runtests.sh` se valida el esquema de la base de datos y se autocorrige si es necesario.

## Comportamiento Actual

`git checkout f9fa42f8969dbbb57cdc915a66ac7528d5eb0184`
`stuff/runtests.sh`
y entonces...
a) el validador escribe UTF-8 invalido y descompone caracteres con acentos
b) en la primer pasada intenta corregir (y descompone como en el punto anterior)
c) en la segunda pasada se queja de de que hay dos lineas consecutivas en blanco
d) goto b)

## Tu ambiente

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
mysqldump  Ver 10.13 Distrib 5.6.31, for debian-linux-gnu (x86_64)
mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by pabloaguilar** [comment]
[schema.sql.txt](https://github.com/omegaup/omegaup/files/1424804/schema.sql.txt)

**Comment by lhchavez** [comment]
la solución es hacer checkout de una versión reciente de `upstream/master` y correr `./stuff/bootstrap_environment.py --purge` (o `./stuff/db-migrate.py migrate`)

**Comment by lhchavez** [comment]
La solución a largo plazo es algo así como https://github.com/omegaup/omegaup/issues/1509
