### ISSUE TITLE
stuff/database_schema.py debe de pedir correr "./stuff/bootstrap_environment.py --purge"

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1509]
`stuff/database_schema.py validate` dice que hay errores y que corras `stuff/database_schema.py fix` pero también debería de decir que antes de correr fix corras `/stuff/bootstrap_environment.py --purge`

**Comment by lhchavez** [comment]
Resulta que esto se puede hacer dentro del linter sin tocar la base de datos!
