### ISSUE TITLE
[FEATURE] Configuración de carrusel en homepage

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#1511]
Como parte del rediseño de homepage se va a agregar un carrusel en el que se anuncien nuevos proyectos y noticias recientes en omegaUp. 

## Comportamiento Esperado

La información del carrusel estará cambiando continuamente y necesitamos una forma sencilla de actualizarla que no requiera esperar al deployment semanal.

## Comportamiento Actual

Actualmente no hay una forma de presentar noticias o proyectos recientes.

## Posible Solución

Se analizaron tres posibles soluciones para esto, [aquí](https://docs.google.com/document/d/1omFJnjFFx6PUFOy1kg8TzZQZOab59zxX19vSCq9mXQE/edit?usp=sharing) se puede ver el reporte.  Se optó por crear un archivo JSON con la información necesaria para crear el carrusel.

**Comment by carlosabcs** [comment]
@tvanessa esto ya puede ser cerrado.
