### ISSUE TITLE
[FEATURE] Validador i18n debe soportar configuración del carrusel 

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#1514]
## Comportamiento Esperado

El archivo de configuración del carrusel va a tener mensajes internacionalizados que deberían tener validación. 

## Comportamiento Actual

No se valida porque el archivo es nuevo

**Comment by pabo99** [comment]
Dependemos del #1511 para poder resolver este issue. @npave ¿Sabes en que estatus está el issue?

**Comment by carlosabcs** [comment]
@tvanessa esto ya puede ser cerrado.
