### ISSUE TITLE
RunController::apiCreate debe bloquear envíos a problemas banneados

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1517]
Como un administrador de un problema banneado, la plataforma no debería permitir realizar envíos a administradores, porque es una manera de circunvenir el bloqueo.

## Posible Solución

Se debe agregar una condición aquí para verificar que el problema no está banneado:

https://github.com/omegaup/omegaup/blob/4ec11f4648b6f40af3bd33d81616f9d6d26bde86/frontend/server/controllers/RunController.php#L69

**Comment by heduenas** [comment]
The condition should be ($r['problem']->visibility == ProblemController::VISIBILITY_PUBLIC_BANNED ||
                  $r['problem']->visibility == ProblemController::VISIBILITY_PRIVATE_BANNED))

**Comment by HorsemanJnr** [comment]
Hello,

I want to fix this bug. Could you assign it to me?

**Comment by lhchavez** [comment]
assigned! thanks :D
