### ISSUE TITLE
Como un administrador de mentores, quiero saber el correo de contacto del coder del mes para poder contactarlo facilmente

### ISSUE THREAD

**Issue by Yorchito** [omegaup/omegaup#1518]
## Comportamiento Esperado
Debería existir una página que puedan ver los administradores que me permitar saber el correo de contacto de los coder del mes. Que sea posible agregar mas administradores para que se puede agregar acceso si alguien mas lo necesita. 

## Comportamiento Actual
Actualmente no hay forma de saber el correo de contacto del coder del mes. Tienes que ser extraído de forma manual por alguna persona que sea site-admin

## Posible Solución

Una página que solo puedan ver los site-admins y que también puedan dar acceso a mas personas (agregar administradores)

## Contexto
Cada mes, el programa de mentores necesita contactar al coder del mes. En muchas ocasiones el ganador no hace caso del banner que se le muestra y tenemos que pedirle a alguien que extraiga su correo e iniciar el contacto nosotros.

**Comment by elendil326** [comment]
@lhchavez @pabloaguilar @npave @Yorchito 

Como lo veo, el feature como tal habla de dos problemas

1. No hay un esquema de permisos que defina a un "administrador de mentores" en omegaUp
2, Como site admin en general, no hay manera fácil de encontrar el email de un usuario

Creo que el _pain point_ más grande es encontrar el email del ususario, y como está descrito el problema, no creo que una nueva página sea necesaria. Siento que el problema se puede resolver con agregar un "mailto:<email>" al coder del mes que se presenta en la página principal. A menos que se quiera ver un catálogo histórico o algo así, pero eso no está descrito aquí.

No sé que opinen de dar de alta el concepto de "_admin de mentores_" para que tenga su propio dashboard y sus propios permisos pero siento que resolver eso no es de tan alta prioridad como resolver el problema de encontrar el email rápido.

**Comment by Yorchito** [comment]
La propuesta de agregar la opción para enviar un correo al coder del mes me parece bien:

> Siento que el problema se puede resolver con agregar un "mailto:" al coder del mes que se presenta en la página principal.

Si nadie está en contra de que eso sea posible entonces estoy de acuerdo en hacerlo de esa manera.

**Comment by elendil326** [comment]
@Yorchito, ya lo discutimos en el backlog grooming de hoy y vamos a resolver el problema principal con la opción del "mailto". Si quieres la segunda parte del problema (dashboard de "admin de mentores") puedes crear otro issue o usar este mismo y actualizarlo con más información del diseño o lo que esperas ver en ese dashboard.

**Comment by elendil326** [comment]
Cerrando en favor de #1526
