### ISSUE TITLE
Agregar aviso de privacidad en omegaup.com

### ISSUE THREAD

**Issue by Yorchito** [omegaup/omegaup#1519]
Las leyes federales en México, requieren que los sitios en Internet muestren un aviso de privacidad en la página principal. 

- El contenido se iniciara aquí: https://docs.google.com/document/d/1NsjieTudl1VwJLDhQhm64Am5mwyh1hsAJa4hqc6-A1I/edit#heading=h.bin39iqjyy4s
- Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo la Ley) y su Reglamento.
- http://abcavisosprivacidad.ifai.org.mx/
- http://inicio.ifai.org.mx/SitePages/Guia-para-el-Aviso-de-Privacidad.aspx

**Comment by elendil326** [comment]
@npave está bien si podemos ponerlo baajo?

**Comment by npave** [comment]
@elendil326 si, podemos poner un link al aviso de privacidad en el footer.

**Comment by elendil326** [comment]
Excelente. Gracias @npave . @Yorchito estoy poniendo este issue tentativamente para trabajar en el siguietne sprint (11/13 - 11/24). Crees que tengas chance de tener listo el aviso de privacidad para esos días?

**Comment by alanboy** [comment]
En que queda el aviso de privacidad actual: https://blog.omegaup.com/privacy-policy/ ?

**Comment by pabo99** [comment]
Una vez que se autorice el nuevo aviso de privacidad, se agregará un link en el footer, como lo comenta @npave
