### ISSUE TITLE
Como site admin, quiero acceder rápidamente a los emails de los usuarios desde la página de omegaUp para poder contactarlos

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1526]
## Comportamiento Esperado

Como site admin, no necesito ir a la base de datos en el back end y escribir un query para obtener el email de un usuario, si no que está presentado de una manera intuitiva y rápida en la página de "omegaUp"

## Comportamiento Actual

Esta información no está disponible desde la página de omegaUp, se tiene que acceder a la base de datos y hacer un query.

## Posible Solución

Cada vez que se imprima el nombre de usuario de un miembro de omegaUp, si el usuario viendo la página es un site admin, mostrar el nomber dentro de un html `<a href="mailto:user@omegaup.com">`

## Contexto

Este es parte de la discusión en el issue #1518. Los administradores de mentores necesitan acceso rápido al correo de los coders del mes, pero en general, un site admin debería tener acceso a esta información también.

**Comment by pabo99** [comment]
Por lo que veo, el correo de todos los usuarios en omegaUp es accesible en la vista de perfil, siempre y cuando el usuario logueado tenga permisos de de site-admin. ¿Esto no soluciona el problema que se plantea originalmente? 

En caso de que alguien mas requiera acceder a esta info, es más fácil sólo revisar si se le puede abrir este permiso a perfiles.

**Comment by pabo99** [comment]
Se cierra, debido a que cualquier site-admin ya tiene la forma de ver el correo de los usuarios desde la página de Perfil.
