### ISSUE TITLE
Agregar el campo "Nombre de escuela" en el formulario crear un nuevo curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#1528]
Relacionar un curso con una escuela nos ayudará con estadísticas, ofrecer ayuda, hacer encuestas de usabilidad, entre otras. 

## Comportamiento Esperado

Al momento de crear un curso, el usuario debe agregar el nombre de la escuela en la que se dará este curso.

## Comportamiento Actual

No existe esa opción.

## Posible Solución

Agregar el campo "Nombre de escuela" en el formulario que se llena cuando se crea un nuevo curso.

**Comment by pabo99** [comment]
@npave Actualmente ya tenemos una tabla de Escuelas, ¿Podemos utilizar estas escuelas para este cambio que solicitas?

**Comment by npave** [comment]
@pabo99 si, que se registre como nueva escuela en ese momento
