### ISSUE TITLE
Agregar un mecanismo para auto-agregar privilegios en sandbox.omegaup.com

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1539]
Como un usuario normal, quiero poder probar cosas en el sandbox de omegaup sin la intervención de un administrador, para no tener que esperar a que ellos lo hagan manualmente.

## Comportamiento Esperado

Una interfaz con un panel de administración (que sería bueno tener de cualquier manera para producción). Esta interfaz debe poder permitir agregar a un usuario a uno de los privilegios globales ( https://github.com/omegaup/omegaup/blob/e9dd1cc9c9034e2ce4b5455722caf40f3da1cd91/frontend/server/libs/Authorization.php#L17-L27 ) o uno de los grupos globales ( https://github.com/omegaup/omegaup/blob/e9dd1cc9c9034e2ce4b5455722caf40f3da1cd91/frontend/server/libs/Authorization.php#L32-L36 )

## Comportamiento Actual

Un administrador debe manualmente editar la base de datos.

**Comment by elendil326** [comment]
Osea, queremos que cualquier usuario con acceso al sandbox pueda mover los permisos de todos los usuarios en el sandbox? o solo sus propios permisos?

**Comment by pabo99** [comment]
@lhchavez ¿Podemos resolverlo con una matriz de permisos y que el usuario seleccione con  checkboxes los permisos que necesita?
