### ISSUE TITLE
(Calidad) Separar datos de feedback que fueron capturados después del cambio en las preguntas

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1540]
Las preguntas fueron cambiadas ligeramente en https://github.com/omegaup/omegaup/pull/1538

Hay que modificar el cronjob para que sólo agregue las que fueron capturadas después de ese cambio.

**Comment by lhchavez** [comment]
Esto se puede hacer simultáneamente con #1552?

**Comment by elendil326** [comment]
¿Esto puede esperar para el siguiente sprint? @lhchavez @Fer-OmegaUp

**Comment by heduenas** [comment]
Este no es urgente, si puede esperar.

**Comment by pabo99** [comment]
No estoy tan familiarizado con el cronjob y tengo este issue en el backlog del sprint actual, ¿Me pueden ayudar a describir el cambio?

**Comment by heduenas** [comment]
Yo creo que para hacer este es mejor esperar a migrar el cronjob a python. Yo espero que eso este listo para este domingo.

**Comment by pabo99** [comment]
Gracias.

**Comment by lhchavez** [comment]
El primer ID con el nuevo formato es `18663`.

**Comment by pabo99** [comment]
Gracias, ahora si @heduenas, ¿me puedes ayudar a explicar a que se refiere este cambio?

**Comment by lhchavez** [comment]
Según entiendo es nada más ponerle ```WHERE qn.`qualitynomination_id` > 18663``` en todos los lugares donde se consulta `QualityNominations` en https://github.com/omegaup/omegaup/blob/master/stuff/cron/aggregate_feedback.py

**Comment by heduenas** [comment]
Exactamente. La idea es simplemente filtrar los quality nominations que vengan despues del 18663. Aunque creo que preferiria que se filtrara usando la fecha, en vez del id. @lhchavez tienes la fecha del 18663?

**Comment by lhchavez** [comment]
filtrarlo por fecha es significativamente más lento que por id, lamentablemente :( así que sugiero seguir con el plan del ID.

**Comment by heduenas** [comment]
@lhchavez Ese es un buen punto. @pabo99 hay que ponerel un comentario en la parte del codigo donde filtres diciendo que a partir de ese id se cambio el formato de la pregunta e incluir la fecha de ese envio.
