### ISSUE TITLE
Permitir hacer algunas tareas administrativas desde la interfaz

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1560]
Como un miembro del comité de soporte, quiero poder hacer algunas tareas administrativas comunes, como validar un usuario dado su correo electrónico, o restablecer contraseñas para que los site-admins no tengan que hacerlo.

## Posible Solución

Un panel administrativo que tenga acceso a esta funcionalidad.

**Comment by elendil326** [comment]
@lhchavez Esto requiere más especificación y diseño. Podemos empezar listando las tareas y creando issues separados por tarea

**Comment by lhchavez** [comment]
Empecemos por las dos tareas de la descripción:

[ ] Validar un usario dado su correo electrónico
[ ] Restablecer contraseñas para que los site-admins no tengan que hacerlo
[ ] Recuperar cuentas viejas
