### ISSUE TITLE
(Secuencias Didacticas): Como problemsetter, quiero poder escribir la solución de mi problema para que los concursantes la puedan leer.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1561]
## Comportamiento Esperado

Así como tenemos `[lang].markdown` en `statements`, sería muy útil tener `[lang].tutorial.markdown`, que es otra redacción que explica cómo se debía resolver el problema.

Habría que definir cuándo mostrarla al concursante, pero tal vez lo más fácil inicialmente sería sólo mostrarla en modo práctica o cuando se resuelve el problema fuera de un concurso.

## Comportamiento Actual

No existe nada similar.

## Contexto

En el Workshop de la OMI estamos intentando hacer un curso en el que los alumnos puedan avanzar a su propio ritmo sin necesidad de estar en una clase o tener un instructor. Esto requiere poder explicar la solución separada de la redacción del problema.

Adicionalmente, lo volveríamos un requerimiento para nuevos problemas de la OMI, de tal forma que omegaUp también se vuelva el lugar canónico para saber cómo resolver los problemas de la olimpiada.

**Comment by heduenas** [comment]
Este muy probablemente va a necesitar un one-pager, sobre todo por la parte de UX.

**Comment by lhchavez** [comment]
Esto necesita también el nuevo formato de los problemas.

**Comment by elendil326** [comment]
Cerrado por contenidos
