### ISSUE TITLE
Aparece duplicado los registros de coder del mes para sep y ago del 2015

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1562]
Probablemente es un bug al contar con mas de una imagen de perfil en el sistema

![image](https://user-images.githubusercontent.com/5838427/32973386-fe1578b8-cbab-11e7-85cc-ba6a7a734269.png)

**Comment by lhchavez** [comment]
Ah buena hipótesis. La causa raíz es por contar con más de un correo en el sistema. Usamos el correo para generar el URL de Gravatar, así que en esencia es lo que suponías.

**Comment by pabo99** [comment]
Duplicado del #1214
