### ISSUE TITLE
El contador de usuarios que resolvieron un problema no está actualizado

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1565]
## Comportamiento Esperado

Al resolver un problema se debería actualizar la entrada en la tabla de problemas que dice cuántos usuarios han resuelto el problema.

## Comportamiento Actual

Está en cero pero sí hay usuarios que lo resolvieron.

![image](https://user-images.githubusercontent.com/468211/32983477-c3b9bd46-cc5a-11e7-95cb-a490e8818139.png)

![image](https://user-images.githubusercontent.com/468211/32983485-e5ba716a-cc5a-11e7-9fa1-06f87a91087a.png)

## Pasos para reproducir (para bugs)

1. Hacer un nuevo problema (?)
2. Hacer un submission que da AC.

**Comment by lhchavez** [comment]
Creo que esto fue a raíz del cambio de host. Según yo teníamos un `TRIGGER` que se encargaba de esto, pero al parecer no se activó.
