### ISSUE TITLE
(Calidad): Tener la posibilidad de mostrar nuevamente el formulario de Quality Nominations

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#1567]
## Comportamiento Esperado

Si un usuario hace dismiss a un formulario de Quality Nominations debe tener la posibilidad de volver a verlo.

## Comportamiento Actual

No hay manera de volver a ver el formulario después de cerrarlo

## Posible Solución

Añadir un botón en la UI para mostrar el formulario si el usuario hizo dismiss.

**Comment by lhchavez** [comment]
Puntos extra si la primera vez que se hace dismiss hay una indicación en la interfaz que muestre el botón.
