### ISSUE TITLE
(Calidad): Añadir soporte para que un usuario pueda eliminar un problema suyo

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1568]
Actualmente se pueden poner como privados. Pero los usuarios pueden estar interesados en eliminarlo por completo. Internamente podríamos ponerle un nuevo tipo de visibilidad que haga que no se muestre en las listas de problemas, para no tener que lidiar con resolver dependencias que otras tablas puedan tener en ese problema en la base de datos.

**Comment by lhchavez** [comment]
Algo así como agregar `const VISIBILITY_PRIVATE_BANNED = -10;` a https://github.com/omegaup/omegaup/blob/981aafc6e32d78e8186b7287d97b332cd69cceff/frontend/server/controllers/ProblemController.php#L13-L18 ? suena razonable.
