### ISSUE TITLE
Como organizador, quiero poder ordenar los problemas/contenidos en un curso

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1572]
## Comportamiento Esperado

No hay forma de decidir qué problema va en qué orden en un curso.

## Comportamiento Actual

Se agregan los problemas al final (?) o en algún orden arbitrario y no se pueden reordenar.

## Posible Solución

Agregar un campo que determine el orden en el concurso, como con los problemas de un concurso.

## Contexto

Los cursos usualmente tienen una progresión lógica, con los problemas yendo en orden (tal vez de dificultad) para enseñar un tema. Sin este feature no se pueden hacer cursos en los que hay una progresión de aprendizaje.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1546 (que ya está en revisión!)
