### ISSUE TITLE
Documentar los browsers soportados oficialmente

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1578]
## Comportamiento Esperado

Como un usuario o desarrollador, quiero saber cuales son los browsers oficiales soportados por omegaUp la plataforma.

## Comportamiento Actual

No se donde determinar esto

## Posible Solución

Plataforma: Agregar una seccion al README.md u una pagina en el wiki
Sitio oficial: Ademas, hacerlo visible en la ayuda o preguntas de omegaup.com

**Comment by lhchavez** [comment]
oficialmente? solo Chrome stable channel. oficialmente _no_ soportado, IE (pero Edge no hay bronca). oficialmente roto IE < 9 y Firefox < (la versión de hace dos años).

esta es otra cosa que necesitamos pruebas automatizadas u_u.

**Comment by lhchavez** [comment]
Con https://github.com/omegaup/omegaup/pull/1590 podemos empezar a tener más pruebas de Selenium

**Comment by lhchavez** [comment]
Un data point más al "oficialmente roto y no se intentará arreglar": acabo de intentar IE 8 cortesía de [Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) (0.356764% de los visitantes según GA) y es un desastre. Casi todas las librerías third party están rotas en ese navegador. Obviamente nuestro código tampoco jala.

**Comment by lhchavez** [comment]
IE 9 (0.00% de los visitantes según GA) también es un estado bastante triste :( algunas cosas funcionan, pero hay errores de cuando en cuando. La arena no funciona para nada, por ejemplo, porque las promesas al parecer no están bien polyfilled ahí.

**Comment by lhchavez** [comment]
IE 10 parece que sí funciona bien.
