### ISSUE TITLE
Actualizar a una version soportada de jQuery

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1579]
De acuerdo al sitio de jQuery, los branches 1.x y 2.x ya no reciben actualizaciones.
La version usada en omegaUp ahorita es 1.10

**Comment by lhchavez** [comment]
+1, pero esto tiene el potencial de romper absolutamente todo D: necesitamos tener más pruebas automatizadas.

**Comment by pabloaguilar** [comment]
Selenium se ve straightforward.
Que te parece esto como integration test:

* En un ambiente con el requerimiento de verificacion deshabilitado (e.g. sandbox)
* Navigate to home page
* Navigate to login page
* Create user name with random e-mail
* Log in with that user
* Create a problem
* Navigate to problem
* Submit code
* Verify run shows up
* Create contest
* Add existing problem to contest
* Navigate to contest
* Click through intro page
* Verify summary
* Open problem
* Submit

Con esa prueba seria suficiente para la migracion ?
Puede quedar eso como el primer milestone de pruebas con Selenium
Como segundo milestone, ponemos el tener una prueba de integracion por user journey (practice, contest, quality nomination, course teacher, course student, interviewer, interviewee)
Y como tercer milestone ponemos el probar coas con detalle, es decir, hacer envios con diferentes veredictos, checar visibilidad de problemas publicos/privados, editar cosas, etc.

Ahorita hice una prueba rapida y creo que agregar el caso principal (que puse arriba) queda pronto

**Comment by lhchavez** [comment]
Con esa prueba creo que sería más que suficiente! Reviví una rama antiquísima en mi VM que ya tenía un soporte súper rudimentario para Selenium: https://github.com/omegaup/omegaup/pull/1587

**Comment by elendil326** [comment]
@lhchavez a juzgar por el pull request, esto ya esta en camino
