### ISSUE TITLE
Categorizacion de un problema no permite seleccion de un tema unico

### ISSUE THREAD

**Issue by JuanM97** [omegaup/omegaup#1581]
## Comportamiento Esperado

Una vez resuelto un problema, omegaUp te felicita por resolverlo, y te hace una serie de preguntas (dificultad del problema, temas relacionados y calidad del problema).

En el menu de seleccion de temas, se espera poder seleccionar los temas que se creen relacionados, uno por uno. En realidad, al seleccionar un item, se seleccionan todos los temas de la lista. Al quitar la seleccion, se quita tambien la seleccion de todos.

## Pasos para reproducir (para bugs)

1. Entrar a tu cuenta de omegaUp y tener al menos un problema resuelto.
2. Entrar a un problema ya resuelto.
3. Debera aparecer una ventana felicitandote por resolver el problema (diciendo algo como "Congratulations for solving this problem!"), preguntando por la dificultad, por temas relacionados (esta es la parte afectada) y por la calidad del problema.
4. En la parte afectada, seleccionar o no cualquier item, hara que ese mismo comportamiento afecte a todos los demas de la lista.

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Google Chrome Version 62.0.3202.94 y Microsoft Edge 41.16299.15.0
* Sistema Operativo y versión (escritorio o móbil): Windows 10 desktop
* Link al sitio en el que este problema pasa: i.e. https://migration.omegaup.com/arena/problem/m3#problems
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/10576130/33155048-ddc1b640-cfa1-11e7-80e9-bb98dfb53d64.png)
![image](https://user-images.githubusercontent.com/10576130/33155058-ea1b7778-cfa1-11e7-8bbf-4a7997f2086d.png)

**Comment by lhchavez** [comment]
Asignando a @heduenas porque según recuerdo ya estaba trabajando en esto.
