### ISSUE TITLE
Error Login Facebook

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1591]
![image](https://user-images.githubusercontent.com/5459260/33252239-79ab5774-d302-11e7-9aae-89684e0f9ab0.png)

El boton de Facebook cuando le das click en lugar de hacer el Login te manda a esa pantalla, creo que puede ser problema de la Graph o podría ser la api key.

**Comment by lhchavez** [comment]
Ya quedó arreglado.
