### ISSUE TITLE
(Calidad) Refactorizar getProblemSuggestionAggregates y getGlobalDifficultyAndQuality

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1597]
Antes de que el cronjob sea migrado a python, refactorizar getProblemSuggestionAggregates y getGlobalDifficultyAndQuality en dos funciones cada una: una que lea los registros de la base de datos y otra que haga calcule los aggregates.

Después hay que se haga la refactorización, migrar los tests testGetGlobalDifficultyAndQuality() y testGetSuggestionRowMap() a python.

**Comment by pabo99** [comment]
@heduenas ¿Sabes si ya hay fecha para la migración del cronjob a Python?
