### ISSUE TITLE
No me deja visualizar los envíos en medio de una arena ( Soy owner y revise en cuenta de admin igual) 

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1601]
![image](https://user-images.githubusercontent.com/5459260/33499648-59f073b4-d69b-11e7-9b5a-70d17ee2ebb5.png)

Tampoco como admin me marca 404 y ya existen envíos :c

**Comment by lhchavez** [comment]
Necesitas meterte sin el `/admin/`, entrar como usuario mortal y volver a meterte a `/admin/.
