### ISSUE TITLE
El ranking no se actualiza con problemas resueltos

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1604]
*Reporte 1:*
Hola, disculpe mi problema es que desde hace un tiempo no he avanzado en el rank, ni mis puntos ni la cantidad de problemas resueltos cambia, sin importar que conteste mas y mas, podrian solucionarlo?

Pues he resuelto publicos y he hecho en concursos (Estoy participando en la ORIG), segun yo si funcionaba pero de un tiempo para aca mis puntos no aumentan en el ranking, y mi posicion no sube ni baja solo se queda estatica con no los mismo datos (puntos y problemas resueltos).

*Reporte 2 (Miguel Romero):*
No se actualiza el ranking global solamente el personal (pagina de perfil).

**Comment by lhchavez** [comment]
Creo que es porque Amazon RDS no soporta los triggers por tiempo? O algo así ha de ser, porque no hay PHP para actualizar esto.

Peor caso armamos un cronjob Python.

**Comment by lhchavez** [comment]
Ya vi el problema: por default Amazon RDS no permite agregar TRIGGERs a menos que cambies la configuración. Eso no se puede hacer sin reiniciar la instancia, así que se hará el domingo en la noche junto con el deployment.

**Comment by lhchavez** [comment]
TRIGGER activado!
