### ISSUE TITLE
Tiempo de Evaluador diferente en "Escuelas"

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1607]
Fuente: https://omegaup.com/preguntas/1297/tiempo-de-evaluador-diferente-en-escuelas

Ya me ha ocurrido varias veces y con diferentes problemas, que tengo un código de AC en un problema, y al momento de enviar este mismo código en "omegaUp Escuelas", me da TLE ( Tiempo Limite Excedido )

Me parece que esto no debería de ocurrir, pues si el código ya estaba aceptado y es el mismo código, no veo porque el tiempo debería de ser un problema.

Me ocurrió con el problema de "Enredados" y "Cables Cruzados".

Link Enredados: https://omegaup.com/arena/problem/Enredados#problems

Link Cables Cruzados: https://omegaup.com/arena/problem/Cables-Cruzados#problems

Link Concurso: https://omegaup.com/course/PES-2018/assignment/PES-divide-y-venceras#problems

**Comment by lhchavez** [comment]
Esto es porque se arregló un bug donde se le estaba dando tiempo de más antes y ahora el evaluador cumple con lo esperado.
