### ISSUE TITLE
Como usuario quiero poder filtar la página de rank por escuela, país y estado para poder saber en qué lugar me encuentro en los ámbitos mencionados

### ISSUE THREAD

**Issue by Yorchito** [omegaup/omegaup#1609]
## Comportamiento Esperado

Como usuario quiero tener una opción de poder ver cual es mi rank por escuela, por país y por estado.

## Comportamiento Actual

Actualmento solo se puede saber cual es mi ranking general 

## Posible Solución
Agregar los filtros necesario para que se pueda elegir en un drop down list, el pais, el estado y la escuela. Una vez aplicado el filtro, la página de ranking debe mostrar a los usuarios que cumplan con dicho filtro.

**Comment by lhchavez** [comment]
Buena idea! :+1:

**Comment by lhchavez** [comment]
Únicamente se va a mostrar la opción del filtro para las cosas que tengan en su perfil. e.g. si un usuario no ha registrado su estado, no se muestra el filtro de "estado".

Hay que armar las queries y cachearlo igual que el rank global.
