### ISSUE TITLE
Score NO se muestra en tiempo real

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#1615]
El contest https://omegaup.com/arena/ORIG1718PIEP01/ se configuró para que no mostrará el score durante el contest, tampoco lo mostraría al final del mismo. Esta configuración la he realizado muchas veces.

Hoy, al hacer lo mismo, en el admin del contest, puede ver los submits de los alumnos pero no puedo ver el score, ni como admin ni con el link admin de score: 

![00](https://user-images.githubusercontent.com/6465292/33797354-18c0a738-dccc-11e7-85cb-f36f81af8a3a.PNG)
![01](https://user-images.githubusercontent.com/6465292/33797355-18dcfaf0-dccc-11e7-8496-8f565874f68b.PNG)

**Comment by lhchavez** [comment]
El grader estaba intentando comunicarse con el broadcaster usando un puerto incorrecto. Ya debe funcionar.
