### ISSUE TITLE
Regresión: No permite agregar múltiples usuarios a un concurso 

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1616]
## Comportamiento Actual

Al momento de intentar agregar múltiples usuarios a un concurso privado me dice que hay un error. Ya intenté con espacios después de las comas, sin espacios y con enter. Les dejo screenshots. Todos los usuarios eran válidos ya que al agregarlos de uno por uno sí los guardó.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Ir a https://omegaup.com/contest/OMIP2018ABIERTO/edit/#contestants 
2.  En el campo de Multiples Usuarios agregar los siguientes: arte_rosa, Gael_Perdomo
3. Dar click en Agregar usuarios

## Contexto

Para la OMIPS tuve que agregar muchos usuarios a los exámenes privados.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* Screenshots:

<img width="946" alt="screen shot 2017-12-09 at 12 03 05 pm" src="https://user-images.githubusercontent.com/5167417/33798122-f60dd442-dcd8-11e7-8b99-e426d107e68f.png">
<img width="748" alt="screen shot 2017-12-09 at 12 00 37 pm" src="https://user-images.githubusercontent.com/5167417/33798123-f61f4bbe-dcd8-11e7-93c5-fc88ccc1a0f0.png">
<img width="699" alt="screen shot 2017-12-09 at 12 00 28 pm" src="https://user-images.githubusercontent.com/5167417/33798124-f62f5356-dcd8-11e7-8a8d-322509610cde.png">

**Comment by lhchavez** [comment]
puedes postear lo que te haya dicho la consola de JavaScript?

**Comment by lhchavez** [comment]
Creo que el problema es que estamos pasándole estado a `bulkOperation` de una manera súper rara:

https://github.com/omegaup/omegaup/blob/3a73c5ba87238cc74d27ede1ef716ffe47263761/frontend/www/js/omegaup/ui.js#L72-L76

La solución es pasarle explícitamente la lista de parámetros a correr.

**Comment by andreasantillana** [comment]
@lhchavez aquí está lo de la consola

```
ui.js:249 /api/contest/addUser/ 404 Usuario o mail no encontrado {status: "error", error: "Usuario o mail no encontrado", errorname: "userOrMailNotFound", errorcode: 404, header: "HTTP/1.1 404 NOT FOUND"}error: "Usuario o mail no encontrado"errorcode: 404errorname: "userOrMailNotFound"header: "HTTP/1.1 404 NOT FOUND"status: "error"__proto__: Object
(anonymous) @ ui.js:249
dispatch @ jquery-1.10.2.min.js?ver=0511ab:5
v.handle @ jquery-1.10.2.min.js?ver=0511ab:5
trigger @ jquery-1.10.2.min.js?ver=0511ab:5
k @ jquery-1.10.2.min.js?ver=0511ab:6
r @ jquery-1.10.2.min.js?ver=0511ab:6
XMLHttpRequest.send (async)
(anonymous) @ VM37:1
send @ jquery-1.10.2.min.js?ver=0511ab:6
ajax @ jquery-1.10.2.min.js?ver=0511ab:6
(anonymous) @ api.js:9
(anonymous) @ contest.edit.js?ver=d91f68:351
(anonymous) @ ui.js:69
each @ jquery-1.10.2.min.js?ver=0511ab:4
each @ jquery-1.10.2.min.js?ver=0511ab:4
bulkOperation @ ui.js:67
(anonymous) @ contest.edit.js?ver=d91f68:348
dispatch @ jquery-1.10.2.min.js?ver=0511ab:5
v.handle @ jquery-1.10.2.min.js?ver=0511ab:5
```

**Comment by andreasantillana** [comment]
No sé si es mejor screenshot hahaha te lo dejo

![image](https://user-images.githubusercontent.com/5167417/33798363-915cd5b2-dcdc-11e7-9f0d-bb8ee0789598.png)
