### ISSUE TITLE
[BUG] Tiempo por omisión para el evaluador

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#1617]
Hola amigos de OmegaUp, según recuerdo antes el tiempo límite del evaluador era igual al tiempo límite del envío pero en algún momento se separaron dichos límites. Al agregar ese campo de configuración, dejaron el valor por omisión en el valor más común (un segundo). 

Para los problemas que no pueden resolverse en un segundo (por ejemplo, tiempo límite de 2 segundos) y donde el evaluador primero resuelve el problema y posteriormente compara la respuesta, el evaluador anteriormente al menos podía usar el mismo tiempo límite que el de los envíos ordinarios. Sin embargo, con el valor por omisión ahora hay casos en los que el evaluador ya no puede ni siquiera emitir el veredicto porque OmegaUp lo mata. Sin un rol activo por parte del autor del problema, eso implica que algunos problemas básicamente quedaron inutilizables y la manera de diagnosticarlo y arreglarlo puede no ser inmediatamente obvia para un administrador genérico del sitio.

**Comment by lhchavez** [comment]
Tienes una lista de dichos problemas?

**Comment by darkmx** [comment]
ahorita me mordió eso en https://omegaup.com/arena/problem/Ordenando-archivos/ pero ya lo arreglé, tendría que revisar todos mis problemas para ver cuáles usan evaluador (sería bueno que en la lista de problemas hubiera un iconito para identificarlos rápido)

**Comment by lhchavez** [comment]
Ya veo. Entonces para hacer esto accionable, crees que sea suficiente con permitir filtrar tus problemas usando más campos? El lenguaje, si tiene validador, si es interactivo, etc?

**Comment by darkmx** [comment]
Eso sería bastante útil (en general, no nada más para esto), pero la primera solución que se me vino a la mente era una query que modificara la base de datos para que al validador se le diera al menos 0.5 segundos más que al envío ordinario, para aquellos casos en los que actualmente el validador tiene un tiempo <= que el tiempo ordinario. 

Por otra parte, temo que si en algún momento se separa la memoria límite. algo similar pasará. No es raro que el validador use más memoria, y si para un problema se requieren >32MB pero al validador le dan 32MB, entonces pasará otra vez lo mismo.

**Comment by lhchavez** [comment]
Sí planeamos separar la memoria límite, pero más bien para establecerlo al máximo: no tiene sentido limitar al validador en términos de memoria, sólo de tiempo (para obligar a los autores a escribir validadores eficientes y que no desperdicien recursos).

**Comment by darkmx** [comment]
Al menos en mi experiencia, con el tiempo límite del envío ya estabamos algo forzados a escribir validadores eficientes, pero lo que reporté no me lo esperaba :( ojalá sea útil lo que les comenté.

**Comment by darkmx** [comment]
sin tener una lista de los problemas afectados, este issue es irrelevante para este momento
