### ISSUE TITLE
Como un creador de concursos y cursos de omegaUp for schools, quiero que sea obligatorio tener los campos de estado, país y escuela para poder presentar un concurso para que tengamos mejor información para poder informar a sus delegados

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1618]
## Comportamiento Esperado
Cuando un usuario quiera empezar un concurso, si no ha llenado esta información que le salga un mensaje que le impida comenzar el concurso hasta que los llene.

## Comportamiento Actual
Cualquier usuario sin datos completos puede entrar al concurso.

## Contexto
Ahora para el examen abierto de OMIP y OMIS queremos mandar una lista a cada delegado con los alumnos de su estado que lo presentaron. Hay muchos registros con nombre, estado, país en NULL. 
Envié correos a los usuarios pidiendo información extra, pero eso nos lleva a otra situación que es que los emails no están verificados y hay muchos emails incorrectos o inexistentes y no hay forma de contactar a los concursantes para pedirles el resto de sus datos.

**Comment by lhchavez** [comment]
Algo que se nos pasó es que quizás no sea una excelente idea obligar a todos los cursos/concursos a llenar su información (estoy _seguro_ que recibiríamos miles de quejas). entonces mejor hay que agregar una opción a los cursos/concursos para activar esto.
