### ISSUE TITLE
Regresión: el listado de cursos no se muestra

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1622]
## Comportamiento Esperado

Al entrar a https://omegaup.com/course/ no se muestra el listado de cursos.

Esto no pasa con todos los usuarios ya que un alumno que esta tomando el curso si puede verlo

## Comportamiento Actual

![image](https://user-images.githubusercontent.com/848246/33956290-b7425660-e003-11e7-8d54-454b7ec81e71.png)

el problema es que regresa 400 en /listCourses
![image](https://user-images.githubusercontent.com/848246/33956330-d697fe20-e003-11e7-9051-72cc88c57296.png)

**Comment by lhchavez** [comment]
Este fue el primer deployment en el nuevo host que tuvo una migración de esquema de la base de datos. Resulta que había una inconsistencia en Puppet donde ese host se considera como que "no tiene base de datos" (porque es verdad), pero no hay ningún target que haga ese deployment.

Abrí https://github.com/omegaup/omegaup/issues/1624 para trackear eso, pero este bug ya quedó arreglado.
