### ISSUE TITLE
Como un maestro de un curso quiero poder leer el progreso de los estudiantes cuando tengo muchas tareas

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1623]
## Comportamiento Esperado

En el curso introductorio de la OMI no se pueden ni los nombres de los alumnos ni los nombres de las tareas https://omegaup.com/course/Curso-OMI/students/

## Comportamiento Actual
![image](https://user-images.githubusercontent.com/848246/33956497-525b3c7a-e004-11e7-8fdc-7bcd089b313d.png)

## Posible Solución

Usar una tabla con scroll y de preferencia mobile friendly =)

**Comment by lhchavez** [comment]
De acuerdo con la posible solución.

Un workaround en lo que lo terminamos es exportar el progreso a una hoja de cálculo.

**Comment by pabo99** [comment]
La solución se discutió en #1685

**Comment by pabo99** [comment]
Así es como quedará la vista del progreso con scroll horizontal:

![sd 67 - fixes 1623 gif](https://user-images.githubusercontent.com/3230352/35901749-d3096922-0b9d-11e8-80d5-5bc422764d4a.gif)
