### ISSUE TITLE
Comenzar a usar promesas en vez de callbacks en operaciones bulk

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1625]
Para legibilidad de código, es recomendable utilizar promesas en vez de callbacks

## Comportamiento Esperado

Actualmente existe una función en `ui.js` llamada `bulkOperation` que sirve para iterar un elemento dado y esta realiza peticiones a algunas API's. Una vez realizado esto, regresa una respuesta por medio de un callback. Se pretende sustituir por promesas, ya que estas ayudan a mantener legibilidad en el código.

Los métodos que lo utilizan son: `makePublic` de `contest/list.js` y de `problem.mine.js`.

**Comment by antedotee** [comment]
Can you assign this issue to me?

**Comment by pabo99** [comment]
Apologies! This issue has already been resolved, so it can be closed.
