### ISSUE TITLE
(Calidad) Correo para reactivar problema reportado esta mal

### ISSUE THREAD

**Issue by Fer-OmegaUp** [omegaup/omegaup#1631]
deberia ser: quality@omegaup.com o calidad@omegaup.com
ahorita dice: omegaup@omegaup.com

**Comment by Fer-OmegaUp** [comment]
@lhchavez as FYI

**Comment by lhchavez** [comment]
no necesitas FYIearme, me llegan todos los correos de TODA la actividad de GitHub. y no filtro los mentions de manera especial.

**Comment by Fer-OmegaUp** [comment]
Ok, good to know
