### ISSUE TITLE
Posición con infinitos beepers, no se reestablece al regresar el mundo a su estado original

### ISSUE THREAD

**Issue by jofeque** [omegaup/omegaup#1632]
He escrito un programa en Java donde utilizará una posición con infinito número de beepers, he diseñado el mundo, al dar un click en el ícono de 'ver el futuro', y luego una vez ejecutado el programa y dar un click al ícono de 'regresar el mundo a su estado original', la posición donde indiqué infinito número de beepers, no se reestablece a infinito. Karel.js no coloca nada ahí

Se espera que al regresar el mundo a su estado original, la posición o posiciones que indiqué que tuvieran infinito número de beepers, lo sigan teniendo.

Estoy usando Chrome en Window 10, visitando https://omegaup.com/karel.js/

**Comment by lhchavez** [comment]
Gracias por reportarlo, lo moví al repositorio de karel.js
