### ISSUE TITLE
Soporte de múltiples dimensiones para el favicon

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#1638]
# Comportamiento actual
- Sólo cubrimos dimensión 64x64 para el favicon de omegaup.com
- Favicon no tiene fondo transparente, sino blanco. El estándar es usar fondo transparente. Esto es evidente cuando tu navegador tiene un tema "no blanco"
![image](https://user-images.githubusercontent.com/684205/34388652-931a007e-eafa-11e7-88ff-41ddf9271191.png)
- Favicon no ha sido regenerado después del último rediseño del logotipo de omegaUp. No se tiene garantía de que el favicon actual use Calibri Bold como lo usa el logo oficial

# Comportamiento deseado
- Soportar las dimensiones que diferentes clientes pidan (ver https://css-tricks.com/favicon-quiz/)
- Favicon necesita fondo transparente
- Asegurarnos de que el favicon actual sigue Calibri Bold como fuente, que es lo que define la última versión del spec del [logotipo](https://drive.google.com/open?id=16B8ZQOpiTLBeiuz3WGQa23LftHpDZLo2uvgNscfl18o)

**Comment by lhchavez** [comment]
Ah se me olvidó cerrar el issue. Gracias!
