### ISSUE TITLE
[FEATURE] Como problemsetter, quiero que los .in de mis problemas de sólo salida estén hosteados en omegaUp.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1660]
## Comportamiento Esperado

Cuando se sube un problema de sólo salida, subes el zip con los .in que quieres que puedan bajar los competidores. En la descripción del problema, puedes hacer referencia a los .in que subiste para que los puedan bajar los competidores, como en libinteractive que hay un tag especial que agrega el diálogo de descarga de las plantillas.

## Comportamiento Actual

Se sube el zip del problema con las entradas, pero no hay manera de que los competidores las bajen de omegaUp. Actualmente, los (pocos) problemsetters que usan problemas de sólo salida los acaban subiendo a un host como Dropbox y poniendo el link a las entradas en la descripción.

**Comment by lhchavez** [comment]
Esto necesita que el nuevo layout de los problemas esté finalizado.
