### ISSUE TITLE
No se pueden realizar envíos a un concurso que fue editado y no se seleccionó algún lenguaje

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1663]
Al intentar realizar un envío en arena, la plataforma devuelve un mensaje que indica lo siguiente:
```
El campo no está en el conjunto válido: language
```
 
## Comportamiento Esperado

Cuando se edita un concurso y un usuario ingresa al mismo, este debería poder realizar envíos, siempre y cuando el lenguaje seleccionado pertenezca a los lenguajes válidos para el concurso o si no fue setteado ninguno.

## Comportamiento Actual

Cuando se edita un concurso y no se selecciona ningún lenguaje de programación, esto no permitirá a los usuarios realizar ningún envío y les mostrará el mensaje antes mencionado.

## Posible Solución

Revisar que la validación de los datos antes de realizar un envío no esté ocasionando que algo falle.

## Pasos para reproducir (para bugs)

1. Crear un concurso, no seleccionar ningún lenguaje de programación
2. Editar el concurso sin seleccionar ningún lenguaje de programación
3. Ingresar al concurso para resolver problemas
4. Seleccionar cualquier problema, y después intentar realizar un envío

**Comment by pabo99** [comment]
Este bug ya no está apareciendo en la última versión. Algún cambio ya lo debió haber corregido

**Comment by elendil326** [comment]
Cerrando como "No Repro"
