### ISSUE TITLE
Link de creación de usuarios OVI

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1665]
El delegado de Veracruz me pregunto si podíamos crear el link de los usuarios para la próxima Ovi (olimpiada veracruzana) se estiman alrededor de 155 participantes a los cuales se desea crear una cuenta unica del evento.

Gracias, buen día.

**Comment by lhchavez** [comment]
para cuándo se ocupan? necesitamos al menos dos semanas de anticipación para crearlos y darles deployment.

**Comment by MiguelRomero** [comment]
Para el día 23, la olimpiada se realizara del 24 al 27 de enero.

**Comment by lhchavez** [comment]
Ejemplo: https://github.com/omegaup/omegaup/pull/1049/files

**Comment by lhchavez** [comment]
Se supone que con el refactor de identidad este tipo de cambios ya no van a ser necesarios.

**Comment by MiguelRomero** [comment]
¿Qué procede sempai?

**Comment by lhchavez** [comment]
Si puedes hacer un pull request similar a ese, estaría genial :D podrías simplemente modificar este: https://github.com/EfrenGonzalez/omegaup/blob/f57ab64be87612a5ab56b0e22acbbec5c4c8c396/frontend/server/controllers/UserController.php#L853-L861

para que diga OVI18

**Comment by MiguelRomero** [comment]
va
