### ISSUE TITLE
El texto de Problemas y Nombres en la vista de progreso de un curso no se despliega correctamente

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1685]
## Comportamiento Esperado

En la vista de `/students` de un curso, no importa qué tan grande hagas la ventana, la tabla no muestra más que iniciales tanto de los nombres de los estudiantes como los nombres de los problemas, y esto es muy difícil de interpretar. 

Exportarlo sí funciona y es un buen workaround, pero creo que puede ser tedioso tener que exportar cada que quieres interpretar la tabla.

## Comportamiento Actual
Solamente se muestran las iniciales de cada palabra

## Posible Solución
Hacer la tabla de tamaño dinámico, o si solo caben n caracteres, que sean los primeros n consecutivos para que por lo menos te des una idea de lo que quiere indicar.

## Pasos para reproducir (para bugs)

https://omegaup.com/course/Curso-OMI/students/ 

1. Entra a un curso que administres en omegaUp for Schools. 
2. Da click a Progreso de los estudiantes

## Contexto

Afecta para la interpretación de la tabla.

## Tu ambiente

https://omegaup.com/course/Curso-OMI/students/
![image](https://user-images.githubusercontent.com/5167417/35100743-86b11c62-fc22-11e7-8269-8b80b793dfde.png)

![image](https://user-images.githubusercontent.com/5167417/35100754-932f0738-fc22-11e7-8d80-9647b10a941f.png)

**Comment by lhchavez** [comment]
Te late agregar un toggle para activar y desactivar un scrollbar? Adicionalmente para los nombres de los problemas, podemos rotarlo para que quepa mejor horizontalmente.

**Comment by pabo99** [comment]
La solución puede ser algo así como lo que se hizo para cuando se unen los scoreboards, agregando un scroll horizontal y que toda la información se muestre desplazando la pantalla 
![sd 25 - fixes 1050 gif](https://user-images.githubusercontent.com/3230352/35103993-2e13e0c0-fc2d-11e7-9c02-b2acc34d166c.gif)

**Comment by andreasantillana** [comment]
Creo que sí está cool lo que propone @pabo99

**Comment by lhchavez** [comment]
tenemos consenso entonces! la propuesta de @pabo99 es la elegida!

**Comment by pabo99** [comment]
Revisando, este es un issue duplicado de #1623
