### ISSUE TITLE
Cambiar la leyenda del eje vertical en las estadísticas del usuario

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1686]
Actualmente dice: "Cantidad de problemas resuletos" pero la grafica de barras muestra la cantidad de envios segmentados por veredicto. Si fueran problemas resueltos deberiamos mostrar unicamente los "AC"

Propongo cambia la leyenda a ~"Camntidad de envios"~ [editor's note: `Cantidad de envíos`].

**Comment by NdubuisiO** [comment]
@elendil326  is this the page that shows user statistics https://omegaup.com/profile/victor123, if so where is the change to be made
