### ISSUE TITLE
Permitir a los usuarios cambiar la privacidad de su perfil

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1688]
Como un usuario de omegaUp, quiero poder cambiar la privacidad de mi perfil para que no se divulge información mía innecesariamente.

Reportado en https://omegaup.com/preguntas/1057/configuracion-del-perfil?show=1057

## Comportamiento Esperado

Mediante una configuración en el perfil, poder establecer que mi perfil no puede ser visto por otros usuarios. Una vez hecho esto, ni los problemas que he resuelto ni los concursos en los que he participado, ni los detalles del perfil (salvo el username) ni los detalles de envíos se deberían mostrar.

Posiblemente la única excepción sería un agregado de número de problemas resueltos y agregado de veredictos, siempre y cuando podamos hacer que tengan cierto delay (1 semana debería ser suficiente).

## Comportamiento Actual

Toda la información personal es accesible a todo el internet, lo que hace que algunas personas tengan miedo de usar la plataforma.

## Posible Solución

* Agregar una columna a la tabla `Users` para establecer si el perfil es privado.
* Si el perfil es privado, esconder toda la información mencionada arriba de `UserController::apiProfile` (a menos que seas ese usuario).

**Comment by AtharvaKhare** [comment]
Hey @lhchavez , I would like to take up this issue.
What should be default state of profile privacy - private or public?
Also, can you please translate " los detalles de envíos se deberían mostrar" (I cannot understand Google's translation)

**Comment by lhchavez** [comment]
that roughly means that the following graph that's currently shown in https://omegaup.com/profile/ (and the underlying data used to build it) should not be shown:

![image](https://user-images.githubusercontent.com/168028/36362186-230b7242-14e7-11e8-9b8d-208604b5c649.png)

That means that https://github.com/omegaup/omegaup/blob/c2e8d65d9ada21d07bddf28d00323a1407267c47/frontend/server/controllers/UserController.php#L1486 should probably raise a `throw new ForbiddenAccessException('userProfileIsPrivate');`. The `userProfileIsPrivate` is an identifier of a translation string, that you can find in `frontend/templates/en.lang` (and the corresponding `es.lang`, `pt.lang`, and `pseudo.lang`; the latter is generated after running `./stuff/i18n.py`).

Let me know if you need any additional help!
