### ISSUE TITLE
Hints en problemas

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#1690]
Como un problemsetter, me gustaría poder agregar hints a un problema, para que los usuarios que necesitan ayuda, puedan tener un poco de ella, dentro del problema.

## Comportamiento Esperado

Que el problema tuviera en su descripción, la posibilidad de solicitar un hint del problema en cuestión. La plataforma te daría acceso a ese hint, por tiempo (por ejemplo, puedes ver un nuevo hint cada 24 horas) o si cumples algunas restricciones (como puntaje mínimo o algo así).

## Comportamiento Actual

Actualmente no esta implementado.

Los usuarios, podrían tener ayuda en un problema sin la necesidad de que el problemsetter tenga que estar pendiente de las clarificaciones del problema.

## Posible Solución

Al redactar un problemas agregar el item #Hint y agregar la configuración para mostrarlo (por tiempo o puntaje). Agregas todos los #Hint que necesites, y que puedas tener acceso a ellos de acuerdo a la condiciones que se vayan cumpliendo.

**Comment by lhchavez** [comment]
esto es algo que hemos querido hacer desde hace tiempo, pero no se nos ha ocurrido una manera elegante de implementarlo porque sería necesario romper varias abstracciones que tenemos. esas abstracciones necesitan un refactor.

**Comment by pacharrin** [comment]
ya hay un issue de esto #821

**Comment by kukogit** [comment]
Leyendo el issue #821 sólo se parece en lo hint, pero a lo que me refiero es hints del problema, no de los casos en los que fallas.

**Comment by lhchavez** [comment]
Ya le cambié el título a #821 para que sea un issue unificado de hints en vez de tener dos muy similares que dependen entre sí.
