### ISSUE TITLE
Error con problemas que tienen INFINITOS

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#1694]
## Comportamiento Actual

Los problemas que fueron subidos hace tiempo a la plataforma, permitían el atributo mochilaKarel=INFINITOS sin embargo, ahora ya no lo permite, entonces cuando se evalua un submit para ese problema no obtienes los 100 puntos.

## Comportamiento Esperado

Que tanto el evaluador como karel.js continúen respetando la palabra INFINITOS para evitar conflictos con problemas viejos.

**Comment by lhchavez** [comment]
esto ya se había resuelto, no? https://github.com/omegaup/karel.js/commit/b5d5263018035584b88698149c55a99847b13912

**Comment by kukogit** [comment]
Hola lhchavez, supongo que no, porque este fin de semana me volvió a pasar.

**Comment by lhchavez** [comment]
existía exactamente un problema con un solo caso que tenía `INFINITOS`, así que mejor se editó ese único caso para que usara `INFINITO`.
