### ISSUE TITLE
[FEATURE] Crear un cronjob para exportar un snapshot anonimizado de la base de datos

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1696]
## Comportamiento Esperado

Que cada cierto tiempo (por ejemplo, semanalmente) se publique un subconjunto anonimizado de la base de datos de produccion con el objetivo de poder hacer analisis de datos

## Comportamiento Actual

La anonimizacion se hace a mano y bajo pedido

## Posible Solución

Crear un cronjob que exporte un subconjunto de los datos de produccion y los anonimice.
Mover el snapshot a una VM distinta a la de produccion en la cual se puede realizar el analisis.
Permitir acceso a esa VM a algunos miembros del staff, siguiendo los lineamientos de nuestra politica de privacidad

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

Nos hace falta poder hacer todo tipo de analisis para
a) mejorar el servicio a nuestro usuarios (por ejemplo, recomendar el siguiente problema a resolver)
b) identificar si estamos cumpliendo con la mision de la organizacion

**Comment by lhchavez** [comment]
En espera de consulta legal en México y Estados Unidos para ver qué es lo mínimo necesario, y cuáles son las mejores prácticas.

**Comment by pabloaguilar** [comment]
Fixed con la réplica limitada que usa Metabase?

**Comment by lhchavez** [comment]
sí!
