### ISSUE TITLE
Vueificar https://omegaup.com/scoreboardmerge.php

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1707]
Como mantenedor de omegaUp, y en el interés de la seguridad de los usuarios, me gustaría que no hubiera lugares en el código de JavaScript donde se construya manualmente el HTML.

https://omegaup.com/scoreboardmerge.php es uno de esos lugares, y para tener consistencia con el resto de la plataforma, debería estar escrito en Vue.

## Comportamiento Esperado

`$(...).html(...)` no debería aprecer en el codebase.

## Posible Solución

Convertir scoreboardmerge a Vue.

**Comment by CarlosCordova18** [comment]
Ok I'll take this, but please give me some time to do it because I'm starting with Vue.

**Comment by lhchavez** [comment]
of course, that was taken into account choosing the bug so that it's not urgent and it's not blocking anything else, so you can progress at your own pace.

**Comment by CarlosCordova18** [comment]
Should I include the CDN of Vue Js in the `scoreboardmerge.js` script? Or is there a Vue JS file which I could reference to?

**Comment by lhchavez** [comment]
no need: we use webpack for that!

you can follow this PR: https://github.com/omegaup/omegaup/pull/1159

since you are changing a top-level file (one that is directly included from
an html file) you need to add an entry into webpack.json, similar to that
PR. webpack takes care of bundling+minimizing Vue into the final .js

**Comment by CarlosCordova18** [comment]
Hi @lhchavez, one question, should I create just one component (`myName.vue`) or I could create all that I need to solve this issue?

**Comment by lhchavez** [comment]
You can create just one component, or create subcomponents. whatever makes
more sense, I'll leave that up to you!

**Comment by CarlosCordova18** [comment]
I've made the modifications, please give them a look.
