### ISSUE TITLE
El parámetro "Límite de pila" está siendo ignorado

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#1709]
Hola amigos de OmegaUp, recientemente acabo de subir un problema en el que puse un límite de pila bastante alto (20MB) pero programas que apartan un arreglo de 10MB están muriendo. Aparentemente el parámetro está siendo ignorado por la plataforma.

El problema es https://omegaup.com/arena/problem/Partiendo-cadenas y un envío donde se muestra el problema es el 7b1e0914.

**Comment by lhchavez** [comment]
ah sí, deberíamos quitar esa opción porque ahora el límite de pila es
"infinito" (en realidad estamos contando la pila contra el límite total de
memoria).

**Comment by darkmx** [comment]
mmm... el problema tiene de límite 96MB pero aún así están muriendo los programas :\ si la pila es infinita creo que no debería ocurrir eso, pero no se me ocurre qué podría estar pasando.

**Comment by lhchavez** [comment]
ya encontré el problema: hay un bug de minijail (la librería que usamos para hacer el sandboxing) que está evitando que podamos establecer el límite de pila de manera correcta.

como en dos semanas debe estar resuelto.

**Comment by lhchavez** [comment]
Arreglado en https://github.com/omegaup/omegajail/commit/8f48852e67ecf327867c1df2f34ad90a9bce1f70, hoy en la noche se hace deploy.

**Comment by darkmx** [comment]
gracias :)
