### ISSUE TITLE
Regresión: El dropdown de typeahead se muestra incorrectamente

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#1710]
## Comportamiento Esperado

Los cuadros de texto para buscar (problemas y usuarios), despliegan erróneamente la información.

## Comportamiento Actual

Al escribir en los cuadros de texto, la lista que se despliega aparece con errores y es difícil elegir la opción correcta.

## Pasos para reproducir (para bugs)

1. Entrar a la sección de problemas (o de agregar un problema o usuario en uncontest)
2. Escribir algunas letras y la lista con errores se desplegará.

**Comment by lhchavez** [comment]
Espero que quede listo para el deploy de hoy en la noche.
