### ISSUE TITLE
Encontrar una manera de correr CoderOfTheMonthTest::testCoderOfTheMonthAfterYear sin que falle un par de veces al año

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1713]
CoderOfTheMonthTest::testCoderOfTheMonthAfterYear hace aritmética de fechas y falla al menos tres veces al año: cerca de Febrero (por tener menos días), y los días donde hay cambio de DST.

Hay que encontrar una manera de que funcione bien los 365 días del año. Parece que hay que dejar de usar las funciones de aritmética de fechas de PHP porque están súper rotas :/

**Comment by pabo99** [comment]
Hice un análisis del comportamiento de dicha prueba y obtuve lo siguiente:
Se simuló la prueba haciendo una ejecución día a día desde hace un año hasta hoy, con el Hotfix #1714  parece que se resuelve el problema de las funciones de aritméticas en las fechas, como se puede comprobar en la siguiente imagen: 

![captura de pantalla 2018-02-11 a la s 09 43 59](https://user-images.githubusercontent.com/3230352/36075383-d505f24e-0f13-11e8-902c-eae166265b7b.png)
 
Para revisar que realmente funciona con el cambio del hotfix antes mencionado, se regresó el código a como estaba anteriormente, encontrando la falla que ocurría. La prueba falló los siguientes días:

- 31 - Marzo
![captura de pantalla 2018-02-11 a la s 09 43 40](https://user-images.githubusercontent.com/3230352/36075445-b311dd78-0f14-11e8-95be-1730ec46cc4b.png)

- 31 - Mayo
![captura de pantalla 2018-02-11 a la s 09 48 13](https://user-images.githubusercontent.com/3230352/36075448-bb84ebee-0f14-11e8-9b58-2c965eb898ea.png)

- 31 - Agosto
![captura de pantalla 2018-02-11 a la s 09 51 55](https://user-images.githubusercontent.com/3230352/36075453-c29704d0-0f14-11e8-828d-53169bd084af.png)

- 31 - Octubre
![captura de pantalla 2018-02-11 a la s 09 54 24](https://user-images.githubusercontent.com/3230352/36075456-c8f5c5dc-0f14-11e8-8cfc-ca38b66e4a0f.png)

- 29 - Enero
- 30 - Enero
- 31 - Enero
![captura de pantalla 2018-02-11 a la s 09 58 16](https://user-images.githubusercontent.com/3230352/36075459-d41a54f0-0f14-11e8-89fe-fa7bc14a935e.png)


Esto porque, efectivamente, al utilizar las funciones de aritmética de fechas, cuándo un mes tiene sólo 30 días ya no se obtiene la fecha deseada.

No encontré fallas en los días donde hay DST, no sé si me falte contemplar más casos.

Tengo la duda si sea buena idea subir la prueba, debido al tiempo que tarda en ejecutarse (aproximadamente 10 minutos) y además es sólo una simulación.

**Comment by lhchavez** [comment]
Parece que el único lugar donde hacemos este tipo de aritmética de fechas (en PHP) es en las pruebas. si ya no va a causar problemas, supongo que podemos cerrarlo como arreglado.

Gracias por confirmar!
