### ISSUE TITLE
Hacer una consulta (y una prueba) para obtener la lista de problemas no-resueltos

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1716]
Como un concursante, quiero ver qué problemas he intentado, pero no resuelto.

Ver https://github.com/omegaup/omegaup/issues/1711 para más información.

Este issue es únicamente para hacer el API, la consulta y la prueba.

**Comment by CarlosCordova18** [comment]
I would like to create this query and test it to create later the API. I just installed the development environment, what should I do to work now with the database?

**Comment by lhchavez** [comment]
You can base your change on another PR that does more or less the same thing, like https://github.com/omegaup/omegaup/pull/1760/files.

Rough sketch of the steps needed:

* Create a new file under `frontend/database` named `number_description.sql`, where `number` is the next available unused integer.
* Run `./stuff/database_schema.py fix --all-files` to regenerate `frontend/database/schema.sql` so that you don't do it by hand, which is painful and error-prone.
* Run `./stuff/update-dao.sh` to regenerate the database schema bindings with PHP.
* Edit `frontend/server/controllers/ProblemController.php` and add a new function called `apiListUnsolvedProblems()` (the `api` prefix means that it can be called as a REST endpoint from `http://localhost:8080/api/problems/listUnsolvedProblems/` automatically). Make this function as similar as possible to the other ones already in that file.
* You will also need to edit `frontend/server/libs/dao/Problems.dao.php` so you can write the SQL query to get the information needed.
* Write a test! You can add it to `frontend/tests/controllers/ProblemListTest.php`.

And ask any additional questions you have :D

**Comment by CarlosCordova18** [comment]
The script .`/stuff/database_schema.py fix --all-files` throws me this error:

> File "stuff/database_schema.py", line 19
    def _expected_database_schema(*, config_file=None, username=None,
                                   ^
SyntaxError: invalid syntax

And also, is there any place where I could take a look on the E-R diagram of the database or just I ought to deduce it from the **schema.sql** script?

Thanks!

**Comment by lhchavez** [comment]
hmm that's odd. that only happens if you try to run it as a python2 script (in other words, if you invoke it as `python stuff/database_schema.py fix --all-files`).

That file has a `#!/usr/bin/python3` at the top, which should force it to run with python3. Are you by any chance running this outside of the VM? If so, try running it inside.

For the ER diagram, you can use https://www.mysql.com/products/workbench/, create a new model and then "reverse-engineer" the `schema.sql`. You can then use Model > Create Diagram from Catalog Objects and finally Arrange > Autolayout to make sense of the mess.

**Comment by CarlosCordova18** [comment]
Thanks, it was just running the script with **python3**.

I think that it won't be necessary to create a file under `frontend/database` because no alteration on the database will be done. I've created the function `apiListUnsolvedProblems()` in the `User Controller`, because the function to get all the solved problems by user has been created there also.

I haven't done the test yet, but could you please tell me how to run it when it's done?

**Comment by lhchavez** [comment]
`./stuff/runtests.sh` runs ALL the tests (it'll take s bit of time).

to run just the unit tests you can run

```

/usr/bin/phpunit \
	--bootstrap frontend/tests/bootstrap.php \
	--configuration frontend/tests/phpunit.xml \
	frontend/tests/controllers
```

you can choose to run just a subset of the tests by specifying one of the files under `frontend/tests/controllers` instead of the whole directory.

**Comment by CarlosCordova18** [comment]
I ran the code but it throws me an error that, because of how little I know about REST API and Unit Tests, I can't understand why is it being thrown, and turns everything so difficult to debug 😕
Are there any resources that I could read to understand better these things in the project?

**Comment by CarlosCordova18** [comment]
I created a pull request, please take a look on it here: https://github.com/omegaup/omegaup/pull/1765/files

**Comment by CarlosCordova18** [comment]
I created a pull request, please take a look on it here: https://github.com/omegaup/omegaup/pull/1765/files

**Comment by lhchavez** [comment]
Oh I forgot to use the magic tag "Fixes: ..." and this didn't auto-close. But this is complete!
