### ISSUE TITLE
Como maestro quiero saber que problemas intentaron resolver mis alumnos

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1717]
Como maestro quiero saber que problemas intentaron resolver mis alumnos

Ver detalles completos en https://github.com/omegaup/omegaup/issues/1711

# Posible solución

hay que definir un rol de maestro, de alguna manera otorgar este permiso de parte de los estudiantes para los maestros, y que el maestro pueda ver esta lista, aún si el perfil es privado.

Esto es similar a https://github.com/omegaup/omegaup/issues/1137

**Comment by warrioru** [comment]
Hey! I'd like to contribute to this issue. I already installed the dev environment and ran the scripts to regenerate the schema and the schema bindings. An explanation like: [#1716 (comment)](https://github.com/omegaup/omegaup/issues/1716#issuecomment-366811775) would be very helpful.
So far the first steps would be to define the new Teacher role, and set the permissions on the student profile so the teacher can see this information?
