### ISSUE TITLE
Como creador de concursos de OMI quiero poder clonar concursos para crear su versión pública

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1725]
## Comportamiento Esperado

Que al dar click en un botón de "clonar" para un concurso se cree su copia idéntica con la misma configuración y mismos problemas.

## Comportamiento Actual

Actualmente para crear la versió pública de un concurso, hay que crear uno nuevo y agregar los problemas y configuraciones manualmente copiando del concurso que se quiere replicar.

## Posible Solución

Creo que podría ser una sección en la vista de edición del concurso o que aparezca la opción cuando se selecciona un concurso en la vista de la lista de mis concursos.

## Contexto

No es un gran problema, pero creo que sí nos podría ayudar mucho sobre todo en tiempos de OMI.

**Comment by lhchavez** [comment]
ya soportamos clonar cursos, así que esto es algo más que razonable. :+1:

**Comment by alirizwi** [comment]
@lhchavez I want to work on this issue.

**Comment by lhchavez** [comment]
assigned to @alirizwi!

**Comment by alirizwi** [comment]
@lhchavez Sorry, couldn't work for last few days due to mid-semester exams in college. Am working now and will make a PR shortly.

**Comment by lhchavez** [comment]
no rush, hope you did well in your exams!

**Comment by alirizwi** [comment]
@lhchavez I am getting 400 Bad request when I try to clone a contest. I have created an API `/api/contest/clone/`, added apiClone function in `ContestController.php` and made necessary frontend changes in the js and template files. Am I missing something?

**Comment by alirizwi** [comment]
@lhchavez The API I created `/api/contest/clone/` is unable to handle POST requests, that's the reason I am getting 400 Bad request error, but it is able to handle GET requests. Do I need to add/change something to make it handle POST requests?
