### ISSUE TITLE
El problema 'chocolates' está roto

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#1727]
## Comportamiento Esperado
Como administrador del problema, al editar problema espero que el formulario se llene con los detalles existentes, y la redacción también. Esto ya sucedía, suena a regresión.

## Comportamiento Actual

Como administrador (nota, yo soy super admin, no sé si eso impacte), intento editar la redacción de un problema y/o detalles pero no puedo: el título da `Editar Problema undefined`, los detalles del problema no se auto-llenan (ver screenshot abajo) ni tampoco la redacción.

## Posible Solución

En network,
`https://omegaup.com/api/problem/details/`  con  `statement_type=markdown&problem_alias=chocolates` está regresando:

`{"status":"error","error":"Oops. Ocurri\u00f3 un error interno. Por favor int\u00e9ntalo nuevamente.","errorname":"generalError","errorcode":500,"header":"HTTP\/1.1 500 INTERNAL SERVER ERROR"}`

## Pasos para reproducir (para bugs)

Estoy entrando vía `https://omegaup.com/problem/chocolates/edit#edit`

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

Nublado :( 

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome 63.0.3239.132
* Sistema Operativo y versión (escritorio o móbil): macosx escritorio
* Link al sitio en el que este problema pasa: `https://omegaup.com/problem/chocolates/edit#edit`
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/207097/35773175-491a6536-08ff-11e8-91e3-fcb467c7c96c.png)

![image](https://user-images.githubusercontent.com/207097/35773176-514131e0-08ff-11e8-81b3-20bceadbc824.png)

**Comment by lhchavez** [comment]
Este problema tiene una redacción malformada y [`json_encode`](http://php.net/manual/en/function.json-encode.php) está explotando. En paralelo hay que intentar agregar `JSON_PARTIAL_OUTPUT_ON_ERROR` a las opciones de `json_encode` y corregir la redacción de ese problema en parciular.

**Comment by lhchavez** [comment]
Listo, ya se corrigió la redacción para que no tuviera utf-8 inválido.
