### ISSUE TITLE
El navbar se convierte en un monstruo cuando se reduce el ancho de la ventana del navegador.

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1737]
## Comportamiento Esperado
Que el menú en ventanas "angostas" se convierta en una barra donde le das click a un botón y se despliegan los elementos.

## Comportamiento Actual
Si reduces el ancho del navegador, el menú se expande verticalmente bloqueando la vista del resto de la página.

## Posible Solución
No sé cómo se arregla, en el sitio de omips bootstrap hizo la magia. 

## Pasos para reproducir (para bugs)

1. Ve a omegaup
2. Reduce el ancho de tu navegador

## Contexto

Cuando no tengo monitor externo y necesito consultar cosas en otro lugar para agregarlo a omegaup tengo que estar cambiando de escritorio porque si divido la pantalla para que quepan 2 ventanas, el menú invade todo.

## Tu ambiente

* Nombre del navegador: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5167417/36054693-6ceaf92c-0dbd-11e8-989f-01ad46e44c6e.png)

**Comment by npave** [comment]
Ya va a quedar arreglado, está en sanbox. Deberia estar en el deployment de este fin de semana.

![hamburguesa](https://user-images.githubusercontent.com/940007/36056266-d49761c4-0db7-11e8-8fd9-26e417e8ede3.png)

**Comment by lhchavez** [comment]
El bugfix más rápido del oeste: arreglado antes de que fuera reportado!
