### ISSUE TITLE
Existen peticiones a API's de Concursos en Cursos

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1740]
Cuando entro a un curso y comienzo a realizar envíos, me aparecen en la consola de Javascript errores de llamadas a APIs de concursos

## Comportamiento Actual

Al revisar la consola de Javascript me percato que hay llamados a `API.events`que se encuentra en `contest`

![captura de pantalla 2018-02-12 a la s 10 58 34](https://user-images.githubusercontent.com/3230352/36109915-7de77b4e-0fe6-11e8-92a7-3651615f380a.png)

**Comment by lhchavez** [comment]
El backend ha sido actualizado! `vagrant provision` debería traer el nuevo backend y ya debería entender el concepto de problemsets.

**Comment by pabloaguilar** [comment]
(perdon por llegar tarde a comentar)
Que no el fix deberia ser solo quitar la llamada a `events` cuando `arena` no haya recibido un `contest_alias`? Esto porque los casos de uso de cursos y de entrevistas no tienen por que recibir eventos, que yo sepa, solo voy a ver mis soluciones, y no la de otros participantes.
