### ISSUE TITLE
Hacer opcional el mostrar usuario en el rank general

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#1750]
*Como usuario, quiero tener la posibilidad de no aparecer en el rank general*

## Comportamiento Esperado

Que sea opcional aparecer en el rank

**Comment by lhchavez** [comment]
This query needs to take into account the user's `is_private` setting:

https://github.com/omegaup/omegaup/blob/8855dcb75086722877a887d146402a88ba94b9d8/stuff/cron/update_user_rank.py#L37-L64

**Comment by CarlosCordova18** [comment]
@lhchavez  I want this one!!!

**Comment by lhchavez** [comment]
Assigned to @CarlosCordova18 !

**Comment by CarlosCordova18** [comment]
One question, where do I need to create the test for this modification?

**Comment by lhchavez** [comment]
Here's the best place to do so: https://github.com/omegaup/omegaup/blob/master/frontend/tests/controllers/UserRankTest.php there's already a bunch of tests, so copy one and modify it to fit your needs.

**Comment by CarlosCordova18** [comment]
I've created the PR, if you can, please assign me another issue to fix :D
