### ISSUE TITLE
Assign colors to usernames depending on their position in the rank

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1752]
This should be part of the "User recognition and motivation" project. @Fer-OmegaUp please assign it to me.

**Comment by lhchavez** [comment]
One question though, is the current, janky ranking formula good enough? The current difficulty falloff has received negative feedback since it's too sharp.

**Comment by heduenas** [comment]
Well, the ranking formula itself I think is a different issue. When designing the color system we should do it in a way so that it's easy to migrate it to a different ranking formula. I was thinking that we can do it by percentiles (e.g. top 1% get assigned color red). That way, the ranking formula doesn't affect the color system at all.

**Comment by lhchavez** [comment]
As long as that doesn't incur an excessive extra cost, :+1:.

**Comment by heduenas** [comment]
I wrote a short design doc, please review https://docs.google.com/document/d/1R14hS-6TEhE34Aw3Pu_85jqIZjCyxVx6fiCHL8cvLg0/edit#heading=h.11f71ntnc2lp

**Comment by heduenas** [comment]
I've divided this issue in 4 work items:
* Backend: #1771
* Display rank field in user's profile: #1772
* Vue component to display colorful usernames: #1773 
* Use Vue component in FE to display usernames: #1774

**Comment by carlosabcs** [comment]
@lhchavez close this one too please
