### ISSUE TITLE
Me aparece un error al agregar tags a un problema

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#1753]
Cuando agrego dos veces un tag un problema me aparece el siguiente error: 

![captura de pantalla 2018-02-16 a la s 08 01 10](https://user-images.githubusercontent.com/3230352/36311161-fabd344a-12ef-11e8-9fd4-26cb5054595c.png)

## Pasos para reproducir (para bugs)

1. Agregar un tag a un problema
2. Agregar nuevamente el mismo tag

**Comment by jaykay12** [comment]
@pabo99 Is there any IRC or slack channel available for the omegaUp organisation?? I need some help in the build process, I am struck.
Any mailing list where I can get replies to my query will be really helpful.

**Comment by pabo99** [comment]
@lhchavez, @alanboy can you help us with this?

**Comment by jaykay12** [comment]
@pabo99 
I was unable to build using the normal recommended manner using Vagrant, so I used the Manual Installation.

I am able to run omegaUp on my localhost, but the login functionality is not working. What's more troubling is the error its showing,
Its asking me to run `cd /opt/omegaup && yarn install && yarn run dev`
These particular commands were asked to run only when we build using Vagrant but in my case no omegaup directory was created in the /opt path

**Comment by lhchavez** [comment]
@jaykay12 that should have been fixed by https://github.com/omegaup/deploy/pull/10 . @heduenas will contact you with information about where those kind of conversations will happen, mainly to avoid having unrelated conversations in issues. it gets a bit hard to keep track of the discussion at hand ^^;;;
