### ISSUE TITLE
Disponibilidad de CSharp

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#1761]
Como un DOCENTE, quiero que CSharp se pueda utilizar en todos los problemas de lenguaje de algo nivel para utilizar problemas que fueron creados antes de que CSharp estuviera disponible para las evaluaciones.

Actualmente, los problemas que se crean para C, C++, java etc. también pueden ser enviados con CSharp pero en problemas anteriores, supongo que antes de que CSharp estuviera disponible como lenguaje pues ahí no se pueden evaluar.

**Comment by lhchavez** [comment]
Todos los problemas viejos que se pueden resolver con lenguajes no-karel ahora también se pueden resolver con C#.

**Comment by licgerman** [comment]
Excelente. Gracias !!!
