### ISSUE TITLE
Sugerencia: conversión de saltos de línea del estilo "Mac viejo"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#1763]
Hola amigos de OmegaUp.

Recientemente subí un problema que es traducción de un problema viejo de otros jueces y conseguí un archivo de casos de prueba que decidí usar (para evitar tener que generar mis propios casos, aunque le hice algunas modificaciones). 

Los casos parecían funcionar bien en mi computadora con Windows, pero cuando lo subí a OmegaUp todos los programas daban "Error en ejecución". Cuando verifiqué que en Linux todo funcionaba bien, descargué los casos que OmegaUp había almacenado y me di cuenta que los saltos de línea habían desaparecido, por lo que algunos enteros se habían "concatenado" y terminaban formando numerotes que causaban que el programa muriera. Noté entonces que el archivo de casos de prueba original usa sólo el caracter \r como salto de línea, pero al parecer OmegaUp los quita con la intención de convertir saltos de línea \r\n en saltos de línea \n al estilo Unix.

Sugiero que el algoritmo de conversión de saltos de línea también tome en cuenta la posibilidad de que los archivos usen saltos de línea \r. Sería buena idea hacer esto si en algún momento se quisieran migrar en masa varios problemas viejos de otros jueces en línea.

**Comment by lhchavez** [comment]
En efecto, ignoramos los saltos de línea `\r` totalmente :( https://github.com/omegaup/omegaup/blob/master/bin/normalizr.cpp#L83

Se aceptan pull requests para eso :D se ve bastante sencillo de arreglar.

**Comment by darkmx** [comment]
Por lo pronto, según yo podría quedar:

case '\r': {
   ch = f.get( );
   if (ch == '\n') {
      // lo de '\n'           // aunque se verá feo duplicar el código
   } else if (ch != EOF) {
      f.putback(ch);
   }
   break;
}

A ver si mañana hago el pull request, tengo que averiguar cómo se hacen D:

**Comment by lhchavez** [comment]
Alternativamente cuando veas un `\r` prendes una bandera, y si ves un caracter que no sea `\n` y la bandera sigue encendida, imprimes un salto de línea legítimo y limpias la bandera. así evitas el uso de `putback`, que la verdad me da un poco de miedo usar porque complica bastante el modelo mental.

acá hay un tutorial de cómo hacer un pull request: https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-Hacer-un-Pull-Request

**Comment by darkmx** [comment]
creo que tengo sueño para escribir código ahorita XD mañana intento hacer el pull request
