### ISSUE TITLE
Soporte: Restablecer contraseñas para que los site-admins no tengan que hacerlo

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1770]
Como un miembro del comité de soporte, quiero poder restablecer contraseñas para que los site-admins no tengan que hacerlo.

Caso de uso: alguien envía un correo a omegaup-soporte@googlegroups.com con su nombre de usuario. Eso es suficiente para validar que es el dueño de la cuenta. Se puede entonces manualmente invocar https://github.com/omegaup/omegaup/blob/5103711b9dba9433e4491273d61127f510d3c522/frontend/server/controllers/ResetController.php#L11 (que necesitaría un parámetro para decidir si se va a enviar o no el correo, y únicamente se le hace caso si se es un miembro del equipo de soporte).

Parte de #1560

**Comment by elendil326** [comment]
@lhchavez cuál es el caso de uso aquí? No está esto ya automátizado del lado del usuario? Es decir, el usuario mismo puede soliticar el cambio de contraseña. Tengo miedo a suplantación de identidad.

**Comment by lhchavez** [comment]
en teoría. en la práctica algunos servidores de correo no aceptan nuestros correos :( (como Outlook)

**Comment by pabo99** [comment]
Sólo que hay un pequeño problema, el token se envía por correo y justo después se encripta con `SHA1`, entonces no encuentro la forma de volver a generar la liga para enviársela posteriormente, a menos que se almacene sin encriptar. ¿Que me recomiendas hacer en ese caso?
