### ISSUE TITLE
[Color Hierarchy] Display "Rank" field below "Graduation date" in user's profile page

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1772]
This depends on back end change #1771 

We should add the field “Rank” below “Graduation date” in https://omegaup.com/profile/xyz. Its value will be Unrated/Beginner/Specialist/Expert/Master/International Master and should be displayed with the color associated with it as described in the desing doc: https://docs.google.com/document/d/1R14hS-6TEhE34Aw3Pu_85jqIZjCyxVx6fiCHL8cvLg0/edit#

**Comment by heduenas** [comment]
Cost estimate: 1 hour

**Comment by heduenas** [comment]
Sorry Carlos, this bug was claimed by Priyam on the slack first. But we can assign #1773 if you want.

**Comment by CarlosCordova18** [comment]
@heduenas 😢 , I'm now starting to learn Vue, but I could give it a try

**Comment by heduenas** [comment]
@pj1527 Are you still working on this issue or can we assign it to someone else?

**Comment by pj1527** [comment]
I would like to work on it but I am busy with few other things, if urgent you can assign someone else otherwise I can resume working on it next week.

**Comment by heduenas** [comment]
@pj1527 we can wait a week. Thanks for working on it!

**Comment by carlosabcs** [comment]
@lhchavez please close this issue 🙏
