### ISSUE TITLE
[Color Hierarchy] Make a Vue component to display usernames

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1773]
This Vue component should display usernames with the color associated to their rank as described in the design doc: https://docs.google.com/document/d/1R14hS-6TEhE34Aw3Pu_85jqIZjCyxVx6fiCHL8cvLg0/edit#

**Comment by heduenas** [comment]
Cost estimate 4 hours.

**Comment by akash-1024** [comment]
I'd like to work on this.
Where can I find the HTML, CSS and JS files?

**Comment by heduenas** [comment]
@akash-1024, this issue consists of creating a Vue component rather than touching html files. Something more or less like this:
https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/components/coderofthemonth/Notice.vue

**Comment by akash-1024** [comment]
Sure!
If allowed to, I would also like to put my efforts on issue #1771 as I have worked with PHP on a couple of projects.

**Comment by heduenas** [comment]
well, #1771 is already assigned to @randika96

**Comment by SMe12435** [comment]
@lhchavez all i have to do is use the Backend API and collect **Problems solved** and assign color according to that number, right?
P.S.  Sorry for being inactive for the last couple of days. it was due to my mid-semester examinations.

**Comment by heduenas** [comment]
@SMe12435 You have to get the user's rank from apiProfile() and display it using the color corresponding to it.

User's rank was introduced into apiProfile() in https://github.com/omegaup/omegaup/commit/4c3420988907ef0356c2b779358d959b90277f69

**Comment by lhchavez** [comment]
@SMe12435 no worries, your exams have way higher priority!

**Comment by heduenas** [comment]
@SMe12435 are you still working on this issue or can we assign somebody else to it?

**Comment by heduenas** [comment]
@CarlosCordova18 will work on this issue.

**Comment by heduenas** [comment]
Respuestas a la segunda y tercera preguntas:
* Si, `<span>` y le pones una clase css dependiendo de su rank.
* No se si es la unica, pero yo diria que si es suficiente con probar diferentes ranks en alguna de las vistas y verificar que se muestra como se espera.
