### ISSUE TITLE
Como maestro de un curso quiero ver un feed de la actividad de un curso

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1782]
## Comportamiento Esperado

Como maestro de un curso quiero poder saber si los usuarios han entrado al curso y qué problemas han intentado para poder darle seguimiento y ayudarles a los que están atorados. 

## Comportamiento Actual

actualmente la unica forma de ver el progreso es usando el scoreboard pero eso no te dice que cambio de una semana a otra haciendo dificil el seguimiento a la spersonas que sí lo estan intentando
## Posible Solución

una posible solucion es tener solo un feed con eventos como X ha intentado enviar una solucion para Y con un veredicto de Z

otra posible solucion es tener un dashboard de estadisticas tanto generales como de la ultima semana entre los datos a saber serias, envios, usuarios más activos, distribución de puntajes.

**Comment by lhchavez** [comment]
Supongo que esto se puede modelar de manera casi idéntica al reporte de actividad de los concursos.
