### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#1786]
*En el caso de un feature, provee un título en el siguiente formato:*

*Como un [tipo de usuario], quiero [funcionalidad o mejora esperada] para
[beneficio esperado]*

*E.g. Como [usuario], quiero [un botón de inicio] para [poder regresar a la
página inicial con un solo click]*

## Comportamiento Esperado

*Si estás describiendo un bug, describe lo que pasó*

*Si estás sugiriendo un cambio/mejora, describe cómo debería funcionar*

## Comportamiento Actual

*Si estás describiendo un bug, dinos lo que paso en lugar de lo que se
esperaba*

*Si estás sugiriendo un cambio/mejora, explicanos la diferencia con la
funcionalidad actual*

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
* Sistema Operativo y versión (escritorio o móbil):
* Link al sitio en el que este problema pasa:
* Captura de pantalla:

**Comment by lhchavez** [comment]
?

**Comment by licgerman** [comment]
Perdón, se fue un enter sin querer. ¿Pueden borrar este issue? Ya subí el correcto.
