### ISSUE TITLE
Visualizar top users del mes

### ISSUE THREAD

**Issue by manduinca** [omegaup/omegaup#1790]
*Como un usuario, quiero visualizar los top coders del mes para poder motivar la competición y se aprecie claramente al ganador*

## Comportamiento Esperado

*Así como podemos ver los top coders y las esculeas más activas, debería mostrarse una tabla con los top coders del mes*

## Comportamiento Actual

*No se muestra una tabla con los top coders del mes*

## Posible Solución

*Tendríamos que calcular el puntaje de los usuarios en el mes, seguro un query que agrupe por users y sume el puntaje en el úlitmo mes, y crear una tabla para la visualización*

**Comment by SpaceWhite** [comment]
Can someone assign me this task?

**Comment by CarlosCordova18** [comment]
Hi, @lhchavez I want to take this issue!

**Comment by SpaceWhite** [comment]
@CarlosCordova18 I'm doing this issue @lhchavez  Can you assign this task for me?

**Comment by heduenas** [comment]
@SpaceWhite are you still working on this issue or can we assign it to someone else?

**Comment by SpaceWhite** [comment]
I'm working on another issue please assign this to another someone else @heduenas

**Comment by lhchavez** [comment]
Marking as available

**Comment by CarlosCordova18** [comment]
@lhchavez este issue aún no está resuelto? Si es así, puedo tomarlo yo?

**Comment by SpaceWhite** [comment]
@CarlosCordova18 Actually I’ve coded this issue. I’ll make PR tomorrow :).

**Comment by CarlosCordova18** [comment]
Oh, okay :D

**Comment by tvanessa** [comment]
El tab *Top coder monthly list* solo muestra un usuario y deberia mostrar el top 100 del mes
![Screen Shot 2019-10-22 at 12 28 31 AM](https://user-images.githubusercontent.com/13296248/67265577-ef48aa80-f462-11e9-96d6-543a8d43777a.png)

**Comment by tvanessa** [comment]
Este issue deberia estar cerrado o falta algun otro componente?

**Comment by tvanessa** [comment]
Resuelto de #1938
