### ISSUE TITLE
[FEATURE] Como un concursante, quiero tener la posibilidad de codificar los problemas con Rust para tener una opción diferente para poder resolver los problemas. 

### ISSUE THREAD

**Issue by rysard** [omegaup/omegaup#1796]
Hola, me gustaria ver si me ayudan a agregar esta funcionalidad, o si me asesoran para poder agregarla yo mismo a la plataforma.

**Comment by lhchavez** [comment]
es un proceso un tanto largo y complicado:

* Hay que hacer un cambio en https://github.com/omegaup/omegajail/blob/master/tools/mkroot para crear un ambiente de compilación/ejecución para Rust
* Hay que agregar Rust a https://github.com/omegaup/omegajail/blob/master/smoketest/test
* Hay que agregar Rust a https://github.com/lhchavez/quark/blob/80f20c648737a115fb4dc87c990634bd7993fa0d/runner/sandbox.go#L157 y https://github.com/lhchavez/quark/blob/80f20c648737a115fb4dc87c990634bd7993fa0d/runner/sandbox.go#L328
* Finalmente, hay que agregar una prueba en https://github.com/lhchavez/quark/blob/80f20c648737a115fb4dc87c990634bd7993fa0d/runner/runner_test.go#L155

Pero sí deberíamos tener soporte de Rust!

**Comment by SpaceWhite** [comment]
I'd like to take this ticket. Can @lhchavez assign this issue to me?

**Comment by lhchavez** [comment]
of course :D

**Comment by pabloaguilar** [comment]
Fixed
