### ISSUE TITLE
Agregar links administrativos en la vista de editar concurso

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1797]
Como administrador de un concurso, me gustaría poder acceder a los enlaces que aparecen en `/contest/mine/` (como los links al scoreboard y el reporte de actividad):

![image](https://user-images.githubusercontent.com/168028/36914071-d7094252-1e00-11e8-9094-59f37488a875.png)

Dentro de la vista de edición del concurso.

## Posible Solución

Agregar una pestaña nueva en la [vista de edición de concurso](https://github.com/omegaup/omegaup/blob/master/frontend/templates/contest.edit.tpl) donde se agreguen los siguientes links:  https://github.com/omegaup/omegaup/blob/75da57a398cc7794c435a58bb00d21e890e2021a/frontend/www/js/omegaup/components/contest/ContestList.vue#L75-L99

**Comment by alirizwi** [comment]
I want to take up this issue.

**Comment by lhchavez** [comment]
assigned to @alirizwi!

**Comment by alirizwi** [comment]
@lhchavez What should be the name of the new tab containing the links?

**Comment by lhchavez** [comment]
`Links`, `Enlaces`, `Vínculos` in spanish, english, portuguese respectively.

**Comment by alirizwi** [comment]
@lhchavez I want to use scorecard url and admin scorecard url in contest.edit.js file, but it seems that ```contest.scoreboard_url``` and ```contest.scoreboard_url_admin``` do not work. How can I use the scorecard urls?

**Comment by lhchavez** [comment]
Oh, right. You also need to add those two columns to https://github.com/omegaup/omegaup/blob/8855dcb75086722877a887d146402a88ba94b9d8/frontend/server/controllers/ContestController.php#L551 and remove them from [`apiDetails()`](https://github.com/omegaup/omegaup/blob/8855dcb75086722877a887d146402a88ba94b9d8/frontend/server/controllers/ContestController.php#L656), probably just with

```php
unset $result['scoreboard_url'];
unset $result['scoreboard_url_admin'];
```

**Comment by alirizwi** [comment]
@lhchavez Its still not working. On accessing through contest.edit.js file,  ```scoreboard_url``` and ```scoreboard_admin_url``` are returned as empty values.

**Comment by lhchavez** [comment]
Can you create a new branch (`git commit checkout -b add-administrative-links && git push origin HEAD:add-administrative-links`) and send a pull request with all the changed files? I can probably help debug that.

**Comment by alirizwi** [comment]
@lhchavez On pushing the code through VM, I am getting this error
![omegaup](https://user-images.githubusercontent.com/23309502/36952549-80e0cdb2-2037-11e8-9d53-1ee8031abceb.png)

**Comment by lhchavez** [comment]
woah, that's new! can you run `git format-patch HEAD^` and share the file
called `0001.*.patch` that is created in the `omegaup` directory next to
the `Vagrantfile`?

for now, also add the `--no-verify` flag to the `git push ...` command.

**Comment by alirizwi** [comment]
@lhchavez Please review the PR. Thanks!
