### ISSUE TITLE
Sanitizar datos de genero

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1802]
- Validar los datos guardados en el campo 'Gender'. Actualmente tenemos valores `NULL` y vacios 
- Asignar el valor de `NULL` a los vacíos.

**Comment by NdubuisiO** [comment]
Hello am interested in the issue of gender. How do I proceed. Where do i experience the error first hand

**Comment by lhchavez** [comment]
we're not 100% sure how it came to be :( Maybe you can try writing a test first that tries to send invalid values like https://github.com/omegaup/omegaup/blob/3c52fe40701abbf73fef7553dee5094359ca203b/frontend/tests/controllers/UserCreateTest.php#L111-L128

but adding an email and an invalid gender.

**Comment by NdubuisiO** [comment]
Writing a test on my local dev environment?

**Comment by lhchavez** [comment]
Yes, please. That same test will then be used to validate that your change is good.

**Comment by lhchavez** [comment]
Assigned to @NdubuisiO

**Comment by NdubuisiO** [comment]
hello @lhchavez @samdsmx i have been trying to navigate to the folder, where user gender is validated before being stored in the database, can you please point me to the file? thanks in advance

**Comment by heduenas** [comment]
This is the controller, but I don't see any validation for gender: https://github.com/omegaup/omegaup/blob/75275f8a59da11708de2832ad3d987833c7e645f/frontend/server/controllers/UserController.php#L24

**Comment by lhchavez** [comment]
the issue _is_ the lack of gender validation. that's why it's nowhere to be found.

**Comment by NdubuisiO** [comment]
Noted, am on it.
