### ISSUE TITLE
Sanitizar datos de Grado academico

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#1804]
Los datos que se guardan en el campo "scholar_degree" de la tabla "users" estan amarrados al lenguaje del usuario, lo que nos causa ruido en las metricas. Se sugiere agrupar por grados internacionales.

Preparatoria	
High school	
Licenciatura	
Bachelor'

**Comment by lhchavez** [comment]
más bien esto debería ser un `set` y no un campo de texto normal, y debería estar basado en un estándar como [ISCED 2011](https://en.wikipedia.org/wiki/International_Standard_Classification_of_Education#ISCED_2011_levels_of_education_and_comparison_with_ISCED_1997):

```mysql
set(
  'none',
  'early_childhood',
  'pre_primary',
  'primary',
  'lower_secondary',
  'upper_secondary', -- secundaria en México
  'post_secondary',  -- secundaria técnica
  'tertiary',  -- vocacional
  'bachelors',
  'master',
  'doctorate'
)
```

**Comment by lhchavez** [comment]
Assigned to @randika96

**Comment by heduenas** [comment]
@randika96 are you working on this issue or we assign it to someone else?

**Comment by randika96** [comment]
@heduenas I have fixed this issue

**Comment by randika96** [comment]
https://github.com/omegaup/omegaup/pull/1811

**Comment by heduenas** [comment]
@lhchavez can we close this issue now?
