### ISSUE TITLE
Los Factories en las pruebas tienen demasiados parámetros

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1816]
Similar a https://github.com/omegaup/omegaup/issues/1440, todas las demás clases de https://github.com/omegaup/omegaup/tree/master/frontend/tests/factories tienen demasiados parámetros.

Hay que arreglar esto igual que https://github.com/omegaup/omegaup/pull/1442

**Comment by NdubuisiO** [comment]
@lhchavez would love to understand this issue more, thanks

**Comment by lhchavez** [comment]
The issue is that there are methods in tests, such as https://github.com/omegaup/omegaup/blob/6806ea6c24d843f909e765c6281b7d47ad6c81ce/frontend/tests/factories/ProblemsFactory.php#L88 that have _way_ too many parameters. If you try to add a new parameter, you need to add it at the very end even if it doesn't make sense there, and you need to explicitly pass in all the previous parameters if you want to specify the last one. A much better solution is to create a small class like https://github.com/omegaup/omegaup/blob/6806ea6c24d843f909e765c6281b7d47ad6c81ce/frontend/tests/factories/ContestsFactory.php#L6 where you can pass in parameters by name like in https://github.com/omegaup/omegaup/blob/f5bec68e627052ccc105f80c34acca8829fc9d72/frontend/tests/controllers/UserContestsTest.php#L16, which is _much_ nicer.

The goal is to create more classes like `ContestParams` for all the factories.

**Comment by SpaceWhite** [comment]
I've been working for this issue for two weeks, can someone tag this issue as assigned @lhchavez

**Comment by lhchavez** [comment]
assigned to @SpaceWhite (but in the future please let us know when you start to avoid incidents like this one).
