### ISSUE TITLE
Cambiar nombre de usuario.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1822]
#Actualmente no es posible cambiar de username, pero sería ideal lograr hacerlo.

**Comment by SpaceWhite** [comment]
Should we let the user to edit email too? @lhchavez

**Comment by lhchavez** [comment]
that's a little bit trickier since we need to verify that the user does.indeed own that email address. but the idea itself is good, so maybe file another issue for it to avoid scope creep.

**Comment by lhchavez** [comment]
assigned to @SpaceWhite
