### ISSUE TITLE
Pruebas de Selenium: Hacer un envío de un problema

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1824]
Como desarrollador de omegaUp, quiero poder empujar cambios con la confianza de que en el siguiente push no va a explotar todo.

## Comportamiento Esperado

Todos los escenarios core de la plataforma deberían tener coverage con Selenium y correrse cada vez que se empuja un cambio en Travis:

Enviar un problema desde la vista de problema. Hoy existen tres maneras de acceder a esta vista (tres vistas diferentes del lado del servidor). La prueba deberá enviar un problema en cada una de estas tres vistas: Desde tu lista de problemas, desde un curso, y desde un concurso.

**Comment by AtharvaKhare** [comment]
I will start working on this issue.

**Comment by pabo99** [comment]
Con el fin de hacer más eficiente y rápida la etapa de pruebas automatizadas, sería conveniente hacerles un refactor, esto quiere decir: crear un curso y un concurso base y en ellos se puedan realizar varias pruebas. Para esta prueba tiene mucho sentido, ya que nada más se espera realizar un envío en cada una de las vistas.

**Comment by dventura11** [comment]
¿Con quién puedo hablar para contribuir con esto?

**Comment by elendil326** [comment]
Que ondas @dventura11 ! Ya hay unos avances en este issue. Puedes tomar otro mejor :)

**Comment by dventura11** [comment]
claro
