### ISSUE TITLE
Mejora - Boton para copiar casos

### ISSUE THREAD

**Issue by cruzjorgesalazar** [omegaup/omegaup#1826]
*En el caso de un feature, provee un título en el siguiente formato:*

Como usuario de omegaUp, me gustaría un boton para copiar el caso de ejemplo con un solo click de los problemas

## Comportamiento Esperado

*Si estás sugiriendo un cambio/mejora, describe cómo debería funcionar*

Deberia ser un boton “copiar” que copie automáticamente el caso de entrada a los portapapeles

## Comportamiento Actual

*Si estás sugiriendo un cambio/mejora, explicanos la diferencia con la
funcionalidad actual*

Seria mas facil y rapido para los usuarios copiar el caso para probarlo con el codigo personal

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
* Sistema Operativo y versión (escritorio o móbil):
* Link al sitio en el que este problema pasa:
* Captura de pantalla:

**Comment by lhchavez** [comment]
no te late mejor que el botón te lleve a https://omegaup.com/grader/ephemeral/ con el caso pre-llenado?

**Comment by cruzjorgesalazar** [comment]
Si esta muy padre la nueva funcion para programar en internet, tiene muchas
funciones, pero creo no sustituye al boton de copiar y siguiria siendo util.

**Comment by yoniihdc** [comment]
@lhchavez me puedes asignar este feature 😄

**Comment by lhchavez** [comment]
Asignado a @yoniihdc !

**Comment by yoniihdc** [comment]
Nada mas para confirmar cual seria el **accepted criteria** de este feature?
* Mantener en el clipboard la entrada de ejemplo
* Abrir el **grader** con los ejemplos preconfigurados (input, output)

o ambas? - Creo que como tarea inicial podria intentar el de crear la copia en el clipboard y el segundo paso seria redireccionar al grader.

**Comment by lhchavez** [comment]
con mandar la entrada de ejemplo al clipboard basta por ahora :) luego vemos cómo abrir el ephemeral grader con los casos de ejemplo.

**Comment by yoniihdc** [comment]
<img width="218" alt="imagen" src="https://user-images.githubusercontent.com/6007230/39100153-1fcd5f88-464b-11e8-9493-47ed8f3332b5.png">

Para casos como esos, esperamos tener el clipboard en cada uno de los ejemplos de entrada? o solo para el ultimo caso de ejemplo?

**Comment by lhchavez** [comment]
supongo que un botón por fila no estaría mal. así no habría ambigüedad.

**Comment by yoniihdc** [comment]
Va, gracias 😃

**Comment by cruzjorgesalazar** [comment]
Algo asi estaria bien.
