### ISSUE TITLE
[BUG] El filtro por problemas en la vista de administrador no sirve si no eres admin del problema.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1828]
## Comportamiento Esperado

Cuando soy administrador en un concurso, puedo filtrar los envíos en la lista por problema.

## Comportamiento Actual

Si agrego un problema público del que no tengo permisos, no puedo filtrar los envíos de ese problema.

## Pasos para reproducir

1. Hacer un concurso.
2. Agregar un problema público del que no tienes permisos.
3. Entrar a la vista de administrador (`/admin`).
4. Ir a Submissions.
5. Intentar filtrar por ese problema.

## Ejemplo

![image](https://user-images.githubusercontent.com/468211/37245680-7ab02d9c-2461-11e8-9abb-1480a91325df.png)

En la imagen observamos que el problema Encontrando-Anagramas está en el concurso, pero no se puede filtrar.

**Comment by dgarvit** [comment]
I would like to work upon this!

**Comment by SpaceWhite** [comment]
@frcepeda Have you tried to click the autocomplete item, it seems work in mine

**Comment by frcepeda** [comment]
The problem isn't the autocomplete items that are shown in the list, but rather the ones that aren't.

Look at the sample screenshot, where Encontrando-Anagramas is in the contest (as seen by the partially accepted submission below), but it isn't shown in the autocomplete box after typing "encontrando".

**Comment by lhchavez** [comment]
Dupe of https://github.com/omegaup/omegaup/issues/1829

**Comment by tvanessa** [comment]
Si es duplicado de #1829?

**Comment by lhchavez** [comment]
huh, no, es lo contrario. ya le di amend al comentario donde digo que sí es.

**Comment by tvanessa** [comment]
Me parece que ya no se reproduce

![index](https://user-images.githubusercontent.com/13296248/85214681-28ebf100-b323-11ea-8011-d896b7905c01.png)
