### ISSUE TITLE
El filtro por problemas en la vista de administrador muestra problemas que no están en el concurso.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1829]
## Comportamiento Esperado

Cuando filtro los envíos de un concurso por problema, sólo aparecen los problemas que están en el concurso.

## Comportamiento Actual

Las sugerencias de filtros contienen todos los problemas de los que tengo permisos de edición.

## Pasos para reproducir

1. Hacer un concurso.
2. Agregar problemas.
3. Ir a la vista de administración (`/admin`).
4. Ir a Submissions.
5. Intentar filtrar

## Ejemplo

![image](https://user-images.githubusercontent.com/468211/37245707-e1e691b8-2461-11e8-97b4-dabf8923cf89.png)

En la imagen vemos que se sugiere el problema Encontrando Intercalados, que no está en el concurso.

**Comment by lhchavez** [comment]
Lo que necesitamos hacer es en vez de poblar el `typeahead` usando datos obtenidos de `apiList`, darle la lista local de problemas y que opere a partir de ellos. Ejemplo: https://twitter.github.io/typeahead.js/examples/

**Comment by yoniihdc** [comment]
Puedo trabajar en este issue si aun no esta asignado a alguien?

**Comment by lhchavez** [comment]
Asignado a @yoniihdc
