### ISSUE TITLE
[BUG] El filtro No-AC de veredictos no funciona.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1830]
## Comportamiento Esperado

Cuando filtro los envíos de un problema por veredicto, puedo filtrar por No-AC.

## Comportamiento Actual

Al elegir el filtro no se muestran envíos.

## Pasos para reproducir

1. Hacer un concurso.
2. Agregar problemas.
3. Ir a la vista de administración (`/admin`).
4. Ir a Submissions.
5. Intentar filtrar.

**Comment by dgarvit** [comment]
I would like to work upon this!

**Comment by dgarvit** [comment]
Can someone help me where to begin working on this?

**Comment by dgarvit** [comment]
@lhchavez can you guide me through this? I cant figure out where to begin from

**Comment by dgarvit** [comment]
I cant seem to figure out which page it is happening on. Also, I wanted to ask which function is responsible for fetching this filtered data. I found a function which counts runs by verdict, but could not find one that filters by verdict.
Also if it is working for other filters, how is it possible that it doesnt work for no-ac?

Finally, I wanted to ask what exactly does no-ac stand for and how it is different from wa.

**Comment by lhchavez** [comment]
@frcepeda will follow up on that. but no-ac is anything that is not `AC`. it includes, but is not limited to `WA` (e.g. it also includes `TLE`, `CE`, `RTE`, etc.)

**Comment by dgarvit** [comment]
Which function is responsible for returning the filtered results?

**Comment by frcepeda** [comment]
No-AC means _any_ other verdict than AC. Basically your filter should return something like `verdict !== 'AC'`.

**Comment by frcepeda** [comment]
The easiest way to reproduce this issue is to create a new problem, make a few submissions to it and then go to the submissions tab at the top of the page (only visible to the problem owner). The filter should appear there (see the screenshot and the URL).

![image](https://user-images.githubusercontent.com/468211/37543008-d7cb5aec-2925-11e8-9d5d-44e2e64e56d3.png)

**Comment by SpaceWhite** [comment]
Is someone still working on this? If not can someone assign me this issue? @lhchavez

**Comment by dgarvit** [comment]
I am working on this.

**Comment by tvanessa** [comment]
Parece que esto también ya se corrigió.

![index2](https://user-images.githubusercontent.com/13296248/85214716-c34c3480-b323-11ea-990d-efffc7254f31.jpg)

**Comment by pabo99** [comment]
Aún sucede el error:

![NO-AC_Filter](https://user-images.githubusercontent.com/3230352/86832231-84c1b400-c05d-11ea-9509-f9509a6d9e14.gif)

Pero ya vi cual es la razón: Cada que se cambia el valor de un filtro, se realiza una petición `ajax` para obtener todos los registros (por el tema de la paginación), y como no existe ningún envío con veredicto `NO-AC`, se obtiene una respuesta vacía. ¿Puedo trabajar en él?
