### ISSUE TITLE
QualityNominationController should check for duplicate tags

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1838]
An error should be returned if a tag appears twice in a request.

https://github.com/omegaup/omegaup/blob/5a8dad4d3053ab0b863e4959e7c5867bc29a65b4/frontend/server/controllers/QualityNominationController.php#L64

**Comment by dgarvit** [comment]
I would like to work upon this!

**Comment by lhchavez** [comment]
Assigned to @dgarvit
