### ISSUE TITLE
Como usuario quiero enterarme de la convocatoria de "Historias omegaUp 2018" para que pueda participar

### ISSUE THREAD

**Issue by Yorchito** [omegaup/omegaup#1839]
Creando issue para que se pueda agregar un banner en la página, similar a las campañas de donación de wikipedia, para que nuestros usuarios se enteren de la convocatoria de las historias omegaUp.

https://docs.google.com/document/d/16Jiqkd0T2xmNS9zvUUlAJt2rJhhWtH2L3Os9SY5MdCU/edit#

Aquí está el texto con los detalles de la convocatoria. Al principio del documento se encuentra la versión larga. Que estaría genial si me ayudan a ponerla en el blog. Y la versión resumida, para que se pueda poner en el banner junto con un link a las bases. 

Gracias!

**Comment by Yorchito** [comment]
__________________________________________________________________________
CONTENIDO PARA EL POSTER/BANNER

¡Participa en Historias omegaUp 2018! 
Comparte con nosotros cómo utilizas omegaUp en tu vida diaria.

Puedes ver la bases aquí: https://blog.omegaup.com/historias-omegaup-2018

Incentivos
Una computadora portátil HP (Modelo 15-bs001) de 15.6".
$2,000.00 pesos (MXN) para libros.

Las historias serán presentadas a nuestros donadores en la Cena de Gala Anual de omegaUp en Bellevue, Washington. 

La convocatoria comienza el lunes 19 de marzo y termina el viernes 27 de abril. 
__________________________________________________________________________

**Comment by lhchavez** [comment]
faltarían las traducciones a inglés y portugués, que alguien diseñe el banner y el sign-off de @npave

**Comment by Yorchito** [comment]
Closing because there is no time to make this actionable anymore.
