### ISSUE TITLE
El link the "puntos para el ranking" no lleva a la vista correcta

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1850]
Como un usuario entro a ver la lista de problemas y le doy click al boton de ayuda de la coumna de "Puntos para el ranking"

## Comportamiento Esperado

Obtengo informacion sobre como se calculan puntos para el ranking.

## Comportamiento Actual

Llego a la vista de la convocatoria de historias omegaUp. Parece que el comportamiento de WordPress al recibir un link invalido es mostrar la pagina principal.

## Posible Solución

Cambiar el link de
https://blog.omegaup.com/2014/06/el-nuevo-ranking-de-omegaup/
a
https://blog.omegaup.com/ranking-de-escuelas-en-omegaup/

**Comment by heduenas** [comment]
Creo que el link correcto es https://blog.omegaup.com/el-nuevo-ranking-de-omegaup/

**Comment by pabloaguilar** [comment]
d'oh!
Gracias por la correccion!
