### ISSUE TITLE
Incorrect problem alias

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1851]
In `/arena/CONTEST_ALIAS#ranking`
Strange contest alias in scoreboard when there are more than 26 problems in a contest

## Current behaviour
Contest become character `[`, `\`, `]`, `^`, etc. This was caused by ascii incremental

## Expected behaviour
Alias bigger than letter Z should be shown as AA, AB, AC, etc

## Possible solution
Change this vue
https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/components/arena/Scoreboard.vue#L12 

Screenshots :
![screenshot from 2018-03-19 08-55-17](https://user-images.githubusercontent.com/15065085/37597134-d4a81edc-2b54-11e8-8292-243dfc2bee91.png)
![screenshot from 2018-03-19 08-55-31](https://user-images.githubusercontent.com/15065085/37597135-d4d1320e-2b54-11e8-9592-39a72615d4d2.png)

**Comment by lhchavez** [comment]
oh. yes, we only fixed that issue in some places, but not the Scoreboard :(

**Comment by alirizwi** [comment]
I want to work on this.

**Comment by lhchavez** [comment]
@SpaceWhite, did you open this issue because you had already started working on it, or can @alirizwi work on it?

**Comment by SpaceWhite** [comment]
Sorry for the slow response, I'll fix it quick @lhchavez

**Comment by lhchavez** [comment]
Assigned to @SpaceWhite
