### ISSUE TITLE
User who visted a problem page cannot go back to the previous page he has vited

### ISSUE THREAD

**Issue by rpjayasekara** [omegaup/omegaup#1854]
From [omegaup.com/arena/problem/aldp#problems](url) user cannot go back to the previous page by using the back button.

## Expected behavior

* Once the user press the back button from a problem page redirect the previous page user has visited.

## Current Behavior

* Once a user load a problem page he cannot go back to the previous page he visited by using the back button.

## Possible solution

* It might need to change the logic that appends the `#problems` part (or rather, any hash) and instead use https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries

**Comment by heduenas** [comment]
@randika96 I wasn't able to reproduce this bug. To confirm, you go to problem list, then open a problem, then click back button on browser? Also, which browser do you use?

**Comment by randika96** [comment]
I am using Firefox. Yeah once I load a problem page I cannot redirect the previous page I visited using the back button

**Comment by tvanessa** [comment]
Duplicated #2046
