### ISSUE TITLE
Certificate error when visiting www.omegaup.com

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#1862]
## Expected behavior

When I visit www.omegaup.com, either I get redirected to omegaup.com or the website loads.

## Current behavior

The current certificate served when loading www.omegaup.com is invalid.

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by lhchavez** [comment]
Fixed.
