### ISSUE TITLE
Problem page should mention creation date

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1863]
We can include it below the problem description:
"Uploaded by: CodingRush" should become "Uploaded by: CodingRush on YYYY/MM/DD"

![screenshot from 2018-03-29 09-43-09](https://user-images.githubusercontent.com/597815/38101676-cb70c984-3335-11e8-9f19-dec2605e74c3.png)

**Comment by alirizwi** [comment]
@heduenas I want to work on this issue.

**Comment by heduenas** [comment]
@alirizwi let me know if you have any questions about this issue.

**Comment by lhchavez** [comment]
audit log: changed the date format from a US-centric "month, day, year" to a more international and unambiguous "YYYY/MM/DD"

**Comment by dgarvit** [comment]
Can I take this if no one is working on this?

**Comment by alirizwi** [comment]
@dgarvit I am working on this issue. Couldn't update the PR due to end semester exam preparations, will do shortly.

**Comment by dgarvit** [comment]
Alright. :)
