### ISSUE TITLE
Permitir el reuso efectivo de problemas, mostrando detalles de administrador a los creadores de concursos

### ISSUE THREAD

**Issue by Fer-OmegaUp** [omegaup/omegaup#1868]
Feedback de la OMI pasada a Alan:

Cuando reusas un problema, actualmente no puedes ver las soluciones que los estudiantes mandan. Esto causa que los profesores, en lugar de reusar un problema, lo copian otra vez para utilizarlo en un concurso.

Para todos los problemas que son publicos, nos gustaria que tambien hubiera una forma de tener permisos de administrador cuando el problema se anade a un concurso, para ese concurso

**Comment by lhchavez** [comment]
esto aún ocurre? me suena a que hubo cargo-culting en algún punto, lo
arreglamos, pero la gente siguió con la vieja idea de que no funciona.

>

**Comment by lhchavez** [comment]
ping @Fer-OmegaUp . hay repro en https://sandbox.omegaup.com?

**Comment by frcepeda** [comment]
(Disclaimer: esto es lo que yo entendí del issue, pero estamos jugando al teléfono descompuesto, creo.)

Este issue no es trivial porque el comportamiento es por diseño.

Supongamos que el usuario A crea un problema cool (por ejemplo, un problema de una OMI pasada). Ahora, el usuario B quiere usar el problema en su concurso/curso, pero no tiene permisos de administrador. Como quiera, hace su concurso con ese problema.

Ahora, cuando ve el log de envíos de sus concursantes/alumnos, solamente ve el código fuente, junto con el veredicto y puntaje finales, pero no un desglose de los casos y sus veredictos, así como los casos en sí.

Como maestro, quieres poder ayudar a tus alumnos si no encuentras el bug en su spaghetti, pero si no conoces los casos donde están fallando, es muy difícil ayudar en problemas no triviales.

Por reuso inefectivo se entiende que un maestro, dada esta situación, se ve desincentivado a usar problemas que no son suyos, porque si hay alguna explosión no puede ayudar a sus alumnos. El problema, claro, es que exponer los casos de prueba de un problema no tuyo es todo otro rollo, tanto técnico, como de privacidad.

**Comment by Fer-OmegaUp** [comment]
esto sigue bloqueado?
@lhchavez

**Comment by lhchavez** [comment]
no hay necesidad del mention, me llegan todas las notificaciones.

no, lo único que hay que hacer es cambiar https://github.com/omegaup/omegaup/blob/b2f7696d41dce4b329ec3f64dab25ef9c12f84b4/frontend/server/controllers/RunController.php#L619 por 

```php
Authorization::isProblemAdmin($r['current_identity_id'], $r['problem']) ||
(!is_null($r['problem']->problemset_id) &&
 Authorization::isAdmin($r['current_identity_id'], $r['problem']->problemset_id));
```

**Comment by lhchavez** [comment]
aguanten, ya me acordé por qué no lo hicimos así desde un principio. si a alguien no le sale un problema, no mostramos qué casos no pasan (porque divilgaría información innecesaria). entonces como workaround, alguien puede hacer un concurso con el problema que no le sale y hacer un envío para tener todos los detalles.

permitir esto posiblemente rompa varios concursos, así que hay que hacerlo a) conscientemente y b) con cuidado.

**Comment by lhchavez** [comment]
hemos llegado a un consenso!

la manera en la que se va a resolver es: si alguien que NO es administrador del problema hace un concurso con ese problema Y ya lo ha resuelto, te muestra los detalles del envío. De esta manera tenemos un buen tradeoff.
