### ISSUE TITLE
Como creador de problemas de karel quiero poder definir la version de libkarel estoy usando

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1869]
Cuando se actualiza libkarel los problemas viejos fallan.

Lo mejor sería que al subir un problema se guardara la versión de libkarel

**Comment by lhchavez** [comment]
esto suena como que demasiado overhead :( mejor hay que hacer libkarel backwards-compatible y listo

**Comment by elendil326** [comment]
Cerrando ya que es más fácil que libkarel sea backward-compatible, además se adhiere a las normas de código.
