### ISSUE TITLE
API.Session.currentSession() se llama dos veces en cada page load

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1870]
## Comportamiento Actual

(casi) Todos los page loads llaman a `API.Session.currentSession` dos veces.
Solo debería haber una llamada.

## Posible Solución

`OmegaUp._initialize` se llama en todas las llamadas a `OmegaUp.on`. Casi cualquier página registra para el evento `ready`, entonces a su vez llama a `_initialize`. Hay un flag guard en `on` pero revisa la variable `_initialized`, que nunca se esta prendiendo. `_initialize`, a su vez, tiene un flag guard usando la variable `ready`, pero ésta no se asigna sino hasta el callback de `currentSession`, permitiendo que la segunda llamada a `_initialize` vuelva a llamar a `currentSession`. Al terminar la primer ejecución de `currentSession`, se asigna la variable `ready`, y llamadas sucesivas a `on` ya no repiten la llamada a `currentSession`.

Queda claro?

Una posible solución es utilizar correctamente la bandera `_initialized` pero que sólo se use desde la función `_initialize`. Así se le podrá llamar cuantas veces sean, pero no va a realizar trabajo doble. Dentro de `_initialize` la bandera se prende inmediatamente, y no hasta que termine el callback de `currentSession`.

## Pasos para reproducir (para bugs)

1. Abrir la consola de Network (en su web debugger de preferencia) 
2. Cargar cualquier página en `omegaup.com`
3. Se ven dos llamadas a `currentSession` en la consola

**Comment by elendil326** [comment]
Esto es browser-independent
