### ISSUE TITLE
Facebook and twitter buttons don't show up in front page

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1871]
## Expected behaviour
Facebook (share, like) and twitter (follow) are shown in omegaup index front page `https://omegaup.com`

## Current behaviour
Facebook (share, like) and twitter (follow) are not shown in omegaup index front page `https://omegaup.com`

## Possible solution
Instead using Iframe show button as div and go to url by using javascript SDK (Sadly I don't know what caused the error :( maybe someone can add it in comment)

## Browser tested
Firefox Quantum 59.0.2 (not working)
Safari 11 (not working)
Chrome 65.0.3325.181 (working)

**Comment by pabloaguilar** [comment]
They're supposed to be shown in the footer. Do you not see then there?
I can see them with both Chrome and Firefox

**Comment by SpaceWhite** [comment]
@pabloaguilar sadly no :(
![canvas](https://user-images.githubusercontent.com/15065085/38171111-c8fa966c-3560-11e8-8023-168d8e494788.png)

**Comment by lhchavez** [comment]
huh, can you open the developer tools and then refresh the page? then see if any elements failed to load in the network tab of the developer tools.

maybe the resources are being blocked by your ISP :/

**Comment by SpaceWhite** [comment]
@lhchavez I can see the iframe elements exist on the page, but inside of those iframe there are no body elements. I think it is not because of my ISP, because it works on google chrome

**Comment by SpaceWhite** [comment]
@pabloaguilar I think that is not the problem. I have safari without addons and those buttons didn't show up

**Comment by SpaceWhite** [comment]
@pabloaguilar @lhchavez I found that this was caused by tracking protection in the browser https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default.
