### ISSUE TITLE
[Performance bug] Botones sociales retrasan el on-load de la página

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#1872]
*Como un usuario normal, quiero que la página cargue lo más pronto posible. (para disminuir bounce rates!)

## Comportamiento Esperado

La página carga en no más de un segundo.

## Comportamiento Actual

Hay muchas cosas que la hacen lenta.. pero una de ellas es que el on-load no sucede sino hasta que se cargaron los botones sociales (Twitter y FB que aparecen en el footer).

## Posible Solución

Cargar los botones sociales en el evento `OmegaUp.on('ready')` para evitar bloquear el tiempo de carga.

Screenshot de Chrome dev console:
![image](https://user-images.githubusercontent.com/189223/38182726-4c6a8496-35f0-11e8-8135-c44fc89aae14.png)

**Comment by lhchavez** [comment]
Esos se cargan con `<script>`? Si sí, podemos usar https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async

Y gracias por investigar el PLT :D hace mucho que no le prestamos atención

**Comment by pabloaguilar** [comment]
Desafortunadamente no son `<script>`, son `<iframe>`.
Podríamos crear los iframes en un script que sí se cargue como `async`
