### ISSUE TITLE
Open redirect vulnerability in login page

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1883]
Sample malicious url `https://omegaup.com/login/?redirect=https%3A//www.example.com/`
## Current behaviour
Redirect URL is not filtered, so that users are vulnerable to phising attack

## Expected behaviour
Redirect URL should be only available with only `omegaup.com` domain

## Possible solution
Add redirect validation in https://github.com/omegaup/omegaup/blob/0f63ff8b4c477155b2231ab4f79e1eb66e69253d/frontend/www/login.php#L48

**Comment by lhchavez** [comment]
Good job on the security issues!
