### ISSUE TITLE
Arena for anonymous user

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1887]
## Current behaviour
Anonymous user (not logged in user) are able to see "Recommended current contest", "Recommended past contest", "My contest" option in `https://omegaup.com/arena/`

## Expected behaviour
Those tab should be hidden because it is strange to have recommended contests, and my contest shown to anonymous user

## Possible solution
Add condition statements `$LOGGED_IN === '1'` in these line
https://github.com/omegaup/omegaup/blob/39ee5de7a2f8e9f137e6b657c743ab74ace49002/frontend/templates/arena.index.tpl#L29
https://github.com/omegaup/omegaup/blob/39ee5de7a2f8e9f137e6b657c743ab74ace49002/frontend/templates/arena.index.tpl#L45
https://github.com/omegaup/omegaup/blob/39ee5de7a2f8e9f137e6b657c743ab74ace49002/frontend/templates/arena.index.tpl#L53

**Comment by heduenas** [comment]
@npave, from your perspective should we hide contests from anonymous users?

**Comment by npave** [comment]
That is right, the tab "My contest" should not be displayed for anonymous users. However, the other tabs ("Recommended current contest", "Recommended past contest") don't have to be hidden, they are recommended contests in general, they don't have relation with the users' activity and they can be a selling point if new users come and see that we have interesting contests.

**Comment by dgarvit** [comment]
I agree with @npave .
I would like to work on this issue if no one is working on this.
