### ISSUE TITLE
Overlay AC submissions in the home page graph

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1893]
It'd be nice to have a graph with the total number of AC submissions over time. Just like we do for total number of submissions. 

![screenshot from 2018-04-08 12-45-05](https://user-images.githubusercontent.com/597815/38471781-d4ccb0b8-3b2a-11e8-81ee-22d641e839c5.png)

**Comment by lhchavez** [comment]
how about a toggle/select instead of having two graphs?

**Comment by heduenas** [comment]
I think having both graphs on the same canvas would be ideal, but toggle/select would also be fine.

**Comment by heduenas** [comment]
Last time I checked ~35% of all submissions were AC (this surprised me, I also expected it to be much smaller). Can you check if that still holds? If it does, having both graphs on the same canvas should work well.

**Comment by lhchavez** [comment]
oh wait, you meant overlaying both time series in the same graph? okay, that makes a lot more sense now.

yes, the ratio is still the same (which is what i assumed what would happen in the above comment).

**Comment by heduenas** [comment]
Closing because of new homepage.
