### ISSUE TITLE
Refactor de Identidad: Fase 10

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1911]
Esto es parte del feature #1300

https://docs.google.com/document/d/1COTwqOYNvuYER5jkeKZWJXxSdVn_2X-CjoDolmEiQ1Y/edit#

**Backend**

Se necesitaría cambiar el inyector de envíos y el Broadcaster, que hacen referencia a la tabla Users, a que hagan referencia a la tabla Identity.

**Comment by lhchavez** [comment]
Este ya está terminado ;) https://github.com/omegaup/quark/commit/03d654e8f791f48a3f2f13cb8a8dcd6e8312e283
