### ISSUE TITLE
Refactor de Identidad: Fase 11

### ISSUE THREAD

**Issue by elendil326** [omegaup/omegaup#1912]
Esto es parte del feature #1300

https://docs.google.com/document/d/1COTwqOYNvuYER5jkeKZWJXxSdVn_2X-CjoDolmEiQ1Y/edit#

**Experiencia de Usuario**

La interfaz de administración de grupo necesitaría tener una pestaña para hacer la administración de las identidades asociadas con el grupo, subiendo un archivo en formato .csv como se especifica arriba. También en la sección de perfil del usuario sería necesario una subsección para administrar identidades, al igual que agregar todas las identidades asociadas al usuario al dropdown del usuario loggueado.

**Comment by pabo99** [comment]
La subsección de administrar identidades se separa en el issue #2089

**Comment by pabo99** [comment]
En la vista de administración de identidades se podrá eliminar, ligar a un usuario y modificar contraseña. 

¿Aquí se pueden editar los campos de país, estado y genero para cada identidad?

**Comment by pabo99** [comment]
La propuesta para la administración de Identidades es agregarlas en el listado de Miembros que pertenecen a un grupo. 

Por el momento, sólo cuentan con una diferencia al resto de los miembros, el `username` se compone de la siguiente forma: `[Alias del Grupo][:][Nombre de usuario]`

Las acciones que se pueden realizar a las identidades son las siguientes: 
- Editar información.
- Cambiar contraseña.
- Ligar identidad a un usuario.
- Eliminar identidad del grupo.

Abajo se muestra una captura con la propuesta: 

![2018-07-23 1](https://user-images.githubusercontent.com/3230352/43098707-85f36aaa-8e85-11e8-90ee-b2c585eb7ee9.png)

**Comment by lhchavez** [comment]
Creo que no es conveniente eliminar identidades (así como no eliminamos nada más). Lo de ligar identidades a un usuario lo tiene que hacer un usuario en su perfil.

Todo lo demás (cambio de contraseña y editar información básica) suena razonable ponerlo ahí donde propones.

**Comment by pabo99** [comment]
El botón de eliminar se refiere a quitar la relación que tiene con el grupo y realizaría la misma función que el botón de la primera lista. Habrá que buscar una mejor redacción para no confundir al usuario. 

El botón de ligar identidad a un usuario lo quito.

**Comment by pabo99** [comment]
@tvanessa Esto ya está resuelto.
