### ISSUE TITLE
El certificado de https://arena.omegaup.com es inválido

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1914]
Como creador de concursos necesito poder entrar a arena.omegaup.com para poder limitar el acceso.

Comportamiento esperado: poder entrar.
Comportamiento actual: no me deja entrar porque dice error de certificado.

![image](https://user-images.githubusercontent.com/848246/38698446-b1eb399c-3e5a-11e8-927a-9ec0aa8d74e5.png)

Tambien si entras por no https te hace redireccion a omegaup.com sin arena

**Comment by lhchavez** [comment]
https://arena.omegaup.com ya está operacional de nuevo. Se perdió en la migración de AWS :(
