### ISSUE TITLE
User without authorization can clone contest

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#1920]
## Current behaviour
User without authorization to access other person private contest, can create clone contest by only providing `contest_alias`

## Expected behaviour
Before clone a contest, check if the contest is available to the user

## Possible solution
Add `self::canAccessContest` function to here
https://github.com/omegaup/omegaup/blob/3696e0adeafd710cde61bed1bffb7303a8bb97fb/frontend/server/controllers/ContestController.php#L835

**Comment by dgarvit** [comment]
I would like to work on this!

**Comment by dgarvit** [comment]
@SpaceWhite can you provide steps to reproduce this?

**Comment by SpaceWhite** [comment]
@dgarvit You can reproduce this by calling clone api with private `contest_alias` that you have no access to. Details:
1. User 1 login, create new private contest
2. User 1 logout, User 2 login
3. Trigger api clone with user 2 credential, with user 1 private contest alias
