### ISSUE TITLE
Como usuario quiero que el tiempo de ejecución del algoritmo sea más preciso.

### ISSUE THREAD

**Issue by CarlosCordova18** [omegaup/omegaup#1931]
## Comportamiento Esperado

Hay problemas, como el caso de [Sumas](https://omegaup.com/arena/problem/sumas#problems), donde el tiempo de ejecución es tan corto que bordea las centésimas o milésimas de segundo. Si como usuario, quisiera mejorar mis tiempos para entrar a la tabla de *"Mejores envíos"*, no habría forma de saber en cuanto he de reducirlos para poder estar ahí ya que lo único que puedo ver son valores 0.00 s.

## Comportamiento Actual

Actualmente los valores para el tiempo se ven hasta las centésimas.
![precision](https://user-images.githubusercontent.com/20785082/38784140-4fd5a10e-40d3-11e8-8673-83b20b17abd0.png)

## Posible Solución

Ajustar la precisión del Tiempo de ejecución a milésimas o diezmilésimas.

## Pasos para reproducir (para bugs)

1. Entrar a algún problema: https://omegaup.com/arena/problem/sumas#problems
2. Ver la tabla de mejores envíos.

**Comment by lhchavez** [comment]
Lamentablemente si mostramos más precisión, entramos al nivel del ruido. Las ejecuciones pueden cambiar por un montón de cosas fuera de tu (o nuestro!) control. Si ese día estaba haciendo más calor en el data center, si los archivos habían sido leídos hace poco tiempo, si llegaron más paquetes al servidor que estaba corriendo el código, si hubo una actualización fuera de banda, etc.

Intentamos mitigar varios de esos factores haciendo pre-caching de los archivos de entrada y procurando que en la medida de lo posible se opere sobre la memoria (o el cache), pero aún así ya estamos peligrosamente cerca del punto en el que el mismo envío ejecutado varias veces va a comenzar a mostrar variabilidad. Puedes confirmar esto mismo en tu propia computadora y poco a poco perder la sanidad si estás intentando optimizar un código, creyendo que hiciste algo bueno (o malo) y resulta que era únicamente el ruido :/

**Comment by CarlosCordova18** [comment]
Daaaa, tiene sentido.
Entonces no habría forma de resolver esto :/

**Comment by lhchavez** [comment]
Sí, lo siento :( es un problema más o menos fundamental que no tiene una solución que dejaría contentos a todos.
