### ISSUE TITLE
Add field for tag list in problem creation view

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1940]
When creating a new problem, user should be asked (**but not forced**) to specify a list of tags for the problem. Right now that's only possible when editing a problem.

This is the problem creating view:
![image](https://user-images.githubusercontent.com/597815/39089596-f5cc2c12-457f-11e8-8b55-1fa67aebd46b.png)

We want to include the a list of tags like this:
![image](https://user-images.githubusercontent.com/597815/39089591-e569005c-457f-11e8-9ebf-d4a301362740.png)

We prefer not to enforce this field to avoid jeopardizing the quality of the tags.

**Comment by SpaceWhite** [comment]
@heduenas  How about the tag public and private properties?

**Comment by heduenas** [comment]
We can add the list of tags and a boolean field "Public" just like shown in the bottom image.
