### ISSUE TITLE
Rank is shown as "Unranked" for some (obviously ranked) users

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#1945]
For example:
![image](https://user-images.githubusercontent.com/597815/39150686-03498712-46f8-11e8-8e47-f6ebae64d2c9.png)

Probably the same root cause as #1944
Also, flag is not being displayed. @SpaceWhite mentions the root cause below.

**Comment by SpaceWhite** [comment]
The country flag is not working because it is not converted to lowercase
https://github.com/omegaup/omegaup/pull/1930/files#diff-c9f7a0ddfd95a54c1c3389f2442f4502R21

**Comment by heduenas** [comment]
@SpaceWhite good catch. I'm going to update the bug description to include the flag issue.

**Comment by heduenas** [comment]
Have we fixed the country flag issue also?

**Comment by SpaceWhite** [comment]
No, I don't want to mess with my 1 bit PR achievement :D.
But I'll create a new PR for country flag issue. Can someone reopen this issue? @heduenas
