### ISSUE TITLE
Aumentar limite de upload de solucion a 20 Kb

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1962]
Como creador de problemas de karel, quiero permitir que los concursantes puedan subir soluciones grandes sobre todo en problemas de karel que son muy verbose

**Comment by lhchavez** [comment]
idealmente hay que establecer esto por-problema, pero por ahora para desatorarlos solo lo voy a hacer con karel.

**Comment by lhchavez** [comment]
el workaround ya está en prod.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/743
