### ISSUE TITLE
Agregar CodeMirror en los detalles de un envio - readOnly

### ISSUE THREAD

**Issue by yoniihdc** [omegaup/omegaup#1965]
Como un Admin de un Contest, quiero poder ver el codigo que envian los alumnos con la sintaxis resaltada para poder entender mejor el codigo. 

## Comportamiento Esperado

Al abrir los detalles de un envio me gustaria ver la sintaxis del codigo resaltada con el mismo editor (`CodeMirror`) que se utiliza cuando se hace un envio pero mantener el funcionamiento de la misma manera (`solo lectura`).

<img width="869" alt="imagen" src="https://user-images.githubusercontent.com/6007230/39613370-5a192732-4f2c-11e8-9e3f-caea48823248.png">

## Comportamiento Actual

<img width="1010" alt="imagen" src="https://user-images.githubusercontent.com/6007230/39613354-2b1448e0-4f2c-11e8-85a7-9e0413458993.png">

## Posible Solución

Reemplazar la etiqueta `<pre>` por un container con el editor `CodeMirror` y habilitar la opcion de solo lectura.

**Comment by yoniihdc** [comment]
@lhchavez si es válido ^ puedo trabajar en esta propuesta?

**Comment by lhchavez** [comment]
OH! sí, por favor :D
