### ISSUE TITLE
Error al tener los lenguajes permitidos(validacion de lenguajes)

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#1973]
Estaba en modo practica de concurso de programacion y descubri que en la barra de seleccion de lenguaje, al presionar una tecla, por ejemplo c, aparece un lenguaje que empieza con esa letra, en este caso c++11, aun que este no esté permitido.

ambiente:
Windows 10
Firefox

se puede recrear el bug en cualquier modo de competencia 

![buug1](https://user-images.githubusercontent.com/5459260/39657011-b6bde200-4fc9-11e8-8be0-ce858923d7a9.png)

AQUI SE PUEDEN VER LOS LENGUAJES PERMITIDOS

![buug2](https://user-images.githubusercontent.com/5459260/39657047-f71de994-4fc9-11e8-9f44-b91d3248a1c0.png)

AQUI SE PUEDE QUE FUE SELECCIONADO UN LENGUAJE NO PERMITIDO

GRACIAS :D

**Comment by yoniihdc** [comment]
@lhchavez puedes asignarme este issue 😄

**Comment by lhchavez** [comment]
hecho!
