### ISSUE TITLE
[FEATURE] Permitir ver los casos completos en ciertos problemas

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#1998]
Como administrador de problemas (didácticos), quiero que la gente que intenta mi problema pueda ver qué casos tuvo bien o mal.

## Comportamiento Esperado

Cuando crees / edites un problema, deberías poder elegir si quieres que los usuarios que intentan resolverlo pueden ver detalles adicionales (los nombres de los casos) y adicionalmente qué subconjunto de los casos de entrada se pueden mostrar a los usuarios. Esto sería una generalización de los casos de ejemplo.

## Comportamiento Actual

Únicamente los administradores del problema pueden ver los nombres de los casos tuvieron bien / mal al ver los detalles.

## Posible Solución

A [`RunController::apiDetails`](https://github.com/omegaup/omegaup/blob/7ea70fe7e2513770025c06e54f383ea3011e3fc1/frontend/server/controllers/RunController.php#L634) se le puede agregar la condición si el problema tiene la opción de ver los detalles del envío.

**Comment by pabo99** [comment]
Aquí el documento para trabajar este issue: https://docs.google.com/document/d/1namOpwMAgNEDuboxtQf1-0YF-Q5ZxsLAHDnpO0Ps2q0/edit?usp=sharing
