### ISSUE TITLE
Dejar de usar DAO::search

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2001]
`DAO::search` se considera peligroso :S como DAO::seach no hace ninguna validación de que las columnas realmente estén en la tabla y simplemente las ignora silenciosamente, esto dejó que un bug llegara a producción aún habiendo pasado las pruebas https://github.com/omegaup/omegaup/issues/2000 (porque las pruebas sólo validaban que existieran los registros esperados, no que _no_ existieran otros registros).

Dado eso y que es inherentemente imposible hacer `JOIN`s con los DAOs, creo que lo mejor es bannear `DAO::search` de todo uso y hacer los queries a patín.

Lo bueno es que únicamente se utiliza 28 veces en todo el codebase, así que no va a haber necesidad de hervir el océano.

**Comment by pabo99** [comment]
Se divide el issue, sólo se enfoca en modificar los controllers, la segunda parte se resolverá en #2091
