### ISSUE TITLE
Guardar todos los consents de privacidad en PrivacyConsent_Log

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2002]
Esto incluye los consents al principio de cada concurso / curso de que los profesores van a poder ver un subconjunto de tu información. Hay que:

- [ ] mover los textos de ahí a un archivo `.md` (en los tres idiomas), digamos `frontend/privacy/privacy_policy/es.md` y `frontend/privacy/contest_..._consent/pt.md`.
- [ ] Agregar columnas a `PrivacyStatements` para poder referenciar los concursos.
- [ ] Hacer un script de migración para copiar todos los consents ya hechos a esta nueva tabla.
- [ ] Agregar pruebas.

**Comment by pabo99** [comment]
Esto depende del #1991, una vez que se libere, se resolverá
