### ISSUE TITLE
Agregar una prueba en Travis para validar que si se toca un markdown de privacidad, PrivacyStatements se actualiza

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2003]
Esto se puede mandar llamar desde [`stuff/travis/lint.sh`](https://github.com/omegaup/omegaup/blob/master/stuff/travis/lint.sh). Supongo que también se podría hacer desde un linter, pero no se me ocurrió cómo hacerlo.

Aquí el chiste es que para cada una de las carpetas de `frontend/privacy/`, haya un valor en `PrivacyStatements.type`. El último valor para `git_object_id` debe ser idéntico a lo que regrese

```bash
git rev-parse HEAD:frontend/privacy/$TYPE
```

**Comment by pabo99** [comment]
Tampoco se me ocurre como hacerlo desde un linter, ¿Alguien tiene una idea?

**Comment by pabo99** [comment]
¿Esto no queda resuelto con el PR #2098?

**Comment by lhchavez** [comment]
sí, se me olvidó cerrarlo ^^;;
