### ISSUE TITLE
Quitar la restricción de 100 días para el curso de "Aprende a programar"

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#2006]
Como un estudiante, quiero poder tener mas de 100 dias para enviar soluciones en el curso en la pagina principal para poder completar dicho curso.

## Comportamiento Esperado

El concurso principal de omegaUp "Aprende a programar" debe dejarme enviar soluciones incluso si yo inicio el curso en un ciclo escolar, y luego me voy de vacaciones a un lugar sin acceso a internet y regreso a clases para continuarlo.

## Comportamiento Actual

Este fue feedback de la OMI asi que no se que es exactamente lo que pasa, pero me imagino que o no te deja entrar al curso o no te deja hacer envios.

## Contexto

Chicos que se van de vacaciones y/o no tienen internet en sus casas para completar el curso y a la hora de regresar a la escuela resulta que ya no tienen oportunidad de continuarlo.

**Comment by dventura11** [comment]
Yo puedo contribuir en esto, ¿Con quién puedo ver los detalles?

**Comment by lhchavez** [comment]
@dventura11 welp, no habíamos visto tu comentario. todavía te interesa? por aquí mismo se puede.

**Comment by pabo99** [comment]
No logro reproducirlo. Actualmente el curso indica que le restan al rededor de 1502 días. Se requiere de más información

**Comment by tvanessa** [comment]
Este issue se puede cerrar si no se puede reproducir?

**Comment by lhchavez** [comment]
posiblement elo arreglamos hace tiempo y no nos dimos cuenta.
