### ISSUE TITLE
Add tooltip to copy case button

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#2011]
Add tool-tip when hovering the button in:

![screenshot from 2018-05-19 13-27-31](https://user-images.githubusercontent.com/597815/40272794-8bd84558-5b68-11e8-9a2d-ee13e03721f0.png)

**Comment by Mart-97** [comment]
Hola, me gustaría tomar este issue:)

**Comment by lhchavez** [comment]
Asignado!

**Comment by Mart-97** [comment]
Hola, tengo una duda!, Como puedo añadir las translations del tooltip  para el hover del botón?

**Comment by heduenas** [comment]
Es con los archivos .lang 
Ve por ejemplo este PR: https://github.com/omegaup/omegaup/pull/1351/files
