### ISSUE TITLE
Al dar de alta un problema me aparece un error la consola de JavaScript

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2014]
Cómo parte de la solución para el issue #1692, me percato de que al dar de alta un nuevo problema, cuando escribo el título, me aparece un error en la consola de Javascript. 

## Comportamiento Esperado

Lo ideal es que no aparezca ningún mensaje de error en toda la prueba

## Comportamiento Actual

No es como tal un bug, pero hay que buscar la forma en que no aparezca el error. 

## Pasos para reproducir (para bugs)

1. Ingresar a omegaUp
2. Dar clic en el menú Problemas -> Crear un nuevo problema
3. Escribir un título para el problema
4. Se genera un alias en automático y se consulta que este no exista en la base de datos.

## Contexto

Como no existe el alias que se generó en automático, la `API` me devuelve un error `404`.

La posible solución es que dicha `API` me devuelva un `Boolean` indicando si el alias está en uso o no.

## Tu ambiente

![captura de pantalla 2018-05-21 a la s 07 19 15](https://user-images.githubusercontent.com/3230352/40307330-9d4b2f5c-5cc7-11e8-8535-e68526c1caa1.png)

**Comment by lhchavez** [comment]
Este cambio se puede hacer en un solo PR, e incluye regresar el `boolean`, consumirlo en interfaz, y quitar el hack de Selenium.
