### ISSUE TITLE
En ocasiones me aparecen errores del WebSocket en la consola de Javascript

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2016]
Cómo parte de la solución para el issue #1692, me percato que ocasiones me aparece un error del `Websocket` en la consola de Javascript. 

## Comportamiento Esperado

Lo ideal es que no aparezca ningún mensaje de error en toda la prueba

## Pasos para reproducir (para bugs)

1. Ingresar a omegaUp
2. Dar clic en Arena
3. Seleccionar un concurso de la lista de concursos actuales
4. Esperar a que aparezca el error (No es común que aparezca siempre).

## Contexto

Desconozco parte del funcionamiento del  `Websocket`, así que me es difícil encontrar una posible solución.

## Tu ambiente

![captura de pantalla 2018-05-21 a la s 07 45 50](https://user-images.githubusercontent.com/3230352/40308230-1b87c558-5ccb-11e8-81a6-d83e580e92bc.png)

**Comment by lhchavez** [comment]
La siguiente vez que te ocurra, corre `vagrant provision` porque puede que estés usando una versión vieja del Broadcaster. si sigue ocurriendo, avísanos.

**Comment by elendil326** [comment]
@pabo99 Voy a cerrar este issue y si vuelve a pasar, verifica con el comando que pone @lhchavez . Si eso no soluciona el problema, re-abrimos este issue.
