### ISSUE TITLE
No funciona el ranking de mi concurso

### ISSUE THREAD

**Issue by luisrodolfo** [omegaup/omegaup#2018]
No funciona el ranking de mi concurso.
https://omegaup.com/arena/SELECTIVO2018_1/

En la sección de administrador, nos aparece vacío el ranking:

![image](https://user-images.githubusercontent.com/12162641/40315789-faa01874-5ce1-11e8-88d5-639b5594a237.png)

Ya se probo en diversos navegadores, y el resultado es el mismo. 

Revise concursos anteriores y si puedo ver el ranking. La falla es en este concurso.

**Comment by frcepeda** [comment]
Parece que es culpa de la API.

La respuesta de `https://omegaup.com/api/contest/scoreboard/contest_alias/SELECTIVO2018_1` es

```
{"status":"ok","problems":[{"order":0,"alias":"Charly-Blak-y-la-casa-de-Tono"},{"order":1,"alias":"Puntos-Criticos"},{"order":2,"alias":"Freddy-el-robot-del-futuro"}],"ranking":[],"start_time":1526911500,"finish_time":1526929500,"title":"Selectivo Final IOI 2018 - D\u00eda 1","time":1526911503000}
```

**Comment by alanboy** [comment]
Y solo pasa en este concurso? O tenemos algo grave entre manos? cc @elendil326

**Comment by darknut** [comment]
@alanboy Es grave, hay envios que dan puntos y que no registran en el concurso hasta mucho después
