### ISSUE TITLE
Función restringida "syscall:mremap" con Ruby

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2024]
Hola amigos de OmegaUp. Un amigo mío estaba intentando resolver el problema https://omegaup.com/arena/problem/Muletillas-de-robots/#runs usando Ruby (tiene gustos algo raros, su último envío es el b8f96865) pero no ha logrado obtener el 100% porque lo mata el sandbox al hacer uso de la llamada al sistema "mremap". Por si las dudas intenté aumentar el límite de memoria, pero no tuvo ningún efecto.

Hasta donde alcanzo a ver, esa llamada al sistema no es tan común (al menos en C++) pero tampoco es peligrosa (creo). No soy muy partidario de Ruby, pero es probable que este aparente inconveniente limite su uso para aquéllos que lo quieran usar. Mis comentarios de "cambia a un lenguaje de verdad" han caído en oídos sordos :(

Saludos!

**Comment by lhchavez** [comment]
ah sí, déjame lo agrego. gracias por reportarlo :D

**Comment by darkmx** [comment]
gracias :)

**Comment by lhchavez** [comment]
listo, se reevaluaron todos los envíos de Ruby que tenían RFE.
