### ISSUE TITLE
Crear ranking mensual para dar seguimiento al coder del mes.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#2025]
Como participante me gustaria saber como va el ranking de los coder del mes para saber que tanto me debo esforzar para ganar.

## Comportamiento Esperado

Poder visualizar el ranking del coder del mes actual mediante una API.

## Comportamiento Actual

En estos momentos no existe tal funcionalidad.

## Contexto

Cuando una persona quiere ser coder del mes, esta compitiendo a ciegas. No sabe si alguien le puede ir ganando y que tanto debe de esforzarse.

**Comment by tvanessa** [comment]
Resuelto de #1938
