### ISSUE TITLE
Aumentar limite de upload de solucion a 20 Kb para problemas en general.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#2031]
Como creador de problemas de competencias de programación, me gustaría poder tener la posibilidad de que los usuarios puedan subir soluciones muy extensas.

## Comportamiento Actual

No permite subir archivos de mas de 10kb.

## Contexto

Cuando la solución del problema es un algoritmo extenso de codificar, no se puede mandar la solución debido a esta limitante.

**Comment by pabo99** [comment]
Duplicado de #1962 que permite temporalmente envíos de 20kb para problemas de Karel.
