### ISSUE TITLE
[FEATURE] Concursos por equipos (como ICPC)

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2033]
Como dice el titulo

**Comment by elendil326** [comment]
Esto podría usar las identidades?

**Comment by elendil326** [comment]
- Un solo equipo, una sola computadora,
 - Una identidad representa un grupo de personas
 - Un feature relevante  a este es mostrar el perfil de la identidad como el grupo ( concursos, problemas resultos, etc.)
- No hay restricción. Al concurso se puede unir tanto individuos como personas
- Faltaría arreglar la funcionalidad de agregar la lista de usuarios. Ahora solo busca en la tabla de ususarios, pero debe buscar en identidades.
