### ISSUE TITLE
[FEATURE] Apartado de tutoriales

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2036]
Apartado de tutoriales
Un lugar centralizado donde encontrar tutoriales (p.ejem el curso de la OMI)

**Comment by elendil326** [comment]
Esto no estaría cubierto ya por los cursos?

**Comment by elendil326** [comment]
Esto se puede resolver poniendo un filtro de público/privado en la lista de cursos. Asumiendo que todos los cursos publicos son tutoriales.

**Comment by elendil326** [comment]
Falta definir el diseño para mostrar de una manera agradable los cursos públicos

**Comment by tvanessa** [comment]
En https://omegaup.com/course/ ya hay una tabla exclusiva para cursos publicos
