### ISSUE TITLE
Recordatorios de problemas no resueltos

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2039]

**Comment by elendil326** [comment]
Falta desarrollar esta idea.

- Marcar problemas para ser resueltos en un futuro y recibir recordatorios de los mismos
- Marcar automáticamente problemas que fueron empezados pero no fueron terminados
- Recordatorios en tareas para cursos

**Comment by lhchavez** [comment]
Esto ya está implementado en https://omegaup.com/profile/
