### ISSUE TITLE
Implementar un sistema de recompensas para comprar casos o pistas

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2044]
Implementar un sistema de recompensas por resolver problemas como “omega coins”. Para comprar casos de prueba o pista  para problemas.

**Comment by carlosabcs** [comment]
@lhchavez  @joemmanuel 
Esto no es lo que hace ahora `Solution Writeups`?

**Comment by lhchavez** [comment]
correcto!
