### ISSUE TITLE
No mostrar "empieza a usar escuelas" para usarios que ya lo usan

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2053]
Si ya se está dentro de un curso ya no debería de aparecer la pantalla de “empieza a usar escuelas” y te debería dirigir directamente a tus cursos.

**Comment by sarvesh211999** [comment]
I want to work on this issue. 
@lhchavez Please assign

**Comment by lhchavez** [comment]
Assigned to @sarvesh211999 ! thanks you very much :)
