### ISSUE TITLE
[FEATURE] API public para consultas de concursos propios

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2054]
Por favor, poner o habilitar un API público para consultas de concursos propios

**Comment by elendil326** [comment]
Esto ya existe, pero se tiene que documentar para uso del público. Este documento puede tomar ejemplos del código abierto de omegaUp.

**Comment by pabloaguilar** [comment]
Fixed con https://github.com/omegaup/libomegaup
