### ISSUE TITLE
[FEATURE] Logros por el tipo de problemas / habilidades

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2057]
Logros para los usuarios según los problemas que resuelve, para que en su perfil aparezcan  sus habilidades

**Comment by carlosabcs** [comment]
Algo relacionado a esto, sería agregar una visualización de los lenguajes de programación más usados por el usuario, en su perfil?

**Comment by tvanessa** [comment]
Queda resuelto con los badges
