### ISSUE TITLE
[FEATURE] Poder eliminar tags de otros en problemas propios

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2061]
Hola amigos de OmegaUp.
Uno de los problemas que subí [https://omegaup.com/arena/problem/Programando-formulas/#problems](https://omegaup.com/arena/problem/Programando-formulas/#problems) pide evaluar unas formulas aritméticas pero alguien le puso el tag "árboles". Desafortunadamente, como autor del problema no puedo eliminar tags que alguien más pone.

**Comment by lhchavez** [comment]
welp, buen punto. @heduenas para que esté enterado.

**Comment by lhchavez** [comment]
asignándolo a @heduenas para que le haga triage.

**Comment by tvanessa** [comment]
@darkmx Implementaron la funcionalidad de quitar todos los tags de los usuarios de un problema especifico. Eso es suficiente? O aún preferirías borrar solo algunos tags?

**Comment by darkmx** [comment]
yo lo veo bien!
