### ISSUE TITLE
El consent de los concursos no está disponible

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2068]
Cuando ingreso al link con el Consentimiento de concursos (https://omegaup.com/privacy/contest-user-information/), me manda un error `404 - Not Found`

## Comportamiento Esperado

Que al dar clic me muestre la página del consent de los concursos.

## Comportamiento Actual

Me manda la siguiente vista:

![captura de pantalla 2018-05-29 a la s 10 02 48](https://user-images.githubusercontent.com/3230352/40667475-e074bbc0-6327-11e8-9b49-241cef887d2c.png)

**Comment by lhchavez** [comment]
sí, está bien. igual con https://github.com/omegaup/omegaup/pull/2020 _tenemos_ que dejar de usar links y poner **todo** el texto del consent ahí.
