### ISSUE TITLE
Tener una manera de ver todos los envíos en la vista de detalles de un curso

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2075]
*Como entrenador, es necesario ver el modo ADMIN de una "tarea" en school. *

## Comportamiento Esperado

Al igual que cuando se crea un concurso, entrar al modo admin para ver los envíos de cada alumnos. 

## Comportamiento Actual

Actualmente no es posible ver los envíos de los alumnos, a menos que seas owner de los problemas que están resolviendo tus alumnos, lo cual es bastante tardado y molesto.

## Posible Solución

Permitir el modo ADMIN

## Contexto

Quita demasiado tiempo, verificar lo que hacen los alumnos sin el modo ADMIN.

**Comment by lhchavez** [comment]
Eso ya se puede hacer :D https://github.com/omegaup/omegaup/commit/13a852809ff7a20e83ae22e05dd169d6646dedf8 sólo necesitas haber resuelto el problema.

**Comment by kukogit** [comment]
No entiendo como eso resuelve mi duda. Cuando hagi un concurso puedo ver
facilmente los envíos de la gente que entra al concurso (agregas /admin al
final de la URL), sin embargo en modo escuela, cuando entro a una TAREA, no
tengo idea de como hacer lo mismo.

O no entiendo que tiene que ver?

**Comment by kukogit** [comment]
Ahora también ya vi que se puede desde el apartado ver avance de alumno, pero creo que ahí sólo puedo ver el último envío... no sé si se puede ver cualquier otro envío, al menos no supe como ver envío por envío en ese apartado.

**Comment by lhchavez** [comment]
oh ya veo, entonces si se pudieran mostrar todos los envíos (de una manera que no se vuelva un relajo visual terrible) en esa sección, solucionaría por completo lo que quieres?

**Comment by kukogit** [comment]
Sí, creo que eso resolvería el issue que puse. De hecho creo que bastaría con darle click a la línea donde esta el detall del envío y que se muestre en el cuadro de arriba.

Saludos.

**Comment by lhchavez** [comment]
ya lo discutimos, y mejor sí lo mostramos exactamente igual que como se muestran en los concursos. así es más fácil de mantener para nosotros y descubrir para ustedes.

**Comment by kukogit** [comment]
Ya no entendí... se van o no a mostrar los envíos de los alumnos en el modo escuela? Sólo para reiterar, a mi sólo me interesa ver los envíos de los chavos, tal cual se ve en el modo ADMIN de los concursos actualmente.

No sé en qué momento "discutimos" la solución.. el issue inicial se trataba de ver los envíos como actualmente se ve en los concursos...

**Comment by lhchavez** [comment]
se van a mostrar en modo admin en los cursos y tareas de la sección de escuelas, tal como se muestran en modo admin de los concursos.

**Comment by kukogit** [comment]
Excelente!!!

**Comment by kukogit** [comment]
Ya merito??? :D

**Comment by lhchavez** [comment]
no, va a tardar varios meses :(

**Comment by kukogit** [comment]
Sacatelas!!!... bueno...

**Comment by pabo99** [comment]
¿Le falta algo a este issue para poder cerrarlo?

**Comment by kukogit** [comment]
Hola Pablo,

Creo que no, acabo de revisar y ya lo puedo ver.

Saludos.
