### ISSUE TITLE
Datepicker and DatetimePicker format

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#2077]
## Current behavior
DatetimePicker and DatePicker are showing `MM/DD/YYYY` format

## Expected behavior
DatetimePicker and DatePicker should show `DD/MM/YYYY`
![screenshot-2018-6-7 contestedit omegaup 1](https://user-images.githubusercontent.com/15065085/41135660-a2613c2a-6aa0-11e8-8f53-bab4779e610f.png)

## Possible solution
Change the following code
https://github.com/omegaup/omegaup/blob/d90f10ac471ecc4647151e38e7a390f5f4edb4ad/frontend/www/js/omegaup/components/DatePicker.vue#L13
https://github.com/omegaup/omegaup/blob/d90f10ac471ecc4647151e38e7a390f5f4edb4ad/frontend/www/js/omegaup/components/DateTimePicker.vue#L14

**Comment by sarvesh211999** [comment]
Is this issue assigned or open ??

**Comment by sarvesh211999** [comment]
Yeah I will try.

**Comment by sarvesh211999** [comment]
Can you just elaborate what to show on the value of `omegaup.T.locale`

**Comment by lhchavez** [comment]
Actually, we can make that string be a translation string, so on `en.lang` the value would be `MM/DD/YYYY` and with `es.lang` and `pt.lang`, the value would be `DD/MM/YYYY`. Then on the `.vue` files, you can just reference `omegaup.T.datePickerFormat`. No need to inspect the value of `omegaup.T.locale`!!!

**Comment by sarvesh211999** [comment]
Yeah Sure .
