### ISSUE TITLE
Como organizador de concurso, quiero poder dar extensiones de tiempo

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#2081]
Cuando hay un concurso con tiempos diferidos, pueden ocurrir circunstancias que ameriten
darle tiempo extra a algún competidor. Actualmente omegaUp no soporta esto, a diferencia
de concursos sin tiempos diferidos en los que se puede mover el tiempo de fin de todos parejo.

**Comment by lhchavez** [comment]
Lo que hay que hacer es dejar de calcular el `end_time` como `access_time` + contestLength, y agregar un campo explícito de `end_time` (que por default sea lo que calculábamos antes). ya con eso se podría modificar el `end_time` conforme sea necesario.

https://github.com/omegaup/omegaup/blob/d32e778cb5caf24b460621b84042a2719f738764/frontend/database/schema.sql#L535

**Comment by pabo99** [comment]
Para la parte de la interfaz se propone agregar una columna en la tabla de usuarios que están registrados en el concurso donde se indique cuando se termina el tiempo para resolverlo. 

El campo se puede editar para dar la extensión de tiempo, siempre y cuando la fecha permanezca dentro del rango de la duración del concurso, y sólo será visible la columna cuando se haya habilitado la opción de inicios separados.

La propuesta queda de la siguiente forma:

![2018-11-07](https://user-images.githubusercontent.com/3230352/48114343-49d20200-e224-11e8-9966-ac3e3ffa45cd.png)
