### ISSUE TITLE
Race condition en PrivacyStatementConsentLogDAO::saveLog

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2088]
`PrivacyStatementConsentLogDAO::saveLog` lee el ultimo Id de la tabla de politicas. Pero esto no necesariamente coincide con lo que se le mostro al usuario si la sucesion de eventos fue:
* Usuario entra a la pagina que pide consentimiento y se toma el tiempo de leer las letritas
* Admin actualiza la politica de privacidad
* Usuario expresa su consentimiento
* `saveLog` lee el id de la politica nueva

Es extremadamente dificil que suceda la situacion anterior. Pero deberiamos poder arreglarlo.
La forma correcta de hacerlo seria pasar el id de la politica que se le mostro al usuario.

**Comment by pabo99** [comment]
Esto ya queda solucionado con los cambios del #1995, ¿Es correcto?

**Comment by pabloaguilar** [comment]
Si, quedo corregido.
Gracias!
