### ISSUE TITLE
Error interno al hacer envíos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2103]
Hola amigos de OmegaUp.
Al hacer envíos se está reportando el siguiente error (información obtenida del inspector de red al momento de hacer el envío).

status	error
error	Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.
errorname	generalError
errorcode	400
header	HTTP/1.1 400 BAD REQUEST

Al parecer los envíos se quedan atascados con status "New" en la página pero pareciera que no son juzgados (y no se puede visualizar la información del envío). Algunos envíos que tienen este problema son el 50029b19, el f0f20a89 y el 3db5d75e del problema https://omegaup.com/arena/problem/Narrando-la-carrera-de-caballos

Rejuzgar estos envíos parece no tener efecto (siguen apareciendo como "New"). Por otra parte, el rejuzgar envíos previamente juzgados parece funcionar sin problemas.

**Comment by lhchavez** [comment]
arreglamos eso ese mismo día. lamentamos la demora y el error :(
