### ISSUE TITLE
[FEATURE] requalify disqualified submission

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#2119]
Related to this PR https://github.com/omegaup/omegaup/pull/2095

## Current behavior
This PR  only allows admin to disqualify user submission. 

## Expected behavior
Allow admin to revert back disqualified submission

**Comment by darkmx** [comment]
Este FR lleva casi dos años, pero algo que puede ayudar y que se puede implementar rápidamente es un window.confirm

**Comment by lhchavez** [comment]
sí, lleva casi dos años, pero tenemos más issues / FR que recursos para atenderlos todos :(

**Comment by darkmx** [comment]
lo sé :( y soy parcialmente culpable de eso, pero se siente muy feo picarle a descallificar por error y no poder deshacer el daño (e imaginar la cara que pone el alumno cuando ve su envío en rojo sin saber por qué); el confirm debe bastar para detener a gente torpe (alias yo) en equivocarse por error

**Comment by lhchavez** [comment]
sí, y precisamente por eso #3864.

**Comment by lhchavez** [comment]
quiénes pueden des-descalificar?

**Comment by darkmx** [comment]
supongo que la persona que descalificó (o con el mismo rol)
si el envío fue en un concurso, el admin del concurso puede descalificar y debería poder hacer lo inverso
si el envío fue en un curso, el admin del curso puede descalificar y debería poder hacer lo inverso
si el envío fue por fuera, el admin del problema

**Comment by tvanessa** [comment]
> quiénes pueden des-descalificar?

Las mismas personas que pueden descalificar, cualquier admin.

**Comment by lhchavez** [comment]
va!
