### ISSUE TITLE
Inconsistent font

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#2124]
## Current behavior
http://domain/problem/new/
![screenshot_20180704_023045](https://user-images.githubusercontent.com/15065085/42260444-731aafb8-7f32-11e8-9c6c-7bb6ac9d04a4.png)
http://domain/problem/prob1/edit/
![screenshot_20180704_023119](https://user-images.githubusercontent.com/15065085/42260447-78540cb8-7f32-11e8-899d-48dc75466c77.png)
Notice those two pages have different font family

## Expected behavior
Use same font for both pages

**Comment by akki111singh** [comment]
I would like to work on this.

**Comment by akki111singh** [comment]
@ihchavez can u assign me this issue?

**Comment by lhchavez** [comment]
assigned to @akki111singh until March 2.
