### ISSUE TITLE
Unhandled deprecated function on datetime

### ISSUE THREAD

**Issue by SpaceWhite** [omegaup/omegaup#2126]
## Current behavior
`DateTimePicker` and `DatePicker` produce error in console when selecting date

![screenshot_20180706_042628](https://user-images.githubusercontent.com/15065085/42368437-073040d4-80d5-11e8-8ea1-052ff322bbad.png)

## Possible solution
Update bootstrap-datepicker.js and datetimepicker.js

**Comment by pabo99** [comment]
En la documentación de  `bootstrap-datetimepicker.js` que se está utilizando trabajan con `jquery-1.8.1` y utilizan un `shorthand` que es obsoleto en `jquery-3.2.1`. ¿Qué tan recomendable es modificar ese shorthand sobre el archivo minificado?
