### ISSUE TITLE
Error sin razon al evaluar un problema

### ISSUE THREAD

**Issue by AresLOLXD** [omegaup/omegaup#2129]
## Comportamiento Esperado
El dia de hoy estaba realizando un concurso en omegaup y note que algunos envios daban error de compilacion, al revisarlos la salida del compilador era: 

> Main:
virtual memory exhausted: Cannot allocate memory

Incluso yo lo probe y me salio el mismo error, volvi a enviar el codigo y me dio.
![image](https://user-images.githubusercontent.com/7190526/42396482-76bac4b8-8127-11e8-9991-94dfad6095dd.png)

## Comportamiento Actual

El servidor de omegaup posiblemente no pueda dar abasto con todas las peticiones, mi compañero me ha dicho que el servidor lleva asi toda la semana.

## Pasos para reproducir (para bugs)
1. No encontre una manera, solo enviando codigos hasta que el error aparezca
## Contexto

Los chicos que estaban resolviendo el examen enviaban su solucion y les mandaba un error sin ninguna culpa de ellos

## Tu ambiente

* Chrome Versión 67.0.3396.99 (Build oficial) (32 bits)
* Windows 7 Ultimate
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/7190526/42396619-0abb34a4-8128-11e8-982e-47918c82bbdd.png)

**Comment by lhchavez** [comment]
Los envíos donde esto ocurría ya fueron reevaluados.

**Comment by lhchavez** [comment]
Cerrando el issue. Gracias por reportarlo! :D
