### ISSUE TITLE
[FEATURE] Agregar UI para guardar comentarios en omegaup.API.Contest.arbitrateRequest

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2131]
Como un co-administrador de concursos por invitación, quiero poder dejar comentarios sobre por qué se aceptó o rechazó a un solicitante.

## Comportamiento Esperado

El API tiene manera de guardar un comentario en el momento en el que se se acepta/rechaza un solicitante.

## Comportamiento Actual

No hay interfaz para escribir el comentario.

## Posible Solución

Agregar la interfaz. Usando un modal para ingresar el comentario, y desplegarlo dentro de la columna de `Current state`.

**Comment by pabo99** [comment]
Steps to reproduce:

- Admin creates a contest and updates the admission mode to: "Registration/open":

![AdmissionModeRegistration](https://github.com/omegaup/omegaup/assets/3230352/388f163c-52f7-49f0-9f0f-0e16a9bf288d)

- Contestant requests access to contest:
![UserRequesAccessToContest](https://github.com/omegaup/omegaup/assets/3230352/ccc76923-fc56-42ca-9b47-e5fe87ec61d3)

- Admin Accept/Reject the user request:
![AdminRejectsUserRequest](https://github.com/omegaup/omegaup/assets/3230352/c5e03018-76bd-49a5-bce8-e6a6af9429f3)

**Comment by Aritra8438** [comment]
Hi @pabo99, so there are two issues to solve?
- Fix the part where the admin can't delete a user.
- Leave a comment why the user was accepted or rejected.

**Comment by pabo99** [comment]
The first part is already completed!

When the admin accepts or rejects the request, a default message is sent to the API. The purpose of this issue is to replace the default message with a comment left by the admin.
