### ISSUE TITLE
El Coder del Mes debe ser aprobado por alguien del equipo de omegaUp Mentors

### ISSUE THREAD

**Issue by JuanM97** [omegaup/omegaup#2132]
*Como un miembro del equipo de omegaUp mentores, quiero poder aprobar al Coder del Mes antes de ser publicado en la página y antes de que reciba el anuncio de ganador en su perfil para poder verificar que no existan signos claros de posible trampa.*

## Comportamiento Esperado
*Una vez determinado el Coder del Mes, quiero tener la habilidad de poder aprobarlo en la página, en vez de ser esto un proceso automático. De esta forma, si existe un caso que el equipo determine viola las reglas del programa, puedan repetir esta evaluación con el siguiente usuario del ranking, hasta determinar al ganador del Coder del Mes.*

## Comportamiento Actual
*Actualmente, al final del mes, el usuario que obtuvo más puntos (en ese mes) es nombrado Coder del Mes. Su nombre es mostrado en la página y se muestra un mensaje en su perfil pidiendo que se ponga en contacto con el equipo de mentores para recibir su premio.*

## Posible Solución
Adaptar una interfaz similar a la de code reviewers para bannear problemas.

## Contexto
*Se detectaron ciertos casos de posible trampa en el nombramiento de Coder del Mes en la plataforma, con lo que el equipo de Mentores requiere verificar dicho nombramiento antes de hacerse público*

**Comment by elendil326** [comment]
Actualmente el coder del mes se calcula cuando el primer request pide saber quién es el coder del mes. Hay que borrar este código. En la UI de los administradores de mentores hay que darle opción de elegir uno de los posibles candidatos

**Comment by pabo99** [comment]
Para no borrar código y poder reutilizar el existente, se puede agregar un campo en la DB donde indique si el usuario fue aprobado, por default tendría `NULL`. Una vez que se apruebe este campo pasa a 'YES'.

El código que se agregaría sería el que vuelva a calcular el `Coder of the month`, omitiendo a los usuarios que hayan sido rechazados en el mes actual desde la `UI` de los administradores de mentores.

**Comment by pabo99** [comment]
A este issue le falta la interfaz

**Comment by heduenas** [comment]
este issue todavia necesita mas trabajo?

**Comment by pabo99** [comment]
No, con el PR #2533 se puede cerrar este issue.
