### ISSUE TITLE
[BUG] Los alumnos no pueden ver el ranking en modo escuela

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2133]
Los alumnos no pueden ver el ranking en el modo Escuela.

## Comportamiento Esperado

Que los alumnos puedan ver su avance y compararlo con los demás alumnos.

## Comportamiento Actual

Al indicar que queremos "Mostrar el scoreboard" y dar actualizar te dice que se hicieron los cambios, pero al darle F5, nuevamente aparece en NO.

## Pasos para reproducir (para bugs)

1. Seleccionar la opción SI de mostrar scoreboard
2. Dar click en el botón actualizar
3. Esperar a que de la indicación de que ya se actualizó
4. Dar F5 para ver que nuevamente está en No.

**Comment by lhchavez** [comment]
El scoreboard en sí ya está en el codebase, sólo falta hacer que el botón funcione y se guarde en la base de datos la preferencia.

**Comment by kukogit** [comment]
Ya no funciona otra vez!!!

**Comment by kukogit** [comment]
@lhchavez

**Comment by pabo99** [comment]
Resulta que si creas un curso con la opción de mostrar scoreboard, si funciona correctamente. Si después editas el curso para que no se muestre el scoreboard, también funciona. 

El problema viene cuando editas el curso para que se vuelva a mostrar.
