### ISSUE TITLE
Los links Publico/Administrador de las tareas/examenes del modo escuela no funcionan

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2144]
## Comportamiento Esperado

Que puedan visualizarles el ranking con los links de Publico y Administrados del modo tarea

## Comportamiento Actual

No funciona, sólo muestra la página de Omegaup pero no los scores

## Contexto

Mientras la opción de "Mostrar Score" (de un curso en el modo escuela) no funcione, la posible forma de ver el score era a través de los links de Publico/Administrador, pero no funcionan, así que los alumnos no pueden comparar su avance con el resto de sus compañeros.

**Comment by pabo99** [comment]
Tienes alguna captura de pantalla o links para ver en donde falla?

**Comment by kukogit** [comment]
Si yo como admin del curso, quiero ver los link públicos y administrador, puedo hacerlo, pero si se los comparto a los de más usuarios, sólo ven lo siguiente:

![Screenshot](https://user-images.githubusercontent.com/6465292/43620388-faabe812-9697-11e8-87a4-c38878b511ad.jpeg)

**Comment by lhchavez** [comment]
puedes compartir el URL porfa? eso se corta en el screenshot.

**Comment by kukogit** [comment]
admin:

https://omegaup.com/course/ENTKPCCPP01/assignment/ENTKPCCPP01A01/scoreboard/13d625c0a13668122d698e1f6134a2

público:
https://omegaup.com/course/ENTKPCCPP01/assignment/ENTKPCCPP01A01/scoreboard/67c759f48d2936de8989b51307c98c

**Comment by pabo99** [comment]
Los links deben verse sin necesidad de loguearse.

**Comment by pabo99** [comment]
¿Le falta algo a este `PR`?
