### ISSUE TITLE
El script redaccion.php ya no recupera la redacción

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2149]
## Comportamiento Esperado

Anteriormente, el script redaccion.php permitía recuperar la redacción de un problema.

## Comportamiento Actual

Actualmente aparece el mensaje de recuperar la redacción pero se quita automáticamente y no recupera la redacción anterior.

## Pasos para reproducir (para bugs)

1. Entrar a omegaup.com/redaccion.php 
2. Hacer una modificación a la redacción
3. Dar F5 o enter en la barra de dirección sin cambiar la dirección
4. Esperar a que carga para ver como no recupera la redacción

## Contexto

Es importante que funcione el script, ya que si uno escribe la redacción y por alguna razón no se hizo un backup de la redacción, pues se pierde tiempo en volver a escribirlo.

## Tu ambiente

Sucede en cualquier navegador.

**Comment by SpaceWhite** [comment]
![Screenshot](https://user-images.githubusercontent.com/15065085/44397152-46748780-a50d-11e8-8ee3-84ebcd7f670b.gif)
I can't reproduce the error
