### ISSUE TITLE
No se puede editar un concurso propio (error 404)

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2150]
Hola amigos de OmegaUp.
Un concurso que tenía planeado poner como examen ya no puedo editarlo. Anteriormente estaba funcionando bien. 

Programación Estructurada (examen 3t, examen 4t) - 2018P
PE3t4t_UAMA2018P
https://omegaup.com/contest/PE3t4t_UAMA2018P/edit/

No sé si tenga algo que ver que el concurso sea en modo registro. Anteriormente no tenía problemas al editarlo pero hace como media hora solicité registrarme a mi propio concurso para ver cómo funcionaba ese modo (teoría: tal vez el sitio cree que no tengo permiso de acceso porque el admin no lo ha aprobado, pero yo soy el admin :( ).

**Comment by lhchavez** [comment]
Esto es porque https://github.com/omegaup/omegaup/blob/4ea1080088f922ec907529e3d206f372c29a65da/frontend/server/controllers/ContestController.php#L2032 espera un `username`, pero en la tabla se guarda la `Identity` de un usuario que cambió su `username`.

Por lo pronto hice el cambio manual en la base de datos para que los usuarios correspondieran, y abrí un bug para arreglar el problema de raíz.

**Comment by darkmx** [comment]
gracias :)
