### ISSUE TITLE
Subdominio https://ses.omegaup.com/ reedirige a una pagina externa.

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#2156]
Llegue ahi revisando la liga de unsuscribe de nuestros newslatters de antaño.

@joemmanuel

**Comment by joemmanuel** [comment]
Arreglado ... .ses era usado para el mailing list que ya dejamos de usar. Seguramente alguien m'as adquiri'o la misma IP p'ublica.

**Comment by lhchavez** [comment]
gracias! nomás para el record, cuál fue la solución?

**Comment by joemmanuel** [comment]
Borr'e la entrada de ses en godaddy.
