### ISSUE TITLE
Insertar múltiples alumnos

### ISSUE THREAD

**Issue by renepayan** [omegaup/omegaup#2158]
## Comportamiento Esperado
* Insertar múltiples alumnos en la sección de cursos de omegaUp Escuelas
## Comportamiento Actual
* Los alumnos se tienen que agregar uno por uno
![captura](https://user-images.githubusercontent.com/4644454/43494604-4d1f8f40-94f9-11e8-9a38-2a9520ddcdb5.PNG)

**Comment by elendil326** [comment]
¿Escribir el nombre de usuario de los alumnos separado por punto y coma es una solución aceptable?
¿Hay algún otro formato que usen para almacenar los usuarios de los alumnos que pueda ser reutilizado? Como CSV por ejemplo.

**Comment by MiguelRomero** [comment]
1.- Sí separado por ';' tambien es viable.
2.- El csv separado por comas tambien es viable.
Se propuso asi por que en los examenes de la arena, agregan multiples usuarios separando por comas, pero a nosotros nos es indiferente como lo quieran solucionar.

**Comment by lhchavez** [comment]
Se decidió convertir lo de agregar estudiantes a un componente, para poder reutilizar lo que se hace en otros lados, donde se tiene un textarea que permite agregar varios estudiantes y un textbox para agregarlos uno por uno.
