### ISSUE TITLE
Error al clonar un curso

### ISSUE THREAD

**Issue by renepayan** [omegaup/omegaup#2160]
## Comportamiento Actual
* Al tratar de clonar un curso en omegaUp escuelas, la plataforma muestra un error, y no permite crear el nuevo curso
![captura](https://user-images.githubusercontent.com/4644454/43494756-f8f3a338-94f9-11e8-8d85-3b9520c274f7.PNG)

**Comment by pabo99** [comment]
¿Esto sigue haciendo repro?

Hice pruebas en local y en `sandbox` y me permite clonar los cursos correctamente

![2018-10-30](https://user-images.githubusercontent.com/3230352/47755716-ec0e4a80-dc64-11e8-96b4-503c058d96c8.png)

**Comment by pabo99** [comment]
Las pruebas que se realizaron fueron las siguientes:

- Curso sin tareas ni exámenes.
- Curso con tareas y/o exámenes, pero sin problemas.
- Curso con tareas y/o exámenes y con al menos un problema.
- Curso sin escuela registrada.
- Curso con escuela nueva.

En todas las pruebas se pudo clonar correctamente el curso. Se cierra el issue hasta que vuelva a ocurrir.
