### ISSUE TITLE
Error al entrar a un examen en la Arena

### ISSUE THREAD

**Issue by renepayan** [omegaup/omegaup#2175]
No se puede acceder a los exámenes recién creados en la arena
solo sucede si se solicita compartir información al momento de crear al examen
![captura](https://user-images.githubusercontent.com/4644454/44311640-82dea100-a3b0-11e8-9235-9bf67dc60191.PNG)

**Comment by elendil326** [comment]
Este ya quedo resuelto con #2172 . Puedes volver a abrirlo si esto sigue haciendo repro.
