### ISSUE TITLE
Error al modificar las fechas de un curso

### ISSUE THREAD

**Issue by renepayan** [omegaup/omegaup#2176]
Cuando se tratan de modificar las fechas de un curso, si la fecha de inicio no se cambia a una fecha posterior, el sistema no permite editar el curso
![39526016_693827747653182_1669579578957365248_n](https://user-images.githubusercontent.com/4644454/44311709-f339f200-a3b1-11e8-8a2b-3aedf3b3f25c.png)

**Comment by SpaceWhite** [comment]
It seems like you want to start an assignment before the course even started. I think we can't do that

**Comment by lhchavez** [comment]
oh ya veo. efectivamente, como dice @SpaceWhite no permitimos hacer _cursos nuevos_ cuando la fecha ya pasó, pero sí deberíamos de permitir _editar cursos existentes_ conservando la fecha actual.
