### ISSUE TITLE
Progreso de Estudiantes en Escuelas

### ISSUE THREAD

**Issue by yeyoboy** [omegaup/omegaup#2177]
Error al Intentar revisar el progreso de estudiantes en "ESCUELAS".

Quiero revisar los envíos de los estudiantes y al intentar hacerlo me marca error.

![captura de pantalla 2018-08-20 a la s 09 17 59](https://user-images.githubusercontent.com/13025387/44345860-115b2d00-a45a-11e8-8795-0ffd4d3becd0.png)

**Comment by lhchavez** [comment]
se le hará deploy a producción el domingo siguiente
