### ISSUE TITLE
Actualizar la redacción de un problema no se refleja inmediatamente

### ISSUE THREAD

**Issue by rccuam** [omegaup/omegaup#2189]
Hola amigos de OmegaUp. 
Actualizar la redacción de un problema está dando problemas (valga la redundancia :). Ocasionalmente se está elevando la siguiente excepción del lado de Javascript al darle clic al botón "Actualizar redacción".

[imagen](https://imgur.com/pEJF40I)

Esto no ocurre siempre, pero sí bastantes veces. Parece que la actualización no siempre se refleja en el servidor a pesar de que se muestra el mensaje usual de "¡Problema actualizado exitosamente!"

**Comment by darkmx** [comment]
Hola de nuevo, al parecer el problema es un poco más raro. 

Por una parte, cuando la excepción se eleva se manda una petición POST a https://omegaup.com/jserrorreport.php que supongo es intencional. Una cosa rara es que darle click al botón puede que no eleve la excepción pero en algún momento se eleva por sí sola (sin recargar la página).

Lo más raro del asunto es que una actualización "procesada correctamente" (la petición sí se manda y el servidor responde que todo está OK) a veces tarda en verse reflejada: si abres el problema y la actualización no se ve, te la puedes pasar dándole F5 hasta que en algún momento ya aparece. No sé si tenga algo que ver con alguna caché que antes no existía y ahora sí; tendré que investigar un poco más cómo funciona OmegaUp y les aviso lo que encontré.

**Comment by darkmx** [comment]
Algo similar ocurre con el `textarea` que tiene la descripción del problema a actualizar. Si recargas el formulario después de realizar una edición, es posible que se cargue la vieja versión; despúes de esperar algunos segundos o un minuto ya aparece la nueva versión al recargar la página.

**Comment by lhchavez** [comment]
oh, esto es porque no estamos invalidando el cache correctamente :S se supone que con https://github.com/omegaup/omegaup/pull/2191 ya se va a arreglar.

**Comment by darkmx** [comment]
ya veo, gracias por la respuesta :)
