### ISSUE TITLE
BUG: No se visualizan correctamente los concursos previos.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2195]
## Comportamiento Esperado

Mostrar los concursos donde participe dentro de mi perfil.

## Comportamiento Actual

No se muestran los concursos en los cuales e participado dentro de mi perfil.
## Pasos para reproducir (para bugs)

1. Ingresar al perfil personal. ( https://omegaup.com/profile/ )
2. Buscar la parte de concursos.

## Contexto

Para poder ver rapidamente las personas con las que participe y ver tus resultados anteriores en los concursos y poder mejorar mis scores.

## Tu ambiente

* Nombre del navegador: Chrome
* Sistema Operativo y versión: MACOS 10.3
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/
* Captura de pantalla: <img width="1566" alt="julian" src="https://user-images.githubusercontent.com/5459260/45556291-83782500-b800-11e8-8882-8a1fc6739f12.png">

**Comment by yoniihdc** [comment]
@elendil326 puedes asignarme el issue.

**Comment by yoniihdc** [comment]
@pabo99 ya esta el PR #2276 una disculpa por la demora.
