### ISSUE TITLE
BUG: Mezcla de calificaciones de problemas dentro de un concurso.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2196]
## Comportamiento Esperado

En el concurso el scoreboard se muestra actualmente de esta forma, notar el problema ​U que ya ha sido resuelto por mi según la tabla, sin embargo, dicho problema no ha sido resuelto por mi.

## Comportamiento Actual

Se estan intercambiando las puntuaciones de problemas que no se han resuelto por problemas que ya estan resuelto, de tal manera de que se otorga puntaje al problema incorrecto.

## Pasos para reproducir (para bugs)

No identificado plenamente.

## Contexto

El usuario estaba en un concurso, mando una solución del problema "A" y se otorgo el puntaje al problema "B" de tal manera que "B" jamas fue resuelto pero tiene el puntaje del problema "A"

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome en su última versión
* Sistema Operativo y versión (escritorio o móbil): Ubuntu Linux 16.04 LTS Escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/TeamSkynet-Training-01#ranking
* Captura de pantalla:
<img width="937" alt="mikael" src="https://user-images.githubusercontent.com/5459260/45644387-440d3b00-ba83-11e8-82cb-303da18e89dc.png">
<img width="954" alt="mikael2" src="https://user-images.githubusercontent.com/5459260/45644388-440d3b00-ba83-11e8-8fcd-78464a5fa6ae.png">
<img width="960" alt="mikael3" src="https://user-images.githubusercontent.com/5459260/45644389-440d3b00-ba83-11e8-98f7-173cabfa5c53.png">

**Comment by pabo99** [comment]
El problema viene en la forma de ordenar los problemas dentro del concurso. Al no elegirlo, todos los problemas se guardan con `order = 1`, esto ocasiona que al realizar la consulta ordenada por este campo, siempre se ordenen arbitrariamente, y por ende, nunca coincida el orden de los problemas en el scoreboard, con el listado de los problemas.

![2018-10-23 1](https://user-images.githubusercontent.com/3230352/47443721-9d4f4500-d77a-11e8-9d62-3c96f5f39893.png)
![2018-10-23 2](https://user-images.githubusercontent.com/3230352/47443726-a04a3580-d77a-11e8-834b-9e2e078e69a1.png)
![2018-10-23 3](https://user-images.githubusercontent.com/3230352/47443733-a2ac8f80-d77a-11e8-8043-a60e42e1213a.png)
![2018-10-23 4](https://user-images.githubusercontent.com/3230352/47443737-a3ddbc80-d77a-11e8-91b4-1ad85052f81e.png)
![2018-10-23](https://user-images.githubusercontent.com/3230352/47443741-a6401680-d77a-11e8-89ba-23c9c85ee91f.png)

Hay dos propuestas para solucionar este bug:

- Arreglar todas las consultas que obtienen los problemas de un `Problemset` para que siempre ordenen por `order` y `problem_id`.

- Solucionar el problema desde raíz, cada que se agregue un problema a un `problemset`, almacenar el orden que le corresponda. Además de agregar un `SP` para actualizar el orden en los concursos que ya se crearon anteriormente.
