### ISSUE TITLE
Modificar la hora de fin de un concurso "cancela" el concurso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2200]
Hola amigos de Omegaup.

En la mañana intenté organizar un concurso rápido de práctica https://omegaup.com/arena/AED2018O/#problems y después de explicarles los problemas a los alumnos, decidí agregar 5 minutos al concurso. Sin embargo, al hacerlo la cuenta regresiva dentro del concurso se fue a 00:00:00 a pesar de que la hora de fin aparentemente sí se actualizó exitosamente (de hecho sigue apareciendo bien en la página, pero la cuenta regresiva simplemente se quedó en ceros: la hora de inicio era 8:20, la hora original de fin era 8:50 y la volví 8:55).

Aunque durante clase tuve que crear rápido otro concurso para los alumnos, no me gustaría intentar reproducir el problema creando más concursos porque no se pueden eliminar. Prefiero pasarles el reporte.

**Comment by darkmx** [comment]
muchas gracias :)

**Comment by lhchavez** [comment]
aún no hacemos deploy de esto, pero manualmente ya arreglé todos los concursos afectados.

**Comment by darkmx** [comment]
Vale, gracias :)

También me gustaría aprender cómo funciona OmegaUp para poder ayudar a corregir cosas en lugar de nada más andar dando lata. Leí en algún lado que andaban haciendo una v2 (no recuerdo si de front-end, back-end o de ambos). ¿Tienen alguna recomendación para poder aprender rápidamente lo que se necesita sobre el funcionamiento de la plataforma? (manejo bien php/js, el detalle sería sólo aprender lo del sistema en sí).

**Comment by joemmanuel** [comment]
@darkmx gracias por tu interés! Puedes empezar por aquí: https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar . Si te quieres unir a nuestro equipo de colaboradores voluntarios, te puedo mandar una invitación a nuestro slack.

**Comment by darkmx** [comment]
vale :) ya actualicé mis datos de contacto en mi perfil de github; probablemente el martes instale lo que se menciona en la wiki
