### ISSUE TITLE
BUG: Fallo al crear concursos

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2201]
## Comportamiento Esperado
Debe mostrar el tiempo en el cual debe comenzar el concurso correctamente.

## Comportamiento Actual

El tiempo se queda en: "00:00:00"

## Contexto

A los concursantes en el tiempo les aparece 00:00:00, independientemente del tiempo seleccionado al crearlo y cuando intentan enviar les aparece: "El concurso ya terminó o aún no empieza"

**Comment by lhchavez** [comment]
dupe de #2200
