### ISSUE TITLE
Error del juez (JE) en envíos 

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2204]
Hola amigos de Omegaup.
El juez en línea está teniendo problemas con los envíos (no sé si con algunos o con todos). Algunos envíos que tienen status JE en el "verdict" de la respuesta JSON de OmegaUp son:

2018-09-21 16:57:12 	2b673553 
2018-09-21 16:33:11 	e74acc88 
2018-09-21 16:32:07 	15260fde 
2018-09-21 16:30:11 	8f13f16b 
2018-09-21 16:09:46 	b18390d5 
2018-09-21 15:58:56 	dedb0f30 
2018-09-21 15:41:50 	47ee975c 	

Todos en https://omegaup.com/arena/problem/Suma-de-intervalos/#problems
Al intentar hacer un envío en otro problema (https://omegaup.com/arena/problem/La-secuencia-infinita/) salió lo siguiente:

```
{untranslated:RuntimeException: Not able to write '
EL CÓDIGO
' in file. /var/lib/omegaup/submissions/af/b5783574617dc5a0446f34dc60e257 in /opt/omegaup/frontend/server/libs/FileHandler.php:45
Stack trace:
#0 /opt/omegaup/frontend/server/controllers/RunController.php(357): FileHandler::CreateFile('/var/lib/omegau...', '#include <cstdi...')
#1 /opt/omegaup/frontend/server/libs/Request.php(72): RunController::apiCreate(Object(Request))
#2 /opt/omegaup/frontend/www/api/ApiCaller.php(31): Request->execute()
#3 /opt/omegaup/frontend/www/api/ApiCaller.php(83): ApiCaller::call(Object(Request))
#4 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()
#5 {main}}
```

**Comment by lhchavez** [comment]
se le acabó el espacio en disco, pero ya quedó.

**Comment by darkmx** [comment]
gracias :)
