### ISSUE TITLE
omegaUp da 502

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#2225]
## Comportamiento Esperado

Cuando visito omegaUp.com puedo utilizar el sitio.

## Comportamiento Actual

Recibo un error 502.

## Pasos para reproducir

1. Abrir omegaup.com

**Comment by SpaceWhite** [comment]
@frcepeda I think this relate to this issue #2223

**Comment by lhchavez** [comment]
it is. but in the meantime some config values were tuned and the service restarted
