### ISSUE TITLE
BUG: Al actualizar la redacción de un problema

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2229]
## Comportamiento Actual

Al tratar de actualizar la redacción de un problema, llenar el campo "Descripción del cambio" y dar lick en el botón actualizar, indica que ya hizo el cambio pero al revisar el problema, no hay tal actualización.

Después de varias ocasiones, tal vez por "suerte" se actualiza la redacción.

## Pasos para reproducir (para bugs)

Bastante simple:

1. Elige tu problema favorito
2. Haz un cambio simple, cualquier cosa, en la redacción
3. Llena el campo obligatorio "Descripción del cambio"
4. Click en actualizar
5. Y listo, verás como NO se actualiza.

## Contexto

Cuando un problema tiene un error, es importante corregirlo lo antes posible para evitar problemas de interpretación del mismo.

## Tu ambiente

* Chrome 70
* Windows 10
* En cualquier problema

**Comment by darknut** [comment]
También me pasa a mi

**Comment by darknut** [comment]
Le podemos subir la prioridad a este bug? Es bastante molesto tener que volver a subir todo el zip para acutalizar la redacción. Eso o darle clic mil veces hasta que jale, lo cual imagino no es bueno para los servers de OmegaUp

**Comment by MiguelRomero** [comment]
OMW @darknut

**Comment by lhchavez** [comment]
@kukogit es más rápido que nos enteremos, pero pues es un proyecto grande y todos somos voluntarios :(

**Comment by darkmx** [comment]
@kukogit @darknut https://github.com/omegaup/omegaup/issues/2189

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/2189
