### ISSUE TITLE
TLE marcado como RTE cuando la memoria se excede por mucho

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2230]
## Comportamiento Esperado

Cuando mandas un código cuya memoria se excede por mucho la que permite OmegaUp, pero que compila bien localmente, el evaluador dice RTE cuando debería decir TLE.

Ejemplo:

Envío b87621a2 para problema votacion

## Contexto

Cuando los competidores ven un RTE están esperando un error tipo segment fault, salirse del arreglo, dividir entre cero, etc, esto no califica como nada de eso, ya que disminuir la memoria usualmente resulta en algunos puntos.

**Comment by lhchavez** [comment]
esto es casi imposible de arreglar sin introducir montones de hacks en las librerías estándar :( la cosa es que si pides _demasiada_ memoria, [`malloc(3)`](https://linux.die.net/man/3/malloc) regresa `NULL` legítimamente.

**Comment by lhchavez** [comment]
sí, entiendo. lo que pasa es que es casi imposible de que haga lo que quieres sin romper montones de cosas o hacerlo imposiblemente difícil de mantener cuando haya updates.

**Comment by darknut** [comment]
No es posible marcarse siquiera como error de compilación? Bueno, al menos ya vi que en el '?' sí dice que puede ser por tener arreglos muy grandes :/

**Comment by lhchavez** [comment]
no hay manera de decirle a gcc/clang que se queje si la memoria que pediría en runtime excede el límite :( podrían haber hacks horrendos inspeccionando el binario, pero no existe manera de hacerlo parejo para los demás lenguajes. entonces mejor hay que dejarlo así.
