### ISSUE TITLE
Hubo un error al agregar un problema a un concurso una vez

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2239]
## Comportamiento Actual

Se tiene un problema con nombre "0110 0101 0122 0104" y alias "0110-0101-0122-0104". Cuando lo quiero agregar a un examen, me dice que el problem_alias no existe en la base de datos.

Problema:
https://omegaup.com/arena/problem/0110-0101-0122-0104/#problems

![image](https://user-images.githubusercontent.com/123875/48309085-98361800-e526-11e8-91d4-089d5784036f.png)

**Comment by lhchavez** [comment]
hmm esto no me hace repro (sí pude agregar y quitar ese problema a otro concurso). puedes intentar reproducirlo [grabando un HAR](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) y compartiéndolo porfa? inmediatamente después de generar el HAR, haz logout y login para invalidar tu token de acceso (porque el HAR lo va a contener).

**Comment by darknut** [comment]
Tan raro eso... lo volví a intentar y ahora sí funciona :/
