### ISSUE TITLE
Los problemas de un concurso se listan en orden incorrecto.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2243]
Hola amigos de OmegaUp. Un concurso que organizo https://omegaup.com/arena/UAM2018/ acaba de iniciar y dos problemas se están mostrando en un orden contrario al establecido. El error parece radicar únicamente al momento de dibujarlos, ya que los datos que devuelve el servidor están bien.

Reproduje el error en Firefox 64 y Chrome 72, ambos en Windows 10.

![sin titulo](https://user-images.githubusercontent.com/19719969/48429035-eb2feb00-e731-11e8-98f8-2ce590f5d0d6.png)

**Comment by darkmx** [comment]
Hola de nuevo, parece que también ocurre un error similar (pero al parecer no idéntico) al reportado en #2196. El problema que yo quería que fuera el A aparece como el B en la lista izquierda, pero sí aparece como el A en el ranking.

![sin titulo](https://user-images.githubusercontent.com/19719969/48441171-7a4bfb80-e750-11e8-9ef2-f5cf511065a2.png)

En el issue anteriormente mencionado se dijo que una posible causa de dicho issue era la existencia de empates en "order", pero en el concurso que organicé no hay empates en "order".

Saludos!!

**Comment by kukogit** [comment]
x2

**Comment by darkmx** [comment]
Hola de nuevo, la información del concurso ya aparece correctamente (no le he movido mano, así que tal vez algún cambio reciente en OmegaUp arregló el problema).

Saludos!!

**Comment by lhchavez** [comment]
ah, excelente! parece que https://github.com/omegaup/omegaup/commit/33b2b95b9e1daa422d6586001c7259e3a99eb4a3 fue suficiente entonces para arreglarlo :D  gracias por avisarnos que ya quedó. cerrando issue.
