### ISSUE TITLE
No sé visualiza correctamente el curso

### ISSUE THREAD

**Issue by AresLOLXD** [omegaup/omegaup#2256]
## Comportamiento Esperado
Qué cargue el scoreboard
## Comportamiento Actual
No carga el scoreboard en el frontend, el API está funcionando correctamente.
## Posible Solución
Arreglar el frontend
## Pasos para reproducir
1. Abrir cualquier curso
![img_20181118_130921_hdr](https://user-images.githubusercontent.com/7190526/48677021-5d3e7080-eb34-11e8-968a-380e5cd5f047.jpg)

## Contexto
No se puede hacer el scoreboard de la preselección
## Tu ambiente
Navegador Firefox 63.0.3
Windows 10 1803
64 bits

**Comment by pabo99** [comment]
Aún te sigue ocurriendo esto? 

Actualmente puedo ver los scoreboards de un curso. En un curso el organizador tiene la opción de elegir si quiere que se muestren o no. 

![Captura de Pantalla 2019-06-06 a la(s) 13 48 41](https://user-images.githubusercontent.com/3230352/59058247-d350bd80-8861-11e9-9db1-e5640c351024.png)

**Comment by lhchavez** [comment]
Parece que ya no ocurre. Si esto no es cierto, por favor vuélvelo a abrir.
