### ISSUE TITLE
Bug: Concurso de OmegaUp no permite que los concursantes entren

### ISSUE THREAD

**Issue by eloisagc** [omegaup/omegaup#2268]
## Descripción del bug
Tenemos un concurso abierto y los estudiantes deberían poder accesarlo, sin embargo aparece un error "interno" y no permite el acceso.

## Comportamiento Actual

Va la captura de pantalla del usuario después de intentar entrar al concurso en la arena
<img width="822" alt="screen shot 2018-12-03 at 8 51 30 am" src="https://user-images.githubusercontent.com/6990253/49396070-141e1d00-f6ed-11e8-8184-529d50243e5c.png">

y las capturas de pantalla de la consola del navegador indicando los errores:

<img width="280" alt="screen shot 2018-12-03 at 8 57 36 am" src="https://user-images.githubusercontent.com/6990253/49396107-2ac47400-f6ed-11e8-9eba-9ded2871e0ce.png">

<img width="552" alt="screen shot 2018-12-03 at 9 06 36 am" src="https://user-images.githubusercontent.com/6990253/49396110-2ef09180-f6ed-11e8-86e5-5a3073f6d6ff.png">

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móbil): Os X Mojave
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/OMIBC2018PrepaExOnline

**Comment by lhchavez** [comment]
ya hicimos el deployment a producción. ya se solucionó el problema?
