### ISSUE TITLE
Bug: Concurso privado en OmegaUp no deja entrar a los concursantes

### ISSUE THREAD

**Issue by eloisagc** [omegaup/omegaup#2278]
## Comportamiento Actual

Este issue está relacionado con un bug que había reportado recientemente https://github.com/omegaup/omegaup/issues/2268
en el cual los concursantes no podían accesar un concurso privado

## Posible Solución

Nos dimos cuenta que poniendo el concurso como público ya no marcaba el error y dejaba entrar a los concursantes.

## Tu ambiente

Nombre del navegador (e.g. Chrome 39, node.js 5.4): Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Sistema Operativo y versión (escritorio o móbil): Os X Mojave
Link al sitio en el que este problema pasa: https://omegaup.com/arena/OMIBC2018PrepaPreSelectivo/

**Comment by lhchavez** [comment]
Ay madre, creo que arreglamos esto hace muchísimo tiempo pero se nos olvidó cerrarlo. Si sigue ocurriendo, por favor vuélvelo a abrir.
