### ISSUE TITLE
Banner de idioma oculta el menú de problema

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2284]
Apenas hoy abrí OmegaUp y había un nuevo feature para cambiar de idioma, eso hacía que el banner de arriba se desplegara en dos filas. De ahí no había problema, pero en cuanto entré a uno de mis problemas, oculta el menú del problema:

<img src="https://i.imgur.com/CxOCmSO.png"/>

Repro en Chrome y Firefox

**Comment by lhchavez** [comment]
dupe de #2285
