### ISSUE TITLE
Errores intermitentes durante un examen (reportado por usuario)

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#2289]
## Comportamiento Actual

Un usuario nos reportó esto (12/19/18 ~11AM Pacific Time)
![image](https://user-images.githubusercontent.com/684205/50243472-23a29480-0382-11e9-9a86-9a2646de0084.png)

El error observado es 502 bad gateway.
El error no está vinculado con ninguna cuenta en particular.

## Contexto

Usuario ubicado en México
Esto pasó durante un examen

**Comment by lhchavez** [comment]
a la siguiente hay que pedirle a la gente que reporte directamente en github para no perder tantísimo contexto jugando al teléfono descompuesto :(

hoy durante dos ocasiones entró el watchdog que automáticamente reinicia al frontend, así que posiblemente fue una de esas. cerrando porque todo WAI
