### ISSUE TITLE
Internationalize quality nomination tags 

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#2307]
For example, 'math' and 'matematicas' are being treated as different tags during aggregation.
Since there is a minimum number of votes required to post a tag, this is preventing some problems with few votes from posting tags and affecting the quality of the tags posted for problems with enough votes.

This is where tags are aggregated: https://github.com/omegaup/omegaup/blob/master/stuff/cron/aggregate_feedback.py#L155

**Comment by lhchavez** [comment]
more than i18n, we need equivalency classes or canonicalization of tags. otherwise we also run into "mate" vs. "matemáticas", even within the same language.

and if we want to add more smarts to tags, maybe we should also consider parent/child relationships between tags (say, "data structures" and "arrays")

**Comment by heduenas** [comment]
I think having a canonicalization or a family tree of tags would be ideal, but it would be rather expensive and would be most helpful for tags inputted by the user by hand. For the issue at hand we only have a [short list of possible tags](https://github.com/omegaup/omegaup/blob/85e2c199555361a76c37cc8dddcebd5ca4486a73/frontend/www/js/omegaup/components/qualitynomination/Popup.vue#L202) to deal with. 

I think it is best to fix the localization issue for tags coming from feedback form for now, and leave the canonicalization for a later time when we can allocate the necessary resources. I also feel like we should fix this localization issue regardless of whether we do the canonicalization thing.
