### ISSUE TITLE
Error al ingresar a un concurso en omegaup.com, me da el error "Intento de Cross-site Request Forgery"

### ISSUE THREAD

**Issue by gilberto2112** [omegaup/omegaup#2327]
*Error al ingresar a un concurso en omegaup.com, me da el error "Intento de Cross-site Request Forgery".
*El navegador es Chrome

**Comment by SpaceWhite** [comment]
@gilberto2112 Could you provide more details? Such as the url you were visiting?

**Comment by tvanessa** [comment]
No se reproduce
