### ISSUE TITLE
Error al editar concurso con "penalty desde que se abrió el problema"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2329]
Hola amigos de OmegaUp.
Hay un bug menor pero medio latoso: creé el concurso https://omegaup.com/contest/AED-2019I-D sin penalties y después intenté ponerlo en modo "penalización [...] por minutos desde que se abrió el problema" pero me marca error interno. La petición parece bien formada y los demás modos de penalización parecen funcionar bien (al menos se acepta la edición del concurso).

![imagen](https://user-images.githubusercontent.com/19719969/51502623-7d8ce480-1d9c-11e9-9130-bcab2aec1fc7.png)

**Comment by lhchavez** [comment]
huh. puedes intentarlo de nuevo y hacer click en el enlace de "Reporta un problema" (es nuevo) que aparece hasta abajo en la página una vez que falle? luego copia toda la sección de "Tu ambiente" que trae información útil para debugguear.

**Comment by darkmx** [comment]
Lo pego acá :) 

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
* Link al sitio en el que este problema pasa: https://omegaup.com/contest/AED-2019I-D/edit/
* Errores en la consola: [{"status":"error","error":"Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.","errorname":"generalError","errorcode":400,"header":"HTTP/1.1 400 BAD REQUEST","_id":"5c46b18b9f0f2263909345","stack":"sendError@https://omegaup.com/js/error_handler.js?ver=5dd116:11:21
jQuery.Deferred.exceptionHook@https://omegaup.com/js/jquery_error_handler.js?ver=0c8c02:4:3
g/</k<@https://omegaup.com/third_party/js/jquery-3.2.1.min.js?ver=40733f:3:30352
"},{"status":"error","error":"Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.","errorname":"generalError","errorcode":400,"header":"HTTP/1.1 400 BAD REQUEST","_id":"5c46b18b9f0f2263909345","stack":"sendError@https://omegaup.com/js/error_handler.js?ver=5dd116:11:21
jQuery.Deferred.exceptionHook@https://omegaup.com/js/jquery_error_handler.js?ver=0c8c02:4:3
g/</k<@https://omegaup.com/third_party/js/jquery-3.2.1.min.js?ver=40733f:3:30352
"}]

**Comment by lhchavez** [comment]
Aquí está el error de la base de datos (hurra por los IDs de correlación!)

```
019-01-22T06:00:43+00:00 [ERROR]: 5c46b18b9f0f2263909345 /api/contest/update/ ADODB_Exception: mysqli error: [1054: Unknown column 'i.identity_id' in 'on clause'] in adodb_throw(UPDATE
                        `Runs` r
                    INNER JOIN
                        `Problemset_Problem_Opened` ppo
                        ON (ppo.problemset_id = r.problemset_id
                            AND r.problem_id = ppo.problem_id)
                    INNER JOIN
                        `Identities`
                        ON (i.identity_id = ppo.identity_id AND r.identity_id = i.identity_id)
                    INNER JOIN `Contests` c ON (c.problemset_id = r.problemset_id)
                    SET
                        r.penalty = ROUND(TIME_TO_SEC(TIMEDIFF(r.time, ppo.open_time))/60)
                    WHERE
                        r.problemset_id = '9683';, ) in /opt/omegaup/frontend/server/libs/third_party/adodb/adodb-exceptions.inc.php:80
Stack trace:
#0 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(311): adodb_throw('mysqli', 'adodb_throw', 1054, 'Unknown column ...', 'UPDATE\n        ...', false, Object(ADODB_mysqli))
#1 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1282): ADODB_TransMonitor('mysqli', 'adodb_throw', 1054, 'Unknown column ...', 'UPDATE\n        ...', false, Object(ADODB_mysqli))
#2 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1222): ADOConnection->_Execute('UPDATE\n        ...')
#3 /opt/omegaup/frontend/server/libs/dao/Runs.dao.php(887): ADOConnection->Execute('UPDATE\n        ...', Array)
#4 /opt/omegaup/frontend/server/controllers/ContestController.php(2339): RunsDAO::recalculatePenaltyForContest(Object(Contests))
#5 /opt/omegaup/frontend/server/controllers/ContestController.php(2261): ContestController::updateContest(Object(Contests), Object(Contests), '2083')
#6 /opt/omegaup/frontend/server/libs/Request.php(77): ContestController::apiUpdate(Object(Request))
#7 /opt/omegaup/frontend/www/api/ApiCaller.php(31): Request->execute()
#8 /opt/omegaup/frontend/www/api/ApiCaller.php(83): ApiCaller::call(Object(Request))
#9 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()
#10 {main}

Next InvalidDatabaseOperationException: generalError in /opt/omegaup/frontend/server/controllers/ContestController.php:2298
Stack trace:
#0 /opt/omegaup/frontend/server/libs/Request.php(77): ContestController::apiUpdate(Object(Request))
#1 /opt/omegaup/frontend/www/api/ApiCaller.php(31): Request->execute()
#2 /opt/omegaup/frontend/www/api/ApiCaller.php(83): ApiCaller::call(Object(Request))
#3 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()
#4 {main} (/opt/omegaup/frontend/www/api/ApiCaller.php:36) 
```
