### ISSUE TITLE
Des-descalificar un envío

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2332]
Hola amigos de OmegaUp.

Acabo de ver que agregaron un botón para descalificar un envío, pero me di cuenta a la mala. Quería picarle a la lupita para ver el código y al estar acostumbrado a la posición del botón, terminé dándole al de descalificar.  Desafortunadamente, no encontré una manera de deshacer mi error (al volverle a picar aparece "rejudging" pero al recargar la página sigue apareciendo descalificado y otras cosas raras como 900%). El envío es el 0b3bbe33 del concurso AED-2019I-D.

![imagen](https://user-images.githubusercontent.com/19719969/51548580-37806100-1e2e-11e9-9c54-a3a9ce2a8b0d.png)

Saludos!!

**Comment by yoniihdc** [comment]
Duplicado de #2119

**Comment by darkmx** [comment]
Enterado, cierro el issue (el 2119 sigue abierto).
