### ISSUE TITLE
Error interno al intentar volver un problema público

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2336]
Hola amigos de OmegaUp.

Estaba intentando volver un problema público desde el panel de edición del mismo (en concreto, desde https://omegaup.com/problem/Ignorando-los-ultimos-elementos/edit/) pero al enviar la consulta y recargar la página, se muestra un mensaje de error interno.

![imagen](https://user-images.githubusercontent.com/19719969/51579682-7e4e7500-1e87-11e9-9edc-8ccdff3a5245.png)

La consulta parece enviarse correctamente y no hay datos útiles en la información de depuración del ambiente (* Errores en la consola: [], creo que es de esperarse porque la página recarga). Al parecer el error también aparece si actualizar otras cosas del problema (por ejemplo, tiempo límite). 

Por mera curiosidad, intenté volverlo público desde mi lista de problemas (marcando su checkbox y luego ejecutando la opción de "volver público") y sí funcionó.

**Comment by darkmx** [comment]
gracias!

**Comment by darkmx** [comment]
Hola de nuevo, una pregunta D: 

¿El fix ya está online? Aún me aparece el mensaje rojito cuando intento hacer alguna modificación (por ejemplo en https://omegaup.com/problem/Subsecuencia-comun-mas-larga-con/edit/ al aumentar el tiempo de 2000 a 2500ms por caso).
![imagen](https://user-images.githubusercontent.com/19719969/52026554-e1668a00-24cd-11e9-8299-1fe29e9e57b1.png)

Lei la descripción del pull #2347 y verifiqué que si adjunto el zip entonces la actualización sí se correctamente en la plataforma, tal como está disponible para nosotros en este momento.

**Comment by lhchavez** [comment]
no, hacemos deploy cada domingo en la noche, así que el lunes siguiente ya va a estar online el fix :D

esperamos que en algún punto del año estemos listos para dar el brinco a hacer deployments diarios.

**Comment by darkmx** [comment]
vale muchas gracias :)
