### ISSUE TITLE
MLE (> 0.1MB) cuando el límite es 128MB

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2337]
Hola amigos de OmegaUp.

Estaba intentando resolver este problema https://omegaup.com/arena/problem/ptwo#problems pero me marca MLE por haber superado 0.1MB aunque el límite es 128MB. Incluso este código falla:

```
#include <cstdio>                    // por si fuera culpa de iostream

int main( ) {
   int n;
   std::scanf("%d", &n);

   const char* res[265 + 1] = { "1", "2", "4", ... }; // todas las respuestas precalculadas, ocupa 12KB
   if (0 <= n && n <= 265) {         // por si fuera un EE mal diagnosticado
      std::printf("%s\n", res[n]);
   }
}
```

Los envíos son los f86d1994, 85744057 y 0bcb7b47. Hice envíos y rejueceos en otros problemas y no hubo errores.
![imagen](https://user-images.githubusercontent.com/19719969/51646558-a9e06680-1f3e-11e9-937e-0d0d76adcb35.png)

**Comment by lhchavez** [comment]
Esto únicamente afectó a los siguientes problemas:

abba
Arte-Abstracto
Contando-Primos
Contando-Primos-Reloaded
El-desorden-de-Karla
El-desorden-de-Karla-reloaded
El-ingrediente-faltante
Experimento-de-exploracion
Firulais-y-El-Arbol
GCD
Javert-y-sus-Outfits
K-Midiendo-gusanos
KTANEI
Kunas
Los-dilemas-de-Karel-2
L-PE-P15-Cuantos-caminos
L-PE-P28-Numeros-diagonales
Merge-Sort
MrKrista-vs-Teoria-de-Numeros
Numeros-Gordos
OMIS2015K2
Parkour
ParteYReparte
Poli-Triangulos
pruebita
ptwo
Sobras
Solving-the-equation
Strange-queries
Suma-Que-Suma
Sumas-de-Jardin
Tarea-aburrida
Ternas
UAS_PCI-Merge-Sort
UAS_PCI-Quicksort

todos los envíos afectados han sido reevaluados.

**Comment by darkmx** [comment]
gracias :)
