### ISSUE TITLE
ranking usuarios

### ISSUE THREAD

**Issue by Delciuxs** [omegaup/omegaup#2339]
## Comportamiento Esperado

Cambiara a la pagina siguiente al dar clic en el enlace

## Comportamiento Actual

En ves de sumar concatena (lo hace como strings): si estás en la página 1, la siguiente página es la 11, no la 2.

## Posible Solución

sumar en vez de concatenar.

## Pasos para reproducir (para bugs)

1. Navegar a https://omegaup.com/rank?page=11
2. Observar que el enlace "Página anterior" lleva a https://omegaup.com/rank?page=10 (correcto)
3. Observer que el enlace "Página siguiente" lleva a https://omegaup.com/rank?page=111 (incorrecto)

**Comment by lhchavez** [comment]
Parece que https://github.com/omegaup/omegaup/blob/ccf4ff2e91248a600bb58532dd9309d831b77c34/frontend/www/rank.php#L24 necesita un cast a entero, porque el payload tiene el tipo incorrecto:

```html
<script type="text/json" id="payload">{"page":"11","length":100,"is_index":false,"availableFilters":{"country":"Filtrar por pa\u00eds","state":"Filtrar por estado","school":"Filtrar por escuela"},"filter":""}</script>
```

**Comment by lhchavez** [comment]
Assigned to @prondubuisi until March 3rd.

**Comment by lhchavez** [comment]
Err, I meant to say February 3rd. Extending to February 10th, will remove assigned label then.
