### ISSUE TITLE
No se pueden descargar los archivos de un problema

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2340]
Hola amigos de OmegaUp.

Se está generando un error al querer descargar el zip con los archivos de un problema. Esto ocurre tanto para problemas viejos como recientes. Por ejemplo:

https://omegaup.com/api/problem/download/problem_alias/sdc/
  devuelve
{"status":"error","error":"Problema no encontrado","errorname":"problemNotFound","errorcode":404,"header":"HTTP\/1.1 404 NOT FOUND","_id":"5c4b3e9cd5ea0146328833"}

https://omegaup.com/api/problem/download/problem_alias/Incrementando-intervalos/
  devuelve
{"status":"error","error":"Problema no encontrado","errorname":"problemNotFound","errorcode":404,"header":"HTTP\/1.1 404 NOT FOUND","_id":"5c4b3e3b8778b602571871"}

**Comment by kukogit** [comment]
+1

**Comment by kukogit** [comment]
Esto también está provocando que al evaluar algunos problemas, está dando MLE. Incluso si evaluo de nuevo una solución que ya tenía AC, me da MLE. 

![image](https://user-images.githubusercontent.com/6465292/51795033-2bd0c980-21a3-11e9-8ca4-0530c010dc36.png)

Y después de evaluar:

![image](https://user-images.githubusercontent.com/6465292/51795038-44d97a80-21a3-11e9-9da4-97bbe127dcb5.png)

**Comment by lhchavez** [comment]
eso no está relacionado con la falla de descargar problemas. puedes abrir otro issue para evitar contaminación de este porfa?
