### ISSUE TITLE
Search bar in rankings to search for a specific User.

### ISSUE THREAD

**Issue by akki111singh** [omegaup/omegaup#2344]
![screenshot_2019-01-28-01-41-33-808_com android chrome](https://user-images.githubusercontent.com/45921807/51806309-8569ee80-229e-11e9-8379-765ff5d42a0a.png)
https://omegaup.com/rank/
We can add a search bar on the top right corner so that it will be easy for the user to search his/her name in the list.

**Comment by ss62171** [comment]
can you please elaborate on this??

**Comment by akki111singh** [comment]
@ss62171 currently there is no search bar for a user to search his name in the rank list in page https://omegaup.com/rank/ (can't able to attach image,don't know why ?) so we can implement this.

**Comment by lhchavez** [comment]
adding a way to search for a user in the ranking list sounds reasonable. but yes, please amend the original comment so that it better explains the problem at hand. a screenshot might not be enough since it's not easy to notice something that's missing.

**Comment by lhchavez** [comment]
sure thing! oh and also, it's possible to view your own rank by going to your profile. granted it might not be the most discoverable way, but it's a workaround.
