### ISSUE TITLE
[Problem Finder] Permitir que apiList() soporte los nuevos criterios de búsqueda

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2349]
La API debe poder soportar los nuevos criterios de búsqueda:
- Tópicos
- Rango de dificultad
- Ordenar en base a: calidad, puntos para ranking o popularidad del problema

## Contexto

Como parte de la implementación del [Problem Finder Wizard](https://docs.google.com/document/d/1JR29kbVpVSAeMk6P_hKi6RkJ67c4mqYPkEaJ-zNkgXU/edit#)

Link al project tracker: https://docs.google.com/spreadsheets/d/1ZbqSShs3sa-3nBq3W6SXppy05lXCf78U1XByzceS4c0/

**Comment by SpaceWhite** [comment]
+1 for this feature :+1:
