### ISSUE TITLE
Error interno al acceder al código de envíos viejos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2350]
Hola amigos de OmegaUp.

Se está produciendo un error al ver el código de envíos viejos en al menos dos problemas: https://omegaup.com/arena/problem/Transiciones-en-cadenas-binarias y https://omegaup.com/arena/problem/Automatas-celulares. La respuesta del servidor al hacer la petición es 

`{"status":"error","error":"Oops. Ocurri\u00f3 un error interno. Por favor int\u00e9ntalo nuevamente.","errorname":"generalError","errorcode":500,"header":"HTTP\/1.1 500 INTERNAL SERVER ERROR","_id":"5c510a5750404535749857"}`

Ahorita hice envíos de prueba (mains que no hacen nada) y ésos, al ser recientes, sí los puedo ver.

**Comment by darknut** [comment]
También me pasa, me metí justo a crear este issue.

**Comment by kukogit** [comment]
Por qué está cerrado, si aún no funciona?

**Comment by lhchavez** [comment]
ya se arregló, pero faltan un par de horas para que se haga el deployment.
