### ISSUE TITLE
Ver mis codigos enviados

### ISSUE THREAD

**Issue by ulises-garcia** [omegaup/omegaup#2359]
## Comportamiento Esperado
Esperaba que me dejara ver mis codigos en mis envios

## Comportamiento Actual
No deja ver los envios

**Comment by lhchavez** [comment]
dupe de https://github.com/omegaup/omegaup/issues/2350

**Comment by ulises-garcia** [comment]
Al ver mis envíos en un problema tengo la opción con una lupa de "Ver Más",
la cual te mostraba el código que habías enviado del problema en cuestión,
pero ahora no te deja ver ese código y dice que algo Inesperado había
ocurrido, que lo intente más tarde.
