### ISSUE TITLE
no me cargan los envios antiguos

### ISSUE THREAD

**Issue by Ffelixpe** [omegaup/omegaup#2360]
## Comportamiento Esperado

estaba esperando acceder a un antiguo problema que subí en la plataforma

## Comportamiento Actual

actualmente en la plataforma no te permite acceder o ver al problema enviado previamente

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

1. entra a cualquier problema que hayas resuelto hace tiempo(mínimo 1 mes)
2. entra a la seccion de envios
3. presionar al boton de vista del programa
4. veras que no carga

## Contexto

intento ver logica de programacion de problemas que habia subido para acordarme de como le habia hecho pero no puedo acceder a el

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

estaba intentando checar un problema y no me cargaba

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.7.3029.81 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Errores en la consola: []
* Captura de pantalla:

**Comment by kukogit** [comment]
Agregando un poco... aparece esa leyenda en la parte superior!!!

![image](https://user-images.githubusercontent.com/6465292/52188493-bdba8100-27f8-11e9-9377-2df6a9c7da12.png)

**Comment by lhchavez** [comment]
dupe de https://github.com/omegaup/omegaup/issues/2350
