### ISSUE TITLE
Código con AC de hace 2 años ya no da

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2362]
Envío 726b737e de 2017 y c38fd24e de 2019 son el mismo código. El primero dio AC pero el segundo da una combinación entre RTE y LTE

Problema en cuestión:
IOI 2013 - Cueva

**Comment by lhchavez** [comment]
Posiblemente sea culpa de Spectre/Meltdown :'( Eso hizo que mágicamente todas las computadoras del mundo fueran mediblemente más lentas.

**Comment by kukogit** [comment]
Suena a que es el problema de Juego de la IOI... es ese?

**Comment by tvanessa** [comment]
Duplicado de #1884
