### ISSUE TITLE
no puedo registrarme

### ISSUE THREAD

**Issue by alfredoanu** [omegaup/omegaup#2369]
## Comportamiento Esperado

*Describe lo que esperabas que pasara*

## Comportamiento Actual

*Describe lo que pasó en lugar de lo que se esperaba*

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Errores en la consola: []
* Captura de pantalla:

**Comment by lhchavez** [comment]
dupe de https://github.com/omegaup/omegaup/issues/2377
