### ISSUE TITLE
[BUG] Algunos problemas muestran caracteres no-ASCII incorrectamente

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2381]
Hola amigos de OmegaUp. 

Hace unos meses noté que **_algunos_** problemas (los cuales originalmente estaban bien y no habían sido actualizados desde hace mucho) estaban mostrando incorrectamente los acentos (Ã³ en lugar de ó, por ejemplo). Cuando me di cuenta, arreglé los que vi (no recuerdo cómo lo hice, creo que subiendo de nuevo el archivo pero no me hagan mucho caso con eso) pero desde el editor no puedo corregir éste https://omegaup.com/arena/problem/Puntos-colineales/#problems y prefiero pasarles el reporte antes de que se me olvide.

El markdown que está en el código fuente trae lo siguiente, lo cual está mal.

------
![imagen](https://user-images.githubusercontent.com/19719969/53197582-1dc66b00-35e0-11e9-8a59-766735a5f6b1.png)

y se dibuja así (también aparece mal en el formulario al momento de editar):

------
![imagen](https://user-images.githubusercontent.com/19719969/53198397-ec4e9f00-35e1-11e9-805b-b54fdd3909b4.png)

La petición que se envía al intentar corregirlo se ve bien.

![imagen](https://user-images.githubusercontent.com/19719969/53197755-6ed65f00-35e0-11e9-8792-4611ceb6cd29.png)

Esto ocurre únicamente para algunos problemas y se da tanto en Firefox como en Chrome (Windows)

**Comment by tvanessa** [comment]
El problema es que modificaste algunos problemas para que se mostraran bien los caracteres, pero en el de _puntos colineales_ no puedo arreglarse aunque lo cambiaste?

**Comment by rccuam** [comment]
Exacto. Aún intentando borrarlos, guardar y luego reescribirlos y guardar, vuelven a aparecer mal.

![imagen](https://user-images.githubusercontent.com/3603833/69540981-aa2a0380-0f4d-11ea-99eb-cd5f30e1498d.png)

**Comment by rccuam** [comment]
Hola de nuevo, hice una prueba (con otro problema).

Parece que si vuelvo a subir el archivo (con codificación occidental Windows-1252 en lugar de UTF-8) entonces se arregla, pero parece que no se puede arreglar directo desde el editor. Durante la prueba hice lo siguiente: agarré el markdown del problema con el error, lo corregí y edité en mi PC (pero sin cambiar la codificación) y luego lo subí en otro problema, pero presentó el mismo error; luego convertí la codificación de UTF-8 a Windows-1252 en mi PC, volví a subir el archivo y ya se arregló.

**Comment by darkmx** [comment]
cuando reporté @3560 no me acordaba que ya había publicado éste, así que cierro el viejo.
