### ISSUE TITLE
No esta funcionando bien OmegaUp

### ISSUE THREAD

**Issue by alanggalgh** [omegaup/omegaup#2386]
Durante la sesión en OmegaUp utilizando el navegador Google Chrome , en ocasiones se queda congelado (no responde ni acepta envíos de códigos). Y en ocasiones la pantalla se pone en blanco y muestra el error 504. Hemos tenido que cerrar completamente el navegador, porque no acepta ni siquiera el refresh.

**Comment by alanggalgh** [comment]
Durante la sesión en OmegaUp utilizando el navegador Google Chrome , en ocasiones se queda congelado (no responde ni acepta envíos de códigos). Y en ocasiones la pantalla se pone en blanco y muestra el error 504. Hemos tenido que cerrar completamente el navegador, porque no acepta ni siquiera el refresh.

**Comment by lhchavez** [comment]
intenté hacerle unos cuantos ajustes a la memoria del servidor. según ya debe estar arreglado.

**Comment by lhchavez** [comment]
hice unos cuantos ajustes más hoy y ya se ve más saludable.

**Comment by alanggalgh** [comment]
Muchas gracias.

Hoy aplicamos examen y solamente se pasmó algunas veces. Gracias nuevamente por el apoyo.

Atentamente.

Ing. Hector Alan Gonzalez Galindo,
Jefe del Depto. de Capacitación en Tecnologías de Información de la
Dirección Gral. de Tecnologías de la Información
(antes Dirección Gral. de Informática),
SEP - Hidalgo,
Delegado de la OMI para el Estado de Hidalgo e
Instructor del Lenguaje C.

e-mail: alanggal@hotmail.com<mailto:alanggal@hotmail.com>,
          alanggal@yahoo.com<mailto:alanggal@yahoo.com>



________________________________
De: lhchavez <notifications@github.com>
Enviado: jueves, 7 de marzo de 2019 08:23 p. m.
Para: omegaup/omegaup
CC: Alan Gonzalez Galindo; Author
Asunto: Re: [omegaup/omegaup] No esta funcionando bien OmegaUp (#2386)


hice unos cuantos ajustes más hoy y ya se ve más saludable.
