### ISSUE TITLE
Durante la sesión en OmegaUp utilizando el navegador Google Chrome , en ocasiones se queda congelado (no responde ni acepta envíos de códigos). Y en ocasiones la pantalla se pone en blanco y muestra el error 504. Hemos tenido que cerrar completamente el navegador, porque no acepta ni siquiera el refresh.

### ISSUE THREAD

**Issue by alanggalgh** [omegaup/omegaup#2387]
Durante la sesión en OmegaUp utilizando el navegador Google Chrome , en ocasiones se queda congelado (no responde ni acepta envíos de códigos). Y en ocasiones la pantalla se pone en blanco y muestra el error 504. Hemos tenido que cerrar completamente el navegador, porque no acepta ni siquiera el refresh.

_Originally posted by @alanggalgh in https://github.com/omegaup/omegaup/issues/2386#issuecomment-470259206_

**Comment by lhchavez** [comment]
Duplicado de https://github.com/omegaup/omegaup/issues/2386
