### ISSUE TITLE
Como soporte omegaUp quiero la funcionalidad de re-Habilitar usuarios viejos para volver otorgarles acceso a la plataforma.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2392]
## Comportamiento Esperado

Poder habilitar usuarios que se dieron de baja por "tiempo de vida máximo" dentro de la plataforma.

## Comportamiento Actual

Solo se puede generar contraseñas, pero no se puede re-habilitar un usuario.

## Pasos para reproducir (para bugs)

1. Ingresar a cuenta de omegaUp
2. Ingresar al Admin panel
3. Escribir el correo que deseas buscar
4. Dar click en generar token.

## Contexto

Actualmente hemos recibido una oleada de usuarios que su cuenta a sido dada de baja debido a que se le considera "vieja", lo cual afecta al número de usuarios activos de omegaUp.

Necesitamos una herramienta para poder habilitar nuevamente a estos usuarios.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Safari STD
* Sistema Operativo y versión (escritorio o móbil): macOS 10.14.3 (18D42)
* Link al sitio en el que este problema pasa:https://omegaup.com/admin/support
* Captura de pantalla:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5459260/53979309-11a7d680-40d3-11e9-8c1b-1021c9a4b83d.png">

**Comment by pabo99** [comment]
De hecho, si puedes re-habilitar las cuentas que ya son muy viejas. Lo que tienes que hacer es lo siguiente:

Si un usuario te reporta que tiene el siguiente mensaje de error:
![Captura de Pantalla 2019-06-06 a la(s) 16 39 35](https://user-images.githubusercontent.com/3230352/59068430-c213ab00-8879-11e9-93a7-fb8d1c9348b4.png)

En ese punto, el usuario puede no hacer la petición de recuperar, debido a que no ha verificado su correo, si fuera el caso.
![Captura de Pantalla 2019-06-06 a la(s) 16 42 51](https://user-images.githubusercontent.com/3230352/59068656-53831d00-887a-11e9-91f1-b5f90a408366.png)

Puedes ir al link que proporcionaste: https://omegaup.com/admin/support con tu cuenta de soporte
Una vez ahí, colocas el correo del usuario que te reportó. Si no ha verificado su correo, lo puedes verificar
![Captura de Pantalla 2019-06-06 a la(s) 16 46 12](https://user-images.githubusercontent.com/3230352/59068771-b2e12d00-887a-11e9-8d2e-b3ce699dede0.png)
![Captura de Pantalla 2019-06-06 a la(s) 16 46 26](https://user-images.githubusercontent.com/3230352/59068774-b4aaf080-887a-11e9-8b13-7f5ac222a00f.png)

En ese punto no puedes generar el token de recuperación debido a que no te ha solicitado la recuperación de su contraseña:
![Captura de Pantalla 2019-06-06 a la(s) 16 46 42](https://user-images.githubusercontent.com/3230352/59068849-fb98e600-887a-11e9-8cf2-0d331bb498f6.png)

Lo que resta por hacer es el proceso normal de recuperación de contraseña, le tendrás que notificar al usuario que lo tiene que hacer para que se le pueda generar el token, y así pueda ingresar su nueva contraseña.

Si tienes un caso que no estemos considerando, reabrimos el issue.
