### ISSUE TITLE
En Safari, el campo del nombre de la escuela se des-selecciona

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2393]
## Comportamiento Esperado

Vincular una escuela con un curso.

## Comportamiento Actual

Estaba creando un curso nuevo en omegaUp Escuelas y en el momento de seleccionar o colocar una escuela me fue imposible seleccionar el textbox.
Es imposible colocar el nombre de una escuela.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Ingresar a una cuenta de omegaUp
2. Crear un nuevo curso
3. Cambiar el nombre de la escuela
## Contexto

Yo como profesor no puedo crear cursos con una escuela indicada, debido a que no me es posible intercambiarlos.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Safari sdt
* Sistema Operativo y versión (escritorio o móbil): MacOs Darwin
* Link al sitio en el que este problema pasa: https://omegaup.com/course/new/
* Captura de pantalla:
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/5459260/53993357-cb636f00-40f4-11e9-8c37-6533e92b0f00.png">

**Comment by joemmanuel** [comment]
No repro, en mi dev env pude crear un concurso nuevo con una escuela arbitraria y también editar la escuela. Hice hard refresh para asegurarme de que la escuela se guardó correctamente.

**Comment by joemmanuel** [comment]
Hablé con Miguel offline, sí hay repro en Safari lol, qué hacemos en ese caso?

![2019-04-26 15 59 13](https://user-images.githubusercontent.com/207097/56840464-88905e80-683c-11e9-9e8a-066c6b02a941.gif)

**Comment by lhchavez** [comment]
welp, alguien con Safari necesita ayudar.

**Comment by joemmanuel** [comment]
Ok, según el readme no soportamos Safari. Fair enough.
