### ISSUE TITLE
Yo como usuario necesito ingresar a las plataforma pero me es denegado por ser "usuario antiguo"

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2397]
## Comportamiento Esperado

Necesito ingresar a omegaUp.com para poder usar la plataforma.

## Comportamiento Actual

Muestra un mensaje mostrando, usuario deshabitado debido a antigüedad.

## Pasos para reproducir (para bugs)

1. Ingresar a omegaUp.com
2. Colocar tus datos de ingreso
3. Tratar de ingresa

## Contexto

Muchos usuarios no pueden ingresar a la plataforma debido a que sus usuarios son tomados como antiguos.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Varios
* Sistema Operativo y versión (escritorio o móbil): MacOs Darwin
* Link al sitio en el que este problema pasa: https://omegaup.com/login

**Comment by MiguelRomero** [comment]
@lhchavez Este se replica demasiado también

**Comment by lhchavez** [comment]
Arreglado en https://github.com/omegaup/omegaup/commit/f3098a3fe98df3cd5458319d0b65715bad5a647e . estábamos desplegando un mensaje erróneo.
