### ISSUE TITLE
[Analytics] Reportar eventos cuando se llena una forma de calidad

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2404]
Como un administrador del sitio me gustaria saber el click-through rate del formato de calidad

## Comportamiento Esperado
Deberiamos poder rastrear cuantas veces los usuarios nos dan feedback dado que les preguntamos.

## Comportamiento Actual
Ahorita tenemos cuantificar cuantos usuarios nos dieron feedback, pero no podemos cuantificar cuantos nos podrian haber dado y no lo hicieron.

## Posible Solución
Utilizando GA/events:
https://developers.google.com/analytics/devguides/collection/analyticsjs/events
`ga('send', 'event', 'quality', 'view', 'feedbackForm', '$A_B_Variant')`
y
`ga('send', 'event', 'quality', 'submit', 'feedbackForm', '$A_B_Variant') `
cuando nos contesten.
`$A_B_Variant` es para cuando empecemos a hacer A/B testing con diferentes formulaciones de las pregunta.

**Comment by heduenas** [comment]
Hace como 6 meses lo estimamos con la tasa de (numero total de ACs) / (numero total de formas de calidad registradas) y salio de ~5%.
