### ISSUE TITLE
Yo como usuario quiero ingresar a la plataforma omegaUp pero no me es permitido por no verificar.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2407]
## Comportamiento Esperado

Yo como usuario de la plataforma necesito ingresar a omegaUp con mi cuenta verificada.
## Comportamiento Actual

Actualmente me dice que mi usuario no esta verificado, no recibo correo de verificación y el soporte de usuario de omegaUp ya verifico con su panel de administrador mi usuario.

## Contexto

No puedo ingresar a mi cuenta de omegaUp por que mi usuario no esta verificado, no recibo correos de verificación y soporte omegaUp no puede verificar mi usuario.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome LTS
* Sistema Operativo y versión (escritorio o móbil): Windows 10

**Comment by MiguelRomero** [comment]
@lhchavez

**Comment by MiguelRomero** [comment]
![Captura](https://user-images.githubusercontent.com/5459260/54696852-326c2500-4af2-11e9-92ce-420aa642751b.PNG)
![captura3](https://user-images.githubusercontent.com/5459260/54696860-35671580-4af2-11e9-9c33-839ee283471f.PNG)

A pesar de verificarlos de manera manual no tienen acceso.  @lhchavez

**Comment by lhchavez** [comment]
hmm parece que esto no está ocurriendo: el primer usuario nunca intentó iniciar sesión y el segundo usuario tengo un log indicando que pudo entrar exitosamente después de haberlo verificado.

voy a agregar más logging para el futuro y exponer la última vez que hicieron login para que no te anden mintiendo. como parece que el problema no existe en realidad, lo voy a cerrar. reabre el bug si encuentras otro ejemplo.

**Comment by MiguelRomero** [comment]
![image](https://user-images.githubusercontent.com/5459260/54773543-6d905600-4bcf-11e9-8df0-8d6c377ce872.png)
 

Hoy en la mañana ya estaba verificado

**Comment by MiguelRomero** [comment]
@lhchavez 
Voy a tener una videollamada con un delegado para ver si efectivamente sus usuarios presentan ese caso.

**Comment by lhchavez** [comment]
casi 100% seguro que no

**Comment by MiguelRomero** [comment]
Martes a las 12 cst no quieres entrar a la llamada?

**Comment by lhchavez** [comment]
no voy a poder
