### ISSUE TITLE
Como usuario, quiero que el autocompletar de la búsqueda me lleve directamente a un problema para ahorrar tiempo

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#2408]
## Comportamiento Esperado

En https://omegaup.com/problem/ busco un problema y me aparece en las sugerencias. Darle clic me lleva directamente al problema.

## Comportamiento Actual

Al darle clic a la sugerencia, autocompleta el id (el que aparece en el URL) del problema en la barra de búsqueda. Después le tengo que dar "Buscar", y finalmente tengo que darle clic al problema.

## Posible Solución

Redirección usando JavaScript

**Comment by pabo99** [comment]
La solución puede quedar de la siguiente forma: 

![2408](https://user-images.githubusercontent.com/3230352/56868415-c82f8580-69b7-11e9-9fde-41398696f615.gif)
