### ISSUE TITLE
blog.omegaup.com no funciona

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#2409]
## Comportamiento Esperado

Al entrar a cualquier página en https://blog.omegaup.com/, debería cargar

## Comportamiento Actual

Aparece
> 502 Bad Gateway
> nginx/1.15.9

## Pasos para reproducir (para bugs)

Entrar a https://blog.omegaup.com/ o hacer clic en "Blog" en omegaup.com

**Comment by gabrc52** [comment]
Se podría redirigir temporalmente a http://web.archive.org/web/2019/https://blog.omegaup.com/

**Comment by lhchavez** [comment]
welp, gracias por reportar esto. ya fue arreglado!
