### ISSUE TITLE
Considerar el uso de KaTeX en vez de MathJax

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2412]
Parece que KaTeX es más rápido que MathJax: https://katex.org/

**Comment by pabloaguilar** [comment]
Dice https://www.intmath.com/cg5/katex-mathjax-comparison.php que no hay mucha diferencia entre KaTeX y MathJax v3 (que es lo que usamos ahora) aunque en su momento sí había mucha diferencia vs. MathJax v2.7
