### ISSUE TITLE
"you need to log in to perform that operation" cuando se abre la lista de problemas

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#2452]
Los mas probable es que haya sido introducido con el problem finder. Algun API esta intentando validar autenticacion aunque no es necesaria.

Carlos ya esta investigando mas.

**Comment by carlosabcs** [comment]
Me parece que es justo [aquí](https://github.com/omegaup/omegaup/blob/master/frontend/server/controllers/TagController.php#L23) el problema. @lhchavez es necesaria esa autenticación o puedo quitarla?

**Comment by lhchavez** [comment]
no veo problema con quitarla.
