### ISSUE TITLE
Imposible seleccionar el textbox de "Escuela" cuando esta creando un nuevo curso

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#2460]
Cuando tratas de seleccionar el textbox de escuela para seleccionar la escuela de procedencia se deselecciona automaticamente, por consiguiente es imposible escoger una escuela.

## Comportamiento Esperado

Seleccionar la escuela de procedencia de manera correcta.

## Comportamiento Actual

Imposible seleccionarlo para escribir la escuela de procedencia.

## Pasos para reproducir (para bugs)

1. Crear un nuevo curso
2. Tratar de dar click en el textbox de escuela

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Safari (Last Version)
* Sistema Operativo y versión (escritorio o móbil): MacOs Darwin

**Comment by lhchavez** [comment]
Dupe de #2393 . Y a mí no me ocurre O_o. puedes intentar con Chrome y con Firefox?
