### ISSUE TITLE
Subir problemas no funciona

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#2476]
## Contexto

Germán me comunicó que se ha enfrentado a este issue al subir problemas. Creando el issue en su representación.

![omegaup](https://user-images.githubusercontent.com/684205/57045610-f9f85480-6c22-11e9-8d76-1a1202c8487a.png)

## Comportamiento Esperado

El feature "Subir problema" funciona correctamente y no se muestran mensajes de error.

## Comportamiento Actual

Un mensaje de error se muestra con:
"Hubo al menos un archivo .in sin su .out correspondiente..."

**Comment by lhchavez** [comment]
pueden intentar poner los .in y los .out en la misma carpeta por lo pronto?

**Comment by rcxr** [comment]
Se confirmó que faltaba un folder en el zip, y que por lo tanto el mensaje de error era esperado.
