### ISSUE TITLE
No muestra el score correctamente en una practica de Escuela

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2481]
## Comportamiento Esperado

Mostrar score como lo hace en las demás prácticas.

## Comportamiento Actual

En la práctica https://omegaup.com/course/ORIGROMI19/assignment/ORIGROMI19EP/#ranking no se muestra el ranking.

## Pasos para reproducir (para bugs)

1.  Entrar al link dado
2. Ir a la pestaña de ranking

## Tu ambiente

* Chrome
* W10
* https://omegaup.com/course/ORIGROMI19/assignment/ORIGROMI19EP/#ranking
* Captura de pantalla:

![image](https://user-images.githubusercontent.com/6465292/57181356-2a750400-6e58-11e9-9677-ab0c54108a84.png)

**Comment by kukogit** [comment]
No entendí, se arregló o no? Sigue sin mostrar el score...

Saludos.

**Comment by lhchavez** [comment]
se arregló, pero como desde hace más de un año, los deployments se hacen los domingos en la noche, así que para mañana ya debe estar visible en la página.

**Comment by kukogit** [comment]
Got it!!!
