### ISSUE TITLE
Como ENTRENADOR quiero poder borrar problemas de un concurso/tarea que ya tiene envíos de participantes

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2488]
## Comportamiento Esperado

Poder borrar problemas de una tarea, examen o concurso una vez que al menos un participante haya hecho un envío.

## Comportamiento Actual

No lo permite, antes era posible.

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

Si por error agregas un problema que no querías y los alumnos lo resuelven o envían cualquier cosa,, ya no puedes eliminarlo y tiene que quedarse ahí.

No creo que afecte a nadie poder eliminar problemas, yo creo que más bien, se agrego esta forma de trabajar por practicidad para OmegaUp y no de los usuarios.

**Comment by kukogit** [comment]
También pasa que subes problemas de la OMI o de alguien más, y esos problemas están mal de alguna forma, y ya no los puedes quitar. Me pasó con el problema de Divisores (de Karel) de una OMI, que subió Joe y no funciona... así que mejor subir mi propio problema de Divisores, y ahí si funciona,.. pero ya no pude quitar el problema que está mal.

**Comment by lhchavez** [comment]
a los participantes que ya se tomaron el tiempo de resolver el problema sí les afecta :S. antes sí se podía y la gente se quejó y decidimos bloquearlo.

para problemas que están mal, por favor repórtalos en vez de subir copias.

**Comment by lhchavez** [comment]
aquí lo importante es que no importa qué decisión al respecto tomemos (permitir o prohibir eliminar problemas de un problemset), _alguien_ se va a quejar  entonces tomamos la decisión pragmática de causar la menor pérdida posible de trabajo (o información). si se permite borrar problemas, afectas el trabajo de O(n) personas mientras que permitirlo afecta a O(1). además si borras un problema, esos envíos ya no se podrían recuperar.

**Comment by kukogit** [comment]
En la forma en la que yo trabajo con mis alumnos, no les afecta si quito problemas porque yo llevo un registro ponderado de su trabajo, y a mi me sirve poner y quitar problemas...

La razón por la que empecé a usar el Modo Escuela es porque "me tuve" que cambiar de usar la parte de  concursos, porque antes la usaba para hacer prácticas también... pero luego, se les ocurrió la idea de no permitir borrar problemas de ahí... y pues bueno... decidí cambiarme a modo Escuela porque aquí si se podía...

Pero bueno, me han dejado sin opciones, así que buscaré, o lo haré yo mismo (aunque me tome mucho tiempo) otras opciones para trabajar que se ajusten a lo que necesito...

Bytes!!!

**Comment by lhchavez** [comment]
creo que lo más saludable es que discutamos tu caso de uso (offline), así que alguien del equipo te va a contactar. hasta ahora parece que _algo_ en escuelas estamos haciendo mal y eso te está orillando a hacer workarounds como andar agregando o quitando problemas de tareas.

nos interesa arreglar el problema de raíz en escuelas para que no haya duplicación de esfuerzos, porque eso no le beneficia a nadie.
