### ISSUE TITLE
OmegaUp pide verificar a un usuario ya verificado

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2490]
Hola amigos de OmegaUp.

Después de una huelga larguísima de 3 meses en mi universidad, finalmente regresamos a clases y algunos alumnos (que ya habían hecho tareas durante enero) han reportado que no pueden ingresar de nuevo a sus cuentas. El error que les aparece es el de que su email no ha sido verificado. Parece ser lo mismo que en https://github.com/omegaup/omegaup/issues/2407 

Confieso que no he visto el error personalmente (llevamos menos de una semana de reiniciar clases y no han pasado a verme a mi cubículo), pero uno de los alumnos mandó sus datos y ya verifiqué que tiene problemas resueltos. Su username es KevinMaldonado y su email es al2173002896@azc.uam.mx

Espero estar reportando un issue real; una disculpa en caso contrario.
Saludos!

**Comment by darkmx** [comment]
Hola de nuevo, otro usuario que aparentemente tiene el mismo problema es Glaas2.
Se hizo otra cuenta y no ha tenido problemas con ella, pero sigue sin poder acceder a la cuenta original (también la creó en enero).

**Comment by lhchavez** [comment]
tuvimos un bug a principios de año donde no estábamos ni enviando el correo de verificación ni validando que estuvieran verificados! así que nadie se dio cuenta :S

puedes pedirles que desde el correo que se dieron de alta envien el correo a la dirección que viene en el error? alguien les va a ayudar a verificar la cuenta manualmente.

**Comment by darkmx** [comment]
Enterado, muchas gracias! 
Yo les aviso.

**Comment by rccuam** [comment]
Hola de nuevo! sólo para actualizar la situación.

Mis alumnos (y al parecer mucha gente más) mandaron mensaje al correo que aparece en el mensaje de error. El correo se publica en automático en https://groups.google.com/forum/#!forum/omegaup-soporte, pero parece que nadie está atendiéndolos allá :(
