### ISSUE TITLE
No me permite crear problemas con validador personalizado, que antes si se podía

### ISSUE THREAD

**Issue by jofeque** [omegaup/omegaup#2497]
## Comportamiento Esperado

Al querer subir un problema nuevo con validador personalizado, como siempre lo he hecho, me manda un mensaje de: 'The problem's layout is not valid.: problem with unused validator'

Incluso, quiero subir de nuevo un problema (https://omegaup.com/arena/problem/caja_magica/) que antes si funcionaba la subida, me manda el mismo error  'The problem's layout is not valid.: problem with unused validator'

**Comment by lhchavez** [comment]
de pura casualidad tendrás más de un archivo que se llame `validator.*`? creo que tenemos que mejorar ese mensaje de error para facilitarles el encontrar el error más rápido.

**Comment by jofeque** [comment]
Solo hay un archivo en raíz llamado validator.cpp

**Comment by lhchavez** [comment]
oh ya. una pregunta, sí le estás poniendo que el validador es custom en la forma para subir el problema?

no estoy viendo que nadie haya intentado editar caja_magica recientemente, pero sí veo varios intentos hoy donde alguien (no estoy seguro si fuiste tú) está intentando subir un .zip con validador pero eligiendo "token por token" como validador en la forma.

**Comment by lhchavez** [comment]
ya hice un cambio para hacer el mensaje de error más claro. avísame si el error era que el validador que elegiste en la interfaz no era "custom" e intentabas subir el .zip con un validador custom.

**Comment by jofeque** [comment]
Tienes razón
Elegía Token by token no Custom validator
Gracias
