### ISSUE TITLE
Como usuario/creador de problema, quisiera poder usar el grader efímero para Karel

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#2507]
La API de grader efímero funciona con Karel, pero el UI no deja mandar nuevos envíos y hay cosas rotas porque no espera `kj` o `kp` como lenguajes válidos.

https://omegaup.com/grader/ephemeral/#3ed426ffeeab7b3b1884

![image](https://user-images.githubusercontent.com/468211/58060834-27506800-7b28-11e9-9d84-f081c7e3d83f.png)

## Comportamiento Esperado

Karel funciona en el grader efímero (con k_os de intérprete, sin el UI clásico de Karel).

## Comportamiento Actual

Se pueden consultar envíos ya existentes, pero no modificarlos o hacer envíos desde cero.

**Comment by lhchavez** [comment]
Según yo esto ya lo arreglamos.
