### ISSUE TITLE
Wrong answer cuando la respuesta tiene muchos caracteres.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#2535]
## Comportamiento Esperado

Al subir un problema en donde la respuesta contiene muchos caracteres, en este caso 10^7, omegaUp da como veredicto Wrong Answer cuando deberia de dar AC.

Baje los archivos de salida y los compare con diff en Linux y todos son iguales, por lo que no se en realidad que este pasando cuando hace la evaluacion.

**Comment by lhchavez** [comment]
qué evaluador estás usando? eso afecta.

el que compara token por token tiene un límite de [4MB](https://github.com/omegaup/quark/blob/d026e4d42ac784f26e52fa103d4e4166f9ae9a37/runner/tokenizer.go#L11-L13) por token. normalmente no afecta porque los tokens están separados por espacio, excepto si tienes los 10^7 caracteres sin separación alguna.

supongo que podemos subir ese límite (o puedes usar un validador personalizado), pero toma en cuenta que debe haber _algún_ límite.

**Comment by galloska** [comment]
Si use el de token por token. Pero es bueno saber que usando un validador personalizado puedo arreglar eso.

Yo creo que la solución sería que a los que lo requieran usen un validador personalizado, pero si habria que agregar ese detalle en la wiki de "Como desarrollar un problema."

**Comment by lhchavez** [comment]
Listo! https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-escribir-problemas-para-omegaUp#configuraci%C3%B3n
