### ISSUE TITLE
No se puede clonar un Curso, en la opción Escuelas

### ISSUE THREAD

**Issue by jofeque** [omegaup/omegaup#2536]
Tengo dos Cursos en la opción de Escuelas, 
- Un Curso **si lo puedo clonar** (https://omegaup.com/course/CHH20E1) mediante la opción de Clonar al estarlo editando)
- El otro, https://omegaup.com/course/CHH19PS1, **no lo puedo clonar**, al tratar de clonarlo me envía el mensaje de **Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.** Todos los parámetros (nombre, alias y fecha de inicio), creo, están correctos. He cambiado algunas características que pudieran estar pegando en que se de el error, pero no he conseguido clonarlo

![no se puede clonar curso](https://user-images.githubusercontent.com/33610618/58751291-fa6e5000-8459-11e9-820e-204ee9c1e74b.png)

**Comment by lhchavez** [comment]
Hmm, parece que este curso está usando un problema que volvieron privado después de haberlo agregado al curso.

@pabo99 puedes hacer los siguientes cambios?

- En [`CourseController::apiClone`](https://github.com/omegaup/omegaup/blob/130d2aea456cd17a1dee90e560a81a877975cf58/frontend/server/controllers/CourseController.php#L194) hay que atrapar `ApiException` y propagarlo en vez de `InvalidParameterException` y `DuplicatedEntryInDatabaseException`.
- Hay que evitar mandar llamar APIs desde el API. Eso quiere decir que hay que hacer refactor de las llamadas que hacemos para permitir invocar esas cosas como métodos normalitos.
- Finalmente, una vez que tengamos métodos normalitos para agregar los problemas al curso, hay que pasarle una bandera que permita NO hacer la verificación de si el problema es privado. En teoría si en el pasado tuviste permiso para agregar un problema, ese permiso sigue siendo válido para fines de clonar el curso (a pesar del hecho de que si quisieras crear ese curso de nuevo desde cero no podrías porque ese problema ya no sería agregable).
