### ISSUE TITLE
Curso introductorio a la OMI

### ISSUE THREAD

**Issue by RisingCephalopod** [omegaup/omegaup#2544]
*Buenos días. Soy nuevo en a plataforma y hace poco comencé el curso introductorio. Actualmente voy en el tema de funciones y en uno de los problemas se me pide que descargue una plantilla para problema interactivo, pero al hacerlo me da un error 404. ¿Podrían arreglarlo por favor? Saludos.*

**Comment by tvanessa** [comment]
Duplicado de #3032
