### ISSUE TITLE
El total de puntos no se despliega de manera bonita

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2550]
Pareciera que es un error típico de floats al hacer sumas:

![image](https://user-images.githubusercontent.com/123875/58992560-05015000-87a0-11e9-86ad-c4d75bf86e43.png)

![image](https://user-images.githubusercontent.com/123875/58992567-09c60400-87a0-11e9-83d4-6e26d6ad57ac.png)

Concursos con el error:

https://omegaup.com/arena/pes-2019-junio-1

https://omegaup.com/arena/pes-2019-junio-2

**Comment by darknut** [comment]
Está relacionado al issue #2545

**Comment by lhchavez** [comment]
no es un error per se: es un efecto colateral de cómo se representan los floats internamente.
