### ISSUE TITLE
[User Badges] Create "Badges" section on omegaUp.com

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2621]
Parte de [User Badges](https://docs.google.com/document/u/2/d/1PUoWuJz3l6R7_ZfueA2YGKy14-1dBaH7wZ9hJ250pNg/edit)

**Comment by carlosabcs** [comment]
Perdón, se me olvidó que este issue también fue solucionado en #2639

**Comment by carlosabcs** [comment]
Ping para que recuerdes cerrar este issue @lhchavez

**Comment by lhchavez** [comment]
Gracias por el recordatorio!
