### ISSUE TITLE
[User Badges] Create "earned badges" subsection on user profile.

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2622]
Parte de [User Badges](https://docs.google.com/document/u/2/d/1PUoWuJz3l6R7_ZfueA2YGKy14-1dBaH7wZ9hJ250pNg/edit)

**Comment by carlosabcs** [comment]
@lhchavez this issue was closed on #2629

**Comment by lhchavez** [comment]
huh, TIL que necesitas poner un `Fixes: #XXX` por cada issue que quieres cerrar. No se vale poner varios en la misma línea.
