### ISSUE TITLE
[BUG] Como usuario quiero que no se inicie sesión automáticamente con Google (con la sesión de Google actual), para poder iniciar sesión de otra forma.

### ISSUE THREAD

**Issue by TsukiZombina** [omegaup/omegaup#2637]
Debido a que los botones de inicio de sesión con distintos servicios tardan distintos tiempos en aparecer di click en iniciar sesión con Google sin querer en vez de Facebook, esto me creó una cuenta nueva de OmegaUp con Google.

## Comportamiento Esperado
Quisiera que hubiera forma de elegir con qué cuenta iniciar sesión en OmegaUp a pesar de tener una sesión iniciada en Google.

## Comportamiento Actual
Debido a que uso Google Chrome, mi sesión de Google siempre está iniciada y cuando abro OmegaUp inmediatamente se inicia esa sesión lo cual me impide iniciar sesión con Facebook. Puedo cerrar esa sesión y tratar de tener más velocidad que mi navegador web para entrar con Facebook, pero en general en muy difícil lograrlo.

## Posible Solución
Poner otro tipo de autenticador de Google (?)

## Pasos para reproducir (para bugs)
1.  Tener una sesión iniciada de Google
2.  Dar click en https://omegaup.com/login/
3.  Inisia sesión automáticamente con Google sin dar tiempo suficienta para elegir otro tipo de inicio de sesión.

## Contexto
no me es posible iniciar sesión con Facebook en google Chrome dado que siempre tiene la sesión de Google iniciada.

## Tu ambiente
* Nombre del navegador: En Chrome, Firefox o Qutebrowser teniendo iniciada la sesión de Google.
* Sistema Operativo y versión (escritorio o móbil): En Windows o Linux de escritorio.
* Link al sitio en el que este problema pasa: https://omegaup.com/login/

**Comment by TsukiZombina** [comment]
Aun inicia sesión automáticamente con la sesión actual de Google por lo que no me es posible ingresar con la cuenta correcta sin la necesidad de eliminar cookies.

**Comment by lhchavez** [comment]
intenta cerrar sesión primero. una vez que cierres la sesión, ya no debería volver a auto-iniciar sesión.
