### ISSUE TITLE
Error al ver problemas habiendo ingresado

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2659]
Hola amigos de OmegaUp.

Desde ayer domingo 7 de julio, más o menos como a las 10PM la plataforma ya no dejaba ver problemas a los usuarios logueados (curiosamente, si estás deslogueado sí puedes verlos).
Ya lleva así un buen rato; lo reporté por Facebook pero creo que aún no han leído mi mensaje.

**Comment by lhchavez** [comment]
acá respondemos más rápido porque Facebook no es el mejor lugar para llevar el seguimiento de los problemas de la plataforma.

@pabo99 puedes ayudar con esto?

**Comment by darkmx** [comment]
gracias :) luego cuando el sitio anda caído les aviso por Facebook porque no es un "bug" como tal, pero chance éste sí y ya lleva un rato :(
