### ISSUE TITLE
[BUG] Hacer responsiva la barra de navegación de omegaUp

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2675]
## Comportamiento Esperado

La barra de navegación debe responder efectivamente a todo tipo de tamaños de pantalla, permitiendo que se accedan a las diferentes dentro de omegaUp de manera efectiva.

## Comportamiento Actual

Hay tamaños en los que la barra de navegación se parte y terminá sobreponiéndose al contenido, impidiendo la libre vista del mismo.

## Posible Solución

Diseñar una barra de navegación adaptada a los estándares actuales e implementarla.

**Comment by tvanessa** [comment]
#3545 resuelve este issue?

**Comment by pabo99** [comment]
Se ha tratado de mitigar en gran parte. Pero aún existe un pequeño rango de resoluciones donde sucede eso. No sé si para poder resolver por completo este error debamos migrar a Bootstrap 4

**Comment by tvanessa** [comment]
#3758
