### ISSUE TITLE
Regresión: La barra de OmegaUp aparece el doble de alta

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2679]
Si inicias sesión con una cuenta con un nombre largo ves esto:

![image](https://user-images.githubusercontent.com/123875/61340774-9e3c7100-a7f8-11e9-98dc-839d9f9987b7.png)

Con una cuenta con un nombre corto, se ve bien:

![image](https://user-images.githubusercontent.com/123875/61340784-a8f70600-a7f8-11e9-947e-c3a8412c3dfb.png)

La primer cuenta usó google login, la segunda usó OmegaUp username

**Comment by lhchavez** [comment]
@pabo99 welp, justo lo que comentabas hoy en la mañana u_u

**Comment by pabo99** [comment]
Sucedió demasiado rápido, de hecho todavía no se libera el Refactor. Más bien, parece que la campaña de notificaciones en la que le está quitando el espacio que antes tenía el username.

**Comment by carlosabcs** [comment]
De hecho sí es por culpa de la campana u.u

**Comment by pabo99** [comment]
La propuesta de @lhchavez es migrar a `Bootstrap 4`, y de paso yo creo que requiere un nuevo
acomodo de los menús. Esto hay que revisarlo con el equipo de `UX`.

**Comment by carlosabcs** [comment]
Perdón por la insistencia, pero tal vez una solución _provisional_ sea aumentarle el ancho al navbar un poco, de 900px ~> 950px.

En lo que el equipo de `UX` especifica los nuevos cambios para los menús con Bootstrap 4.

**Comment by lhchavez** [comment]
podemos esconder la campana en lo que encontramos una solución más permanente? también estoy abierto a hacerle cambios al navbar para que esconda elementos detrás de un drop-down si no caben dado el ancho del nombre

**Comment by carlosabcs** [comment]
Me parece mejor así. Voy a esconderla provisionalmente.

Lo otro que propones, supongo que debería hacerse post-migración?

**Comment by lhchavez** [comment]
según recuerdo había manera en bootstrap 3 para hacer eso, pero podría estar confundiendolo com bootstrap 4

**Comment by gabrc52** [comment]
Todavía no se ha arreglado para /arena/problem/, habría que reabrir esta issue.

**Comment by lhchavez** [comment]
@gabrc52 la campana ya se ocultó, así que eso que mencionas es un issue nuevo (no es una regresión ocasionada por la campana). puedes abrir un issue nuevo con un screenshot de lo que estás observando?

**Comment by gabrc52** [comment]
Listo: #2797
