### ISSUE TITLE
La barra de navegación ocupa mucho espacio, impidiendo buscar

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#2692]
Para usuarios con nombres largos, ahora que aparece un ícono de notificaciones la barra de navegación ocupa dos rengoles, tapando la barra de búsqueda.

![image](https://user-images.githubusercontent.com/24363938/61571679-ce834a00-aa5a-11e9-805e-b9eb09a8553f.png)

## Comportamiento Esperado

La barra de navegación ocupa un renglón.

## Comportamiento Actual

La barra de navegación ocupa dos renglones impidiendo la utilización correcta.

## Pasos para reproducir (para bugs)

1. Cambiar tu nombre de usuario a uno largo

## Tu ambiente

Firefox 67.0.2

**Comment by lhchavez** [comment]
Dupe de #2679 . el lunes siguiente se hace el deploy.
