### ISSUE TITLE
Devolver opciones del Ranking

### ISSUE THREAD

**Issue by Adrigondo** [omegaup/omegaup#2713]
## Comportamiento Esperado
Que en la pestaña de ranking, aparezcan las opciones que habian antes para visualizar el ranking segun el pais, el estado, y la escuela.

## Comportamiento Actual
Las unicas opciones que aparece es la de buscar usuario, pagina siguiente y pagina anterior.

## Posible Solución
Devolver las opciones, pues era algo muy util.

## Pasos para reproducir (para bugs)

1. 
2. 
3. 
4. 

## Contexto
Utilizaba mucho estas opciones pues podia ver el avance que llevan mis compañeros de clase.

## Tu ambiente

Chrome
Windows 10(escritorio)
https://omegaup.com/rank/

![Ranking](https://user-images.githubusercontent.com/53382424/61999775-8335f080-b085-11e9-844b-75ca7eee7958.png)

**Comment by joemmanuel** [comment]
Gracias por el reporte @Adrigondo ! 
Tenemos +1 reporte similar por Facebook.

**Comment by pabo99** [comment]
Hola @Adrigondo, Me puedes ayudar a resolver ciertas dudas que me surgieron:
- ¿Recientemente editaste datos de tu perfil o estás utilizando un usuario en el que no le hayas actualizado su información (País/Región, Estado o Escuela)? Este es el único requisito que se debe cumplir para mostrar los filtros apropiadamente.

Acabo de ingresar a mi cuenta, y si puedo verlos:
![Rank – omegaUp - Google Chrome 2019-07-31 20-04-23 gif](https://user-images.githubusercontent.com/3230352/62258548-89eb9d00-b3d0-11e9-9557-5792fcf54975.gif)

En caso de que si los tengas actualizados, proseguiré a revisar que otros factores pudieran estar ocultando esos filtros.

**Comment by lhchavez** [comment]
huh, eso no debería ser requisito. posiblemente ese es el bug

**Comment by pabo99** [comment]
Entonces cuando un usuario no haya registrado uno de esos datos, ¿qué le debería mostrar al elegir el filtro? Actualmente sólo te filtra la información dependiendo de lo que tengas registrado en tu cuenta.

**Comment by lhchavez** [comment]
aaaah espera, el filtro es buscar por _mi país / región_, no por un país arbitrario. entonces está bien así, sólo hay que cambiar el texto (para incluir el "mi") y desplegar un mensaje cuando no se ha llenado esa información en el perfil para que sea descubrible.

**Comment by pabo99** [comment]
Lo que si me causa duda, es que antes a @Adrigondo si le aparecía y ahora no. 

Hay un punto en el que esto pudo haber sucedido, y es cuando se eliminaron los campos de esos filtros de la tabla `Users`, aunque no tendría porque pasar, tomando en cuenta el script del archivo [49_add_identity_table.sql](https://github.com/omegaup/omegaup/blob/master/frontend/database/49_add_identity_table.sql)

**Comment by Adrigondo** [comment]
Ya no me aparecia la opcion desde hace un mes mas omenos y hace 3 dias me volvio a aparecer la opcion, no he cambiado ningun dato, y tengo todos los datos necesarios. Lo que si hice, es que como una o dos semanas antes de que me dejase de aparecer la opcion, camnie el nombre de usuario.

**Comment by Adrigondo** [comment]
Pero en si, las opciones me volvieron a aparecer hace 3 días.

**Comment by pabo99** [comment]
Voy a intentar eso que mencionas (cambiar el nombre de usuario) y ver como se comportan los filtros.

**Comment by pabo99** [comment]
@Adrigondo: realicé algunas pruebas para validar que los filtros no desaparezcan cuando realizas cambios de tu información. 

A partir del domingo en la noche te deberían aparecer ciertas modificaciones.

Así se deberían cada una de las vistas de ranking de usuarios:

Cuando el usuario no está logueado:
![new_message_must_login](https://user-images.githubusercontent.com/3230352/62373353-36c43800-b4ff-11e9-93c3-ac51599b59ce.png)

Cuando el usuario no ha actualizado su información básica:
![new_user_with_basic_info](https://user-images.githubusercontent.com/3230352/62373337-2ca23980-b4ff-11e9-85eb-2e727e81e84a.png)

Cuando el usuario ya actualizó al menos un dato de la información básica (Escuela, Estado o País):
![new_message_basic_info](https://user-images.githubusercontent.com/3230352/62373348-3166ed80-b4ff-11e9-93f1-9a487c4f7555.png)

Si el lunes notas que aún sigue fallando algo, favor de reportarlo.
