### ISSUE TITLE
Error Cursos pasados

### ISSUE THREAD

**Issue by Adrigondo** [omegaup/omegaup#2720]
*En el caso de un feature, provee un título en el siguiente formato:*

## Comportamiento Esperado
En la pestaña escuela, en la seccion de cursos pasados deberian aparecer los cursos en los que he estafo, pero ya finalizaron. 

## Comportamiento Actual
No aparece ningún curso antiguo, aparecen los mismos que en los cursos actuales.

##Pasos para reproducir
Para ver el bug solo hay que entrar ennla seccion Escuela, y en la opcion de Cursos pasadis dar clic, no apareceran los cursos pasados, únicamente los actuales. 

## Posible Solución
Creo que a la seccion cursos pasados esta realizando la misma accion que los cursos actuales, por lo que no cambia nada. 

## Contexto
*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*
Me gustaría poder realizar problemas que tenia en una clase, sin embargo no recuerdo su nombre. 

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
Chrome
* Sistema Operativo y versión (escritorio o móbil):
Windows 10(escritorio)
* Link al sitio en el que este problema pasa:
https://omegaup.com/course
* Captura de pantalla:
![Screenshot_20190729_121116](https://user-images.githubusercontent.com/53382424/62071650-40495980-b1fa-11e9-9584-85fea76ea11b.jpg)
![Screenshot_20190729_121222](https://user-images.githubusercontent.com/53382424/62071651-40e1f000-b1fa-11e9-814b-8a44012b4caa.jpg)

**Comment by lhchavez** [comment]
esto lleva rato así o es algo reciente?

**Comment by Adrigondo** [comment]
Desde que descubri el error, lleva como 2 o 3 meses.
