### ISSUE TITLE
Errores cuando edito un problema ó intento crear uno nuevo.

### ISSUE THREAD

**Issue by dambort** [omegaup/omegaup#2725]
Soy el usuario dambort, ya he subido unos cuantos problemas, porque los utilizamos en la asignatura "Algoritmos y Estructuras de Datos" de 1er. año de la Universidad Tecnológica Nacional. Facultad Regional Santa Fe. Argentina.

Adjunto una captura de pantalla, mostrando que el problema más reciente que subí, lo dejé hace unos días con estado "No Público"

![Screenshot_2019-07-30 Mis problemas – omegaUp](https://user-images.githubusercontent.com/8449652/62160495-8382f580-b2ea-11e9-97f6-90196973caae.png)

cuando intento editarlo, para cambiarle el estado y publicarlo, obtengo el siguiente mensaje de error:

![Screenshot_2019-07-30 Editar problema – omegaUp](https://user-images.githubusercontent.com/8449652/62160553-9eee0080-b2ea-11e9-86b1-97e063e2cea8.png)

También sucede algo similar, cuando intento crear un problema nuevo.

Espero que puedan corregir el problema!

Desde ya muchas gracias y saludos desde Argentina!

Daniel Ambort

**Comment by lhchavez** [comment]
huh, al parecer la tabla de `Tags` tenía una columna que no estaba en el esquema esperado y eso estaba causando que no se pudiera construir el objeto. Inténtalo nuevamente, ya debería estar solucionado.

Saludos desde México / Estados Unidos!
