### ISSUE TITLE
(Badges) Desfase de la descripcion del badge

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#2730]
Cuando el puntero está sobre un badge específico se muestra la descripción del siguiente badge, no del actual.
![bugBadges2](https://user-images.githubusercontent.com/13296248/62245937-7ff97800-b397-11e9-957a-50b8e7a292a7.gif)

El error sólo lo vi en firefox (v66.0.3 y v68), en chrome funciona bien.

**Comment by lhchavez** [comment]
@carlosabcs
