### ISSUE TITLE
Error al descargar problemas interactivos desde Escuelas

### ISSUE THREAD

**Issue by LaloRivero** [omegaup/omegaup#2784]
## Comportamiento Actual

*No es posible descargar los archivos de los problemas interactivos que se encuentran en el Curso-OMI en el apartado de ordenamiento y complejidad*

## Pasos para reproducir (para bugs)

https://omegaup.com/templates/COMI-Bubble/undefined/COMI-Bubble_windows_cpp.zip

## Tu ambiente

* Chrome
* Windows

**Comment by lhchavez** [comment]
huh, esto sólo ocurre cuando se visita el problema desde escuelas: https://omegaup.com/course/Curso-OMI/assignment/Ordenamiento_y_complejidad#problems/COMI-Bubble

**Comment by lhchavez** [comment]
@pabo99 esto parece que es causado porque tenemos tres funciones que hacen _casi_ lo mismo: https://github.com/omegaup/omegaup/blob/af95b5bdff3b551fdcb26887c77855c5cf99fa90/frontend/server/libs/dao/Problemset_Problems.dao.php#L13 https://github.com/omegaup/omegaup/blob/af95b5bdff3b551fdcb26887c77855c5cf99fa90/frontend/server/libs/dao/Problemset_Problems.dao.php#L101 y https://github.com/omegaup/omegaup/blob/af95b5bdff3b551fdcb26887c77855c5cf99fa90/frontend/server/libs/dao/Problemset_Problems.dao.php#L212

ya mitigué el error en #2786, pero puedes hacer un refactor para no tener esa triplicación de lógica?

**Comment by pabo99** [comment]
Enterado

**Comment by LaloRivero** [comment]
Gracias por el apoyo y la pronta respuesta que dan a los issues en OmegaUp, pero sigue pasando lo mismo, no se pueden descargar los archivos desde el Curso-OMI en escuelas. Por fuera ciertamente funciona con normalidad. Saludos

**Comment by lhchavez** [comment]
ah es que únicamente hacemos deploy los domingos en la noche

**Comment by LaloRivero** [comment]
A excelente entonces el lunes checo muchas gracias
