### ISSUE TITLE
[BUG] La barra de navegación aparece el doble de alta en /arena/problem

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#2797]
Similar a #2679, pero ocurre al ver un problema, por ejemplo, https://omegaup.com/arena/problem/ASUMAB#problems

Al utilizar un nombre de usuario corto (OK):

![image](https://user-images.githubusercontent.com/24363938/63611208-ffe2be80-c5a0-11e9-822a-7f56031b2d82.png)

Al utilizar un nombre de usuario largo:

![image](https://user-images.githubusercontent.com/24363938/63611282-24d73180-c5a1-11e9-991f-6cf2b809532a.png)

Al desplazarse hacia arriba no se puede ver la barra donde aparecen envíos, clarificaciones, etc:

![image](https://user-images.githubusercontent.com/24363938/63611331-3fa9a600-c5a1-11e9-8653-6f8d17bab544.png)

## Tu ambiente

Firefox 67.0.2 maximizado, resolución de 1366x768

**Comment by lhchavez** [comment]
bajando la prioridad porque ya fue mitigado (según yo).

si sigue apareciendo el problema, por favor avísanos para volverle a subir la prioridad.

**Comment by categulario** [comment]
@lhchavez sigue pasando

![Captura de pantalla de 2019-10-09 21-54-29](https://user-images.githubusercontent.com/790756/66535575-a3e7e100-eadf-11e9-8fa4-05689f23fe4f.png)

firefox 70 en linux

**Comment by categulario** [comment]
me gustaría echarme un fix, aunque no le veo ni pies ni cabeza a cómo montar una versión local de este desmain pa'probar

**Comment by lhchavez** [comment]
> me gustaría echarme un fix, aunque no le veo ni pies ni cabeza a cómo montar una versión local de este desmain pa'probar

https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar

**Comment by categulario** [comment]
¿el docker funciona?

**Comment by lhchavez** [comment]
> ¿el docker funciona?

posiblemente. hace varios años nadie lo toca :( (deberíamos borrarlo para evitar confusión)

**Comment by categulario** [comment]
será? a mi humilde parecer docker >> vagrant, incluso para el deploy

**Comment by heduenas** [comment]
Conmigo ya no se reproduce, por lo menos en Firefox 72 en MacOS

**Comment by categulario** [comment]
@heduenas trata con un ancho de pantalla entre 769px y 869 px

**Comment by lhchavez** [comment]
@heduenas también intenta con un nombre de usuario largo
@categulario por cierto, Docker ya está semi-soportado de nuevo: https://github.com/omegaup/omegaup/pull/3346

**Comment by pabloaguilar** [comment]
A mi me sigue pasando, en Firefox 73 con mi lenguaje puesto en Español.
