### ISSUE TITLE
Hacer que share_user_information y accept_teacher, en GroupIdentities, sean booleanos de verdad

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2812]
## Comportamiento Esperado

Idealmente se debería usar booleanos cuando se debe escoger 1 opción entre 2 alternativas. Sobretodo cuando los campos indican explícitamente que es una opción: o verdadera o falsa.

## Comportamiento Actual

`share_user_information` puede ser `1` o `0`.
`accept_teacher` puede ser `yes` o `no`.

## Posible Solución

- Para `share_user_information`, migrar todos los `1` a `true`, y los `0` a `false`. Actualizar DAO y controladores + pruebas y frontend.
- Para `accept_teacher`, migrar todos los `yes` a `true`, y los `no` a `false`. Actualizar DAO y controladores + pruebas y frontend.

**Comment by carlosabcs** [comment]
@lhchavez puedes darle el visto bueno a lo que describo en la sección de `Posible Solución` en este issue?

**Comment by lhchavez** [comment]
ae ve bien!
