### ISSUE TITLE
Progreso en OmegaUp Escuelas no es correcto

### ISSUE THREAD

**Issue by JACazares** [omegaup/omegaup#2842]
## Comportamiento Esperado

En la pagina de OmegaUp Escuelas, en el curso Proceso de Entrenamiento y Selección 2020 (https://omegaup.com/course/PES-2020), en el apartado de progreso debería de aparecer un porcentaje que indique que tanto has resuelto en la Tarea específica.

## Comportamiento Actual

En este momento, si no has resuelto nada aparece --.--%, y si has resuelto 1 o mas problemas, aparece Infinity%

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Entrar a https://omegaup.com/course/PES-2020
2. Entrar a cualquier tarea y resolver un problema
3. Regresar a la pagina principal del curso
4. Aparece Infinity%

## Contexto

Esto me afecta porque no se con exactitud que tanto he resuelto, y no me puedo comparar adecuadamente con mis compañeros que también están en este curso.

## Tu ambiente

* Chrome 76.0.3809.100 (Official Build) (64-bit)
* MacOS Mojave 10.14.6
* https://omegaup.com/course/PES-2020
* Captura de pantalla:
<img width="1280" alt="Screen Shot 2019-08-28 at 9 29 35 PM" src="https://user-images.githubusercontent.com/17916448/63905794-f6ab8480-c9da-11e9-8edd-7e63508511e9.png">

**Comment by lhchavez** [comment]
welp, posiblemente tenemos una divisiṕn entre cero D:

**Comment by pabo99** [comment]
> welp, posiblemente tenemos una división entre cero D:

Lo reviso

**Comment by JACazares** [comment]
El curso del "Proceso de Entrenamiento y Selección 2020" me sigue mostrando Infinity%. Aproximadamente cuando se deberia de arreglar esto?

**Comment by lhchavez** [comment]
el lunes siguiente debería entrar a producción.
