### ISSUE TITLE
ayuda libreria cv

### ISSUE THREAD

**Issue by antoniotacuri** [omegaup/omegaup#2863]
Estoy investigando en el proc de imagenes, he bajado algunos codigos y hay un componente donde importan la libreria cv. Instalo dicha libreria poniendo pip install cv y cv2 y no puedo importarla, me puede por favor ayudar cual es el error

**Comment by lhchavez** [comment]
lamentamos que tengas un error, pero este no es un canal donde puedes pedir soporte técnico para cosas no-relacionadas con omegaUp.
