### ISSUE TITLE
No permite agregar problemas a concursos

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#2873]
No es posible agregar algunos problemas en los concursos, la mayoría de los problemas, a presionar el botón de agregar, marca "Versión del problema no encontrada".

Con algunos pocos problemas si funciona pero la mayoría de los que quise agregar marcaron el error.

![version](https://user-images.githubusercontent.com/22159184/64175587-3d590e80-ce21-11e9-96c1-b49e453d53b5.JPG)

**Comment by joemmanuel** [comment]
+1 reporte del mismo problema por Facebook.

**Comment by pabo99** [comment]
Este es uno de los problemas que no permite agregar a concursos:

https://www.youtube.com/watch?v=vUUSSYe6wRA&feature=youtu.be

El error se da en el problema Estaciones.

**Comment by lhchavez** [comment]
a ver intenta de nuevo, ya corregí todos los problemas que usaban `published` como commit.

**Comment by licgerman** [comment]
Hice una prueba con varios problemas al azar. Ya todos se pudieron agregar. Gracias.
