### ISSUE TITLE
No aparece el botón de seguir en Twitter

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2878]
En la página principal de omegaUp no aparece el botón de `Seguir` de `Twitter`. Esto no se da siempre, es un hecho que se da esporádicamente, pero afecta directamente a las pruebas de selenium, tanto en ambiente local, cómo en Travis.

## Comportamiento Esperado

Así se debería mostrar:

![ok_twitter](https://user-images.githubusercontent.com/3230352/64356021-c90c9f80-cfc7-11e9-8d2e-94d5f9d9d18a.png)

## Comportamiento Actual

Pero en ocasiones se muestra así:

![error_twitter](https://user-images.githubusercontent.com/3230352/64356046-d6298e80-cfc7-11e9-869c-729d1571bd6a.png)

**Comment by lhchavez** [comment]
Parece que la manera de hacer el embed cambió: https://developer.twitter.com/en/docs/twitter-for-websites/follow-button/overview

**Comment by lhchavez** [comment]
```html
<a href="https://twitter.com/omegaUp?ref_src=twsrc%5Etfw" class="twitter-follow-button" ...>Follow @omegaUp</a>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

parece que hay que poner el `<script>` después del `<a>` y nosotros lo tenemos antes, en `frontend/templates/head.tpl`. puedes moverlo a `frontend/templates/footer.tpl`?

**Comment by pabo99** [comment]
> ```
> <a href="https://twitter.com/omegaUp?ref_src=twsrc%5Etfw" class="twitter-follow-button" ...>Follow @omegaUp</a>
> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
> ```
> 
> parece que hay que poner el `<script>` después del `<a>` y nosotros lo tenemos antes, en `frontend/templates/head.tpl`. puedes moverlo a `frontend/templates/footer.tpl`?

Si, en un momento hago este cambio
