### ISSUE TITLE
No aparece el botón de Agregar problema a un Concurso

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#2894]
Como organizador de concursos quiero agregar problemas, pero al escribir el nombre no logro ver el botón de `Agregar problema`.

## Comportamiento Esperado

Al elegir un problema para agregarlo en un concurso esperaría que estuviera disponible el borón de Agregar problema.

## Comportamiento Actual

El botón no aparece aunque elija el problema de la lista.

## Posible Solución

Esto comenzó a ocurrir desde que se solucionó el #2873 debido a que se realizaban varias acciones al intentar presionar dicho botón. Ahora funciona de la siguiente forma:

Al escribir el nombre o alias del problema y/o elegirlo de la lista de sugerencias se debe presionar la tecla `Enter` o simplemente quitar el foco de dicho campo. Esto para que se pueda mandar `Problem::apiVersions`, una vez que esta `API` responde ahora si aparece el botón.

La solución pudiera ser agregar una nota que indique lo que se debe hacer para que no haya confusiones.

**Comment by lhchavez** [comment]
ya intenté con el problema https://omegaup.com/arena/problem/aldp y no hay repro cuando hago click afuera del campo D: (pero a veces con enter no es suficiente)

**Comment by pabo99** [comment]
Para este issue se considera agregar una nota con las instrucciones para poder elegir la versión del problema, además se agrega un botón para que sea más claro.

Antes de elegir problema:
![Select Problem](https://user-images.githubusercontent.com/3230352/65070387-256da880-d952-11e9-98d8-05fe9d4f91b2.png)

Una vez que se presiona el botón de Obtener versiones:
![Get Versions Problem](https://user-images.githubusercontent.com/3230352/65069875-31a53600-d951-11e9-9ab9-828ccca48a3d.png)
