### ISSUE TITLE
Error al enviar codigos en escuelas: "El concurso ya termino, o aun no empieza"

### ISSUE THREAD

**Issue by Adrigondo** [omegaup/omegaup#2903]
## Comportamiento Esperado

La clase esta abierta por lo que me deberia dejar enviar mis codigos

## Comportamiento Actual

Al enviar un codigo sale en la pantalla el siguiente mensaje: "La clase ya termino, o aun no empieza"

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

En el curso introductorio a la OMI, al intentar enviar un codigo en la tarea de estructuras de datos avanzadas sale ese error.

## Contexto

Es la segunda vez que ocurre el error, y como es un curso recomendado en el inicio, decidi reportarlo. La primera vez ocurrio en una clase que creo mi profesor, y como no se pudo solucionar, creamos otra, donde ya no ocurrió el error.
## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador : Chrome
* Link al sitio en el que este problema pasa: https://omegaup.com/course/Curso-OMI/assignment/COMI-EDA#problems/COMI-Paseo-por-el-Bosque/new-run
* Errores en la consola: []
* Captura de pantalla:
![error1](https://user-images.githubusercontent.com/53382424/65006222-b0ea2980-d8bf-11e9-8dc1-f6b983cc602b.JPG)

**Comment by pabo99** [comment]
No logro reproducir el error que te marca, aún ingresando al curso que comentas e intentando realizar un envío a ese mismo problema. Las condiciones para que ese mensaje de error aparezca son:
- Que el curso / concurso no haya iniciado.
- Que el curso / concurso ya haya finalizado.
- Que el `problemsetIdentity->end_time` se haya seteado correctamente.

**Comment by lhchavez** [comment]
Dupe de #3029
