### ISSUE TITLE
[Schools] Los timestamps se muestran como, hmm, timestamps

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2907]
*Como un maestro, quise crear una tarea e accidentalmente le di una fecha de inicio anterior a la fecha de inicio del curso

## Comportamiento Esperado

La plataforma deberia indicarme que no puedo asignar una fecha/hora anterior al inicio de clases, pero mostrar el inicio de clases en forma de fecha

## Comportamiento Actual

Se muestra el inciio de clases en forma de timestamp
![image](https://user-images.githubusercontent.com/189223/65383479-00b75f00-dccb-11e9-85b9-2126759fee75.png)

## Posible Solución

Representar la fecha en forma de fecha

## Pasos para reproducir (para bugs)

1.  Crear un curso con cierta fecha de inicio
2.  Crear una tarea con una fecha/hora de inicio anterior a la fecha de inicio del curso
3.  Click en "Schedule assignment"
4.  Observar el error en la barra de errores

**Comment by carlosabcs** [comment]
Estuve revisando cómo solucionar esto, y, según yo, implica hacer refactor en [`Validators::validateNumberInRange`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Validators.php#L292) y en [`Request::ensureInt()`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Request.php#L117), para que puedan determinar si es una fecha o no y mostrar el epoch parseado a Date cuando arrojen la excepción.

Es así @lhchavez ?
