### ISSUE TITLE
"Cross-site request forgery attempt" error upon loading www.omegaup.com

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#2914]
User who has never used omegaUp opened the webpage and a red banner showed up with "Cross-site request forgery attempt".

User was not able to create an account.

Same behavior was observed in a private session.

Same behavior was observed in a second computer.

**Comment by lhchavez** [comment]
workaround: do not enter the site through www.omegaup.com, just omegaup.com

**Comment by rcxr** [comment]
Nice! I was able to reproduce the issue when using www.omegaup.com

I updated the issue title

**Comment by lhchavez** [comment]
a permanent redirect was added.
