### ISSUE TITLE
Agregar Issue Template para la propuesta de Badges

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#2916]
En la [Guía para la propuesta de Badges](https://docs.google.com/document/d/1Q9C_IInZ65nuwzbgGjHuwiqy0Ngw9P6Vc26IhumCvoM/edit), al final del documento, se establece también la creación de un issue template para poder proponer badges libremente.

La creación de este template está restringido a los propietarios del repositorio. Cómo agregar este archivo, lo describe la propia guía de Github: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by lhchavez** [comment]
Arreglado en https://github.com/omegaup/omegaup/pull/3010
