### ISSUE TITLE
[FEATURE] Permitir a los usuarios ver qué problemas están resolviendo otras personas

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#2918]
Contexto: https://docs.google.com/document/d/1X-i2lq3erDrB7lH_0JhF4YBTPXqJIVUuQW4Wy9rxNCs/edit?ts=5d960c29

**Comment by lhchavez** [comment]
no entiendo a qué te refieres con ticker :S

**Comment by pabloaguilar** [comment]
En el document hacen referencia a algo asi:
https://familytechzone.com/missing-the-facebook-ticker/

**Comment by lhchavez** [comment]
ah ya. la tendencia global es a eliminar los tickers (facebook eliminó el suyo hace tiempo e Instagram acaba de anunciar hoy que lo va a eliminar pronto), así que quizás serìa bueno reconsiderar el ticker como mecanismo. pero +1 a la idea de exponer *algo* que resuelva la necesidad de los usuarios

**Comment by heduenas** [comment]
Tal vez un feed de actividad de tus contactos. Estilo la de Strava que siempre te muestra todo en orden cronologico y es deterministico.

**Comment by lhchavez** [comment]
puede ser. preferiría no introducir dos conceptos al mismo tiempo (contactos y el feed), así que si un feed global de actividad que muestre todos los primeros ACs recientes enviados a problemas públicos o participación en concursos públicos realmente resuelve el problema, +1.

también me gustaría ver otras alternativas (onda lo que dijo Joe en el comentario de ese documento de "debugguear" mejor la petición)

**Comment by heduenas** [comment]
Queda resuelto con el feed de @carlosabcs
