### ISSUE TITLE
Evaluador me sigue dando JE en submissions.

### ISSUE THREAD

**Issue by galloska** [omegaup/omegaup#2922]
El evaluador me da JE en problema con multiples queries. E intentado usar mi propio validador, incrementar el tiempo, usar el validador por default de omegaUp y ningun parece funcionar. De 150 casos que tenia, lo baje a 90, despues 50, y ahora con solo 18 casos, el problema sigue sin funcionar. 

Se mantiene en status "new" sin dar ningun veredicto. Eh intentado recortar muchas cosas de mi problema (Lo cual no deberia) pero sigue sin funcionar la plataforma.

![image](https://user-images.githubusercontent.com/6158469/66273949-09ad4200-e82e-11e9-9593-5116bd849bfb.png)

Este problema es parte del Coding Cup TECNM. Espero se le pueda dar alguna solucion a este issue.

Nota: Con problemas de multiples queries siempre eh tenido el mismo inconveniente.

**Comment by lhchavez** [comment]
estás subiendo el .zip con un archivo `testplan`? parece que los casos no están concordando exactamente con el nombre de los archivos (e.g. hay un archivo `01.in`, pero parece que el testplan dice que el archivo se llama `1`, sin el cero).

Creo que necesitamos hacer que el validador sea un poco más robusto.

**Comment by galloska** [comment]
Si, tiene un archivo testplan. No me habia percatado de eso, ya que el testplan lo estoy generando de manera automatica y quito los ceros por alguna razon. Ya corregi el error y ahora si termina de evaluar los problemas. 

Creo que solo habria que checar que los archivos mencionados en el testplan existan en el directorio.

**Comment by lhchavez** [comment]
> Creo que solo habria que checar que los archivos mencionados en el testplan existan en el directorio.

sí, eso es justo lo que estoy haciendo ahorita.
