### ISSUE TITLE
Ver soluciones de algunos problemas causan timeouts persistentes

### ISSUE THREAD

**Issue by Arthusr56** [omegaup/omegaup#2923]
Buenos dias, mando este mensaje para mencionar unos problemas que me he encontrado en la pagina de omegaup.

Ultimamente el sistema de omegaup ha tenido un comportamiento extraño, y estoy seguro que le ha pasado a otras personas. En el pasado he resuelto ciertos problemas de los cuales por ciertas razones las decidi reenviar el problema mismo. 
Pero por alguna razon que desconozco, la solucion que reenvio ya no me da "AC", si no que me da algun otro mensaje como "PA" o "TLE".

Tambien tengo que mencionar que para ciertos problemas me he encontrado con otro inconveniente. Un ejemplo en mi caso es el problema de "Espanglish".
He querido visualizar la solucion correcta que mande para ese problema, pero la plataforma simplemente no la carga.
Si intento refrescar la pagina, me sale el mensaje "504 Gateway Time-Out", y no importa cuantas veces refresco la pagina despues de eso, el mismo mensaje me sigue saliendo.

Ya me percate de que debo cerrar el navegador entero y abrirlo otra vez para que omegaup responda nuevamente, pero aun estan los otros inconvenientes.

Les agredeceria mucho si pudieran resolver mi problema actual con la pagina.

**Comment by lhchavez** [comment]
La primera parte es https://github.com/omegaup/omegaup/issues/1884 entonces este issue sólamente se va a enfocar en el error 504.

Esto está muy raro, porque el error 504 persiste aún intentando visitar otras partes de la página en esa misma sesión O_O

**Comment by lhchavez** [comment]
al parecer la sesión (de PHP) tiene algo que ver: esto sólo se puede reproducir si se manda el cookie con el `PHPSESSID`. únicamente usamos la sesión para mostrar un par de alertas y hacer login usando inkedin/facebook.

posiblemente sea buena idea cambiar la manera en la que se guardan las sesiones en el disco para evitar esto.
