### ISSUE TITLE
Reducir considerablemente la cantidad de puntos que obtienes por resolver tus propios problemas

### ISSUE THREAD

**Issue by Vented5** [omegaup/omegaup#2928]
*Hola, me encuentro aquí para hacer una propuesta como creador de problemas.*

Recientemente comencé apoyar a la olimpiada de mi estado, sin embargo me he dado cuenta de que resolver problemas hechos por ti te proporcionan una gran cantidad de puntos en el ranking global.
Sin mencionar los muchos problemas en la plataforma que solo tienen un envío correcto (hecho por el creador del problema).
Considero que esto no es justo debido a que el creador conoce la solución del problema, poniendo en desventaja a los demás participantes.

Propongo reducir considerablemente la cantidad de puntos por resolver tus problemas.

*Gracias por su atención equipo  de OmegaUp.*

**Comment by lhchavez** [comment]
@wkoder se quejó de esto hace poco. según yo le estábamos dando *cero* puntos a los autores, pero al parecer esto no es cierto ^^;;

**Comment by wkoder** [comment]
Deberia dedicarme al QA! :P Concuerdo al 100%, creadores no deberian obtener ningun punto por resolver su problema. Estoy convencido ya hay mucha gente explotando esto, como comente offline :)

PD. Me di cuenta de esto porque observe gente "notoria" agregando problemas muy muy faciles que ellos mismos resolvian, incluso repetidos, y se podia notar no era solo para "probarlos".

**Comment by pabloaguilar** [comment]
Considerablemente seríaa creo, vdd? No creo por qué un autor debería ganar puntos por sus propios problemas.

Y si es así, tiene dueño el issue? Necesito puntos para mí camiseta

**Comment by lhchavez** [comment]
ahora el dueño eres tú. y sí, debería ser cero si eres dueño.
