### ISSUE TITLE
Eliminar escuelas duplicadas, preservando sus relaciones

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#2932]
Al buscar una escuela para el perfil de usuario, el autocomplete presenta dos problemas.
1. Se repiten los nombres de las escuelas, pero tiene diferente ID
2. No muestra todas las sugerencias que regresa el payload

![index](https://user-images.githubusercontent.com/13296248/66548632-807c6080-eaf6-11e9-998c-66b878f67ef8.jpg)

Se probó en chrome y firefox.

**Comment by carlosabcs** [comment]
Según veo, esto se debe a que fueron creados múltiples registros para una misma escuela.
@lhchavez esto debería tratarse con una migración?

**Comment by lhchavez** [comment]
sí, pero hay que tener cuidado porque las primeras dos escuelas de ese screenshot sí están duplicadas de verdad, pero las demás son distintas.

también, se podrá separar el issue en dos para atacar cada problema por separado?

**Comment by carlosabcs** [comment]
Hay que validar también que no se guarden más escuelas con nombres repetidos. Más tarde creo los issues.

**Comment by carlosabcs** [comment]
@tvanessa podemos renombrar esto a: "Eliminar escuelas duplicadas, preservando sus relaciones"?
