### ISSUE TITLE
Mostrar badges en escala de grises cuando no se han obtenido

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#2934]
Actualmente se muestra una silueta completamente negra:
<img width="835" alt="Screen Shot 2019-10-11 at 4 05 15 PM" src="https://user-images.githubusercontent.com/597815/66689769-276d1380-ec41-11e9-9b04-fda4020c9bdf.png">

Seria mejor mostrarlos en escala de grises para que el usuario tenga por lo menos una idea de como se ven y para que los usuarios con muchos badges los puedan "lucir" mejor.

**Comment by lhchavez** [comment]
esto sale fácil con [`filter: grayscale(100%)`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) en CSS. pero creía que esto era una decisión consciente de parte de @carlosabcs .

**Comment by carlosabcs** [comment]
De todas maneras esto no altera la idea de "bloqueado/desbloqueado", así que prefiero implementarlo.
