### ISSUE TITLE
El boton de "Back" no funciona al ver un problema desde la lista de problemas

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2941]
*Como un usuario que quiere practicar, quiero poder leer un problema para decidir si quiero intentarlo, y regresar a la lista de problemas si decido que no*

## Comportamiento Esperado

Darle click al boton de "Back" inmediatamente despues de entrar a leer un problema desde la lista de problemas deberia llevarme de regreso a la lista de problemas

## Comportamiento Actual

"Back" me deja en la vista de problema.
Creo que porque al entrar al ver un problema se cambia el hash inmediatamente y se hace de manera que si crea una entrada nueva en el history stack, y entonces back me lleva a la vista que inmeditamente lleva al hash, dejandome atorado ahi.

## Posible Solución

Asegurarnos que la solucion de "Back" en concursos funcione tambien en la vista de un solo problema

## Pasos para reproducir (para bugs)

1. Entrar a omegaup.com
2. Ir a "Problemas"
3. Dar click a algun problema
4. Dar click al boton "Back"
5. Observar que el navegador no cambia de pagina

## Contexto

No puedo regresar a la lista de problemas con un click en "Back" tengo que dar long click y regresar a dos posiciones atras.

## Tu ambiente

* Chrome 77
* Windows 10

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/2046
