### ISSUE TITLE
Deshabilitar transformaciones a los casos de entrada

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#2947]
Hola amigos de OmegaUp.

Estaba revisando el problema https://omegaup.com/arena/problem/Compresion-de-cadenas/#problems donde los casos de entrada originales tienen cadenas en ASCII extendido (en pocas palabras, algunos bytes tienen bit más significativo prendido y la cadena no es UTF8). Aunque antes el problema funcionaba bien, ahora encuentro que los casos de entrada fueron modificados (posiblemente algún utf8_encode o algo así) y que si los vuelvo a subir, OmegaUp les vuelve a meter mano.

¿Podrían agregar alguna manera de deshabilitar eso? De rápido, no encuentro una manera que me satisfaga de darle la vuelta.

**Comment by lhchavez** [comment]
welp, el hecho de que antes funcionara bien es un error porque siempre hemos estado haciendo (o al menos intentando hacer) normalización a UTF-8.

pero el problema está bien formado y la petición suena válida. esto va a tomar un poco de tiempo y quizás sólo lo permitamos para tu problema (o sea que no tendría opción en la interfaz) porque la cantidad de archivos subidos accidentalmente con mal encoding excede por mucho la cantidad de problemas que se benefician de poder subir archivos binarios.

**Comment by darkmx** [comment]
Se me ocurre que se deshabilitaran las transformaciones si la cosa tiene un validador personalizado. Casi todos los problemas son de comparación token a token; los validadores suenan a que algo especial se está haciendo (mi problema tiene validador, por lo de la cadenota).

**Comment by lhchavez** [comment]
igual con los validadores personalizados no tienes garantía de que fue la intención del autor subirlo con mal encoding.

**Comment by darkmx** [comment]
Eso sí :(

**Comment by darkmx** [comment]
Hola de nuevo, me puse a chambear un poco y ya le di la vuelta a la normalización (básicamente genero casos donde todo es o será UTF-8 válido). Un poquitín tedioso porque no cualquier cosa es UTF-8 válido, pero ya quedó :)

Aunque en este momento ya no sea necesario, muchas gracias por considerar hacer una excepción con el problema que subí. Espero no hacer cosas raras en problemas futuros.

**Comment by lhchavez** [comment]
oh! qué bien que pudiste resolver el problema :D
