### ISSUE TITLE
[FEATURE] Paginar las tablas de problemas resueltos e intentos y concursos en perfil del usuario

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#2948]
Hay usuarios con muchos problemas resultos e intentos, asi como concursos, y se scrollea mucho para llegar a las demas secciones.
![Screen Shot 2019-10-15 at 12 29 36 PM](https://user-images.githubusercontent.com/13296248/66863409-c8144980-ef47-11e9-9c17-ffd10ad9d074.png)
![Screen Shot 2019-10-15 at 12 29 48 PM](https://user-images.githubusercontent.com/13296248/66863416-cba7d080-ef47-11e9-8a0b-c84f7e560877.png)
![Screen Shot 2019-10-15 at 12 30 07 PM](https://user-images.githubusercontent.com/13296248/66863432-d2364800-ef47-11e9-9b77-0b11f572da79.png)

**Comment by carlosabcs** [comment]
Este issue ya puede cerrarse @tvanessa
