### ISSUE TITLE
Actualizar Google Analytics de ga.js a analytics.js

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#2951]
*Como desarrollador quiero asegurarme de usar la versión actual de Google Analytics*

## Comportamiento Esperado

Usar la biblioteca de Google Analytics recomendada por la documentación de Google:
https://developers.google.com/analytics/devguides/collection/analyticsjs

## Comportamiento Actual

Seguimos utilizando ga.js, que según su documentación, ya no debería ser utilizado.
https://developers.google.com/analytics/devguides/collection/gajs

## Posible Solución

Seguir las instrucciones aqui:
https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs

**Comment by pabloaguilar** [comment]
Donde creamos google-analytics.js? Es a patita en el ambiente de prod?

**Comment by lhchavez** [comment]
sí :S pero no deberíamos. hay que meterlo a git y quitarlo de .gitignore

**Comment by pabloaguilar** [comment]
Gracias! Ahorita mando la actualizacion a `analytics.js`
