### ISSUE TITLE
[BUG] El tab Top coder monthly list solo muestra un usuario 

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#2973]
El tab *Top coder monthly list* solo muestra un usuario y deberia mostrar una lista
![Screen Shot 2019-10-22 at 12 28 31 AM](https://user-images.githubusercontent.com/13296248/67265577-ef48aa80-f462-11e9-96d6-543a8d43777a.png)

**Comment by carlosabcs** [comment]
@tvanessa, en ese tab qué debería salir? La lista de todos los usuario que han sido nombrados Coders del Mes, por ejemplo en noviembre? Es decir: coder de noviembre-2019, noviembre-2018, noviembre-2017...?

**Comment by tvanessa** [comment]
No, lo que yo entiendo es que ahi va el top de usuarios del mes, es decir, los primeros K lugares del ultimo mes. Vi que se agrego en este PR https://github.com/omegaup/omegaup/pull/1938
