### ISSUE TITLE
[FEATURE] Cambiar el formato de la duración de un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#2976]
Actualmente se muestra en días, horas, minutos, segundos.
![Screen Shot 2019-10-23 at 11 15 13 PM](https://user-images.githubusercontent.com/13296248/67458562-5d1fde00-f5eb-11e9-9dc9-00db4ac07bd0.png)

Lo ideal seria cambiarlo a años, meses y días (4 años 6 meses 4 días)

**Comment by lhchavez** [comment]
con tiempos mayores a ~1 mes, posiblemente sea bueno usar tiempo difuso en vez de dar cuentas exactas, porque especificarlo a nivel de días quizás es demasiada precisión. librerías como https://momentjs.com/ pueden ayudar a eso.

**Comment by pabo99** [comment]
Suena bien lo de la librería, y con la condición que indicas (tiempos mayores a ~1 mes) sólo se estaría utilizando en los cursos.

Faltaría revisar si es necesario validar que si un curso es público no tome en cuenta la hora de finalización de las tareas. O en su defecto, cuando un curso es público se pueda editar desde la interfaz gráfica esta opción (tanto al curso cómo a las tareas).

Por cierto, aún no he encontrado (desde la UI) la forma de hacer público un curso, ¿Esta acción la realiza un rol en específico? o ¿Se realiza directamente en la base de datos?

**Comment by heduenas** [comment]
@pabo99 hasta donde entiendo tienes que llamar el `api/course/update/` con parámetros `'course_alias=introduccion_a_cpp&name=Curso+de+Introducci%C3%B3n+a+C%2B%2B&description=Curso+de+Introducci%C3%B3n+a+C%2B%2B&start_time=1574413440&finish_time=1581148799.999&alias=introduccion_a_cpp&show_scoreboard=false&needs_basic_information=false&requests_user_information=no&school_id=3170&public=true'` (por ejemplo). El `public=true` de al final es el que lo hace público. Necesitas llamarlo identificado como site admin.

**Comment by tvanessa** [comment]
@pabo99 voy a cambiar la descripción del issue para que este cambio sea para todos los cursos, no solo los públicos
