### ISSUE TITLE
No permite actualizar un problema

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#2984]
Al intentar actualizar un problema no envía ningún mensaje, sin embargo en la consola del navegador aparecen errores.

## Comportamiento Esperado

Actualizar el problema

## Comportamiento Actual

No importa la actualización que quieras hacer, no te permite hacerla. No envía mensajes de error o algún mensaje.

Este mensaje aparece en la consola:

![image](https://user-images.githubusercontent.com/6465292/67580780-871cf180-f70c-11e9-9e00-7786e5cd09e7.png)

## Pasos para reproducir (para bugs)

1. Abre cualquier problema
2. Intenta actualizar
3. No lo hace.

## Contexto

Mucho, siempre es necesario hacer actualizaciones.

## Tu ambiente

Cualquier sistema operativo.

**Comment by lhchavez** [comment]
logs:

```
t=2019-10-25T14:09:43+0000 lvl=eror msg="push failed" path=/var/lib/omegaup/problems.git/La-escalera-del-seg
undo-piso-III err="bad-request: restricted-ref" stack="[github.com/omegaup/gitserver.(*zipUploadHandler).Ser
veHTTP(github.com/omegaup/gitserver/ziphandler.go:1604) main.(*muxGitHandler).ServeHTTP(omegaup-gitserver/ma
in.go:93)]" errstack="\ngithub.com/omegaup/githttp.(*GitProtocol).PushPackfile\n\t/home/ubuntu/go/omegaup/gi
thttp/protocol.go:235\ngithub.com/omegaup/gitserver.PushZip\n\t/home/ubuntu/go/omegaup/gitserver/ziphandler.
go:1303\ngithub.com/omegaup/gitserver.(*zipUploadHandler).ServeHTTP\n\t/home/ubuntu/go/omegaup/gitserver/zip
handler.go:1588\nmain.(*muxGitHandler).ServeHTTP\n\t/home/ubuntu/go/omegaup/gitserver/cmd/omegaup-gitserver/
main.go:93\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).
serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:
1357"
```

parece que faltó pasarle una bandera al gitserver después de la actualización de ayer

**Comment by lhchavez** [comment]
se le hizo revert a esa actualización. ya debería permitirte actualizar problemas.

**Comment by kukogit** [comment]
Efectivamente, ya se puede. Pero cualquier cosa que pase, les aviso.

**Comment by lhchavez** [comment]
sí, muchas gracias!

**Comment by kukogit** [comment]
Ya volvió pasar!!!

**Comment by kukogit** [comment]
Es exactamente el mismo error!!!

**Comment by lhchavez** [comment]
qué problema es? qué estabas intentando hacer? (actualizar problema o redacción?)

**Comment by kukogit** [comment]
La redacción

**Comment by lhchavez** [comment]
qué problema es? puedes intentar de nuevo?

**Comment by kukogit** [comment]
Ya funcionó

**Comment by kukogit** [comment]
Y qué fue lo que pasó?

**Comment by lhchavez** [comment]
se estaban regresando menos privilegios para usuarios que contuvieran puntos :(
