### ISSUE TITLE
[BUG] Problema actualizar tiempo tarea dentro de la escuela

### ISSUE THREAD

**Issue by Seasmoster** [omegaup/omegaup#2987]
## Comportamiento Esperado

Al actualizar el tiempo de termino de una tarea, la tarea permitiara realizar envio normalmente

## Comportamiento Actual

SI modificamos el tiempo de termino de una tarea, se queda con el tiempo anterior a pesar de haber actualizado la tarea con un tiempo mayor, mostrarno un error de que el tiempo ha termino al realizar el envio. Tengo una imagen para la mostrar el error.

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

1. Crear una escuela normal
2. Agregar una tarea con problema con una fecha x (termine rapido), actualizar la fecha de la tarea.
3. Error se presentara.

## Contexto

*Cómo te ha afectado este issue?
Afecta que tengo que crear una copia igual de la tarea con tiempo mayor al deseado, en vez de actualizar la tarea si es requerido a lo que yo necesite.
 Cuál es el objetivo a cumplir?*
La tarea se peude modificar, si se termino el tiempo, extender el tiempo y pueden subir las soluciones a los problemas lo alumnos.

## Tu ambiente

El error se creo al impartir un taller de preparacion de profesora de la olimpiada mexicana de informatica Baja California. Se creeo una escuela para que lo maestro reolvieran problema, al querer ampliar el tiempo, a los maestros les aparece el error de que el tiempo termino.

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
* Link al sitio en el que este problema pasa: https://omegaup.com/course/TCO/edit/#edit
* Errores en la consola: []
* Captura de pantalla: https://drive.google.com/file/d/1TG7eU2zQDjFlOQbK8VWFndt9UC1VDvCP/view?usp=sharing

**Comment by lhchavez** [comment]
puedes grabar un video de cuando estás editando la fecha de la tarea? no logro reproducir este error y hay gente que reporta que esto ocurre sólo a veces.

**Comment by tvanessa** [comment]
Duplicado de #3029
