### ISSUE TITLE
[FEATURE] Poder embeber videos en la descripción de un problema

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3000]
También en las soluciones.

**Comment by lhchavez** [comment]
posiblemente haya que actualizar el whitelist: https://github.com/omegaup/omegaup/blob/769d8ed8c40f85bfecb5196824dea1fa568c36d7/frontend/www/js/omegaup/ui.js#L611

puedes poner un ejemplo de markdown necesario para embeber un video?

**Comment by tvanessa** [comment]
Se tiene que hacer con html
```
<figure class="video_container">
  <iframe src="https://www.youtube.com/embed/enMumwvLAug" frameborder="0" allowfullscreen="true"> </iframe>
</figure>
```
[https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#videos](https://about.gitlab.com/handbook/product/technical-writing/markdown-guide/#videos)

**Comment by tvanessa** [comment]
@carlosabcs puedes revisar que este cambio funciona en lecturas y problemas en cursos?
