### ISSUE TITLE
[FEATURE] Botón para dar seguimiento entre assignments

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3004]
Como participante de un curso con múltiples assignments, cuando completas un assignment el flujo para ir al siguiente assignment es complicado. Debería haber un botón que te invite a ir al siguiente; en especial porque el botón de back no siempre funciona.

**Comment by lhchavez** [comment]
esto suena razonable, pero el botón de back deberíamos arreglarlo de cualquier manera.

puedes abrir otro bug nada más para eso?

**Comment by tvanessa** [comment]
Ya hay dos: [2046](https://github.com/omegaup/omegaup/issues/2046) y [2941](https://github.com/omegaup/omegaup/issues/2941). Para diferentes contextos los discutimos en uno mismo o que se abran varios issues?

**Comment by lhchavez** [comment]
ah dices tú como participante? si sí, entonces es exactamente lo mismo que https://github.com/omegaup/omegaup/issues/2046 y podemos usar ese. si es como profesor, entonces mejor crea uno nuevo porfa.

**Comment by pabo99** [comment]
La propuesta es agregar un link en la parte inferior derecha que te lleve a la siguiente tarea, se vería algo así:

![next_assignment](https://user-images.githubusercontent.com/3230352/71216651-abb2c700-2280-11ea-8550-4eba00ad5fd6.png)

¿Está bien o existe otra propuesta?

**Comment by heduenas** [comment]
Mejor hay que ponerlo justo debajo de la lista de problemas:

![image](https://user-images.githubusercontent.com/597815/71219614-9044bd80-227a-11ea-9065-47b3540e367b.png)

**Comment by lhchavez** [comment]
me gusta la propuesta de @heduenas porque pone toda la navegación entre los problemas en el mismo lugar. eso es bueno estructuralmente para los componentes y cognitivamente para los usuarios.

**Comment by pabo99** [comment]
Perfecto, incluiré el botón de anterior y el de siguiente. 

Sólo una duda: ¿los botones se deben mostrar en todas los problemas? o ¿sólo en el primer problema se muestra el botón de anterior y en el último problema se muestra el botón de siguiente?

**Comment by lhchavez** [comment]
para facilitar el despliegue, muéstralos siempre pero deshabilítalos si no es posible ir al anterior y/o al siguiente.

**Comment by lhchavez** [comment]
aumentando el tiempo porque hay que vueificar cosas.
