### ISSUE TITLE
[omegaUp Escuelas] Las explicaciones/descripciones no deberían mostrar puntaje

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3009]
En un curso, cuando hay una descripción/explicación de un tema (i.e. un problema que no permite enviar soluciones), se muestra el valor de esa tarea. Pero no hay forma de ganar puntos por leerla.
![Screen Shot 2019-10-30 at 12 00 51 AM](https://user-images.githubusercontent.com/13296248/67836402-c3a07280-faa9-11e9-8eae-d434b07a327e.png)

**Comment by carlosabcs** [comment]
Esto involucra determinar si una tarea es **realmente** una tarea o es una explicación, verdad? De ser así, los cambios deberían partir desde acá: https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L40

Y posiblemente hayan varias cosas más qué considerar, como agregar explicaciones de manera separada a tareas y exámenes.

**Comment by lhchavez** [comment]
no es necesario cambiar el esquema! si la lista de lenguajes permitidos está vacía, es una explicación.

**Comment by carlosabcs** [comment]
Y donde se agregan esas explicaciones? Porque yo supuse que era en la descripción de una tarea, pero me parece que no.

Y aquí tampoco
![image](https://user-images.githubusercontent.com/20785082/67872558-21f84000-fb00-11e9-893d-25afffbcd6ed.png)

**Comment by lhchavez** [comment]
es un problema normal, común y corriente. lo único es que cuando creas ese problema, en el conjunto de lenguajes permitidos elijes ninguno y listo! por convención, ese problema ahora "es una explicación".

**Comment by carlosabcs** [comment]
Ahora sí entendí!
