### ISSUE TITLE
[FEATURE] Enviar invitación a usuarios a través de una URL para agregarse a un curso en escuelas. Como un Docente, quiero tener la capacidad de poder enviar una url para que se agreguen usuarios para facilitar el proceso de inscripción de varios alumnos a escuelas.

### ISSUE THREAD

**Issue by LaloRivero** [omegaup/omegaup#3013]
Enviar invitación a usuarios a través de una URL para agregarse a un curso en escuelas

Como un Docente, quiero tener la capacidad de poder enviar una url para que se agreguen usuarios para facilitar el proceso de inscripción de varios alumnos a escuelas.

## Comportamiento Esperado

Tener la capacidad de mandar una URL de invitación o un código de clase a los estudiantes y que por si solos dando click y confirmando su usuario de omegaup puedan registrarse en un dado curso en escuelas.

## Comportamiento Actual

Se tiene que agregar usuario por usuario, primero se registran los alumnos, después el alumno tiene que hacer llegar el usuario al admin del curso en escuelas. Detalle importante que los estudiantes comenten muchos errores en este proceso y se hace un proceso largo y poco eficiente.

## Posible Solución

Implementación de una URL de invitación como los grupos en redes sociales o código de clase como en algunas plataformas educativas ejemplo: google classroom.

## Alternativas consideradas

*Opcional, si has pensado en alternativas para solucionar este problema y las has descartado, nos gustaría también escucharlas.*

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

Docente de educación media superior que  utiliza OmegaUp como principal herramienta en clase. Objetivo: Agilizar el proceso de registro por parte de los estudiantes y de manera mas practica.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Opera:
* Windows 10:

**Comment by pabo99** [comment]
La propuesta es reutilizar en lo posible la funcionalidad de `Concursos abiertos con registro`.

Para esto serán necesarias por parte del profesor las siguientes acciones; 
- Proporcionar la `URL` del curso a los usuarios que desea invitar. El método de envío (vía correo electrónico, redes sociales, whats app, etc.) es elección del mismo profesor. 
- Dar de alta el curso con la opción de: `Con registro` (o algún texto similar)

Con estas dos acciones los alumnos deberían ser capaces de acceder directamente al curso con la URL sin necesidad de ser invitados como ocurre hasta el día de hoy.

 A su vez, el profesor puede aprobar/rechazar las solicitudes que le aparezcan en la vista de _Cursos > Estudiantes_.

Algo así:

El profesor da de alta el curso _Abierto con registro_
![image](https://user-images.githubusercontent.com/3230352/73864683-b06b1480-4807-11ea-92d9-e57407f47a8c.png)

El estudiante ingresa a la URL del curso proporcionada por el profesor
![image](https://user-images.githubusercontent.com/3230352/73864850-edcfa200-4807-11ea-88ac-7cdb9c67edb8.png)

El estudiante da clic en _Registrarse en el curso_
![image](https://user-images.githubusercontent.com/3230352/73864883-fa53fa80-4807-11ea-8939-e0aa180b0992.png)

El profesor puede aceptar / rechazar las solicitudes de los estudiantes
![image](https://user-images.githubusercontent.com/3230352/73865135-6cc4da80-4808-11ea-8adc-009ef161def9.png)

![image](https://user-images.githubusercontent.com/3230352/73865292-a4cc1d80-4808-11ea-8853-db5b0055b84b.png)

Sólo los usuarios que fueron aprobados por el profesor podrán acceder al curso.
