### ISSUE TITLE
Bug en fechas.

### ISSUE THREAD

**Issue by Alpier** [omegaup/omegaup#3016]
## Comportamiento Esperado

Se espera que al dar clic en "Editar perfil" la fecha de nacimiento y de graduación se represente de la forma *MM/DD/AAAA* (que es la forma de input).

## Comportamiento Actual

Al dar clic en "Editar perfil" las fechas cambian de la forma *MM/DD/AAAA* a la forma *DD/MM/AAAA*, lo que provoca que al intentar guardar cambios salte un globito que dice "Parámetro inválido: birth_date" o "Parámetro inválido: graduation_date".

## Posible Solución

Es sólo cambiar la forma de la fecha al mostrártela.

## Pasos para reproducir (para bugs)

1. Iniciar sesión.
2. Ir al perfil.
3. Ir a editar perfil.
4. Ver el cambio de forma en la fecha (de *MM/DD/AAAA* a *DD/MM/AAAA*)

## Contexto

Es molesto que se haya que cambiar la fecha cada vez que editas algo de tu perfil.

## Tu ambiente

* Nombre del navegador: Firefox 70.0.1 64-bit
* Sistema Operativo y versión (escritorio o móvil): Mac OS X El Capitán (he verificado el bug en macOS Mojave)
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/edit/
* Captura de pantalla:
![Screenshot_2019-11-01 Perfil – omegaUp](https://user-images.githubusercontent.com/56698888/68039427-180a4480-fc9a-11e9-9b55-dcbac946fc17.png)

**Comment by carlosabcs** [comment]
@lhchavez, esto tiene relación con #2998 también, y según vi, tiene que ver con el [`toLocaleString`](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/ui.js#L489), que usamos para que las fechas se vean en el formato de acuerdo al país de origen.

Según yo, hay dos opciones (estuve trabajando en la primera):
- Dejar que `formatDate` siga cambiando la forma en que se muestran las fechas en estos inputs, pero asegurar que no hayan problemas a la hora de actualizar los datos, por ejemplo, guardando la fecha oficial como atributo `data-date` y usando ese valor a la hora de hacer `update`.

- Hacer una función análoga a `formatDate` => `formatGenericDate`, que no varíe en base `T.locale` sino que se mantenga igual, y usarlo en estos inputs.

**Comment by lhchavez** [comment]
me gusta más la primera opción!

**Comment by carlosabcs** [comment]
> me gusta más la primera opción!

Me acabo de dar cuenta de que no será posible :(
Aún si creara un evento para actualizar `data-date` junto a `$('#graduation_date).val()`, no existe en javascript la contraparte de `toLocaleString` que vendría a ser `fromLocaleString`.

Me parece que solo queda la segunda opción, a no ser que tengas otra idea.

**Comment by Alpier** [comment]
Yo no sé mucho de esto, pero, ¿qué no se supone que no debería de ocurrir el bug teniendo una variable ```mes``` y ```dia```, por ejemplo?
Me refiero a que, lo muestre como lo muestre, al guardarse ```mes``` seguiría siendo igual, análogamente para ```dia```.

**Comment by lhchavez** [comment]
> Yo no sé mucho de esto, pero, ¿qué no se supone que no debería de ocurrir el bug teniendo una variable `mes` y `dia`, por ejemplo?
> Me refiero a que, lo muestre como lo muestre, al guardarse `mes` seguiría siendo igual, análogamente para `dia`.

eso es más complicado que lo que quiere hacer @carlosabcs porque internamente las fechas son un sólo número (segundos desde medianoche enero 1, 1970 UTC).

> > me gusta más la primera opción!
> 
> Me acabo de dar cuenta de que no será posible :(
> Aún si creara un evento para actualizar `data-date` junto a `$('#graduation_date).val()`, no existe en javascript la contraparte de `toLocaleString` que vendría a ser `fromLocaleString`.
> 
> Me parece que solo queda la segunda opción, a no ser que tengas otra idea.

creo que lo que tenemos que hacer es obtener la fecha del datepicker antes de que la convierta en cadena. si ese datepicker no permite hacerlo, quizás sería buen momento para considerar usar un componente Vue para eso, lo cual simplificaría muchas cosas.

**Comment by carlosabcs** [comment]
Creo que este issue ya puede ser cerrado, fue tratado en #3038
