### ISSUE TITLE
El tiempo limite de los envios no puede ser agregado de la manera correcta.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#3023]
## Comportamiento Esperado

Necesito ingresar un tiempo determinado entre envios. 

## Comportamiento Actual

No se puede agregar un tiempo estimado entre envios. 

## Pasos para reproducir (para bugs)

1. Crear un concurso
2. Otorgar un tiempo entre envios
3. Guardar concurso

## Contexto

Se requiere crear un concurso con un intervalo entre envios de un minuto.

##Solución

Al parecer solo es cambiar de minutos a segundos.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome ultima version a la fecha.
* Sistema Operativo y versión (escritorio o móvil): Mac Os
* Link al sitio en el que este problema pasa: https://omegaup.com/contest/new/
* Captura de pantalla: 
![image](https://user-images.githubusercontent.com/5459260/68092701-77f81b00-fe53-11e9-84b3-c77ece5544f1.png)

**Comment by MiguelRomero** [comment]
@lhchavez  Creo que debería ser de alta prioridad esta semana tenemos varios concursos para la preseleccion de IOI

**Comment by Alpier** [comment]
Yo creé un concurso hace tiempo y me encontré con eso mismo, hasta donde indagué, me dí cuenta de que la input es en segundos aunque diga minutos.

**Comment by MiguelRomero** [comment]
> Yo creé un concurso hace tiempo y me encontré con eso mismo, hasta donde indagué, me dí cuenta de que la input es en segundos aunque diga minutos.

Thanks a lot!
