### ISSUE TITLE
[Badge Proposal] Perfil actualizado

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#3024]
# Contenido

Este es el template para la propuesta de insignias en omegaUp, asegúrate de haber leído las consideraciones a tener en cuenta para proponer una insignia: [Guía para proponer insignias](https://blog.omegaup.com/guia-para-la-propuesta-de-insignias-en-omegaup/).

## ¿Cuál es el nombre de la insignia que propones?
Perfil actualizado

## ¿Qué debe haber realizado un usuario para recibir esta insignia?
El usuario ha actualizado (y completado) su perfil en omegaUp.

## ¿Esta insignia tiene un ícono personalizado?
Aún no

## (Opcional) Si tienes una idea de cómo implementar la consulta y prueba unitaria para esta insignia, puedes ingresarla acá:

La consulta debe verificar que los campos correspondientes a los datos de perfil de usuario en las tablas `Users` e `Identity`, llenos.

Para la prueba se deben crear dos usuarios, el primero no debe tener los campos de perfil de usuario completos, el otro sí.

**Comment by Alpier** [comment]
Me gusta la idea, considero que vendría bien que a nuevos usuarios que no hayan completado su perfil les salte un prompt de "completa tu perfil" o algo así.
Me explico con un ejemplo: Un usuario se crea su cuenta, hace cosas y cierra sesión, luego inicia sesión y sale un prompt de que actualice o complete su perfil.

**Comment by carlosabcs** [comment]
> Me gusta la idea, considero que vendría bien que a nuevos usuarios que no hayan completado su perfil les salte un prompt de "completa tu perfil" o algo así.
> Me explico con un ejemplo: Un usuario se crea su cuenta, hace cosas y cierra sesión, luego inicia sesión y sale un prompt de que actualice o complete su perfil.

También está en discusión hacer algo parecido :D
