### ISSUE TITLE
No puedo hacer un envío a cierto problema

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#3026]
Traté de entrar al problema https://omegaup.com/arena/problem/lacasadesolidnieves#problems/new-run; no obstante me aparece el texto "error" en la pantalla. Además, el botón de "Nuevo envío" no funciona. Dentro de un curso (https://omegaup.com/course/PES-2020/assignment/PES-grafos#problems/lacasadesolidnieves), el LaTeX no se renderiza bien.

Background: Es uno de los problemas para el PES de IOI 2020.

Firefox 69.0.1 imprime el siguiente texto en la consola:

```
Unhandled exception  TypeError: "e.querySelector(...) is null"
    renderSampleToClipboardButton commons.js:1
    renderSampleToClipboardButton commons.js:1
    value commons.js:1
    onlyProblemLoaded contest.js:10
    <anonymous> contest.js:118
    value commons.js:1
    _notify commons.js:1
    _initialize commons.js:1
    jQuery 2
        j
        k
```

Si bien podría haber un error en el problema, el contenido se puede leer por lo que OmegaUp no debería bloquear los envíos.

**Comment by lhchavez** [comment]
Efectivamente era un error en el problema: el que lo subió metió markdown manualmente de tal manera que estaba interfiriendo con el código para copiar el caso de ejemplo.

Ya quedó arreglado.
