### ISSUE TITLE
[BUG] Algunos problemas de Escuela no aceptan envíos

### ISSUE THREAD

**Issue by jofeque** [omegaup/omegaup#3029]
## Comportamiento Esperado

Que un Curso donde un usuario tiene derechos, permita que se envíen soluciones a todos los problemas del Curso

## Comportamiento Actual

Cuando un usuario se logea y entra a un Curso de Escuelas, intenta enviar una solución a un problema y la página (OmegaUp) le manda un mensaje de que el **El concurso ya teminó o aún no empieza**

## Pasos para reproducir (para bugs)

1.  Logearse
2. Ir al Curso de Escuelas
3.  Seleccionar un problema
4. Hacer un envío
5. Se muestra el mensaje de  **El concurso ya teminó o aún no empieza**

## Contexto

- Ya se revisó la hora de la computadora y está bien
- Un usuario se logea en esa misma computadora y si puede hacer envíos, otros usuarios no

## Tu ambiente

* Nombre del navegador Chorme
* Sistema Operativo y versión (escritorio o móvil): Windows 10 y en el Android
* Link al sitio en el que este problema pasa: https://omegaup.com/course/CHH19CB3/assignment/H2#problems/Recogiendo-a-lo-mas-10-beepers
* Captura de pantalla:
![WhatsApp Image 2019-11-05 at 09 17 35](https://user-images.githubusercontent.com/33610618/68225143-34192900-ffad-11e9-99f0-3dd9bfc684b8.jpeg)

**Comment by LaloRivero** [comment]
Tengo el mismo error y es recurrente

**Comment by jofeque** [comment]
Hola
Creo que ya se donde está el "error". Cuando se crea un Curso en Escuelas, las fechas de inicio y fin de cada Assignment se definen y se bloquean y no pueden modificarse, aunque uno edite la Tarea/Examen; como ya se guardó el periodo en que se podía enviar y por eso nos envía el mensaje de **Contest time has expired or not started yet**
Es decir, es problema de fecha y no de que el problema esté privado o el usuario no tenga derechos de enviar

**Comment by lhchavez** [comment]
puedes grabar un video intentando modificar las fechas de una tarea? ya van varios reportes que nos hacen de esto pero no logramos reproducirlo nosotros, y se arregla modificando la fecha de la tarea :S 

lo que sospecho es que la interacción con el seleccionador de fecha/hora sea el factor que cambia entre cuando nosotros lo intentamos y ustedes lo hacen.

**Comment by kukogit** [comment]
Sigue pasando!!! D:

**Comment by kukogit** [comment]
Inicialmente le había puesto a una tarea que se acabara el 16/11/19 a las 16:15 mas o menos. Pero luego la cambie al 30/11/19 y después de que la primera hora indicada, ya no quiso recibir envíos.

**Comment by lhchavez** [comment]
sí, sabemos que le sigue pasando a algunas personas, pero no sabemos _por qué a nosotros no_. @kukogit tú puedes ayudarnos con https://github.com/omegaup/omegaup/issues/3029#issuecomment-554560549 ?

**Comment by LaloRivero** [comment]
![escuelas](https://user-images.githubusercontent.com/39440542/69372050-3393ba00-0c5e-11ea-9aa8-d67020d5f758.png)

 Se acabo el tiempo de envíos para esa tarea

![cambio](https://user-images.githubusercontent.com/39440542/69372075-427a6c80-0c5e-11ea-902a-cc5fd4c8000e.png)

Se le agrego mas tiempo

![cambio_error](https://user-images.githubusercontent.com/39440542/69372382-d51b0b80-0c5e-11ea-9382-bc75f5415dec.png)

Manda ese mensaje de error

**Comment by kukogit** [comment]
> sí, sabemos que le sigue pasando a algunas personas, pero no sabemos _por qué a nosotros no_. @kukogit tú puedes ayudarnos con [#3029 (comment)](https://github.com/omegaup/omegaup/issues/3029#issuecomment-554560549) ?

Te refieres a lo del video?

**Comment by jofeque** [comment]
Hola
Como aún no está solucionado el #3077, no he podido generar evidencia para publicarla y que se analice
:)

**Comment by jofeque** [comment]
Existe uno en https://omegaup.com/course/CHH19CB3, donde el usuario javier24vega11/javiervega2411 (usuario/contraseña) tiene derechos, él no puede hacer envíos, en ningún problema, de la **Práctica A** que se vence el **31 de diciembre de 2019**. Al momento de hacer un envío la página indica que **El concurso ya terminó o aún no empieza.**

**Comment by kukogit** [comment]
Esto aun no jala, cierto?

**Comment by heduenas** [comment]
cierto

**Comment by heduenas** [comment]
Esto sucede con todos los estudiantes inscritos al concurso o solamente con algunos?

**Comment by heduenas** [comment]
@jofeque, se sigue reproduciendo este problema?

Hice login con la cuenta que mencionas y aparece que el usuario ya resolvió todos los problemas de la práctica A.

**Comment by kukogit** [comment]
Sucede con todos los alumnos que ya estaban registrados, pero si registras a un alumno después de cambiarle la fecha a una tarea, ese alumno si puede hacer envíos.

Es algo bastante raro.

**Comment by jofeque** [comment]
> @jofeque, se sigue reproduciendo este problema?
> 
> Hice login con la cuenta que mencionas y aparece que el usuario ya resolvió todos los problemas de la práctica A.

Pero @heduenas el Curso de Escuelas se termina el 1 de enero de 2020, y la Práctica A se termina el 30 de diciembre de 2019; es decir, aún tiene tiempo de hacer envíos. 
Pero, si el usuario en cuestión desea hacer más envíos en la Práctica A (que está vigente en cuanto a las fecha de vencimiento), **no puede hacer más envíos** porque sale el mensaje de **El Concurso ya terminó o aún no empieza**

Ese es el problema. Como ya tenemos un Curso de Escuelas y un usuario, se podrá hacerle un debug de que es lo que está pasando.

**Comment by heduenas** [comment]
@lhchavez tienes identificada la causa de este bug?

**Comment by lhchavez** [comment]
@heduenas no :(

**Comment by lhchavez** [comment]
esto ya lleva abierto demasiado tiempo, hay que ver cómo hacerle para arreglarlo

**Comment by heduenas** [comment]
Tienes bandwidth para atenderlo tu?

**Comment by lhchavez** [comment]
no inmediatamente. desasignándome.

**Comment by lhchavez** [comment]
Creo que la primer pista para encontrar cómo reproducirlo es lo que dijo @kukogit en https://github.com/omegaup/omegaup/issues/3029#issuecomment-565902844: el comportamiento es distinto cuando se registra un alumno después de cambiar la fecha. entonces _puede ser_ que sea el caso que cuando se cambia la fecha de fin, eso interactúa de manera extraña con los tiempos diferidos (https://github.com/omegaup/omegaup/issues/2081) y luego al entrar a https://github.com/omegaup/omegaup/blob/36f2a912727b82daef7ffd05c314b4d529fa48d4/frontend/server/src/DAO/Problemsets.php#L58-L65 eso causa la excepción porque el objeto del usuario con el tiempo diferido no se actualizó.

@heduenas puedes asignar este issue a alguien que pueda atenderlo de inmediato?
