### ISSUE TITLE
[BUG] OmegaUp no deja bajar librerías de libinteractive (Error 404)

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#3032]
Problemas:

https://omegaup.com/arena/problem/Cables-Cruzados#problems
https://omegaup.com/arena/problem/jarras#problems
https://omegaup.com/arena/problem/donCarlos/#problems

No importa la combinación que pongas en el selector de libinteracive, manda error 404

https://omegaup.com/templates/Cables-Cruzados/7680d6817de38b0c66b14d610397b96f63869a55/Cables-Cruzados_unix_c.tar.bz2
https://omegaup.com/templates/Cables-Cruzados/7680d6817de38b0c66b14d610397b96f63869a55/Cables-Cruzados_windows_cpp.zip

**Comment by darknut** [comment]
Solo revisé esos tres, es posible que esté roto en general

**Comment by lhchavez** [comment]
ya quedó listo. hacía falta regenerar los artefactos de algunos problemas de libinteractive con las nuevas versiones de los problemas.
