### ISSUE TITLE
[BUG] Login via Facebook dejó de funcionar

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3035]
## Comportamiento Esperado

Hacer login con mi usuario via Facebook.

## Comportamiento Actual

El intento de login me da el siguiente error:
![image](https://user-images.githubusercontent.com/207097/68319785-b409c680-0073-11ea-8036-9f9bae98fe92.png)
`Cross-site request forgery validation failed. Required param "state" missing from persistent data.`

## Posible Solución
No he investigado D: 

## Pasos para reproducir (para bugs)

1.  omegaUp.com -> Login
2. Click en el botón de Facebook 

## Tu ambiente

* Nombre del navegador : Chrome Version 78.0.3904.70 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): MacOS Mojave
* Link al sitio en el que este problema pasa: omegaUp.com/login
* Captura de pantalla:  (arriba)

**Comment by Alpier** [comment]
Hola, Joe.
Confirmo el bug para Firefox 70.0.1 en macOS

**Comment by Davidxp2002** [comment]
Hola, Si el problema persiste en Google Chrome Versión 78.0.3904.97 (Build oficial) (64 bits).
Igual el mismo BUG.
En Windows 10.
