### ISSUE TITLE
[BUG] Mensaje de error al subir casos y tamaño máximo

### ISSUE THREAD

**Issue by rccuam** [omegaup/omegaup#3037]
Hola amigos de OmegaUp.

Estoy tratando de subir un caso gigantesco (260MB descomprimido) y OmegaUp me pone el mensaje "Hubo un problema interno al momento de intentar actualizar el problema." En https://github.com/omegaup/omegaup/blob/master/frontend/templates/es.lang encontré que tienen un mensaje explícito para violaciones al _max_size_ pero ése no es el mensaje que aparece. Mi reporte de bug iría en ese sentido (si el problema es el tamaño, el mensaje no es el que se tenía pensado que apareciera; si el problema es otro entonces habría que checar) y mi pregunta va en el sentido de si en verdad hay un máximo (en https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-escribir-problemas-para-omegaUp sugiere mantenerlo debajo de los 100MB pero dice que no hay tope real; posiblemente en la práctica sí haya alguno, pues el mensaje que está en el template me hace pensar eso).

El problema en cuestión es el https://omegaup.com/problem/Busqueda-sobre-un-archivo-v2/

**Comment by lhchavez** [comment]
oh! efectivamente ese tamaño no está soportado, y creo que la propagación del error real no está funcionando correctamente :S

**Comment by RuizYugen** [comment]
@lhchavez  cual es el tamaño máximo soportado?

**Comment by RuizYugen** [comment]
ya para recrear el issue?

**Comment by darkmx** [comment]
por búsqueda binaria encontré que es como 100MB

**Comment by lhchavez** [comment]
sigamos la sugerencia de la documentación: mantenerlo por debajo de 100M. no quiero divulgar el límite real porque luego es difícil bajar ese límite a algo más razonable u_u
