### ISSUE TITLE
Buscador de problemas no puede encontrar problemas

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#3062]
Este query:
https://omegaup.com/problem/?query=areas+Metropolitanas&language=all&order_by=title&mode=asc

No puede encontrar este problema:
https://omegaup.com/arena/problem/omi-2019-areas-metropolitanas/#problems

Que antes funcionaba bien.

**Comment by MiguelRomero** [comment]
https://omegaup.com/arena/problem/Karel-y-Gretel#problems <- Problema que presenta condición.

**Comment by darknut** [comment]
Tampoco funciona cuando quieres agregar problemas a concursos:
![image](https://user-images.githubusercontent.com/123875/69031999-5426f000-0990-11ea-9ce0-221ca6d7be03.png)
![image](https://user-images.githubusercontent.com/123875/69032013-5ee18500-0990-11ea-9298-78ed3c73fb72.png)
