### ISSUE TITLE
[BUG] Los administradores no pueden bannear problemas de la cola quality nominations

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3066]
Se intentó bannear un problema (se verificó que no estuviera ya banneado) y se mostró el error: `There was an internal problem in handling the problem update.: forbidden`

![screenshot](https://user-images.githubusercontent.com/597815/69000042-60228d00-087e-11ea-9a43-e11f3276c78f.png)

**Comment by pabo99** [comment]
Parece que ese mensaje tiene mas que ver con el `ProblemDeployer`. Estoy probando con problemas que tengo en mi ambiente local y si funciona correctamente.

**Comment by tvanessa** [comment]
@pabo99 Joe si pudo suspender problemas, y es site admin. Lo probaste con los dos usuarios en tu ambiente local?

**Comment by pabo99** [comment]
Esa información me será de utilidad. Deja hago pruebas con estos casos para ver si puedo reproducirlo

**Comment by pabo99** [comment]
El error se da en la petición `curl_exec` en `ProblemDeployer` L402.

Esto es lo que obtengo en el `stack trace`:

```
2019-12-03T21:49:26+00:00 [ERROR]: 5de6d866bf28a050130483 /api/qualityNomination/resolve/ update zip failed: {"retval":1,"output":"{\n\t\"status\": \"error\",\n\t\"error\": \"forbidden\",\n\t\"updated_files\": null\n}\n"} OmegaUp\Exceptions\ProblemDeploymentFailedException: problemDeployerInternalError in /opt/omegaup/frontend/server/src/ProblemDeployer.php:457
Stack trace:
#0 /opt/omegaup/frontend/server/src/ProblemDeployer.php(98): OmegaUp\ProblemDeployer->execute('/opt/omegaup/fr...', 'test_user_5', 'banningProblemD...', Array, NULL, 'ours', false, true, true)
#1 /opt/omegaup/frontend/server/src/Controllers/Problem.php(934): OmegaUp\ProblemDeployer->commit('banningProblemD...', Object(OmegaUp\DAO\VO\Identities), 0, Array)
#2 /opt/omegaup/frontend/server/src/Controllers/Problem.php(861): OmegaUp\Controllers\Problem::updateProblem(Object(OmegaUp\Request))
#3 /opt/omegaup/frontend/server/src/Controllers/QualityNomination.php(522): OmegaUp\Controllers\Problem::apiUpdate(Object(OmegaUp\Request))
#4 [internal function]: OmegaUp\Controllers\QualityNomination::apiResolve(Object(OmegaUp\Request))
#5 /opt/omegaup/frontend/server/src/Request.php(63): call_user_func('\\OmegaUp\\Contro...', Object(OmegaUp\Request))
#6 /opt/omegaup/frontend/server/src/ApiCaller.php(77): OmegaUp\Request->execute()
#7 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): OmegaUp\ApiCaller::httpEntryPoint()
#8 {main} (/opt/omegaup/frontend/server/src/ProblemDeployer.php:462)
```

Parece ser un problema de permisos.

**Comment by lhchavez** [comment]
oh! en efecto! algunas cosas:

* estamos llamando APIs desde un API, lo cual complica un poco las cosas.
* al momento de actualizar el problema (dentro de `Problem::apiUpdate`) para los casos en los que no hay que involucrar al `ProblemDeployer` (porque no cambian las redacciones, los casos, o la configuración del grader), deberíamos omitir esa llamada.
