### ISSUE TITLE
[Badge Proposal] Experto en {lenguaje de programación}

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3067]
## ¿Cuál es el nombre de la insignia que propones?
Experto en {c, cpp, java, python ,ruby, pearl, C#, pascal, Karel, lua, etc}

## ¿Qué debe haber realizado un usuario para recibir esta insignia?
El usuario resolvió más de 10 problemas en {c, cpp, java, python ,rugby, pearl, C#, pascal, Karel, lua, etc}

## Si tienes una idea de cómo implementar la consulta y prueba unitaria para esta insignia, puedes ingresarla acá:

La tabla `Submissions` tiene el campo `language`.

**Comment by heduenas** [comment]
Reabriendo porque aún faltan varios lenguajes

**Comment by lhchavez** [comment]
te late mejor cerrar este y abrir uno por lenguaje?

**Comment by heduenas** [comment]
Va pues
