### ISSUE TITLE
[FEATURE] Eliminar u ocultar definitivamente los tags que ponen los usuarios con sus votaciones

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#3069]
## Comportamiento Esperado

Tener la libertad de elegir que tags se queda o no en un problema de mi autoría.

## Comportamiento Actual

No se pueden eliminar ni ocultar.

## Alternativas consideradas

Permitir eliminarlas u ocultar. O mejor que sólo ciertos usuarios puedan hacerlo, aquellos que hayan demostrado que tienen un compromiso por etiquetar bien un problema.

## Contexto

Al desplegar mis problemas, y buscar por tags, se complica porque los usuarios asignan tags de manera aleatoria y con total descuido a los tags correctos.

## Tu ambiente

En cualquier ambiente.

**Comment by kukogit** [comment]
Esto ya es posible? Es bastante molesto que la gente taguee un problema de Karel diciendo que son arreglos o cadenas.

**Comment by kukogit** [comment]
Y es molesto porque lo hacen con mis problemas

**Comment by tvanessa** [comment]
Poner un checkbox en la edición del problema que indique si el autor quiere mostrar los tags de los usuarios.
Si es el caso, no mostrar ningun tag de los usuarios.
![Screen Shot 2020-04-06 at 4 59 43 PM](https://user-images.githubusercontent.com/13296248/78616255-9c07c000-7828-11ea-8b51-a869b4330fdf.png)
