### ISSUE TITLE
[BUG] El componente para administrar cursos tarda por siempre en cargar / no carga.

### ISSUE THREAD

**Issue by LaloRivero** [omegaup/omegaup#3077]
## Comportamiento Esperado

Al querer agregar alumnos a un curso en escuelas, la plataforma no lo permite, no aparecen los alumnos antes registrados y se congela la pantalla junto con el cursor. Pareciera que esta cargando pero no pasa nada.

## Comportamiento Actual

Se congelo la pantalla al momento de querer agregar nuevos alumnos en el apartado de escuelas

## Pasos para reproducir (para bugs)

1. Entrar a escuelas 
2. Seleccionar un curso
3. Dar click en agregar un nuevo estudiante

**Comment by LaloRivero** [comment]
Checando el mismo bug, lo que sucede es que tarda demasiado en cargar (algunos minutos). Verifique con diferentes redes de Internet y parece que no hay diferencia alguna. Sigue siendo el mismo tiempo de demora

![BUG](https://user-images.githubusercontent.com/39440542/69168255-9b59d180-0ab3-11ea-8581-df61998223d9.png)

**Comment by jofeque** [comment]
Hola
Al parecer no se puede conectar a facebook (de manera interna); en la parte inferior del navegador indica **esperando a facebook.com** al tratar de editar un Curso de Escuelas.

**Comment by jofeque** [comment]
Bug corregido
:)

**Comment by LaloRivero** [comment]
Parece que tiene este error todo lo referente a un administrador en Escuelas, agregar nuevas tareas, problemas, alumnos se congela por un rato y aveces te regresa a la pagina anterior
![image](https://user-images.githubusercontent.com/39440542/69286051-81051e00-0baf-11ea-9eb9-424e186c2a6f.png)

**Comment by lhchavez** [comment]
puede alguien intentar abrir la consola de JavaScript y ver qué errores salen ahí? si no, pueden crear un [HAR file](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-Network-Captures-for-Troubleshooting/ta-p/366) y mandárnoslo a soporte@omegaup.com? (eso va a contener las cookies que mandaron al sitio y sería mejor no divulgarlas por aquí).

**Comment by LaloRivero** [comment]
Esto es lo que arroja la consola

`JQMIGRATE: Migrate is installed, version 3.0.1
/course/CHH20PS1/edit/#students:1 

A cookie associated with a cross-site resource at http://www.facebook.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

/course/CHH20PS1/edit/#students:1 A cookie associated with a cross-site resource at http://twitter.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

/course/CHH20PS1/edit/#students:1 A cookie associated with a cross-site resource at https://nr-data.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by LaloRivero** [comment]
Esto es lo que arroja al querer editar un curso en escuelas

`JQMIGRATE: Migrate is installed, version 3.0.1
(index):1 A cookie associated with a cross-site resource at http://www.facebook.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
(index):1 A cookie associated with a cross-site resource at https://nr-data.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2vue.common.prod.js:6 The specified value "999-12-31" does not conform to the required format, "yyyy-MM-dd".
ni @ vue.common.prod.js:6
S @ vue.common.prod.js:6
(anonymous) @ vue.common.prod.js:6
e._update @ vue.common.prod.js:6
n @ vue.common.prod.js:6
pr.get @ vue.common.prod.js:6
pr.run @ vue.common.prod.js:6
dr @ vue.common.prod.js:6
(anonymous) @ vue.common.prod.js:6
Ze @ vue.common.prod.js:6
Promise.then (async)
Ge @ vue.common.prod.js:6
tt @ vue.common.prod.js:6
(anonymous) @ vue.common.prod.js:6
pr.update @ vue.common.prod.js:6
de.notify @ vue.common.prod.js:6
set @ vue.common.prod.js:6
fr.set @ vue.common.prod.js:6
(anonymous) @ edit.js:569
j @ jquery-3.2.1.js:7331
k @ jquery-3.2.1.js:7365
setTimeout (async)
(anonymous) @ jquery-3.2.1.js:7381
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
fire @ jquery-3.2.1.js:7208
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
f.<computed> @ jquery-3.2.1.js:7422
(anonymous) @ api.js:19
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
A @ jquery-3.2.1.js:10252
(anonymous) @ jquery-3.2.1.js:10252
load (async)
send @ jquery-3.2.1.js:10252
ajax @ jquery-3.2.1.js:10252
e.ajax @ jquery-migrate-3.0.1.min.js?ver=0ff315:80
(anonymous) @ api.js:9
(anonymous) @ edit.js:564
value @ omegaup.js:57
_notify @ omegaup.js:184
(anonymous) @ omegaup.js:176
j @ jquery-3.2.1.js:7331
k @ jquery-3.2.1.js:7365
setTimeout (async)
(anonymous) @ jquery-3.2.1.js:7381
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
fire @ jquery-3.2.1.js:7208
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
f.<computed> @ jquery-3.2.1.js:7422
(anonymous) @ api.js:19
i @ jquery-3.2.1.js:7132
fireWith @ jquery-3.2.1.js:7206
A @ jquery-3.2.1.js:10252
(anonymous) @ jquery-3.2.1.js:10252
load (async)
send @ jquery-3.2.1.js:10252
ajax @ jquery-3.2.1.js:10252
e.ajax @ jquery-migrate-3.0.1.min.js?ver=0ff315:80
(anonymous) @ api.js:9
_initialize @ omegaup.js:164
on @ omegaup.js:188
596 @ list.js:6
a @ bootstrap:79
r @ bootstrap:45
t @ bootstrap:32
(anonymous) @ universalModuleDefinition:11
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
(index):1 A cookie associated with a cross-site resource at http://twitter.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by LaloRivero** [comment]
Existen diversos errores en este video se visualizan. @lhchavez @MiguelRomero @joemmanuel 
https://drive.google.com/file/d/1lQSGVhNGv5VIh119dGf6vr3ErHAouVvS/view?usp=sharing

**Comment by heduenas** [comment]
Como workaround, si esperas lo suficiente (unos 60 segundos en mi computadora), el componente termina de cargar y es funcional. Eso observe por lo menos en el navegador Brave en Linux.
