### ISSUE TITLE
[FEATURE] Links en markdown del problema deberían de abrirse en un nuevo tab

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3078]
Ahorita se abren en el mismo tab.

**Comment by antedotee** [comment]
I think the problem still persists.Can you assign this issue to me?

**Comment by antedotee** [comment]
i cleared the coding round of omegaup.Can you assign this issue to me now?

**Comment by pabo99** [comment]
> i cleared the coding round of omegaup.Can you assign this issue to me now? my omegaUp username is noob101

Could you please begin resolving the first issue I assigned to you? We will have other candidates searching for issues, so we need a pool to assign them.

**Comment by MayaSatishRao** [comment]
@pabo99 I didn't understand the issue completely. What do you mean by markdown in problem. Can you provide any screenshots?

**Comment by pabo99** [comment]
Sure, you can test in the URL used in the animation:

![LinkInProblemMarkdown](https://github.com/omegaup/omegaup/assets/3230352/819c0645-a388-47cf-9dbb-a989e90e4a3a)

**Comment by Aritra8438** [comment]
Interesting! Can you assign this issue to me?
