### ISSUE TITLE
[Escuelas] Informar a los usuarios sobre cómo funciona el nuevo ranking de escuelas.

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#3080]
Como parte del desarrollo del proyecto de Escuelas: perfil y ranking, se cambiará la manera en que el ranking es calculado. Además, cada envío que realicen los usuarios, ahora tiene asociado el `id` de la escuela a la que actualmente está asociado. Ya existe una migración que agregó ese campo y lo rellenó también: https://github.com/omegaup/omegaup/pull/3052

Lo que propongo en este issue es:
- Informar a los usuarios que todos sus envíos realizados hasta antes de una fecha determinada (en el futuro), se asociarán a la escuela que poseen actualmente, y que en adelante, cada envío que hagan estará asociado a su escuela actual. Así ellos tendrán tiempo de actualizar su escuela para poderle dar el puntaje correspondiente a la escuela correcta (en caso tengan mal seleccionada o sin seleccionar su escuela actual). Podemos informarle a los usuarios a través de media posts y también a través de una pestañita en su próximo inicio de sesión (así como cuando se le informa al nuevo coder del mes que ha sido seleccionado).
- En una fecha determinada en el futuro, y ya con los usuarios con sus escuelas actualizadas, re-inicializar todos los valores de `school_id` en `Submissions`.

**Comment by joemmanuel** [comment]
@MiguelRomero FYI ^

**Comment by tvanessa** [comment]
https://blog.omegaup.com/el-nuevo-ranking-de-escuelas-de-omegaup/
