### ISSUE TITLE
[BUG] Cuando se está creando un problema "Sin envíos", desactivar los campos exclusivos de problemas con envíos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3086]
![image](https://user-images.githubusercontent.com/597815/69411184-51ded180-0cc1-11ea-9c7e-25555e839bc5.png)

Cuando se elije "Sin envíos" se deben de desactivar todos los campos mostrados en el screenshot. (Excepto "Lenguajes")

**Comment by pabo99** [comment]
Este cambio requerirá migración del componente a `vue`. Así que será necesario incrementar el tiempo
