### ISSUE TITLE
[BUG] OmegaUp Escuelas no permite modificar cursos recién creados o clonado

### ISSUE THREAD

**Issue by eloisagc** [omegaup/omegaup#3092]
## Comportamiento Esperado

Poder modificar un curso recién creado o clonado en OmegaUp Escuelas

## Comportamiento Actual

No permite modificar el curso recién creado o clonado en OmegaUp Escuelas. La página se queda colgada mucho tiempo cuando trato de editar el curso.

<img width="880" alt="Screen Shot 2019-11-22 at 20 51 04" src="https://user-images.githubusercontent.com/6990253/69473926-0f73ce00-0d6f-11ea-84dc-966b158b9a09.png">

Cuando finalmente carga la página no permite hacer nada y se vuelve a quedar colgada.

<img width="454" alt="Screen Shot 2019-11-22 at 19 56 30" src="https://user-images.githubusercontent.com/6990253/69473924-097ded00-0d6f-11ea-93de-2a6c05ae510e.png">

## Contexto

Hemos estado toda la tarde intentando dar de alta los cursos para los talleres de la OMIBC. Urge solución por favor

## Tu ambiente
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Mac Os  X Catalina

También probamos con Firefox y Explorer en Windows y nada :(

**Comment by pabo99** [comment]
Dupe of #3081 

Parece que los dos son ocasionados por el mismo problema. Ya se atendió
