### ISSUE TITLE
[FEATURE] Explicar el significado de los colores de los tags en la lista de problemas.

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3095]
Aclarar la distinción entre tags propuestos por los usuarios y los del dueño.

![Screen Shot 2019-11-23 at 1 33 35 AM](https://user-images.githubusercontent.com/13296248/69476667-96d23900-0d91-11ea-9c3b-684696e54291.png)

**Comment by carlosabcs** [comment]
Tienes alguna propuesta de cómo deberíamos hacer esto?
Se me ocurre dos rectangulitos uno azul y otro gris, y a lado de cada uno "etiquetas del autor", "etiquetas de los usuarios"

**Comment by carlosabcs** [comment]
PING!
Creo que puedo hacer esto antes de acabar este internship.
Esto va a ser necesario ya que estoy introduciendo los tags de categoría (de calidad), por lo que ya tendráimos 3 colores distintos.
Me parece que también se puede poner un tooltip para que cuando el usuario pose el clic encima del tag, se describa de qué tipo es.

**Comment by heduenas** [comment]
(Discuiendo offline)
