### ISSUE TITLE
Problem deployment no soporta carpetas intermedias 

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#310]
Algunos zips vienen con una carpeta intermedia entre las carpetas de /cases y /statements, por ejemplo /problema/cases y /problema/statements. Dado que es muy común, en caso de falla por el primer método, hay que intentar entrar a la primer carpeta y de ahí hacer el deployment.
En caso de falla hay que dar un error descriptivo y loggear con detalles.

**Comment by lhchavez** [comment]
Ya logramos que la gente no se equivoque tan seguido al subir problemas, y además ya mejoramos bastante los errores en el problemdeployment, así que ya no es _tan_ urgente hacer esto. Pero si alguien quiere invertir tiempo en un feature peque, lo dejaré abierto con el tag de help wanted.

**Comment by elendil326** [comment]
@lhchavez Esto lleva abierto dos años y no sé que tan aplicable siga siendo. Cerration?

**Comment by lhchavez** [comment]
no: es parte de mejorar la experiencia de los usuarios. seguido se queja la raza de esto.

**Comment by lhchavez** [comment]
Cerrando porque mejor se va a arreglar con el revamp de cómo se guardan los problemas en backendv2.
