### ISSUE TITLE
[FEATURE] Tener opción de mostrar casos fallados al enviar solución

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3102]
Para cursos sería útil poder mostrar a los usuarios la entrada y salida de los casos que sus códigos fallaron. 

Para no afectar el ranking, esto debería de darse como una opción a la hora de crear/editar un problema, de manera que la habilidad de ver los casos sea igual para todos y no sólo para los que están en un curso que tiene el problema.

**Comment by tvanessa** [comment]
Duplicado de #1998
