### ISSUE TITLE
El sistema no esta permitiendo editar cursos

### ISSUE THREAD

**Issue by ucancih** [omegaup/omegaup#3103]
## Comportamiento Esperado
Realizo diferentes acciones permitidas en el menú "Escuelas" sección de "Edición de cursos": Editar el curso, Tareas, Problemas, Estudiantes, Administradores, Clonar. 

## Comportamiento Actual

Ingreso al sistema, menú Escuelas, selecciono uno de mis cursos y luego "clic" en el botón "Editar curso" y hasta ahí se queda, los datos de la página no cargan y no permite realizar las acciones de edición ya mencionadas. He probado con diferentes navegadores y computadoras; el comportamiento es el mismo.

## Pasos para reproducir (para bugs)
Ingreso al sistema
Menú Escuelas
Selecciono uno de mis cursos
"Clic" en el botón "Editar curso" 
¡Hasta aquí se queda!

## Contexto
Mi objetivo principal es asignar tareas, problemas y exámenes a mis grupos, y ello no se puede realizar.

## Tu ambiente

Firefox Browser 70.0.1 (32-bit)
Windows 7 Ultimate Service Pack 1
https://omegaup.com/course/fpitc19B/edit/#problems

* Captura de pantalla:
![omegaup](https://user-images.githubusercontent.com/58175358/69544639-2298c080-0f5e-11ea-8047-c1a796fb443a.jpg)

**Comment by heduenas** [comment]
Vamos a hotfixear este fix? El bug ya lleva mas de una semana y esta afectando por lo menos a varios profesores.

**Comment by lhchavez** [comment]
sí, ya está en producción.
