### ISSUE TITLE
[FEATURE] Correr script de migración de canonicalizacion de tags

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3108]
Correr el script https://github.com/omegaup/omegaup/blob/master/stuff/canonicalize_tags.py en producción para arreglar las etiquetas capturadas en la base de datos.

**Comment by carlosabcs** [comment]
ping @lhchavez

**Comment by heduenas** [comment]
ping @lhchavez para ya terminar el proyecto canonicalización de tags :)
