### ISSUE TITLE
[BUG] Falla de seguridad que permite ver información de scoreboard, incluso cuando este esta oculto

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#3116]
## Comportamiento Actual
Cuando se hace una peticion GET al link: https://omegaup.com/api/user/conteststats/ con sesión iniciada, te da un JSON que incluye información de cada concurso al que el usuario ha participado.
Creo que el campo scoreboard_url_admin no debería aparecer, pues permite observar el scoreboard de un concurso y lo que permite realizar trampas en este, pues puedes identificar que problemas resuelve la gente y así elaborar una mejor estrategia que los demás.

## Posible Solución

No dar tanta informacion en el GET 

## Pasos para reproducir (para bugs)
Con sesion iniciada entras a  https://omegaup.com/api/user/conteststats/ 

## Contexto

Hace mucho dejo de funcionar la opción de ver concursos en los que uno ha participado, queriendo ver si era un error visual, me fije en las peticiones GET que hacia para ver si podía recuperar la información de allí. (También quería aprender a hacer una extensión de chrome, e iba hacer una que arreglara eso).
Pero me encontré con la información extra.

Hace meses reporte este problema por Facebook, pero luego me entere de que necesitas reportar los errores por GitHub y que la página de FB no es necesariamente atendida por ustedes.

**Comment by lhchavez** [comment]
welp, gracias por reportar esto!
