### ISSUE TITLE
[BUG] No permite actualizar los casos de un problema

### ISSUE THREAD

**Issue by LaloRivero** [omegaup/omegaup#3120]
## Comportamiento Esperado

Poder modificar o actualizar los casos de un problema propio.
 
## Comportamiento Actual

Al re subir el .zip manda error
Internal Server Error
**Failed to load resource: the server responded with a status of 500 ()**

## Pasos para reproducir (para bugs)

1.  Entrar a mis problemas
2.  Seleccionar el problema y presionar el icono para editar
3.  Seleccionar el archivo .zip
4.  Escribir la descripción del cambio
5. Presionar el botón de actualizar problema

## Contexto

No puedo actualizar mis problemas, para corregir los casos

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Opera
* Windows 10
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/39440542/69753621-3df7fd00-1111-11ea-88ff-512f6abb7170.png)

**Comment by LaloRivero** [comment]
@miguelomega @MiguelRomero

**Comment by pabo99** [comment]
@LaloRivero, ¿Tienes identificado en que problemas te aparece este error o te sucede con todos?

**Comment by LaloRivero** [comment]
Son problemas que subí hace poco tiempo, dos en particular que son los últimos.

**Comment by lhchavez** [comment]
@LaloRivero tienes los links a los problemas? así no tenemos que andar adivinando a cuáles te refieres.

**Comment by pabo99** [comment]
@LaloRivero ¿Me puedes apoyar con una captura de pantalla de la configuración de tu problema (Cualquiera de los dos que reportaste está bien)?

**Comment by LaloRivero** [comment]
![image](https://user-images.githubusercontent.com/39440542/74202802-bd826c00-4c2a-11ea-85b4-8eacede6a693.png)

**Comment by pabo99** [comment]
Gracias, seguiré intentando reproducir el bug.

En caso de requerir más información te lo hago saber.

**Comment by pabo99** [comment]
@LaloRivero se acaba de subir un cambio que permite mostrar un mensaje de error cuando se edita un problema. ¿Puedes subir nuevamente el archivo zip con los casos actualizados? Para ver si aún te marca error. Ahora ya no debería de mandarte la pantalla de Internal Server Error.

**Comment by LaloRivero** [comment]
Listo @pabo99 ya se pudieron actualizar los casos con éxito, si me marco un error en el testplan que ya pude corregir con éxito, gracias.
