### ISSUE TITLE
[FEATURE] Minimizar la posibilidad de ser Coder del Mes resolviendo problemas triviales

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3132]
## Comportamiento Esperado

Que el Coder del Mes reconozca a los usuarios que resuelven problemas retadores más que a los que resuelven (muchos) más problemas (muy) fáciles.

## Comportamiento Actual
Los puntos de ranking que otorga cada problema dependen inversamente del número de soluciones aceptadas. (https://github.com/omegaup/omegaup/blob/fa9c4d93899bdcaa154c565d8e1cf4e95e8ec964/stuff/cron/update_user_rank.py#L87) 
Algunos usuarios están abusando de este mecanismo resolviendo problemas fáciles poco descubribles o muy nuevos que son muy fáciles y pocas personas los han intentado. 

## Posible Solución
Después de una discusión en slack, hay dos propuestas:

* *Corto plazo / parche*: Contar un problema para ranking sólo si el número de usuarios distintos que han intentado el problema es mayor a N, y/o que el número de usuarios distintos que hayan resuelto el problema sea mayor a K. Se sugiere empezar con N>3. ([personal]: intuitivamente yo sugeriría un prior de N>10, K>5, haciendo una pasada rápida por el último coder del mes esto quitaría muchos problemas triviales repetidos).

* *Largo plazo*: En el mundo ideal, sólo problemas con distintivo de calidad deberían contar para el ranking.

## Alternativas consideradas
Contar a lo mas N problemas de cada bucket de dificultad. Esto se puede implementar una vez que tengamos una masa crítica de problemas de calidad y los usuarios no puedan engañar al sistema haciendo parecer un problema fácil cuando no lo es simplemente por hacerlo poco descubrible.

## Contexto
Anectódicamente creemos que los coders del mes de los últimos 1 o 2 años han ganado resolviendo un gran volumen de problemas triviales.

**Comment by lhchavez** [comment]
sigo pensando que limitar la cantidad de problemas en cada bucket de dificultad es injusto y no está resolviendo los dos problemas de raíz:

* algunos problemas tienen una dificultad artificialmente inflada.
* los problemas fáciles contribuyen un peso excesivo al ranking.

**Comment by carlosabcs** [comment]
Así como existe: `p.accepted` para contar la cantidad de `AC`'s submissions. Puede existir `solvers_count` para tener el número de usuarios que han resuelto un problema?

**Comment by lhchavez** [comment]
veo que hay un PR abierto, pero falta avisarle a la gente!

se puede escribir un blogpost y agregar un enlace al carrusel del homepage?

**Comment by tvanessa** [comment]
La idea es prender el crobjob en enero, pero queremos tenerlo listo pronto.
También esperamos primero dar publicidad a las nuevas colecciones y luego a las nuevas reglas de coder del mes

**Comment by pabo99** [comment]
@tvanessa, veo que ya hay un PR abierto (#4949), Además del Blog Post, falta algo más en ese PR?

**Comment by tvanessa** [comment]
@pabo99 es PR 4949 es respecto al ranking general. 
Necesitamos modificar el coder del mes. El blog post se necesita hasta que se prenda el cronjob. Si le dan merge a tu cambio no se prende el cronjob.

**Comment by pabo99** [comment]
La consulta en la función `update_coder_of_the_month_candidates` ya también cuenta con el filtro de problemas de calidad. De hecho se agregó en el PR #4975 y ese ya está aprobado. ¿Qué más le faltaría e este issue?
