### ISSUE TITLE
[FEATURE] Mostrar el mejor diagnóstico en caso de error

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3141]
Hola amigos de OmegaUp.

Cuando un problema tiene varios casos y el alumno se equivoca de mil y un maneras (algunos casos los tiene mal, en otros su programa truena, en los más grandes tiene TLE) al usuario sólo se le muestra un diagnóstico (me parece que el del último caso).  Desafortunadamente, esto da pie a que el alumno crea que su programa "sólo es lento, pero está bien" y no se percata que tiene que revisar con cuidado otras partes (por ej. si tiene 30% TLE, a veces creen que todo el faltante es por TLE cuando en realidad 50% del faltante es WA y 20% del faltante es TLE).

Propongo darle un orden total a los diagnósticos, de modo de que sólo le aparezca el más representantivo. El orden que propongo a continuación lo obtuve de la serie de preguntas:

![imagen](https://user-images.githubusercontent.com/19719969/70349867-3f20dc80-182b-11ea-9652-31e2845ceee3.png)

En _templates/es.lang_ encontré otros veredictos y calculé el siguiente orden ya contemplando todos los mensajes (no estoy muy seguro de poner "Salida límite excedida" ahí, pero es un diagnóstico raro de todos modos).

```
verdictJE = "Error del juez (no reenviar)"
verdictCE = "Error de compilación"
verdictFO = "Error de ejecución (función restringida)"
verdictRFE = "Error de ejecución (función restringida)"
verdictRE = "Error de ejecución"
verdictRTE = "Error de ejecución"
verdictOL = "Respuesta incorrecta (límite de salida excedido)"
verdictOLE = "Respuesta incorrecta (límite de salida excedido)"
verdictWA = "Respuesta incorrecta"
verdictPA = "Respuesta parcialmente correcta"
verdictML = "Límite de memoria excedido"
verdictMLE = "Límite de memoria excedido"
verdictTLE = "Tiempo límite excedido"
verdictTO = "Tiempo límite excedido"
verdictAC = "Respuesta correcta"
```

Entiendo que este cambio, tiene prioridad muy baja. Lo publico para que luego no se me olvide la idea :P

Saludos!

**Comment by tvanessa** [comment]
Este es el orden que manejamos ahorita:
```
JE
CE
RFE
RTE
MLE
OLE
TLE
WA
PE
PA
AC
```

Y este es el orden que tú propones (falta acomodar PE)
```
JE
CE
RFE
RTE
OLE
WA
PA
MLE
TLE
AC

```

Fuera de MLE y TLE coinciden los demas.
@lhchavez tú estás de acuerdo en hacer este cambio considerando el contexto que da Rodrigo?

Por otra lado, cambiar esto es tan sencillo como cambiar el orden aqui:

https://github.com/omegaup/backend/blob/e3ca6bcf4fffb9949698e2fffe456fd316885551/common/src/main/scala/com/omegaup/data/Types.scala#L41

**Comment by lhchavez** [comment]
lamentablemente el cambio no es viable :( MLE, TLE, RFE y sus amigos interrumpen la ejecución inmediatamente y no reportan la solución parcial porque estaría malformada de cualquier manera.

un ejemplo es `printf(3)` en C y `std::cout` en  C++. por default esos dos usan un line buffer cuando se conectan a una consola, pero en el ambiente del grader envían su salida a un archivo, y se bufferean bastante (~1k, y mucha gente sabe que hay que mantener ese buffer y evitar operaciones que le hacen flush, como `std::endl`). cualquiera de esos errores se reportaría como WA porque muy posiblemente no habría nada en la salida, y se perdería información que hoy en día se obtiene!

otra manera de pensarlo es cambiando la serie de preguntas a:

* el programa compiló? si no, CE
* el programa ejecutó una función restringida? si sí, RFE
* el programa teminó de ejecutarse correctamente? si no, uno de RTE, TLE, MLE, OLE (depende qué límite excedió)
* el programa obtuvo al menos un caso correcto? si no, WA
* el programa obtuvo todos los casos bien? si no, PA
* AC!!!

y eso hace match con lo que hacemos hoy en día.

**Comment by lhchavez** [comment]
conversamente, si usamos el orden propuesto y a alguien le sale "50% WA", alguien podría pensar "bien! el algoritmo da en tiempo, sólo hay que arreglar bugs", sin percatarse de que tiene que optimizarlo primero.

no importa qué orden se elija, va a perder información y va a confundir a _alguien_.

habiendo dicho eso, estoy de acuerdo con el espíritu de "mejorar los mensajes de error", y podría estar de acuerdo con desplegar más de uno si a alguien se le ocurre cómo hacerlo de manera bonita. un "progress bar" con porcentajes (similar a cómo GitHub despliega la proporción de lenguajes en un repositorio como una rayita de colores de unos cuantos pixeles de alto) podría funcionar.

**Comment by darkmx** [comment]
En mi experiencia con mis alumnos, en efecto es inevitable confundir a alguien. Sin embargo, para los alumnos resulta más educativo saber directamente que están mal, en lugar de que pierdan tiempo optimizando algo que de hecho está mal.

Por otra parte, tenía la impresión de que lo que se reportaba era simplemente el resultado del último caso (probablemente porque el último caso suele ser TLE). Si omegaUp maneja un orden, entonces al menos les puedo enseñar a los alumnos cuál es ese orden.

Sobre lo de mostrar más de un mensaje de error, creo que no propongo nada. Salvo pedir que se reconsidere que un WA tenga preferencia a un TLE, me da un poco de miedo aumentar la cantidad de información que se despliega (tanto porque puede confundir al alumno como porque puede dar pistas de los casos). Anécdota que ocurre frecuentemente: cuando los alumnos tienen error en ejecución, suelen ir al cubículo a preguntarme por qué su programa mató el stack; yo les pregunto que cómo saben que eso ocurrió y me responden que omegaUp les dijo eso; yo les tengo que explicar que lo que dice omegaUp es que ésa es sólo una posible razón, no necesariamente **la** razón. Tal vez la barrita de progreso pueda quedar bonita y clara, pero no tengo mucha imaginación en cuanto a diseño de UI.

**Comment by darkmx** [comment]
Followup que se dio en Slack pero que no había puesto aquí:

> Rodrigo - rcc
> Hola a todos, platicando con Joe y con Francisco Zaragoza de la UAM, a Francisco se le ocurrió que si se le quiere mostrar más de un veredicto al usuario (ej. cuando un caso está mal, en otro mueren por tiempo, etc) entonces esta barrita puede ser una buena idea.
![image](https://user-images.githubusercontent.com/19719969/103462318-01baa700-4cea-11eb-854e-efced21e8d25.png)
> 
> lhchavez:
> en contextos educativos 100% de acuerdo. en contextos competitivos, bajo una bandera no-default al momento de configurar el concurso suena razonable.
> 
> Rodrigo - rcc
> ah claro, durante la plática tmb se dijo que eran contextos totalmente distintos
> 
> lhchavez
> sí, la cosa era que no teníamos una manera elegante de desplegar la información y esto se ve bastante razonable
> y no-imposible de implementar: https://getbootstrap.com/docs/4.5/components/progress/#multiple-bars
> lo único truculento sería agregar una columna JSON a la base de datos para guardar esta información de manera indexable para no tenerle que pedir al grader los detalles completos de cada envío nada más para renderear esto
> (y digo truculento porque la última vez que quisimos agregarle una columna a esa tabla se comió todo el espacio en el servidor en lo que se hacía la migración  del esquema ^^;; )
>

**Comment by woohoou** [comment]
+1

**Comment by heduenas** [comment]
Ahora con el rediseño de la tabla de veredictos creo que ya quedo resuelto esto.
