### ISSUE TITLE
[FEATURE] Mejorar mensaje de error cuando se añaden múltiples usuarios a la vez a un curso

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3146]
Cuando uno de los usuarios introducidos es incorrecto, el mensaje de error que aparece es:

     Se ha producido un error al agregar usuarios, al menos uno de ellos no se agregó correctamente. 

Deberíamos de mostrar explicitamente los usuarios que no se pudieron agregar.

**Comment by pabo99** [comment]
Asignado a @RuizYugen
