### ISSUE TITLE
[BUG] Los cursos publicos no son visibles para todos en el tablero de cursos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3147]
Para que los cursos públicos sean visibles para todos debes ingresar a: https://omegaup.com/schools/ y presionar _Start using schools_ pero esto no es intuitivo.

**Comment by carlosabcs** [comment]
La idea es hacer una tablita con los cursos públicos paginados debajo de:
![image](https://user-images.githubusercontent.com/20785082/72072179-5edc7200-32bb-11ea-8947-754e40c90869.png)
?

¿Aún si el usuario no está loggeado se mostrarían esos concursos?

**Comment by tvanessa** [comment]
En este tablero es donde no son visibles los cursos públicos (si no diste click en https://omegaup.com/schools/).
![Screen Shot 2020-01-09 at 3 43 00 PM](https://user-images.githubusercontent.com/13296248/72115587-72f49380-32fc-11ea-9ac2-32a7040b69ca.png)

Mas bien lo que buscamos es que sean visibles ahi.

**Comment by tvanessa** [comment]
Mi propuesta es crear un tab en ese tablero que se llame Cursos Públicos

**Comment by heduenas** [comment]
No es necesario cambiar la página `https://omegaup.com/schools/`.
Sólo `https://omegaup.com/course/` como dice Vanessa.

**Comment by pabo99** [comment]
Ok, el detalle es que la página `https://omegaup.com/schools/` le aparece a los usuarios que no han participado en ningún curso durante el tiempo que han utilizado la plataforma, ya sea cómo invitados u organizadores. Así que para que los cursos públicos puedan ser fácil de identificar sugiero dos alternativas:

- Lo que comenta @carlosabcs de mostrar la tabla de cursos públicos en la página de bienvenida de a Escuelas para los usuarios nuevos.

- Desaparecer la página de bienvenida a Escuelas para los usuarios que ya están logueados y cuando ingresen a la opción Escuelas accedan directamente al listado de Cursos, de cualquier forma les aparecerían los Públicos sin importar si se acaban de registrar. La página de bienvenida podría quedar sólo disponible para los usuarios que no se han logueado.

Con respecto al listado de cursos públicos podríamos utilizar el formato que se le dará a las tablas en el cambio #3335 para que se muestre de la siguiente manera:

![image](https://user-images.githubusercontent.com/3230352/72650347-e70ae900-3945-11ea-8a1e-88345e4b153d.png)

**Comment by tvanessa** [comment]
Me gusta más la segunda idea. Solo que preferiría mostrar estos cursos en la tabla "Lista de cursos", ponerla en una nueva pestaña que se llame "Cursos omegaUp" (o Cursos Públicos, si prefieren)

**Comment by pabo99** [comment]
Al ser una pestaña de "Lista de cursos", ¿Cuál de las pestañas se mostraría por defecto, Cursos Públicos o Cursos Actuales?
Así:
![image](https://user-images.githubusercontent.com/3230352/72657281-0b77bd00-3968-11ea-8a03-88eaf2b3fb59.png)

o así:
![image](https://user-images.githubusercontent.com/3230352/72657295-36faa780-3968-11ea-9710-d19156616c4e.png)

**Comment by tvanessa** [comment]
Se mostrarían las 3, cursos actuales, pasados y públicos.

**Comment by pabo99** [comment]
¿En que jerarquía?

**Comment by tvanessa** [comment]
En este orden: actuales, pasados y públicos

**Comment by lhchavez** [comment]
hay un problema potencial con juntar la lista de cursos en los que participo/participé y los públicos: es casi imposible enterarse que hay un nuevo curso público a menos que hagas click en esa pestaña!

podemos reconsiderar el tener ambos en una sola tabla y crear una aparte para cursos públicos? podemos mostrar esta tabla tanto en el intersticial como en la página que aparece una vez que ya estás loggueado y ya participas/administras en un curso.

**Comment by heduenas** [comment]
@pabo99 seria mucho trabajo cambiar al diseño que propone lhchavez? Si es mucho trabajo podemos mejor dejarlo como lo tienes por ahora y abrir otro issue para mover los cursos publicos a otra tabla.

**Comment by pabo99** [comment]
No debe haber problema lo que comenta @lhchavez, sólo ayúdenme a entender bien.

> podemos reconsiderar el tener ambos en una tabla?

Si, sólo tendría que revertir un cambio.

> podemos crear una tabla aparte para cursos públicos?

Sería similar a lo que propuse originalmente: 
![image](https://user-images.githubusercontent.com/3230352/72650347-e70ae900-3945-11ea-8a1e-88345e4b153d.png)
está bien?

> podemos mostrar esta tabla tanto en el intersticial como en la página que aparece una vez que ya estás loggueado y ya participas/administras en un curso?

En que parte del intersticial sería lo más recomendable?

**Comment by heduenas** [comment]
Lo que muestras en la imagen me parece que se ve bien. Sólo cambiaría "Lista de cursos" por "Cursos que estudio".

Para lo del intersticial yo creo que es mejor dejarlo para otro issue. Vanessa y yo nos encargamos de reportarlo y describir ahí en qué parte ponerlo.
