### ISSUE TITLE
[FEATURE] Al abrir una tarea se debería de mostrar el primer problema en vez del summary

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3153]
Al abir una tarea de un curso:
![image](https://user-images.githubusercontent.com/597815/70498731-3995f180-1acc-11ea-89eb-6f4b81a27971.png)

Lo primero que se muestra es el summary:
![image](https://user-images.githubusercontent.com/597815/70498888-a7dab400-1acc-11ea-8f91-f6862643920d.png)

Se debería de cargar el primer problema (SIN desaparecer el link al summary a la izquierda):
![image](https://user-images.githubusercontent.com/597815/70498800-6f3ada80-1acc-11ea-9f23-c39bb29d2875.png)

**Comment by lhchavez** [comment]
no siempre quieres que ocurra eso: a veces la descripción contiene lo que tus screenshots muestran para el primer problema.
