### ISSUE TITLE
[FEATURE] Usabilidad: evitar que el buscador de problemas avance inadvertidamente sin tags 

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3183]
Hola amigos de OmegaUp.

Las primeras veces que uno usa el buscador de problemas (donde se puede buscar por tag, seleccionar la dificultad, etc) uno tiene la impresión de que lo que se escribe es lo que se buscará (por ejemplo, escribir "string" buscará problemas con tags que contengan esa palabra). En realidad, lo que ocurre es que se buscan los tags en ese momento y uno puede seleccionados abajo... o no :) si no nos damos cuenta de que debemos seleccionarlos y proseguimos con la búsqueda, terminaremos buscando un subconjunto vacío de tags y se mostrarán todos los problemas.

Una propuesta de mejora concreta es: si el usuario escribió algo en la barra de búsqueda de tags, no eligió ninguno y le a click a "Siguiente", notificarle que no seleccionó ningún tag y preguntarle si desea continuar con la búsqueda de todos modos. Otra propuesta (más complicada y menos detallada) sería usar directamente lo que el usuario escribió para (de algún modo) buscar los problemas.

**Comment by tvanessa** [comment]
Tal vez podemos hacer algo como lo que hace leetcode:
![image](https://user-images.githubusercontent.com/13296248/73118130-9c750800-3f15-11ea-8d3b-44a02fb9ee75.png)

Podemos poner un campo arriba del buscador de tags en donde se vayan agregando los tags que se van seleccionando, y cambiar el texto del buscador de tags de "Add Tag" a "Search tags". El campo donde se van a ir agregando los tags podemos ponerle una etiqueta al inicio que diga "Lista de tags: " o algo asi.

**Comment by darkmx** [comment]
La UI cambió (y mejoró bastante desde entonces). Este issue ya no es relevante.
