### ISSUE TITLE
[BUG] El perfil de escuela del Bachillerato de Cancún no se renderea

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3191]
## Comportamiento Esperado

El perfil de la escuela del Bachillerato de Cancún se debería renderear como todos los demas.

## Comportamiento Actual

El perfil no se muestra, hay un null ref exception:

https://omegaup.com/schools/profile/3482/

vue.common.prod.js:6 TypeError: Cannot read property 'name' of null
    at a (Profile.vue?2fd9:31)
    at a.e._render (vue.common.prod.js:6)
    at a.r (vue.common.prod.js:6)
    at vn.get (vue.common.prod.js:6)
    at new vn (vue.common.prod.js:6)
    at vue.common.prod.js:6
    at a.xn.$mount (vue.common.prod.js:6)
    at a.xn.$mount (vue.common.prod.js:6)
    at init (vue.common.prod.js:6)
    at vue.common.prod.js:6

## Posible Solución
Será porque esta escuela no tiene bandera de país? (especulación, no he visto el código)

## Pasos para reproducir (para bugs)

Simplemente entrar a: https://omegaup.com/schools/profile/3482/ 

## Contexto

:) El feature está quedando súper nice, gracias @carlosabcs !!

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome
* Sistema Operativo y versión (escritorio o móvil): Escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/schools/profile/3482/
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/207097/71013312-579fbb00-20a5-11ea-8b96-de59333a78f6.png)

**Comment by carlosabcs** [comment]
Gracias @joemmanuel !
Ya he enviado un PR para solucionar eso: https://github.com/omegaup/omegaup/pull/3187
