### ISSUE TITLE
Mi perfil aparece vacio: Empty parameter.: target_username

### ISSUE THREAD

**Issue by JoseJuanSE** [omegaup/omegaup#3194]
## Comportamiento Esperado

Que aparezca de forma correcta mi perfil

## Comportamiento Actual

![image](https://user-images.githubusercontent.com/59002673/71052503-20ff8a00-2111-11ea-9ae4-11b1f1967442.png)

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. https://omegaup.com/profile//
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Errores en la consola: []
* Captura de pantalla:

**Comment by JoseJuanSE** [comment]
Ya me aparece correctamente, gracias.

**Comment by JoseJuanSE** [comment]
Ya me aparece correctamente, gracias.

**Comment by darkmx** [comment]
Hola a todos, tal vez se deba reconsiderar abrirlo.
Al parecer el problema es intermitente. Uno de mis alumnos me mandó un correo preguntándome del error y un par de horas después de mandó otro de que ya estaba bien, pero ahorita anda cucho.

![imagen](https://user-images.githubusercontent.com/19719969/71224923-7c11b800-229c-11ea-952a-c5463ed59d84.png)

Aprovecho para preguntar. Me acuerdo que antes, el lenguaje por omisión en el que yo hacía un envío era C++11 (hablo en 1ra persona porque no puedo afirmar si esto era cierto para todos). No recuerdo si era por coincidencia o si en mi perfil podía elegirlo, porque ahorita no carga mi perfil como para poder ver qué se puede editar :( Posiblemente fuera coincidencia, porque recuerdo que la lista se veía diferente y acabo de ver el commit #3179. En dicho caso, publicaré de forma separada un feature-request para poder elegirlo.

![imagen](https://user-images.githubusercontent.com/19719969/71225043-efb3c500-229c-11ea-80b2-c49a52f9c56b.png)

**Comment by lhchavez** [comment]
acabo de limpiar el cache porque antes había un objeto intermedio `user_info` que ya no existe. esa información se guardaba en el cache.

con respecto al lenguaje por omisión sí crea un issue aparte porque este issue ya fue resuelto.

**Comment by darkmx** [comment]
enterado!

**Comment by lhchavez** [comment]
resulta que sigue ocurriendo! https://omegaup.com/profile/rcc/

definitivamente hay que hacer algo al respecto de ese `'userinfo'` :S

**Comment by lhchavez** [comment]
@pabo99 puedes darle prioridad a este issue sobre #3004? esto está afectando a más gente.

**Comment by pabo99** [comment]
Si, claro.

**Comment by pabo99** [comment]
Estoy revisando que `apiProfile` almacena todo en `userinfo` y se manda llamar desde un par de lugares. El que pareciera que está causando la confusión es en el controlador de [Problem L1768-L1774](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/Problem.php#L1768-L1774) debido a que están guardando en caché `apiProfile`. 

Puedo solucionar eso, pero aún así no tengo forma de validar que ya funcione correctamente. La alternativa es quitar de todos lados `userinfo`. El único inconveniente de quitarlo de todos lados es que hay un lugar donde no es tan fácil quitarlo: en `getCodersOfTheMonth` debido a que esta función regresa más cosas y se revolvería todo.
