### ISSUE TITLE
[BUG] Después de cambiar de nombre de usuario no se actualizan mis datos en el ranking General

### ISSUE THREAD

**Issue by MarioJimenez9** [omegaup/omegaup#3202]
Los Ultimos dias he estado resolviendo problemas con el fin de escalar posiciones en el ranking, sin embargo, mi puntaje no incrementa ni tampoco la cantidad de problemas resueltos. Ya han pasado aproximadamente de 2 a 3 dias.

---En el ranking me aparecen 456 problemas resueltos. (Esta cifra no ha incrementado en los ultimos dias)
https://omegaup.com/rank/ 

---Mientras que en mi perfil tengo 473
https://omegaup.com/profile/MarioJimenez9/

**Comment by tvanessa** [comment]
Este perfil también es tuyo? https://omegaup.com/profile/MarioJimenez9/ Yo no puedo ver tu perfil de https://omegaup.com/profile/ITSUR-MarioD10S/ pero vi que el otro tiene los 473 problemas que has resuelto.

**Comment by MarioJimenez9** [comment]
cierto olvidé que cambié mi nombre de usuario

**Comment by carlosabcs** [comment]
@lhchavez  será que se ha quedado atascado el script para actualizar los ranks?

**Comment by lhchavez** [comment]
ah! seguro es eso.

**Comment by lhchavez** [comment]
listo, el cronjob ya corre de nuevo.
