### ISSUE TITLE
[BUG] El filtro por tag en la lista de problemas no funciona.

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3203]
En https://omegaup.com/problem/ si das click en un tag, el filtro no muestra problemas con ese tag

![Screen Shot 2019-12-18 at 7 17 57 PM](https://user-images.githubusercontent.com/13296248/71142441-443b3f80-21cc-11ea-9529-fc1c2a1d2b86.png)
![Screen Shot 2019-12-18 at 7 18 14 PM](https://user-images.githubusercontent.com/13296248/71142445-46050300-21cc-11ea-93ed-3f1ed63f1d5f.png)

Se probó en firefox y chrome.

**Comment by LuisMBarrera** [comment]
Hola buenos días, soy nuevo contribuyendo a proyectos open-source y quería saber si podia ayudar con este issue.

**Comment by tvanessa** [comment]
Hola @LuisMBarrera este issue esta duplicado y ya fue asignado. Pero eres bienvenido a contribuir con nosotros, te recomiendo este otro issue para empezar https://github.com/omegaup/omegaup/issues/3086

PD: https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar

**Comment by LuisMBarrera** [comment]
Muchas gracias @tvanessa lo revisare de inmediato
