### ISSUE TITLE
[FEATURE] Poder elegir el lenguaje por omisión en el que se hace un envío

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3209]
Hola amigos de omegaUp.

Cuando uno hace un envío, hay un `<select>` donde se debe seleccionar el lenguaje en el que está escrito el código, Ahorita el valor seleccionado por omisión simplemente es el primero listado en el código ya cargando a memoria (algo que me intriga es que el orden en el código fuente es diferente al que aparece en el inspector D: supongo que hay un JS que hace algo por ahí). Estaría padre poder elegir el lenguaje por omisión en nuestro perfil, para evitar tener que hacerlo en cada envío (evitando así uno que otro CE accidental).

**Comment by lhchavez** [comment]
ya se puede, no? https://omegaup.com/profile/edit/

**Comment by darkmx** [comment]
ah! perdón :( pero ahorita se ve así:

![imagen](https://user-images.githubusercontent.com/19719969/71227969-6f925d00-22a6-11ea-9d05-f056d2b7203d.png)

qué procede? cierro esto y abro un bug? o chance reeditar por completo este post

**Comment by lhchavez** [comment]
se vale reeditar este bug porque es la misma causa y no se ha arreglado. una vez que se cierra, es para siempre y se prefiere que se abra uno nuevo, pero como este no se ha cerrado, se vale.

**Comment by lhchavez** [comment]
eso del `<script>` no es el problema porque yo sí puedo editar mi perfil y también tengo ese 404.

**Comment by darkmx** [comment]
Entonces está más raro. Intenté editar mi perfil en Chrome y no pude; me logueé es una ventana privada de firefox y tampoco pude. Intentaré encontrar la fuente real del problema y si resulta que soy solo yo, cierro el issue. Si resulta sí ser un bug, actualizo, edito y mantengo abierto.

**Comment by lhchavez** [comment]
La causa raíz de que no puedes editar tu perfil es https://github.com/omegaup/omegaup/issues/3194

**Comment by darkmx** [comment]
Creo que el problema es otra vez lo de 
![imagen](https://user-images.githubusercontent.com/19719969/71228912-550db300-22a9-11ea-8566-0a89916e0e3d.png)

**Comment by darkmx** [comment]
> 
> 
> La causa raíz de que no puedes editar tu perfil es #3194

sip :(
