### ISSUE TITLE
Eliminar los problemas repetidos

### ISSUE THREAD

**Issue by MarioJimenez9** [omegaup/omegaup#3216]
En la ventana principal del problemario hay una gran cantidad de problemas repetidos, prácticamente dicen lo mismo solo les cambiaron los nombres.
<img width="751" alt="send" src="https://user-images.githubusercontent.com/59043072/71316738-eceed680-243a-11ea-8ae4-e122990a5b25.png">
<img width="761" alt="sen2" src="https://user-images.githubusercontent.com/59043072/71316753-4f47d700-243b-11ea-81fc-474ce47f74bd.png">
<img width="768" alt="sen3" src="https://user-images.githubusercontent.com/59043072/71316754-50790400-243b-11ea-85b3-980bc23900cd.png">

Esto influye en el ranking especialmente en el de las escuelas mas activas.

**Comment by lhchavez** [comment]
cada que veas un problema así, repórtalo por favor. vamos a cerrar este issue porque dependemos de ustedes para que reporten los problemas duplicados.
