### ISSUE TITLE
[BUG] Problemas inutilizables por actualizaciones en el markdown

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3218]
Hola amigos de omegaUp.

A través de los años, diversas actualizaciones en el despliegue de los statements han provocado que algunos problemas queden unitilizables. El mayor ofensor es el caracter # dentro de los casos de ejemplo. Una lista no exhaustiva de los problemas afectados es:

- https://omegaup.com/arena/problem/Andar-Chido#problems
- https://omegaup.com/arena/problem/COCI-SILUETA#problems
- https://omegaup.com/arena/problem/Centro-Omijal#problems
- https://omegaup.com/arena/problem/Cuban-Challenge#problems
- https://omegaup.com/arena/problem/Dos-Laberintos#problems

Hay aproximadamente 20 problemas potencialmente afectados. En un caso similar, algunos autores (yo incluido en su momento) nos dimos cuenta de que había problemas con el despliegue de nuestros problemas e intentamos usar \\# para corregirlo. En su momento eso sirvió (es decir, \\# se desplegaba como #) pero actualmente ya no es el caso (\\# ahora se despliega como \\#). Una lista no exhaustiva de los problemas afectados es:

- https://omegaup.com/arena/problem/COMI-Derrame-de-Petroleo#problems
- https://omegaup.com/arena/problem/Cuantos-Productos#problems
- https://omegaup.com/arena/problem/Dora-la-Exploradora-A#problems
- https://omegaup.com/arena/problem/El-escape-de-Charls-y-Briaares
- https://omegaup.com/arena/problem/Hashtag#problems

Algunos autores han intentado darle vuelta al problema agregando espacios, ya que la interpretación de # como especial se deshabilita si no es el primer caracter de la línea. Sin embargo, algunos autores han tenido que agregar notas para que los alumnos no se confundan o de plano simplemente lo dejan así. Una lista no-exhaustiva de los problemas afectados es:

- https://omegaup.com/arena/problem/Escape-del-laberinto#problems
- https://omegaup.com/arena/problem/Portal#problems
- https://omegaup.com/arena/problem/bloques#problems
- https://omegaup.com/arena/problem/datbomb#problems
- https://omegaup.com/arena/problem/luigi#problems

Hay aproximadamente 20 problemas potencialmente afectados por \\# o por tener que poner espacios adicionales. Adicionalmente, hay otros 20 problemas "frágiles", es decir, por la naturaleza del problema, algún caso de entrada adicional a los ya especificados podría caer en algún caso problemático. Algunos autores (yo incluido) hemos tenido que cambiar a entidades html para arreglar nuestros problemas, pero el markdown queda horrible. Algunos ejemplos son https://omegaup.com/arena/problem/4FC-Imagenes#problems y https://omegaup.com/arena/problem/Alicia-y-la-llave-dorada.

En mi opinión, lo ideal sería deshabilitar el comportamiento especial de # dentro de los casos de ejemplo, pero tal vez sea una sugerencia no muy meditada (en realidad no sé qué tanto implique a nivel de la implementación o del mantenimiento del código). Independientemente de la solución, creo que es importante reparar los problemas afectados.

**Comment by lhchavez** [comment]
puedes separara lo de las imágenes? no tiene que ver con el manejo de markdown en la sección de ejemplos.

**Comment by lhchavez** [comment]
re: deshabilitar el comportamiento especial de `#`, esa era la intención :S parece que hay que ver cómo hacerle para que las tablas de entrada / salida tengan la misma prioridad que los bloques de código al momento de ser parseados como

    ```
    # micódigo
    ```

**Comment by lhchavez** [comment]
resulta que no fue tan difícil.

**Comment by darkmx** [comment]
Muchas gracias :) estaría padre poder corregir los statements de los problemas que usaron \\# en su momento, pero veo un poco más complicado hacer eso automáticamente (también usaron \- o \* y se corre el riesgo de "arreglar" problemas que en verdad querían poner diagonal invertida y no otra cosa). Luego hago una lista (esta vez exhaustiva) de los problemas que son seguros de corregir y se las mando.
