### ISSUE TITLE
Test completo de Scoreboard

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#322]
TODO: @joemmanuel incluirá más detalles al respecto.

**Comment by pabo99** [comment]
@joemmanuel  ¿Qué tipo de pruebas se deben realizar? ¿Se tienen todos los casos de uso?, Es que no conozco en su totalidad lo que se hace en el scoreboard

**Comment by pabo99** [comment]
Esperando a que se autoricen los cambios del #1022

**Comment by elendil326** [comment]
Incluye hacer correr el broadcaster en travis

**Comment by lhchavez** [comment]
https://github.com/omegaup/puppet/blob/master/manifests/services.pp

**Comment by pabo99** [comment]
Este issue es sólo para las pruebas en selenium, las pruebas unitarias se resolverán en #2090

**Comment by pabo99** [comment]
¿Le falta algo a este issue para poder cerrarlo?
