### ISSUE TITLE
[BUG] No se selecciona el lenguaje preferido por omisión

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3241]
Hola amigos de omegaUp.

En nuestro perfil podemos elegir nuestro lenguaje preferido, pero al momento de hacer envíos se selecciona siempre el primero del dropdown. Debido a esto, el usuario debe tener constante cuidado al enviar sus programas y evitar CE. Esto ocurre tanto en Firefox como en Chrome (Windows).

![imagen](https://user-images.githubusercontent.com/19719969/71548099-f6160100-296e-11ea-97be-89fb7266f5a1.png)

**Comment by lhchavez** [comment]
ya se mitigó la parte crítica (los CE que ocurren cuando esto falla). Igual estaría bien diagnosticar por qué está ocurriendo y arreglarlo, porque suena a que es molesto.

**Comment by darkmx** [comment]
Enterado! gracias :) ahorita que termine de subir un problema, intentaré diagnosticar

**Comment by lhchavez** [comment]
resulta que fue mucho más fácil de lo que pensaba. ya quedó :D

**Comment by darkmx** [comment]
genial :D a two-liner; voy cerrando esto!
