### ISSUE TITLE
[BUG] Error al mostrar scores en problemas de una practica de escuelas

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#3242]
## Comportamiento Esperado

Que muestre el score correcto de cada envío.

## Comportamiento Actual

No muestra el score de algunos envíos.

## Pasos para reproducir (para bugs)

1. Entrar a una practica de escuela donde se haya resuelto algún problema 
2. Dar click en el problema que se tienen varios envíos
3. Aparece en la parte superior un mensaje de error

## Contexto

Los alumnos no pueden visualizar sus envíos anteriores.

## Tu ambiente

* Windows 10
* Chrome

![image](https://user-images.githubusercontent.com/6465292/71548486-8b67c400-2974-11ea-8611-cd039aa4ee40.png)

**Comment by kukogit** [comment]
![image](https://user-images.githubusercontent.com/6465292/71550809-71db7200-299e-11ea-9dda-22105d6d204e.png)

**Comment by lhchavez** [comment]
hmmm no logramos reproducir este error. puedes grabar un [`.har`](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-Network-Captures-for-Troubleshooting/ta-p/366), cerrar tu sesión inmediatamente después de terminar de grabar (porque ese archivo contiene las cookies que envías) y compartirlo por aquí?

en el futuro por favor siempre incluye el URL donde ocurre el error para hacernos la vida más fácil.

**Comment by kukogit** [comment]
Sigue pasando el error. Tienes que hacer un envío a un problema de una tarea y luego entrar de nuevo...

https://omegaup.com/course/ORIG19OMIPS20/assignment/ORIG19OMIPS20T04/

[omegaup.com.har.zip](https://github.com/omegaup/omegaup/files/4008264/omegaup.com.har.zip)

**Comment by lhchavez** [comment]
gracias! ya con eso _creo_ que podemos arreglarlo.

**Comment by kukogit** [comment]
Cerrado significa que "ya merito" se arregla?

**Comment by kukogit** [comment]
Porque estoy aplicando examen y mis chamacos no pueden ver sus puntajes ni envíos.

**Comment by lhchavez** [comment]
sí, siempre se hacen los deploys los domingos en la noche.

**Comment by kukogit** [comment]
Entonces eso es un no, y que mis alumnos le hagan como puedan... gracias.
