### ISSUE TITLE
[FEATURE] Definir duración infinita para cursos públicos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3298]
Es esperado que algunos de los cursos públicos de la plataforma estén por siempre en la ella. Se propone definir una duración infinita en los cursos.

Actualmente se puede pedir a los admins que la duración se extienda por años, o extendiendo periódicamente el curso en la plataforma.
 
Una alternativa es que al llamar al API para hacer el curso público, se agregue un parámetro que indique que la duración es infinita.

**Comment by carlosabcs** [comment]
Entonces, al recibir ese parámetro que indica que la duración es infinita, qué valor le pondríamos a esto
https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L182 en dicho curso?

**Comment by pabo99** [comment]
> Entonces, al recibir ese parámetro que indica que la duración es infinita, qué valor le pondríamos a esto
> https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L182 en dicho curso?

Dos propuestas:

- Modificar la columna para que acepte `null`.
- Ignorar el valor que tiene y se quede con el default.

Ya cuando ingreses al curso / tarea primero se valide si tiene prendida la bandera de infinito y después la fecha de fin.

**Comment by carlosabcs** [comment]
Ok, pondré en slack esto para que definamos de una vez qué propuesta llevar a cabo.

**Comment by lhchavez** [comment]
voto por `null` porque es más elegante que poner una bandera separada.
