### ISSUE TITLE
[BUG] Badge experto en C++ no se ve en perfil de usuario

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3325]
![image](https://user-images.githubusercontent.com/597815/72302593-65524d00-361f-11ea-8bf6-30cf480776c8.png)

**Comment by lhchavez** [comment]
ah eso fue porque renombramos el badge de `cppexpert` a `cppExpert`. hice backfill y ya todos los usuarios tienen el badge con el nombre correcto.
