### ISSUE TITLE
[FEATURE] Cambiar la cantidad de usuarios que poseen un badge a terminos absolutos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3326]
![image](https://user-images.githubusercontent.com/597815/72303513-5faa3680-3622-11ea-88a1-360ba3d17133.png)

Cambiar de:
 3.55% 👥 Porcentaje de usuarios que han recibido esta insignia 
a:
 710 de 20000 👥 Usuarios han recibido esta insignia

**Comment by lhchavez** [comment]
cuál es el objetivo de este cambio? el porcentaje y el número absoluto dan distinta información y se pueden usar para motivar a la gente de maneras distintas.

**Comment by heduenas** [comment]
Los porcentajes de los badges suelen salir muy bajos dado que tenemos muchisimos usuarios inactivos. Por otro lado el badge de experto en python sale en 0.00%, sospechamos que es porque hay muy pocos usuarios con el badge y se redondea a 0.00%.

Otra propuesta es decir "X de N usuarios han recibido esta insignia" y asi seguimos dando la información que daba el porcentaje.

**Comment by lhchavez** [comment]
esa última opción me parece aceptable. la idea es que el badge debería manifestar cierta "exclusividad"; usar el número absoluto así sin contexto hace que eso se pierda, pero ya con el nominador/denominador se recupera (y de hecho se prefiere para porcentajes muy cercanos a cero).
