### ISSUE TITLE
[BUG] No se puede cambiar de escuela mas de una vez en el perfil de usuario

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3331]
## Comportamiento Actual

Puedes cambiar de escuela una vez, pero si lo intentas de nuevo aparece el mensaje: `Oops. I've encountered an internal error. Please try again.`

**Comment by tvanessa** [comment]
@carlosabcs Tienes un idea de por qué pasa esto?

**Comment by carlosabcs** [comment]
Wow, no me había percatado. Algo en `IdentitiesSchools` no debe estar funcionando como debe. Asígnamelo, voy a ver si el error aparece agregando una prueba de actualización de escuela más de una sola vez.

**Comment by lhchavez** [comment]
Esto ya está mitigado (así que dándole downgrade a P2) _pero_ falta atender esto: https://github.com/omegaup/omegaup/pull/3333#issuecomment-574941084

**Comment by carlosabcs** [comment]
> Esto ya está mitigado (así que dándole downgrade a P2) _pero_ falta atender esto: [#3333 (comment)](https://github.com/omegaup/omegaup/pull/3333#issuecomment-574941084)

Copiaré la respuesta que puse en el PR, acá:
> welp, no puedo encontrar una explicación de por qué la fecha de graduación está en el índice primario: creo que no debió haber estado nunca ahí O_O.
> 
> algo que hay que asegurar es que un usuario no tenga más de una escuela "activa" concurrentemente, pero eso no se puede garantizar con índices.

Respecto a lo primero:
Usé `DROP INDEX` porque así se eliminaba el `UNIQUE INDEX`. No sé si `UNIQUE INDEX` sea igual a `INDEX`, pero éste último, nunca lo creé de manera explícita, lo que había antes era:
```sql
UNIQUE KEY `identity_school_graduation_date` (`identity_id`,`school_id`,`graduation_date`)
```

Respecto a lo segundo, eso ya está asegurado en `apiUpdate` y su DAO correspondiente.
