### ISSUE TITLE
[Badge Proposal] Completar los lenguajes para el badge Experto en Python

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3332]
Asegurar que el query de este badge pide `py, py2, py3`

**Comment by lhchavez** [comment]
`py` ya no es un lenguaje seleccionable, así que con `py2` y `py3` basta. ambos están en el query, así que ya está resuelto \o/

https://github.com/omegaup/omegaup/blob/b11994d263b985d71a9e4fd97dd468afb37b4c27/frontend/badges/pythonExpert/query.sql#L17

**Comment by tvanessa** [comment]
Cuál es la razón para dejar `py` en la tabla de Submissions? Eso fue lo que nos hizo querer considerarlo
 https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L851
