### ISSUE TITLE
[FEATURE] Agregar opciones adicionales al dar respuesta a un reporte

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3339]
Hola amigos de omegaUp.

En una plática con @tvanessa, @carlosabcs y @heduenas se mencionó el inconveniente de que la respuesta a un reporte (nominación negativa) actualmente sea binaria: se niega o se aprueba el reporte. El efecto de aprobar un reporte es que el problema desaparece de la lista de problemas, pero esto puede ser algo exagerado en algunos casos:

- La redacción del problema no es clara, pero el problema no es spam.
- Hay reportes creíbles o evidencia de que los casos están mal, pero parece ser un error genuino.
- El problema es duplicado, pero posiblemente el autor del duplicado no lo sabía, o bien, se hizo a sabiendas pero con justificación razonable (modificar algún setting, agregar o corregir casos). Sobre este tema platiqué un poco con @lhchavez y no creemos que suspender el problema duplicado sea siempre la alternativa correcta.

Dicho esto, conviene agregar opciones adicionales al dar respuesta a un reporte. Estuvimos comentando sobre la posibilidad de habilitar la aparición de una advertencia cuando el usuario entra al problema. Aún hay decisiones de diseño por tomar, pero voy creando el issue de referencia por mientras.

**Comment by tvanessa** [comment]
#3831
