### ISSUE TITLE
Exponer apiStats en el admin panel del concurso

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#334]
Api entry point:
https://omegaup.com/api/contest/stats/contest_alias/:contest_alias/
https://omegaup.com/api/contest/stats/contest_alias/IOI2013E3E2/

Este es un ejemplo del output de ContestController::apiStats : 

array(5) {
  ["total_runs"]=>
  string(2) "23"
  ["pending_runs"]=>
  array(11) {
    [0]=>
    string(32) "5368fb810b1deaca90df13fc198dff4d"
    [1]=>
    string(32) "4a70a6d0c7241bf29086f5174fcfcc14"
    [2]=>
    string(32) "74ad1c6790aea0924332770307911a4f"
    [3]=>
    string(32) "c437382e691a9d5c2e9d8c9ae108d772"
    [4]=>
    string(32) "298b22463dc0f9211438351256f36039"
    [5]=>
    string(32) "d821fc41366f995f16d1c16f2025ff97"
    [6]=>
    string(32) "b68f7630180493293f75f1e943531519"
    [7]=>
    string(32) "efc6fc5257cc96bde3e65a3bac2d821f"
    [8]=>
    string(32) "3e5c4f9b724ed44d509f11c81d8c4bc9"
    [9]=>
    string(32) "3314e2bcde423d15cefe6e6fc25085b7"
    [10]=>
    string(32) "f87848ef7a8235d11a9b570462a37cef"
  }
  ["max_wait_time"]=>
  int(7)
  ["max_wait_time_guid"]=>
  string(32) "5368fb810b1deaca90df13fc198dff4d"
  ["veredict_counts"]=>
  array(11) {
    ["AC"]=>
    string(1) "7"
    ["PA"]=>
    string(1) "0"
    ["WA"]=>
    string(1) "5"
    ["TLE"]=>
    string(1) "0"
    ["MLE"]=>
    string(1) "0"
    ["OLE"]=>
    string(1) "0"
    ["RTE"]=>
    string(1) "0"
    ["RFE"]=>
    string(1) "0"
    ["CE"]=>
    string(1) "0"
    ["JE"]=>
    string(2) "11"
    ["NO-AC"]=>
    string(1) "0"
  }
}

**Comment by pabo99** [comment]
¿a que se refiere este cambio?
