### ISSUE TITLE
[FEATURE] Remover inicio de sesión automatico

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#3341]
*Ejemplo: Como [usuario], quiero [un botón de inicio] para [poder regresar a la
página inicial con un solo click]*
Como [usuario], quiero [tener que escribir mis datos en el log in] para [así poder cambiar de cuentas fácilmente]

## Comportamiento Esperado

Al ir al menú de login, no se inicia sesión hasta escrivir tu usuario y contraseña.

## Comportamiento Actual

Al ir al menú de login, si se había iniciado sesión antes, esta se abre sola. *Incluso si se cierro sesión*
Esto ha sido un problema porque en ciertos lugares como  CIMAT, cyberso el centros de computos escolares, es díficil iniciar la sesión de alguien diferente a quien había iniciado sesion con anterioridad.

Además, el hecho de que presionar el botón, cerrar sesion no arregle el hecho, puede causar que individuos accedan a las cuentas de otras personas sin su concentimiento, lo que les puede permitir el obtener información, modificar información, copiar codigos, mandar codigos bajo otro usuario, etc.

## Posible Solución

Creo que esta cosa solo ha de pasar si se da en un check box de remember me. Y debe dejar de pasar cuando se cierre la sesión manualmente.

## Alternativas consideradas

Remover completamente el inicio de sesión automatico.

Una forma similar a google, donde al iniciar sesión pregunta, quien eres y puedes darle click a tu user name o iniciar con otra sesión.

## Contexto

Una vez, un compañero no podía iniciar sesión en una computadora, porque alguien ya habia iniciado sesión allí.

## Tu ambiente

Windows 10
Chrome Versión 79.0.3945.117 (Build oficial) (64 bits)
https://omegaup.com/login/?redirect=%2F

![omegaUndesiredFeature](https://user-images.githubusercontent.com/19498800/72683436-02d4d300-3a9d-11ea-9171-c7cd91a7e62d.gif)

**Comment by lhchavez** [comment]
Duplicado de #2637
