### ISSUE TITLE
[BUG] Las fechas en las tareas de un curso se muestran incorrectamente

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#3351]
## Comportamiento Esperado

Al ingresar al listado de tareas en un curso, se deben mostrar la fecha de inicio y fecha de fin de cada una de ellas.

## Comportamiento Actual

En su lugar se está mostrando una cadena con números que no corresponden al año correcto.

## Pasos para reproducir (para bugs)

1. Ingresar a cualquier Curso
2. Ver el listado de tareas

## Tu ambiente

* Captura de pantalla:
![image](https://user-images.githubusercontent.com/3230352/72757371-617d7800-3b95-11ea-867c-93f55c57b49b.png)

**Comment by carlosabcs** [comment]
Esto ya lo tengo casi corregido en un PR que estoy preparando. Así que si gustas me lo puedes asignar @pabo99

**Comment by eloisagc** [comment]
exactamente eso nos está pasando con las tareas en OmegaUp que ya se habían cerrado y que volvimos a abrir. Las fechas ahora se muestran de forma incorrecta y cuando los usuarios quieren hacer envíos les aparece lo que se muestra en la segunda imagen:
<img width="369" alt="Screen Shot 2020-01-22 at 13 17 13" src="https://user-images.githubusercontent.com/6990253/72935069-83a00300-3d19-11ea-8e09-aa92d60485e3.png">

![WhatsApp Image 2020-01-22 at 12 52 27](https://user-images.githubusercontent.com/6990253/72935409-2193cd80-3d1a-11ea-8ebe-2dade5a5872e.jpeg)

**Comment by carlosabcs** [comment]
Uff, no me había dado cuenta de eso último. Lo agregaré al commit que resuelve este issue @eloisagc.
