### ISSUE TITLE
[Badge Proposal] Cambiar el badge de Legacy User

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3359]
# Contenido

Sugiero que removamos el badge de Legacy User ya que es imposible de obtener para la mayoría de los usuarios. Entiendo que la intención es que los usuarios antiguos sean reconocidos pero por lo que he visto en otros sitios, la idea de usar badges es para motivar a los usuarios a continuar en la plataforma, personalmente me preocupa que sea desmotivante tener un badge que no se pueda alcanzar para alguien que se dé a la tarea de coleccionar los badges.

**Comment by pabloaguilar** [comment]
+1 Joe, muy buen punto sobre badges inalcanzables.
Que tal si cambiamos la definicion a algo como "usuario activo por mas de N anios" ? De esa manera si motivas a la gente a que siga volviendo (aun pasada su etapa de concursante, por ejemplo)

**Comment by carlosabcs** [comment]
La propuesta de @pabloaguilar  me parece genial, sería un reconocimiento parecido al que se buscaba con `Legacy User`.

**Comment by heduenas** [comment]
Estoy de acuerdo. Cual es la definición de "activo que típicamente" manejamos? que cantidad N de años les parece razonable?

**Comment by pabloaguilar** [comment]
Thinking out loud:
* N = 3 años
* Activo = Envió al menos una solución O creó al menos un problema O creó al menos un concurso en el año

Segunda idea: Partir el badge en una serie de badges para diferentes valores de N.

**Comment by lhchavez** [comment]
para evitar bikeshedding, +1 a lo que dijo @pabloaguilar

**Comment by licgerman** [comment]
Entiendo que se refieren a los últimos 3 años para indicar que está activo. ¿Es correcto?
