### ISSUE TITLE
[BUG] No puedo filtrar usuarios del ranking.

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#3371]
## Comportamiento Esperado

Filtrar Usuarios en el ranking

## Comportamiento Actual

Me indica que "Para filtrar los usuarios del ranking debes actualizar tu información básica." sin embargo mi perfil lo tengo completamente lleno. 

## Pasos para reproducir (para bugs)

Desconozco si sea un bug particular a mi perfil, o este extendido.

## Tu ambiente

![image](https://user-images.githubusercontent.com/5838427/73139217-9586ec00-4020-11ea-8e03-e8ec4c20bf35.png)

![image](https://user-images.githubusercontent.com/5838427/73139222-a9325280-4020-11ea-93c4-522e9da75090.png)

**Comment by heduenas** [comment]
No pude reproducir este bug. Intente antes y después de hacer login y en ambos casos funciona como se espera. Puedes reintentar? Se abrá arreglado con el deployment de hoy?

**Comment by samdsmx** [comment]
Te mando mis accesos, inbox

**Comment by pabo99** [comment]
A mi también me sucede. Me lo puedes asignar a mi @heduenas
