### ISSUE TITLE
[Problemas: tags y sello de calidad] Insertar todos los tags de categorías a la tabla de Tags

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#3374]
Esta lista de tags de categorías será provisto por: @darkmx 
Según lo que se discutió en el one pager, los tags que tienen que ver con las categorías tendrán el siguiente nombre: `problemCategory${inserte_el_alias_del_tag}`.

**Comment by carlosabcs** [comment]
@darkmx me gustaría que me ayudes pasándome el alias de todas las categorías con su correspondiente nombre, yo me encargo de las traducciones y las incluyo en el PR para este issue.

**Comment by darkmx** [comment]
Hola Carlos. No sé exactamente si lo siguiente es lo que necesitas, pero de todos modos será útil y lo mando (ahorita estoy considerando una categoría más que la del documento, que corresponde con problemas de "sólo-salida" que están usando mucho para problemas matemáticos para niños del tipo de respuesta abierta).

```
RespuestaAbierta		Problemas de respuesta abierta
EducaciónKarel			Programación educativa con Karel
IntroduccionProgramación	Introducción a la programación
ProblemasMatemáticos		Matemáticas y teoría de números
EstructurasDatosElementales	Ordenamiento y estructuras de datos elementales
AlgoritmosRedes			Diseño de algoritmos y optimización en redes	
ProgramaciónCompetitiva		Problemas de programación competitiva
TemasEspecializados		Programación para temas especializados
```
