### ISSUE TITLE
[FEATURE] Escribir documento de diseño para mostrar casos de prueba  (+ diff para casos pequeños) en ciertos problemas

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3376]
Escribir diseño para proyecto que de solución a #1998 y #990.

**Comment by pabo99** [comment]
El documento del diseño se encuentra en https://docs.google.com/document/d/1namOpwMAgNEDuboxtQf1-0YF-Q5ZxsLAHDnpO0Ps2q0/edit?usp=sharing para comenzar la discusión de cambios.
