### ISSUE TITLE
[FEATURE] Como administrador de un curso me gustaría que el ScoreBoard se ordenara

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#3387]
## Comportamiento Esperado

Que los puntajes de las tareas y exámenes se actualizaran en tiempo real como lo hace en un contest y que además se muestren ordenados

## Comportamiento Actual

Muestra los alumnos ordenados alfabéticamente y los puntajes no se actualizan hasta que le das F5.

## Alternativas consideradas

Que tenga el mismo comportamiento de un concurso.

## Contexto

Que los alumnos puedan visualizar su puntaje respecto los demás competidores.

**Comment by tvanessa** [comment]
Al ordenar alfabéticamente, la gráfica del scoreboard solo muestra el progreso de los primeros 10, no el de los puntajes más altos
![Screen Shot 2020-06-17 at 1 51 39 PM](https://user-images.githubusercontent.com/13296248/84949467-27f85c80-b0a2-11ea-91b3-e465daa80bc9.png)
