### ISSUE TITLE
[BUG] No corren las pruebas

### ISSUE THREAD

**Issue by RuizYugen** [omegaup/omegaup#3388]
## Comportamiento Esperado

Estaba realizando el issue #3146 ya corria bien localmente pero al ejecutar la pruebas me marca el error que se muestra a continuación y las pruebas fallan, la copia local esta actualizada con los ultimos cambios igual que la base de datos.

## Comportamiento Actual

al ejecutar ./stuff/runtests.sh
marca lo siguiente
```
.............................F.................................  63 / 540 ( 11%)
............................................................... 126 / 540 ( 23%)
............................................................... 189 / 540 ( 35%)
............................................................... 252 / 540 ( 46%)
............................................................... 315 / 540 ( 58%)
............................................................... 378 / 540 ( 70%)
............................................................... 441 / 540 ( 81%)
............................................................... 504 / 540 ( 93%)
....................................                            540 / 540 (100%)

Time: 29.45 minutes, Memory: 32.00MB

There was 1 failure:

1) CoderOfTheMonthTest::testCoderOfTheMonthAfterYear
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'eea387da2a07c1370dcff4a64b70e363'
+'0fc8a5766999dd1e52f98a76b56f1a57'

/opt/omegaup/frontend/tests/controllers/CoderOfTheMonthTest.php:266

FAILURES!
Tests: 540, Assertions: 7554, Failures: 1.
```

## Pasos para reproducir (para bugs)

Realice los cambios en los archivos que se muestra en el pull request #3360

## Contexto
El objetivo erra cambiar el mensaje de error que se muestra cuando se agrega un usuario no registrado en un curso.

**Comment by pabo99** [comment]
Pareciera que el fix que agregué en #3384 No ayudó a corregirlo del todo. Habrá que revisar la causa del problema

**Comment by lhchavez** [comment]
escalando a P0 porque está evitando que Travis funcione bien.

**Comment by pabo99** [comment]
Lo primero que tendremos que hacer es ver de donde sale ese usuario que tiene mejor rankeo que el de la prueba. 

Estaba pensando que agregar más envíos del mismo problema no ayuda en mucho porque esto no incrementa su puntaje, así que habrá que intentar crear más problemas y que tenga envíos de cada uno de ellos.

**Comment by RuizYugen** [comment]
No seria bueno modificar el numero de problemas que se envían en coderOfTheMonthTest.php a un numero considerable

**Comment by RuizYugen** [comment]
Puede que el problema sea en que las pruebas de las badge de experto tienen 11 problemas en las pruebas de coderOfTheMonth tenga menor que esas y por eso falle

**Comment by lhchavez** [comment]
la cosa con seguirle subiendo a ese número es que las pruebas que dependen de que un usuario "sea el mejor" van a empezar a competir entre ellas y nunca vamos a encontrar un número "considerable" :(

las pruebas de los badges son inocentes: corren después y limpian la base de datos antes de correr. y habiendo dicho eso, quizás esa es la solución de corto plazo: limpiar la base de datos antes de correr la prueba que falla.

luego podemos reorganizar el código de manera que la base de datos se limpie antes de correr _cada prueba_; ese sería la solución a largo plazo.
