### ISSUE TITLE
[FEATURE] Como un usuario, quiero poder buscar si otro usuario ya resolvió un problema en específico

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#3397]
## Comportamiento Esperado

Recientemente hicieron un cambio que ahora los problemas resueltos en el perfil de usuario están siendo paginados, lo cual es bueno para que se vea bonito, pero ahora ya no puedo buscar si uno de mis alumnos ya resolvió o no un problema, ahora tengo que dar click en siguiente constantemente y buscar en cada pagina de resutlados.... hay alguna forma fácil de saber si alguien ya hizo o no un problema o hay planes de agregar ese feature?

## Posible Solución

Una opción de búsqueda en el perfil del usuario, y que te ponga si ya lo resolvió o lo intentó.

## Contexto

Necesito saber si uno de mis alumnos ya hizo un problema antes de dejárselo, el problema lo pudo haber resuelto ayer o el año pasado.

**Comment by lhchavez** [comment]
la búsqueda en el perfil suena razonable.
