### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#3403]
## Comportamiento Esperado

Como un administrador de un grupo debería ver la pestaña `Crear Identidades` además de `Miembros` y `Scoreboards`.

## Comportamiento Actual

Solamente se muestran las pestañas `Miembros` y `Scoreboards`.

## Pasos para reproducir (para bugs)

1. Login
2. Concursos -> Mis grupos
3. Dar click al grupo que ya existe `omips-2020`

Flujo alternativo
1. Login
2. Concursos -> Mis grupos
3. Crear un grupo

## Contexto

Estoy intentando generar los usuarios para la 5a OMIPS.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2 (19C57)
* Link al sitio en el que este problema pasa: https://sandbox.omegaup.com/group/omips-2020/edit/#identities
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5167417/73596393-70462200-44e7-11ea-8e35-28a92b05dc36.png)

**Comment by lhchavez** [comment]
esto te sigue pasando? te hice admin de ese grupo hace rato

**Comment by lhchavez** [comment]
ah faltaba hacerte miembro de `omegaup:group-identity-creator`.
