### ISSUE TITLE
[BUG] Limite de registros en Identidades de concursos

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#3419]
## Comportamiento Esperado

Al dar click en crear identidades, deberían crearse las identidades sin importar cuántos registros sean.

## Comportamiento Actual

Subiendo un archivo con 143 registros, al dar click en crear identidades, regresa un error 400 con el mensaje `Empty parameter.: group_alias`

Aquí pueden ver el request gigantón https://gist.github.com/andreasantillana/29850ee3bda70d4417b56bc8effa1ee4

y el response
```
{"status":"error","error":"Empty parameter.: group_alias","errorname":"parameterEmpty","errorcode":400,"header":"HTTP\/1.1 400 BAD REQUEST","_id":"5e38e1ffd5b3d026994206"}
```

## Pasos para reproducir (para bugs)

1.  En un grupo ir a la tab `Crear identidades`
2. Subir un archivo con143 participantes.
3. Dar click en `Crear identidades`

## Contexto

Para la OMIPS se tuvieron que subir varios archivos para poder registrar a todos los participantes.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Version 79.0.3945.130 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2 (19C57)
* Link al sitio en el que este problema pasa: https://omegaup.com/group/OMIS2020/edit/#identities
* Captura de pantalla:
![image (1)](https://user-images.githubusercontent.com/5167417/73712255-20c24a80-46cf-11ea-8aa3-d492b2404f58.png)

**Comment by lhchavez** [comment]
esto es una limitación de PHP que por default no soporta más de 1000 "parámetros" y falla **silenciosamente** :/ https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars

esto le manda 7 parámetros por registro, así que con 144 excede el límite. algo que podemos hacer es mandar un JSON para que sea un sólo parámetro
