### ISSUE TITLE
[FEATURE] Insignias - No todas las insignias obtenidas están coloreadas

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3427]
## Comportamiento Esperado

Cuando veo el perfil de un usuario, las insignias que ha desbloqueado deberían aparecer coloreadas.

## Comportamiento Actual

Sólo algunas de las insignias que el usuario ha obtenido salen coloreadas. Este es el caso del coder del mes actual:
https://omegaup.com/profile/JJHernandez
![image](https://user-images.githubusercontent.com/207097/73851078-c1a12a80-47e1-11ea-87f4-d101cced7e6f.png)

Después, al dar click en todas las insignias el problema es más evidente. Dado que el badge de Usuario Histórico está prendido, sospecho que el request que colorea badges se hace bajo mi usuario y no del usuario del cuál estoy viendo el perfil:

![image](https://user-images.githubusercontent.com/207097/73851246-0200a880-47e2-11ea-9b2c-ef4e83e1533a.png)

## Posible Solución

Hay que revisar el contexto de la api que regresa los badges obtenidos :)

## Pasos para reproducir (para bugs)

https://omegaup.com/profile/JJHernandez

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 79.0.3945.117
* Sistema Operativo y versión (escritorio o móvil): Mac OS
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/JJHernandez
* Captura de pantalla: (agregadas en el reporte)

**Comment by tvanessa** [comment]
Platicando offline la propuesta es cambiar el string "Ver todas" (las insignias), pues ese texto da a entender que no se estan mostrando todas las insignias de un usuario especifico.

**Comment by carlosabcs** [comment]
Me avisan si necesitan que haga alguna modificación respecto a esto.

@joemmanuel creo que Vanessa ya te lo comentó pero lo pondré de todas formas, sea que estés viendo las insignias en el perfil de un usuario, o en la lista general, solo te apareceran coloreadas aquellas que ya obtuviste. Esto se hizo como una similitud a los "personajes desbloqueables" en algunos videojuegos.

**Comment by heduenas** [comment]
Yo creo que valdría la pena cambiar "Ver todas" por "Ver todas las insignias disponibles" para que evitar la confusión.
