### ISSUE TITLE
[FEATURE] Como usuario, quiero publicar mis insignias en Social Media para reafirmar mis logros

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3428]
## Comportamiento Esperado

Agregar una funcionalidad que permita postear en Social Media (Facebook, Twitter, Instagram, etc...) la lista de badges obtenidos y cada uno de los badges individualmente (https://omegaup.com/badge/coderOfTheMonth/)

## Comportamiento Actual
No hay forma de compartir logros externamente.

## Contexto
Hay 2 objetivos, el primero es darle oportunidad a los usuarios de reafirmar y publicar sus logros en Social Media, el otro es crear más tracción y engagement en el sitio a través de los badges publicados.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
* Sistema Operativo y versión (escritorio o móbil):
* Link al sitio en el que este problema pasa:
* Captura de pantalla:

**Comment by tvanessa** [comment]
Duplicado de #2750
