### ISSUE TITLE
[BUG] No se actualiza el tiempo de termino de un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3437]
Cambie la duracion del curso de c++ a infinito y se guardo bien.
![Screen Shot 2020-02-07 at 5 52 12 PM](https://user-images.githubusercontent.com/13296248/74077199-c24ce300-49d2-11ea-8360-11da396125ef.png)

Pero cuando entro a alguna tarea me dice que termina en 8 meses:

![Screen Shot 2020-02-07 at 11 54 14 AM](https://user-images.githubusercontent.com/13296248/74077212-d690e000-49d2-11ea-95c0-a78d194088fc.png)

**Comment by carlosabcs** [comment]
@tvanessa te falta actualizar cada tarea a: "Duración ilimitada".

Cuando tienes un curso con duración ilimintada, puedes tener tareas con duración ilimitada también, o no.
