### ISSUE TITLE
[BUG] Las consultas del ranking de escuela del mes son muy lentas

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#3438]
## Comportamiento Esperado

Las consultas del ranking de escuela del mes deberían ser rápidas.

## Comportamiento Actual

La consulta de ranking de escuela del mes puede tardar varios segundos en terminar. Si resulta que es necesario recalcular el ranking de la escuela del mes, puede darse el caso de que múltiples hilos de PHP van a terminar haciendo el mismo request a la base de datos, causando que cada consulta individual tarde más por la carga extra, causando que la probabilidad de que más usuarios hagan la misma petición que causa que se intente recalcular el ranking, exacerbando el problema. Actualmente tenemos un cache para intentar mitigar esto, pero resulta que es muy fácil que haya un [cache stampede](https://en.wikipedia.org/wiki/Cache_stampede), _especialmente_ si se reinicia el servicio de PHP por cualquier razón, porque esto causa que el cache se limpie. Para empeorar la situación, tenemos un watchdog que reinicia PHP cuando empieza a regresar 502, entonces si el servicio llega a tener cierta cantidad de carga que causa que el número de procesos no sea suficiente para atender la carga adicional, PHP regresa 502 y simultáneamente crea más procesos hijo (todos con el cache vacío), y eso hace que el watchdog entre en acción y reinicie PHP.

## Posible Solución

Por ahora se van a desactivar todas esas consultas hasta que se arregle el problema de raíz. Necesitamos hacer dos/tres cosas:

a) Agregarle un mecanismo al cache para que a lo más un proceso haga la actualización del cache. Eso cambiaría el cache stampede por un [thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem), pero así al menos no tiraría la base de datos.
b) Si hay consultas que tardan mucho, esas deberían hacerse en un cronjob y guardar los resultados en un JSON / redis.
c) Si es posible, hay que hacer que esas consultas no sean lentas (gracias, capitán obvio!).

## Contexto

Esto tiró omegaUp por ~1 hora durante la OMIP/S 2020.

**Comment by pacharrin** [comment]
para evitar el thundering herd propongo que no esperen por la actualización. que se queden con el último conocido.

No es crítico tener el ranking en tiempo real.

**Comment by lhchavez** [comment]
la cosa es que no existe el último conocido. no hay manera sencilla de resolverlo en el escenario que tiró producción hoy :(

**Comment by lhchavez** [comment]
lo que falta de este issue: tener un ranking materializado (una tabla/columnas indexadas que contenga esta información precalculada, como la del ranking de usuarios) y correr la consulta necesaria para actualizarla en un cronjob.

@carlosabcs FYI
@tvanessa / @heduenas será posible priorizar esto?

**Comment by carlosabcs** [comment]
> lo que falta de este issue: tener un ranking materializado (una tabla/columnas indexadas que contenga esta información precalculada, como la del ranking de usuarios) y correr la consulta necesaria para actualizarla en un cronjob.
> 
> @carlosabcs FYI
> @tvanessa / @heduenas será posible priorizar esto?

El rank de escuelas ya se actualiza a través de un cronjob (`update_ranks.py`) y estamos usando el campo `rank` en `Schools` para almacenar la posición en el ranking de cada escuela.
¿A parte de eso, qué debería hacer?

**Comment by lhchavez** [comment]
eliminar todas las consultas en https://github.com/lhchavez/omegaup/commit/8388f5e6b0484d0d6223a89235c0a89b9f1b2946 para que usen la información del cronjob.
