### ISSUE TITLE
Las cuentas creadas de manera automatica no estan verificadas y no tienen un correo asignado.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#3443]
## Comportamiento Esperado

Necesito entrar a las cuentas creadas para la olimpiada mexicana de informatica con sede en Chihuahua para hacer la olimpiada estatal.

## Comportamiento Actual

No permite el acceso a dichas cuentas debido a que no han sido verificadas y no tienen correos asignados

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Ingresar al login
2. Ingresar los datos de una cuenta creada de manera automatica

## Contexto

Se necesita ingresar a las cuentas creadas de manera automatica para la olimpiada mexicana de informatica en la sede estatal de Chihuahua

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome más reciente a la fecha.
* Sistema Operativo y versión (escritorio o móvil): OS 10.15
* Link al sitio en el que este problema pasa: https://omegaup.com/login/?redirect=%2F
* Captura de pantalla:
<img width="1192" alt="Captura de Pantalla 2020-02-10 a la(s) 19 11 42" src="https://user-images.githubusercontent.com/5459260/74204549-47d1cc80-4c39-11ea-9e3b-a0a14eb0dd24.png">

**Comment by MiguelRomero** [comment]
@LaloRivero

**Comment by lhchavez** [comment]
pueden intentar https://blog.omegaup.com/administracion-de-identidades/ ? si sí, avísenme qué usuario es el que va a crear las identidades para agregarlo a la lista de usuarios que pueden crearlas.

**Comment by LaloRivero** [comment]
@lhchavez Seria mi usuario: LaloRivero, de ante mano gracias!

**Comment by lhchavez** [comment]
listo, ya debes poder seguir el tutorial. cerrando el issue.

si te atoras en algo del tutorial házselo saber a @MiguelRomero y/o crea un issue nuevo.
