### ISSUE TITLE
[FEATURE] Como un desarrollador, quiero no volver a ver knockout para enfocarme en Vue

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#3456]
Todavía hay algunas dependencias a knockout en el código. Deberiamos cambiar todo eso a Vue.

## Comportamiento Esperado

Deberíamos consolidar la tecnología de plantillas en Vue y no usar otras cosas.
Esto es similar a #2009 pero en referencia a Knockout en lugar de Smarty

## Comportamiento Actual

Hay funcionalidad que depende de Knockout. En particular la puntuación de envíos en la Arena.

**Comment by pabo99** [comment]
Haré una lista con las funcionalidades que dependen de Knockout, para poder dar seguimiento de la migración:

- [ ] Clarifications Notifications (www/js/omegaup/arena/notifications.js) PR: #2909 En revisión.
- [ ] Contest List (www/js/omegaup/arena/contest_list.js) PR:____ Estatus:____
- [ ] Summary View (www/js/omegaup/arena/arena.js) PR:____ Estatus:____
- [ ] Run View (www/js/omegaup/arena/arena.js) PR:____ Estatus:____
- [ ] Observable Run (www/js/omegaup/arena/arena.js) PR:____ Estatus:____

Si me falta alguna, favor de agregarla.

**Comment by lhchavez** [comment]
@tvanessa @heduenas será posible meter #3610 al siguiente sprint que sea posible? si ese se resuelve, se puede mover un hack gigante de https://github.com/omegaup/omegaup/blob/dedade699eec4526a198f1fbf109592916250bfc/frontend/www/js/omegaup/omegaup.js#L11-L38 a los archivos de arena, lo cual va a hacer más fácil la migración de más código a TypeScript!
