### ISSUE TITLE
Concursos[BUG]

### ISSUE THREAD

**Issue by cfemat** [omegaup/omegaup#3459]
## Desarrollo de concurso

*Concurso programado.
*

## Error en envios y view de los problemas.

*El concurso comenzó a tardar en cargar, los problemas no se muestran en algunos equipos (arroja un error en el JSON), en los equipos que se muestran al intentar realizar un envío no se puede enviar, igual arroja error en la sintaxis del JSON *

## Comprobamos que fuera la conexión, pero no importando la red, por lo que el error es de la plataforma.

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

*Vínculo para el concurso*

1. https://omegaup.com/arena/1ER4IM42020#problems
2. 
3. 
4. 

## Contexto

*Estabamos aplicando un examen en una escuela de la asignatura de programación, para la cual se utiliza OmegaUp*

## Examen

*La única variación que pudiera afectar es el número de estudiantes que estaban en el examen, sin embargo no se había tenido este problema anteriormente.*

* Nombre del navegador : Chrome
* Sistema Operativo y versión Windows / escritorio 
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/1ER4IM42020#problems
* Captura de pantalla: 
![imagen](https://user-images.githubusercontent.com/56486587/74756070-a4387b80-5239-11ea-836a-bb2616ba3e3a.png)

**Comment by tvanessa** [comment]
Este issue ya fue atendido.
