### ISSUE TITLE
[FEATURE] Como usuario coder necesito dar de baja mi cuenta.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#3460]
## Comportamiento Esperado

Al yo presionar un boton de "Eliminar cuenta" me permita eliminar mi cuenta de la plataforma omegaUp.

## Comportamiento Actual

No existe.

## Contexto

Yo como usuario de omegaUp necesito eliminar mi cuenta actual.

**Comment by pabloaguilar** [comment]
Dupe de #2638
