### ISSUE TITLE
[FEATURE] Migrar a mysql8

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3462]
Para optimizar los queries de ciertos badges

**Comment by lhchavez** [comment]
21 horas? ja! esto va a tomar varios meses.

**Comment by lhchavez** [comment]
Justo cuando pensaba que iba a estar listo esta semana, #3557 lo está bloqueando u_u

**Comment by lhchavez** [comment]
```
Engine version
8.0.17
```
