### ISSUE TITLE
[BUG] Comportamiento inesperado con tags html en casos de ejemplo

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3479]
Hola amigos de omegaUp. Mis alumnos de servicio social andan checando los problemas de la plataforma y encontraron un grupito de problemas a los que se les debe corregir el markdown (usaban html en los casos de ejemplo). Un ejemplo de ellos es https://omegaup.com/arena/problem/Canguros#problems. 

Sin embargo, mi reporte va con respecto a https://omegaup.com/arena/problem/AcomodandoOMI#problems y otro similar: encontré que está usando tags html (en concreto, el tag `<pre>`) pero el parser del markdown lo está dejando pasar en los casos de ejemplo (es decir, no le hace _escape_ sino que lo honra). Si bien `<pre>` es inofensivo, mando el reporte porque sospecho que la intención es que ningún tag se escape (por ejemplo, `<br>` ya no se honra sino que aparece textuamente `<br>`).

**Comment by lhchavez** [comment]
Tenemos un whitelist de tags que honramos: https://github.com/omegaup/omegaup/blob/471f0f6e27402d29ad15dc26ea9c2445ccdc7d52/frontend/www/js/omegaup/ui.js#L707

peeeero dentro del contexto de casos de ejemplo la intención es escapar todo O__O. así que hay que corregir eso.
