### ISSUE TITLE
[FEATURE] Vuefication arena index: arena.index.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3481]
Smarty template `arena.index.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Esto se migró en el cambio #4062, así que ya se puede cerrar.
