### ISSUE TITLE
[FEATURE] Vuefication arena competition: arena.contest.interview.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3486]
Smarty template `arena.contest.interview.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este archivo y todos los referentes a Interviews se van a eliminar en el PR #5542, así que se puede cerrar.
