### ISSUE TITLE
[FEATURE] Vuefication arena competition: arena.runs.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3488]
Smarty template `arena.runs.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Esto se terminó de migrar en el PR #3725. Ya se puede cerrar
