### ISSUE TITLE
[FEATURE] Vuefication Courses: course.edit.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3493]
Smarty template `course.edit.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este cambio, al igual que #3954, va a ser muy extenso (Nada más del archivo que se va a migrar de `.js` a `.ts` son 700 líneas). Lo mejor será partirlo en varios pedacitos y quizás para este milestone sólo nos enfoquemos en la creación del componente en la plantilla unificada (sin que se muestre aún). ¿Que te parece @tvanessa?

**Comment by tvanessa** [comment]
Sí, suena bien. Quieres abrir más issues para cada parte?

**Comment by pabo99** [comment]
Si, en un momento los creo.
