### ISSUE TITLE
[FEATURE] Vuefication Group: group.scoreboard.edit.contests.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3498]
Smarty template `group.scoreboard.edit.contests.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este archivo se migró en el PR #5006. Así que se cierra el issue.
