### ISSUE TITLE
[FEATURE] Vuefication: user.edit.tpl

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3502]
Smarty template `user.edit.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este archivo se migró en el PR #5452. Así que se cierra.

**Comment by pabo99** [comment]
Assigned to: @luis-8
