### ISSUE TITLE
[BUG] API: "/contest/create"problema al introducir valores al parámetro "points_decay_factor"

### ISSUE THREAD

**Issue by Dannyell001** [omegaup/omegaup#3517]
## Comportamiento Esperado

El parámetro points_decay_factor espera un double.

## Comportamiento Actual

Al momento de hacer el POST, marca un error de campo vacío 

## Contexto

Intento crear un contest a través de la API, pero no puedo crearlo por el error que me dice que el campo está vacío. Ya he iniciado sesión para hacer este POST.

Sistema Operativo y versión (escritorio o móvil): Windows 10, escritorio
Programa utilizado: Postman
Captura de pantalla: ![image](https://user-images.githubusercontent.com/36236722/75834090-a560c100-5d80-11ea-8639-c8de42c46298.png)

**Comment by lhchavez** [comment]
al final cuál fue el problema? sólo por curiosidad

**Comment by Dannyell001** [comment]
Hola

Fue error mío, puse un espacio después del nombre de points_decay_factor.

Gracias por preguntar
________________________________
De: lhchavez <notifications@github.com>
Enviado: miércoles, 4 de marzo de 2020 11:20 a. m.
Para: omegaup/omegaup <omegaup@noreply.github.com>
CC: Dannyell001 <d-alvarez1@live.com.mx>; State change <state_change@noreply.github.com>
Asunto: Re: [omegaup/omegaup] [BUG] API: "/contest/create"problema al introducir valores al parámetro "points_decay_factor" (#3517)


al final cuál fue el problema? sólo por curiosidad
