### ISSUE TITLE
[BUG] Volver público/privado un problema desde la lista de problemas resetea la salida límite

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3521]
Hola amigos de omegaUp.

El día de ayer acabó el concurso anual de la UAM y volví públicos los problemas usando la opción disponible en la lista de problemas.
![imagen](https://user-images.githubusercontent.com/19719969/75935657-782a1680-5e45-11ea-9024-eed0382b43ad.png)
Sin embargo, hace unos minutos me metí a ver el ranking del concurso y noté que algunos participantes tenían 50% en un problema donde ya tenían el 100% (el problema es https://omegaup.com/arena/problem/Paisajes-de-la-ciudad/#problems). Al entrar al problema, vi que ya no había envíos aceptados (incluso los que yo hice al subir el problema) y el diagnóstico era límite de salida excedido. Modificando el límite se arregló, pero hice otra prueba (ahora poniéndolo privado desde la lista de problemas) y el límite de salida se volvió a cambiar a su valor por omisión (que no es suficiente para resolver el problema).

Aprovecho para preguntar: tenía la impresión de que el límite de salida se estimaba automáticamente con los .out que los autores subíamos, pero que eso en algún momento dejó de pasar. ¿Sí se autocalculaba o sólo era mi impresión? en caso afirmativo, era bastante útil.

**Comment by lhchavez** [comment]
huh, ese problema no tiene validador personalizado (que se supone que es el único caso donde _no_ recalculamos el límite), así que debería de preservar lo que hubiera tenido antes. esto es una regresión.
