### ISSUE TITLE
[FEATURE] Añadir modo ICPC a concursos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3532]
Actualmente tenemos modos OMI, IOI y CONACUP. Pero no hay modo ICPC que permita evaluar los problemas como _todo o nada_

**Comment by heduenas** [comment]
Para precisar, en ICPC a diferencia de los concursos de omegaUp:
* No hay puntaje parcial. Si el programa fallo en por lo menos un caso, el problema da 0 puntos.
* El feedback no incluye el % de casos que si paso. Solo da el veredicto (AC, WA, TLE, etc) sin entrar en mas detalle.
* Un equipo no puede ver el veredicto de los envios de otro equipo en el scoreboard, a menos de que este sea AC. O sea, un equipo puede saber cuales problemas ha resuelto otro equipo, cuales problemas ha intentado pero no resuelto, cuantas veces lo ha intentado, pero no puede saber si fueron WA o TLE, etc. Ver [1].

[1] Un ejemplo de un scoreboard de un concurso ICPC: http://scorelatam.naquadah.com.br/

**Comment by pabo99** [comment]
-  Hay que generar un documento de diseño.

**Comment by pabo99** [comment]
El link al documento de diseño se encuentra en:

https://docs.google.com/document/d/1GyWiRykBA52xaODDWHdnLlhAm4H9vvL8yz4vwzPEgCM/edit
