### ISSUE TITLE
[FEATURE] Reconsiderar cómo mostrar la gráfica de envíos en vista de perfil

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#3534]
Según analytics, la vista de perfil de ciertos perfiles es muy pesada.
Crea algo del orden de 1500 elementos DOM para alguien que ha resuelto ~500 problemas.

Este es el ejemplo:
http://www.omegaup.com/profile/NetoDios

Un par de sugerencias (para agregar en el rediseño de perfiles de usuario):

* Determinar qué vista mostrar por default (por día, por semana, por mes) dependiendo del número de envíos
* (de npave@) Enviar solo los últimos N días

![image](https://user-images.githubusercontent.com/189223/76157699-41f8cb00-60c1-11ea-8f76-874fb702f605.png)

**Comment by pabo99** [comment]
La forma en que funcionan las gráficas actualmente es obteniendo todos los envíos que ha realizado el usuario, sin importar las fechas en las que los haya hecho. Todos los cálculos se realizan de lado del cliente. Con lo cual, hago las siguientes observaciones para las dos propuestas:

> * Determinar qué vista mostrar por default (por día, por semana, por mes) dependiendo del número de envíos

Tendría que modificarse la lógica para que todos los cálculos se realicen desde el servidor, y así poder determinar cual será la vista default.

> * (de npave@) Enviar solo los últimos N días
 
Esto ocasionaría que se muestren gráficas vacías cuando los usuarios tienen periodos largos de inactividad. 
Una alternativa a esta opción es enviar sólo los N últimos envíos sin importar la fecha en la que se hayan realizado.

En caso de que se decida la solución de los últimos N días o los últimos N envíos, se tendría que agregar una leyenda que lo especifique.

**Comment by tvanessa** [comment]
@pabloaguilar esto se resolvio con el nuevo diseño de perfil?
