### ISSUE TITLE
[FEATURE] El tab Concursos actuales recomendados usualmente esta vacio

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3535]
Sugerencia 1: ocultar el tab si esta vacio

Sugerencia 2: Mostrar un texto que diga que por el momento no hay concursos recomendados

![image](https://user-images.githubusercontent.com/13296248/76157712-a3b93500-60c1-11ea-8e32-5affb9d01668.png)

**Comment by pabo99** [comment]
La sugerencia 2 se está trabajando en el PR #3523 

![image](https://user-images.githubusercontent.com/3230352/76166702-296ecc00-6126-11ea-9e8a-77fd0c888269.png)

Ya está en revisión.

**Comment by pabo99** [comment]
Este issue ya se puede cerrar, porque ya se ve reflejado el cambio en producción:

![image](https://user-images.githubusercontent.com/3230352/76182999-843b0e80-618c-11ea-8bbf-2b95a8a8ac64.png)
