### ISSUE TITLE
Canned responses para las clarificaciones

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#354]
En casi todos los concursos cuando entras como administrador, te permite contestar clarificaciones usando un texto arbitrario. idealmente hay que mostrar también un dropdown que te permita elegir:

* Sí
* No
* Sin comentarios
* Vuelve a leer el problema
* Otro

y sólo si elige `Otro`, mostrar el textbox.

**Comment by lhchavez** [comment]
El reglamento de la OMI indica que _tenemos_ que responder con "Sí", "No" y "Sin comentarios".

**Comment by erosethan** [comment]
Pls make "Vuelve a leer el problema" happen.

**Comment by lhchavez** [comment]
Eso suena bien. Agregado.
