### ISSUE TITLE
Los errores que se despliegan cuando se intenta subir un problema mal-formateado no me dicen cómo resolver los errores

### ISSUE THREAD

**Issue by Arthusr56** [omegaup/omegaup#3546]
## Comportamiento Esperado

Quiero crear un problema, llene los espacios para crear un problema y agregue el archivo zip con los casos y la redaccion para crear el problema.

Si el .zip tiene errores, debería mostrar un mensaje ayudándome a resolverlos.

## Comportamiento Actual

Omegaup no me deja crearlo, dice que "No se encontraron redacciones"
![Cap1](https://user-images.githubusercontent.com/56237061/76657754-32053f00-6538-11ea-84a2-eaa882a6af73.PNG)

![Cap2](https://user-images.githubusercontent.com/56237061/76657762-35002f80-6538-11ea-9b70-1e74f4133a3b.PNG)

**Comment by lhchavez** [comment]
hay que crear subcarpetas para los casos y las redacciones. aquí en este link está cómo hacerlo y algunos ejemplos: https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-escribir-problemas-para-omegaUp

**Comment by Arthusr56** [comment]
Oh, ya entiendo, gracias por su ayuda
