### ISSUE TITLE
[BUG] Varias tablas/columnas de MySQL tienen nombres reservados

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#3557]
## Comportamiento Esperado

La base de datos se debería poder actualizar a MySQL 8 en Amazon.

## Comportamiento Actual

Debido a los siguientes errores, la base de datos no se puede actualizar:

```
2) Usage of db objects with names conflicting with new reserved keywords
The following objects have names that conflict with new reserved keywords. Ensure queries sent by your applications use `quotes` when referring to them or they will result in errors.
More Information:
https://dev.mysql.com/doc/refman/en/keywords.html

omegaup.Groups - Table name
omegaup.Coder_Of_The_Month.rank - Column name
omegaup.School_Of_The_Month.rank - Column name
omegaup.Schools.rank - Column name
omegaup.User_Rank.rank - Column name
```

## Posible Solución

Lamentablemente hay que cambiar el nombre de la tabla `Groups` y todas las columnas que se llaman `rank`.

**Comment by pabloaguilar** [comment]
Y qué tal ponerle un sufijo `_` ?
Se ve feo pero es mas claro que buscar sinónimos menos obvios

**Comment by lhchavez** [comment]
a `Groups`? supongo que puede funcionar. los otros pueden llamarse `ranking`

**Comment by lhchavez** [comment]
Listo, lo único que falta es cambiar todas las columnas llamadas `rank`.

@tvanessa @heduenas pueden asignar este issue? Ya no me dio tiempo de seguirle :/

**Comment by tvanessa** [comment]
Se asigna a @RuizYugen
