### ISSUE TITLE
Descargar códigos sin usar copy-paste

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#356]
Si abres un concurso, haces un envío y luego haces click en el botón de detalles, la única manera de descargar el código es usando copy/paste. debería haber un link que te deje bajar el archivo con la extensión correcta.

**Comment by lhchavez** [comment]
esto son dos líneas de javascript.

**Comment by lhchavez** [comment]
Resulta que el fix no funciona en la vista de "solo problema" :( (por ejemplo https://omegaup.com/arena/problem/sumas#runs )

**Comment by pabo99** [comment]
Para este bug, ¿tengo que hacer un nuevo pull request?

**Comment by lhchavez** [comment]
sí :( si todavía tienes la rama en tu fork, puedes empezar con esa. si no, puedes crear una rama y hacer `git revert 3b592b58700e0262057c02d7a4b1f3206f777078` para "re-aplicar" tu cambio.
