### ISSUE TITLE
[BUG] Algunos caracteres latinos no se muestran correctamente

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3560]
Hola amigos de omegaUp.

Reporto este problema que ya lleva tiempo, pero que no había reportado de forma individual.
En algunos problemas, los caracteres latinos (ej. acentos, ñ) no se están mostrado correctamente. Un ejemplo es https://omegaup.com/arena/problem/Monedas-volteadas-en-intervalos/#problems

El problema no se corrige aún si elimino los caracteres latinos (ej. quitando acentos), lo guardo y luego los vuelvo a poner usando el editor. Lo raro es que sólo en algunos problemas ocurre este fenómeno.

**Comment by pabloaguilar** [comment]
Me robé tu problema y lo subí a sandbox.omegaup.com con varios formatos.
Hasta donde puedo ver los encodings de `UTF-8 with BOM` y `ANSI` funcionan bien, pero `UTF-8  without BOM` no. Supongo que nuestro auto-detector de UTF-8 está descompuesto y supone que UTF-8 sin BOM es ANSI.

Yo uso Notepad++ y con eso puedo controlar explícitamente el con/sin BOM.

En cuanto a modificar el problema dentro del editor, me imagino que el record de con/sin BOM es persistente de alguna manera (e.g. el editor ver el contenido que es ANSI, te permite poner acentos, pero sigue grabando en modo ANSI).

**Comment by lhchavez** [comment]
cuando hay un BOM explícito, ese es el caso fácil porque el BOM nos dice qué encoding tiene: https://github.com/omegaup/gitserver/blob/6802d7c58b335636c444539ea394ba7435f56b6d/normalizer.go#L44-L72

cuando no hay, se usa https://godoc.org/github.com/saintfish/chardet#NewTextDetector que supongo sí se puede confundir con ISO 8859-1-EN o Windows 1251(_muy_ cerca a ANSI). esa librería cuando no tiene BOM y todo el texto es UTF-8 válido, [_debería_ decir que es UTF-8](https://github.com/saintfish/chardet/blob/3af4cd4741ca4f3eb0c407c034571a6fb0ea529c/utf8.go#L60-L61), pero posiblemente haya que manejarlo a mano por fuera para que no haya sorpresas.

**Comment by lhchavez** [comment]
ok, ya entendí el problema! esa librería cuenta el número de caracteres UTF-8 válidos (que _no_ son ASCII) y el número de caracteres inválidos. como esa redacción "sólo" tiene tres caracteres con acento, el algoritmo de chardet no muestra mucha confianza que es UTF-8 válido. Si le agregas un cuarto, muestra 100% confianza de que es UTF-8.

_entonces_ lo que voy a hacer es lo que dije en [el comentario anterior](https://github.com/omegaup/omegaup/issues/3560#issuecomment-600666840): si es UTF-8 válido de antemano, no pasárselo a chardet.

**Comment by darkmx** [comment]
Acabo de revisar https://omegaup.com/arena/problem/Monedas-volteadas-en-intervalos/#problems y sigue viéndose mal :( intenté también borrar las basuritas y acentos, guardar, luego volver a poner acentos y sigue cucho. Intenté hacer la prueba en sandbox.omegaup.com por si el bugfix aún no está live, pero me mandó un error interno.
