### ISSUE TITLE
[BUG] Internal Server Error al buscar un problema

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3574]
Hola amigos de omegaUp.

Al buscar un problema, omegaUp está devolviendo el código de error 500.
Parece que el problema es el `order_by=title`
https://omegaup.com/problem/?query=monedas&order_by=title

ya que esto funciona
https://omegaup.com/problem/?query=monedas&language=all&mode=asc

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/3561

**Comment by darkmx** [comment]
oops D: sorry
