### ISSUE TITLE
[BUG] La plataforma no devuelve la lista de tags completos para usarse en el buscador

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3579]
Hola amigos de omegaUp.

Recientemente se ha limitado la cantidad de registros que las distintas apis de omegaUp devuelven. Parece que https://omegaup.com/api/tag/list/ (cuando se invoca correctamente) devuelve únicamente 100 tags. Como el buscador avanzado usa esa lista precargada de tags, algunos tags no aparecen en la búsqueda (por ejemplo, "arboles" que sí existe https://omegaup.com/problem/?tag[]=arboles).

![imagen](https://user-images.githubusercontent.com/19719969/77235995-0dd0e000-6b80-11ea-83cb-b3ae1b93f59d.png)

Esto lo descubrí buscando alguna forma de extraer la lista completa de los tags que existen en la plafatorma.

**Comment by pabo99** [comment]
Parece ser que siempre ha estado así esa búsqueda. @lhchavez podremos quitar el límite que obtiene los tags cuando se manda llamar desde la búsqueda avanzada de problemas?

**Comment by lhchavez** [comment]
prefería buscar otra alternativa: esos límites están ahí para prevenir DoS accidentales.

**Comment by pabo99** [comment]
Se me ocurren dos opciones:
- Utilizar el `Typeahead` que se utiliza para buscar usuarios, problemas, etc. para que cada que el usuario escriba una letra se realice una búsqueda por medio de la API.
- Realizar dos idas a la base de datos: la primera que cuente el número de Tags que existen en la tabla y después obtener los tags con el límite que acabamos de obtener con la consulta anterior.

¿Cuál de las dos ideas suena mejor?
