### ISSUE TITLE
[BUG] Tabla de en envios totales esta fallando

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3587]
Esto es lo que se muestra: 

![image](https://user-images.githubusercontent.com/597815/77372902-0b0ef000-6d24-11ea-8493-ac5cd47729d6.png)

**Comment by pabo99** [comment]
Pareciera más bien que antes estaba fallando y ahora trata de funcionar correctamente. 

En concreto, la tabla de `Run_Counts` quizás no estaba almacenando el total de envíos desde el 12 de noviembre del 2017 y por algún cambio realizado el 23 de marzo de 2020 ya volvió a hacerlo correctamente. De cualquier forma, reviso cómo está la consulta para descartar esto que comento.
