### ISSUE TITLE
[BUG] Lista de las mejores 100 escuelas del mes pasado no se muestra

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3592]
## Comportamiento Actual
![image](https://user-images.githubusercontent.com/597815/77388442-5d183b80-6d4d-11ea-8332-19bf5e953889.png)

@carlosabcs eso es esperado para el mes de marzo? (veo que tampoco tenemos coder del mes de marzo y se que ese se debe de agregar a mano)

**Comment by carlosabcs** [comment]
Bueno, eso también tiene que ver con lo que comenté en slack. Pero por más que reviso el código, no encuentro la razón por la que se borró la escuela del mes que ya teníamos guardada.

**Comment by lhchavez** [comment]
se corrió manualmente la consulta y ya está no-vacía, pero sólo tiene una entrada. no se si eso es suficiente como para cerrar este bug, así que dejándolo abierto.

**Comment by carlosabcs** [comment]
> se corrió manualmente la consulta y ya está no-vacía, pero sólo tiene una entrada. no se si eso es suficiente como para cerrar este bug, así que dejándolo abierto.

Eso es porque para marzo la consulta que construí era para tener solo 1 escuela del mes (por eso solo aparecerá una en el top 100). De lo contrario, la consulta sería más compleja.
