### ISSUE TITLE
[FEATURE] Hacer que la arena se despliegue bien cuando el usuario aumenta el tamaño de los textos en su navegador

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#3616]
Como un participante de curso online, quiero que el tamaño de los textos se puedan hacer más grandes para poder visualizar correctamente lo que se está proyectando

## Comportamiento Esperado

Lo que se puede hacer es agregar un par de botones en la arena(tanto en la descripción del problema, como en donde se manda el código) los cuales sirvan para modificar el tamaño de la fuente, uno para disminuir (-) y otro para aumentar (+)

## Comportamiento Actual

Actualmente no existe nada relacionado, sólo las herramientas del navegador.

## Contexto

Estoy viendo el curso de aprende a programar de #QuedateEnCasaConomegaUp y uno de los comentarios de los participantes fue con respecto a eso, además de que si es necesario para que se pueda leer de una mejor forma.

## Tu ambiente

* Captura de pantalla:
Así es como se les está mostrando a los participantes:
![image](https://user-images.githubusercontent.com/3230352/77700100-27579a80-6f79-11ea-8cc7-5edc3d30d18d.png)

**Comment by lhchavez** [comment]
el zoom del navegador no es suficiente? ninguna otra página del mundo implementa esto porque asumen que el navegador lo hace.

**Comment by pabo99** [comment]
Si, parece que no se ve mal:
![image](https://user-images.githubusercontent.com/3230352/77700870-b74a1400-6f7a-11ea-8ebb-02ea8f319954.png)

Sólo habrá que dar feedback para que en el siguiente curso haga zoom desde el comienzo del curso.

También sería un poco molesto hacer zoom out cada que se abra la ventana de nuevo envío, ya que no se muestra el botón de "Enviar" ni siquiera hacendo scroll down:
![image](https://user-images.githubusercontent.com/3230352/77701118-2c1d4e00-6f7b-11ea-8c32-c88ab3e1f41c.png)

**Comment by lhchavez** [comment]
a-ha! eso segundo sí hay que arreglarlo!
