### ISSUE TITLE
[FEATURE] Considerar no desaparecer los tabs del navbar en las tareas de cursos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3618]
Por ejemplo en: https://omegaup.com/course/Curso-OMI/assignment/COMI-intro#problems

se ve asi:
![Screen Shot 2020-03-26 at 8 11 38 PM](https://user-images.githubusercontent.com/13296248/77718293-be374d80-6f9f-11ea-9489-a642b348eb96.png)

**Comment by lhchavez** [comment]
no es una regresión, así fue diseñada la arena para evitar distracciones, así que siempre ha sido así.

_peeeero_ en el contexto de tareas no estoy seguro si es lo deseado. en exámenes también de debería esconder?
