### ISSUE TITLE
[BUG] El autocomplete de problemas (al buscar) no considera todos los problemas

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3622]
Hola amigos de omegaUp.

Hace rato tuve que organizar un concurso de emergencia y necesitaba agregar un problema al concurso para poder ponerlo en modo público. El primer problema que se me vino a la mente es https://omegaup.com/arena/problem/suma-de-intervalos#problems y entonces escribí "suma de intervalos" en el buscador de la opción "Agregar problemas", únicamente para darme cuenta que el problema en cuestión no aparecía (aparecían otros similares, pero más difíciles).

![imagen](https://user-images.githubusercontent.com/19719969/77798793-2dad4b80-7039-11ea-9fb1-cc2e71e5efb6.png)

El problema también ocurre en el buscador normal de problemas.

![imagen](https://user-images.githubusercontent.com/19719969/77798838-40c01b80-7039-11ea-80a4-5a9ab53efc71.png)

Este issue en conjunto con #3558 es bastante molesto, ya que por #3558 yo había estado usando el buscador para encontrar mis propios problemas (hasta encontrarme con esta situación).

**Comment by tvanessa** [comment]
Si buscas por alias tampoco funciona?

**Comment by darkmx** [comment]
El autocomplete no, aunque logré agregar el problema que quería al concurso saltándome el autocomplete.

![imagen](https://user-images.githubusercontent.com/19719969/77806863-97ceec00-704b-11ea-9ce0-575092c8239e.png)

**Comment by darkmx** [comment]
Agrego otro par de problemas que no salen en el autocomplete (aunque la cosa no parece ser un fenómeno generalizado; estoy logrando encontrar problemas afectados por este issue pero al parecer no son la mayoría):

https://omegaup.com/arena/problem/Generando-rectangulos/#problems
![imagen](https://user-images.githubusercontent.com/19719969/77808052-9dc6cc00-704f-11ea-8112-cd5996eaa233.png)

https://omegaup.com/arena/problem/Extremos-de-una-funcion-cubica/#problems
![imagen](https://user-images.githubusercontent.com/19719969/77808140-e3839480-704f-11ea-91cb-00117e8dcde3.png)
