### ISSUE TITLE
[BUG] Prueba testGetSchoolOfTheMonth esta fallando.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3639]
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
...............................................................  63 / 563 ( 11%)
............................................................... 126 / 563 ( 22%)
............................................................... 189 / 563 ( 33%)
............................................................... 252 / 563 ( 44%)
............................................................... 315 / 563 ( 55%)
............................................................... 378 / 563 ( 67%)
............................................................... 441 / 563 ( 78%)
...EF.......................................................... 504 / 563 ( 89%)
...........................................................     563 / 563 (100%)
Time: 8.54 minutes, Memory: 122.00 MB
There was 1 error:
1) SchoolOfTheMonthTest::testGetSchoolOfTheMonth
Trying to access array offset on value of type null
/home/travis/build/omegaup/omegaup/frontend/tests/controllers/SchoolOfTheMonthTest.php:308
--
There was 1 failure:
1) SchoolOfTheMonthTest::testApiSelectSchoolOfTheMonth
Failed asserting that actual size 2 matches expected size 3.
/home/travis/build/omegaup/omegaup/frontend/tests/controllers/SchoolOfTheMonthTest.php:438

**Comment by carlosabcs** [comment]
Ah, esto también ya debe quedar cerrado gracias a #3640

**Comment by lhchavez** [comment]
volvió a ocurrir hoy: https://travis-ci.com/github/omegaup/omegaup/jobs/309488578

**Comment by lhchavez** [comment]
más déjà vu:

```
...............................................................  63 / 563 ( 11%)
............................................................... 126 / 563 ( 22%)
............................................................... 189 / 563 ( 33%)
............................................................... 252 / 563 ( 44%)
............................................................... 315 / 563 ( 55%)
............................................................... 378 / 563 ( 67%)
............................................................... 441 / 563 ( 78%)
..E............................................................ 504 / 563 ( 89%)
...........................................................     563 / 563 (100%)
Time: 8.52 minutes, Memory: 122.00 MB
There was 1 error:
1) SchoolOfTheMonthTest::testCalculateSchoolsOfMonth
OmegaUp\Exceptions\DatabaseOperationException: generalError
/home/travis/build/omegaup/omegaup/frontend/server/src/MySQLConnection.php:349
/home/travis/build/omegaup/omegaup/frontend/server/src/MySQLConnection.php:364
/home/travis/build/omegaup/omegaup/frontend/server/src/DAO/Base/SchoolOfTheMonth.php:257
/home/travis/build/omegaup/omegaup/frontend/tests/controllers/SchoolOfTheMonthTest.php:206
```

y el error es `Failed to query MySQL (1062): Duplicate entry '1-2020-04-01' for key 'School_Of_The_Month.rank_time'`
