### ISSUE TITLE
[FEATURE] Vistas en nomination/mine

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3698]
Modificar las cadenas Reportar Problema por "Reporte" ademas de la cadena ¿Por qué es inapropiado este problema? por "¿Por qué quieres reportar este problema?"

Modificar la vista de la tabla nomination/mine para que muestre solo las siguientes columnas:
Alias
Autor
Fecha
Estatus
Detalles

**Comment by lhchavez** [comment]
pregunta: por qué "Reporte"? Suena como el resultado de un análisis (un [informe](https://es.wikipedia.org/wiki/Informe) o su equivalente en inglés: [report](https://en.wikipedia.org/wiki/Report)).

la otra cadena sí suena bien.

**Comment by tvanessa** [comment]
Ah.. me referia al titulo del pop-up que aparece cuando le das click en "Reportar problema"

Mejor eliminamos el titulo de ese pop-up y conservamos el string "Reportar problema" (_sin punto_ por consistencia con los demas strings).
