### ISSUE TITLE
[BUG] Scrollbar no está presente cuando quieres ver los detalles de un envió

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#3700]
## Comportamiento Actual

No hay scrollbar aquí:
![image](https://user-images.githubusercontent.com/123875/78734057-10f7fa00-78fc-11ea-8143-bfa547c7dc21.png)

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome  80.0.3987.163; Firefox 74.0.1
* Sistema Operativo y versión (escritorio o móvil): Windows 10

**Comment by lhchavez** [comment]
cerrado en https://github.com/omegaup/omegaup/pull/3689
