### ISSUE TITLE
[BUG] No se puede desplazar en el código fuente

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#3716]
## Comportamiento Esperado

Al darle clic al botón de lupa para ver el código de un problema, y usar la rueda del mouse o touchpad, se puede desplazar para ver lo que sigue en el código fuente.

## Comportamiento Actual

Eso no sucede.

## Posible Solución

Agregar `overflow: auto` como atributo de CSS

## Pasos para reproducir (para bugs)

1. Abrir un problema
2. Darle al botón de lupa
3. Intentar desplazare

## Tu ambiente

Firefox 74, escritorio

**Comment by lhchavez** [comment]
Dupe de #3700. El domingo en la noche se hace el deploy.
