### ISSUE TITLE
[FEATURE] Reportes de problemas 2.0 Agregar icono al problema cuando es resuelto como warning 

### ISSUE THREAD

**Issue by RuizYugen** [omegaup/omegaup#3734]
Tambien modificar la vista de los problemas que tienen un warning, agregando un icono y mostrando un banner como se muestra en la imagen.
![image](https://user-images.githubusercontent.com/33679884/79183109-237ba300-7dd6-11ea-85c3-231742bbb7ba.png)

**Comment by carlosabcs** [comment]
Resuelto*

**Comment by RuizYugen** [comment]
@tvanessa me lo puedes agregar a mi por favor
