### ISSUE TITLE
[FEATURE] Añadir un identificador numerico a los problemas

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3738]
Sugerencia de profesores y usuarios.

Hay varios problemas con nombres parecidos y se confunden. Buscar problemas mediante un numero seria mas sencillo

**Comment by darkmx** [comment]
x2 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pabo99** [comment]
¿El número que identifique a cada problema será asignado sólo a los problemas de calidad o todos los problemas deben tener un identificador?

En el caso de que todos los problemas deban llevar identificador, ¿puede ser este el id que almacenamos en la base de datos o tendríamos que agregar de cualquier forma el nuevo campo?

**Comment by lhchavez** [comment]
lo más fácil sería usar `problem_id` (sin importar si sólo los problemas de calidad o todos).

de otra manera tendríamos que usar números más grandes, y eso dificultaría el caso de uso deseado.

**Comment by tvanessa** [comment]
Todos los problemas tendrían un identificador numérico.

**Comment by pabo99** [comment]
Ya estoy trabajando en este issue. Tengo una duda que me gustaría aclarar antes de continuar:

¿El identificador del problema se deberá agregar en todos los lugares donde se muestra el problema?

Mi duda surge porque estaba revisando algunos lugares donde no tiene mucho sentido agregarlo, por ejemplo en un concurso, ya que cada problema tiene un identificador alfanumérico para el ordenamiento:
![image](https://user-images.githubusercontent.com/3230352/84450361-84c4c480-ac15-11ea-8ae5-e772a410620d.png)

Mismo caso ocurre con los cursos, ahí también ya cuentan con un identificador.

**Comment by tvanessa** [comment]
No, no es todos los lugares. Nuestra idea inicial es que sea en la lista de problemas, en la vista del problema y en la URL del problema.

**Comment by darkmx** [comment]
En mi opinión, el id numérico debería aparecer o poder usarse en aquéllos lugares donde el alias aparece o puede usarse en la interfaz (ej. la URL o en un buscador). Donde sólo aparece el título del problema no.

**Comment by pabo99** [comment]
Ok, entendido. 

Voy a incluirlo en los tres lugares donde comenta Vanessa, y además haré que en el buscador  también se considere ese identificador.

**Comment by pabo99** [comment]
Cierto, falta la segunda parte

**Comment by pabo99** [comment]
> En mi opinión, el id numérico debería aparecer o poder usarse en aquellos lugares donde el alias aparece o puede usarse en la interfaz (ej. la URL o en un buscador). Donde sólo aparece el título del problema, no.

Retomando la discusión que tuvimos en la junta de ingenieros, falta agregar el Id en la URL. Aquí los comentarios de las posibles soluciones:

-  Agregar una nueva entrada en el archivo `nginx.rewrites` similar a 
```
/arena/problem/([0-9]+)/?$  /arena/problem.php?problem_id=$1 last;
```
(no sé si eso funcione) y en `Problem::getProblemDetailsForSmarty` lea uno de los dos campos posibles que se le pueden mandar.

- Otra solución puede ser sólo modificar la entrada existente en `nginx.rewrites` para que quede de la siguiente forma:
```
rewrite ^/arena/problem/([a-zA-Z0-9_+-]+)/?$ /arena/problem.php?query=$1 last;
```
y que en `Problem::getProblemDetailsForSmarty` se puede revisar desde un inicio si `query` es numérico obtenga el problema al que le corresponda el `problem_id` de lo contrario funcione como ya lo hacía anteriormente.

Independientemente de cual de las dos opciones es la indicada para resolver el issue o si conocen una mejor, también platicamos que debería ser bueno agregar más restricciones a los alias de problemas (y quizás en general a todos los alias), tales como:

- El alias no puede ser número.
- El alias no puede comenzar con un número.

Actualmente ya contamos con alias que tienen esas características (al rededor de 47 que empiezan con número y dos que son un número). Aquí es donde tiene mucho sentido lo que comenta @darkmx de que no debería de ir donde sólo se muestra el título del problema porque aparece así:
![image](https://user-images.githubusercontent.com/3230352/84795319-efcb1e00-afbc-11ea-87e8-b242a41ddec1.png)
 Donde "2906" es el id del problema y "1 y 2" es el título del problema.

**Comment by darkmx** [comment]
+1 a añadir restricciones a los alias, pero la visualización fea es por culpa del _nombre_ del problema y ahí está más difícil justificar restricciones.

Si sólo hay dos alias que son completamente numéricos, ¿se podría hacer un datafix para agregarles algo? por ejemplo, un guión bajo.

Ahorita así como está, efectivamente el número ha confundido a algunos (aunque tampoco mucho). En el difunto TJU la cosa se veía así:

![imagen](https://user-images.githubusercontent.com/19719969/84796652-7c2a1080-afbe-11ea-9d30-f750d8c93926.png)

Se me ocurren dos cosas: 
- Experimentar con estilos.
- Agregar el id a la tablita que se muestra abajo. 

PD. aprovecho para preguntar eso de límite de entrada, porque nunca le he entendido :( siempre es muy bajo y nunca se honra (mientras que el límite de salida sí te puede tumbar pero no se muestra). De hecho, la tablita de un problema se ve diferente en un concurso a fuera del concurso (viene eso de consola).

![imagen](https://user-images.githubusercontent.com/19719969/84798195-47b75400-afc0-11ea-9329-db58a917ccbd.png)

**Comment by lhchavez** [comment]
> * Otra solución puede ser sólo modificar la entrada existente en `nginx.rewrites` para que quede de la siguiente forma:
> 
> ```
> rewrite ^/arena/problem/([a-zA-Z0-9_+-]+)/?$ /arena/problem.php?query=$1 last;
> ```
> 
> y que en `Problem::getProblemDetailsForSmarty` se puede revisar desde un inicio si `query` es numérico obtenga el problema al que le corresponda el `problem_id` de lo contrario funcione como ya lo hacía anteriormente.
> 

mi preferencia es que si alguien accede a un problema mediante su ID numérico, te redirija al URL que tiene el alias usando [`HTTP 301 Moved Permanently`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301), que indica que el otro URL es el canónico.

**Comment by pabo99** [comment]
Acabo de agregar un par de issues para que las discusiones que se generaron aquí no se pierdan.
