### ISSUE TITLE
[BUG] El usuario no ha recibido el badge de Coder del mes pero badge/coderOfTheMonth/ dice que si

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3746]
Por ejemplo, Hugo no ha sido coder del mes, pero en la descripción del badge dice cuando recibió la insignia.

![Screen Shot 2020-04-15 at 7 05 30 PM](https://user-images.githubusercontent.com/13296248/79406600-5b0c5b80-7f4c-11ea-9edd-6f72bd362dda.png)

También noté que hay 88 usuarios con la insignia. Según mis cuentas deben ser menos, pero quizás es parte del mismo bug.

**Comment by carlosabcs** [comment]
Ah, esto probablemente es producto de los cambios que hicimos de mover todos los reconocimientos del mes al cronjob. No se me ocurre aún, cómo podríamos adaptar la verificación para este badge.

**Comment by RuizYugen** [comment]
este bug esta en todas las badges

**Comment by tvanessa** [comment]
Sí ):, también lo reportaron en #3777 
Debería mostrar el texto de esta cadena: https://github.com/omegaup/omegaup/blob/e04d843af464677ddc327f91b99cf35c86ca969d/frontend/templates/es.lang#L46
