### ISSUE TITLE
[FEATURE] Modificar el titulo y el link del componente de top de usuarios (homepage)

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3751]
El top de usuarios en el homepage cambio recientemente al top de mes.
Cambiar el titulo Top 5 usuarios con más puntaje -> Top 5 usuarios con más puntaje del mes

Y el link de Ver ranking completo:
- Si es posible, que muestre el tab _Lista de candidatos para coder del mes_, pero si esto implica muchos cambios (porque no queremos que muestre este tab por default cuando entras a `coderofthemonth/`), entonces
- Cambiar el string Ver ranking completo -> Ver ranking general

**Comment by carlosabcs** [comment]
Ok, y optaré por la segunda opción puesto que sí va a involucrar varios cambios.

**Comment by carlosabcs** [comment]
@tvanessa , entonces ya no redireccionará al ranking de los mejores del mes, sino al ranking general. Estto será tanto para escuelas como para coders, verdad?

**Comment by tvanessa** [comment]
Si, para que sea consistente que lleve al ranking general de usuarios y escuelas, pero que muestre el top 5 del mes.

Entonces solo modifica las cadenas, por favor.

En el futuro hacemos que nos lleve al tab de candidatos del mes.

**Comment by tvanessa** [comment]
Otro detalle, puedes poner Title Case en **todos** los títulos de las tablas del homepage?
Por favor
