### ISSUE TITLE
[BUG] Al ver los detalles de un badge que no tienes, muestra que lo obtuviste en una fecha inválida.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#3777]
## Comportamiento Esperado

Cuando veo un badge que no tengo, no dice que ya lo tengo.

## Comportamiento Actual

![image](https://user-images.githubusercontent.com/468211/79923351-2d129580-83ea-11ea-9c0e-b106408f5532.png)

## Pasos para reproducir

1. Abrir mi perfil
2. Ver todos los badges disponibles
3. Hacer click en un badge que no tengo

**Comment by tvanessa** [comment]
#3790
