### ISSUE TITLE
[BUG] La notificaciones no se ven bien

### ISSUE THREAD

**Issue by RuizYugen** [omegaup/omegaup#3778]
Las notificaciónes en la navbar no se ven bien se muestra como en la imagen
![image](https://user-images.githubusercontent.com/33679884/79925216-71f4f700-83ff-11ea-89e7-436c7526a35a.png)

**Comment by carlosabcs** [comment]
Esa notificación es de qué? Justo ahora solo soportamos las notificaciones de badges.

**Comment by pabo99** [comment]
No sé si en el nuevo navbar se implementaron también las notificaciones de clarificaciones. Pero esas sólo se pueden ver estando en arena. 

Parece que estas que comenta Jesús son otro nuevo tipo.

**Comment by carlosabcs** [comment]
Las de clarificaciones aún no, solo las que se pueden mostrar desde el homepage, que son que hice con badges.

**Comment by RuizYugen** [comment]
Es de nominaciones de si un problema se suspende

**Comment by carlosabcs** [comment]
> Es de nominaciones de si un problema se suspende

Tienes que personalizarla con estilso de CSS

**Comment by RuizYugen** [comment]
Lo que pasa es que agrego una notificacion el la base de datos de Notifications pero esta no se muestra

**Comment by carlosabcs** [comment]
Ah, es que las notificaciones tienen una estructura tipo JSON, no sé si viste.
Cómo es el registro que estás guardando? Podemos trasladar esta conversación a slack.

**Comment by RuizYugen** [comment]
asi me parece bien

**Comment by tvanessa** [comment]
@RuizYugen este issue se deberia cerrar?
