### ISSUE TITLE
[BUG] Soluciones de problema - LaTeX no se renderea en el editor de soluciones

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3787]
## Comportamiento Esperado

Al agregar una solución a un problema usando el editor de problemas, Vista Previa debería mostrar el rendering de LaTeX.

## Comportamiento Actual

La Vista Previa del editor de soluciones no renderea el LaTeX

## Posible Solución

El workaround que encontré para activar el rendereo es:
1. Regresar a Editar Redacción
2. Abrir la vista previa de la redacción
3. Volver a Editar Solución
4. Vista Previa ahora muestra el rendering apropiadamente, win!

## Pasos para reproducir (para bugs)

Previsualizar cualquier solución con "$x$"  (que no siga la secuencia de pasos anteriores)

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 80.0.3987.163 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): Mac OS Mojave
* Link al sitio en el que este problema pasa: Cualquier problema, https://omegaup.com/problem/Karel-y-los-quebrados/edit/#solution 
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/207097/80124869-bc808b80-8545-11ea-91ec-9b7e3b81dd7d.png)

**Comment by lhchavez** [comment]
arreglado en https://github.com/omegaup/omegaup/pull/3774

**Comment by lhchavez** [comment]
mentiras, me estaba refiriendo al otro issue.

**Comment by heduenas** [comment]
Ya se renderea
