### ISSUE TITLE
[BUG] Soluciones del Problemas - El LaTeX no se renderea al mostrar la solución

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3788]
## Comportamiento Esperado

Cuando un usuario "destapa" la solución a un problema, el contenido LaTeX se debería renderear apropiadamente.

## Comportamiento Actual

El contenido LaTeX de las soluciones no se está rendereando.

## Posible Solución

No encontré workarounds como en https://github.com/omegaup/omegaup/issues/3787

## Pasos para reproducir (para bugs)

Subí una solución con LaTeX a https://omegaup.com/arena/problem/Tu-y-tu-Futuro/#solution

![image](https://user-images.githubusercontent.com/207097/80125259-44669580-8546-11ea-8817-1a879141760a.png)

## Tu ambiente

Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Sistema Operativo y versión (escritorio o móvil): Mac OS Mojave
Link al sitio en el que este problema pasa: Cualquier problema, https://omegaup.com/arena/problem/Tu-y-tu-Futuro/#solution

**Comment by lhchavez** [comment]
arreglado en https://github.com/omegaup/omegaup/pull/3774
