### ISSUE TITLE
[BUG] El query para asignar badge del coder del mes no esta funcionando correctamente

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3791]
Hay 88 coders del mes, y segun mis cuentas deberian ser menos (hay 83 en la [lista](https://omegaup.com/coderofthemonth/) incluyendo repetidos).

![Screen Shot 2020-04-15 at 7 05 30 PM](https://user-images.githubusercontent.com/13296248/80152341-55c49780-8570-11ea-91ef-88bc21631096.png)

También note que los primeros dos canditatos a coder del mes ya tienen asignado el badge.

**Comment by carlosabcs** [comment]
OJO @RuizYugen, que como ya les asignaste el badge a estos usuarios, debes asegurarte de quitárselas en base de datos también.
