### ISSUE TITLE
[BUG] Nuevamente no funciona el buscador de problemas.

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#3803]
## Comportamiento Actual
Después de buscar, ya sea (por cualquier manera), aparecen los resultados y en la parte inferior de  la página está la paginación, esa paginación no sirve, presiono para ver la página 2, o la 3 o cualquiera y no hace nada.

## Pasos para reproducir (para bugs)
Simplemente buscar, por cualquier forma. Sí aparecen los problemas pero solo de la página 1, las demás ya no se pueden ver.

**Comment by heduenas** [comment]
Nota: Si se da {click derecho -> Open in new tab} en el número de página sí abre correctamente la página seleccionada.
