### ISSUE TITLE
[BUG] Los badges de Coder del Mes que se asignaron erroneamente no se borraron

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3815]
Ahora hay 89 coders del mes. 

Nota: los primeros dos **candidatos** a coder del mes (general) ya tienen asignado ese badge. también el segundo lugar del mes pasado https://omegaup.com/coderofthemonth/
![Screen Shot 2020-04-26 at 11 11 56 PM](https://user-images.githubusercontent.com/13296248/80339450-84ae6800-8813-11ea-80f8-df41259cdc9f.png)

**Comment by lhchavez** [comment]
la consulta que eliminaba los badges mal-asignados se corrió a mano.
