### ISSUE TITLE
[BUG] El código de la descripción del problema no se ve al editar.

### ISSUE THREAD

**Issue by luisoncpp** [omegaup/omegaup#3827]
## Comportamiento Esperado

Al abrir la opción de editar la descripción, el código en la caja de texto debería ser el código en formato markdown que actualmente está guardado en OmegaUp.

## Comportamiento Actual

Estaba intentando editar el problema maintain para arreglar errores de formato, y al abrir la opción de editar la descripción, el código estaba en blanco.

## Pasos para reproducir (para bugs)

Abrir este link cambiando "maintain" por el nombre de un problema del cual se tenga permiso de editar.
https://omegaup.com/problem/maintain/edit/#markdown

## Contexto

Pues varios de mis problemas(si no es que la mayoría) tienen errores de formato, y es mucho más sencillo arreglarlos si se puede editar el código ahí mismo en lugar de tener que bajar el zip.

## Tu ambiente

Chrome Version 81.0.4044.122 (Official Build) (64-bit) en gLinux

**Comment by tvanessa** [comment]
@carlosabcs sabes si podría estar relacionado a la corrección que hiciste de las soluciones?

**Comment by carlosabcs** [comment]
> @carlosabcs sabes si podría estar relacionado a la corrección que hiciste de las soluciones?

Acabo de comentar las líneas que hice en ese cambio, y nada.
No tendrá que ver con este cambio de @pabo99? https://github.com/omegaup/omegaup/pull/3786

**Comment by pabo99** [comment]
Pudiera ser, deja intento reproducirlo, para saber por donde está el error.

**Comment by pabo99** [comment]
Efectivamente, tuvo que ver con ese cambio. @tvanessa, me lo asignaré y en cuanto tenga oportunidad lo arreglo.

**Comment by pabo99** [comment]
Como "workaround" lo que se puede hacer en lo que se sube la corrección es cambiar el idioma de la redacción a inglés y nuevamente cambiarlo a español, de esa forma ya se muestra correctamente la descripción del problema.

![Markdown](https://user-images.githubusercontent.com/3230352/80654598-421ea280-8a42-11ea-82a5-cde768af3a48.gif)
