### ISSUE TITLE
[BUG] No se respeta el banned ni el warning cuando un problema es cambiado de visibilidad

### ISSUE THREAD

**Issue by RuizYugen** [omegaup/omegaup#3832]
## Comportamiento Esperado

Cuando se cambie la visibilidad de un problema y esta en banned o warning este debe de seguir en banned o warning este ya sea publico o privado

## Comportamiento Actual

Cuando se modifica la visibidad de un problem en /problem/mine/ regresa hacer warning

**Comment by RuizYugen** [comment]
@tvanessa puedes revisar si el comportamiento esperado si esta bien, por favor.

**Comment by tvanessa** [comment]
Si, me parece que así es el comportamiento esperado. Lo pongo aquí con los nombres de las visibilidades:

`VISIBILITY_PRIVATE_BANNED` -> No puede cambiarse
`VISIBILITY_PUBLIC_BANNED` -> No puede cambiarse
Para dar mas claridad, el Private y Public de esta visibilidad solo es para saber si el problema era público o privado antes de estar `banned`

`VISIBILITY_PUBLIC_WARNING`  puede intercambiarse con `VISIBILITY_PRIVATE_WARNING` y viceversa.
