### ISSUE TITLE
[BUG] Error en carga fría de los envíos de un problema

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3836]
Hola amigos de omegaUp.

Recientemente me di cuenta que los envíos de un problema (tanto el top de envíos como la lista de envíos visibles para el admin) no se estaban cargando ocasionalmente. Recargar la página arreglaba el problema. Ahorita me di cuenta que el problema parece ocurrir únicamente durante la carga fría. Parecen ocurrir diversos errores que cuestan un poco de trabajo reproducir.

Un error es el siguiente:
![imagen](https://user-images.githubusercontent.com/19719969/80612202-41b1e780-8a01-11ea-8fbc-d0110c4e0305.png)

Otro error es el siguiente:
![imagen](https://user-images.githubusercontent.com/19719969/80612422-935a7200-8a01-11ea-9761-278de9c52363.png)

El primer error ocurrió tanto en Firefox como en Chrome, pero fue mucho más fácil reproducirlo en Chrome (borrar la cache basta, aunque sólo pude reproducirlo en 4 de 5 intentos). El segundo error sólo me ocurrió una vez en Chrome. Ambos navegadores ejecutan la versión más reciente del navegador respectivo en Windows. Es probable que se trate de una condición de carrera durante la carga de los scripts JS.

**Comment by lhchavez** [comment]
Esto ya se maneja de otra manera, así que ya no debería ocurrir nunca.
