### ISSUE TITLE
[BUG] El submission_gap utiliza el reloj local de la computadora y no el del servidor

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3839]
### Contexto

Los profesores hacen concursos en las escuelas y no siempre pueden configurar la hora/fecha de las computadoras de la escuela. Esto ocasiona que sus alumnos no puedan hacer envíos, pues reciben mensajes como `Debes esperar 90500 segundos entre cada envío`.

![Screen Shot 2020-04-28 at 5 53 07 PM](https://user-images.githubusercontent.com/13296248/80664718-58316080-8a4c-11ea-96b2-5f47c596f305.png)

### Pasos para reproducir
-Hacer un concurso con submissions_gap = default
-Cambiar la hora/fecha de la computadora cliente, por ejemplo a ayer
-Hacer refresh
-Hacer un envio en el concurso
-Intentar hacer otro envio

**Comment by lhchavez** [comment]
se refresca el navegador entre los pasos 2 y 3? si todo se hace dentro de la misma carga de página, eso es esperado.

**Comment by tvanessa** [comment]
Si se refresca, lo voy a agregar.

**Comment by lhchavez** [comment]
vale, gracias por confirmar!

creo que lo único que hay que hacer es agregar algo así como https://github.com/omegaup/omegaup/pull/3739/files#diff-9660d6c851f3736793f8dd538d28f8e3 en la llamada al API donde se obtiene el `submission_gap`.
