### ISSUE TITLE
[BUG] No puedo visualizar los concursos que administro. 

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#3854]
## Comportamiento Esperado

Necesito visualizar los concursos que administro para poder configurar. 

## Comportamiento Actual

Seleccionas la casilla de "Mostrar los concursos que administro" y no muestra los concursos que administro.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Iniciar sesión 
2. Ir a la ventana de mis concursos
3. Seleccionar "concursos que administro"

## Contexto

No puedo visualizar los concursos que administro para poder modificarlos.

## Tu ambiente

Windows 10
Chrome (ultima versión disponible a la fecha)

 Link al sitio en el que este problema pasa: https://omegaup.com/contest/mine/
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5459260/80776833-e5e27e00-8b28-11ea-901c-0fe5c297e749.png)

**Comment by pabo99** [comment]
Parece que esto ya fue corregido por #3853 

Además ese cambio y todo lo que se está migrando a `TypeScript` ayudará a que se disminuyan el número de regresiones ocasionadas por `typo`'s
