### ISSUE TITLE
[BUG] Que el autocomplete en los envíos de un concurso sólo busque en el concurso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3861]
Hola amigos de omegaUp.

La lista de envíos de un concurso tiene dos `<input type="text">` que permiten buscar usuarios o problemas específicos. Sin embargo, en lugar de limitarse a buscar usuarios o problemas que estén en el concurso, el autocomplete busca sobre toda la plataforma. Encontrar algo de este modo resulta más engorroso de lo ideal, ya que uno pensaría que basta teclear poco en un concurso (pues un concurso suele tener un alcance limitado), pero uno termina necesitando teclear mucho para desambiguar.

![imagen](https://user-images.githubusercontent.com/19719969/80866036-2d185e00-8c52-11ea-85f0-bcbe926aa9b2.png)

**Comment by carlosabcs** [comment]
Este issue ya fue resuelto, puedes cerrarlo @tvanessa , por fa

**Comment by darkmx** [comment]
yo ayudo :P

**Comment by darkmx** [comment]
Hola amigos.

El problema sigue ocurriendo (aunque la naturaleza es distinta). Parece que el typeahead le da preferencia a lo del concurso, pero sigue mostrando cosas de más.

![image](https://user-images.githubusercontent.com/19719969/109393595-56dcf880-78e8-11eb-959d-c5d5b0767b56.png)
