### ISSUE TITLE
[BUG] Notificación del badge de experto en C++ no se puede leer

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#3868]
<img width="788" alt="Screen Shot 2020-05-03 at 9 17 54 PM" src="https://user-images.githubusercontent.com/597815/80935955-e7f44900-8d83-11ea-821a-e555e2c446fa.png">

**Comment by heduenas** [comment]
También vale la pena revisar si otros badges de "Experto en" fallan. Yo solo tengo ese de experto en C++.

**Comment by RuizYugen** [comment]
Al intentar reproducir el issue en local no pasa 
![image](https://user-images.githubusercontent.com/33679884/80993790-4dd2e600-8e01-11ea-9c7e-8c8d5685ed51.png)

**Comment by lhchavez** [comment]
```
mysql> UPDATE Notifications SET contents = '{"type": "badge", "badge": "cppExpert"}' WHERE contents = '{"type": "badge", "badge": "cppexpert"}';
Query OK, 6773 rows affected (0.06 sec)
Rows matched: 7156  Changed: 6773  Warnings: 0
```

**Comment by lhchavez** [comment]
la razón de esta rotura fue por #3317.
