### ISSUE TITLE
[FEATURE] Como un usuario principiante, quiero encontrar problemas muy fáciles

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#3871]
*Como un usuario principiante, quiero encontrar problemas muy fáciles para poder practicar*

## Comportamiento Esperado

Si ordenas los problemas de forma ascendente por dificultad, los problemas al inicio deben ser los más fáciles. Esto es muy útil para encontrar una lista de problemas que sean fáciles de resolver.

## Comportamiento Actual

Ver: https://omegaup.com/problem/?query=&order_by=difficulty&mode=asc

Actualmente ordenar de forma ascendente por dificultad pone en primer instancia los problemas que no tienen dificultad, lo que previene que los problemas "muy fáciles" salgan hasta el inicio.

## Posible Solución

Generalmente cuando ordenas por una columna, los renglones que no tienen un valor en esa columna se ponen hasta el final, no al inicio.

## Alternativas consideradas

Poder buscar problemas solamente fáciles, así no será necesario ordenar los problemas porque puedes simplemente filtrar por problemas de una u otra dificultad.

## Contexto

Estoy escribiendo un plan de estudio para estudiantes de Honduras que están muy motivados para empezar y les quise compartir este link: https://omegaup.com/problem/?query=&order_by=difficulty&mode=asc sin embargo el link no muestra problemas fáciles sino problemas sin categorizar.

**Comment by heduenas** [comment]
Gracias por reportar ese bug Rafa. En lo que arreglamos esa UX, te recomiendo que le pases la liga del curso de [intro a C++](https://omegaup.com/course/introduccion_a_cpp/) o el del [curso de la OMI](https://omegaup.com/course/Curso-OMI/assignment/COMI-programacion#problems), ambos tienen problemas basicos.
