### ISSUE TITLE
[BUG] Usuarios explícitamente invitados a un concurso en modo registro deben ser confirmados de todos modos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#3890]
Hola amigos de omegaUp.

Hoy puse un examen extraordinario en omegaUp y desde hace algunas semanas solicité a los alumnos que lo iban a presentar que me mandaran sus usuarios. Los usuarios los agregué a mano con la opción "Agregar usuario" en:

![imagen](https://user-images.githubusercontent.com/19719969/81232207-19565a00-8fba-11ea-96fa-7b8a99a81470.png)

Establecí el concurso en modo "Registro/abierto" con dos objetivos:
1) Que el link al concurso fuera visible aún si no estaban registrados/logueados en la plataforma.
2) Que si alguien intentaba ingresar sin haberme avisado antes, al menos pudiera darme cuenta.

Afortunadamente (o eso creí), todos los alumnos inscritos en el examen me enviaron sus usuarios de omegaUp con anticipación y los agregué a todos. Después de esto me despreocupé, pensando que iban a poder entrar sin problemas. Sin embargo, pocos minutos después de haber iniciado el examen, me mandaron correos diciéndome que no podían entrar al mismo. Como no tenía idea de la razón (¿habría puesto mal los usuarios?), mi primer impulso fue poner el concurso público, avisarles y seguir con el examen.

Acabo de reproducir el issue en https://sandbox.omegaup.com/arena/TdD1. Agregué manualmente al usuario rcc2 y luego rcc2 abrió el concurso antes de que iniciara, lo que hizo que le apareciera el botón de "Solicitar registro" o una cosa así. Cuando inició el concurso, el siguiente mensaje seguía apareciéndole (con todo y recarga de página):

![imagen](https://user-images.githubusercontent.com/19719969/81232813-2fb0e580-8fbb-11ea-87d1-fe7d354499d3.png)

Del lado del administrador aparece lo siguiente:

![imagen](https://user-images.githubusercontent.com/19719969/81232978-81597000-8fbb-11ea-9a85-398a1c7f6fa6.png)

Aparentemente, el registro pendiente tiene prioridad sobre el haber agregado explícitamente al usuario. Creo que esto es contraintuitivo y provocó varios miniinfartos :( De hecho, el letrero que indica que la solicitud de registro está pendiente permanece aunque el concurso ya acabó (con todo y recarga de página).

**Comment by tvanessa** [comment]
@pabo99 seria fácil extender esto para cursos con registro (compartir URL)?

**Comment by pabo99** [comment]
Si, los dos se manejan de la misma forma. Así que se puede reutilizar mucho código.
