### ISSUE TITLE
[FEATURE] Como un Profesor, quiero clonar un curso público para evaluar a mis alumnos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#3897]
## Comportamiento Esperado
(Propuesta original del Dr. Franz) 
Tener la posiblidad de clonar un curso público para poder observar el desempeño de un grupo específico de alumnos. _Lo que quise decir con "clonar" un curso de omegaUp es que un profesor lo pueda tener para su grupo pero no pueda modificar el contenido... el material que se despliegue debe ser idéntico al que omegaUp haya diseñado... solo la lista de alumnos
quedará restringida a los que el profesor decida... esto sería diferente de "copiar" un curso propio, ya que en la copia el profesor podría cambiar cualquier aspecto que quiera en la copia (por supuesto, algún profesor suficientemente motivado siempre podrá copiar a mano un
curso de omegaUp y cambiarle lo que quiera... la idea de clonar es para los que quieran algo fácil y rápido)_

## Comportamiento Actual
Con la funcionalidad actual no es posible que un profesor pueda monitorear el avance solamente de su grupo de alumnos en un curso público, incluyendo ver dónde se atoraron y que códigos están mandando. 

## Alternativas consideradas
(Joe)
Quizás no es necesario clonar el curso si se pudiera hacer una vista de sólo lectura del Admin/Profesor con intersección entre un Grupo y los participantes del curso 😅.

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*
Monitorear un grupo de alumnos en específico con material existente.

*Proveer contexto nos ayuda a encontrar la solución adecuada*
Nota para priorización: este issue será más relevante cuando tengamos más cursos públicos 😁 Por el momento sólo tenemos 1.

**Comment by heduenas** [comment]
Por ahora podemos simplemente poner una liga para clonar el curso público abajo de la lista de contenido.
![image](https://user-images.githubusercontent.com/597815/89242437-64323e80-d5b6-11ea-871d-06e2a06e252d.png)

Que al dar click te lleve al formulario de clonar curso.

**Comment by pabo99** [comment]
> _Proveer contexto nos ayuda a encontrar la solución adecuada_
> Nota para priorización: este issue será más relevante cuando tengamos más cursos públicos 😁 Por el momento sólo tenemos 1.

Ahora ya hay más de un curso público, así que ya se va a empezar a trabajar e la solución.

**Comment by pabo99** [comment]
Sólo faltaría definir alguna de las dos propuestas:

- Permitir hacer clon del curso. La diferencia con el resto de los cursos es que estos deshabilitarían la opción de editar el contenido.
- Agregar la funcionalidad de modo sólo lectura para los cursos públicos donde el usuario se agrega como administrador, del curso original, pero sólo puede  agregar usuarios, mismos que serían los que puede monitorear su avance.

Si tienen otra alternativa, la pueden comentar para elegir la que mejor se adapte.

**Comment by tvanessa** [comment]
Hemos estado discutiendo esto con Nancy, porque le interesa para el proyecto de UEMSTIS (#4362). Necesitamos que cualquier persona pueda clonar el curso y que pueda modificar su copia. O sea, debe de poder agregar, quitar, reordenar problemas. Por ahora podemos hacer lo que Hugo propone, y que se clone de manera normal.
