### ISSUE TITLE
[FEATURE] Vuefication: common.navbar.tpl 

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3919]
Smarty template `.tpl` needs to be converted to .vue
 Please see: [link](https://pastebin.com/5psKRQpH)
 Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este archivo se migró en el PR #5394, así que ya se puede cerrar el issue.
