### ISSUE TITLE
[FEATURE] Vuefication: quality.nomination.list.tpl 

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3959]
Smarty template `.tpl` needs to be converted to .vue
 Please see: [link](https://pastebin.com/5psKRQpH)
 Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment]
Este archivo ya se migró a la plantilla unificada en el PR #4132. Así que ya se puede cerrar.
