### ISSUE TITLE
[FEATURE] Actualizar wiki sobre migración a vue-ts-bs4

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#3992]
https://github.com/omegaup/omegaup/wiki/Smarty-template-vuefication-(-Guidelines-To-Follow-)

**Comment by carlosabcs** [comment]
Done
https://github.com/omegaup/omegaup/wiki/%5BGuidelines-to-Follow%5D-Migrating-from-Smarty-.tpl-to-Typescript,-Vue-and-Bootstrap-4
