### ISSUE TITLE
[FEATURE] Añadir la opción "Ver mis insignias" en el navbar

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4006]
- En el dropdown del usuario agregar "Ver mis insignias" y que te lleve a  https://omegaup.com/badge/list/

 
![Screen Shot 2020-05-14 at 2 05 20 PM](https://user-images.githubusercontent.com/13296248/81986130-1f68be00-95ec-11ea-9b39-c734366a484c.png)

- En la notificación que recibe el usuario sobre sus nuevos badges, poner un link a los detalles del badge (https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/components/notification/Notification.vue#L85)

**Comment by lhchavez** [comment]
se puede separar el cambio de cadena a otro issue? preferiría que cada cambio / issue sea lo más pequeño posible para hacer la revisión más rápida y que en el rarísimo caso en el que algo se le tenga que hacer revert de emergencia, sea más fácil y haya menos probabilidad de conflicto.
