### ISSUE TITLE
[FEATURE] No listar los "Cursos de registro abierto" en la tabla de Cursos Públicos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4008]
Al mostrarlos en esta lista puede llegarle mucho spam al profesor, y también le hace ruido a un estudiante que esta buscando cursos públicos.

La intención es que solo se pueda acceder a estos cursos por los alumnos que tengan el link del curso.

También se propone cambiar la sección de "Modo de acceso" a lo siguiente,
- Cambiar los strings:
    - Privado -> "Manual (Agrega los nombres de usuario de tus estudiantes)"
    - Registro abierto -> "Compartir URL (Los estudiantes se inscriben desde el URL)"
- Agregar un botón de "copiar URL" cuando se seleccione el modo "Compartir URL".
- Cambiar los textos de ayuda a:
Select course admission mode. There are two different options:
Share URL: Anyone with the link can apply to join. Additionally you can manually add usernames to your course.
Manual Only: Students can not access it unless they have been explicitly invited.
![Screen Shot 2020-05-14 at 3 56 05 PM](https://user-images.githubusercontent.com/13296248/81993860-74f89700-95fb-11ea-99c7-0d6ae297add3.png)
![Screen Shot 2020-05-14 at 3 55 22 PM](https://user-images.githubusercontent.com/13296248/81993868-788c1e00-95fb-11ea-9ee3-11535bd16d02.png)

**Comment by carlosabcs** [comment]
Esa `URL` a ser compartida, es la URL del curso o es una URL especial? Si es lo segundo, ya lo soportamos?

**Comment by lhchavez** [comment]
sí, pero esto es un poco más amigable a los profesores que no quieren andar manipulando URLs o yendo al curso y copiando la dirección del navegador.

**Comment by carlosabcs** [comment]
Entonces, es la URL del curso nada más, no?!

**Comment by tvanessa** [comment]
Si, la del curso

**Comment by tvanessa** [comment]
Revise esto en producción y los cursos de registro abierto se ocultan de la tabla de Cursos públicos **solo** para el administrador del curso. 
El resto de los usuarios si lo tienen listado.

A ningún usuario le debería mostrar este tipo de cursos en la tabla de Cursos públicos
