### ISSUE TITLE
[BUG] No se guarda orden de las tareas en un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4032]
### Comportamiento Actual

Al editar un curso puedo cambiar el orden de las tareas, pero no se guarda. Por otro lado no hay un botón que indique si quiero guardar cambios o una indicación de que se hizo el cambio

![Screen Shot 2020-05-17 at 1 12 06 AM](https://user-images.githubusercontent.com/13296248/82160545-00b43280-984b-11ea-99e4-5e0dd7f1c3ab.png)

### Posible solución

Guardar el orden
Agregar un botón "Guardar cambios" o mostrar un banner que diga "Se guardaron tus cambios" (lo que sea mas fácil de implementar)

**Comment by lhchavez** [comment]
esto comenzó (o empeoró) esta semana, según NewRelic.

Esto es de lo que se está quejando:

```
E_WARNING: Invalid argument supplied for foreach()
in OmegaUp\Controllers\Course::apiUpdateAssignmentsOrder called at ? (?)
in call_user_func called at /opt/omegaup/frontend/server/src/Request.php (69)
in OmegaUp\Request::execute called at /opt/omegaup/frontend/server/src/ApiCaller.php (26)
in OmegaUp\ApiCaller::call called at /opt/omegaup/frontend/server/src/ApiCaller.php (95)
in OmegaUp\ApiCaller::httpEntryPoint called at /opt/omegaup/frontend/www/api/ApiEntryPoint.php (5)
```

y el código involucrado es 

https://github.com/omegaup/omegaup/blob/80206ee502d4fd660fe7aaea1a74a361a03c54b9/frontend/server/src/Controllers/Course.php#L1023-L1027

aquí el problema es que se está dependiendo que _algo_ poble `$r['assignments']`, y al parecer no se está haciendo. la solución es dejar de depender que _algo_ lo poble, y en vez obtener el arreglo explícitamente.

**Comment by carlosabcs** [comment]
> esto comenzó (o empeoró) esta semana, según NewRelic.
> 
> Esto es de lo que se está quejando:
> 
> ```
> E_WARNING: Invalid argument supplied for foreach()
> in OmegaUp\Controllers\Course::apiUpdateAssignmentsOrder called at ? (?)
> in call_user_func called at /opt/omegaup/frontend/server/src/Request.php (69)
> in OmegaUp\Request::execute called at /opt/omegaup/frontend/server/src/ApiCaller.php (26)
> in OmegaUp\ApiCaller::call called at /opt/omegaup/frontend/server/src/ApiCaller.php (95)
> in OmegaUp\ApiCaller::httpEntryPoint called at /opt/omegaup/frontend/www/api/ApiEntryPoint.php (5)
> ```
> 
> y el código involucrado es
> 
> https://github.com/omegaup/omegaup/blob/80206ee502d4fd660fe7aaea1a74a361a03c54b9/frontend/server/src/Controllers/Course.php#L1023-L1027
> 
> aquí el problema es que se está dependiendo que _algo_ poble `$r['assignments']`, y al parecer no se está haciendo. la solución es dejar de depender que _algo_ lo poble, y en vez obtener el arreglo explícitamente.

Entonces, si entendí correctamente, ya no vamos a pasar los assignments como parámetro (ya que por alguna razón no se están pasando). En su defecto qué pasaremos para indicar el nuevo orden?

**Comment by joemmanuel** [comment]
fyi, la funcionalidad de ordenar problemas dentro de un assignment tiene el mismo bug del comportamiento.

**Comment by carlosabcs** [comment]
> fyi, la funcionalidad de ordenar problemas dentro de un assignment tiene el mismo bug del comportamiento.

Sí!, lo noté cuando arreglaba este bug así que lo arreglé también.
