### ISSUE TITLE
[BUG] Banner genérico de error aparece si abres cualquier problema con sesión iniciada, y no puedes interactuar con la página

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#4038]
Es imnposible interactuar con la página si inicié sesión:

![image](https://user-images.githubusercontent.com/123875/82175990-49d7a700-988a-11ea-8d67-7c8a210e9675.png)

No me aparece ningún error en la consola. Lo probé en Chrome y Firefox (Windows).

La sección de envíos y mejores envuís también está vacía, puede estar relacionado o pueden ser diferentes problemas.

![image](https://user-images.githubusercontent.com/123875/82176178-e00bcd00-988a-11ea-8f2d-c7301cfc5c38.png)

Las secciones aparecen bien si no has iniciado sesión, pero cuando inicias no puedes hacer nada.

**Comment by darknut** [comment]
Después de seguir probando, el problema es mucho más grave. No puedo hacer nada si inicié sesión, aunque no sea mi problema

**Comment by darkmx** [comment]
El error es

![imagen](https://user-images.githubusercontent.com/19719969/82209674-47e60600-98d3-11ea-9b16-57f28b5fc446.png)

**Comment by lhchavez** [comment]
gracias por la captura de pantalla con el error de la consola, eso facilitó mucho las cosas!

el fix ya está encaminado hacia producción, como en ~10 minutos más debería estar disponible.
