### ISSUE TITLE
[FEATURE] Ordenar y buscar las nominaciones en la cola de nominaciones

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4043]
Hola amigos de omegaUp.

Las nominaciones están saliendo revueltas. Sería buena idea ordenarlas por fecha. De hecho sería muy bueno poder buscar las nominaciones por autor o problema, como se hace en los envíos de un concurso.

![imagen](https://user-images.githubusercontent.com/19719969/82244920-a3ca8200-9907-11ea-994b-46d8e93b41ed.png)

**Comment by tvanessa** [comment]
Agregar la barra de búsqueda como se muestra en la imagen. Usar typeaheads en este buscador

![Screen Shot 2020-05-20 at 9 50 44 PM](https://user-images.githubusercontent.com/13296248/82524977-20ff1e00-9ae5-11ea-9bf1-dd1ab236784b.png)

**Comment by pabo99** [comment]
¿Cuáles serían los criterios de búsqueda para el Typeahead?

**Comment by darkmx** [comment]
Puede haber muchos. ¿Podría haber un `<select>` al lado para poder elegir entre alias, nominador y autor?

**Comment by RuizYugen** [comment]
@tvanessa este cambio solo seria para https://omegaup.com/nomination/

**Comment by tvanessa** [comment]
Si, solo ese
