### ISSUE TITLE
[BUG] No se puede realizar inicio de sesión con facebook

### ISSUE THREAD

**Issue by RuizYugen** [omegaup/omegaup#4046]
## Comportamiento Esperado

Poder hacer login con fecebook 

## Comportamiento Actual

Marca error cuando acces inicio de sesion con facebook 
con facebook marca este error
![image](https://user-images.githubusercontent.com/33679884/82276360-aa2e1d80-994a-11ea-9608-3e4e8fc002ac.png)

## Posible Solución

Ver el estado de las credenciales

**Comment by tvanessa** [comment]
@pabo99 cuando se hizo la migración a vue+ts+bs4 se arreglo esto?

**Comment by pabo99** [comment]
Si, el inicio de Facebook y de Gmail se arreglaron. Quizás hay alguna actualización que debemos realizar para que vuelva a funcionar el de Facebook.

En el caso de LinkedIn, ese si presentaba un bug conocido al momento de migrar, se reportó en https://github.com/omegaup/omegaup/issues/4954

Habrá que resolver los dos.

**Comment by pabo99** [comment]
En mi versión local funciona correctamente:

![FacebookLogin](https://user-images.githubusercontent.com/3230352/112591276-c05a0500-8dc9-11eb-97a6-cd0975d270e6.gif)

Aunque en la página de desarrolladores de facebook, tenía una alerta de que se había desactivado la API Graph por inactividad:

```
Acceso a la API Graph desactivado por inactividadatención
Por motivos de inactividad, se desactivó el acceso de omegaUp a la API Graph. Si lo restauras, la app solo podrá 
usar la versión más reciente y las que se desarrollen en el futuro. Más información
Si ya no usas esta app para acceder a la API Graph, no es necesario que realices ninguna acción.
```

Desconozco si esto ocurrió también con la app de producción, pero sería bueno revisarlo.
