### ISSUE TITLE
[BUG] Los veredictos de reportes de problemas se guardaron al reves

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4074]
Se añadieron veredictos nuevos a los reportes de problemas y al migrar los viejos veredictos a los nuevos ocurrio un error en https://github.com/omegaup/omegaup/blob/master/frontend/database/145_change_quality_nominations_status.sql#L19

`denied` deber ir a `resolved`
`approved` debe ir a `banned`

**Comment by RuizYugen** [comment]
@lhchavez para este issue se deben de correr nomas unas sentencias creo un PR normal o temando las sentencias y tu las corres?

**Comment by lhchavez** [comment]
crea un PR, pero lo voy a correr manualmente

**Comment by RuizYugen** [comment]
Esta ya esta listo terminado
