### ISSUE TITLE
[BUG] Campos de "Tipo de validador" y "Tipo de problema" no están localizados

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4083]
Tengo mi cuenta configurada en español y los elementos de esos dropdowns me salen en inglés.

**Edit:** In https://omegaup.com/problem/new/ the fields `Problem type` and `Output validator type` are not localized

![image](https://user-images.githubusercontent.com/597815/82720825-fc817e00-9c6b-11ea-9785-ef2ec5a45df0.png)

### Steps to reproduce

- Go to https://omegaup.com/problem/new?lang=es
- Click on the dropdown `Tipo de validador` and `Tipo de problema`, you will see that those options are in English

**Comment by carlosabcs** [comment]
Cuales serían las traducciones en español?
- "Token por Token"
- "Clase (sin envíos)"
?

**Comment by tvanessa** [comment]
Ya no se reproduce
