### ISSUE TITLE
Exceso de tiempo para re intentar envió de solución en un problema de un curso. 

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#4087]
## Comportamiento Esperado

Necesito volver a enviar una posible respuesta dentro de un problema dentro de un curso.

## Comportamiento Actual

Marca un número enorme de tiempo de espera para poder enviar una nueva solución hacia el problema dentro del curso.

## Pasos para reproducir (para bugs)

https://omegaup.com/course/Curso-de-Python-FutureLabs/assignment/variables/#problems/CR-Hola-mundo/new-run
1. Ir a cursos.
2. Abrir el curso de Python.
3. Seleccionar un problema
4. Enviar una respuesta errónea
5. Intentar enviar una nueva solución

## Contexto

No puedo enviar más soluciones a un problema con el cual me equivoque con anterioridad.

## Tu ambiente

* Windows 10 
* Chrome ultima versión a la fecha
* Link al sitio en el que este problema pasa:https://omegaup.com/course/Curso-de-Python-FutureLabs/assignment/variables/#problems/CR-Hola-mundo/new-run
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5459260/82736383-faacce80-9cee-11ea-8a40-dec7d606076b.png)

**Comment by pabo99** [comment]
Dupe of: #4059 

Como workaround puedes recargar la página y ya se vuelve a habilitar el botón de Enviar.
