### ISSUE TITLE
[BUG] En el editor de Cursos, los cambios en el orden de tareas no se guardan

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#4089]
## Comportamiento Esperado

Al cambiar el orden de las tareas en el editor de cursos, el orden se debería guardar.

## Comportamiento Actual

El orden no se guarda, al darle F5 regresa al orden original.

## Pasos para reproducir (para bugs)

https://omegaup.com/course/Curso-de-Python-FutureLabs/edit/#assignments

1. Crea 2 tareas en un curso
2. Invierte el orden
3. Ve al curso, el orden no se guarda.
4. 

## Contexto
En el curso de Python no pusimos el intro a omegaUp 🤣

## Tu ambiente
Chrome  81.0.4044.138
![image](https://user-images.githubusercontent.com/207097/82737634-30e65000-9ce7-11ea-89b0-4ef6782f1a58.png)

**Comment by lhchavez** [comment]
Dupe de #3931 4032
