### ISSUE TITLE
[FEATURE] Agregar soporte para imagenes .svg en statements y solutions

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4090]
Justo ahora se filtran esos archivos al subir un problema.

@lhchavez sería suficiente con agregar `.svg` en estas líneas?

* https://github.com/omegaup/gitserver/blob/73e6c51a467d8e8d273b49b558221350be855801/handler.go#L122
* https://github.com/omegaup/gitserver/blob/73e6c51a467d8e8d273b49b558221350be855801/handler.go#L133

**Comment by lhchavez** [comment]
_creo_ que sí. estaría bueno agregar una prueba cuando se arregle para corroborar.
