### ISSUE TITLE
[FEATURE] Quitar el miniranking en la vista de los problemas de un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4112]
El profesor debería decidir si poner este miniranking y no ponerlo por default.

![Screen Shot 2020-05-25 at 11 40 06 AM](https://user-images.githubusercontent.com/13296248/82841629-a4c15d80-9e8b-11ea-91f5-9d735c4fb841.png)

**Comment by pabo99** [comment]
Empecé a trabajar en este issue, pero acabo de leer el comentario:

> El profesor debería decidir si poner este miniranking y no ponerlo por default.

Actualmente ya se pregunta al profesor si el curso debe mostrar el scoreboard, si se elige la opción "Si", se muestra tanto la pestaña de "Ranking" como el mini-ranking.  Además de que el valor por default es no mostrarlo.

Para solucionar esto planteo las siguientes opciones:
- Dejar tal cual está y para los cursos donde no se desee mostrar miniranking, cambien la configuración del curso.
- Ocultar el miniranking para todos los cursos
- Que el campo de mostrar scoreboard de cursos ahora cuente con tres opciones. así como se muestra en la imagen:
![image](https://user-images.githubusercontent.com/3230352/84081005-c568d780-a9a2-11ea-9ecc-3f89d3383130.png)

La tercera opción sería la ideal para permitir al profesor configurar el curso como él prefiera, pero también es la opción mas costosa debido a que se tiene que modificar la base de datos.

¿Cuál de las tres les parece la óptima?
