### ISSUE TITLE
[BUG] Los problemas con advertencia desaparecen de la lista de problemas creados en el perfil del autor

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4136]
Hola amigos de omegaUp.

Ando de cacería baneando algunos problemas fraudulentos. Los problemas baneados están desapareciendo de la lista de problemas del autor (lo cual es correcto), pero un problema al que sólo le puse una advertencia también. El problema en cuestión es https://omegaup.com/arena/problem/Otro-problema-de-combinatoria/#problems y el perfil del autor es https://omegaup.com/profile/Hugo_Glz/

**Comment by tvanessa** [comment]
Falsa alarma, si se arregló
