### ISSUE TITLE
[FEATURE] Estandarización de tags (Parte 2): Localizar todos los lugares donde se muestran los tags

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4154]
- `/problem/`
- `/problem/mine/`
- `/problem/alias/edit/#tags`
- Formulario de revisores. En esta se va a permitir asignar tags de ~~técnica de resolución y/o un~~ nivel al problema.

**Comment by carlosabcs** [comment]
O sea que las nominaciones de revisores ahora también incluirán a los nuevos tags públicos? Eso es algo que actualmente no estamos soportando

**Comment by tvanessa** [comment]
Tienes razón. Por ahora solo localiza el nivel. Dejamos para otro issue asignar la técnica de resolución
