### ISSUE TITLE
[BUG] No están funcionando los cursos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4176]
El curso de la OMI es el único que se muestra. El de C++ y el de Python no se muestran al entrar a `https://omegaup.com/course/introduccion_a_cpp/`. La consola dice `TypeError: "e is null"`:

![image](https://user-images.githubusercontent.com/597815/83978350-bce9a180-a8bb-11ea-9a7f-6ecafe4a13ac.png)

**Comment by lhchavez** [comment]
ja, creo que encontramos esto al mismo tiempo.
