### ISSUE TITLE
[FEATURE] Renderizar imágenes centradas de la descripcion de problema en /redaccion.php

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4217]
Hola amigos de omegaUp.

Hoy en la mañana pregunté en el depto técnico cómo podía centrar una imagen. Luis Héctor me dijo que si agregaba un título a la imagen (la sintaxis para esto es agregar una cadena entrecomillada no vacía después del src), que además estuviera en su propio párrafo, se activarla una regla de CSS que haría la magia. Aunque el preview no la muestra correctamente, sí funciona en el rendering final tras guardar el markdown. Abro este issue para corregir el preview y para documentar esta característica (si es que se garantiza que siempre funcionará) o para proporcionar una manera directa ade hacer esto que no requiera saber lo anterior.

**Comment by lhchavez** [comment]
El estilo CSS donde esto se hace posible es https://github.com/omegaup/omegaup/blob/147122b3f572421d2664d545b6180b91c9f06eb5/frontend/www/css/arena.css#L204-L207

Las sintaxises que sería bueno agregar a `redaccion.php` son:

```markdown
![alt-text](URL "titlo entrecomillado")
```

y

```markdown
![alt-text][1]

...

^[1] URL "titulo entrecomillado"
```

la imagen en sí (la parte de `![alt-text]`) hay que ponerla en un párrafo por sí sola.

**Comment by lhchavez** [comment]
Arreglado en https://github.com/omegaup/omegaup/pull/4289
