### ISSUE TITLE
[BUG] Cuando creas una nueva cuenta y vas a cursos dice que ya me inscribi a un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4218]
Cuando una cuenta es nueva y vas a https://omegaup.com/course/, la tabla de `Cursos que estudio` muestra los tres cursos públicos de omegaUp, pero no los he abierto/inscrito.

![Screen Shot 2020-06-14 at 10 18 56 PM](https://user-images.githubusercontent.com/13296248/84620874-fc048d80-ae8d-11ea-8016-ac84c665091b.png)

**Comment by heduenas** [comment]
Acabo de experimentar creando una nueva cuenta y efectivamente me muestra los cursos como si estuviera inscrito a ellos. Sin embargo, en mi cuenta de admin del curso de Intro a C++ no me muestra al nuevo usuario como alumno. Es hasta que la cuenta de usuario nueva se mete al curso y confirma que quiere entrar al curso que aparece como alumno del curso en la cuenta del admin.
