### ISSUE TITLE
[BUG] El autocomplete de usuarios ya no funciona bien

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4222]
Hola amigos de omegaUp.

En los envíos de un concurso, el autocomplete de los usuarios sí encuentra al usuario, pero al seleccionar la opción encontrada se rellena el `input type="text"` con _el nombre_ y no con el username. Eso hace que la búsqueda fracase :(

![imagen](https://user-images.githubusercontent.com/19719969/84717405-50b21200-af3b-11ea-8859-8de03730f6d3.png)

Fuera de un concurso, el buscador funciona pero ya no se muestran sugerencias (es decir, no funciona el autocomplete), así que necesitas saberte el usuario completo para poder buscarlo.

![imagen](https://user-images.githubusercontent.com/19719969/84717548-bef6d480-af3b-11ea-8f1f-5559bdf1102b.png)

Ocurre esto tanto en Firefox como en Chrome.
Links de donde vienen las imágenes: https://omegaup.com/arena/problem/La-recurrencia-de-un-algoritmo-h/#runs y https://omegaup.com/arena/E2ADA2020ICSI01/admin/#runs

**Comment by pabo99** [comment]
Hola @darkmx, ¿me puedes apoyar a revisar si aún ocurre la falla dentro de los concursos? Es que en el ambiente local funciona correctamente el auto completado de problemas y de usuarios:
![AutocompleteRuns](https://user-images.githubusercontent.com/3230352/85098022-fb863280-b1be-11ea-9489-e60b7eaa3c0a.gif)

Los otros dos lugares donde se muestra la lista de envíos (La vista global y la vista de cursos) si están fallando tal cual lo describes. Así que comenzaré por arreglar esos dos lugares.

**Comment by darkmx** [comment]
Hola @pabo99, perdón por responder apenas (tuve clase en la mañana).
¿Sí pudiste reproducir la falla en los concursos? leyendo el bugfix parece que sí, pero quisiera confirmar para ver si necesitas que lo reproduzca por acá.

**Comment by pabo99** [comment]
Si pude reproducir la falla, pero sólo en la vista de envíos globales y de cursos. Los envíos en concursos funcionaba correctamente. Si pudieras revisar nuevamente si aún logras reproducirlo y enviarnos más información que nos pueda ser útil. Gracias.

**Comment by darkmx** [comment]
A ver, ahí va (no supe cómo poner un GIF aquí porque lo pegaba como PNG).
https://gifyu.com/image/uCgP

La consola no da mensajes útiles (sólo lo del error de usuario no encontrado).
![imagen](https://user-images.githubusercontent.com/19719969/85166319-b993d580-b22c-11ea-882a-2640aadf1287.png)

**Comment by pabo99** [comment]
Ohhhh, ya logré reproducirlo en el ambiente local. Acabo de subir otro PR (#4243), con lo cual se garantiza que esto no vuelva  a ocurrir. Gracias por la ayuda
