### ISSUE TITLE
[FEATURE] Filtrar tabla de envios con un click

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4231]
Sugerencia de Prof. Franz
"Si le doy click a un problema en los envíos de un trabajo me muestre sólo los envíos de ese problema (en lugar de mandarme al enunciado del problema) y si le doy click a un usuario en los envíos de un trabajo me muestre sólo los envíos de ese usuario (en lugar de mandarme al perfil del usuario)."

Para no limitar el acceso al enunciado del problema o al perfil del usuario, proponemos también poner un icono de `new-tab` para poder ver esta información.

**Nota: Esto también podria ser útil en concursos, pero tiene prioridad mayor para cursos.**

![Screen Shot 2020-06-17 at 2 22 50 PM](https://user-images.githubusercontent.com/13296248/84952634-20878200-b0a7-11ea-806e-4b4bacdc3654.png)

**Comment by pabo99** [comment]
Dado que ya estamos reutilizando componentes, esto se agregaría para los tres lugares en donde se muestra la lista de envíos:
- Cursos
- Concursos
- Envíos globales

Estaba trabajando en resolver el issue #4277 y estaba relacionado con este, así que subiré un PR que soluciona ambos issues.
