### ISSUE TITLE
Poder mandar clarificaciones "on behalf" de alguien más como admin

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#424]
Para implementar notificaciones personales. Onda que un chamaco anda haciendo ruido y quieres decirle nada más a él que se calle.

**Comment by pabo99** [comment]
Revisando la descripción, se lograron identificar tres casos que se pueden solucionar:

Escenario 1: Enviar mensaje como admin a usuario en privado.

Escenario 2: Enviar un mensaje como admin a todos los participantes 

Escenario 3: Enviar un mensaje como admin a nombre de un tercero (Para este caso se requiere un campo extra, además del que ya se va a crear).

Para este issue, ¿Se pretenden incluir los tres distintos casos?

**Comment by pabo99** [comment]
Esperando a que se haga merge del pull_request #1847

**Comment by lhchavez** [comment]
El escenario 3 no es necesario, así que ya quedó esto terminado.
