### ISSUE TITLE
[BUG] En la lista de trabajos de un curso, Mathjax se incrusta indebidamente

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4251]
Hola amigos de omegaUp.

Hay un bug bastante raro del que me acaba de avisar Franz (profesor de la UAM). En la lista de trabajos de su curso en https://omegaup.com/course/aed2020i/, a veces MathJax se carga indebidamente en los nombres de los trabajos y ocurren un sin fin de cosas raras. Por ejemplo:

![imagen](https://user-images.githubusercontent.com/19719969/85305649-fa7d2b80-b472-11ea-9ea0-1f92513f6fe1.png)

El problema es difícil de reproducir. No pude reproducirlo en Firefox, mientras que en Chrome pude reproducirlo sólo algunas veces (sin hacer nada en particular, simplemente entrando o recargando).

![imagen](https://user-images.githubusercontent.com/19719969/85305915-52b42d80-b473-11ea-83bb-921eb897cc9b.png)

**Comment by lhchavez** [comment]
Dupe de #4311
