### ISSUE TITLE
[BUG] Los bagdes tienen diferentes tamaños en la vista del perfil

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4262]
Parece que solo cambia el tamaño con los badges de `Experto en {lenguaje}`

![Screen Shot 2020-06-24 at 12 33 06 PM](https://user-images.githubusercontent.com/13296248/85619546-51bc0100-b617-11ea-9f50-73cbbe6bf2c4.png)
![Screen Shot 2020-06-24 at 12 33 58 PM](https://user-images.githubusercontent.com/13296248/85619552-5385c480-b617-11ea-9ce7-09c9b568f604.png)

**Comment by mjayalam** [comment]
Hay una manera, de poder obtener los badges de experto automáticamente en el listado de usuario, para hacer pruebas en mi local?

**Comment by mjayalam** [comment]
Parece ser que esto se va a arreglar cuando la migración esté completada, revisando en mi rama donde tengo la migración, los badges experto, lucen igual que los demás.

![image](https://user-images.githubusercontent.com/12377916/85635462-8ba2fc80-b643-11ea-9c63-c222531545a9.png)
