### ISSUE TITLE
[BUG] El previsualizador del markdown ya no funciona bien.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4264]
Hola amigos de omegaUp.

Una reciente actualización hizo que el previsualizador ahora sólo funcione parcialmente. Algunas cosas como las viñetas o los recuadritos de los casos de ejemplo ya no se muestran:

https://omegaup.com/arena/problem/Practicando-ciclos/#problems

Vista normal:
![imagen](https://user-images.githubusercontent.com/19719969/85629989-78d6fa80-b638-11ea-8cca-a27afc0bb7a0.png)

Vista en previsualización del markdown:
![imagen](https://user-images.githubusercontent.com/19719969/85630039-91471500-b638-11ea-99ed-27dee98ff397.png)

**Comment by lhchavez** [comment]
Afortunadamente los cambios que he estado haciendo para homogeneizar el despliegue de los markdowns van a ayudar a esto: ahora sólo va a ser necesario mover los estilos CSS a [`Markdown.vue`](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/components/Markdown.vue).
