### ISSUE TITLE
[FEATURE] Estandarización de tags: El campo `Nivel` es requerido

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4267]
P1: Validarlo en el backend
P2: Validarlo en el frontend

**Comment by tvanessa** [comment]
@pabo99 esto se resolvió recientemente?

**Comment by pabo99** [comment]
Hasta el momento así va el avance de este issue:

- [x] Campo "Nivel" requerido: Validación en el frontend (PR: #4416 )
- [ ] Campo "Nivel" requerido: Validación en el backend
- [ ] Campo "Tags públicos" requerido: Validación en el frontend
- [ ] Campo "Tags públicos" requerido: Validación en el backend
