### ISSUE TITLE
[FEATURE] [Cursos UX] Quitar la pagina /schools cuando das click en `Cursos` la primera vez

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4268]
Es confusa para la mayoria de los usuarios.

Podemos poner esta informacion en el carrusel de la pagina principal

![Screen Shot 2020-06-25 at 3 35 52 PM](https://user-images.githubusercontent.com/13296248/85802413-c5ced580-b6f9-11ea-8488-edce1a5c23a0.png)

**Comment by pabo99** [comment]
¿Exactamente que es lo que pondríamos en el carrusel? ¿La información del banner, o la de las tarjetas que vienen abajo? 

En cualquiera de los dos casos requeriríamos de ilustraciones como las que ya se muestran actualmente.

**Comment by tvanessa** [comment]
Mejora hay que abrir otro issue para eso. Porque justamente estamos bloqueados por el diseño para una entrada en el carrusel
