### ISSUE TITLE
[FEATURE] [Cursos UX] Mejorar el dashboard de un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4271]
- Unificar las tablas y diferenciar el tipo de actividad con una nueva columna
- Nombrar la tabla como Contenido
- Introducir el concepto de "Porcentaje completado" (esto sustituye a Progreso)
- Se tiene que agregar un nuevo valor `lesson` al enum de `assignment_type` ([liga](https://github.com/omegaup/omegaup/blob/master/frontend/database/schema.sql#L40)).  En otro issue vamos a hacer que el profesor pueda seleccionar `lesson` en la UI para su contenido.

## Para estudiantes:
![Screen Shot 2020-07-15 at 2 53 00 PM](https://user-images.githubusercontent.com/13296248/87601936-ec55b000-c6aa-11ea-967e-531f3839b070.png)

## Para profesores:
- Quitar la barra de progreso general, la columna de progreso por tarea y la columna de scoreboard.

El dropdown de 'Estadisticas' muestra: progreso de los estudiantes(`/students`), reporte de actividades(`/activity`), lista de envios(`/list`)

El dropdown de Editar curso te muestra links directos a : administrar estudiantes, añadir contenido

![dashboard_admin](https://user-images.githubusercontent.com/13296248/87258671-414eb780-c45a-11ea-909a-71bc169a63be.gif)

Liga a los iconos (pueden usarse otros iconos)
https://thenounproject.com/search/?q=exam&i=2188213
https://thenounproject.com/search/?q=lesson&i=1476946
https://thenounproject.com/search/?q=homework&i=1520826

**Comment by pabo99** [comment]
Para las plantillas que se muestran en bootsrap 4 estamos usando Font Awesome Icons, ¿crees que podamos buscar algunos parecidos del set que vienen ahí?

**Comment by pabo99** [comment]
¿Y que tal se vería el dashboard del curso si lo mostramos gráficamente? Se me ocurre algo como esto: 

![calendar](https://user-images.githubusercontent.com/3230352/85886488-d475c500-b7ab-11ea-86e8-ff350c9345a3.png)

Acá hay un [demo](https://neuronet.io/gantt-elastic/#/), y acá está la documentación: https://github.com/neuronetio/vue-gantt-schedule-timeline-calendar

**Comment by tvanessa** [comment]
Creo que estos iconos sirven:
lesson: https://fontawesome.com/icons/chalkboard-teacher?style=solid
exam: https://fontawesome.com/icons/list-alt?style=regular
homework: https://fontawesome.com/icons/file-alt?style=regular

Se ve muy bien la tabla. Creemos que será mejor meterlo para una segunda iteración para que sean más sencillos los cambios en esta ocasión.

**Comment by tvanessa** [comment]
Para calcular el "porcentaje completado general": tomar el promedio de los porcentajes completados de cada tarea/examen.

Nota: Le cambiamos el nombre a "porcentaje completado" para que no se entienda como la calificación del curso. La calificación final de curso la introducimos después.
