### ISSUE TITLE
[BUG] El markdown de un problema se despliega mal en un concurso pero bien afuera

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4288]
Hola amigos de omegaUp.

Ayer me pidieron el enlace a cierto concurso que yo organicé y noté que el rendering de un problema se muestra mal (es una regresión, porque se veía bien cuando lo organicé y no fue hace mucho). Curiosamente, el problema se despliega bien fuera del concurso.

Los enlaces relevantes son:
https://omegaup.com/arena/ER-AED-2019-I01/#problems/La-loca-mesa-del-te
https://omegaup.com/arena/problem/La-loca-mesa-del-te/#problems

![imagen](https://user-images.githubusercontent.com/19719969/86294481-383c2b80-bbba-11ea-90c8-634353419536.png)

**Comment by darkmx** [comment]
órale jaja, eso no me lo esperaba :) muchas gracias

**Comment by lhchavez** [comment]
coincidió que ya estaba abierto el PR y estaba esperando a que las pruebas terminaran.

**Comment by darkmx** [comment]
ahora está ocurriendo el mismo error incluso afuera de un concurso :( 
https://omegaup.com/arena/problem/La-fabrica-de-panquecitos/#problems
