### ISSUE TITLE
[FEATURE] Actualizar versión de C# 

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4293]
Actualmente tenemos la version 2.2 (del ~2005)

### Contexto
Los usuarios optan por usar Java porque C# es una versión muy vieja

**Comment by lhchavez** [comment]
Usamos [**dotnet** 2.2](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.7/2.2.7.md), no C# 2.2. Esa versión de dotnet soporta C# 7.3.
