### ISSUE TITLE
[FEATURE] Quitar `Output only` de la lista de lenguajes preferidos

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4294]
En https://omegaup.com/profile/edit/

![Screen Shot 2020-07-02 at 2 10 29 PM](https://user-images.githubusercontent.com/13296248/86409559-fb317100-bc6d-11ea-9bd5-dcc24eca517f.png)

**Comment by darkmx** [comment]
en algo relacionado, ¿podrían considerar que los lenguajes permitidos de un concurso aparezcan todos seleccionados por omisión? ya ha pasado (por ejemplo, en la liga omegaUp) que los concursantes se quejan de que no pueden enviar nada, porquea los organizadores del concurso se les olvidó que por omisión ninguno es permitido.

**Comment by pabo99** [comment]
> en algo relacionado, ¿podrían considerar que los lenguajes permitidos de un concurso aparezcan todos seleccionados por omisión? ya ha pasado (por ejemplo, en la liga omegaUp) que los concursantes se quejan de que no pueden enviar nada, porquea los organizadores del concurso se les olvidó que por omisión ninguno es permitido.

No logro reproducirlo. 

Lo que hice es crear un nuevo concurso y si me aparecían todos los lenguajes.

Después actualicé algunos campos del concurso y volví a ingresar, pero sigo viendo todos los lenguajes.

Quizás es algún caso que no es el que se da por omisión, ¿Puedes intentar reproducirlo y subirlo en otro issue porfa?

**Comment by darkmx** [comment]
Aparecen todos, pero deseleccionados D: se tienen que seleccionar manualmente.

![imagen](https://user-images.githubusercontent.com/19719969/86498996-3a36f380-bd4e-11ea-9913-696a5e290707.png)

 ¿Nos referimos a lo mismo?

**Comment by pabo99** [comment]
Si, es correcto, nos referimos a lo mismo. Quizás lo que se podría agregar en la descripción es que si no se selecciona ningún lenguaje, se podrán realizar envíos en todos los lenguajes disponibles.

Este es el ejercicio que acabo de realizar en el sandbox y todo funciona como debería:

![DefaultContestLanguages](https://user-images.githubusercontent.com/3230352/86499273-f1803a00-bd4f-11ea-8def-c4ae14b40803.gif)

**Comment by darkmx** [comment]
Ah, ya veo! lo que pasa es que en la liga omegaUp o en la copa centroamericana sí ocurrió que los lenguajes no estaban habilitados y los alumnos se quejaron pocos minutos después de comenzar (aunque de eso ya tiene varios meses). Me parece que Rafa tuvo que habilitarlos rápido en cuanto nos llegaron los mensajes de los alumnos. Mi confusión estribaba en que, cuando yo he organizado concursos posteriores y he visto que ninguno aparece seleccionado por omisión, me quedé con la idea de que lo mismo me podía ocurrir también en mis concursos.

Lo que mencionas de agregar esa descripción haría más claro todo.

**Comment by pabo99** [comment]
Debió haber sido algo que ya se corrigió. De cualquier forma ya se creó el Issue #4308 para hacer obligatorio el campo de lenguajes en un concurso y que todos los lenguajes disponibles se seleccionen por defecto.

**Comment by antedotee** [comment]
I think output-only is still showing.Can you assign it to me?

**Comment by pabo99** [comment]
> I think output-only is still showing.Can you assign this issue to me?

One question, @antedotee: Are you interested in participating in the GSoC 2024 program? If so, I recommend solving the problems in this contest: https://omegaup.com/arena/gsoc2024. Afterward, you can share your omegaUp username with us so that we can assign you an issue.

**Comment by antedotee** [comment]
i cleared the coding round of omegaup.Can you assign this issue to me now?
my omegaUp username is noob101

**Comment by pabo99** [comment]
Could you please start solving the first issue I assigned to you before?

**Comment by antedotee** [comment]
I have opened the pull request of the previous issue which was assigned to me.Can you please review that PR and assign this issue to me?

**Comment by pabo99** [comment]
> I have opened the pull request of the previous issue which was assigned to me.Can you please review that PR and assign this issue to me?

Done!
