### ISSUE TITLE
[FEATURE][Cursos UX] Lecturas tienen etiqueta inconsistente

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#4310]
## Comportamiento Esperado

Las lecturas deberían llamarse "Lectura" consistentemente en toda la plataforma

## Comportamiento Actual

Hay lugares donde todavía dice "Problema".
En particular en donde se despliega la fuente al final de la redacción de una lectura.

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Captura de pantalla
Sabemos que es una lectura:
![image](https://user-images.githubusercontent.com/189223/86506160-b139af80-bd81-11ea-805d-7a1dc3d2de4d.png)

Pero le decimos "Problema" al listar la fuente:
![image](https://user-images.githubusercontent.com/189223/86506174-d8907c80-bd81-11ea-97a0-61e680cebd6f.png)

**Comment by tvanessa** [comment]
Change the string `wordsProblemsetter` to
Spanish: `Subido por`  
Portuguese: `Proposto por`
English : `Uploaded by`

**Comment by tvanessa** [comment]
Assigning to @FishyFeeshy
