### ISSUE TITLE
[BUG][Curso C++] Contenido inapropiado

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#4313]
## Comportamiento Actual

En la introducción a variables, viene un hexadecimal muy particular: `0xcafebabe`. Así viene en el original, pero creo que es la idea de broma de alguna persona que editó el original.

## Comportamiento Esperado

Algún otro hexadecimal.

**Comment by heduenas** [comment]
Corregido. Gracias por reportar.
