### ISSUE TITLE
[BUG] Los problemas no se actualizan en cursos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4315]
Al editar un problema que está en un curso, la actualización sólo se ve reflejada cuando se accede al problema a través de la lista de problemas y no a través del curso.

Pasos para reproducir:
* Crear un problema.
* Crear un curso y añadir el problema.
* Editar el problema.
* Ver que no se actualiza el problema en el curso.

**Comment by pabo99** [comment]
No logro reproducir este issue, ya he intentado actualizar redacciones y el zip con los casos, pero parece que en ambos escenarios se actualiza correctamente. 

De cualquier forma, este cambio se puede enfocar en agregar el formulario de cambio de versión en problemas de cursos tal cual se muestra en concursos

**Comment by heduenas** [comment]
Donde actualizas el problema? A lo mejor yo no lo estoy actualizando como debería.

**Comment by pabo99** [comment]
> Donde actualizas el problema? A lo mejor yo no lo estoy actualizando como debería.

Desde la sección de "Ver historial de versión" en Editar problema:
![ChangeProblemVersion](https://user-images.githubusercontent.com/3230352/89617798-75967780-d850-11ea-99a0-bbac5e9fea23.gif)


También probé cambiar redacciones del problema y esas se reflejan sin tener que hacer algo extra:
![NewVersionProblemCourse](https://user-images.githubusercontent.com/3230352/89617869-952da000-d850-11ea-8970-9513a7a8a42f.gif)

De cualquier forma, ya subí el PR #4464 para poder editar la versión desde el curso.
