### ISSUE TITLE
[BUG] El markdown de un problema se despliega mal

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4321]
Hola amigos de omegaUp.

En #4288 había reportado un problema con el despliegue del markdown, aunque sólo ocurría en concursos. Ahora también está ocurriendo fuera de concursos.

https://omegaup.com/arena/problem/La-fabrica-de-panquecitos/#problems
El texto dice " (con dificultad) " pero los paréntesis los está mal interpretando.

![imagen](https://user-images.githubusercontent.com/19719969/86536040-2accbd00-beaa-11ea-9738-6c15e46a7ab8.png)

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/4311
