### ISSUE TITLE
[BUG] El link para editar un problema no funciona

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4322]
Hola amigos de omegaUp.

El link para editar problemas se rompió. Ahora me lleva a https://omegaup.com/problem/%7B$problem_alias%7D/edit/ sin evaluar el alias.

![imagen](https://user-images.githubusercontent.com/19719969/86536085-77b09380-beaa-11ea-8a53-48eefcfe96ce.png)

**Comment by lhchavez** [comment]
arreglado en https://github.com/omegaup/omegaup/commit/04dcd094f260070cf3b3a0885f35d326cdacfdfb

**Comment by pabo99** [comment]
Con razón no lo podía reproducir ni en local, ni en sandbox.
