### ISSUE TITLE
[BUG] Link "Editar" problema mal generado

### ISSUE THREAD

**Issue by alculquicondor** [omegaup/omegaup#4326]
## Comportamiento Esperado

*Click en editar problema desde la vista del problema abre el link correcto para editar*

## Comportamiento Actual

*Link errado*

`https://omegaup.com/problem/%7B$problem_alias%7D/edit/`

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome 81
* Sistema Operativo y versión (escritorio o móvil): Linux

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/4322
