### ISSUE TITLE
[BUG] Error con administrador de cursos

### ISSUE THREAD

**Issue by NetoDios** [omegaup/omegaup#4328]
## Comportamiento Actual

Eror 404, al querer entrar a ver los envios realizados por los participantes de un curso, el link proporcionado arroja un error 404

## Pasos para reproducir (para bugs)

Este es un problema que encontre en los cusros que administro, no lo he visto replicado en otros lugares como los concursos.

1. Desde el navbar, el boton "Cursos"
2. En la seccion de "Cursos que administro", el link del curso a ver
3. Desde la seccuin de "Tareas" o "Exámenes", el link (o el boton "Envios") a una tarea
4. Error 404

## Contexto

No soy el creador original del curso, pero somos un grupo de trabajo (6 personas) que activamente ponemos tareas para los participantes, y nos es importante revisar los envios porque comunmente nos hacer preguntas en relacion a errores que obtienen, y de igual forma, nosotros revisamos estos envios periodicamente para evitar plagios.
Asumo es un error en la sintaxis del link al que me redirige.

## Ambiente

Actualmente uso Chrome en Windows 10.

**Comment by tvanessa** [comment]
Solo hemos podido reproducirlo si eres admin pero no dueño (los owners si pueden verlos)
Además de los envíos, esta rotos los links  a las tareas estilo: omegaup.com/course/introduccion_a_algoritmos/assignment/busqueda_binaria/admin/
