### ISSUE TITLE
El modo ADMIN dentro de los "assignments" de los cursos no funcionan.

### ISSUE THREAD

**Issue by BubuDavid** [omegaup/omegaup#4333]
## Comportamiento Esperado
Se supone que al entrar a una página de assignments en un curso de OmegaUp como Admin deberías de ser capaz de subir problemas y ver los códigos de los alumnos, pero no funciona.

## Comportamiento Actual
Me arroja una página en blanco con el logo de Omega y con descripción: **HTTP/1.1 404 - Not Found**
## Pasos para reproducir (para bugs)
1. Entrar a OmegaUp con su cuenta.
2. Ingresar a un curso donde seas administrador. 
3. Entrar a algún _Assignment_.
4. Observar el error.

## Contexto
Se supone que debería de ser capaz de ver como van las personas que están tratando de resolver los problemas (Me interesa personalmente porque yo hice cada uno de los problemas y me quiero asegurar de que no exista algún tipo de confusión o error de mi parte) pero no puedo ver nada a menos que salga del modo ADMIN.
**Importante: Este bug solo está presente para ADMINS**

* Nombre del navegador: Google Chrome
* Sistema Operativo y versión: Windows 10
* Link al sitio en el que este problema pasa: https://omegaup.com/course/Curso-de-Python-FutureLabs/assignment/Funciones/admin/
* Captura de pantalla:
![Report Issue](https://user-images.githubusercontent.com/50858626/86854853-e0506980-c07e-11ea-93ac-badd6a29fcdf.PNG)

**Comment by tvanessa** [comment]
#4338
