### ISSUE TITLE
Yo como usuario administrador de curso, necesito borrar un problema que tiene envíos aceptados.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#4339]
*Provee un título para esta sugerencia con el siguiente formato:*

*Yo como usuario administrador de curso, necesito borrar un problema que tiene envíos aceptados.

## Comportamiento Esperado

*Debería permitirme remover un problema (tarea) de un curso aunque tenga AC el problema en cuestión.

## Comportamiento Actual

No me permite borrar el problema debido a que tiene ACs

## Alternativas consideradas

Generar una subtarea o correción general.
## Contexto

Si un problema esta mal redactado y me doy cuenta tarde, afectara al resto de usuarios.

## Tu ambiente
* Captura de pantalla:

<img width="930" alt="Captura de Pantalla 2020-07-08 a la(s) 20 18 54" src="https://user-images.githubusercontent.com/5459260/86986380-2c6fdc80-c159-11ea-93f7-6b40d75b6e3c.png">

**Comment by lhchavez** [comment]
contrapunto: si se borra el problema, va a afectar a los que ya lo resolvieron.

**Comment by MiguelRomero** [comment]
> contrapunto: si se borra el problema, va a afectar a los que ya lo resolvieron.

Facto, pero el problema esta mal elaborado, entonces implicitamente no es la respuesta correcta los acs

**Comment by lhchavez** [comment]
entonces no importa qué se haga, se va a afectar gente :( pero parece que se afecta menos gente si no se pueden borrar cosas.

**Comment by MiguelRomero** [comment]
Depende del caso pero creo que podríamos poner un modal donde el administrador del curso es consiente de la afectación.

**Comment by lhchavez** [comment]
ya se! mejor hay que advertir _al agregar_ problemas que una vez que se tenga un AC, el problema se vuelve permanente.

**Comment by MiguelRomero** [comment]
Lo que creas más conveniente, para mi esta bien.
