### ISSUE TITLE
[BUG] No se puede descargar la plantilla de problemas interactivos

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#4340]
En cualquier programa interactivo, si intentas bajar la plantilla en cualquier lenguaje para cualquier sistema operativo, sin importar si iniciaste sesión o no, o qué browser uses, no baja el zip, a veces solo recarga la página y a veces se va al tope de la página, pero no descarga el zip.

**Comment by lhchavez** [comment]
sale algo en la consola? puedes compartir el enlace completo de un problema donde esto ocurre?

**Comment by darknut** [comment]
En la consola no se ve nada
Aquí hay un problema https://omegaup.com/arena/problem/Cables-Cruzados
