### ISSUE TITLE
[FEATURE] Cambiar "Agregar estudiante" por "Administrar estudiantes"

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4346]
Esa liga lleva a una UI que permite hacer más operaciones que agregar estudiantes.
![image](https://user-images.githubusercontent.com/597815/87136534-7e475e00-c250-11ea-8bc5-b0364473172f.png)

**Comment by heduenas** [comment]
@michellechiq99 can you take on this bug?

**Comment by tvanessa** [comment]
Cambiar la cadena `wordsAddStudent` a:

ES: Administrar estudiantes
EN: Manage students
PT: Gerenciar alunos
