### ISSUE TITLE
[BUG] Cuando quiero entrar a un concurso me pregunta "Sí" o "No" sin contexto

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4351]
Por ejemplo en https://omegaup.com/arena/ONI2020PRACTICA/  me muestra esto
![Screen Shot 2020-07-10 at 5 10 56 PM](https://user-images.githubusercontent.com/13296248/87212159-f6a23380-c2d1-11ea-9fd3-66d825611291.png)

## Posible solución
Dar contexto cuando se selecciona la opción: `Solicitar acceso a información de los participantes` ~~Quitar los radio buttons cuando el admin del concurso pide la información básica requerida~~

**Comment by pabo99** [comment]
Creé un concurso en el que se requiere la información básica y si me muestra correctamente el intro:

Usuario con información completa en su perfil:
![image](https://user-images.githubusercontent.com/3230352/87229757-8eeef580-c370-11ea-827f-80e149d674ba.png)

Usuario sin información completa en su perfil:
![image](https://user-images.githubusercontent.com/3230352/87229776-b04fe180-c370-11ea-8ac3-d49cafc59cb4.png)


Debe ser un caso que no se está considerando de acuerdo a la configuración del concurso, porque yo lo veo correctamente si lo configuro así:

![image](https://user-images.githubusercontent.com/3230352/87229697-fe181a00-c36f-11ea-982d-10c0d71ee06e.png)

¿Me puedes indicar si hay alguna diferencia en la configuración del tuyo con respecto al que te muestro? De esa forma puedo probar más casos

**Comment by tvanessa** [comment]
Tienes razón, esa no es la causa. Más bien es `Solicitar acceso a información de los participantes` en la opción `Requerido`

**Comment by heduenas** [comment]
Poner la leyenda "¿Dar acceso a los administradores del curso a tu información?" / "Grant access to your information to the contest admins?" / "Conceder acesso às suas informações aos administradores do concurso?"
