### ISSUE TITLE
[BUG] No cargan los perfiles de usuario

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4353]
Hola amigos de omegaUp.

Los perfiles de usuario andan cuchos. Por ejemplo https://omegaup.com/profile/osmar/ y https://omegaup.com/profile/rcc

![imagen](https://user-images.githubusercontent.com/19719969/87227451-a7571400-c360-11ea-8d10-6465ace79dc7.png)

**Comment by mjayalam** [comment]
Hola!, acabo de entrar a los perfiles, y se me muestran correctamente, parece ser que el error se da cuando no se ha iniciado sesión y quieres verlos, eso que muestras es con la sesión iniciada?

**Comment by darkmx** [comment]
Ah, creo que no había iniciado sesión (igual, deben aparecer). Logueado sí se muestran.
