### ISSUE TITLE
[FEATURE] Mejorar el title="..." de las páginas del sitio

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4359]
Hola amigos de omegaUp.

Cuando hacemos muchas cosas en la plataforma y abrimos muchas pestañas, con frecuencia queremos ir a o reabrir alguna en particular. Esto se vuelve un poco difícil sin ver el URL de la página, porque el `title="..."` no ayuda a distinguir pestañas. En el caso de los problemas, sería ideal que el `title` de la página incluyera el nombre del problema.

![imagen](https://user-images.githubusercontent.com/19719969/87253305-d42e2880-c43f-11ea-992c-029ccb152d27.png)

![imagen](https://user-images.githubusercontent.com/19719969/87253280-99c48b80-c43f-11ea-9805-02fc5038bd3e.png)

**Comment by lhchavez** [comment]
lo bueno es que con la migración a Vue y la nueva plantilla unificada esto ya es bastante más sencillo!

**Comment by pabo99** [comment]
De hecho ya se solucionó:

![image](https://user-images.githubusercontent.com/3230352/220788532-5f94ba3a-bc72-443e-9ea7-6d1cbf8b5cef.png)


Así que se cierra el issue
