### ISSUE TITLE
[FEATURE] Como un creador, quiero enlace para editar concurso creado

### ISSUE THREAD

**Issue by alculquicondor** [omegaup/omegaup#4360]
*Como un creador, quiero enlace para editar concurso creado*

Una vez que un concurso ha sido creado, no hay ningún enlace que lleve a la plataforma de edición.

Ejemplo:

1. Voy a https://omegaup.com/arena/
1. Accedo a un concurso creado por mí
1. Aparece dashboard con descripción del concurso

## Comportamiento Esperado

Un enlace para editar el concurso

**Comment by pabo99** [comment]
La opción de editar concursos creados se movió a otro menú, ahora lo puedes encontrar en:

![EditContest](https://user-images.githubusercontent.com/3230352/87254997-9d124400-c44c-11ea-9453-c021b97e3828.gif)

**Comment by alculquicondor** [comment]
Oh gracias!
Igualmente un enlace en el concurso mismo sería útil. Tal cual hay en los problemas que uno crea.

**Comment by IngridRB** [comment]
Hola @heduenas, puedo tomar este issue? Ya mandé un PR sobre el otro que tenía asignado (https://github.com/omegaup/omegaup/pull/6930)

**Comment by IngridRB** [comment]
Hola @heduenas, puedo tomar este issue? Ya mandé un PR sobre el otro que tenía asignado (https://github.com/omegaup/omegaup/pull/6930)

**Comment by heduenas** [comment]
Hecho!
