### ISSUE TITLE
[FEATURE] Permitir que usuarios clonen un curso sin agregarlos como administrador

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#4362]
##Comportamiento Esperado

Backend debe permitir que usuarios invitados clonen un curso que yo cree/administro sin que los tenga que agregar como adminsitradores. Quiero que puedan crear una copia de mi curso, pero no quiero darles permisos para modificar el mio.

**Comment by lhchavez** [comment]
Esto suena razonable. Lo único sería que esto no estaría disponible si hay al menos un problema privado en el curso. O crees que sería mejor advertir "hey, esta lista de problemas son privados y no estarían disponibles en el curso clonado:" y dejar que lo clonen de cualquier manera?

**Comment by npave** [comment]
Creo que vamos a necesitar buscar una solución más compleja. El principal caso de uso que tengo en mente es permitir que profesores clonen cursos que se están desarrollando. Pero estos cursos tienen contenido+problemas. Ahorita el contenido se crea con formato problema privado para que nadie lo use/modifique. Entonces, si no se puede clonar problemas privados, no podrán clonar cursos con contenido. Además, en el futuro podríamos querer crear problemas privados para agregar a un curso para un grupo de escuelas. En este caso, los profesores debería poder clonar el curso aún cuando tenga problemas privados.

Qué tal si agregamos un nivel intermedio de acceso (lectura de cosas privadas, pero sin poder para modificarlas) para problemas, igual como lo estamos proponiendo aquí para cursos?

**Comment by lhchavez** [comment]
> Ahorita el contenido se crea con formato problema privado para que nadie lo use/modifique. 

welp, esto por qué es? lo de que nadie lo modifique se puede arreglar con hacer el contenido público, pero cuál sería la razón por la cual alguien querría que nadie use el contenido, pero que sí permita clonarlo? como que ese caso de uso intermedio es el que no estoy entendiendo.

**Comment by npave** [comment]
La redacción no fue la adecuada, dejame explicar mejor.
Necesito poder crear problemas que no se puedan modificar y que solo algunos usuarios puedan ver. 
Un ejemplo de caso de uso es el siguiente: una organización educativa quiere crear un curso con contenido y problemas para que lo utilice solo su grupo de escuelas. Para ello crea un comité que es el encargado de desarrollar el curso, solo ellos pueden modificar el contenido y los problemas. Es importante que los problemas no sean públicos porque algunos de ellos pueden ser los exámenes. Cuando el curso esté listo, los profesores necesitan clonarlo. Entonces los profesores pueden ver todo el curso incluido los problemas y decidir cual es el mejor momento para que sus estudiantes vean cada problema.

**Comment by heduenas** [comment]
Diseño: https://docs.google.com/document/d/1zyjVp-P9kWuyiXslGo2kcjzcqhMVxlhYgeCQym5Q2Y0/edit?ts=5f29d001#heading=h.zhcp01px2qvq

**Comment by pabo99** [comment]
Con el cambio del PR #4565 ya se completó este issue. Ya se puede cerrar =D
