### ISSUE TITLE
[BUG] En la lista de envíos, los enlaces a los perfiles de los usuarios son incorrectos.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4364]
Hola amigos de omegaUp.

En la lista de envíos, los enlaces a los perfiles de los usuarios abren el problema en sí y no el perfil del usuario. Aparentemente, el problema es que los enlaces ahora tiene `href="#"`  

![imagen](https://user-images.githubusercontent.com/19719969/87262029-16765a80-c47e-11ea-9ed5-4688a891d1dc.png)
![imagen](https://user-images.githubusercontent.com/19719969/87262069-30b03880-c47e-11ea-9d6e-f7eb66a4d97e.png)

**Comment by lhchavez** [comment]
abren el problema?! se supone que deberían filtrar la tabla para que sólo aparezcan envíos de ese usuario.

pero el comportamiento de que haciendo click a eso NO te lleve al perfil es el deseado. para eso está el ícono de la cajita y la flecha a la derecha.

**Comment by darkmx** [comment]
Ah ya D: feature nuevo. Supongo que lo me sacó de onda es que un comportamiento de toda la vida sufriera un cambio repentino.
Cierro el issue.

**Comment by lhchavez** [comment]
xkcd obligatorio: https://xkcd.com/1172/
