### ISSUE TITLE
[BUG] Las calificaciones se exportan de forma inadecuada en ODS

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4368]
Hola amigos de omegaUp.

Cuando se tiene un curso y se exportan las calificaciones de los alumnos en formato ODS, las calificaciones se exportan con una comilla sencilla antes de cada valor numérico. Por ejemplo: 

https://omegaup.com/course/aed2020i/students/
![imagen](https://user-images.githubusercontent.com/19719969/87317784-16617380-c4ed-11ea-9e59-78d2a7418603.png)

Esto impide aplicarles una fórmula matemática (ej. una suma) directamente. El CSV se ve bien, aunque una inconsistencia menor es que ante la ausencia del nombre del usuario, en ODS aparece una celda en blanco y en el CSV aparece null.

![imagen](https://user-images.githubusercontent.com/19719969/87318292-c2a35a00-c4ed-11ea-80d6-4259650a420c.png)

![imagen](https://user-images.githubusercontent.com/19719969/87318315-c931d180-c4ed-11ea-802f-15d4c22d8bab.png)

**Comment by lhchavez** [comment]
Parece que esto se arregló sin querer en #4746, aunque el porcentaje aún no se muestra correctamente.
