### ISSUE TITLE
No puedo editar, resolver ni visualizar un problema que acabo de subir a la plataforma

### ISSUE THREAD

**Issue by YaelMontoya** [omegaup/omegaup#4382]
## Comportamiento Esperado

Poder editar, resolver o minimo visualizar mi problema

## Comportamiento Actual

Pos no pasa

## Posible Solución

No se :'v

## Contexto

Quiero que funcione mi problema :c
 
He intentado desde otra cuenta y no me deja realizar el problema tampoco

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/(KHTML, like Gecko) Chrome/
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/Numeros-Ciclicos/

**Comment by darkmx** [comment]
Curiosamente, los problemas sí aparecen listados en la lista de problemas.
![imagen](https://user-images.githubusercontent.com/19719969/88075834-f2321200-cb3e-11ea-9122-fecd1dbdf594.png)

**Comment by NetoDios** [comment]
Me sucede lo mismo, recién hice un problema para aprender a utilizar la tecnología de libinteractive, lo hice desde una cuenta nueva, y marque el problema como privado.

Quizá alguna de esas variantes, o la combinación sean fuente de problema.

Igual forma utilizo Google Chrome en Windows 10.
Id del problema que subí: 11548

**Comment by tvanessa** [comment]
@YaelMontoya tu problema es interactivo?
@NetoDios puedes compartir el alias/nombre de tu problema?

**Comment by NetoDios** [comment]
@tvanessa claro, como mencioné, estoy intentando aprender como hacer problemas e hice este como prueba.
Nombre: No Hacer Envios - Probando
Alias: NHE1
Link (pero esta en privado lol): https://omegaup.com/arena/problem/NHE1/

**Comment by lhchavez** [comment]
esto es porque falta el archivo `statements/es.markdown` como menciona la guía: https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-escribir-problemas-para-omegaUp#statements

lo que falta es hacer que esto falle al momento de intentar subir el problema en vez de después al intentar verlo/editarlo.

**Comment by YaelMontoya** [comment]
:c El archivo statements/es.markdown si esta, al igual que las otras carpetas que deben de estar, la verdad no se en que me estoy equivocando, ya revise los nombres de las carpetas y archivos pero todo esta bien

**Comment by YaelMontoya** [comment]
chale, ya vi en que me equivoque, gracias por sus comentarios
