### ISSUE TITLE
[FEATURE] [Cursos UX] Mejoras en el listado de cursos

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#4387]
Mejorar la vista del listado de cursos. Se pretende que en el listado se muestre la siguiente información:

- Nombre del curso.
- Nombre de la escuela.
- Tiempo restante de finalización (para el caso de curso con fecha de fin).
- Porcentaje de avance (de preferencia mostrar gráficamente).
- Botón que lleve al usuario al curso (ya sea para iniciar o para continuar).
- Para los cursos públicos, mostrar el temario.

La propuesta del diseño es la siguiente:

![image](https://user-images.githubusercontent.com/3230352/87615934-7a488f80-c6d9-11ea-909e-c2b44aee7b3b.png)

**Comment by tvanessa** [comment]
De los pendientes:
 - Definir cuántos cursos se deben mostrar en la vista
    - Públicos: Todos
    - Que estudio:  5 cursos
 - Definir los criterios para ordenar los cursos:
    - Públicos: Fecha de creación, primero los más recientes
    - Que estudio: Si no es muy costoso, por fecha de última actividad (último envio), primero los más recientes.
 - Definir que información debe desplegar cuando se presione el icono de información
    Aún se está definiendo. Espero completarlo esta tarde.
 - Definir si se debe ocultar un curso del listado público cuando un usuario accedió a él
    No, solo poner el botón como continuar

**Comment by pabo99** [comment]
> Públicos: "omegaUp ofrece cursos gratuitos y bajo demanda para que aprendas a programar y mejores tus habilidades de programación."
> * Que estudio: "Aquí encontraras la lista de los cursos a los que te inscribiste y los cursos que organizan tus profesores."
>   @pabo99 te dejo los strings, gracias

Si me puedes ayudar con las traducciones, te lo agradecería mucho, para no hacer tantas iteraciones en las revisiones.

**Comment by tvanessa** [comment]
PUBLICO 
"Cursos de programación bajo demanda que omegaUp ofrece de forma gratuita." 
"On-demand courses that omegaUp offers for free."
"Cursos sob demanda que o omegaUp oferece gratuitamente."

QUE ESTUDIO
"Aquí encontraras la lista de los cursos en los que te has inscrito." 
"Here you will find the list of courses that you are enrolled in."
"Aqui você encontrará a lista de cursos nos quais está matriculado."
