### ISSUE TITLE
[BUG] El tamaño de los iconos de badges creció dramáticamente

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#4397]
Los iconos en los badges se hicieron muy grandes y se muestran de esta forma:

![image](https://user-images.githubusercontent.com/3230352/87839769-e9e98680-c861-11ea-9312-2f26e3194dc4.png)

**Comment by mjayalam** [comment]
Oh, estuve revisando, e incluso en mi rama principal de los cambios de perfil, se reproduce ese bug, tanto en la lista de todos los badges como en el perfil del usuario:

![image](https://user-images.githubusercontent.com/12377916/87854466-d24ce500-c8d7-11ea-97e5-3f63db8245f1.png)

Ahora, intentando solucionarlo, nos manda a un estado exactamente igual a #4262  en ambas secciones, también @tvanessa  te había comentado que #4262  no ocurría, pero es un hecho que ahora ya ocurre intentando solucionar este bug  u.u

![image](https://user-images.githubusercontent.com/12377916/87854608-beee4980-c8d8-11ea-8d2c-f45af14fb6f0.png)
![image](https://user-images.githubusercontent.com/12377916/87854616-cc0b3880-c8d8-11ea-8fb2-f5a1b645cdfc.png)
