### ISSUE TITLE
[FEATURE] Cuando edito un problema y lo guardo me dice "Falta un valor requerido"

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4413]
No dice cuál es el campo que no he completado. En mi caso, faltaba completar la descripción del cambio.

![Screen Shot 2020-07-21 at 8 47 20 PM](https://user-images.githubusercontent.com/13296248/88132121-8d54d700-cb93-11ea-9bd8-56271271a472.png)

## Posible solución
Marcar en rojo los campos que faltan

**Comment by pabo99** [comment]
La solución a este problema es quitar las validaciones manuales que agregamos y empezar a usar las de Bootstrap, ya hay un par de formularios que las usan:

![image](https://user-images.githubusercontent.com/3230352/88225088-88ddfc00-cc2f-11ea-8a77-b5188e5541a9.png)
