### ISSUE TITLE
[BUG] Time-out al editar un problema

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4420]
Hola amigos de omegaUp.

Al menos desde ayer, la petición realizada al editar un problema (ej. cambiar casos o modificar el tiempo límite) provoca un error de timeout (ocasionalmente me da error interno del servidor en lugar de timeout). Esto lo puedo replicar consistentemente sólo en algunos problemas y sólo mediante algunas acciones específicas (ej. cambiar los casos o bajarle el tiempo). Un problema donde sí pude replicarlo consistentemente es https://omegaup.com/problem/Programando-formulas/edit/

![imagen](https://user-images.githubusercontent.com/19719969/88398948-b93aad00-cd8b-11ea-8ba3-f7194c949d83.png)

![imagen](https://user-images.githubusercontent.com/19719969/88394550-3d3d6680-cd85-11ea-8cee-71b536d578ee.png)

Al abrir de nuevo el problema, parece que la edición sí se realizó. Sin embargo, pareciera que no todos los envíos se reevaluaron (y los que aparecen con `new` tardan incluso media hora en reevaluarse).

**Comment by lhchavez** [comment]
si un envío se hizo en el contexto de un concurso _no_ debería reevaluarse (así que eso es WAI).

los que están en la cola _deberían_ aparecer con `new`, y como se reevalúan con prioridad más baja, es razonable que se tarde tanto. si ya hay muchos envíos en la cola (ahorita hay más de 1000), el timeout es razonable para evitar que la cola crezca de manera descontrolada.

**Comment by lhchavez** [comment]
a lo más lo que podríamos hacer es que los rejudge se hagan de manera asíncrona para evitar el timeout.

**Comment by darkmx** [comment]
es decir, ¿el timeout es sinónimo de "la cola está muy llena, estoy esperando a _al menos_ poder agregar los envíos en la cola"?

**Comment by lhchavez** [comment]
correcto!

**Comment by darkmx** [comment]
ta muy complicado todo jaja :( lo del redjuge asíncrono suena a que se volverá la cola de la cola, pero posiblemente evitar el timeout complique algo en algún lado de todos modos; creo que mejor cierro el issue, gracias!

**Comment by lhchavez** [comment]
sí, conforme los servicios escalan y crecen, se vuelven complicados :(
