### ISSUE TITLE
[BUG] No es posible crear problemas

### ISSUE THREAD

**Issue by msclecram** [omegaup/omegaup#4427]
## Comportamiento Esperado

*Al llenar el formulario para crear un problema nuevo, el problema se crea correctamente.

## Comportamiento Actual

*Al intentar crear el problema, sale el mensaje 'Missing required field'. Respuesta: {"status":"error","error":"Empty parameter.: problem_alias","errorname":"parameterEmpty","errorcode":400,"header":"HTTP\/1.1 400 BAD REQUEST","parameter":"problem_alias","_id":"5f1dbf453c795190026489"}

## Pasos para reproducir (para bugs)

1.  Llenar el formulario de un problema.
2.  Intentar crear el problema.

## Tu ambiente

* Windwos 10, Chrome.

**Comment by lhchavez** [comment]
logs:

```
2020-07-26T17:37:09+00:00 [INFO]: 5f1dbf453c795190026489 /api/problem/details/ OmegaUp\Exceptions\InvalidParameterException: parameterEmpty in /opt/omegaup/frontend/server/src/Validators.php:555
Stack trace:
#0 /opt/omegaup/frontend/server/src/Validators.php(128): OmegaUp\Validators::isPresent()
#1 /opt/omegaup/frontend/server/src/Controllers/Problem.php(2340): OmegaUp\Validators::validateValidAlias()
#2 [internal function]: OmegaUp\Controllers\Problem::apiDetails()
#3 /opt/omegaup/frontend/server/src/Request.php(69): call_user_func()
#4 /opt/omegaup/frontend/server/src/ApiCaller.php(26): OmegaUp\Request->execute()
#5 /opt/omegaup/frontend/server/src/ApiCaller.php(92): OmegaUp\ApiCaller::call()
#6 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): OmegaUp\ApiCaller::httpEntryPoint()
#7 {main} (/opt/omegaup/frontend/server/src/ApiCaller.php:345) 
```

esto está ocurriendo al momento de validar que el alias no está siendo usado. se está mandando `alias` en vez de `parameter_alias` como parámetro.
