### ISSUE TITLE
[BUG] No puedo visualizar las clarificaciones correctamente. 

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#4433]
## Comportamiento Esperado

Yo como administrador de un concurso necesito visualizar las preguntas que tengan los concursantes dentro del apartado de clarificaciones.

## Comportamiento Actual

Aparece el número de clarificaciones totales pero no el contenido de las mismas.

## Pasos para reproducir (para bugs)

1. Entrar como administrador a un concurso.
2. Click sobre clarificaciones.

## Contexto

Yo como administrador de un concurso no puedo aclarar dudas de los participantes de la misma.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome (Versión más reciente)
* Sistema Operativo y versión (escritorio o móvil): Windows 10
* Captura de pantalla:
![116050643_849397738921443_1491826015806045055_n](https://user-images.githubusercontent.com/5459260/88825298-03a59a80-d18d-11ea-803a-799b638a4294.png)

**Comment by MiguelRomero** [comment]
@lhchavez Hola! Buenos días, es el Bug que reporta Marcel! daré seguimiento, creo que urge debido a que esta en media competencia. 

Saludos!

**Comment by pabo99** [comment]
Enterado.
