### ISSUE TITLE
[Badge Proposal] Badge para graduado de Curso de Intro a Algoritmos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4436]

**Comment by heduenas** [comment]
@RodCross, te estoy asignando este isssue. Cualquier pregunta que tengas @carlosabcs es el gurú de los bastes.

**Comment by RodCross** [comment]
@heduenas, he visto que hay dos cursos de introducción a algoritmos ¿en todo caso también debería haber una badge para la segunda parte?

**Comment by heduenas** [comment]
Sí, suena bien hacerlo de una vez.
