### ISSUE TITLE
[BUG] Sumissions llevan días atorados en new

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#4443]
Problema: [cables cruzados](https://omegaup.com/arena/problem/Cables-Cruzados)
Usuario: Sebs

![image](https://user-images.githubusercontent.com/123875/88982585-8574f100-d27d-11ea-9648-7135301ecdb9.png)

GUIDS:
9029e6cf
14b226d5
b9d38a1a
97d0ef52
6bf192c2

Submissions nuevos se quedan también atorados para este usuario en particular, pero para otros usurios, sí les da respuesta.

Subimos este código en otra cuenta y al parecer ahí tambien se traba. Puede que el código tenga algo que ver.

**Comment by lhchavez** [comment]
huh, esos deberían ser JE: el validador/código no-del-participante está arrojando una excepción. los logs y los outputs están disponibles.

deja los cambio a JE a mano para que no se vean feos.
