### ISSUE TITLE
[BUG] Imposibilidad de escoger 09 como mes (septiembre) al crear un concurso

### ISSUE THREAD

**Issue by omarpaladines** [omegaup/omegaup#4445]
## Comportamiento Esperado

Posibilidad de agendar un concurso durante el mes de septiembre.

## Comportamiento Actual

Al intentar agendar un concurso para el mes de septiembre, seleccionando 09 tanto en el input o en el calendario dado, se muestra 10 (Octubre) en lugar. No me es posible seleccionar ninguna fecha en septiembre.

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Crear un concurso.
2. Intentar seleccionar 09 como mes, ya sea directamente en input o en el calendario que se muestra.

## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
*El contexto que nos proporciones nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Versión browser: Chrome version 83
* OS: macOS Catalina
* Link al sitio en el que este problema pasa:
* Captura de pantalla:

**Comment by tvanessa** [comment]
El problema que tienes es que el componente no te deja cambiar a ningún mes? o sólo no te permite seleccionar en septiembre?

Si te paso lo primero, es probable que sea porque están "escondidas" las flechas para moverse ):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13296248/89091620-c34a4600-d35f-11ea-9d4c-26b49273777e.gif)

**Comment by omarpaladines** [comment]
Si me dejaba escoger otros meses. Simplemente como que había un Gap entre 08 y 10. Intentaré moverme con las flechas y seleccionar así. Ese detalle no lo había visto. 

Gracias!

**Comment by omarpaladines** [comment]
De hecho, si me salen las flechas. Esto es lo que yo veo:

[image: Screen Shot 2020-07-31 at 7.22.27 PM.png]

Ahí tengo seleccionado el 1 de septiembre, pero se queda en 10. Por alguna
razón no es igual a lo que mostraste en el mensaje anterior.

**Comment by omarpaladines** [comment]
Parece que hoy ya me deja. Quizá haya sido algo de mi browser. Gracias igualmente por revisarlo.
