### ISSUE TITLE
Failed to query MySQL (1213): Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#4457]
A veces cuando se envía un código, la página no responde y eventualmente envía estos errores

![image](https://user-images.githubusercontent.com/123875/89460131-a37b9f00-d71e-11ea-8af3-96db1a7a8c64.png)

![image](https://user-images.githubusercontent.com/123875/89460160-affff780-d71e-11ea-9f5b-d2ca1e21b419.png)

El código sí se envía y eventualmente se evalúa, pero esto ocasiona que el usuario pueda darle click multiples veces al botón enviar sobrepasando el check de tiempo. Y dado que la pantalla de envio de código no se cierra sola, la acción más obvia para el usuario es dar clic a enviar multiples veces:

![image](https://user-images.githubusercontent.com/123875/89460264-da51b500-d71e-11ea-80c7-cb57a159f87f.png)

Me ha pasado con este problema:
https://omegaup.com/arena/problem/OMI-2017-Escalones/#problems/OMI-2017-Escalones

**Comment by lhchavez** [comment]
Esto ya no ha pasado últimamente.
