### ISSUE TITLE
No me deja hacer una pregunta en el área de preguntas de omegaup

### ISSUE THREAD

**Issue by 5an7y** [omegaup/omegaup#4461]
## Comportamiento Esperado

Poder ingresar con mi usuario para hacer una pregunta en Omega Up.

## Comportamiento Actual

Al momento de hacer click en **ingresar** me redirige de nuevo a la misma pagina. Y si hago click en **registrarme** me dirige a la pagina de mi perfil en OmegaUp.

## Posible Solución

Si esta pagina ya no esta en uso, no debería aparecer en *ayuda*

## Pasos para reproducir (para bugs)

1.  Ingresar a Omegaup > Ayuda > Preguntas > Hacer una pregunta
2. Click en *registrar* te regresa a la misma pagina
3. Click en *ingresar* te dirige a tu perfil de omegaup

[Click here to see video](https://drive.google.com/file/d/1IEMmjDTquXQQuIyZWjKrfWZCPIgxainf/view?usp=sharing)

## Contexto

Quería hacer una pregunta acerca de ciertas funcionalidades y cuando quería hacerlo me tope con este issue. 

* Nombre del navegador: Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
* Link al sitio en el que este problema pasa: https://omegaup.com/preguntas/ask

**Comment by lhchavez** [comment]
Ya no aparece en ayuda.
