### ISSUE TITLE
[FEATURE] Mensaje de éxito al ejecutar el comando ./stuff/lint.sh

### ISSUE THREAD

**Issue by BlueBlockGrape** [omegaup/omegaup#4480]
*Como [programador], quiero [un mensaje de éxito] para [saber que el comando ./stuff/lint.sh se ejecuto correctamente y que no hubo errores después de finalizar de ejecutarse]*

## Comportamiento Esperado

*Un mensaje de éxito al final de ejecutarse el comando ./stuff/lint.sh en el caso de que todo salió bien y no hay nada que corregir*

## Comportamiento Actual

*Solo se ejecuta el comando y no regresa algún tipo de mensaje*

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a saber si no hubo errores en la ejecución*

## Tu ambiente

*vagrant*

**Comment by lhchavez** [comment]
para arreglar esto, hay que quitarle el `exec` a https://github.com/omegaup/omegaup/blob/56d4c3f33d268282083597d04b3cd29c7cd0aa41/stuff/lint.sh#L39, agregar `set -e` arriba de L3 y poner `echo OK` al final del archivo.
