### ISSUE TITLE
Conectar el componente Problem Details con Arena y eliminar el código heredado

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#4493]
Part of: #3489

**Comment by lhchavez** [comment]
Para poder darle revert a https://github.com/omegaup/omegaup/pull/4724, hay que agregar una prueba de Selenium que las clarificaciones sigan funcionando para evitar https://github.com/omegaup/omegaup/issues/4723

**Comment by pabo99** [comment]
> Para poder darle revert a #4724, hay que agregar una prueba de Selenium que las clarificaciones sigan funcionando para evitar #4723

Listo, el PR #4732 ya contiene la prueba en selenium para las clarificaciones. También ya hice el `reland` del `revert` y lo subí en el PR #4733
