### ISSUE TITLE
[FEATURE] Deprecar omegaup.com/preguntas

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4496]
@lhchavez sabes cuáles son los pasos para hacer esto?

**Comment by lhchavez** [comment]
quitar los enlaces y ya.

**Comment by tvanessa** [comment]
Parece que el único lugar es el navbar 
![Screen Shot 2020-08-17 at 3 27 48 PM](https://user-images.githubusercontent.com/13296248/90450319-44af1180-e09e-11ea-8cae-c12e7957ed10.png)
