### ISSUE TITLE
[FEATURE] Problemas con el tab "Modo de acceso" en Editar Curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#4499]
## Comportamiento Esperado

La vista al cambiar entre tabs debería ser la misma que al recargar la página.

## Comportamiento Actual

Cambio el modo de acceso a un curso de "Manual.." a "Compartir URL.." y guardo los cambios sin ningún problema. Cambio de tab y cuando regreso el campo "Modo de acceso" dice "Manual..". Si no modifico nada y recargo lo página, el campo de "Modo de acceso" dice "Compartir URL..."

![image](https://user-images.githubusercontent.com/940007/89981447-be6f7700-dc28-11ea-90ba-bfd35bc8c0c3.png)

**Comment by tvanessa** [comment]
Si se está guardando bien en la base de datos. Pero a la hora de abrir otra vez el tab no se carga desde la DB la opción selecionada.
