### ISSUE TITLE
[FEATURE] Permitir agregar múltiples usuarios separados por líneas en Cursos

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#4504]
Me gustaría poder pegar mi lista de usuarios en el campo agrega Múltiples usuarios sin tener que separarlos por comas. Por ejemplo, si tengo mi lista de usuarios en una hoja de cálculo.

**Comment by dulcehc** [comment]
Hola, me gustaría trabajar en este issue

**Comment by lhchavez** [comment]
listo, ya te lo "asignamos"!
