### ISSUE TITLE
[BUG] El idioma del usuario no se establece correctamente en cuentas nuevas

### ISSUE THREAD

**Issue by anscharivs** [omegaup/omegaup#4505]
## Comportamiento Esperado

*El idioma del usuario se debería establecer para todo el sitio al momento de crear una cuenta nueva.*

## Comportamiento Actual

*A pesar de que las cuentas nuevas se crean en Inglés, en el perfil de editar usuario está autoseleccionada la opción de Español. Sin embargo, la configuración no se puede guardar a menos que se seleccione algún lenguaje de programación de preferencia, en combo de más abajo.*

## Posible Solución

*Al parecer algo relacionado con los lenguajes de programación de preferencia está interfiriendo.*

## Pasos para reproducir (para bugs)

1. Crear una cuenta de usuario nueva.
2. Dirigirse a Mi perfil > Editar perfil.
3. Escribir un nombre (es obligatorio) y seleccionar un idioma, o dejar el que está seleccionado por defecto (Español).
4. Dar clic en Guardar cambios.

El mensaje de error que se genera en la consola es:
`Failed to query MySQL (1265): Data truncated for column 'preferred_language' at row 1`

Sólo se pueden guardar cambios si se selecciona algún lenguaje de programación preferido en el combo de más abajo.

## Contexto

*Al parecer el problema tiene relación con #4486, pues a menos que se guarde el idioma manualmente desde la opción de editar perfil, el problema de dicho issue aparece*

## Tu ambiente

*Se hicieron pruebas en el ambiente virtual y en sandbox. El problema aparece en ambos casos.*

**Comment by pabo99** [comment]
Esto ya no está sucediendo
