### ISSUE TITLE
Filtrar envíos localmente cuando se usen websockets

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#453]
* Hasta ahorita, el concurso _más_ popular ever tuvo ~1650 envíos, y solo 5 superan 1000 envíos.
* Idealmente, en vez de estar polleando al backend, la mayoría de los clientes (los que están con navegadores semi-recientes) van a poderse conectar por websocket y recibirán todos los updates en tiempo real, evitando para siempre la ráfaga de F5 para ver qué pasó con algo. Los filtros en server-side son, lamentablemente, incompatibles con los streams (bueno... exagero. no son incompatibles, pero necesitaríamos meterle muchísima infraestructura: indices, muchos más mecanismos de replicación etc. etc. etc.)
* Hay librerías que lo hacen fácil y bonito :P

**Comment by pacharrin** [comment]
༼ つ ◕_◕ ༽つ pls omegaup gif filters ༼ つ ◕_◕ ༽つ

**Comment by joemmanuel** [comment]
@lhchavez qu'e librer'ias lo hacen f'acil y bonito?

**Comment by lhchavez** [comment]
ya ni me acuerdo, eso fue hace tres años :P
