### ISSUE TITLE
[BUG] Al querer editar un problema que ya existe, muestra error 400

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#4538]
## Comportamiento Esperado

Poder editar un problema que ya existe.

## Comportamiento Actual

Muestra pantalla de error 400.

## Pasos para reproducir (para bugs)

1. https://omegaup.com/problem/Lomas-de-Guanajuato/edit/
2. https://omegaup.com/problem/pes-consola-marciana/edit/

## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
No podemos subir/corregir problemas para el PES.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome version 84.0.4147.125 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2 (19C57)
* Link al sitio en el que este problema pasa: https://omegaup.com/problem/Lomas-de-Guanajuato/edit/
* Captura de pantalla:

![image](https://user-images.githubusercontent.com/5167417/90851249-bce53380-e339-11ea-8523-4b0cf7d67b1e.png)

**Comment by lhchavez** [comment]
ya no hemos visto este problema recientemente.
