### ISSUE TITLE
[BUG]Error en edición de perfil

### ISSUE THREAD

**Issue by rubmary** [omegaup/omegaup#4547]
## Comportamiento Esperado

Estoy intentando actualizar mi [perfil](https://omegaup.com/profile/rubmary/), en particular quiero actualizar mi nombre de "rubmary" a "Rubmary Rojas"

## Comportamiento Actual

Aparece una barra de error cada vez que entro en la sección de edición de perfil y cada vez que intento guardar los cambios. No se observa ningún cambio en el perfil.
Acorde a https://github.com/omegaup/omegaup/issues/4520#issuecomment-678696665 al actualizar todo el perfil se soluciona el problema, pero en mi caso sigue sin actualizarse el perfil.

## Pasos para reproducir (para bugs)

1. Estado actual de mi perfil.
![parte1issue](https://user-images.githubusercontent.com/13296248/90989834-710cd700-e551-11ea-8c52-b2d3c5722d0c.png)

2. Entro a la sección de edición y se muestra un mensaje de error
![Screenshot from 2020-08-23 17-23-31](https://user-images.githubusercontent.com/12685130/90989477-0024e980-e568-11ea-8b5a-94f4fd8cbeb2.png)

3.  Completo todos los datos que me permite cambiar (incluyendo el lenguaje de preferencia) e intento guardar los cambios:
![Screenshot from 2020-08-23 17-23-52](https://user-images.githubusercontent.com/12685130/90989494-264a8980-e568-11ea-82f6-cab3e79a5c63.png)

4. No se muestra ningún cambio en el pefil cuando entro otra vez
![parte2issue](https://user-images.githubusercontent.com/13296248/90989844-7c600280-e551-11ea-80b3-8dbf0054a921.png)

## Video reproduciendo el bug
https://youtu.be/5UCN_3v_2hY

## Tu ambiente

* Nombre del navegador: Chrome
* Sistema Operativo y versión: Ubuntu 20.04.1 LTS

**Comment by elsantodel90** [comment]
¡Atención! ¡Este problema es muy relevante para la CIIC 2020!

**Comment by pabo99** [comment]
Hola @rubmary, estoy revisando el bug que mencionas, pero no logro reproducirlo. ¿Puedes intentar ingresar nuevamente a la vista de Editar perfil? Pero ahora si puedes mostrarnos que te aparece en la consola de [DevTools](https://developers.google.com/web/tools/chrome-devtools)

**Comment by rubmary** [comment]
Hola @pabo99, este es el error que aparece en la consola
```
ui.ts:125 ReferenceError: UI is not defined
    at basicedit.js:40
    at l.notify (omegaup.ts:51)
    at e.OmegaUp._notify (omegaup.ts:620)
    at omegaup.ts:612
v @ ui.ts:125
Promise.catch (async)
_initialize @ omegaup.ts:615
_onDocumentReady @ omegaup.ts:591
675 @ omegaup.js:24
n @ bootstrap:79
487 @ omegaup.js?ver=4e9634:1
n @ bootstrap:79
t @ bootstrap:45
a @ bootstrap:32
(anonymous) @ omegaup.js?ver=4e9634:1
(anonymous) @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:1
```
![Screenshot from 2020-08-24 15-53-35](https://user-images.githubusercontent.com/12685130/91089920-42126600-e622-11ea-8049-55155abd2a06.png)
