### ISSUE TITLE
[FEATURE] Añadir información acerca de feature de cursos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4561]
Aún está por confirmarse el texto que irá en "Breve descripción de curso...". Al dar clic en "Leer más" se redirigirá  a una entrada del blog también por confirmar.

![image](https://user-images.githubusercontent.com/597815/91281363-d40e9180-e73c-11ea-9a63-3b605faa028e.png)

**Comment by heduenas** [comment]
@BlueBlockGrape puedes empezar a trabajar en este issue por favor? El texto y la liga están por confirmarse, pero ya puedes empezar a trabajar en el componente.

**Comment by tvanessa** [comment]
@BlueBlockGrape 
Descripción:
Los cursos en omegaUp son para
	- Profesores que desean crear cursos en línea
	- Alumnos que participan en los cursos de sus clases
	- Cualquier usuario que desea aprender más sobre programación participando en los cursos públicos
Link:
https://blog.omegaup.com/cursos-en-omegaup/
