### ISSUE TITLE
[FEATURE] Creación de Componente en Vue para cada colección de problemas.

### ISSUE THREAD

**Issue by BlueBlockGrape** [omegaup/omegaup#4577]
Creación de un componente en Vue para cada colección de problemas que se muestra en el mock

![mok](https://user-images.githubusercontent.com/43051192/91739293-57821580-eb77-11ea-97f4-e7d49f4c6d12.png)

Se espera que cada componente tenga:

- El nombre de la categoría.
- El numero de problemas que contiene.
- Un botón (action button)  que dice "Iniciar" si no hay problemas resueltos o dice "Continuar" si hay por lo menos un problema resuelto.
- Un borde "Negro" si no hay problemas resueltos o "Azul" si hay por lo menos un problema resuelto.
- Un icono relacionado con la categoría como se muestra en el mock.

![mock2](https://user-images.githubusercontent.com/43051192/91740576-1c80e180-eb79-11ea-8546-bdc03b733701.png)

## Contexto

Es parte de la creación de una nueva página para las Colecciones de Problemas

**Comment by tvanessa** [comment]
@lhchavez 
Tenemos dos tipos de componentes, uno con contenido estático y el otro no.
Para resolver este issue, qué nos recomiendas:
 1. Hacer componentes de vue para cada tipo
 2. Hacer un API que regrese la información estática y se use un solo componente

**Comment by lhchavez** [comment]
se vale opción C? onda:

* hacer un componente común que tanto los componentes estáticos como dinámicos "extienden" con [slots](https://vuejs.org/v2/guide/components-slots.html). según yo el único slot necesario sería el de mostrar el número de problemas que existen en tal o cual colección, entonces _posiblemente_ exista la posibilidad de hacer un único componente.
* hacer que el `getXxxForSmarty()` regrese la información dinámica para poder rendererar los componentes dinámicos y estáticos (autores, problema aleatorio, buscador de problemas). así no sería necesario hacer un API para esta vista en particular.

**Comment by BlueBlockGrape** [comment]
> se vale opción C? onda:
> 
> * hacer un componente común que tanto los componentes estáticos como dinámicos "extienden" con [slots](https://vuejs.org/v2/guide/components-slots.html). según yo el único slot necesario sería el de mostrar el número de problemas que existen en tal o cual colección, entonces _posiblemente_ exista la posibilidad de hacer un único componente.
> * hacer que el `getXxxForSmarty()` regrese la información dinámica para poder rendererar los componentes dinámicos y estáticos (autores, problema aleatorio, buscador de problemas). así no sería necesario hacer un API para esta vista en particular.

Hay algún ejemplo en el que me pueda basar para esta parte? no le entiendo muy bien a la parte de regresar información dinámica.

**Comment by tvanessa** [comment]
Se refiere a que en esta función: 
https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/Problem.php#L4829

Le agregues al campo `payload` una entrada más, por ejemplo:
`'otherCollections' => [collectionAuthors, collectionRandomProblem, collectionSearchProblem]`

donde los elementos `collectionXxX...` son cadenas localizadas.

Y así ya es más sencillo reutilizar el componente.
