### ISSUE TITLE
[BUG] La barra de progreso de estudiantes no respeta el valor que se asigno al problema

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4614]
De #4605:
"El porcentaje que se muestra no corresponde con la calificación. En este ejemplo, el problema 1 vale el 10% de la calificación y sin embargo se marca 25%. Cuando se hace el "hover" sobre los diferentes cuadritos sí se marca el porcentaje de cada problema. Un comportamiento esperado es mostrar ya sea (a) ¿qué porcentaje de la calificación de la tarea se ha obtenido? o, mejor aún, (b) ¿qué calificación total de la tarea lleva el alumno? [o, claro, las dos cosas]"

Contexto: Recientemente se agregó la funcionalidad de asignar el valor del problema en una tarea. Parece que no se está tomando en cuenta en la barra de progreso

**Comment by pabo99** [comment]
Esto se corrige con el cambio de #4633
