### ISSUE TITLE
Test Cases Públicos

### ISSUE THREAD

**Issue by MauDieguez** [omegaup/omegaup#4619]
Debido a la falta de editoriales y/o soluciones en los problemas de OmegaUp, estaría genial que en **problemas de práctica** se pudieran ver los test cases para poder debuggear. 

Muchas veces uno no se puede dar cuenta de sus errores (sobretodo cuando se está practicando) y esta sería una manera práctica para poder solucionarlos y aprender. 

Por ejemplo, si obtuve AC en 5 casos, pero en el 6to obtuve WA, sería bueno que me mostrara el caso donde obtuve WA.
Claro está, será opción del usuario si decide ver los casos o no.

**Comment by lhchavez** [comment]
Esto ya está soportado! :D no hay muchos problemas de práctica, pero en los que ya están marcados como tales, esto ya está disponible.

Pronto habrá un blogpost al respecto en https://blog.omegaup.com/?p=1387

**Comment by MauDieguez** [comment]
Muchas gracias! Entonces estaría genial que se pudiera hacer con todos los problemas de la plataforma, a excepción de los concursos/escuelas, etc. Ya que generalmente, con esos practicamos:)

**Comment by lhchavez** [comment]
eso está más complicado porque la inmensa mayoría de los problemas están en un concurso o curso de escuela. es necesario que el autor lo marque como problema educativo / de práctica explícitamente porque no podemos adivinar cuál cae en qué categoría.

**Comment by MauDieguez** [comment]
Pero generalmente son concursos pasados. Una solución es que una vez que se acabe el concurso ya se puedan ver los test cases para los problemas. Y si se vuelve a reusar el problema dentro de otro concurso, solo que no se puedan ver dentro de él.

**Comment by lhchavez** [comment]
no es tan fácil: mucha gente se quejaría si súbitamente un problema que subió se cambia de configuración (digamos, porque planeaba usarlo en otro concurso / curso).

queremos buscar maneras de incentivar a que esto ocurra, pero no podemos unilateralmente hacer cambios de este estilo.

**Comment by MauDieguez** [comment]
Vale, muchas gracias:)
