### ISSUE TITLE
[BUG] Códigos con MLE, RTE, o LTE aparantemente dan 100

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#4636]
Cuando subes un problema y recibes un error, a veces marca 100 puntos con ese error, para luego cambiar al puntaje correcto cuando se actualiza la página.

![119085133_321316915593374_4663330933840664080_n](https://user-images.githubusercontent.com/123875/92670197-5912b280-f2c8-11ea-9b86-7e2d2a361cd1.png)
![bc45814b-3cb6-46de-8bc8-6bf02d2797b8](https://user-images.githubusercontent.com/123875/92670199-59ab4900-f2c8-11ea-8b8a-fc2b6846ed04.png)
![6d551925-d264-4700-ae7a-892e800ac8c0](https://user-images.githubusercontent.com/123875/92670200-5a43df80-f2c8-11ea-8448-937fc783c195.png)

**Comment by lhchavez** [comment]
dupe de https://github.com/omegaup/omegaup/issues/4632
