### ISSUE TITLE
[BUG] No s epuede cambiar el tiempo de validador al editar un problema

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#4640]
## Comportamiento Esperado

Estaba intentando editar el porblema https://omegaup.com/problem/OMI-2017-Escalones/edit/

- puse "1000" en Tiempo límite para el validador (ms) 
- puse  "alguna descripción" en la descripción del cambio
- le di en click a actualizar problemas

esperaba que actualizara el límite

## Comportamiento Actual

no marca error al guardar pero no actualiza el valor,
incluso guarda el registro de una nueva version pero sin cambios

**Comment by darkmx** [comment]
dupe de #4227
