### ISSUE TITLE
[BUG] Scoreboard siempre leakea información sobre los envíos realizados

### ISSUE THREAD

**Issue by elsantodel90** [omegaup/omegaup#4641]
## Comportamiento Esperado

Poder hacer concursos sin scoreboard, de modo que nadie tenga ninguna información sobre lo que envían los demás participantes (Sistema IOI)

## Comportamiento Actual

Por más que se ponga en "0%" el tiempo de prueba con scoreboard, igualmente los concursantes pueden obtener cierta información al ir a la sección de “Rankings”. Si bien los puntajes no salen, sí salen la cantidad de envíos. Esto puede interpretarse como una medida de complejidad.

## Contexto

Esto afectó al concurso oficial CIIC 2020

**Comment by pabo99** [comment]
Estoy revisando que, efectivamente, al ingresar a la sección de Ranking dentro de un concurso se muestran el número de envíos que ha realizado cada uno de los participantes por problema. 

La duda que me surgió es la siguiente: 

A. ¿Es un bug el mostrar esa información? o
B. ¿Es un escenario que no tenemos contemplado dentro de la configuración de los concursos? 

En caso de ser la opción A, es cuestión de dejar de mostrar esa información en el ranking (o en su defecto, dejar de mostrar la tabla completa).
En el caso de B, habrá que agregar un campo nuevo en el formulario que indique que no se debe mostrar el scoreboard en ningún lugar del concurso.

Mi duda surge debido a que actualmente en el campo de "¿Cuánto tiempo se mostrará el Scoreboard? (%)", sólo se considera dejar de actualizar los puntos.
