### ISSUE TITLE
[FEATURE] Como problemsetter, quiero usar el mismo caso de prueba en múltiples subtareas (grupos de casos)

### ISSUE THREAD

**Issue by elsantodel90** [omegaup/omegaup#4642]
Al crear casos agrupados para un problema, quiero que sea posible compartir un mismo caso de prueba en varios grupos de casos. Por ejemplo, el sistema CMS utilizado en IOI permite especificar las subtareas (grupos de casos) mediante regexes que se aplican a los nombres de los casos, y de esa forma es posible tomar el mismo caso en varias subtareas.

El ejemplo más común y totalmente natural ocurre cuando una subtarea está incluida en otro, por ejemplo porque una garantiza N hasta 100, y otra garantiza N hasta 1000. No tiene sentido que un programa pase la segunda pero falle la primera, pero hoy esto ocurre en varios problemas en omegaup. La única forma de evitarlo como problemsetter sería incluir todos los casos de la primera subtarea en la segunda. Esto es muy incómodo, y no escala a medida que hay más cantidad de subtareas. También aumenta notoriamente todos los tiempos de ejecución innecesariamente, al ejecutarse exactamente el mismo caso varias veces solamente para que sea tenido en cuenta en varios grupos. 

Si se pudiera especificar por ejemplo con regex, se tendrían casos S01.E1 S01.E2 etc para la primera subtarea y S02.E1 S02.E2 etc para la segunda, de modo que la primera subtarea se especifica como "S01.E." pero la segunda como "S0[12].E.".

Esta situación exacta se pone de manifiesto en todos los concursos con un formato similar IOI, como lo es la CIIC.

**Comment by tvanessa** [comment]
ping de requerimientos @lhchavez por favor

**Comment by kishtarn555** [comment]
También ayudaria a reducir el tamaño de los zip, que a veces llegan a tamaños problematicamente grandes y omegaup o el internet no deja subirlos

**Comment by elsantodel90** [comment]
Esto todavía no lo tenemos para esta CIIC, verdad?

**Comment by tvanessa** [comment]
No ): estará listo en ~2 semanas.

**Comment by elsantodel90** [comment]
¿Esto se completó? ¿Se podrá usar para la OII 2023 de julio?

**Comment by tvanessa** [comment]
Ya se puede usar, solo se están arreglando errores de scoreboard.

**Comment by tvanessa** [comment]
> ¿Esto se completó? ¿Se podrá usar para la OII 2023 de julio?

Ya se puede usar, se están resolviendo bugs del scoreboard. Es muy seguro que estén resueltos para julio
