### ISSUE TITLE
[FEATURE] Poder editar la versión de un problema en la tarea de un curso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4652]
Hola amigos de omegaUp.

En contraste con los concursos, los cursos no me dejan cambiar la versión de un problema puesto como tarea. Sólo me deja moverlo, borrarlo y subir más problemas.

![imagen](https://user-images.githubusercontent.com/19719969/93006583-9aeb6500-f523-11ea-9bfe-68692b214dab.png)

Esto es un _gran_ problema si se detecta que hubo algún error o inconveniente en la especificación inicial del problema.

**Comment by carlosabcs** [comment]
Hola @darkmx, no consigo reproducir el problema. O sea, al agregar un nuevo problema, puedes escoger la versión que deseas. Pero de ahí, hasta donde he visto, ni en concursos es posible modificar la versión del problema que agregaste. A no ser que no esté reproduciendo el problema como debe de ser...

**Comment by darkmx** [comment]
En los concursos sí se puede:

![image](https://user-images.githubusercontent.com/19719969/108860680-0c8c0c80-75b4-11eb-8d3f-b2e4308eb889.png)

**Comment by darkmx** [comment]
Espera, a no ser de que sólo te deje agregar problema pero no modificarlo D: espera deja ver.

**Comment by darkmx** [comment]
Ya vi. En la pantalla que puse en mi mensaje anterior, puedes elegir un problema que ya tengas agregado. El botón "Agregar problema" se deshabilita porque no se vale agregar dos veces el mismo problema, pero sí sigue funcionando la parte de elegir versión. Al elegir la versión y darle actualizar, se actualiza el problema que ya estaba agregado.

**Comment by darkmx** [comment]
Me acabo de dar cuenta de que exactamente lo mismo sirve en cursos D: creo que entonces no es un FR, sino que el issue es un problema de usabilidad (necesitas medio adivinarle al uso de la interfaz para lograr hacer lo que quieres). Pensaré en ponerlo como issue aparte, pero por ahora cierro éste.
