### ISSUE TITLE
[FEATURE] En las lecturas de un curso, colorear la sintaxis de los fragmentos de código

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4657]
Hola amigos de omegaUp.

En las lecturas de un curso, los fragmentos de código usan el mismo estilo que los casos de ejemplo de un problema (una cajita con letra negra y fondo gris):

![imagen](https://user-images.githubusercontent.com/19719969/93008585-ff1a2300-f53b-11ea-8c26-603712a3f24f.png)

La característica en cuestión sí está disponible en el editor de código al momento de hacer un envío, pero no en las lecturas. Como se espera que las lecturas se usen por muchos alumnos (y más en tiempos de pandemia) sería bueno agregarla.

**Comment by lhchavez** [comment]
_posiblemente_ haya necesidad de agregarle el lenguaje así como aquí en github. onda

    ```cpp
    #include<...>
    ...
    ```

pero +1, es buena idea y suena no-tan-difícil de hacer.

**Comment by darkmx** [comment]
muchas gracias :)
