### ISSUE TITLE
[FEATURE] Separar por lineas información del tooltip de progress bar

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4672]
Si es dificil o imposible, hay que por lo menos separar las diferentes informaciones con " | ". Por ejemplo: "Problema: Fulanito | Puntaje: 50 de 100 puntos posibles | Progreso 50%"

<img width="632" alt="Screen Shot 2020-09-16 at 2 53 36 PM" src="https://user-images.githubusercontent.com/597815/93396435-83b2bd00-f82c-11ea-8fec-20ba761fb61a.png">

**Comment by pabo99** [comment]
Esto se resolvió en el PR #4821:

![image](https://user-images.githubusercontent.com/3230352/96503059-5042c400-1218-11eb-9c89-c6cb644c16f1.png)

Ya se puede cerrar.
