### ISSUE TITLE
[BUG] El order de los problemas no se copia al clonar un curso

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#4681]
## Comportamiento Esperado

Al clonar un curso, la estructura del nuevo curso es idéntica a la del curso original.

## Comportamiento Actual

Los problemas se copian en desorden.

## Posible Solución

Cambiar esta línea:
https://github.com/omegaup/omegaup/blob/15e198d5e042bb69685164001a449d5b4b53ba73/frontend/server/src/Controllers/Course.php#L711

por algo como `$problem['order'] ?? 1`

## Pasos para reproducir (para bugs)

1. Crear un curso con una tarea con múltiple problemas y asignarles un orden.
2. Clonar el curso.
3. Observar el orden de los problemas en el nuevo curso.

## Contexto

Para el programa de UEMSTIS se creó un curso "maestro" del cual se clonaron cursos para presentar y demostrar las capacidades de cursos. Pero al persentar, resultó que el orden de los problemas no era el esperado.

**Comment by lhchavez** [comment]
Faltan las pruebas.
