### ISSUE TITLE
[FEATURE] Autogenerar alias en UI de clonar curso

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4685]
La UI de clonar curso debe de tener por default un alias que sea distinto al alias del curso original. Esto aplica para ambas UIs de clonar:
1. La de clonar un curso propio: `https://omegaup.com/course/<ALIAS>/edit/#clone`
2. La de clonar curso por URL: `https://omegaup.com/course/capacitacion-ejemplo/clone/<TOKEN>/`

Una opción es poner `<alias_original>_copia` para 1. y `<alias_original>_username` para el segundo.

**Comment by lhchavez** [comment]
me gusta la idea de `<alias_original>_username`, pero `<alias_original>_copia` _preferiría_ no dar un default porque la gente va a dejar ese default y vamos a terminar con `copia1`, `copia2`, etc.

**Comment by heduenas** [comment]
De acuerdo, vamos a hacer solo el de `<alias_original>_username`.
