### ISSUE TITLE
[BUG] Algunos tags se pintan amarillo cuando no deberían

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4695]
Algunos tags se pintan amarillo cuando no deberían al filtrar por una etiqueta, por ejemplo: https://omegaup.com/problem/?tag[]=problemTagMatrices

![image](https://user-images.githubusercontent.com/597815/93627712-318faa00-f99a-11ea-9b1d-9c7837e1573d.png)

**Comment by tvanessa** [comment]
@BlueBlockGrape puedes revisar si este issue ya no se reproduce con el cambio que hiciste en #4869?

**Comment by BlueBlockGrape** [comment]
> @BlueBlockGrape puedes revisar si este issue ya no se reproduce con el cambio que hiciste en #4869?

Intenté replicar el error en local y no me sale, aunque creo que no tengo suficientes problemas para probarlo bien.

Algo que vi en la página ya en la web, es que los problemas que se pintan de amarillo varias etiquetas omiten una clase `custom-badge-owner` o `custom-badge-vote` y directamente ponen `custom-badge-quality` por lo que no creo que el cambio en 4869 lo arregle, pero no estoy seguro. 

Sería de ver si están mandando en `tag.source` directamente la palabra `quality`, pero si no estoy muy seguro de que lo arregle el otro cambio.
