### ISSUE TITLE
[FEATURE] Liga de editar contenido debe de permitir editar problemas.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4696]
Al dar clic en "Editar" en la tabla de contenidos:
![image](https://user-images.githubusercontent.com/597815/93629338-fa6ec800-f99c-11ea-8021-a16ca648e56f.png)

Se debe de mandar al usuario a `https://omegaup.com/course/<ALIAS>/edit/#content` con la tarea seleccionada precargada:
![image](https://user-images.githubusercontent.com/597815/93629670-82ed6880-f99d-11ea-85eb-5ee0414209ee.png)

**Comment by tvanessa** [comment]
Duplicado con #4725
