### ISSUE TITLE
[FEATURE] Tabla de progreso de estudiantes tiene demasiado texto repetido

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4698]
![image](https://user-images.githubusercontent.com/597815/93631217-0dcf6280-f9a0-11ea-890b-67553fdf492f.png)

Hay que poner en el titulo de la columna el número de puntos posibles, e.g. "3. Práctica de Notación Asintótica (500 puntos)". Y en las celdas del interior de la tabla poner solamente el progreso como porcentaje, o sea simplemente "XX%".

**Comment by darkmx** [comment]
Había puesto esto en un issue separado y luego vi éste :( pongo lo que puse allá.
---

Hola amigos de omegaUp.

Basado en las sugerencias de Francisco Zaragoza, van los siguientes comentarios:
1) Los tooltips que aparecen en los cuadritos de los problemas de una tarea son muy largos y también se pueden mejorar:
![imagen](https://user-images.githubusercontent.com/19719969/93714795-9d088180-fb2a-11ea-9140-c43196caaed2.png)
La mejora: Poner el nombre del problema en lugar del alias.
La simplificación que propongo: 
![imagen](https://user-images.githubusercontent.com/19719969/93715091-ab579d00-fb2c-11ea-98f2-6d9f9743c1b4.png)
Francisco sugiere siempre poner el porcentaje redondeado al entero más cercano. De hecho, Francisco propone algo aún más corto que lo que estoy mostrando en la imagen: "alias: p1/p2, p3%" pero siento que ése sí queda demasiado corto. 

2) Del mismo modo, el texto que se despliega en cada tarea es muy largo y repetitivo. La página se ve muy densa en texto, a pesar de proporcionar realmente poca información. 
![imagen](https://user-images.githubusercontent.com/19719969/93715059-76e3e100-fb2c-11ea-982e-d7c196e7384c.png)

Una vez simplificado el tooltip, se podría usar una frase del mismo estilo para esta parte.

**Comment by heduenas** [comment]
Vamos poniendo "Introduccion a omegaUp: 10 de 10 puntos, 100% de progreso" en el tooltip como propone Rodrigo. Redondeando el porcentaje al entero mas cercano. Y en la celda hay que poner "200 de 300 puntos, 67% de progreso".

**Comment by pabo99** [comment]
Creo que sigue siendo mucho texto de texto en la celda y seguimos teniendo el problema que reporta Francisco Zaragoza, por medio de @darkmx de tener texto repetitivo y que no aporta demasiado:
![image](https://user-images.githubusercontent.com/3230352/96157414-e3f25880-0ed7-11eb-9627-da14c53e7b50.png)


Al contrario de como se había propuesto originalmente, de sólo colocar el progreso:
![image](https://user-images.githubusercontent.com/3230352/96157554-0edcac80-0ed8-11eb-86ae-cefbb476c8af.png)


Esta última opción me parece la más adecuada, pero quedo en espera de sus comentarios.

**Comment by darkmx** [comment]
En efecto, el cuerpo de la página aún se siente pesado en cuanto a texto repetitivo, incluso después de la simplificación. La propuesta de Juan Pablo se ve bastante bien, aunque tal vez le agregaría    X% (Y pts)    porque no todas las tareas tienen el mismo puntaje.

El tooltip sí lo dejaría como Hugo comenta.
