### ISSUE TITLE
Quitar todas las librerías externas e importarlas como submódulos de git

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#470]
Si algo necesita un parchezuco (como log4php), se puede hacer un fork, pero quiero que esté el menos código posible en nuestro repo principal (por cosas de licencias y así)

**Comment by lhchavez** [comment]
smarty ya usa git! https://github.com/smarty-php/smarty

**Comment by elendil326** [comment]
@lhchavez este es un ongoing effort? quieres abrir un feature por librería e ir cerrando de uno en uno en cuanto sea posible?

**Comment by lhchavez** [comment]
no, ya se hizo lo que valía la pena que se hiciera.
