### ISSUE TITLE
[BUG] No aparecen listados todos los cursos que el usuario administra

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4721]
Hola amigos de omegaUp.

Francisco Zaragoza me reporta el siguiente bug. Él ahorita está impartiendo un curso propio y uno de sus colegas le acaba de dar derechos de administrador en el suyo. Sin embargo, me comenta que en https://omegaup.com/course/mine/ sólo le aparece el suyo:

![imagen](https://user-images.githubusercontent.com/19719969/94344163-f406ce80-ffe2-11ea-9c4b-7ea418d62a1c.png)

mientras que si usa el URL directo al otro curso, sí puede entrar:

![imagen](https://user-images.githubusercontent.com/19719969/94344173-06810800-ffe3-11ea-9b90-0888d164c1d4.png)

**Comment by tvanessa** [comment]
No podemos reproducirlo ): 
Sabes si hay otros cursos que tenga como admin invitado?

**Comment by darkmx** [comment]
dont know :( le preguntaré

**Comment by darkmx** [comment]
no me han respondido :\ y tampoco tengo forma de reproducirlo yo
si me dicen algo, lo reabro
