### ISSUE TITLE
[FEATURE] Alinear consistentemente el contenido de un curso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4722]
Hola amigos de omegaUp.

Francisco Zaragoza me reporta lo siguiente. Resulta que la alineación de los botoncitos de administración de las tareas de un curso tienen una alineación visiblemente inconsistente, dependiendo si los alumos ya han hecho envíos o no.

![imagen](https://user-images.githubusercontent.com/19719969/94344319-0b928700-ffe4-11ea-9312-70967678f38f.png)

**Comment by yesidays** [comment]
Hola, ¿puedo trabajar este ticket? saludos
