### ISSUE TITLE
[FEATURE] Como un creador de problemas, quiero embed a código para no tener que pegarlo a mano

### ISSUE THREAD

**Issue by Juanito98** [omegaup/omegaup#4739]
## Comportamiento Esperado

si hago {{plantilla.py}} lo transforme a código pegado en el markdown

## Comportamiento Actual

NO existe esa funcionalidad ahora.

**Comment by lhchavez** [comment]
El acuerdo al que llegamos es que si se encuentra un párrafo que contenga

    {{nombredearchivo.extension}}

Esto se va a interpretar como si fuera:

    ```extension
    los contenidos de `nombredearchivo.extension`
    ```

y eso se va a reescribir a

    <pre><code class="language-extension">los contenidos de `nombredearchivo.extension`</code></pre>

como el requisito es que `{{nombredearchivo.extension}}` esté en un párrafo, sólo va a funcionar si está rodeado de líneas vacías por sí sólo. Esta sintaxis se tomó prestada de http://fletcher.github.io/MultiMarkdown-4/transclusion, con la diferencia de que el proceso aquí no va a ser recursivo y sólo se va a usar para incluir snippets de código.

**Comment by lhchavez** [comment]
Esto quizás le interese a @darkmx !

**Comment by darkmx** [comment]
> 
> 
> Esto quizás le interese a @darkmx !

omg ! :)
