### ISSUE TITLE
[BUG] El botón de bajar zip con los .in en un problema de solo-salida da 404

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#4741]
## Comportamiento Esperado

En mi problema de sólo salida, puedo bajar el zip con los .in al hacer click en el botón.

## Comportamiento Actual

Recibo un 404.

## Pasos para reproducir (para bugs)

1. Abrir el problema https://omegaup.com/arena/problem/OMI-2020-Practica-Fichas (es privado: puedo dar acceso a quien requiera)
2. Hacer click en el botón al final de la redacción.

## Contexto

Este problema (y estilo de problema) va a usarse en la OMI de práctica el fin de semana, así como en la OMI la siguiente semana.

**Comment by lhchavez** [comment]
Faltaba crear el directorio donde se guardan estos .zip. Ya funciona.
