### ISSUE TITLE
[BUG] No se están agregando miembros a un grupo.

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#4789]
## Comportamiento Esperado

Al subir un csv y guardar identidades con mensaje exitoso, poder ver los miembros.

## Comportamiento Actual

Subí un csv, guardé las identidades, miembros aparece vacío.

## Pasos para reproducir (para bugs)

1. https://omegaup.com/group/OMIS-2020/edit/#identities
2. Subir un csv
3. Dar clic a Guardar identidades
4. Ir a members

## Contexto

Usuarios omis

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 85.0.4183.121 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.6 (19G2021)

respuesta de `bulkCreate/` 
```
{"status":"ok","_id":"5f7d29a546822056103273"}
```

![image](https://user-images.githubusercontent.com/5167417/95281086-fe636c80-081b-11eb-894f-b42b114c341e.png)

respuesta de `members/`
```
{"identities":[],"status":"ok","_id":"5f7d29dc67c79228070491"}
```
![image](https://user-images.githubusercontent.com/5167417/95281097-04f1e400-081c-11eb-8f25-b72ec7ad66cb.png)

**Comment by andreasantillana** [comment]
subí el archivo a este grupo y sin broncas.

https://omegaup.com/group/OMISS-2020/edit/#members

**Comment by lhchavez** [comment]
no es un error meramente cosmético, porque no se están guardando en la base de datos ni siquiera!
