### ISSUE TITLE
[FEATURE] Como autor, me gustaría que fuera opcional desplegar todos mis problemas en lugar del paginado

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#4792]
Agregar una opción para mostrar todos los problemas

Como autor, me gustaría que fuera opcional desplegar todos mis problemas en lugar del paginado, ya que se vuelve complicado buscar problemas por paginado debido a la estandarización de los tags,

**Comment by darkmx** [comment]
+1

Desde que se agregó el paginado a https://omegaup.com/problem/mine/ ya no podemos buscar fácilmente nuestros propios problemas por nombre, ya que pueden no estar en la primera página del resultado (y es una lata andar buscando en cada página). Yo he tenido que usar el buscador de https://omegaup.com/problem/, lo cual es triste (no porque sea triste usar el buscador, sino porque la página general de problemas resulta ser más útil que la página específica de mis problemas)

**Comment by tvanessa** [comment]
Agreguemos un buscador en la página
