### ISSUE TITLE
Drop db en vez de truncate en el bootstrap de testing

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#480]

**Comment by lhchavez** [comment]
Ya corremos pruebas en Travis donde siempre se borra la BD. Ya no es necesario.

**Comment by lhchavez** [comment]
Mejor sí hay que hacerlo, porque a los developers les sirve.

**Comment by lhchavez** [comment]
listo, los developers ya pueden darle purge cuando quieran usando `./stuff/db-migrate.py purge`.
