### ISSUE TITLE
[FEATURE] Habilitar la opción "Retroalimentación de envíos" para cursos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4826]
Hola amigos de omegaUp.

![imagen](https://user-images.githubusercontent.com/19719969/96340857-8b999300-105e-11eb-8cc4-682194161eb7.png)

La opción de "Retroalimentación de envíos" que está disponible para concursos, no está disponible para cursos. Esa opción ha resultado útil para concursos y creo que sería aún más útil tenerla en los cursos.

**Comment by gabrc52** [comment]
Incluso podría ser útil tenerlo en problemas que no están en un curso ni en un concurso.
