### ISSUE TITLE
Bajar test cases de vez en cuando

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#483]
From Mendo:

Downloading a test case in training mode – After a student submits a wrong solution
to a task, he is presented with an option of potentially downloading one of the test cases
that his solution does not correctly solve. Users are limited in the number of tests that they
can download in a certain time period. We have found this to be a very positive change in
the system and a lot of users are taking advantage of this feature to ﬁx mistakes in their
code instead of just giving up on solving a problem.

**Comment by lhchavez** [comment]
Cran. Tenemos que pensar mejor esto para el training gate.
