### ISSUE TITLE
[FEATURE] Como un desarrollador nuevo, quiero que GitHub corra el linter por mí para no tener que correrlo a mano

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#4839]
## Comportamiento Esperado

Correr el linter es algo mecánico que se tienen instrucciones para seguir, pero hay ocasiones en las que no se puede ejecutar (sobre todo en Windows si se está corriendo Docker-en-NTFS porque ese setup no soporta symlinks).

Estaría cool si GitHub corriera el linter si algo sale mal.

## Comportamiento Actual

Ahorita sólo notifica al desarrollador que hay que correr el linter.

## Contexto

Cada que alguien quiere cambiar un acento o algo trivial en las plantillas de traducción desde GitHub, no se puede hacer porque el linter se queja.

**Comment by pabo99** [comment]
Esto ya lo está haciendo GitHub, ¿cierto? Para que se pueda cerrar este issue

**Comment by lhchavez** [comment]
sí! tarda un montón, pero sí lo hace :D
