### ISSUE TITLE
[FEATURE] Mejorar el rendering de los casos de ejemplo

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4841]
Hola amigos de omegaUp.

El usuario "mheredia" (Marco Heredia, profesor de la UAM) me reporta lo siguiente.
Resulta que a veces el espacio de la columna "Entrada" de los casos de ejemplo está resultando insuficiente y se está generando un mini-scroll por el overflow. Aparentemente, esto ocurre cuando la sección de descripción es muy larga.

https://omegaup.com/arena/problem/volumenNcubos/#problems
![image](https://user-images.githubusercontent.com/19719969/96643879-d0872900-12ed-11eb-9f72-8391bf732e57.png) ![image](https://user-images.githubusercontent.com/19719969/96644116-383d7400-12ee-11eb-8af4-26a71fce9347.png)
![image](https://user-images.githubusercontent.com/19719969/96644249-61f69b00-12ee-11eb-9446-72790706dd59.png)

El problema parece empeorar cuando el problema se muestra como parte de un concurso, al grado que no se alcanza a percibir inmediatamente que parte de la entrada está oculta:

![image](https://user-images.githubusercontent.com/19719969/96644040-15ab5b00-12ee-11eb-80f4-379233e301c2.png)

Posiblemente convenga darle un min-width a las columnas de entrada y salida, así como un max-width a la de descripción, si es que existe.

**Comment by lhchavez** [comment]
aquí la solución es ponerle

```css
    overflow: visible;
    margin-right: 20px;
```

al `<pre>`.
