### ISSUE TITLE
[FEATURE] Evitar el scrolling de la tabla de envíos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4842]
Hola amigos de omegaUp.

Cuando un usuario hace un envío y su nombre de usuario es larguísimo, éste provoca que algunos botones de la lista de envíos se oculten por falta de espacio. Por ejemplo, https://omegaup.com/arena/problem/Calculos-mentales-competitivos/#runs

![image](https://user-images.githubusercontent.com/19719969/96644976-7e470780-12ef-11eb-9613-05ee937e5cc3.png)

Haciendo un scroll "a fuerza bruta" (dar click y arrastrar el mouse a la derecha) es posible deslizarnos en la interfaz. Esto debería ser innecesario. Entra las opciones disponibles para corregir este problema están word-break, text-overflow o simplemente usar más espacio hacia los lados.

**Comment by tvanessa** [comment]
@pabo99 Puedes ver cuál es la cantidad máxima de caracteres que hacen que si se vea completa la tabla? Para que implementes el word-break con ese ancho.

**Comment by lhchavez** [comment]
> @pabo99 Puedes ver cuál es la cantidad máxima de caracteres que hacen que si se vea completa la tabla? Para que implementes el word-break con ese ancho.

determinar cualquier cantidad máxima de caracteres va a resultar casi imposible: eso depende de los anchos de las otras columnas, del zoom que tenga el usuario, de la fuente en la que se esté desplegando, etc.

tal vez algo así como [`table-layout: fixed;`](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout) sería la solución permanente. con eso únicamente sería necesario establecer la proporción de los anchos de las columnas.

y tal vez sería bueno de paso mover las acciones a un botón de dropdown si se necesitan desplegar más de una (onda, mostrar el botón de detalles O un botón con el [dropdown](https://getbootstrap.com/docs/4.5/components/dropdowns/) con todas): esa columna en particular es muy ancha y así nos podríamos ahorrar mucho ancho.

**Comment by darkmx** [comment]
Haciendo pruebas, word-break: break-all de CSS funciona relativamente bien (resolución de 1600x900 con zoom de 200%)

![image](https://user-images.githubusercontent.com/19719969/97176968-562a2f00-175b-11eb-8d6a-d63c974ae5ef.png)

Tener columnas de ancho fijo no estaría nada mal, aunque posiblemente de todos modos se necesite word-break, ya que sigue existiendo el riesgo de que el contenido no quepa en el ancho asignado (ya no se empujarían las demás columnas, pero igual se tiene que resolver el despliegue de dicho contenido problemático).
