### ISSUE TITLE
[FEATURE] Cambiar el link de Problem Finder por un boton

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4852]
En https://omegaup.com/problem/ el Problem Finder se muestra como un link
![Screen Shot 2020-10-22 at 10 00 12 PM](https://user-images.githubusercontent.com/13296248/96958410-3cb28a00-14b2-11eb-81f0-3384dfe96432.png)

Cambiarlo por un botón que solo diga "Problem Finder"

![Screen Shot 2020-10-22 at 9 59 51 PM](https://user-images.githubusercontent.com/13296248/96958433-4e942d00-14b2-11eb-981c-c5e794287b96.png)

**Comment by pabo99** [comment]
Assigned to @lnetza
