### ISSUE TITLE
[FEATURE] Traducir Penalty al crear un concurso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4855]
En https://omegaup.com/contest/new cambiar las cadenas:

- Tipo de penalty -> Tipo de penalización
- Penalty -> Tiempo de penalización

**Comment by pabo99** [comment]
Assigned to @ibonkonesa

**Comment by pabo99** [comment]
Esto se corrigió en el PR #4858. Ya se puede cerrar 👍
