### ISSUE TITLE
[BUG] Cascada de envíos por problemas en la plataforma

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4864]
Hola amigos de omegaUp.

Desde hace ya varios meses, ocurre con cierta frecuencia que la plataforma se ataruga y en menos de un minuto se desataruga, permaneciendo sin problemas adicionales incluso por horas. Cuando eso ocurre, casi siempre hay algo en el log de errores con un mensaje del estilo "transacción fallida, reiniciando". Me ha pasado (pero no lo había reportado), que cuando la plataforma se ataruga al momento de hacer un envío y si decido volverle a picar el botón de enviar mientras sigue taruga, la plataforma termina recibiendo y procesando los dos envíos. Sin embargo, ahora sí les reporto el problema porque acabo de ver que pueden ocurrir cosas graves:

https://omegaup.com/arena/E3PE2020PCTG02
![image](https://user-images.githubusercontent.com/19719969/97195158-9fd14480-1770-11eb-8b63-c92fd4cbdb86.png)

**Comment by lhchavez** [comment]
Además de https://github.com/omegaup/omegaup/pull/4875, hay que bloquear el botón hasta que el servidor nos regrese la confirmación de que el envío se hizo (o no se hizo).
