### ISSUE TITLE
[FEATURE] El formulario de revisores muestra un campo extra

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4886]
Eliminar el campo de texto abajo de los radiobuttons del inicio

![Screen Shot 2020-11-02 at 2 39 08 PM](https://user-images.githubusercontent.com/13296248/97927313-9cfac480-1d19-11eb-9950-3065ca00314c.png)

Probe en firefox y chrome y en ambos se reproduce

**Comment by tvanessa** [comment]
Se arregla con la migración de arena.problem

**Comment by pabo99** [comment]
Como la migración puede llevar tiempo, se va a abrir un PR que arregle los estilos de este componente y no de la impresión de que hay un campo extra
