### ISSUE TITLE
[FEATURE] El listado de problemas de calidad filtra mal las etiquetas

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#4890]
Al dar click en una etiqueta en la nueva lista de problemas de calidad, me redirige a la antigua vista de problemas. Esto es un problema porque la antigua lista no filtra por problemas de calidad

### Posible solución
Al dar click en las etiquetas se debe filtrar en la misma lista y no redirigir a otra.

Por ejemplo, al dar click aqui:
![Screen Shot 2020-11-03 at 1 05 10 AM](https://user-images.githubusercontent.com/13296248/97966673-00fca780-1d71-11eb-862b-283884215e60.png)
 me manda a esta URL: https://omegaup.com/problem/?tag[]=problemTagConditionals

@VegaMex te bloqueria en tus avances si se lo asigno a Aarón?

**Comment by VegaMex** [comment]
@tvanessa Al parecer no
