### ISSUE TITLE
[FEATURE] Poner feed de /preguntas recientes en el index de omegaup

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#491]
TODO: @joemmanuel pondrá más detalles del behavior esperado (n. de preguntas en el feed, color, etc).

**Comment by elendil326** [comment]
Incrementar P1 por cambio de sprint

**Comment by elendil326** [comment]
Marcando como bloqueado, pues Nopal Creativa hará grooming de las preguntas existentes para asegurarse que son de alta calidad.

**Comment by pabloaguilar** [comment]
Supongo que ya no es relevante desde que cerramos `/preguntas`
