### ISSUE TITLE
[BUG] No es posible actualizar la redacción de un problema en idiomas distintos al Español

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#4953]
## Comportamiento Esperado

La intención es agregar redacciones de un problema en distintos idiomas, como
lo son español, inglés y portugués.

## Comportamiento Actual

Parece ser que sólo el lenguaje principal es el que está permitiendo actualizarse,
en este caso el español.

## Posible Solución

Esto funcionaba con anterioridad, así que la solución puede ser buscar entre versiones
pasadas en que punto se rompió.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Ingresar a la sección de _Mis problemas_.
2. Dar clic en el botón de _Editar problema_.
3. Cambiarte a la opción _Editar redacción_.
4. Seleccionar un idioma distinto al original.
5. Escribir algún texto cualquiera.
6. Dar clic en _Actualizar redacción_.

## Tu ambiente

![UpdateRedactionFailed](https://user-images.githubusercontent.com/3230352/100522652-375ef400-3170-11eb-985c-7abc9344b187.gif)

**Comment by lhchavez** [comment]
ese código ha cambiado tanto que posiblemente no sea viable buscar en qué cambio se introdujo la regresión (además porque hacer un revert NO es deseable): más bien hay que arreglarlo con el código actual. igual para el otro bug de redacciones.

y ahora habría que introducir pruebas ^^;;

**Comment by pabo99** [comment]
Estuve revisando y parece que si funciona (con un workaround): Después de agregar la imagen, si se modifica algo más en la redacción, ahora si aparece:
![UploadImageProblemWorkaround](https://user-images.githubusercontent.com/3230352/100678150-21992c80-3332-11eb-9f17-6ef0cfe81b2f.gif)

Sólo habrá que encontrar la forma de que el cambio se refleje al instante de agregar la imagen

**Comment by pabo99** [comment]
Esto ya funciona correctamente, así que se cierra por el momento
