### ISSUE TITLE
[FEATURE] En un curso, permitir restringir los lenguajes a usar

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4972]
Hola amigos de omegaUp.

Una característica muy útil de los concursos es poder restringir el conjunto de lenguajes de programación que se pueden usar. Sería útil también que esta característica esté disponible en cursos.

**Comment by tvanessa** [comment]
Poner la opción en el formulario principal de crear curso (como se hace en concursos):

![Screen Shot 2021-01-26 at 3 04 53 PM](https://user-images.githubusercontent.com/13296248/105945790-cb3b2800-601a-11eb-9ae7-bafa0ba18f29.png)

**Comment by heduenas** [comment]
@lhchavez puedes por favor prioritizar revisar este PR? está bloqueando a Carlos.

**Comment by lhchavez** [comment]
> @lhchavez puedes por favor prioritizar revisar este PR? está bloqueando a Carlos.

dónde está el PR? pueden poner una referencia a este issue en el commit description?

**Comment by heduenas** [comment]
Sorry, este es el PR https://github.com/omegaup/omegaup/pull/5050 y no tiene nada que ver con este issue.
