### ISSUE TITLE
[BUG] Los números de línea del editor se enciman con el código

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4973]
Hola amigos de omegaUp.

Los números de línea que están en el editor del modal de "Nuevo envío" se enciman con el código. Esto ocurre tanto en Chrome como en ZorroDeFuego.

![image](https://user-images.githubusercontent.com/19719969/101550455-f8514f80-3974-11eb-8962-826640c98ed4.png)

Pocas personas editan su código directamente ahí, pero al pegar el código y darle click a enviar, siempre queda la duda de si el código escrito se corrompió de alguna forma o si todo está bien.

**Comment by darkmx** [comment]
Una cosa que noté hoy: el error ocurre a veces. Parece que con códigos cortos es más probable que ocurra:

![image](https://user-images.githubusercontent.com/19719969/101969236-e972d300-3be8-11eb-9193-6474de9d0b43.png)

y si le empiezo a dar saltos de línea:

![image](https://user-images.githubusercontent.com/19719969/101969248-fbed0c80-3be8-11eb-8606-044b5eaf7aea.png)

**Comment by pabo99** [comment]
Si, al parecer sólo sucede cuando has escrito menos de 10 líneas, una vez que llegas a esa cantidad no importa que borres el código, ya siempre se muestra correctamente.

Actualmente estamos trabajando en la migración de ese componente en donde ya no se enciman los textos, pero va a tardar un poquito en aplicarse para concursos y cursos, primero empezaremos con la vista de problemas individuales

**Comment by darkmx** [comment]
Creo que algo lo arregló (posiblemente la migración que comentaba Juan Pablo) y no he visto que vuelva a ocurrir, así que lo cierro.

**Comment by Apocryphon-X** [comment]
Estuve probando, y el problema sigue ocurriendo bajo las condiciones que menciona @pabo99. Cuando el código tiene < 9 lineas se sigue presentando este error. Se podria volver a abrir este issue?

![issue-omega](https://user-images.githubusercontent.com/40130428/113789916-bc9d7b00-9705-11eb-9a51-31c10932d171.gif)

**Nota:** Este issue ya no ocurre con problemas individuales, sin embargo, sigue ocurriendo para concursos y posiblemente cursos.

**Comment by darkmx** [comment]
oops D: lo probé para problemas individuales, pero no se me ocurrió que podía pasar en otro lado
lo abro de nuevo y gracias por el update

**Comment by darkmx** [comment]
Creo que ahora sí ya no ocurre (lo cheque en un problema individual y en un concurso).
