### ISSUE TITLE
[FEATURE] Mejoras a la tabla de "Progreso de los estudiantes"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4980]
Hola amigos de omegaUp.

Francisco Zaragoza me pidió que les publicara las siguientes sugerencias de mejora:
- La última columna actualmente se llama "Puntuaje global" pero muestra un símbolo de porcentaje. En el resto de la tabla se hace una diferenciación entre porcentajes y puntajes. Por lo mismo, la última columna no debería contener el símbolo de porcentaje. Francisco sugiere también que se llame "Calificación global" (aunque en lo personal prefiero que siga siendo "Puntaje global" porque la calificación de un curso escolar puede depender de otras cosas que no están en omegaUp).
- Sería bueno poder ordenar las columnas de la tabla.

**Comment by tvanessa** [comment]
- Para el primer punto: sigamos el mismo formato que las otras columnas (y dejemos el título como Puntaje global), por ejemplo

![Screen Shot 2021-01-26 at 2 54 36 PM](https://user-images.githubusercontent.com/13296248/105918322-97dfa580-5fe8-11eb-92dc-7ba41f13d603.png)

 - Empecemos con ordenar la columna de "Nombre" de estudiante. Si no es complicado, seguir con la del "Puntaje global". Esta bien si se abre otro issue para eso.
