### ISSUE TITLE
[BUG] Los bloques de código multilínea son ilegibles.

### ISSUE THREAD

**Issue by luisoncpp** [omegaup/omegaup#4987]
## Comportamiento Esperado

Un bloque de código(code sample, &lt;pre&gt; &lt;code&gt; Ctrl + K) de varias líneas debería de estar dentro de un solo marco.

## Comportamiento Actual

Los bloques de código se ven mal, un bloque de código de muchas líneas se ve como varios bloques de código de una sola línea encimados, cada línea tiene su propio marco y los marcos acaban encimados.

## Posible Solución

Hasta hace poco funcionaba bien, así que nomás habrá que ver qué rompió el funcionamiento y corregir esa parte.

## Pasos para reproducir (para bugs)

Abrir
https://omegaup.com/arena/problem/teatro/#problems

## Contexto

La mayor parte de los problemas que subo utilizan eso para detallar la entrada y la salida, se volvieron ilegibles ahora.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* Sistema Operativo y versión: Windows 10 de 64 bits
* Link al sitio en el que este problema pasa:  https://omegaup.com/arena/problem/teatro/#problems
* Captura de pantalla: https://files.slack.com/files-pri/T04UR3ZCR-F01HAHULZ18/image.png

**Comment by pabo99** [comment]
Al parecer ya quedó corregido con el deploy de hace un momento. Ya se puede cerrar este issue
