### ISSUE TITLE
[FEATURE] Mejorar la interfaz para minimizar la cantidad de clics necesarios para ver los problemas

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#4996]
Hola amigos de omegaUp.

Conforme crece la plataforma, la interfaz también cambia, y la cantidad de clics que se tienen que dar para lograr alguna acción está aumentando. Una sugerencia concreta es que debe ser posible entrar a la lista completa de problemas en https://omegaup.com/problem/ y a la colección de problemas en https://omegaup.com/problem/collection/ con un solo clic desde la portada y sin tener que hacer scroll (aunque esto implicaría modificar la portada del sitio). 

Una mejora que requiere menos cambios (y que no es mutuamente excluyente) es agregar la opción de ver la lista de todos los problemas en el submenú "Problemas" de la barra principal. Además, yo agregaría una línea separadora para distinguir los enlaces a las listas de los enlaces relacionados con crear contenido.

![image](https://user-images.githubusercontent.com/19719969/103461202-39bdec00-4ce2-11eb-949d-cf49c00498cb.png)

**Comment by YannyTwoo** [comment]
I'd like to work on this issue.

**Comment by pabo99** [comment]
Done!

**Comment by YannyTwoo** [comment]
Hi, every time I'm trying to push the changes, the lang.en.ts (same for pt and es) get rewritten and the translations I've added for the changes get removed.
Running `./stuff/lint.sh --linters=i18n fix --all` doesn't help either

**Comment by YannyTwoo** [comment]
Unable to resolve a dubious ownership error again when pushing

**Comment by YannyTwoo** [comment]
Dubious ownership error comes up when I just push a single branch, is this the case for everyone?
