### ISSUE TITLE
[BUG] Algunos veredictos viejos de la cola de nominaciones siguen mostrándose incorrectamente

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5002]
Hola amigos de omegaUp.

Cuando se hizo el rediseño de la cola de nominaciones, ocurrió una inconsistencia interna cuando las opciones disponibles para el veredicto pasaron de ser dos a ser tres. Tenía entendido que se hizo un datafix para corregirlo, pero aparentemente aún hay problemas. Por ejemplo, el reporte https://omegaup.com/nomination/11238/ se atendió y el problema se conservó ("resolved"), pero el error provocó que en la lista de nominaciones aparezca "banned" a pesar de que el problema sí está activo (como es correcto).

![image](https://user-images.githubusercontent.com/19719969/103971396-0c34d080-5130-11eb-9a83-5f6e17b3f3da.png)

Intenté sobreescribir el veredicto mostrado, pero me puso error interno:

![image](https://user-images.githubusercontent.com/19719969/103971479-5453f300-5130-11eb-833f-bfbb37b019cd.png)
```
{status: "error", error: "Hubo un problema interno al momento de intentar actualizar el problema.", errorname: "problemDeployerInternalError", errorcode: 412, header: "HTTP/1.1 412 PRECONDITION FAILED", …}
error: "Hubo un problema interno al momento de intentar actualizar el problema."
errorcode: 412
errorname: "problemDeployerInternalError"
header: "HTTP/1.1 412 PRECONDITION FAILED"
httpStatusCode: 412
status: "error"
_id: "5ff7d2f5f0d4e033816013"}
```

Aprovechando que el estado de los problemas no fue afectado por el bug, creo que lo mejor es que cualquier reporte que aparezca como "banned" pero cuyo problema realmente siga activo, se corrija. Del mismo modo, que se corrija cualquier reporte que aparezca como "resolved" pero cuyo problema realmente esté baneado. Los reportes de "warning" no deberían tener ningún error. En teoría la verificación debe ser innecesaria para los veredictos hechos después del rediseño de la cola de nominaciones.

**Comment by tvanessa** [comment]
Hacer datafix de la tabla de QualityNominations: 
 - cuando `nomination = demotion` y,
   - cuando `status = banned`, hacer un fix pues si los problemas dicen `banned` pero están activos en la plataforma cambiarlos a `status = resolved`.
   - cuando `status = resolved`, hacer un fix ya que si los problemas estan baneados entonces de debe cambiar `status = banned`

**Comment by lhchavez** [comment]
Ya se corrió el datafix.
