### ISSUE TITLE
[FEATURE] Hacer gender-free las descripciones de las insignias (parte 1)

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5011]
### Modificar en los archivos lang en español y portugués las siguientes cadenas:

----------- Español
badge_100solvedProblems_description = "Otorgado a personas que han resuelto 100 problemas o más."
badge_500score_description = "Otorgado a personas que han conseguido una puntuación igual o mayor que 500."
badge_coderOfTheMonth_description = "Otorgado a personas que han sido nombradas Coder del Mes al menos una vez."
badge_contestManager_description = "Otorgado a personas que han administrado al menos un concurso."
badge_contestManager_name = "Admin de Concurso"
badge_cppExpert_description = "Otorgado a personas que han resuelto más de 10 problemas en C++."
badge_cppExpert_name = "Especialista en C++"
badge_feedbackProvider_description = "Otorgado a personas que han enviado la calificación de al menos un problema."
badge_javaExpert_description = "Otorgado a personas que han resuelto más de 10 problemas en Java."
badge_javaExpert_name = "Especialista en Java"
badge_karelExpert_description = "Otorgado a personas que han resuelto más de 10 problemas en Karel."
badge_karelExpert_name = "Especialista en Karel"
badge_legacyUser_description = "Otorgado a personas que realizaron algún envío hace más de 3 años."
badge_pascalExpert_description = "Otorgado a personas que han resuelto más de 10 problemas en Pascal."
badge_pascalExpert_name = "Especialista en Pascal"
badge_problemSetter_description = "Otorgado a personas que han creado al menos un problema."
badge_pythonExpert_description = "Otorgado a personas que han resuelto más de 10 problemas en Python."
badge_pythonExpert_name = "Especialista en Python"
badge_updatedUser_description = "Otorgado a personas que han completado la información en su perfil."
badge_virtualContestManager_description = "Otorgado a personas que han administrado al menos un concurso virtual."
badge_virtualContestManager_name = "Admin de Concurso Virtual"
 
----------- Portugués

badge_100solvedProblems_description = "Concedido a pessoas que resolveram 100 ou mais problemas."
badge_500score_description = "Concedido a pessoas que obtiveram pontuação igual ou superior a 500."
badge_coderOfTheMonth_description = "Concedido a pessoas que foram nomeadas Coder do Mês pelo menos uma vez."
badge_contestManager_description = "Concedido a pessoas que administraram pelo menos um concurso."
badge_contestManager_name = "Admin do Concurso"
badge_cppExpert_description = "Concedido a pessoas que resolveram mais de 10 problemas em C++."
badge_cppExpert_name = "Especialista en C++"
badge_feedbackProvider_description = "Concedido a pessoas que enviaram uma classificação para pelo menos um problema."
badge_javaExpert_description = "Concedido a pessoas que resolveram mais de 10 problemas em Java."
badge_javaExpert_name = "Especialista en Java"
badge_karelExpert_description = "Concedido a pessoas que resolveram mais de 10 problemas em Karel."
badge_karelExpert_name = "Especialista en Karel"
badge_legacyUser_description = "Concedido a pessoas que enviaram uma solução há mais de 3 anos."
badge_pascalExpert_description = "Concedido a pessoas que resolveram mais de 10 problemas em Pascal."
badge_pascalExpert_name = "Especialista en Pascal"
badge_problemSetter_description = "Concedido a pessoas que criaram pelo menos um problema."
badge_pythonExpert_description = "Concedido a pessoas que resolveram mais de 10 problemas em Python."
badge_pythonExpert_name = "Especialista en Python"
badge_updatedUser_description = "Concedido às pessoas que completaram as informações em seu perfil."
badge_virtualContestManager_description = "Concedido a pessoas que administraram pelo menos um concurso virtual."
badge_virtualContestManager_name = "Admin do Concurso Virtual"

**Comment by RodCross** [comment]
@tvanessa Pensaba abrir una issue para las dos insignias que falta hacer gender-free. Pregunto porque esta es la parte 1 y no sé si habrá algo más que hacer con otras insignias, yo tenía en mente estas dos:

![image](https://user-images.githubusercontent.com/52440153/107135198-85a61700-68c6-11eb-90a1-46afdc81010b.png)

**Comment by tvanessa** [comment]
Sí, me parece bien abrir otro issue para actualizar esas dos badges. Gracias (:
