### ISSUE TITLE
[Rediseño de Cursos] Implementar el homepage de Cursos

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#5013]
Implementar `https://omegaup.com/courses/` que presentará la información de: https://mi5fge.axshare.com/#id=z3v4ig&p=homepage_cursos&hi=1&g=1

**Comment by tvanessa** [comment]
Para español y portugués hay que cambiarlo para que sea gender-free.

----------
En omegaUp, 

Docentes pueden:

- Acceder y usar más de 2000 problemas de calidad para utilizar como tareas y exámenes.
- Observar el avance de sus estudiantes.
- Identificar los temas que se están complicando a sus estudiantes.


Estudiantes pueden:
- Obtener retroalimentación automática de sus soluciones.
- Aprender habilidades que les serviran en su vida profesional.
- Acceder a cursos en línea 24/7.

--------
En omegaUp, 

Professores podem:

- Acesse e use mais de 2.000 problemas de qualidade para usar como tarefas e testes.
- Observe o progresso de seus alunos.
- Identifique os problemas que estão complicando seus alunos.


Alunos podem:
- Obtenha feedback automático sobre suas soluções.
- Aprenda habilidades que o servirão em sua vida profissional.
- Acesse cursos online 24/7.

---------
In omegaUp professors can:
	- Choose from more than 2000 problems for their assignments and exams in their courses.
	- Follow the student's progress in real-time.
	- Identify areas where students are struggling.

In omegaUp students can:
	- Get instant feedback on their solutions.
	- Learn professional skills.
	- Access public online courses 24/7.

**Comment by carlosabcs** [comment]
Ping @tvanessa por fa dale una revisada para poder  hacer que esto se suba a producción al mismo tiempo que las redirecciones a esta página (que ya están mergeadas en master).
