### ISSUE TITLE
[Rediseño de Cursos] Implementar modal para dar detalles sobre cursos que estudio y cursos públicos

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#5015]
Tal y como aparece en https://mi5fge.axshare.com/#id=tmo3uy&p=lista_de_problemas_2_-__info&hi=1&g=1
TODO: Definir qué irá como texto del modal cc @tvanessa @heduenas

**Comment by tvanessa** [comment]
Cursos públicos:
- Estos cursos son bajo demanda, es decir puedes inscribirte y completarlos cuando tú quieras
- No tienen ningun costo.
- Puedes obtener retroalimentación instantanea sobre tus soluciones.
- Incluyen lecturas


Cursos que estudio:
- Cada que comienzas un curso lo podrás ver y continuar en esta lista.
- También podrás ver los cursos a los que te invitan las y los docentes de tu escuela.
- Se mostrarán solo tus cursos más recientes, para ver más ve a "Ver todos los cursos"


Public courses:
- These courses are on-demand. You can enroll and complete it anytime you want.
- They are free.
- You can get instant feedback on your solutions.
- Lectures are included.

Curses I study:
- Every time you enroll in a course, you will be able to see it on this list.
- You can also see the list of courses that your professors invite you to join.
- We will show your most recent courses if you want to see them all go to "See all courses".
