### ISSUE TITLE
[FEATURE] Quitar bullets en el footer

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5024]
Recientemente se hicieron cambios a los CSS y esto afecto el estilo del footer. Las ligas del footer no deberian tener bullets

![Screen Shot 2021-01-15 at 1 45 04 AM](https://user-images.githubusercontent.com/13296248/104708966-3445a600-56d3-11eb-82d0-09c5ebf393b6.png)

**Comment by pabo99** [comment]
Ya se resolvió parcialmente con el PR #5007:

![image](https://user-images.githubusercontent.com/3230352/104753915-3aad3f80-571e-11eb-9de4-df4dda9d387f.png)

 Sólo faltaría quitar los bullets de:
- Código de conducta.
- Políticas de privacidad.
