### ISSUE TITLE
[BUG] Clonar concurso no está funcionando

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#5029]
## Comportamiento Esperado

Al intentar clonar un curso, debería todo funcionar satisfactoriamente.

## Comportamiento Actual

Me aparece el siguiente mensaje:

![image](https://user-images.githubusercontent.com/20785082/104928483-b69ec600-5970-11eb-8281-6ae1ac501dbb.png)

## Posible Solución

Probablemente sea un error en la API

**Comment by pabo99** [comment]
¿En qué vista encontraste este error? Ya que hay varios lugares donde se puede clonar un curso. Y no logro reproducirlo tal cual como lo que te aparece a ti.

También se me hace extraño ese datetime que te está mostrando en la consola: `v_-01-01 00:00:00`

**Comment by carlosabcs** [comment]
> ¿En qué vista encontraste este error? Ya que hay varios lugares donde se puede clonar un curso. Y no logro reproducirlo tal cual como lo que te aparece a ti.
> 
> También se me hace extraño ese datetime que te está mostrando en la consola: `v_-01-01 00:00:00`

Perdón, era clonar concurso

**Comment by pabo99** [comment]
> > ¿En qué vista encontraste este error? Ya que hay varios lugares donde se puede clonar un curso. Y no logro reproducirlo tal cual como lo que te aparece a ti.
> > También se me hace extraño ese datetime que te está mostrando en la consola: `v_-01-01 00:00:00`
> 
> Perdón, era clonar concurso

Ya me había asustado un poco de que no encontraba la falla por ningún lugar. Más tarde reviso los concursos.

Gracias.
