### ISSUE TITLE
[FEATURE] Considerar activar apc.stat

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#504]
APC hace un stat al principio de cada request para ver si hay que recompilar o no. Si cambiamos esta bandera, al parecer es significativamente más rápido, pero a cambio cada modificación de código que se haga necesita que reiniciemos el servidor.

http://www.php.net/manual/en/apc.configuration.php#ini.apc.stat

**Comment by lhchavez** [comment]
Como ya tenemos un script de deployment, podemos hacerlo :D

**Comment by pabloaguilar** [comment]
Obsoleto
