### ISSUE TITLE
[FEATURE] Como un soporte, quiero cambiar correos de usuarios para las personas que pierden sus correos.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#5054]
Como usuario soporte necesito una herramienta que me permita reasignar correos de cuentas, debido que las personas pierden sus accesos a los correos con los cuales hicieron su primer registro.

## Comportamiento Esperado
Una herramienta donde pueda asignar un correo a un usuario especifico de manera manual.
## Comportamiento Actual

Actualmente mi cuenta momega (Soporte) no cuenta con dicha funcionalidad, al tenerla podré reasignar los usuarios que necesiten accesos a dicho correo.

## Contexto

Los usuarios de omegaUp suelen perder los correos con los cuales accedieron por primera vez a la plataforma y necesitan recuperar sus cuentas mediante un correo nuevo.

**Comment by lhchavez** [comment]
@tvanessa @heduenas será posible darle prioridad a esto?

**Comment by pabo99** [comment]
Hola @miguelomega, en este caso en específico que comentas: ¿Cuáles son los datos que le pides al usuario para poder comprobar que el usuario realmente es el dueño de la cuenta?

Te lo pregunto para poder agregar las búsquedas necesarias con la información que se puede requerir al momento de realizar la consulta.

**Comment by miguelomega** [comment]
El usuario y la contraseña actual, el correo que es actual y el correo que
será después, si sientes que podríamos agregar algo más como una
identificación estaría bien.

**Comment by pabo99** [comment]
Con eso es suficiente para saber que la cuenta le pertenece. @miguelomega , te etiquetaré en el PR donde se muestre la UI para que nos ayudes a ver si con eso es suficiente para que puedas realizar esta acción de cambiar correo electrónico
