### ISSUE TITLE
[BUG] Errores al ver el listado de cursos

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#5070]
Al ingresar a la página de lista de cursos, se muestra un error en la consola de desarrollador:
```
VM1045 npm.vue.js:642 [Vue warn]: Property or method "acessMode" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <CourseCardsList> at frontend/www/js/omegaup/components/course/CardsList.vue
       <Root>
```
Da la impresión que nada más es un `typo`, de cualquier forma hay que revisarlo. Esto no afecta para mostrar el listado de cursos

Parece que nada más sucede en el ambiente local, no logré reproducirlo en sandbox.

**Comment by carlosabcs** [comment]
Este issue ya puede ser cerrado, lo solucioné cuando cambié el nombre de los componentes.
