### ISSUE TITLE
[BUG] No se puede seleccionar una fecha en febrero al crear un curso

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5073]
Esto afecta a los profesores del curso de capacitación porque su curso debe de comenzar en febrero.

Si selecciono una fecha en febrero cambia el mes a marzo.

![bugfecha](https://user-images.githubusercontent.com/13296248/106312305-4bc87700-621b-11eb-80db-3d4f1acbb0a3.gif)

**Comment by heduenas** [comment]
Hoy ya no se reproduce. Al parecer es un bug que depende de la fecha. Le voy a bajar a P2.
