### ISSUE TITLE
[BUG] No se pueden descargar carpetas adjuntas en problemas interactivos.

### ISSUE THREAD

**Issue by omarpaladines** [omegaup/omegaup#5074]
## Comportamiento Esperado

En el problema interactivo:
https://omegaup.com/arena/problem/OMI-2020-Primo
se intenta descargar la carpeta con el código de ejemplo.
## Comportamiento Actual

No ocurre nada. No hay descarga de archivos.

## Tu ambiente

Chrome en Windows, pero también me ocurrió en MacOS.

**Comment by lhchavez** [comment]
Esto debería entrar a producción en el deploy de en la noche.
