### ISSUE TITLE
[BUG] Al equivocarse en la creación de un problema o concurso, algunos campos se resetean

### ISSUE THREAD

**Issue by gabrc52** [omegaup/omegaup#5080]
## Comportamiento Esperado

*Describe lo que originalmente estabas intentando hacer y cómo esperabas que se comportara la plataforma.*

Si te equivocas en la creación de un problema o concurso, OmegaUp te dice cuáles son los campos que tienes que corregir, los corriges y ya puedes terminar.

## Comportamiento Actual

*Describe lo que en realidad pasó en lugar de lo que se esperaba*

Si te equivocas en la creación de un problema o concurso, OmegaUp te dice cuáles son los campos que tienes que corregir, los corriges y ahora te revirtió otros campos a su valor predeterminado o en blanco.

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

Por ejemplo:

1. Crear un problema
2. No ponerle tags
3. Algunos de los campos como el alias y el zip se resetearon y se tienen que volver a llenar

## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
*El contexto que nos proporciones nos ayuda a encontrar la solución adecuada*

Si te equivocas en la creación de un concurso, te dice en qué te equivocaste pero te resetea la duración del concurso. Si no te das cuenta, creas un concurso de 5 horas accidentalmente.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Firefox 84.0.2 (aunque parece ser problema de backend)
* Sistema Operativo y versión (escritorio o móvil): Escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/contest/new/ , https://omegaup.com/problem/new/
* Captura de pantalla: *se omite*

**Comment by carlosabcs** [comment]
Hola, no he conseguido reproducir este issue. Puedes detallar un poco más los pasos para revisarlo?

**Comment by carlosabcs** [comment]
No he conseguido reproducir el problema para concursos.

Para problemas, solo he visto que se resetean:
- Alias
- ZIP file,
el primero ya lo estoy corrigiendo en un PR, el segundo no es posible guardarlo de alguna forma (recuerda que la página se recarga cuando envías el formulario).

**Comment by carlosabcs** [comment]
@tvanessa puedes dar una revisada a este issue? Según yo, ya hice todo lo posible para resolverlo (y cerrar el issue), pero si consideras que hay algo más que se deba hacer, por favor coméntamelo.
