### ISSUE TITLE
[FEATURE] Uniformar el consumo de memoria para todos los lenguajes de programación

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5083]
Hola amigos de omegaUp (lo siguiente es de _muy_ baja precedencia y posiblemente lo que propongo ni siquiera sea la mejor solución, pero lo escribo antes de que se me olvide y para que quede registro).

Como muchos saben, la Java Virtual Machine consume mucha memoria por defecto (cientos de MB). Para que el límite de memoria de los problemas de omegaUp no tumben a Java de inmediato, la plataforma intenta ocultar este hecho. Por ejemplo, un main vacío en Java y en C++ se reportan así:

![image](https://user-images.githubusercontent.com/19719969/106526700-b1cb2d80-64ab-11eb-8cc1-a18de7e095ce.png)

Como a C++ no hay que hacerle ningún favor, su consumo de memoria incluye la imagen del ejecutable tras cargarse, Sin embargo, esto resulta en que el usuario puede emplear más memoria para sus variables en Java que en C++. Yo subo algunos problemas con un límite de memoria muy bajo y esto puede resultar perjudicial. De hecho, tan sólo por claridad, sería bueno restarte a todos los lenguajes la cantidad de memoria que usan los programas más cortos de cada lenguaje (y en su caso, con el compilador respectivo), para poder tener una comparación un poco más justa.

**Comment by lhchavez** [comment]
ja, eso ya se hace. el problema es que la manera en la que se reporta la memoria total usada varía _ligeramente_ entre ejecuciones (un par de MB es normal), así que se eligió la memoria más grande de Java que se reportó a lo largo de varias ejecuciones como la "memoria base".

así que cerrando porque ya está uniformado!

**Comment by darkmx** [comment]
También se hizo lo mismo con C/C++? (lo de correrlo varias veces para calcular una memoria base y restarla)

**Comment by lhchavez** [comment]
> También se hizo lo mismo con C/C++? (lo de correrlo varias veces para calcular una memoria base y restarla)

sí, y fue menos de 1M. hay que notar que en C++ *no* se incluye la imagen del ejecutable: sólo el [Resident Set Size](https://en.wikipedia.org/wiki/Resident_set_size). el tamaño de la imagen (y de libc) no se cuentan porque esos se `mmap(2)`-ean por el kernel, y como no se modifican, no se contabilizan contra el RSS.

**Comment by darkmx** [comment]
Aunque el ejecutable de un programa grandote (ej Photoshop o alguna cosa así) no esté completo en RAM física (si una funcionalidad nunca se usa, entonces nunca se asigna en memoria física aunque esté en el espacio de direcciones), sospecho que, en el caso de los programitas que se suben a omegaUp, prácticamente todo el ejecutable sí termina cayendo en el RSS (seguramente no todo glibc; he visto programas que "bajan su memoria" con tan sólo evitar printf). Pero bueno, si también se hizo el mismo ejercicio para C/C++ entonces efectivamente, caso cerrado.
