### ISSUE TITLE
[BUG] En el perfil de otra persona se muestran mis insignias no las de ella

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#5129]
Edit: también considerar el caso cuando no se ha iniciado sesión

![image](https://user-images.githubusercontent.com/20785082/107376162-92d62800-6ab7-11eb-8c35-e3232ab50dee.png)

![image](https://user-images.githubusercontent.com/20785082/107376244-ac776f80-6ab7-11eb-9d20-9e39692e200a.png)

![image](https://user-images.githubusercontent.com/20785082/107376298-ba2cf500-6ab7-11eb-9063-12b0c03bb420.png)

**Comment by tvanessa** [comment]
No he podido reproducirlo en firefox, ni en chrome.

Pero si noté que cada perfil que visito tiene las mismas insignias. El perfil desde el que probaste tiene alguna insignia?

**Comment by carlosabcs** [comment]
> No he podido reproducirlo en firefox, ni en chrome.
> 
> Pero si noté que cada perfil que visito tiene las mismas insignias. El perfil desde el que probaste tiene alguna insignia?

Lo hice desconectado, pero para un usuario desconectado, las insignias del usuario del perfil igual deben mostrarse, pero en escala de grises.
