### ISSUE TITLE
[BUG] Para agregar problemas a un examen hay que intentarlo varias veces

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#5148]
En un concurso, cuando se intentan agregar problemas:

1. Escribe el nombre de un problema
2. Elíge uno que aparece en la lista

Esperado:
   Se habilita el botón de agregar problema
Actual:
   No pasa nada.

En este video se ve lo que está pasando. Esta fue la tercera vez que escribí el nombre. Al final del video se ve que al fin se habilita el botón.

https://www.youtube.com/watch?v=e_mg_pDpkWE

**Comment by tvanessa** [comment]
Al parecer el botón se activa hasta que cambias de campo (o das click en otro lado). Hay que hacer que se active cuando selecciones el problema.
