### ISSUE TITLE
[FEATURE] Poder "eliminar" un concurso propio

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5164]
Hola amigos de omegaUp.

La plataforma nos permite eliminar problemas propios (en realidad se quedan ahí, pero al menos ya no nos aparecen en nuestra lista de problemas). Sería bueno poder hacer lo mismo con concursos.

**Comment by lhchavez** [comment]
jamás vamos a permitir eliminar cosas de verdad, pero hacer algo funcionalmente equivalente a lo que hacemos con concursos es factible.
