### ISSUE TITLE
[FEATURE - Arena UX] Tener un botón de exportar a .csv/.xlsx la tabla de scoreboard

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#5172]
Idea obtenida en lluvia de ideas para rediseño de arena.

Para más información: @licgerman

**Comment by tvanessa** [comment]
Poner un link en https://omegaup.com/contest/{alias}/edit/ en la pestaña de enlaces.
También se va a poner en el la página donde se muestra el scoreboard, pero esperamos hasta que se migre arena.contest a vue.

Extra: Corregir el string "Admin Scoreboard link" por "Admin scoreboard link"
![Screen Shot 2021-09-17 at 1 25 33 AM](https://user-images.githubusercontent.com/13296248/133751112-bec22a56-b2c5-41ce-a867-b804c4677d23.png)

**Comment by luis-8** [comment]
¿Se utilizaría la función `toCsv()` de [ViewProgress.vue](https://github.com/omegaup/omegaup/blob/3eb55298ff546cef130142f57384e6c648759f65/frontend/www/js/omegaup/components/course/ViewProgress.vue#L168)?

**Comment by tvanessa** [comment]
Sí, se puede usar. Pero hay que refactorizar para mover esa función a un archivo común  y que lo puedan usar los dos componentes.
