### ISSUE TITLE
[FEATURE - Arena UX] Mostrar todas las opciones de editar problema (regresar los tabs como estaban anteriormente)

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#5176]
Idea obtenida en lluvia de ideas para rediseño de arena.

Para más información: @darkmx

**Comment by pabo99** [comment]
It should show like in Courses:

![image](https://github.com/omegaup/omegaup/assets/3230352/ae8b33ce-3333-4d2d-bde7-0968ed3b6c3d)

**Comment by Aritra8438** [comment]
Hi @pabo99, This seems very similar to an issue assigned to me, can you assign this to me too?

**Comment by pabo99** [comment]
> Hi @pabo99, This seems very similar to an issue assigned to me, can you assign this to me too?

Done
