### ISSUE TITLE
No aparece la informacion del usuario

### ISSUE THREAD

**Issue by Moroni112** [omegaup/omegaup#5181]
## Comportamiento Esperado

*Describe lo que esperabas que pasara*

## Comportamiento Actual
A la hora de ver mi perfil, todo está en blanco, ya intenté ingresar desde diferentes dispositivos pero es el mismo resultado

*Describe lo que pasó en lugar de lo que se esperaba*
Se esperaba que apareciera toda mi informacion como usuario de omega up y ademas los problemas que he hecho y los que no e resuelto 

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/
* Errores en la consola: []
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/79867391/109540034-34311800-7a7f-11eb-8100-ef2b0118b08f.png)

**Comment by lhchavez** [comment]
también ocurre con https://omegaup.com/profile/SJMA_11723 . parece que no son _todos_ los perfiles, pero no es un caso aislado tampoco.

**Comment by pabo99** [comment]
Estos son los errores que están apareciendo en consola:

```
TypeError: Cannot read property 'contests' of undefined
    at new Z (Profilev2.vue?vue&type=script&lang=ts&:230)
    at VM205 npm.vue-class-component.js:1
    at a.data (VM205 npm.vue-class-component.js:1)
    at VM203 npm.vue.js:2
    at VM203 npm.vue.js:2
    at VM203 npm.vue.js:2
    at a.e._init (VM203 npm.vue.js:2)
    at new Z (VM203 npm.vue.js:2)
    at VM203 npm.vue.js:2
    at init (VM203 npm.vue.js:2)
     ...
VM203 npm.vue.js:2 TypeError: Cannot read property 'profileRank' of undefined
    at a.n (Profilev2.vue?vue&type=template&id=e8011a10&scoped=true&:61)
    at a.e._render (VM203 npm.vue.js:2)
    at a.r (VM203 npm.vue.js:2)
    at pn.get (VM203 npm.vue.js:2)
    at new pn (VM203 npm.vue.js:2)
    at VM203 npm.vue.js:2
    at a.wn.$mount (VM203 npm.vue.js:2)
    at a.wn.$mount (VM203 npm.vue.js:2)
    at init (VM203 npm.vue.js:2)
    at VM203 npm.vue.js:2
```

Pareciera que el elemento `extraProfileDetails` no se está llenando correctamente (es extraño, porque en los cambios recientes se quitaron algunos llamados a APIs para evitar justamente ese problema). Aún así, si llega a fallar algo, se atrapa la excepción pero se regresa el payload sin el elemento que ocasiona el error, aunque sólo se está mostrando en `logException` y no en el navegador.
