### ISSUE TITLE
[BUG] En un curso, el progreso de los estudiantes se rompió

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5183]
Hola amigos de omegaUp.

Algo (grave) le pasó al progreso de los estudiantes en los cursos de omegaUp (por ejemplo, https://omegaup.com/course/aed2020o), tanto en el sitio web como en las hojas de cálculo:

![image](https://user-images.githubusercontent.com/19719969/109571836-e1bd1f00-7ab1-11eb-903a-b991cdfe6509.png)

Aunque no se muestran las capturas completas, todo aparece en ceros excepto para la primera columna y el puntaje total (que sólo considera las evaluaciones que sí se están desplegando bien).
Sobra decir que sí ocurrieron evaluaciones. Si nos vamos a una en concreto (por ejemplo, la tarea 4 del mismo curso) vemos los envíos que los alumnos hicieron:

![image](https://user-images.githubusercontent.com/19719969/109572038-2ba60500-7ab2-11eb-8565-7639564ce3b9.png)

**Comment by carlosabcs** [comment]
@darkmx puedes verificar si ya está solucionado?

**Comment by darkmx** [comment]
Ayer Nancy me pidió que revisara (generé un CSV de un curso) y ya se ve bien. No sé si haya algún otro error escondido por ahí, pero no parece.
