### ISSUE TITLE
[BUG] En la lista de concursos, al entrar a modo práctica me regresa 404 

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5215]
### Pasos para reproducir:

 - Ir a https://omegaup.com/arena/
 - Seleccionar el tab "Concursos pasados"
 - Dar click en cualquiera de "Práctica".
 
![Screen Shot 2021-03-08 at 7 35 17 PM](https://user-images.githubusercontent.com/13296248/110415009-e6e81400-8045-11eb-9a32-6e01e3759bfd.png)

Probé en firefox 82

**Comment by pabo99** [comment]
Ahh, ya logré reproducirlo. En los concursos en los que no estabas registrado e intentas ingresar en modo práctica directamente es cuando manda este error. 
¿Qué sería recomendable, que te mande  a la página con el intro del concurso para que te registres  o que te permita ingresar directamente al concurso en modo práctica?
