### ISSUE TITLE
[FEATURE] Como desarrollador, quiero que las implementaciones de la API permitan interactuar con los problemas usando su ID

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5241]
## Comportamiento Deseado

- Obtener el ID de un problema mediante la API [`/problem/details/`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/README.md#apiproblemdetails).
- Obtener los detalles de un problema utilizando el ID por medio de la API [`/problem/details/`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/README.md#apiproblemdetails).
- Realizar envíos usando la API [`/run/create/`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/README.md#apiruncreate) y el ID de un problema.
- Posibilidad de interactuar con las API `/problem/*`, utilizando el ID de los problemas.

## Comportamiento Actual

Las API relacionadas con problemas usualmente están limitadas a el parámetro `problem_alias`. Seria una buena alternativa poder interactuar con dichas API utilizando el ID de los problemas.

## Posible Solución

Agregar el dato del ID en el tipo retornado por [`/problem/details/`](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/README.md#apiproblemdetails), y permitir el paso del parámetro `problem_id` a las API relacionadas con problemas. Esto serviría como una alternativa en caso de que no se conozca el alias.

## Contexto

Actualmente estoy desarrollando una CLI que se pueda integrar con la [API de OmegaUp](https://github.com/omegaup/omegaup/blob/master/frontend/server/src/Controllers/README.md) para realizar acciones de forma rápida. En caso de que algún usuario desee realizar un envió, y no conozca el alias de un problema, seria buena idea que pudiese proporcionar el ID en su lugar.

**Comment by lhchavez** [comment]
la idea es que si un usuario no conoce el alias de un problema, es casi certero que no tiene permiso para hacer envíos :(

voy a cerrar esto porque no queremos exponer ids más que de un conjunto limitado de cosas donde los alias no tienen sentido (ejemplos: clarificaciones)

**Comment by lhchavez** [comment]
visto desde otro punto de vista: para todo fin práctico, el `problem_alias` _es_ el id de los problemas!

**Comment by Apocryphon-X** [comment]
Entiendo, lo mejor será usar el `problem_alias` en lugar del ID al lado del nombre para no exponer datos adicionales

La idea que tenía era poder obtener un problema mediante ID como en el buscador de problemas pero para hacer envíos con el alias bastará

**Comment by lhchavez** [comment]
hmm pero qué se ganaría con obtener el id? necesitas el alias primero para obtener el id, o alternativamente usar cualquier otro api que igual regresaría el alias. no es más cómodo ni se ahorran pasos de ninguna manera.

el único escenario que se me ocurre es uno que queremos activamente evitar: el poder enumerar problemas a los que no tienes acceso.

**Comment by Apocryphon-X** [comment]
Tomando esos puntos en cuenta, es mejor usar el `problem_alias`. No sería bueno obtener acceso a problemas privados así que me quedaré con el alias, como mencionas es más práctico!
