### ISSUE TITLE
Feature: I18N

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#525]
Hay que importar los millones de problemas abiertos en inglés para tener i18n

**Comment by elendil326** [comment]
@lhchavez cuando dices "importar" dices traducir? Está medio ambigua la cosa para darle otro número que no sea el infinito.

**Comment by lhchavez** [comment]
no, cuando dije "importar" realmente quise decir "importar" :P se suponía que ese era un repositorio con un montón de problemas ya en inglés, pero las prioridades han cambiado y ahora necesitamos contenido (de calidad)  en español.
