### ISSUE TITLE
Modo de historia con Karel

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#526]
"un tutorial sin ser un tutorial" ~alanboy

podemos hacer un modo donde haya varios problemas sencillos con karel.js interactivos de volón

**Comment by elendil326** [comment]
@lhchavez este feature implica crear nuevos problemas o abilitar el modo interactivo en problemas existentes?

**Comment by elendil326** [comment]
Karel ya no es una prioridad en términos de las olimpiadas.
