### ISSUE TITLE
[FEATURE] Agregar interfaz para administrar API tokens

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#5271]
Parte de #5242

Idealmente esto debería ir en https://omegaup.com/profile/edit/ con una interfaz similar a https://github.com/settings/tokens

**Comment by DT3264** [comment]
Hey @lhchavez, I'd like to add the interface to manage API tokens, are there any details I should be aware of?

**Comment by tvanessa** [comment]
> 

Puedes comenzar revisando los PR que se hicieron para la parte del backend. Aqui se muestra una lista de ellos: #5242
