### ISSUE TITLE
[BUG] No se pueden usar problemas Solo Salida en Concursos cuando se quita la opcion de cat en el listado de lenguajes

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5286]
## Comportamiento Esperado

Crear concursos, agregar problemas de `Solo Salida` y poder hacer envíos correctamente. 

## Comportamiento Actual

Al agregar un problema de `Solo Salida` en un concurso, no aparece la opción para hacer envíos y el problema se queda como si fuera de tipo Lectura.  Antes esto no ocurría.

## Pasos para reproducir 

1. Crear un concurso.
2. En el listado de lenguajes permitidos, elimina la opción `cat`.
3. Agregar un problema de `Solo Salida` al concurso recién creado.
4. Revisar la parte de envios.

![Issue-Solo-Salida](https://user-images.githubusercontent.com/40130428/112661543-41da8300-8e1c-11eb-8067-fd4c53ccfb4d.PNG)

## Contexto

Estaba tratando de hacer un concurso para entrenar a mi subdelegación. Agregue algunos problemas de Solo Salida pero dentro de poco me percate que no se podían realizar envíos. Tuve que agregar otros problema de imprevisto.

## Tu ambiente

- Nombre del navegador: Google Chrome Versión 89.0.4389.82 (Build oficial) (64 bits)
- Sistema Operativo y versión: Microsoft Windows 10 Home Single Language 10.0.18363 Compilación 18363.
- Link al sitio en el que este problema pasa: **Cualquier concurso con problemas de `Solo Salida`**.

**Comment by pabo99** [comment]
Hola @Apocryphon-X , estuve intentando reproducir el escenario que describes, pero todo me funciona como debería:

![OnlyOutputProblem](https://user-images.githubusercontent.com/3230352/112668281-f2985080-8e23-11eb-80b9-3a7167920688.gif)

A menos que no esté considerando algo. ¿Ya revisaste que el archivo .zip cuente con la información necesaria para que el problema acepte envíos?

Sigo al pendiente.

**Comment by Apocryphon-X** [comment]
Hola @pabo99! Estuve analizando que podría estar causando el *"bug"*.

Descubrí que el problema esta en la sección de lenguajes:
![Issue-OmegaUp](https://user-images.githubusercontent.com/40130428/112680955-a6550c80-8e33-11eb-93d6-a97c19436605.PNG)

Se omitió la opción `cat` (sin querer), esto volvió imposible resolver problemas de solo salida en el concurso.  Seria buena idea que no se pudiera eliminar esta opción, pues este tipo de problemas solo se puede resolver de ese único modo. 

He notado este mismo problema en los concursos pasados de otras personas pero nunca supe porque se originaba el problema. Puede que esto este causando confusión en algunos usuarios. (No todos saben a que _lenguaje_ se refiere `cat`)

**Comment by pabo99** [comment]
Ah, excelente. Eso si nos sirve para arreglar el bug. Deja cambio el título con eso que comentas.

**Comment by pabo99** [comment]
Posible solución: Cuando se agrega un problema de "sólo salida" a un concurso se pueden realizar dos acciones:
- Bloquear la opción de `cat` en el listado de lenguajes o agregarla en automático cuando se de de alta el problema de ese tipo.
- Para no bloquear ni asignar valores en automático, se puede mandar un mensaje de información que el concurso cuenta con problemas de ese tipo y si no se agrega la opción `cat`  no se podrá resolver.

**Comment by luis-8** [comment]
Hola, ¿cómo puedo crear un problema de Sólo Salida? 
Copie el archivo .zip del problema 'Sumas' para crear uno, y sólo dejé 4 carpetas: cases, examples, statements y solutions. En la carpeta cases sólo tengo 2 archivos: Main.in y Main.out. 
Al crear el problema seleccioné el tipo "Solo Salida"
¿Hay algo más que hacer? Intenté reproducir el bug con eso, y no tuve el problema.

**Comment by tvanessa** [comment]
Quitaste el lenguaje `cat` de la lista de lenguajes soportados en el concurso?

**Comment by luis-8** [comment]
> Quitaste el lenguaje `cat` de la lista de lenguajes soportados en el concurso?
Sí, ahorita también quité todos los demás para estar seguro, sólo dejé 1 lenguaje y aún así el participante tiene la sección de hacer envíos.

**Comment by tvanessa** [comment]
Lo hiciste en la máquina local? si no, me pasas el link de tu concurso para revisarlo?

**Comment by luis-8** [comment]
Sí, lo hice en la máquina local. Ahora lo intenté en sandbox y ahí sí se reproduce el bug. No sé por qué en la local no.
