### ISSUE TITLE
No es posible enviar soluciones en modo práctica en concursos ya finalizados [BUG]

### ISSUE THREAD

**Issue by Pino-29** [omegaup/omegaup#5300]
## Comportamiento Esperado

Que la plataforma desplegara los problemas y mostrara la opción de enviar soluciones.

## Comportamiento Actual

Al entrar al modo práctica la redacción de los problemas no se despliegan ni aparece opción para enviar soluciones

## Pasos para reproducir (para bugs)

1. Ingresar el siguiente link: https://omegaup.com/arena/pes-2019-junio-4/#problems/cuarta-transformacion 
2. Hacer clic en "Este concurso ha terminado. Para continuar enviando soluciones usa nuestro Modo Práctica haciendo clic aquí.", se encuentra en la parte superior.
3. Clic sobre cualquier problema del concurso.

## Contexto
Estaba intentando resolver un problema del pasado, de un concurso de hace 2 años (en el cual participé), pero al entrar al modo práctica los problemas no se despliegan ni aparece opción para enviar soluciones. Ahora no puedo saber si mi solución es correcta. :(

## Tu ambiente

* Nombre del navegador: Firefox Web Browser y Google Chrome.
* Sistema Operativo y versión (escritorio o móvil): Escritorio: Linux, Ubuntu 18.04
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/pes-2019-junio-4/#problems/cuarta-transformacion 
 aunque realmente me ha pasado lo mismo con todos los contest que he intentado.
* Captura de pantalla: 
![Screenshot from 2021-04-01 01-23-59](https://user-images.githubusercontent.com/59517584/113258339-0f4fe080-9289-11eb-8a7e-5a9e210103bd.png)

**Comment by Apocryphon-X** [comment]
Este bug esta muy (o completamente) relacionado con el issue #5231.
