### ISSUE TITLE
[BUG] La búsqueda de problemas sufre ante alias desafortunados

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5303]
Hola amigos de omegaUp.

Cuando un problema tiene como alias una palabra muy común, ocurre una interacción fea con el typeahead y el buscador. Con el typeahead, suele ser común encontrar el problema específico que estábamos buscando. Sin embargo, al darle click al problema deseado en el typeahead, el typeahead reemplaza el contenido del `input type="text"` por el alias del problema elegido. Si el alias es una palabra muy común, entonces ahora la búsqueda real se hará con esa palabra, _tanto en el nombre de problema como en el alias_. Eso quiere decir que lo que queríamos hacer (restringir la búsqueda para accesar al problema que queríamos) fracasará.

![Untitled_ Apr 2 2021 5_48 PM](https://user-images.githubusercontent.com/19719969/113461932-ec821100-93db-11eb-995f-374fb80bab68.gif)

**Comment by darkmx** [comment]
PD. aquí lo ideal sería que, al darle click a lo que el typeahead sugiere, se nos debería redirigir en automático al problema elegido.

**Comment by npave** [comment]
Me acabo de topar con esto otra vez, estoy queriendo agregar un problema de nombre Caminos y no aparece en la lista, Caminos- es un problema diferente. 

![image](https://user-images.githubusercontent.com/940007/156015638-734cf325-f4aa-4e94-9243-78d6dbfcb576.png)

**Comment by darkmx** [comment]
Relacionado con #5564

**Comment by tvanessa** [comment]
Se resuelve con #6700
