### ISSUE TITLE
[BUG] No sirven los concursos (Modo práctica)

### ISSUE THREAD

**Issue by Chyaru** [omegaup/omegaup#5310]
Seleccionas uno de los problemas y no carga nada.
![image](https://user-images.githubusercontent.com/82061637/113778965-a5a15d80-96f2-11eb-8df5-9e7234c6b9a8.png)

**Comment by lhchavez** [comment]
@pabo99 puedes ayudar?

**Comment by pabo99** [comment]
Si, esto ya se arregló en el PR #5301, ya que se debe al mismo problema reportado en los issues #5231 y #5300 donde los concursos contienen problemas privados

**Comment by lhchavez** [comment]
En teoría esto ya debe estar resuelto. Si no es el caso, por favor vuelve a abrir este issue

**Comment by Apocryphon-X** [comment]
@lhchavez Hola! Lamentablemente este issue sigue ocurriendo :( . Por ejemplo, el contest `pes-2021-abril-1` aún presenta este problema.
![image](https://user-images.githubusercontent.com/40130428/114326199-39ab6480-9af9-11eb-8fb2-fb428a810ca1.png)

**Comment by pabo99** [comment]
Ingresé a este concurso en modo práctica y si puedo ver los problemas como se puede mostrar:

![ArenaContestPracticeOk](https://user-images.githubusercontent.com/3230352/114501176-1367f080-9bef-11eb-9151-b57cdc751474.gif)

Tengo dos teorías de porque se muestra así en el caso de @Apocryphon-X :

- Intentó ingresar antes de que se hiciera el deploy.
- La conexión de red es lenta y tarda en cargar, y esto da la apariencia que no carga los problemas.

Para la segunda teoría, habrá que agregar un [spinner](https://vue-spinners.saeris.io/) y se oculte hasta que se cargue el problema, en caso de que exista un error, que aparezca en la pantalla, para que garanticemos que funciona correctamente.

**Comment by Apocryphon-X** [comment]
@pabo99: Ya descubrí cual es el problema. Al parecer, intentar acceder al modo practica desde la pestaña "Concursos pasados" provocara este error si no ingresaste previamente al contest.

![image](https://user-images.githubusercontent.com/40130428/114750532-b3219d80-9d19-11eb-8cc5-eba987af0be9.png)

El proceso para replicar el bug, se ve acá:
![issue-omega-1](https://user-images.githubusercontent.com/40130428/114752031-82426800-9d1b-11eb-8c9e-19f783cf260b.gif)

**Comment by pabo99** [comment]
Ah, perfecto. Esa información es más útil para poder arreglar este issue.

**Comment by Apocryphon-X** [comment]
Hola! El cambio de la PR ya se aplico a omegaUp? Al parecer sigue ocurriendo el problema que mostré en la animación hace unos días. (Donde entras a un concurso modo practica desde la pestaña "Concursos pasados", sin registrarte previamente)

Resulta que acceder de dicho modo a los concursos en modo practica te impide ver problemas en lo absoluto. Por ejemplo, no pude ver ningún problema en el concurso `PCPP` . El concurso incluye el problema `Watermelon` y tampoco lo pude ver a pesar de que soy administrador de dicho problema .

Solo se pueden ver los problemas si te sales del modo practica y te registras en el concurso. Sinceramente, no se si esto sea comportamiento esperado.

> @pabo99: Ya descubrí cual es el problema. Al parecer, intentar acceder al modo practica desde la pestaña "Concursos pasados" provocara este error si no ingresaste previamente al contest.
> 
> ![image](https://user-images.githubusercontent.com/40130428/114750532-b3219d80-9d19-11eb-8cc5-eba987af0be9.png)
> 
> Este es el proceso para replicar el bug:
> ![issue-omega-1](https://user-images.githubusercontent.com/40130428/114752031-82426800-9d1b-11eb-8c9e-19f783cf260b.gif)

**Comment by lhchavez** [comment]
> Hola! El cambio de la PR ya se aplico a omegaUp?

aún no. hacemos deployment a producción los sábados y domingos en la noche.

**Comment by Apocryphon-X** [comment]
Ah ok. Entiendo 😅
