### ISSUE TITLE
[BUG] Dejó de funcionar el comando {{codigo.[lang]}} para pegar código en markdown

### ISSUE THREAD

**Issue by Juanito98** [omegaup/omegaup#5314]
## Comportamiento Esperado

Hace unos meses se habilitó la función de agregar en el markdown algo como lo siguiente

<details><summary>Solución para la Subtarea 1 (25 puntos)</summary>

{{file.[lang]}}

</details>

Esto hacía que se desplegara el código. 

## Comportamiento Actual

Ahora que lo necesito para un concurso que debo hacer el sábado, veo que ya no está funcionando.
Dice: 

Unreconized source filename: archivo

## Posible Solución

Checar qué pasó ahí

## Pasos para reproducir (para bugs)

Como referencia pueden ver este problema de la OMI 2020.

https://github.com/ComiteMexicanoDeInformatica/OMI-Archive/blob/75ea10e0420ac85a3cfced4d3ba1ffee7752d9fd/2020/omi/d%C3%ADa-1/OMI-2020-Mapas/solutions/es.markdown

Cuando se creó se desplegaba bien las soluciones, ahora ya no 

https://omegaup.com/arena/problem/OMI-2020-Mapas/#solution

## Contexto

El Coding Rush empieza este sábado. Ya nos habíamos adaptado a pasarles a los muchachos plantillas de código en el mismo markdown. 

## Tu ambiente

* VsCode

![image](https://user-images.githubusercontent.com/6314568/113952344-1f147b00-97db-11eb-8cad-89e8836aed37.png)

**Comment by lhchavez** [comment]
Cerrando en favor de https://github.com/omegaup/omegaup/issues/5316 porque ya está arreglado en producción y sólo falta agregar pruebas.
