### ISSUE TITLE
[BUG] El typeahead no encuentra todos los problemas, y no permite introducir uno directamente por alias

### ISSUE THREAD

**Issue by Juanito98** [omegaup/omegaup#5321]
## Comportamiento Esperado

Esperaba poder modificar el problema de un concurso pero no pude.

## Comportamiento Actual

Cambié el formato del validador de un problema y me hice bolas y cambié casos y al final me di cuenta que lo que no estaba pasando era que el problema en el concurso que ya había acabado no estaba jalando la última versión.

En teoría, la manera de actualizarlo es agregarlo de nuevo pero no me deja

![image](https://user-images.githubusercontent.com/6314568/114288777-a9591b00-9a37-11eb-866b-2723ebbef18b.png)

## Posible Solución

Agregar una opción de actualizar el problema a la última versión

## Pasos para reproducir (para bugs)

1. Este es el problema que ya actualicé bastante jaja https://omegaup.com/arena/problem/CR19-Calificaciones-de-Armando/
2. Este es el concurso que lo usa https://omegaup.com/arena/CR191/#problems
3. Le doy en editar concurso -> agregar problemas
4. Busco el problema que quiero actualizar, no lo encuentra.
5. Escribo el alias completo del problema que quiero actualizar 
5. No me deja

## Contexto

Afecta el score de los chicos del Coding Rush

## Tu ambiente

* Google Chrome Versión 89.0.4389.114 (Build oficial) (x86_64)
* MacOS
* Omegaup

**Comment by lhchavez** [comment]
@tvanessa @heduenas @pabo99 más señales de que Typeahead debe morir así como que ayer.

**Comment by pabo99** [comment]
Este es el typeahead que se acaba de implementar recientemente :( (y no creo que sea la causa de la falla que se reporta).

En este caso, no aparece intencionalmente: se están filtrando los problemas que ya fueron agregados al concurso. 

Había olvidado que se requiere que carguen para el caso de los que se pretenden editar. Pero también se me ocurre otra idea: agregar un botón de editar problema (en el pasado me suena a que ya existía), y de ese modo ya podríamos editar los problemas sin tener que buscarlos

**Comment by lhchavez** [comment]
va, el botón de editar me agrada! así se pre-poblan todos los campos para minimizar errores.

**Comment by pabo99** [comment]
Efectivamente, ese botón ya existía, pero se perdió en la migración a la plantilla unificada (acabo de ver que se quedó con las clases de glyphicon). Ya se arregló de cualquier forma en el PR #5326 .
