### ISSUE TITLE
[BUG] Falta contenido al clonar un curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#5356]
## Comportamiento Esperado

Al clonar un curso se copia todo el contenido.

## Comportamiento Actual

Al clonar un curso falta contenido. [Curso fuente](https://omegaup.com/course/RS/) [Curso clonado](https://omegaup.com/course/ResolviendoProblemas2021/) Se clonaron 3/4 tareas, falta el Problema 2.

![Problema la clonar un curso](https://user-images.githubusercontent.com/940007/116771605-bc8d5400-aa01-11eb-9b07-ac78b6f7f169.png)

![Problema la clonar un curso 2](https://user-images.githubusercontent.com/940007/116771604-bbf4bd80-aa01-11eb-8675-018e9b39288e.png)

**Comment by pabo99** [comment]
@npave, tienes más información que nos puedas proporcionar? 

Tal como si hay problemas privados, si se clonó desde la cuenta de un administrador o desde un usuario por medio de un token.

Es que no logro reproducirlo. Ya intenté esos casos, pero veo que en todos los intentos se ha clonado por completo

**Comment by npave** [comment]
@pabo99  Lo intenté de nuevo y obtuve el mismo error, continuando con el ejemplo que puse, solo se clonaron las tareas que tenían problemas. La tarea "Problema 2" no tenía problemas.

**Comment by pabo99** [comment]
Ahh, ese dato es relevante. Hago la prueba,  y si me falla, ya será más fácil corregirlo. 

De una vez probaré con lecturas, que creo que también faltaría cubrir

Muchas gracias por la info.
