### ISSUE TITLE
[BUG] Este perfil en particular se muestra en blanco

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#5359]
## Comportamiento Esperado

Al visitar el perfil https://omegaup.com/profile/PauloMB/ se debería de mostrar la información del usuario en cuestión.

## Comportamiento Actual

El perfil se muestra en blanco. Al parecer es un error del FE.
```
TypeError: Cannot read property 'contests' of undefined
TypeError: Cannot read property 'profileRank' of undefined
```

## Pasos para reproducir (para bugs)

1. Navegar a https://omegaup.com/profile/PauloMB/ 

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome
* Sistema Operativo y versión (escritorio o móvil): Windows
* Link al sitio en el que este problema pasa:  https://omegaup.com/profile/PauloMB/ 
* Captura de pantalla: 
![image](https://user-images.githubusercontent.com/684205/116795902-138c3b00-aa8d-11eb-86cc-2b7d6f7236ea.png)

**Comment by lhchavez** [comment]
tenemos más ejemplos: #5430
