### ISSUE TITLE
Race conditions en PHP

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#536]
Hay varios errores en New Relic que solo pueden ser explicados si consideramos race conditions que ocurren al hacer varios queries relacionados. Un ejemplo es en Scoreboard::RefreshScoreboardCache donde se queriean los usuarios, los problemas y luego los runs. Si un usuario manda un run en el inter, va a tener un run para un usuario que no conocemos.

Hay que ver dónde conviene poner transacciones para tener una vista consistente de la base de datos D:

**Comment by elendil326** [comment]
@lhchavez esto sigue ocurriendo?

**Comment by lhchavez** [comment]
posiblemente sí, pero la instancia que había identificado ya fue arreglada.

repro or didn't happen, supongo :P
