### ISSUE TITLE
[BUG] Miembros creados por identidades no se agregan a un grupo

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#5361]
## Comportamiento Esperado

Al subir un csv en la sección de `Crear identidades` en un grupo y obtener el mensaje de éxito, ver la lista de los miembros en ese grupo.

## Comportamiento Actual

La lista está vacía. Solo me pasa con el grupo `OMIP2021`.

## Pasos para reproducir (para bugs)

en https://omegaup.com/group/OMIP2021/edit/#identities
1. Tenía ese grupo ya con identidades creadas por medio de un csv.
2. luego las borré todas de una por una desde la vista de miembros.
3. ahora subo este archivo
https://gist.github.com/andreasantillana/13bbf96f71287d12bfe00d09cfff423a
4. Dar clic en `Crear identidades`.
5. Ir a la pestaña `Miembros`.

## Contexto

Estoy intentando crear los usuarios para la OMIP que es el sábado 😢 

## Tu ambiente

Esta fue la respuesta a la petición del `bulkCreate`
```
{"status":"ok","_id":"609206c259344743305763"}
```

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 90.0.4430.85 (Official Build) (x86_64)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2
* Link al sitio en el que este problema pasa: https://omegaup.com/group/OMIP2021/edit/
* Captura de pantalla:
![Screen Shot 2021-05-04 at 21 45 20](https://user-images.githubusercontent.com/5167417/117092073-ce813680-ad22-11eb-8708-73b82180862b.png)
![Screen Shot 2021-05-04 at 21 45 27](https://user-images.githubusercontent.com/5167417/117092077-d345ea80-ad22-11eb-85d1-49bb7c1e9599.png)

**Comment by lhchavez** [comment]
@pabo99 puedes atender esto mañana en cuanto empieces el día? urge bastante :S

**Comment by pabo99** [comment]
Entendido. Lo reviso con prioridad
