### ISSUE TITLE
[BUG] Cuando el caso de prueba es muy largo y de una sola línea, no hay un scroll

### ISSUE THREAD

**Issue by TachoMex** [omegaup/omegaup#5373]
## Comportamiento Esperado

Al poner un caso de prueba que es de una sola linea y la entrada y salida son muy grandes, no aparece un scroll horizontal, de modo que no es posible que se pueda visualizar el contenido del ejemplo de forma correcta. 

## Comportamiento Actual

No aparece el scroll

## Posible Solución

Podría ser que se añada un scroll horizontal al visualizar un problema en la vista de examen, pues cuando se visualiza el problema en la vista de problemas si es posible visualizar de forma correcta el problema. 

## Pasos para reproducir (para bugs)

1. Crear un problema con una entrada en una sola línea de unos 200 caracteres (o quizá más grande, depende la resolución del monitor). 
2. Poner este problema en un examen
3. Ver el problema dentro de la vista de examen

## Contexto

Al abrir el examen estatal, lo que hicimos para darle la vuelta fue añadir un caso de prueba más pequeño para que no se presentara el error y no atorar a los chicos, quizá podrían ver el bug si observan una versión anterior del problema Poema-sin-b

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Firefox 88.0.1
* Sistema Operativo y versión (escritorio o móvil): Ubuntu 20 Escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/OMIJAL-2021-PREPA-ESTATAL/#problems/Poema-sin-b
* Captura de pantalla:

![imagen](https://user-images.githubusercontent.com/4283840/117514552-be9f6780-af59-11eb-8569-b192551c7c36.png)

**Comment by heduenas** [comment]
Hay que ponerle `max-width` a la tabla que renderiza los casos. Me parece que eso generara scrolls horizontales cuando sea necesario
