### ISSUE TITLE
[FEATURE] No se tienen permisos para crear identidades

### ISSUE THREAD

**Issue by XanderWilde** [omegaup/omegaup#5376]
## Comportamiento Esperado

Agregar rápidamente múltiples identidades a un grupo. Las identidades no son usuarios reales y no necesitan tener un correo electrónico o validar su cuenta.

## Comportamiento Actual

No se puede subir identidades.
Marca (No tienes los permisos para realizar esa acción)

## Posible Solución
Sin posibles aportaciones de mi parte

## Pasos para reproducir (para bugs)

1. Creo identidades
2.  Subo formato .csv
3.  Me da acceso al nombre ejemplo: 

Nombre de usuario | Nombre | Contraseña | País / Región | Estado | Género | Escuela
Seleccion-COBAEV-OVI-2020:username-1 | Developer Dian | CVUrRuVQ | MX | VER | male | Best School
Seleccion-COBAEV-OVI-2020:username-2 | Danny Dev | uDHXYuha | MX | VER | male | Best School

4.  Sin acceso a crear usuarios

## Contexto

Sin poder crear identidades a la cual poder administrar 

## Tu ambiente

* Chrome 39 ( Versión 90.0.4430.93 (Build oficial) (32 bits) )
* Microsoft Windows y Windows 7. (escritorio):
* Link al sitio en el que este problema pasa: https://omegaup.com/group/Seleccion-COBAEV-OVI-2020/edit/#identities
* Captura de pantalla: 
![i](https://user-images.githubusercontent.com/82114901/117753569-501f0b80-b1de-11eb-8b30-9327c45fd2fe.png)

**Comment by tvanessa** [comment]
@XanderWilde puedes compartir tu nombre de usuario para poder dar permisos? Se puede enviar a engineering@omegaup.com

Gracias!

**Comment by XanderWilde** [comment]
Xander.Wilde
Mario Alberto Martinez Ulloa

**Comment by tvanessa** [comment]
Lo sentimos por tardar, el bug #5446 nos retraso para dar permisos.
Ya asignamos los permisos (:
