### ISSUE TITLE
[BUG] Error al volver público un problema mediante la lista de problemas.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5392]
Hola amigos de omegaUp.

Cuando intento hacer público el problema https://omegaup.com/arena/problem/2da-ccp-serpientes-escaleras/ mediante la lista de problemas, esto no funciona. Intenté hacer públicos dos problemas y curiosamente uno sí se pudo, pero éste no. En cambio, si lo intento hacer público desde dentro del problema entonces sí funciona (y lo puedo volver a poner privado para intentar reproducir el error descrito y sigue ocurriendo).

Lo que sale es lo siguiente:
```
Object
error: "Hubo un problema interno al momento de intentar actualizar el problema."
errorcode: 412
errorname: "problemDeployerInternalError"
header: "HTTP/1.1 412 PRECONDITION FAILED"
httpStatusCode: 412
status: "error"
_id: "609af568e13e5622148394"
```

---- Edit
Para reproducir este bug:
- Ir al menu donde aparece el username.
- Seleccionar "Mis problemas"
- Marcar algunos checkboxes
- Ir al dropdown "Para los items seleccionados"
- Seleccionar hacer públicos

**Comment by heduenas** [comment]
@darkmx puedes hacer a nuestro intern Luis (username `luis8`) admin de tu problema para que pueda investigar que esta pasando. Ni el ni yo logramos reproducir ese bug en nuestros problemas?

**Comment by darkmx** [comment]
Listo, ya lo agregué. No hay errores con otros problemas, pero ése todavía sigue con error (lo acabo de comprobar nuevamente: lo volví privado y luego lo intenté volver público desde la lista, sin éxito).

**Comment by heduenas** [comment]
Gracias por agregarlo!
