### ISSUE TITLE
[FEATURE] El puntaje global en cursos no es fácil de ver cuando tienen muchas tareas

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#5397]
Cuando tienes más de 5 tareas en un curso el puntaje global, que está hasta la derecha, queda escondido y no es fácil de visualizar.  Una propuesta es mover el puntaje global a la derecha del nombre del estudiante para que sea lo primero que se puede observar. 

![Progreso de estudiantes en cursos](https://user-images.githubusercontent.com/940007/118086795-5c8b9b80-b379-11eb-8f40-a14acafa5b6d.png)

**Comment by heduenas** [comment]
Resuelto via https://github.com/omegaup/omegaup/pull/5511
