### ISSUE TITLE
[FEATURE] En la tabla de progreso de los estudiantes el encabezado de la tabla y el nombre de usuario no debería desplazarse

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#5398]
En la tabla de progreso de los estudiantes el encabezado de la tabla y el nombre de usuario no debería desplazarse con las barritas de desplazamiento. Sugerencia, congelar primera columna y primera fila.

**Comment by pabo99** [comment]
Encontré la funcionalidad con `bootsrap-vue` para congelar encabezados y columnas: https://bootstrap-vue.org/docs/components/table#sticky-columns, podemos probar con esta tabla que tal funciona, para ver si comenzamos a migrar más tablas que tenemos.
