### ISSUE TITLE
Agregar una opción para mantener la cookie con el auth token al hacer login

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#540]
Actualmente cuando se hace login, la galleta solo sobrevive la sesión actual, no persiste como antes solía hacer (aunque el efecto neto es casi el mismo porque antes expiraba a las 8 horas). Hay que exponer una manera UIosa de que se guarde foreveranever.

**Comment by elendil326** [comment]
@lhchavez esto sigue siendo un issue?

**Comment by lhchavez** [comment]
no
