### ISSUE TITLE
Solicutud para crear identidades

### ISSUE THREAD

**Issue by josuegregorio** [omegaup/omegaup#5401]
Hola, soy Josué Aguilar, profesor de la Universidad Anáhuac Oaxaca, voy a generar algunos concursos en la plataforma y me sería muy útil la funcionalidad de crear identidades. Espero que por este medio se pueda hacer dicha petición. 
Gracias de antemano y quedo en espera de su respuesta.

Usuario: josuegag

Saludos.

**Comment by tvanessa** [comment]
Ya estás agregado. Nos avisas si vuelves a tener problemas.

**Comment by josuegregorio** [comment]
Hola, me sigue apareciendo que no tengo permisos. "No tienes los permisos para realizar esa acción"

**Comment by tvanessa** [comment]
Hola. Ya volvimos a darte acceso, esperemos que esta vez funcione.
Estamos al pendiente si hay más incovenientes

**Comment by josuegregorio** [comment]
Logro ver las cuentas y passwords que se generan al subir el archivo csv, incluso descargar el archivo con las cuentas, pero al presionar el botón de generar identidades me vuelve a aparecer que no tengo permisos.

**Comment by Apocryphon-X** [comment]
Me pasa lo mismo @tvanessa
