### ISSUE TITLE
[BUG] Si un problema tiene un alias de más de 32 caracteres, se guarda una versión truncada del alias que no permite encontrarlo después

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#5402]
## Comportamiento Esperado

Cuando le doy clic a un problema mío, ver el problema.
Cuando le doy clic a editar un problema mío, poder editar el problema.

## Comportamiento Actual

Me regresa una pantalla de 404.

https://omegaup.com/arena/problem/pes-2021-may-olimpiada-multidisc/
https://omegaup.com/problem/pes-2021-may-olimpiada-multidisc/edit/

## Pasos para reproducir (para bugs)

1. Ir a la lista de mis problemas https://omegaup.com/problem/mine/
2. Darle clic al problema 

## Contexto

Es un problema creado para el selectivo final para escoger a los IOIs, es la próxima semana.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 90.0.4430.85 (Official Build) (x86_64)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2
* Link al sitio en el que este problema pasa: 
  * https://omegaup.com/arena/problem/pes-2021-may-olimpiada-multidisc/
  * https://omegaup.com/problem/pes-2021-may-olimpiada-multidisc/edit/
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5167417/118202284-3587a500-b41f-11eb-9ab1-2dc05ddec43f.png)
![image](https://user-images.githubusercontent.com/5167417/118202316-43d5c100-b41f-11eb-830f-944c2715387f.png)

**Comment by tvanessa** [comment]
No he podido reproducirlo con mis problemas públicos ni privados.
Tienes más información?
El problema se subió con tu cuenta o eres admin con alguien más?

**Comment by andreasantillana** [comment]
> No he podido reproducirlo con mis problemas públicos ni privados.
> Tienes más información?
> El problema se subió con tu cuenta o eres admin con alguien más?

Solo pasa con ese problema. El problema lo subió https://omegaup.com/profile/cesar/ y a él le pasa y desde la cuenta de https://omegaup.com/profile/pacharrin (que es admin) también pasa.

**Comment by andreasantillana** [comment]
Usé el mismo zip para crear otro problema y se ve bien. Como que algo quedó corrupto solo para este problema específico.

**Comment by lhchavez** [comment]
efectivamente, los archivos del problema pes-2021-may-olimpiada-multidisc no existen. _pero_ los de pes-2021-may-olimpiada-multidisciplinaria sí existen y parece que se crearon casi al mismo tiempo. (aunque no veo en ningún lugar en los logs la creación de pes-2021-may-olimpiada-multidisc)

**Comment by lhchavez** [comment]
..... OH! ya entendí el problema! no se validó que el alias fuera de menos de 32 caracteres, así que mysql amigablemente truncó el alias del problema a 32 caracteres al momento de guardarlo.

ya le cambié el nombre al archivo para que se encontrara y apagar el fuego inmediato, _pero_ hay que agregar validación de longitud.

**Comment by andreasantillana** [comment]
Gracias!!!

**Comment by darkmx** [comment]
Hola amigos, una pregunta.

Inadvertidamente me topé con este bug (afortunadamente ya había leído el issue y supe la causa, pero ya era tarde). Cuando se corrija el bug, ¿se arreglarán los problemas? Puedo esperar a que arreglen el issue (de hecho, el problema se quedó privado y además lo iba a borrar), pero corregir el issue en lo general posiblemente requiera un datafix que no sé si implementarán (digamos, si los problemas afectados son _muy_ pocos, hasta se podría hacer a mano y no programar el datafix, pero de ahí surge mi pregunta, porque quiero deshacerme del problema afectado y no quiero que se quede para la posteridad).

El problema en cuestión es https://omegaup.com/arena/problem/Sumatoria-de-sumatorias-duplicad/
