### ISSUE TITLE
Error al ver Perfil  / usuario sin clasificación 

### ISSUE THREAD

**Issue by franz96521** [omegaup/omegaup#5430]
## Comportamiento Esperado
poder ver mi perfil desde otras cuentas o desde el ranking global, parece que mi perfil fue borrado, pero desde la cuenta puedo ver y continuar mandando problemas 

## Comportamiento Actual
el perfil al cargar desde una cuenta secundaria se queda en banco la pagina 
imagen desde otra cuenta:
![Screenshot from 2021-05-22 15-12-18](https://user-images.githubusercontent.com/44103131/119239651-2506b700-bb10-11eb-8814-af3e554775f1.png)

imagen desde mi cuenta 
![Screenshot from 2021-05-22 15-11-17](https://user-images.githubusercontent.com/44103131/119239634-09031580-bb10-11eb-896f-4631fde76021.png)

## Pasos para reproducir (para bugs)
en https://omegaup.com/rank/ buscar el perfil Franz96521  
o ir directamente https://omegaup.com/profile/Franz96521 

## Contexto
Tratando de ver mi perfil desde una cuenta secundaria me di cuenta que es imposible y no aparezco en ranking. Además de eso mi perfil desde mi cuenta principal aparece en Rankin “sin clasificación“ teniendo más de 280 problemas resueltos, y datos personales  

en fecha de graduación “Invalid Date” 

## Tu ambiente
* chrome Version 90.0.4430.212 (Official Build) (64-bit)
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/

**Comment by lhchavez** [comment]
Dupe de #5359
