### ISSUE TITLE
Algunos bugs detectados durante CIIC 2021

### ISSUE THREAD

**Issue by ghost** [omegaup/omegaup#5435]
## Comportamiento Actual
Cuando intentaba hacer mi segundo envío al problema https://omegaup.com/arena/ciic-2021/#problems/ping-pong
del concurso https://omegaup.com/arena/ciic-2021/#problems, la página me informó que debía esperar alrededor de 3600s, lo cual pienso que fue un bug.

Lo mismo me paso entre cada envío de cada problema.

## Comportamiento Esperado
Era mi primera experiencia en una CIIC, no sabía cual era el tiempo oficial de espera entre un envío y otro al mismo problema, pero participantes de años pasados me habían comentado que era 60s, no la cifra que me arrojó la página.

## Contexto
-Ocurrió durante una olimpiada (CIIC 2021), mi primera y última participación en un evento de este tipo.
-Entorpeció que pudiera probar distintas soluciones al mismo problema rápidamente ya que debía esperar 1h entre cada una.

## Ambiente

*Navegador: Mozilla Firefox, no tengo conocimiento de que versión era, puesto que no fui quien instaló los programas en la PC usada para la Olimpiada.
*Sistema Operativo: Windows 10
*Link a donde ocurrió el problema: https://omegaup.com/arena/ciic-2021/#problems

## Comportamiento Actual
En la página el tiempo restante de concurso que se me mostraba tenía 1h de más.

## Comportamiento Esperado
Que mostrase el tiempo correctamente.

## Pasos para reproducir ambos bugs
-Tener la hora de la PC mal configurada.

Creo que esta fue la posible causa a ambos bugs, debido a que la hora de la PC usada tenía 1h de atraso, puede que el tiempo entre envíos 60s se haya multiplicado por 60 al haber 1h de atraso(60 min), resultando en los 3600s que me mostró la página entre cada envío y en el tiempo restante incorrecto.

## Posible Solución al Bug#1
Se que la mala configuración de la hora no depende de ustedes, pero mi sugerencia es que modifiquen el algoritmo de como se calcula este tiempo, no me parece que lo esté haciendo de la manera correcta.

## Posible Solución al Bug#2
Modificar el algoritmo de como se calcula el tiempo restante, por las mismas razones de arriba.

**Comment by tvanessa** [comment]
Duplicado de #3839
