### ISSUE TITLE
[BUG] Cuando se intenta agregar un rol a un usuario que ya lo tiene, sale un error no-inteligible

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5450]
Cuando asigno permisos a un usuario que ya los tiene me muestra el error: "Oops. I've encountered an internal error. Please try again."

![Screen Shot 2021-06-02 at 3 01 44 PM](https://user-images.githubusercontent.com/13296248/120617232-c34b2480-c40e-11eb-9f50-423db180b373.png)

### Pasos para reproducir
 - Entrar a admin/user/username
 - Seleccionar un checkbox para un permiso que ya se tiene

Notas:
 - No lo pude reproducir en sandbox
 - Cuando refresco la página se limpian los checkboxes.

### Contexto
Es importante dar permisos a docentes para crear identidades.

**Comment by pabloaguilar** [comment]
A mi tambien me pasa. Pero me pasa solo con ciertos usuarios. En particular, ya me puedo modificar mis propios permisos pero no puedo modificar los permisos de @npave

**Comment by lhchavez** [comment]
pueden intentar reportar el bug desde la página _o_ buscar los errores que salen en la consola de JS _o_ buscar los payloads completos al api que fallan con 500? eso debería ayudar a encontrar los request ids para saber qué falló.

**Comment by pabloaguilar** [comment]
Ya no sé dónde quedó el botón de mandar feedback /shamecube

Pero tengo esto en la consola de JS:
```
error: "Oops. I've encountered an internal error. Please try again."
​
errorcode: 400
​
errorname: "Failed to query MySQL (1062): Duplicate entry '4-7-1' for key 'User_Roles.PRIMARY'"
​
header: "HTTP/1.1 400 Bad Request"
​
httpStatusCode: 400
​
status: "error"
```

**Comment by lhchavez** [comment]
ah! eso es indicación de que ya tiene el rol, tons hay que mostrar el error de manera bonita para que todo sea WAI

**Comment by pabloaguilar** [comment]
Pero a diferencia de otros usuarios, que se muestran con checkboxes marcadas, este usuario siempre sale vacío por más que le agregue permisos.
