### ISSUE TITLE
[BUG] Link de Discord no valido en el apartado de redes sociales

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5472]
## Comportamiento Esperado

Obtener el enlace de invitación al servidor de Discord cuando se da click en la zona de contacto.
![image](https://user-images.githubusercontent.com/40130428/121819300-e74e0780-cc51-11eb-84bb-54553be81a6c.png)

## Comportamiento Actual

Se obtiene un link que no permite acceder al servidor.
![image](https://user-images.githubusercontent.com/40130428/121819318-03ea3f80-cc52-11eb-9f84-2cd2e25ef342.png)

## Posible Solución

Modificar la linea 98 del archivo  [Footerv2.vue](https://github.com/pabloaguilar/omegaup/blob/441a2cfcfca3df9c0489198a5c33c6486fb16ee1/frontend/www/js/omegaup/components/common/Footerv2.vue#L98) de modo que en su lugar tenga el siguiente link de invitación: https://discord.gg/K3JFd9d3wk

![image](https://user-images.githubusercontent.com/40130428/121819585-7c053500-cc53-11eb-947d-cbf9b995b5dd.png)

**Comment by lhchavez** [comment]
se acepta ese parche como PR!

**Comment by Apocryphon-X** [comment]
Excelente, enseguida hago un PR
