### ISSUE TITLE
[FEATURE] Agregar al carrusel información para el curso "Resolviendo problemas en omegaUp"

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5477]
Título: Resuelve un problema nuevo cada semana
Descripción: Únete al curso "Resolviendo problemas en omegaUp", aprende tips sobre concursos de programación y gana premios. 
________ EN
Título: Solve a new problem every week
Descripción: Enroll in the "Solving problems in omegaUp" course, learn tips about programming contests and earn prizes.
________ PT
Título: Resolva um novo problema a cada semana
Descripción: Inscreva-se no curso "Resolvendo problemas no omegaUp", aprenda dicas sobre concursos de programação e ganhe prêmios

Link: https://omegaup.com/course/ResolviendoProblemas2021/
Imagen: 
![undraw_Process_re_gws7](https://user-images.githubusercontent.com/13296248/121958246-52faa800-cd18-11eb-9bb6-2f56b8cfcf3e.png)

@npave nos puedes ayudar confirmando el titulo y descripción corta?

**Comment by tvanessa** [comment]
@egessel si necesitas el archivo svg para la imagen lo puedes encontrar aqui: https://undraw.co/search
La imagen se llama "process"

El color de nuestra paleta es #5588DD (o puedes probar con #FFDD00). [Ver todos los colores](https://github.com/omegaup/media)

**Comment by npave** [comment]
@tvanessa @egessel  me parece bien el titulo y descripción. ¿Podemos utilizar la siguiente imagen por favor?

![Recurso 1](https://user-images.githubusercontent.com/940007/122865254-edd82100-d2da-11eb-8479-33dfcdc49ad5.png)
