### ISSUE TITLE
[FEATURE] Como creador de problemas, me gustaría que se pudiesen centrar imágenes en la redacción

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5486]
## Comportamiento Esperado

Agregar imágenes centradas a la redacción de un problema.

## Comportamiento Actual

No existe manera de centrar imágenes en las redacciones de los problemas.

## Posible Solución

Habilitar el uso de `<p style="text-align:center;">...</p>` en la redacción de los problemas.

**Comment by lhchavez** [comment]
eso ya se puede!

```markdown

![lhchavez](https://secure.gravatar.com/avatar/5728f55219cafd349bfa2c708992e7f3?s=51 "hello")

```

(léase: pon la imagen solita en un párrafo y ponle un caption).

jamás vamos a permitir el uso de `style` porque eso es una [vulnerabilidad](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/05-Testing_for_CSS_Injection).

**Comment by Apocryphon-X** [comment]
Genial! No sabia que se podía. He intentado de muchas maneras pero no he probado esa; en cuanto al style no sabia que era una vulnerabilidad. Gracias por el feedback!
