### ISSUE TITLE
[FEATURE] Como un organizador de concursos, quiero poder usar la metodología de evaluación de la IOI para ser consistente con esos concursos

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#5533]
## Comportamiento Esperado

omegaUp, como plataforma oficial de la Olimpiada Mexicana de Informática (y también donde se han realizado las últimas CIIC) debería de soportar la metodología de [evaluación de la IOI](https://ioi2017.org/contest/rules/#feedback) en concursos configurados de esa manera:

> The final score for each subtask will be the maximum score of this subtask across all submissions. The score for each task will be sum of scores for its subtasks. (For example, consider a contestant who made two submissions on a task that contains two subtasks. First submitted solution got 30 points for the first subtask and 10 points for the second subtask, second solution got 0 points for the first subtask and 40 points for the second subtask, then the final score for this task will be 70.)

Al final, se suman los puntajes de los subtasks y ese es el puntaje para ese concurso. Esto es un poco distinto a las otras metodologías de evaluación donde sólo se obtiene el máximo de los puntajes para cada problema, porque ahora se tienen que considerar las subtareas también.

## Comportamiento Actual

Esto no se soporta porque la tabla de envíos no tiene información sobre las subtareas.

### Opción 1: Require cambios a la base de datos

* Crear una tabla `Subtasks` (relación N:1 con `Runs`), con campos para el `run_id`, `name`, `score`, `verdict` (y quizás `runtime`, `memory`, etc.).
* Para cada grupo de casos, quark debería crear un registro en esta tabla además del registo en `Runs`.
* Los concursos configurados con las reglas de la IOI, para cada problema necesitarían hacer un `INNER JOIN` adicional para obtener el máximo de cada subtarea y luego sumarlos todos, en vez de sólo obtener el máximo para cada problema.
* Los envíos existentes necesitarían leer el `details.json` y crear todos los registros `Subtasks` históricos.

### Opción 2: No requiere cambios a la base de datos

* Para los concursos con las reglas de la IOI, crear un pipeline de RabbitMQ que genere el scoreboard a partir de los `details.json` de todos los envíos cada cierto tiempo.

## Alternativas consideradas

(Ver las dos opciones arriba).

## Contexto

Ya van varias veces que nos piden esto.

**Comment by kishtarn555** [comment]
Similar a: https://github.com/omegaup/omegaup/issues/2911

**Comment by lhchavez** [comment]
No es similar, es lo mismo! Cerrando como duplicado.
