### ISSUE TITLE
[BUG] No se puede editar nada en un concurso

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#5557]
Al intentar editar un concurso, no se aplica ningún cambio:

![UpdateContestFailure](https://user-images.githubusercontent.com/3230352/127070949-15445421-030f-4302-a3d4-d85d07b8e9fd.gif)

Agregar prueba para evitar futura regresión

**Comment by Apocryphon-X** [comment]
El fix de este issue ya fue agregado a OmegaUp o aun no se a incorporado? Estoy tratando de editar la fecha de fin de un concurso y el valor no se actualiza apesar de dar click en "Actualizar Concurso" @pabo99

**Comment by pabo99** [comment]
El deploy se hará hasta el día sábado por la tarde.
