### ISSUE TITLE
[FEATURE] Actualizar cadenas de la vista del coder del mes

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5593]
En español la cadena dice: "Lista de apirantes a coder del mes"
Corregir el typo

![Screen Shot 2021-08-09 at 12 28 02 PM](https://user-images.githubusercontent.com/13296248/128762972-d74796f7-cfe1-4060-9ee3-90395b65ff5d.png)

**Comment by erwaen** [comment]
Hice un pull request resolviendo este typo.

**Comment by lhchavez** [comment]
Arreglado por https://github.com/omegaup/omegaup/pull/5597
