### ISSUE TITLE
Filtro de lenguajes por concurso

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#561]
Por ejemplo, si se tiene un concurso tipo OMI, poder limitar los lenguajes a los oficiales.

**Comment by elendil326** [comment]
TODO: @lhchavez a especificar que falta después del commit [40fede8](https://github.com/omegaup/omegaup/commit/40fede853bb89c8327c498d01ba153a24ea5d307)

**Comment by lhchavez** [comment]
Falta hacer la interfaz: que cuando se cree un concurso se pueda elegir un subset de problemas (con un dropdown https://getbootstrap.com/docs/3.3/components/#btn-dropdowns y checkboxes).

**Comment by elendil326** [comment]
@lhchavez te refieres a la interfaz para elegir un subset de problemas o un subset de lenguajes?

**Comment by pabo99** [comment]
@lhchavez @npave esta es la propuesta con respecto a la interfaz de los lenguajes para concursos:

![captura de pantalla 2017-11-02 a la s 08 56 15](https://user-images.githubusercontent.com/3230352/32332768-5142ce04-bfb4-11e7-89ed-91631ea0c614.png)

¿Que les parece?

**Comment by npave** [comment]
Me parece bien.
