### ISSUE TITLE
[FEATURE] Quitar la tabla de detalles en *cursos públicos*

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5612]
La tabla no da información relevante pues los cursos públicos son de duración ilimitada y se pueden comenzar en cualquier momento

![Screen Shot 2021-08-12 at 3 36 30 PM](https://user-images.githubusercontent.com/13296248/129278691-d696f10c-623c-49aa-8766-f6f12bfbe550.png)

**Comment by carlosabcs** [comment]
Ya nada más falta que me aprueben [un PR](https://github.com/omegaup/omegaup/pull/5601) para cambiar a la versión en BS4 de ArenaCourse. Está mal si solo hago el cambio en esa versión? Es que los cambios para la versión antigua (la de la imagen) son un poco más complejos.
