### ISSUE TITLE
[FEATURE] Cursos UI: Componente para los tabs

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5630]
Como se propone en el diseño de Nancy
![Screen Shot 2021-08-18 at 11 17 57 AM](https://user-images.githubusercontent.com/13296248/129951920-3fc32b51-8f73-43d9-a09c-0ddec0ee75ee.png)

**Comment by carlosabcs** [comment]
@tvanessa @npave, por fa, aclárenme esta parte, específicamente este campo de qué tipo sería? `varchar(tamaño_n)` o un `tinytext `(como la descripción del curso)? Y se rellenaría en un `textarea`?
