### ISSUE TITLE
[FEATURE] Ocultar botón de login con facebook

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5638]
Se desactivó el inicio de sesión con FB porque no se actualizaron las políticas de datos.

Mientras se arregla eso, ocultar el botón de facebook que se muestra en [omegaup.com/login](omegaup.com/login)

**Comment by TsukiZombina** [comment]
¿Podrían reactivar el botón de inicio de sesión con Facebook? ¿O compartir un enlace por aquí para inicio de sesión con Facebook? Ya que era mi único medio para iniciar sesión a OmegaUp. En #2157 les comentaba que no podía crear contraseña para iniciar sesión si necesidad de Facebook y hasta el momento permanece abierto, por lo que no tengo forma de acceder.

**Comment by samdsmx** [comment]
@tvanessa como podemos ayudar a esta usuaria? Podrían recuperar su cuenta de forma manual?

**Comment by tvanessa** [comment]
Seguimos bloqueados por las políticas de datos

**Comment by TsukiZombina** [comment]
No requiero entrar específicamente con Facebook, solo quiero poder usar mi cuenta de nuevo, poder crear una contraseña como les comentaba en #2157, me parece la mejor opción.

**Comment by heduenas** [comment]
@TsukiZombina puedes intentar con el formulario de "recuperar contraseña"? https://omegaup.com/login/password/recover/
Después de ponerle tu dirección de correo que usabas para facebook debería de llegarte una liga para crear tu contraseña.

cc @MiguelRomero para futuras instancias de este problema.

@samdsmx el equipo de ingeniería no es el encargado de estipular politicas de privacidad. Estamos trabajando con Joe para ver quién puede ayudarnos con eso.

**Comment by TsukiZombina** [comment]
@heduenas @MiguelRomero ya lo he hecho y ese método no me permite obtener una contraseña, devuelve el mensaje de error `Usuario no verificado.`
No deseo que modifique sus políticas de privacidad, solo que de alguna manera pueda tener una contraseña para ingresar, incluso podría ser aceptar se me asignara una contraseña temporal.

**Comment by pabloaguilar** [comment]
Creo que podríamos ayudar verificando si usuario en el panel de admin y de ahí que @TsukiZombina utilice la forma de recuperar contraseña

**Comment by samdsmx** [comment]
Gracias Pablo! La cuenta fue verifica desde el panel de admin, para que pudieran recuperar la contraseña, y funciono satisfactoriamente.  Dejare el comentario sobre este workaround en el issue #2157
