### ISSUE TITLE
[BUG] 400 Al crear identidades en un grupo 

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#5656]
## Comportamiento Esperado

Al agregar un csv para crear identidades para el grupo https://omegaup.com/group/OMI-2021/edit/#identities
espero que se creen correctamente las identidades.

## Comportamiento Actual

```
error: "Oops. I've encountered an internal error. Please try again."
errorcode: 400
errorname: "Failed to query MySQL (1062): Duplicate entry 'Centro de Bachillerato TecnolÃ³gico Industrial y d-MX-AGU' for key 'Schools.name_country_id_state_id'"
header: "HTTP/1.1 400 Bad Request"
status: "error"
_id: "612cfb21f0f99533318757"
```

## Posible Solución

El encoding del archivo que me mandaron está terrible, no sé si eso pueda afectar 

## Pasos para reproducir (para bugs)

1.  Ir al grupo https://omegaup.com/group/OMI-2021/edit/#identities
2. Adjuntar un archivo específico de nombres (se los puedo mandar por slack)
3. Guardar identidades

## Contexto

Estoy ayudando a crear los usuarios para la OMI (creo que es este fin de semana)

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):  Chrome Version 92.0.4515.159 (Official Build) (x86_64)
* Sistema Operativo y versión (escritorio o móvil): macOS Catalina 10.15.2
* Link al sitio en el que este problema pasa: https://omegaup.com/group/OMI-2021/edit/#identities
* Captura de pantalla: 
![image](https://user-images.githubusercontent.com/5167417/131366762-08f7beca-3640-4f43-a34a-5f6219275fe5.png)

**Comment by pabo99** [comment]
@andreasantillana, sería de mucha utilidad si nos mandas el archivo .csv que estás intentando subir.

En caso de que vengan nombres de usuarios reales, los puedes sustituir por nombres inventados, finalmente el problema que veo se presenta en el nombre de la escuela y/o estado/país.
