### ISSUE TITLE
[BUG] OmegaUp no permite elegir septiembre (y otros meses) como fechas de inicio y fin de un concurso

### ISSUE THREAD

**Issue by ccepeda** [omegaup/omegaup#5663]
## Comportamiento Esperado

Al crear un concurso, se espera que OmegaUp permita elegir cualquier fecha válida como inicio o fin del mismo.

## Comportamiento Actual

OmegaUp no permite elegir septiembre ni otros meses como febrero, abril, etc como inicio o fin de un concurso.

## Pasos para reproducir (para bugs)

1. Crear un concurso.
2. En la página de alta o edición intentar crear un concurso con fechas de distintos meses.
3. OmegaUp cambia el mes.

Ignoro si siempre permite utilizar el mes actual.

## Contexto

Este bug está afectando actualmente para la creación de los exámenes de la fase nacional de la Olimpiada Mexicana de Informática que se llevará a cabo el 4 y 5 de septiembre.

## Tu ambiente

* Chrome Versión 92.0.4515.159 (Build oficial) (64 bits)
* Se anexa video de captura de pantalla.

https://user-images.githubusercontent.com/20668726/131523787-40de90c9-3953-4504-a437-c6043bae77f7.mp4

**Comment by tvanessa** [comment]
): este es un error del date-picker que pasa el último día de **algunos** meses. Mañana que ya sea septiembre se van a poder elegir las fechas correctas. Otra alternativa llamar directamente a la API para crearlo.
Si esto es un inconveniente podemos escalarlo más. Avísenos si es suficiente esperar a mañana.

**Comment by ccepeda** [comment]
Sí, puedo esperar a mañana sin problema. Gracias!

**Comment by lhchavez** [comment]
Hay que arreglar esto antes de que vuelva a pasar.

**Comment by Apocryphon-X** [comment]
Relacionado con: #5298

**Comment by lhchavez** [comment]
Cerrando como duplicado
