### ISSUE TITLE
[BUG] No se pueden ver las estadísticas en vivo de un concurso

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#5681]
## Comportamiento Esperado

Poder visualizar las estadísticas en vivo de la OMI 2021.

## Comportamiento Actual

Al dar click en el botón de estadísticas me redirige a la pagina correcta pero solo se muestra en blanco.
![image](https://user-images.githubusercontent.com/40130428/132101388-3d67d66d-782f-496d-a22d-9259a8a65df1.png)
![image](https://user-images.githubusercontent.com/40130428/132101411-e1822eb3-b611-4870-a5e5-00317cee4628.png)

## Pasos para reproducir (para bugs)

1.  Acceder a OmegaUp.
2. Ingresar al link de estadisticas en un concurso.

**Comment by pabo99** [comment]
¿Puedes mostrarnos el mensaje de error que te aparece en la consola de desarrollador ahí en el navegador? Es que parece ser que no sucede con todos los concursos.
![image](https://user-images.githubusercontent.com/3230352/132103013-c39e840c-6318-498c-8878-79a6c5185148.png)

**Comment by Apocryphon-X** [comment]
Cierro issue, al parecer las estadisticas estaban siendo bloqueadas por un AdBlocker! Gracias por el feedback
