### ISSUE TITLE
[FEATURE] Agregar el logo de Amazon a nuestro landing page por 1 año

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#5699]
## Comportamiento Esperado

Mostrar el logo de Amazon en nuestro landing page por 1 año (al menos) de acuerdo a nuestro [sponsorship package](http://omegaup.org/eventos/omegaup-gala-2021/assets/files/SponsorshipV4.pdf).

En particular el wording es: `Recognition on omegaUp Educational Platform landing page for one full year`

![image](https://user-images.githubusercontent.com/684205/133005056-81e09b7b-e7e5-4092-bb07-7f648be4f89c.png)

## Comportamiento Actual

Logo de Amazon no se muestra.

## Posible Solución

Usar el logo de Amazon de https://press.aboutamazon.com/images-videos

Usar un wording como el de los supporters of sitios como codefoces: `Supported by: ...`

Para preguntas y comentarios usar Slack #equipo_fundraising o fundraising@omegaup.com.

**Comment by Apocryphon-X** [comment]
Estaba leyendo el documento y menciona que hay un curso de Java pero no lo encontré en la sección de cursos en OmegaUp 🤔

**Comment by rcxr** [comment]
# Ideas

## Opción A
![image](https://user-images.githubusercontent.com/684205/133004897-bf3f3ddf-7b90-46ac-be71-01eae19e3bc0.png)

## Opción B
![image](https://user-images.githubusercontent.com/684205/133004977-bbfd543b-a0d7-4fe0-8510-d5456864db74.png)

# Mejoras

## Usar separador

Separar la sección de supporters de la sección de "Compite", "Train", "Create", etc., con un banner sólido. ¿tal vez con otra anécdota de un usuario como la de Mariola?

## Agregar logo al pie de la página

Agregar un logo (tal vez monocromático) al pie de nuestra página con un título "Supporters" y que esté siempre visible

![image](https://user-images.githubusercontent.com/684205/133005034-e7f48983-59e7-4e59-8bf6-d0603a1a4458.png)
