### ISSUE TITLE
[FEATURE] Integrar una herramienta para las pruebas de selenium

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5702]
Se necesita poder ver todo el flujo de clicks/vistas de Selenium en la interfaz. Se sugirió usar https://www.cypress.io/
Nos gustaría que se pudiera integrar a github actions.

La falta de esta herramienta retrasa el lanzamiento de nuevos features.

**Comment by lhchavez** [comment]
https://github.com/omegaup/omegaup/pull/5700 debería aguantarnos un rato más.
