### ISSUE TITLE
[FEATURE] Añadir el tag de "métodos numéricos" en el repositorio de tags.

### ISSUE THREAD

**Issue by danielramosl** [omegaup/omegaup#5731]
Añadir el tag de "métodos numéricos" en el repositorio de tags.

## Comportamiento Esperado

Poder tener una forma más fácil de encontrar problemas de métodos numéricos en el buscador.

## Comportamiento Actual

No existe un tag para métodos numéricos, a la hora de crear problemas los tags más parecidos es el de "funciones" y el de "cálculos aritméticos" algo completamente distinto a un problema sobre métodos numéricos.

## Contexto

Estoy creando varios problemas sobre métodos numéricos pero no puedo ponerles un tag adecuado para que más personas puedan buscar problemas de este tipo.

## Tu ambiente

![image](https://user-images.githubusercontent.com/91300869/134610711-7df4f9f4-3d76-46b9-994b-47bf05774548.png)

**Comment by darkmx** [comment]
+1, ya hay varios problemas nuevos que caen en ese tag y que no podrían clasificarse correctamente con tags preexistentes
