### ISSUE TITLE
Permitir agregar un nombre a desplegar a cada usuario en un concurso

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#581]
Posiblemente esto permita hacer que concursos como la OMI y los de las escuelas ya no tengan que permanentemente cambiar los nombres de las personas. Entonces podrían reciclar todos los usuarios sin tener que andar metiendo prefijos Y los scoreboards se mostrarían hermosos por siempre.

**Comment by elendil326** [comment]
Esto se escucha relacionado a #578 @lhchavez es esto un dupe?

**Comment by lhchavez** [comment]
Supercedido por el refactor de identidad
