### ISSUE TITLE
[BUG] No es posible abrir problemas en la plataforma

### ISSUE THREAD

**Issue by 5an7y** [omegaup/omegaup#5852]
## Comportamiento Esperado

Intentar acceder a los problemas o crear un problema en OmegaUp.

## Comportamiento Actual

La pagina dice que no fue encontrada.

## Pasos para reproducir (para bugs)

1.  Intentar abrir un problema en OmegaUp

## Contexto

Varios usuarios estan siendo afectados. Los reportes vienen por el canal de Discord.

## Tu ambiente

* Nombre del navegador : Google Chrome
* Sistema Operativo y versión (escritorio o móvil) : Windows 10
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/Area-y-perimetro-de-triangulo-re/ (por ejemplo)
* Captura de pantalla:

![image](https://user-images.githubusercontent.com/34700620/137774795-c270f80c-1002-4a3a-92ad-d71c037f9da8.png)

**Comment by heduenas** [comment]
Veo que este issue ya no se reproduce. Voy a cerrarlo.
