### ISSUE TITLE
[FEATURE] En un curso, mostrar un valor numérico en la barra de progreso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5900]
Hola amigos de omegaUp.

En cursos, esta barra de progreso

![image](https://user-images.githubusercontent.com/19719969/139070370-0f8925fe-5b9d-498d-bc08-5f0ea175871e.png)
no muestra información suficiente a los alumnos, porque los deja reflexionando sobre "qué tanto es tantito". Un alumno incluso se puso a medir para estimar su porcentaje de avance en el curso. 

Dado que el porcentaje se debe calcular para dibujar la barra, no estaría de más ponerlo. En el "progreso de los estudiantes" también aparece un puntaje; tampoco estaría de más ponerlo, por consistencia.

**Comment by tvanessa** [comment]
Esta es mi propuesta para acomodarlos

![Screen Shot 2021-11-01 at 2 08 23 PM](https://user-images.githubusercontent.com/13296248/139742407-882734bc-d220-42f4-b06c-e8c447c88af0.png)

**Comment by darkmx** [comment]
Se ve bonito. A mí me parece que el porcentaje basta, pero a Francisco Zaragoza (que fue quien me reportó el issue) le parece que también habría que agregar el puntaje, ya que el puntaje global se reporta tanto en % como en puntaje.

![image](https://user-images.githubusercontent.com/19719969/139759962-4d6a9898-e213-4d93-ad71-5cf845759d10.png)

**Comment by carlosabcs** [comment]
No me había fijado en sus comentarios... Ahorita lo tengo como se usa en Boostrap4 (dentro de la misma barra de progreso): 
![image](https://user-images.githubusercontent.com/20785082/140068533-0e1d938d-1a38-4f77-8f9b-06bf42fbdb9b.png)

¿Qué les parece?

**Comment by darkmx** [comment]
Otra razón (muy buena, de parte de Francisco): a los cursos de clases reales normalmente se les van incorporando las actividades poco a poco; si al alumno sólo se muestra el porcentaje, entonces éste podría tener 100% en un momento y 50% en otro, confundiéndolo. En cambio, el puntaje es algo que nunca debería bajar (y como el alumno nunca perdería puntos, el cambio repentino del porcentaje no debería espantarlo demasiado).

**Comment by tvanessa** [comment]
Esta es otra propuesta, dejando el porcentaje como lo usa bootstrap4:

![Screen Shot 2021-11-03 at 9 45 40 PM](https://user-images.githubusercontent.com/13296248/140259530-764d3ffb-7539-4936-8f26-59f537f7328d.png)

**Comment by darkmx** [comment]
Se ve súper bien.
