### ISSUE TITLE
[BUG] Como admin de un concurso, me aparece un "x" en un problema que no he intentado.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5901]
Hola amigos de omegaUp.

Estoy cuidando un concurso (que de hecho es examen) y de la nada me apareció una crucecita roja en un problema, a pesar de que no lo he intentado y soy admin. No recuerdo que estuviera ahí desde el inicio; creo que apareció cuando *alguien más* intentó el problema y se equivocó.

![image](https://user-images.githubusercontent.com/19719969/139076666-164085a0-d241-478f-8996-6bb74c5ae492.png)

**Comment by heduenas** [comment]
Hay que darle prioridad a este issue porque no solo afecta a admins del concurso, sino que tambien a concursantes.
