### ISSUE TITLE
[FEATURE] Agregar botón de progreso de estudiantes en la parte de edición de un curso

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#5914]
No se puede llegar a la interfaz de Progreso de los estudiantes desde la página de edición. Se tiene que ir a la página principal del curso y después ingresar a Progreso de estudiantes.

![Progreso de estudiantes-en edición](https://user-images.githubusercontent.com/940007/139520282-661d7d9d-80d8-483a-b0a1-562a46051d70.png)

![Progreso de estudiantes-en edición2](https://user-images.githubusercontent.com/940007/139520288-1aae3680-12d3-4068-bc4b-6baa79d50dea.png)

## Comportamiento Esperado

Poder ingresar desde la interfaz de edición de un curso a el progreso de estudiantes.

**Comment by IngridRB** [comment]
Hola @heduenas @carlosabcs me gustaria tomar este issue. Mi usuario en el concurso de GSoC es IngridRB y ya resolví 3 problemas.

**Comment by Karyme-Nava** [comment]
Hola @tvanessa @heduenas @pabo99, ¿me pueden asignar este issue si aún no está asignado a alguien más? Mi usuario en el concurso GSoC es Karyme_Nava, ya completé los 4 problemas

**Comment by heduenas** [comment]
Asignando este issue a @Karyme-Nava ya que a Ingrid le fue asignado otro issue. Gracias a ambas por la ayuda con estos issues!

**Comment by pabo99** [comment]
@Karyme-Nava Aún estás interesada en resolver este issue?

**Comment by Karyme-Nava** [comment]
Sí, estoy trabajando en él
