### ISSUE TITLE
[FEATURE] Corregir el texto de `privacy/accept_teacher`

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#5931]
El texto,

> ¿Deseas agregar a los organizadores del curso como tus profesores/profesoras?
> 
> Si los aceptas, podrán ver la lista de los problemas que has resuelto y de los que has intentado resolver

debería dejar claro que se refiere al listado de los problemas fuera del curso. O solo preguntarlo a los que tienen perfiles privados.

**Comment by heduenas** [comment]
ES:
```
¿Deseas aceptar a las personas administradoras del curso como tus docentes?

Si los aceptas, podrán ver la lista de los problemas que has resuelto y de los que has intentado resolver tanto dentro como fuera del curso.
```

EN:
```
¿Do you want to accept the admins of the contest as your teachers?

If you accept them, they will be able to see the list of problems that you have solved or attempted to solve both inside the course and outside the course.
```

**Comment by mohdabbas955** [comment]
@heduenas Does in EN ,Question mark will come in starting of Do.

**Comment by mohdabbas955** [comment]
I have solved this issue.Can you please assigned me this issue? So that I can make a generate PR.

**Comment by pabo99** [comment]
> @heduenas Does in EN ,Question mark will come in starting of Do.

It was a mistake. In english, question mark is not needed at the beginning of the question. Thanks for your help

**Comment by pabo99** [comment]
> I have solved this issue.Can you please assigned me this issue? So that I can make a generate PR.

Now, the issue has been assigned to you, @mohdabbas955. Go ahead with your PR =D

**Comment by tvanessa** [comment]
ES: Acepto que cualquier admin del curso pueda ver toda mi lista de problemas resueltos y los que he intentado resolver
EN: I accept any course admin to see my entire list of problems that I have solved or attempted to solve
PT: Aceito que qualquer admin de curso veja minha lista completa de problemas que resolvi ou tentei resolver
