### ISSUE TITLE
[FEATURE] Como un usuario en móvil, quiero no tener que desplazarme de izquierda a derecha para hacer login

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#5934]
## Comportamiento Actual

Cuando entro a omegaUp en móvil (e.g. Chrome en Android) y quiero hacer login, tengo que ir al botón de hamburguesa que está en la parte superior derecha.

Eso abre el menú pero los links que son parte del menú se muestran en el margen izquierdo.

## Comportamiento Esperado

Estaría mejor que los elementos del menú se mostraran cargados a la derecha, donde está el botón.

Otra opción sería que el botón de hamburguesa se ubicara a la izquierda.

## Contexto

Mi flujo de trabajo al entrar en móvil es abrir omegaUp.com, hacer zoom para ver la hamburguesa de buen tamaño, darle click, luego desplazarme hasta la izquierda para poder ver el botón de login. Hacer login, volver a hacer click al botón de hamburguesa luego desplazarme hasta la izquierda para ver el dropdown de mi perfil y de ahí ir a mis cursos o cosas parecidas.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome on Android 95.0.4638.50
* Sistema Operativo y versión (escritorio o móbil): Android 11
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/189223/140016834-45f0a134-afe4-485a-a92d-4ce12bf7a934.png)

**Comment by heduenas** [comment]
English summary of this issue: Let's align the navigation bar buttons (Contests, Cousers, etc) to the right instead of the left.

**Comment by MohitOhlyan** [comment]
I think I might be able to pull it off. Can you assign me this task?

**Comment by heduenas** [comment]
You got it! Thank you for working on these!
