### ISSUE TITLE
[BUG] Algunos perfiles tardan una cantidad significativa de tiempo en cargar

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#5966]
Hola amigos de omegaUp.

Si intentan abrir el perfil https://omegaup.com/profile/David_Castillo_Velazquez/, notarán que termina su carga de forma casi instantánea (tiempo total de 0.7 segundos). Si abren mi perfil en https://omegaup.com/profile/rcc, el tiempo se dispara a 7 segundos donde el principal responsable del tiempo total es la carga del documento principal (y este comportamiento ocurre consistentemente al recargar la página)

![image](https://user-images.githubusercontent.com/19719969/140845764-e56e5360-148d-4a27-8723-1338dd618d7f.png)

Si abren el perfil del top 1 de omegaUp en https://omegaup.com/profile/osmar/, el tiempo se dispara a 16 segundos y el principal responsable sigue siendo el documento principal

![image](https://user-images.githubusercontent.com/19719969/140845891-5c87b6b6-5117-4fcb-902e-37d3e8804c40.png)

Aparentemente, el tiempo de carga está en función de la cantidad de problemas resueltos (y posiblemente también de la cantidad de problemas creados, pero lo dudo). Seguramente la base de datos anda haciendo malabares cada vez que se solicita el /profile/ de un usuario. Estaba navegando por el código de omegaUp, pero creo que el despliegue de esa página ejecuta código que está repartido en varios archivos fuente y me perdí. Independientemente de mi fracaso al encontrar el cacho de código culpable, el tiempo de procesamiento que se está invirtiendo en esas cargas es algo peligrosa.

**Comment by pabloaguilar** [comment]
Carga igual de lento al hacer un refresh?
Podría ser lento la primera vez pero el caché debería hacerlo igual de
rápido en la 2da carga.

**Comment by darkmx** [comment]
Tarda siempre mucho :(

**Comment by pabloaguilar** [comment]
Parece que estamos mandando muchisima información inútil a la hora de generar la página de perfil.

En particular, veo que para la lista de contenido creado, el `payload` incluye cosas como:
* Problemas
  - nivel de dificultad
  - envíos
  - envíos aceptados
* Concursos
  - modo de evaluación
  - link al scoreboard
  - link al scoreboard de admin
  - fechas de inicio y fin

Pero lo único que estamos usando es el alias para generar links y el nombre para ponerlo en la lista.

**Comment by pabloaguilar** [comment]
Una mitigación sería el tenerlo en cache; pero nada de eso esta cache-ado.

Hay una dependencia ahí medio rara entre `User` e `Identity` donde botan entre uno y otro para formar el perfil completo y creo que eso dificulta un poco el mantener el cache en buen estado.

Un parche temporal sería cachear `extraProfileDetails` independientemente del perfil y solo ponerle un timeout cortito (de a media hora o una hora o algo así) parecido a `APC_USER_CACHE_USER_RANK_TIMEOUT`.

Algo más en serio sería arreglar el ping pong de los controladores para armar el perfil y definir una mejor estrategia de mantenimiento del cache.

Mando la mitigación esta semana.

**Comment by lhchavez** [comment]
En teoría https://github.com/omegaup/omegaup/pull/6068 debería ayudar un montón: eso era lo más lento de toda la consulta por mucho.

**Comment by darkmx** [comment]
La carga de perfiles se aceleró mucho :) (antes el perfil del top 1 tardaba 16s y ahora tarda 3.5s) aunque me gustaría añadir que parece ser (aunque no estoy completamente seguro) que aún hay un low-hanging fruit por ahí.
Les pongo una tablita:

![image](https://user-images.githubusercontent.com/19719969/144460967-52c2f7e4-486e-49cc-838f-9ae4d494e8d1.png)

Enlaces clickeables:
https://omegaup.com/profile/TheAvenger/
https://omegaup.com/profile/osmar/
https://omegaup.com/profile/AlejandroGY/
https://omegaup.com/profile/DiegoBriaares/
https://omegaup.com/profile/Mariola_Cam_Lie/
https://omegaup.com/profile/rcc

Aparentemente, la cantidad de concursos en los que un usuario ha participado es un buen predictor para el tiempo de carga. Suponiendo una sobrecarga mínima de 0.3s, es notable la diferencia que hay entre la carga de los perfiles de TheAvenger y osmar. En el perfil de DiegoBriaares hay menos problemas resueltos, menos problemas intentados y muchos concursos: lo lento de la carga también ocurre con él.

**Comment by pabloaguilar** [comment]
Creo que esto ya quedó adecuadamente cubierto. Entre el fix de @lhchavez y parche de cache mio, la 2da+ carga de los perfiles en la lista lenta (gracias por compilarla @darkmx!) ya cargan en < 120ms para mí. La primer carga, no cubierta por el cache todavia cuadra con los números en la tabla, pero las cargas sucesivas se ven bien.

Declaro el issue cerrado 😀
