### ISSUE TITLE
[FEATURE] Como un Profesor/Concursante, quiero poder googlear problemas para encontrarlos facilmente

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#5973]
## Comportamiento Esperado

Al googlear palabras claves de un problema en Google, este me recomendará la pagina que me lleva al problema.

## Comportamiento Actual

No sucede esto, incluso haciendo búsqueda avanzada en Google, como encontrar frases exactas o buscar solo en omegaup.com

## Posible Solución

No lo sé, si tuviera que adivinar, cuando el web crawler investiga un problema de Omegaup este no ha renderizado O directamente es inencontrable por el webcrawler., o robots.txt (No sé mucho de SEO)

## Alternativas consideradas

Por cierto, Bing aparenta funcionar, pero Google tiene la mayor cantidad de usuarios y estaría genial que también funcione.
![image](https://user-images.githubusercontent.com/19498800/141010561-cec5adca-781b-4ccf-b664-af21b0e2247f.png)

## Contexto

A veces recuerdo palabras de un problema o cosas vagas, mientras que en otros jueces online esto es suficiente para encontrar el problema, en Omegaup no funciona.

## Tu ambiente
![image](https://user-images.githubusercontent.com/19498800/141009472-30c13665-c8ee-49ff-b9d3-3028bfeffaa2.png)
![image](https://user-images.githubusercontent.com/19498800/141009600-be68399e-2c19-40e8-8052-d658a508e030.png)

**Comment by tvanessa** [comment]
resuelto en #6350
