### ISSUE TITLE
[BUG] Internal Server Error al abrir cualquier problema

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#5979]
## Comportamiento Actual

Esta dando este error al intentar leer cualquier problema:
![image](https://user-images.githubusercontent.com/123875/141225933-730966e6-12bc-4bd9-98c6-c36de128ff16.png)
https://omegaup.com/arena/problem/Niveles-Pascal/

Sucede en Chrome, Firefox & Edge con sesión iniciada  sin iniciar

No hay información alguna en la consola

**Comment by tvanessa** [comment]
ya no se reproduce
