### ISSUE TITLE
Agregar concursante bulk

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#598]
Evaluar que se reciba una lista en csv de usernames o correos de usuarios ya registrados en la plataforma. Esto _no_ va a crear usuarios

**Comment by lhchavez** [comment]
La idea es que en la página de edición del concurso [link] ahorita tenemos un campo para agregar concursnates uno a uno. Estaría cool tener un textarea para pegar una lista de correos/usernames y un algo para "subir" un archivo (pero en realidad se lea mediante JavaScript) para llamar al API de agregar usuarios uno a uno desde el cliente y al final mostrar una tablita de los usuarios que no se pudieron agregar porque no se encontraron. Esto no debería requerir cambios a la API.
