### ISSUE TITLE
[FEATURE] Como un usuario de JavaScript, quiero poder usar JS y/o TS para evaluar problemas en omegaUp.

### ISSUE THREAD

**Issue by e-fishel** [omegaup/omegaup#5984]
## Comportamiento Esperado

Cuando este por enviar mi código, y se elija lenguaje, que aparezca JS y/o TS. Y que al enviarlo, el juez en línea se encargue de evaluarlo correctamente.
Y también me gustaría verlo soportado en el ephemeral.

## Comportamiento Actual

Actualmente están básicamente C11, C++11, C++17, Java, Python 2, Python 3, Ruby, C#, Pascal, Haskell y Lua.
En ésta lista no esta JS ni TS porque ni JS ni TS están actualmente soportados en omegaUp.

## Alternativas consideradas

no incluirlo y hacerme sad 😥

## Contexto

El objetivo es poder usar JS y/o TS para problemas de omegaUp ya que éstos lenguajes son útiles y usados ampliamente.
Hasta el momento no se puede enviar ningún problema en JS y, si no ha sido claro, me gustaría enviarlos en JS y/o TS.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

_//no es bug, no tengo adblocker activado y, según yo, ningúna de mis extensiones esta interfiriendo, no hay <option> con JS y/o TS._

* Captura de pantalla:
![Ωup no JS or TS](https://user-images.githubusercontent.com/86935360/141402367-f60cdd95-5138-4a6c-9cd9-546660e980be.png)

Gracias ◉⌣◉

**Comment by tvanessa** [comment]
Resuelto en #6397
