### ISSUE TITLE
En la pestaña de "envíos" de un concurso no aparecen la totalidad de envíos hecho por los concursantes.

### ISSUE THREAD

**Issue by jcrosalesl** [omegaup/omegaup#5991]
## Comportamiento Esperado

*Esperaba poder revisar todos los envíos de los concursantes que se ven el "scoreboard" del concurso.

## Comportamiento Actual

*A la hora de revisar los envíos hechos al concurso "DDF2021" no aparecen la totalidad de envíos.*

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

Link del "scoreboard" del concurso, observar al usuario yahir.ibarra.136 (resolvió 5 problemas)
1. https://omegaup.com/arena/DDF2021/scoreboard/fDDC7E6QSLDhkvm5KsAqgbmNPRppzm/

Link a la lista de problemas que resolvió el usuario yahir.ibarra.136 (solo se observan 3 problemas)
2. https://drive.google.com/file/d/13cFGgeu1sdxUtpnvo4P_UK3xn965CfRH/view?usp=sharing

Y lo mismo pasa para todos los usuarios, en el "scoreboard", aparecen mas problemas de los que se observan en los "envíos"

## Contexto

*No pude revisar cada problema resulto para cerciorarme que habían usado el algoritmo propuesto*

*Que en la pestaña envíos aparezcan todos los problemas que subieron los concursantes*

## Tu ambiente

*Al terminar el concurso, durante el concurso si era posible revisar*

* Nombre del navegador (Chrome está actualizado, Versión 95.0.4638.69 (Build oficial) (64 bits)
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Errores en la consola: [no]
* Captura de pantalla: Adjunte links

![Problemas_Yahir](https://user-images.githubusercontent.com/94211317/141606645-e40b9a23-6cb7-43de-a97f-201c5293eea6.jpg)
![Scorboard](https://user-images.githubusercontent.com/94211317/141606646-17319f53-02f9-41b5-b0bd-9c0d2d4a7454.jpg)

**Comment by tvanessa** [comment]
@pabo99 esto podría ser consecuencia de la migración de arena?

**Comment by pabo99** [comment]
> @pabo99 esto podría ser consecuencia de la migración de arena?

Lo más probable es que si se deba a una regresión al momento de realizar la migración. 

De cualquier forma, lo revisaré para poder solucionarlo
