### ISSUE TITLE
Adaptar los colores del Ephemeral grader acorde a los del resto de la interfaz.

### ISSUE THREAD

**Issue by carlosabcs** [omegaup/omegaup#5999]
Hay que definir esos nuevos colores.

**Comment by pabo99** [comment]
¿Hay forma de que esto sólo se aplique para el iframe embebido en la arena? Ya que hay algunos comentarios done prefieren que el ephemeral por separado se muestre con el tema oscuro

**Comment by samdsmx** [comment]
#6647
