### ISSUE TITLE
[BUG] Se muestran números incorrectos en el # de problemas/lecciones

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#6009]
Si vas a la lista de contenido de un curso, los números de la cantidad de problemas y lecciones para cada card son incorrectos.

Sólo lo explore en cursos públicos: https://omegaup.com/course/introduccion_a_cpp/

![Screen Shot 2021-11-17 at 3 22 52 AM](https://user-images.githubusercontent.com/13296248/142192375-af104aa0-8348-43bd-b8e5-bf578c93bdfb.png)
![Screen Shot 2021-11-17 at 3 25 56 AM](https://user-images.githubusercontent.com/13296248/142192381-1ac947e5-90e9-46ff-afb3-0161bcefd29c.png)

**Comment by carlosabcs** [comment]
Esto ya está corregido en: https://github.com/omegaup/omegaup/pull/5994
