### ISSUE TITLE
Responder clarificaciones directamente respondiendo emails

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#601]

**Comment by lhchavez** [comment]
A partir de a7b1089e923ce68c8e3a9558360a53e7691ddb8d ya enviamos correos cuando hay nuevas clarificaciones si el problemsetter activa la opción de enviar correos (posiblemente en el futuro esa opción se vuelva default y/o mandatoria).

Aún no es posible responderlas por correo.

**Comment by lhchavez** [comment]
Como ya agregamos un link directo en el correo, creo que no es tan necesario.
