### ISSUE TITLE
[BUG] Dropdown de ranking no esta localizado.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6018]
![Screen Shot 2021-11-18 at 3 31 38 PM](https://user-images.githubusercontent.com/597815/142513165-4705559b-e4c3-4e09-a311-ef3868037180.png)

Los elementos del dropdown aparecen en ingles, pero tengo mi perfil configurado en espanol.

**Comment by pabo99** [comment]
Creo entender el problema que está ocurriendo aquí:

Las cadenas que se muestran en ese dropdown vienen directamente del controlador y están utilizando `\OmegaUp\Translations::getInstance()->get()`, el cuál no está optimizado para mostrar los textos en el lenguaje que ha seleccionado el usuario como preferencia, sino que están mostrándolos en el lenguaje del navegador. 

Este error no es tan común porque por lo regular el idioma que utilizan los usuarios coincide con el idioma del navegador.

Entonces, para solucionar este bug se me ocurren dos posibles soluciones.

- Dejar al cliente (vueJS) que decida elegir las cadenas localizadas y en el controlador sólo indicar cuales son las que se quieren mostrar.
- Arreglar la falla en la clase `\OmegaUp\Translations` para que solicite el lenguaje de preferencia del usuario logueado, sólo en caso de que no esté logueado o que haya guardado esta información, ahí si mostrar el lenguaje del navegador.

**Comment by lhchavez** [comment]
voto por la segunda para arreglarlo en todos lados al mismo tiempo

**Comment by pabo99** [comment]
Ok. Se me ocurre que podríamos recibir el argumento de `$identity`, tanto en `getInstance` como en el constructor de `Translations`. Este argumento podría se nullable y opcional (para que el cambio se pueda realizar gradualmente). Después de eso ya podríamos mandar el argumento en donde se utiliza `\OmegaUp\Translations::getInstance()->get()` (empezando por las cadenas de traducción que se reportan en este issue).

@S4ND1X , Si tienes dudas de como implementar esta solución, nos puedes contactar para resolverlas.

**Comment by S4ND1X** [comment]
> Ok. Se me ocurre que podríamos recibir el argumento de `$identity`, tanto en `getInstance` como en el constructor de `Translations`. Este argumento podría se nullable y opcional (para que el cambio se pueda realizar gradualmente). Después de eso ya podríamos mandar el argumento en donde se utiliza `\OmegaUp\Translations::getInstance()->get()` (empezando por las cadenas de traducción que se reportan en este issue).
> 
> @S4ND1X , Si tienes dudas de como implementar esta solución, nos puedes contactar para resolverlas.

Buenas taredes a ambos, le empezare a dar una checada entre el viernes y el sabado, si salen dudas (que seguramente si 😆 ) sin duda se las hare llegar, muchas gracias por la aclaracion!
