### ISSUE TITLE
[BUG] En una búsqueda por texto, la obligatoriedad de usar el typeahead causa problemas

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6057]
Hola amigos de omegaUp.

Recientemente Juan Pablo Marín (del ICPC) intentó ponerme de admin en unos problemas que está subiendo. Al teclear mi usuario (rcc) le apareció el equivalente a esto:

![image](https://user-images.githubusercontent.com/19719969/143686361-856ab5d6-b006-4b12-bb32-e4aa0e73bda4.png)

Como mi usuario no es ninguna de las sugerencias, entonces uno pensaría que debemos 1) ignorar las sugerencias, 2) darle click al botón para que se use lo que escribimos en el campo de texto. Desafortunadamente esto no funciona, porque la búsqueda no hará nada si no se eligió una de las sugerencias. Esto es (muy) contraintuitivo. 

Lo que yo siempre hago cuando me enfrento a este inconveniente, es terminar mi búsqueda con un espacio. Esto tiene el efecto de filtrar la lista de recomendaciones:

![image](https://user-images.githubusercontent.com/19719969/143686483-acf29544-fe10-4bb6-88d6-f0c1f53baeac.png)

Ya con eso le puedo dar click a la recomendación y otro click al botón. Ese segundo click es deseable en algunas circunstancias (ej. agregar admin; no queremos que se agregue por error) pero es indeseable en otros contextos (ej. #5303).

**Comment by Apocryphon-X** [comment]
Este problema es del mismo tipo que #5564
