### ISSUE TITLE
[BUG] No se pueden descargar los casos de un problema reciente y omegaUp le pone "AC" a todos los envíos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6058]
Hola amigos de omegaUp.

El problema https://omegaup.com/arena/problem/diametro-de-un-arbol/#problems fue subido recientemente (28/9/2021) pero ocurre un error al intentar descargar los casos en https://omegaup.com/api/problem/download/problem_alias/diametro-de-un-arbol (no soy autor pero tengo admin):

![image](https://user-images.githubusercontent.com/19719969/143718765-0b018ba5-66ee-4f75-9f1d-cd211dafeb75.png)

Aún así, la plataforma está aceptando todo (incluso programas que imprimen tarugadas) con 0s y 0MB

![image](https://user-images.githubusercontent.com/19719969/143718793-9bb45f35-6793-44bc-ab61-2dd19745560c.png)

**Comment by darkmx** [comment]
Lo mismo pasa con un problema de ayer: https://omegaup.com/arena/problem/Formando-Hidrocarburos-/

**Comment by lhchavez** [comment]
Cerrando porque esto es esperado.
