### ISSUE TITLE
[BUG] La plataforma está aceptando zips de problemas que no cumplen la especificación

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6059]
Hola amigos de omegaUp.

Andamos rastreando un bug y la plataforma está aceptando un zip con esta estructura:

statements/
   es.markdown
cases/
   caso.in.txt
   caso.out.txt

Esto eventualmente causa todos los problemas descritos en #6058

**Comment by lhchavez** [comment]
Ahora que ya se arregló, esta es la lista de problemas que no se declaran como que sí aceptan envíos _pero_ no tienen casos:

```
Busqueda-Binaria-Material-COVI
Busqueda-Binaria-Reconstruido__C
Busqueda-Binaria-Reconstruido_CO
Busqueda-en-Profundidad
Cola
Cola-de-prioridad
COMI-Recursion
COVI-BusquedaAmplitud
Explicar-el-concepto-de-Pilas-y-
Introduccion-a-las-estructuras-d
karel34112
Lista-stl-leccion
Merge-Sort
OVI-BubbleSort
OVI-HeapSort
OVI-InsertionSort
OVI-Introduccion-a-DP
OVI-IntroduccionOrdenamiento
OVI-MergeSort
OVI-QuickSort
OVI-SelectionSort
parImparSinEnvios
prueba100
REC_Aritmetica-y-Divisibilidad
Recursion-con-memoria
Set-COVI
STL_Vector
Temario-Curso-COVI
Vector
Vectores-y-Matrices
zxcv
```

hay que ver manualmente a ver si sí es cierto que _deberían_ tener casos.

**Comment by darkmx** [comment]
Los checo al ratito.

**Comment by darkmx** [comment]
Lo que salió:

Busqueda-Binaria-Reconstruido__C      de plano no abre (404)
Busqueda-Binaria-Reconstruido_CO     de plano no abre (404)
parImparSinEnvios                                privado, sin autor ni envíos
zxcv                                                       suspendido, sin autor ni envíos

Me intriga saber cómo terminaron así, pero sospecho que no hay nada grave en ignorarlos.
