### ISSUE TITLE
[BUG] Navegar entre páginas de envíos se volvió notablemente lento

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6071]
Hola amigos de omegaUp.

Esta semana noté que la navegación entre las páginas de los envíos de un problema es algo más lenta que antes (y ya es lo suficientemente lenta como para confundir en algunos contextos, por ejemplo, cuando filtras la lista por algún criterio).

Este problema https://omegaup.com/arena/problem/Lavos-el-devorador-de-planetas/ tiene aproximadamente 50 envíos, pero aún así, navegar entre cada página tarda bastante.

![image](https://user-images.githubusercontent.com/19719969/144153078-510b9bce-70d3-41d6-8b5b-86de69804a82.png)

**Comment by lhchavez** [comment]
Resulta que https://github.com/omegaup/omegaup/pull/6070 lo arregló

**Comment by darkmx** [comment]
Qué buen servicio :)
