### ISSUE TITLE
[FEATURE] Dejar de permitir que los usuarios asignen tags viejos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6089]
Hola amigos de omegaUp.

Hace ya como un año se rediseñó la lista de tags (problemTag___) pero en omegaUp ya existía una lista de tags (problemTopic___) que quedó obsoleta. Sin embargo, los usuarios siguen estando en la posibilidad de asignar los tags obsoletos:

![image](https://user-images.githubusercontent.com/19719969/144721091-d1b7a327-a4a1-42c9-bb09-53720bf5af17.png)

De hecho, propongo que los usuarios ordinarios _dejen de poder asignar tags_ en problemas ajenos que intenten resolver. Dos razones: 1) los autores de problemas están obligados a asignar tags a problemas nuevos; 2) algunos usuarios hacen mal uso de la asignación de tags obsoletos. Si se decide no quitar dicha capacidad, entonces al menos se debería modificar la lista de tags para dejar de mostrar los tags obsoletos y ahora mostrar los tags nuevos.

**Comment by heduenas** [comment]
English summary of this issue: We should remove the "Topics" section from the feedback form that you get whenever you solve a problem (outside of a contest).

**Comment by anmode** [comment]
could i get some guidance!? Feedback form is generated so it uses database.  I tried a lot but still trying so i could get to the point.

**Comment by MohitOhlyan** [comment]
Is this already solved? If not, can you please assign me this.

**Comment by heduenas** [comment]
That's correct @MohitOhlyan. You have now 2 open issues assigned, can we wait at least until you send a PR for 1 of the 2?

**Comment by MohitOhlyan** [comment]
> That's correct @MohitOhlyan. However, you now have 2 open issues assigned, can we wait at least until you send a PR for 1 of the 2?

Yea sure. I Working on both. Thanks again.

**Comment by Mohdtalha12** [comment]
Can you please assign me this issue?
i will be able to solve it.

**Comment by heduenas** [comment]
Can you first solve 2 of 3 problems of the phase one test? I have extended the deadline https://omegaup.com/arena/gsoc2022e/

**Comment by Mohdtalha12** [comment]
Hello heduenas,
 I am participating in GSOC 2022.
I will be able to do both things together.
Please assign me this issue.

**Comment by heduenas** [comment]
We have a rule to ask applicants to first complete the test. I order to keep the process fair to those who started the application process earlier, we can't make exceptions.

**Comment by artmtt** [comment]
Hello, I think I might be able to solve this, if it is still available, can I be assigned to the issue?

**Comment by Mohdtalha12** [comment]
@artmtt 
I am solving this issue .
Please look for another issue
