### ISSUE TITLE
[BUG] ephemeral grader no corre

### ISSUE THREAD

**Issue by PiedraFernando** [omegaup/omegaup#6093]
## Comportamiento Esperado

Al darle clic en "Run" debería mostrar los resultados de los casos.

## Comportamiento Actual

Se queda cargando y no aparece ninguna actualización, de hecho en la consola del navegador aparecen dos errores "Failed to load resource: the server responded with a status of 504 ()" y "Async error TypeError: Cannot read properties of undefined (reading 'state')"

## Posible Solución

Hace poco han dicho que cambiaron DNS, por lo que podría ser que aun ephemeral, no a actualizado las DNS, o falta actualizar las direcciones para las peticiones de ephemeral.

## Pasos para reproducir (para bugs)

En un problema cualquiera, por ejemplo: https://omegaup.com/arena/problem/Watermel/
1.  Entras a la sección de ephemeral
2.  Verificas que el código esta correcto, de hecho en el que aparece por defecto también ocurre.
3.  Das clic en "Run"

## Contexto

Quería probar mi solución a un problema sin tener que instalar el compilador de python.

## Tu ambiente

-navegador: Google chrome Versión 96.0.4664.45 (Build oficial) (64 bits)
-Windows 11
-Imagen del problema: https://drive.google.com/file/d/1as8YUsK_gbnDx55YoZewkgIZ443wYzKJ/view?usp=sharing

**Comment by lhchavez** [comment]
resulta que esto es porque no pudimos terminar la migración a k8s completamente: el firewall del grader sólo permitía conexiones desde el viejo frontend. ahora con k8s, no estoy enteramente seguro de cómo debería hacerse eso, porque los nodos de k8s no tienen una IP pública :/

**Comment by lhchavez** [comment]
nevermind, ya encontré la IP pública del cluster de k8s. listo!
