### ISSUE TITLE
[FEATURE] Notificar a usuarias elegibles de la OFMI

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6099]
Los requisitos son:
Tiene registrado genero y este es != masculino
Tiene registrada fecha de nacimiento y esta es >= 01/07/2003
Tiene registrado pais y este es = Mexico

**Comment by Mau-MD** [comment]
Enviado el query de SQL por slack

**Comment by heduenas** [comment]
Muchas gracias Mau! Una vez que @lhchavez confirme haber corrido el query hay que cerrar este issue.
