### ISSUE TITLE
Permitir ocultar concursos

### ISSUE THREAD

**Issue by rendon** [omegaup/omegaup#610]
Sería bueno tener una opción para borrar concursos, hay varios concursos que solo se crearon para hacer pruebas pero que no son útiles.

**Comment by lhchavez** [comment]
Tal vez sea mejor resolver #617 en vez de esto.

**Comment by alanboy** [comment]
Tambien se necesita esto. Ademas de #617

**Comment by elendil326** [comment]
@lhchavez quién definirá el diseño para habilitar esto?

**Comment by pabo99** [comment]
¿Esto no se soluciona con los concursos privados? Ya que es la bandera que propone @joemmanuel

**Comment by heduenas** [comment]
Se cierra por los concursos privados
