### ISSUE TITLE
[FEATURE] Agrupar campos de `problem/new/` usando paneles colapsables

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6102]
Hay que agrupar los campos usando paneles colapsables. Justo al abrir la pagina solo el primer panel va a estar extendido y el resto colapsados.

El resultado debe de quedar algo similar a esto: https://www.youtube.com/watch?v=EeF0yWP4xp0?t=1500

Los campos deben de quedar en los siguientes grupos y en el orden que se muestra en esta lista:

Datos basicos:
* Titulo
* Alias
* Fuente del problema
* Adjuntar archivo zip

Etiquetas:
* Etiquetas publicas
* Etiquetas privadas
* Nivel
* Mostrar tags sugeridos por usuarios

Limites:
* Tiempo limite por caso
* Tiempo limite total
* Tiempo limite para el validador
* Tiempo limite extra para libinteractive
* Limite de memoria
* Limite de salida
* Limite de entrada

Validacion:
* Tipo de problema
* Tipo de validador

Accesos:
* El problema sera publico?
* Recibir preguntas acerca del problema por correo

Evaluacion:
* Mostrar diferencias en los casos
* Puntaje de grupos

**Comment by lhchavez** [comment]
cómo va a quedar esto con el creador? sólo va a cambiar el "adjuntar archivo zip" por "todo el creador"?

**Comment by heduenas** [comment]
Junto con Mau llegamos a esta UX:
El CDP va a ser el primer paso para llenar nombre, statement, casos y solucion. Luego el CDP va a generar el zip del problema, lo va a guardar en el storage local y va a redigir al usuario al formulario que ahorita tenemos en `/problem/new`. El formulario va a cargar el zip desde el storage local en vez de pedir archivo adjunto.

Tambien, el CDP va a tener un boton para cargar desde .zip para usuarios que prefieren editar por fuera.
