### ISSUE TITLE
[BUG] - Error en la consola de desarrollo

### ISSUE THREAD

**Issue by Miespinosac** [omegaup/omegaup#6105]
## Comportamiento Esperado

*Al resolver un peoblema, necesito ocupar la consola que me permite desarrollar y generar los casos de prueba

## Comportamiento Actual

La consola no se muestra correctamente, ésta vibra y no permite la ejecución del progrma

Esto comenzó desde que hubo una migración, (Cambio la consola de Negro a blanco)

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Entrar a resolver un problema
2. ir a la consola **omegaUp ephemeral grader**
3. En esa consola se muestra el error
## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
*El contexto que nos proporciones nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
* Sistema Operativo y versión (escritorio o móvil): Escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/MEC-Compras-Navidenas/
* Captura de pantalla:
*
![Captura de pantalla (32)](https://user-images.githubusercontent.com/95708834/145077546-139cb840-5775-439e-81fb-dde42aae6c12.png)

**Comment by pabo99** [comment]
Esto se arregla con el PR #6098 

El despliegue en producción se dará el fin de semana.
