### ISSUE TITLE
[Badge Proposal] Un Problema para Navidad 2021

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6129]
## ¿Cuál es el nombre de la insignia que propones?
*Un Problema para Navidad 2021

## ¿Qué debe haber realizado un usuario para recibir esta insignia?
*El usuario participó en el Concurso Un Problema para Navidad 2021 enviando problemas originales con temática Navidad. 

## ¿Esta insignia tiene un ícono personalizado?
*
![insigniaUnProblemapara Navidad2](https://user-images.githubusercontent.com/940007/145664961-2ab7f784-c405-4288-a0d6-98e21f005010.png)

**Comment by tvanessa** [comment]
@npave no tenemos la lista de ganadores, en especial sus usernames

**Comment by npave** [comment]
@tvanessa te mandé la información en Slack. Gracias!

**Comment by tvanessa** [comment]
@npave notamos que la imagen es .png, pueden proporcionarnos un .svg? por favor

**Comment by marleneharms** [comment]
@npave el archivo que está en el drive está vacío. Creo que fue un error, ¿me lo podrías pasar de nuevo? Gracias:)

**Comment by npave** [comment]
Claro, aquí lo dejo

https://drive.google.com/file/d/1ZRhuSfPFnQcYgno7BsWb0i-9aK5Oorbs/view?usp=sharing

**Comment by marleneharms** [comment]
@npave hola, @lhchavez me comenta si se puede convertir esta imagen a curvas, es que excede el tamaño maximo para un badge
