### ISSUE TITLE
[BUG] Problema con el limite de subida para archivos .zip

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#6130]
## Comportamiento Esperado

Subir a la plataforma un problema cuyo .zip pesa ~20 MB (y descomprimido, pesa ~40MB).

## Comportamiento Actual

Al tratar de subir un archivo .zip de 21 MB, aparece un error 413 (Request Entity Too Large).
![image](https://user-images.githubusercontent.com/40130428/145693421-44c107a9-88a3-4614-8210-f04b5a0d51b3.png)

## Pasos para reproducir

1. Entrar a la pagina para [crear](https://omegaup.com/problem/new/) un problema, o la pagina para editar uno.
2. Subir un problema cuyo .zip pese ~20MB.

## Contexto

Intento subir el .zip de un problema candidato para la OFMI 2022 pero al tratar de hacerlo, automaticamente es rechazado.

## Ambiente

<html>
<body>

Google Chrome | 96.0.4664.93 (Build oficial) (64 bits) (cohort: Stable)
-- | --
Revisión | 17531e0a70b4f8108f2418e8b5117f465077710b-refs/branch-heads/4664@{# 1229}
Sistema operativo | Windows 11 Version Dev (Build 22509.1011)
JavaScript | V8 9.6.180.20
User-agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Línea de comandos | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Ruta del ejecutable | C:\Program Files\Google\Chrome\Application\chrome.exe

</body>
</html>

**Comment by lhchavez** [comment]
Creo que con la migración a k8s se nos olvidó subir el límite del Ingress. Ahora ya se subió bastante más y ya no deberían tener problemas.
