### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#6131]
Acabo de subir un problema a OmegaUp y la subida estuvo bien, pero al confirmar una actualización de casos o de redacción, aparecer que la página no existe.

https://omegaup.com/problem/KVArribaOAbajo/edit/

Al presionar el botón actualizar redacción aparece:

![image](https://user-images.githubusercontent.com/6465292/145704071-d20dca68-6e02-483c-9d33-bdeacd22b007.png)

**Comment by lhchavez** [comment]
Dupe de #6132 (que ya quedó arreglado)
