### ISSUE TITLE
[BUG] Al editar un problema sale una pagina en blanco y nada se actualiza

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6132]
Al editar un problema a traves de https://omegaup.com/problem/ALIASedit/ sale una pagina en blanco y nada se actualiza.

@lhchavez tendrá que ver con cubernetes o será más bien por el rediseño de las páginas de editar y crear problema?

![Screen Shot 2021-12-11 at 11 32 04 PM](https://user-images.githubusercontent.com/597815/145704265-08b9142f-ab17-4a0d-a6a6-773e51d97c4d.png)

**Comment by kukogit** [comment]
Justo eso me acaba de pasar, pero no escribí bien el BUG

**Comment by kukogit** [comment]
Help!!! Necesito actualizar dos problemas que se aplicarán en examen al rato.

**Comment by lhchavez** [comment]
qué problemas son? parece que no son todos

**Comment by lhchavez** [comment]
parece que estaba mal-configurado el callback de autorización de gitserver con la migración a kubernetes. hasta donde pude ver, ya quedó resuelto.
