### ISSUE TITLE
[BUG] Error 504 al tratar de actualizar los limites de memoria en un problema

### ISSUE THREAD

**Issue by Apocryphon-X** [omegaup/omegaup#6134]
## Comportamiento Esperado

Disminuir el limite de memoria en un problema (de 32 MiB a 20 MiB).

## Comportamiento Actual

Al cambiar el limite de memoria y dar click en "Actualizar Problema", omegaUp arroja un error 504 (Gateway Time-out).
![image](https://user-images.githubusercontent.com/40130428/145724261-fce80267-2cb9-49c8-97ed-c3b8535aac54.png)

(Probablemente ocurra al editar otros parametros del problema)

## Pasos para reproducir

Nota: El .zip de el problema que presenta dicho issue pesa ~13MB, descomprimido pesa ~28MB.

1. Subir un problema a omegaUp.
2. Editar su limite de memoria.

## Contexto

Intento limitar la memoria de un problema candidato para la OFMI y el error esta impidiendo la actualización del limite.

## Ambiente

<html>
<body>

Google Chrome | 96.0.4664.93 (Build oficial) (64 bits) (cohort: Stable)
-- | --
Revisión | 17531e0a70b4f8108f2418e8b5117f465077710b-refs/branch-heads/4664@{# 1229}
Sistema operativo | Windows 11 Version Dev (Build 22509.1011)
JavaScript | V8 9.6.180.20
User-agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Línea de comandos | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Ruta del ejecutable | C:\Program Files\Google\Chrome\Application\chrome.exe

</body>
</html>

**Comment by Apocryphon-X** [comment]
@lhchavez, volvio a salir 504. Tambien lo probe actualizando la redacción del problema y salio otro 504
![image](https://user-images.githubusercontent.com/40130428/145724798-1aa97530-9bb4-47e4-80ec-255a0f16f60d.png)

**Comment by lhchavez** [comment]
puedes medir el tiempo que pasa entre que le das click y te sale el 504?

**Comment by Apocryphon-X** [comment]
Claro. Acabo de medir y el tiempo que tarda en salir el 504 es exactamente 1 minuto

**Comment by lhchavez** [comment]
ya subí más límites a ver si ya te permite

**Comment by Apocryphon-X** [comment]
Revise nuevamente y me marco el 504 de nuevo (nueva medicion: 1 minuto)

**Comment by Apocryphon-X** [comment]
Esta raro porque en la mañana funcionaba bien, podia editar la redacción y todo. Ahorita ya no me deja editar nada en ese problema porque a cada rato sale el 504

**Comment by lhchavez** [comment]
OH! gracias, esa información extra ayuda. _resulta_ ser que ese problema en particular está atorado! déjame ver qué se puede hacer para a) desatorarlo y b) prevenir que se vuelva a atorar.

**Comment by lhchavez** [comment]
listo, desatorado y _en teoría_ ya no debería volverse a atorar. si falla, reintentar después de 120s de la petición original _debería_ funcionar.

**Comment by Apocryphon-X** [comment]
Ya funciona, gracias!
