### ISSUE TITLE
[BUG] Matar todas las race conditions del ProblemDeployer

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#615]
flock(2) ftw

**Comment by elendil326** [comment]
@lhchavez más detalles :)

**Comment by lhchavez** [comment]
Creo que lo más conveniente es reimplementarlo en un lenguaje de verdad (Go).

Esto se va a hacer dentro de gitserver.

**Comment by lhchavez** [comment]
esto lleva un buen rato implementado en gitserver.
