### ISSUE TITLE
REGISTRO DE CUENTA POR PRIMERA VEZ

### ISSUE THREAD

**Issue by IlseRu** [omegaup/omegaup#6152]
## Comportamiento Esperado

Registro con mensaje exitoso para una cuenta en omegaup.

## Comportamiento Actual

Cuando doy clic en registrar, me manda un mensaje como si fuera de error, en rojo  pero si se hace el registro correctamente.

## Posible Solución

Cambiaria el color del mensaje, de rojo a verde/azul,  ya que se trata de verificar la cuenta por correo electronico.

## Pasos para reproducir (para bugs)

1.  ingresar datos (usuario, email y contraseña) 
2. dar clic en registrar 
3.  aparece mensaje en rojo pidiendo verificar cuenta y si sigue persistiendo error (que no hay) contactar a soporte

## Contexto

Confunde un poco ya que al dar clic en registrar, te dice el mensaje en el que te pide verificar tu cuenta, sin embargo es de color rojo y lo indica como si ya fuera un problema la verificacion, por el mensaje de "Si sigues teniendo problemas, escribe a omegaup-soporte@googlegroups.com".

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador Chrome 
* Sistema Operativo y versión (escritorio o móvil): windows 10 escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/login/?redirect=%2F
* Captura de pantalla:
![problema 1](https://user-images.githubusercontent.com/45744087/146305708-b67c27c3-f1a7-40c3-b337-e300462c3895.png)

**Comment by heduenas** [comment]
Hay que usar amarillo en vez de rojo.
