### ISSUE TITLE
INICIO DE SESION "CUENTA EN OTROS SITIOS" 

### ISSUE THREAD

**Issue by IlseRu** [omegaup/omegaup#6154]
## Comportamiento Esperado

Iniciar sesión de otra forma además de la tradicional (ingresando correo y contraseña en formulario de omegaup)

## Comportamiento Actual

En el apartado de Cuenta en otros sitios no aparece otras opciones para iniciar sesión

## Posible Solución

Añadir las otras formas de iniciar sesión (por correo de google etc) 

## Pasos para reproducir (para bugs)

1.  ingresar a omegaup 
2.  ir a "iniciar sesion"

## Contexto

 En la parte de “Cuenta en otros sitios” no aparece nada antes de que hagas el registro, lo cual es un poco confuso ya que no sabía de que otra manera podía acceder. Aparece el icono de Google cuando ya hiciste el registro previo. 

## Tu ambiente
* Nombre del navegador Chrome 96
* Sistema Operativo y versión (escritorio o móvil): windows 10 escritorio 
* Link al sitio en el que este problema pasa: https://omegaup.com/login/?redirect=%2F
* Captura de pantalla:

![problema 2](https://user-images.githubusercontent.com/45744087/146306362-44a3110e-4f12-40ec-85e2-a3a7abcd67c8.png)

**Comment by tvanessa** [comment]
Duplicado #6153
