### ISSUE TITLE
EDITAR PERFIL - AGREGAR IDENTIDAD

### ISSUE THREAD

**Issue by IlseRu** [omegaup/omegaup#6155]
## Comportamiento Esperado

Entender que es "identidad" en omegaup y poder editarlo 

## Comportamiento Actual

En la sección de identidad aparece el signo de información (i) sin embargo no explica que es, y  tiene un botón que dice “Agregar identidad” pero al presionarlo sale un mensaje de error. 

## Posible Solución

ponerle informacion practica al boton informativo (i) sobre que es identidad, y explicar que datos son los que van ahí.

## Pasos para reproducir (para bugs)

1.  Iniciar sesión
2. Ir a mi perfil 
3. Editar perfil 
4. Administrar identidades
5.  Editar informacion
6. Dar clic en boton "Agregar identidad"

## Contexto

En la sección de identidad aparece el signo de información (i) sin embargo no explica que es, me confunde ya que tiene un botón que dice “Agregar identidad” pero al presionarlo sale un mensaje de error.  "Parametro invalido: username"

## Tu ambiente
* Nombre del navegador Chrome
* Sistema Operativo y versión (escritorio o móvil): windows 10 escritorio 
* Link al sitio en el que este problema pasa: https://omegaup.com/profile/#manage-identities
* Captura de pantalla: 
![problema 3](https://user-images.githubusercontent.com/45744087/146307204-fc5f8088-ed08-4b07-98d9-b97a47ebd9a9.png)

**Comment by tvanessa** [comment]
Esto será más relevante ahora que desde el perfil se ven las opciones de "Editar perfil".

**Comment by AlexiaAM** [comment]
Hola, me gustaría resolver este issue :)

**Comment by heduenas** [comment]
Hay que agregar un mensaje de descripción.
Cadenas a usar:

ES:
"Si participaste en algún concurso y te asignaron un usuario y una contraseña, agregalo aquí para vincularlo con tu cuenta principal."
EN:
"If you participated in a contest and you were given a username and a password, add them here to link them to your main account"

**Comment by MohitOhlyan** [comment]
Should the description be added into the sign(i) when the mouse button is hovered over it?

**Comment by heduenas** [comment]
No, it should be added as a text box above the username/password fields.
