### ISSUE TITLE
AÑADIR GRUPO DE ADMINISTRADORES EN UN CURSO

### ISSUE THREAD

**Issue by IlseRu** [omegaup/omegaup#6160]
## Comportamiento Esperado

añadir correctamente el nombre del nuevo grupo de administradores en un curso 

## Comportamiento Actual

la función de “Agregar grupo de administradores” no pude utilizarlo, ya que no me deja añadir un grupo me sale el siguiente mensaje, y si intento usar algunos de los que me da de sugerencia  no me deja añadir el nombre del grupo

## Pasos para reproducir (para bugs)

1.  ir a un curso que se este gestionando 
2.  editar curso 
3.  ir a "administradores

## Contexto

no pude añadir un grupo para tener varios administradores, solo por separado

## Tu ambiente
* Nombre del navegador Chrome
* Sistema Operativo y versión (escritorio o móvil): windows 10 escritorio
![problema 7](https://user-images.githubusercontent.com/45744087/146309998-4a1d4ec9-2114-4814-ab00-82d768e155bf.png)

* Captura de pantalla:

**Comment by tvanessa** [comment]
Aquí lo que pasa es que primero debes crear un grupo en https://omegaup.com/group/new/ y después agregarlo. Por eso no te deja.

**Comment by heduenas** [comment]
New strings to use for the error message.

ES:
"Parámetro inválido: group. El grupo no existe, crealo en https://omegaup.com/group/new/"
EN:
"Invalid parameter: group. That group does not exist, create it at https://omegaup.com/group/new/"

**Comment by MohitOhlyan** [comment]
This seems doable. Can you assign me this issue? I think I can do it.
