### ISSUE TITLE
[BUG] Cuenta regresiva para el inicio de un concurso calcula mal

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6166]
Este es un screenshot cuando falta menos de 1 minuto para que incie. 

![Screen Shot 2021-12-17 at 1 51 16 PM](https://user-images.githubusercontent.com/597815/146612149-94d13968-0c17-439c-82be-baa2a655df73.png)

Creo que mas bien estamos mostrando el tiempo que falta para que se termine el concurso desde ahora, en vez del tiempo que falta para que inicie.

**Comment by darkmx** [comment]
Duplicado de #5909 (lo menciono porque #5909 ya se había asignado al milestone de otra persona).
