### ISSUE TITLE
[BUG] Las pruebas de Selenium están súper flaky

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#6185]
## Comportamiento Esperado

Las pruebas deberían pasar consistentemente si el funcionamiento no ha cambiado. Las pruebas flaky son casi inútiles: si se tienen que correr hasta que pasen, no se sabe si realmente hay errores transitorios, o si la prueba en sí tiene errores. Eso quiere decir que si hay una regresión, la prueba deja de funcionar.

## Comportamiento Actual

Hay que reintentar las pruebas de Selenium un montón de veces para que pasen.

## Posible Solución

Hay que arreglar las pruebas para que no sea doloroso contribuir cambios.

**Comment by Mau-MD** [comment]
Estoy casi seguro que se debe a los paneles colapsables de cuando se crea un problema. Casi seguro que #6145 lo arregla. Nomas tengo que ver lo de la prueba unitaria que me hace falta jeje

**Comment by lhchavez** [comment]
Hasta ahora Selenium no ha fallado ni una vez. Marcando esto como arreglado. Muchas gracias @Mau-MD !
