### ISSUE TITLE
Yo como usuario de soporte no puedo verificar correos/cuentas.

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#6195]
Yo como usuario soporte necesito verificar cuentas de los usuarios, los cuales me proporcionan su correo, yo me dirijo a omegaup.com/admin/support y ahí tengo una herramienta para poder verificar correos.

## Comportamiento Actual

No puedo verificar el correo de: f-ertorres@hotmail.com

Otros correos si puedo, pero especialmente ese no.

## Pasos para reproducir (para bugs)

omegaup.com/admin/support
1. Colocar el correo de f-ertorres@hotmail.com 
2. Dar click en verificar

## Contexto

No puedo verificar la cuenta de f-ertorres@hotmail.com

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome LTS
* Sistema Operativo y versión (escritorio o móvil): Windows 11
* Link al sitio en el que este problema pasa: omegaup.com/admin/support
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5459260/147158521-ea7c6817-fac4-4ab3-bb1d-a1bf915597d6.png)

**Comment by pabloaguilar** [comment]
Creo que con mi cuenta omegaUp (pablo.aguilar@omegaup.com) falla de la misma forma.
La respuesta del request se puede ver en el dev console y en ambos casos, el usuario problematico en este issue y mi propio usuario con el cual reproducirlo, tienen el campo `birthdate` = 0.

**Comment by pabo99** [comment]
> Creo que con mi cuenta omegaUp ([pablo.aguilar@omegaup.com](mailto:pablo.aguilar@omegaup.com)) falla de la misma forma. La respuesta del request se puede ver en el dev console y en ambos casos, el usuario problematico en este issue y mi propio usuario con el cual reproducirlo, tienen el campo `birthdate` = 0.

Muchas gracias @pabloaguilar , con eso ya  podemos asegurar que la falla si es por una fecha mal formada. Ya subí el PR con la posible solución.

**Comment by MiguelRomero** [comment]
@pabo99 Buenos días, entonces crees que este para el domingo? :D ojala! Saludos!
