### ISSUE TITLE
[BUG] La lista de contenido en cursos siempre dice "Resume"

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#6196]
Aunque no haya ingresado al contenido del curso, los botones de acceso siempre dicen "Resume". Esto no ayuda a saber qué contenido ya he visto.

![Screen Shot 2021-12-22 at 2 59 25 PM](https://user-images.githubusercontent.com/13296248/147164432-6117fc94-5e39-4d16-a945-5c03a556a111.png)

**Comment by carlosabcs** [comment]
¿Te parece si cambio el botón a "Ir"? Si no, ¿cuál sería el criterio para determinar si un Assignment ya ha sido abierto?

**Comment by tvanessa** [comment]
Qué tan costoso sería poner "Start" si no ha abierto un `assignment` y "Resume" en otro caso?

**Comment by carlosabcs** [comment]
Tendría que agregar un campo en BD para indicar que se dio clic a "Start" y así saber cuándo mostrar o no "Start" y "Resume". Hasta 4 horas supongo.

**Comment by tvanessa** [comment]
Está bien, mejor que se cambie a "Ir al contenido".

**Comment by pabloaguilar** [comment]
Qué tal aproximar la pregunta "abrió el contenido" mediante las entradas en `Problemset_Problem_Opened` ? A fin de cuentas, para contar que abrieron algún contenido tiene sentido que hayan tenido que ver algún problema, no? De lo contrario solo vieron el resumen, que no dice nada y pues, no cuenta tanto como haber empezado la lección?

**Comment by carlosabcs** [comment]
Provisionalmente, estoy cambiando el texto del botón.
Voy a intentar lo que sugiere @pabloaguilar
