### ISSUE TITLE
[BUG] No funciona la página para redactar problemas

### ISSUE THREAD

**Issue by SJMA11723** [omegaup/omegaup#6229]
## Comportamiento Esperado

Abrir el editor y poder visualizar la redacción.

## Comportamiento Actual

No abre la página

## Pasos para reproducir

1. Entrar al link: https://omegaup.com/redaccion.php

## Tu ambiente

https://omegaup.com/redaccion.php

![Screenshot_2021-12-30-09-30-49-421_com.opera.browser.jpg](https://user-images.githubusercontent.com/30766844/147766361-efda4588-8656-4d09-8158-fde1f5b9c189.jpg)

**Comment by pabo99** [comment]
Esto se debió corregir con #6227. Ya se puede cerrar
