### ISSUE TITLE
Mostrar lista de tags en la página de Add tags

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#623]
@joemmanuel de conseguir un mock-up del diseño esperado.

**Comment by pabo99** [comment]
¿La lista de tags puede quedar así?

![captura de pantalla 2017-11-06 a la s 21 27 34](https://user-images.githubusercontent.com/3230352/32475847-80b677ca-c339-11e7-9445-d631c41d8629.png)

**Comment by pabo99** [comment]
@npave ping, ¿que te parece ese diseño? ¿O sugieres otro distinto?

**Comment by npave** [comment]
@pabo99  cómo seleccionaste qué tags mostrar? Me gustaría darle semántica a los tags para poder mostrarlos en grupos como hemos platicado en issue #1491 y #1492

**Comment by pabo99** [comment]
En la imagen de propuesta sólo vienen ordenados alfabéticamente sin ningún filtro. Entonces primero se revisan los issues que mencionas para poder continuar con este.

**Comment by elendil326** [comment]
#1544 le dará seguimiento
