### ISSUE TITLE
[BUG] La insignia de problemas de calidad no es un PNG y se ve el fondo blanco en la tabla de problemas resueltos

### ISSUE THREAD

**Issue by Mau-MD** [omegaup/omegaup#6235]
## Comportamiento Esperado/Actual

Al momento de ir a perfil de cualquier usuario y ver los problemas que ha resuelto (o cualquier otra tabla), la insignia que muestra si ese problema es de calidad o no, tiene fondo blanco, y en algunas columnas, la tabla tiene un fondo gris. En mi opinion se ve feo esto:( 

Esta insignia deberia de tener fondo transparente para que no importe el color de fondo, se vea bien. Esto puede tambien ayudar para el futuro dark-mode que se quiere implementar. 

## Posible Solución

Cambiar la imagen por un png con fondo realmente transparente

## Pasos para reproducir (para bugs)

1. Ir al perfil de cualquier usuario (incluso el tuyo)
2. Ver los problemas resueltos que contengan medalla de calidad

![image](https://user-images.githubusercontent.com/74751751/147792986-0fb00aba-58da-42b2-8ba9-b9ddcb924561.png)

**Comment by heduenas** [comment]
We already have a larger png file of the quality badge with transparent background: https://github.com/omegaup/omegaup/blob/main/frontend/www/media/quality-badge.png

We need to take that and generate a small version with the same dimensions as the current one and replace it.

**Comment by MohitOhlyan** [comment]
I am working on this issue. Can you please assign me this @heduenas @Mau-MD ? Thank You.
