### ISSUE TITLE
[FEATURE] En el formulario para crear un problema, hacer más visible la opción de elegir problema de solo lectura

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6278]
Al crear un nuevo problema, es difícil encontrar la opción problema de solo lectura. 

![Problema de solo lectura](https://user-images.githubusercontent.com/940007/148725706-7a9d4b98-dc08-4674-833e-68317c0e80ba.png)

Una forma de resolverlo puede ser agregar en la parte de arriba los diferentes tipo de problemas que se pueden crear, similar a lo que se hace cuando se crea un concurso.

**Comment by tvanessa** [comment]
ping @heduenas tenemos varios problemas de Karel y también puede afectar su creación.

**Comment by heduenas** [comment]
Ok, hay que mover el campo de "Tipo de problema" al final de la seccion de "Informacion basica".
![image](https://user-images.githubusercontent.com/597815/159184353-b3bd412e-02f4-464c-8510-c36608fe3eae.png)

**Comment by MohitOhlyan** [comment]
Can we just move the entire Validation part in Basic Information? If We move the "Problem Type" to Basic Information, only one field will be left in "Validation". 

I am working on it. So, please let me know if I should Move the just the "Problem Type" or the entire "Validation".

**Comment by heduenas** [comment]
Ok, how about this instead?
* Validation panel is expanded by default when the page loads
* Remove the "(optional)" part from the title
* Move the panel right above "Limits" panel

This way the panel is not left with a single field.

**Comment by MohitOhlyan** [comment]
That sounds good. By 

> Ok, how about this instead?
> 
> * Validation panel is expanded by default when the page loads
> * Remove the "(optional)" part from the title
> * Move the panel right above "Limits" panel
> 
> This way the panel is not left with a single field.

**Comment by MohitOhlyan** [comment]
This sounds good. 
By removing the (optional) part from the title, I should also make the fields necessary in the Validation form?

**Comment by MohitOhlyan** [comment]
> This sounds good. By removing the (optional) part from the title, I should also make the fields necessary in the Validation form?

The form already have a required property to it. So, I guess no changes need in that.
