### ISSUE TITLE
[BUG] No sirve el link al libro de Problemas y Algoritmos de Luis Vargas

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6292]
Al dar click al link del libro Problemas y Algoritmos de Luis Vargas que está en el menú superior en la sección de Ayuda te muestra un 404 Not Found .

**Comment by tvanessa** [comment]
Liga al libro: https://lobishomen.files.wordpress.com/2011/01/libropre3.pdf

Guardar una copia en: `frontend/www/media` y actualizar la liga en el navbar

**Comment by lhchavez** [comment]
mejor hay que guardarlo aquí usando `curl` así como le hacemos con la documentación: https://github.com/omegaup/prod/blob/main/docker/static/Dockerfile así no agregamos archivos grandes al repositorio principal

**Comment by lhchavez** [comment]
también habría que actualizar el Ingress para que se sirva la ruta donde está ese pdf desde ese contenedor: https://github.com/omegaup/prod/blob/d0309e930eea83b2454476d1714d84a64ed116e7/k8s/omegaup/base/frontend/deployment.yaml#L227

**Comment by S4ND1X** [comment]
@lhchavez para tener permisos de modificar el código dentro del repo de prod, como seria el workflow?

**Comment by lhchavez** [comment]
> @lhchavez para tener permisos de modificar el código dentro del repo de prod, como seria el workflow? 
> 

mandar PR normalito. una vez que se le hace merge, Argo CD lo corre por tí para no tener necesidad de agregar permisos a individuos

**Comment by S4ND1X** [comment]
> > @lhchavez para tener permisos de modificar el código dentro del repo de prod, como seria el workflow?
> 
> mandar PR normalito. una vez que se le hace merge, Argo CD lo corre por tí para no tener necesidad de agregar permisos a individuos

va perfecto, muchas gracias!

**Comment by lhchavez** [comment]
también hay necesidad de agregar un redirect permanente de `/img/libropre3.pdf` a `/docs/assets/libroluisvargas.pdf` en `frontend/server/nginx.rewrites` en el repositorio de omegaUp para que no se rompan los enlaces originales.
