### ISSUE TITLE
[BUG] Se puede acceder a la pagina de login aún estando logeado

### ISSUE THREAD

**Issue by hum-sc** [omegaup/omegaup#6293]
## Comportamiento Esperado
Que me redireccione al home cuando trato de ir a la pagina de inicio de sesión, después de logearme.   

*Describe lo que originalmente estabas intentando hacer y cómo esperabas que se comportara la plataforma.*
Me iba a logear, pero una vez estando en la pagina de login le volví a dar en :
![image](https://user-images.githubusercontent.com/67933378/149265822-9bed05fb-a166-46d8-973a-15a46b76f74f.png)

Y me dirigió a la pagina de login con la siguiente query:
![image](https://user-images.githubusercontent.com/67933378/149266969-d0fd4100-1811-4022-b12e-a387e28e024f.png)
Lo cual provocó que me redireccionara a login otra vez.

## Comportamiento Actual
Cuando accedes a login estando logeado, no te redirecciona a home o no te sale un error o algún toast que te diga "ya haz iniciado sesión".

## Posible Solución
Hacer una verificación de inicio de sesion y redireccionar al home si es que ya se ha iniciado sesion, algo tan simple como:

``` javascript

if(isLogged()){
    redirectTo('/');
}else{
    render();
}
```

ejemplo muy basico xd, se que no son las funciones que usan, ni sé si usen js en el router 

## Pasos para reproducir (para bugs)

1. Iniciar sesión
2. Ir a https://omegaup.com/login/
3.  Y ya

## Contexto

No afecta nada, solo creo sería una mejor experiencia de usuario, o no se si cause problemas en el servidor

## Tu ambiente

* Nombre del navegador Microsoft Edge 97
* Sistema Operativo y versión (escritorio o móvil): Windows 11 Home Single Lenguage 21H2
* Link al sitio en el que este problema pasa: https://omegaup.com/login/?redirect=%2Flogin%2F
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/67933378/149267298-36539d41-7909-4661-9b97-a35955e1b0f4.png)

**Comment by denllx** [comment]
I think this could be solved by reading the login status stored in `CommonPayload`. Could anyone assign this issue to me? @carlosabcs @heduenas
