### ISSUE TITLE
[BUG] No es posible incrementar el tiempo límite total de un problema en más de 1 min 

### ISSUE THREAD

**Issue by omarpaladines** [omegaup/omegaup#6307]
## Comportamiento Esperado

Necesito incrementar el tiempo total del problema en más de 1 minuto ya que tengo varios casos y creo que no alcanza a evaluar todos en 1 min.

## Comportamiento Actual

Me da "bad request" al cambiarlo. Pero puedo reducirlo o cambiar otras cosas del problema y no pasa nada.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Cambiar el límite total de tiempo de cualquier problema a más de 60 segundos.

## Contexto

Necesito incrementar el tiempo total del problema en más de 1 minuto ya que tengo varios casos y creo que no alcanza a evaluar todos en 1 min.

## Tu ambiente
Chrome en una Surface Laptop.

**Comment by lhchavez** [comment]
actualmente esto funciona como se espera: no podemos extender este tiempo más allá de un minuto (por ahora) porque eso causa _muchos_ problemas en la infraestructura.

**Comment by omarpaladines** [comment]
Entendido. Gracias por la aclaración. Alguna recomendación distinta a disminuir el número de casos?

**Comment by lhchavez** [comment]
esa es la mejor opción por el momento: cambiar el número o la complejidad de los casos.
