### ISSUE TITLE
[BUG] En un concurso, la detección de orígenes para los usuarios se rompió.

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6319]
Hola amigos de omegaUp.

El concurso https://omegaup.com/contest/E3ADA2021OCSI01/activity/ dice que todos los usuarios (incluyéndome) tuvimos la misma dirección de origen. Aunque se pudiera dar el caso de que un alumno le haga el examen a todos los demás o de que haya una misma IP asignada para todos los que estén conectados en una red institucional, en el caso de este concurso eso no ocurrió (seguimos en clases en línea y sigo en mi casa).

![image](https://user-images.githubusercontent.com/19719969/150586318-91b032b9-058d-4eb2-8bb5-907aea5b5f0b.png)

**Comment by tvanessa** [comment]
pasó sólo en este concurso?

**Comment by darkmx** [comment]
Nop, pasó también con https://omegaup.com/contest/ERADA2021OI01/activity/ que ocurrió la semana pasada.
![image](https://user-images.githubusercontent.com/19719969/155033070-6c653f63-e986-48da-b13a-cf5f29e971b5.png)

**Comment by pabo99** [comment]
@lhchavez, comentabas que esto podría ser ocasionado por kubernetes, sabes como se podría solucionar?

**Comment by lhchavez** [comment]
a ver, hice un cambio en el sandbox. pueden checar a ver si ya se arregló?

**Comment by darkmx** [comment]
Mañana les puedo confirmar en la plataforma live si el fix ya está online (hoy pondré un concurso al que entrarán los alumnos mañana).

**Comment by lhchavez** [comment]
no se ha hecho el fix en producción, sólo en el sandbox. me da miedo darle push a ese cambio a producción hasta que no se haya validado en el sandbox ^^;;

**Comment by darkmx** [comment]
Ah ok, entonces checaré en el sandbox ahorita y les digo (me confundí entre el sandbox.omegaup.com y el sandbox como componente de la plataforma).

**Comment by darkmx** [comment]
Pues hice el concurso https://sandbox.omegaup.com/contest/gomito/activity/ e hice accesos y un par de envíos desde IPs distintas (reinicié el modem tres veces). Esto es lo que ocurre:

![image](https://user-images.githubusercontent.com/19719969/155889491-2e46e3ba-2b83-4624-a50b-4540262ca29b.png)

**Comment by darkmx** [comment]
Update: parece no funcionar:

![image](https://user-images.githubusercontent.com/19719969/155889894-1376dc2b-329f-4846-8b8d-c92242ca4e6c.png)

**Comment by lhchavez** [comment]
ok, a ver segundo intento. ahora en vez de hacer el cambio en el nginx ingress, se está haciendo en el nginx del frontend (todavía sólo en el sandbox).

**Comment by darkmx** [comment]
Aparentemente ya quedó:

![image](https://user-images.githubusercontent.com/19719969/155905039-50ea7034-dca7-475d-b42f-d36363fbd3f5.png)

**Comment by lhchavez** [comment]
hurra! :D deja le doy deploy al fix de verdad entonces. gracias por confirmar!
