### ISSUE TITLE
[BUG] Internal server error al accesar o crear a problemas

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6328]
Hola amigos de omegaUp.

Desde al menos hace como media hora, la plataforma está arrojando muchos "HTTP/1.1 500 - Internal Server Error" al intentar entrar a problemas. Se arregló solito hace unos minutos, pero no duró mucho bien y otra vez está igual.

**Comment by darkmx** [comment]
Ahorita ya revivió pero ahora aparece esto al crear:
![image](https://user-images.githubusercontent.com/19719969/150805935-207a86ff-dd83-4ddb-b905-de2db2e4756b.png)

Desconozco en dónde podría ver un mensaje de error más detallado.

**Comment by darkmx** [comment]
Acaba de funcionar (lo intenté como 10 veces y ahorita se desatoró).

**Comment by darkmx** [comment]
Pero no lo pude ver XD supongo que revivirá dentro de otro rato.

![image](https://user-images.githubusercontent.com/19719969/150809708-f0696bb9-b694-4ee0-a505-ca4997f0907d.png)

**Comment by darkmx** [comment]
Al intentar agregarle problemas a un concurso, sale esto:

`{"status":"error","error":"{untranslated:serviceUnavailable}","errorname":"serviceUnavailable","errorcode":503,"header":"HTTP\/1.1 503 SERVICE UNAVAILABLE","_id":"61eec3b8920a6927327209"}`

**Comment by lhchavez** [comment]
tengo la sospecha de que fue el deployment del sábado. intentaremos hacer otro deployment que trae un fix a ver si la situación mejora.

**Comment by darkmx** [comment]
ahorita un alumno me dijo que desde ayer está así, así es que es probable (no usé omegaUp ayer así que no me di cuenta)

**Comment by lhchavez** [comment]
ya se arregló?

**Comment by darkmx** [comment]
Ahorita están en examen y no se ha muerto (les dije que si fallaba lo reagendaríamos pero eso no ha ocurrido).

**Comment by lhchavez** [comment]
excelente! tentativamente cerrando esto entonces. reábrelo si vuelve.
