### ISSUE TITLE
[FEATURE] Limpiar el modal al solicitar abrir los detalles de un envío

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6336]
Hola amigos de omegaUp.

Ando investigando posibles intermitencias en https://omegaup.com/api/run/details (cuando tenga más detalles subo el issue), pero de una vez hago esta sugerencia. Cuando un administrador de problema abre los detalles de un envío para ver el código, luego cierra la ventana modal que se abrió y después elige un envío distinto, se abre la ventana modal pero los contenidos previos de ésta siguen ahí y sólo se sobreescriben hasta que la segunda petición AJAX respondió. Como ahorita https://omegaup.com/api/run/details anda tardando un poquitín, ocurre la (breve) confusión de seguir viendo el código del envío previo en lo que el servidor responde.  Es ideal que la interfaz le muestre al usuario alguna señal de que el contenido se está cargando y que debe esperar.

**Comment by heduenas** [comment]
Steps to reproduce:
1. Make a WA/PA submission to any problem.
2. Make an AC submission to the same problem.
3. Click on the details icon for the WA/PA solution.
4. Wait for the details to load.
5. Exit the details window.
6. Click on the details icon for the AC solution.
7. Watch the details window display the WA/PA solution for a few seconds (which is confusing to the user) while it loads the AC solution details.

Solution: Clear the payload of the solution details component whenever a new solution is requested.

**Comment by AlejandroGY** [comment]
Hola, quisiera trabajar en este issue pero es la primera vez que voy a colaborar, si es posible ¿Me podrían asesorar un poco para poder resolverlo? Muchas gracias

**Comment by heduenas** [comment]
Asignado! perdón por la tardanza.

**Comment by heduenas** [comment]
El primer paso que debes de seguir es instalar tu entorno de desarollo local https://github.com/omegaup/omegaup/wiki/Instalaci%C3%B3n-de-m%C3%A1quina-virtual. Despues de eso hay que encontrar el archivo .vue que se encarga de renderizar los detalles del envio.

**Comment by MohitOhlyan** [comment]
Can you assign me this. Weekend is coming and I think I would be able to solve this.
