### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaweiCA** [omegaup/omegaup#6340]
## Comportamiento Esperado

*Enviar un código para resolver un problema.*

## Comportamiento Actual

*Dio  JE como veredicto*

## Pasos para reproducir (para bugs)

https://omegaup.com/arena/problem/Coleccionista/#problems 

Por ejemplo en este problema da JE, envíe un código que antes me dio AC y ahora sale Error de Juez como veredicto.

## Contexto

Estaba realizando un concurso interno con algunos estudiantes cuando nos dimos cuenta de este problema.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Versión 97
* Sistema Operativo y versión (escritorio o móvil): Windows 10 
*Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/Coleccionista/#problems
Igual pasa en otros problemas.
* Captura de pantalla:

![image](https://user-images.githubusercontent.com/98440065/151669410-e2e63ac5-2621-4b51-b00f-b29cdf9c0b1e.png)

**Comment by lhchavez** [comment]
Duplicado de #6320
