### ISSUE TITLE
[FEATURE] Redirigir al login cuando una URL de arena/problem no es visible y el usuario no ha ingresado

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6352]
Hola amigos de omegaUp.

Hoy se platicó sobre lo que ocurre cuando un usuario (que no ha ingresado a la plataforma) intenta entrar a un concurso privado mediante el enlace directo: se le muestra un error de 404. Actualmente se le tiene que pedir a los participantes que primero ingresen a la plataforma y luego entren al enlace. Mostrar una pantalla preliminar del concurso tal vez sea algo no deseable, porque se fuga información de que el concurso (privado) sí existe incluso para usuarios sin permiso de verlo. La alternativa es que, si un usuario que no ha ingresado intenta entrar ya sea a un concurso privado o a un _concurso inexistente_, primero que se le redirija al login y luego se le regrese a la dirección del concurso: si existe y tiene permisos entonces ya podrá verlo; en caso contrario ya se le puede mostrar la pantalla 404.

**Comment by pabloaguilar** [comment]
No veo cómo funciona, pero esto parece ya funcionar. Al abirr un link a un concurso privado en una ventana incógnito me lleva directo al login con el redirect apuntando de regreso al concurso

**Comment by darkmx** [comment]
Parece ya funcionar D: aunque el comportamiento que describo sigue ocurriendo en problemas (y en algún momento también en concursos, pero algo lo arregló para ese caso).
