### ISSUE TITLE
[BUG] Yo como usuario nuevo necesito registrar una cuenta 

### ISSUE THREAD

**Issue by MiguelRomero** [omegaup/omegaup#6372]
## Comportamiento Esperado

Necesito generar una nueva cuenta ocupando un correo.

## Comportamiento Actual

Me marca el siguiente error:

![image](https://user-images.githubusercontent.com/5459260/154340171-b1ed51f3-2d6e-4bc8-af70-c5581b72a76c.png)

## Pasos para reproducir (para bugs)

1. Ir a omegaup.com
2. Generar una cuenta usando email

## Contexto

Un usuario intenta crear una cuenta, pero obtiene como respuesta el error mostrado en la parte superior. 

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome LTS
* Sistema Operativo y versión (escritorio o móvil): Escritorio windows 10
* Link al sitio en el que este problema pasa:
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/5459260/154340452-1fdca051-d22d-45fb-a855-9ac3bb934963.png)

**Comment by pabo99** [comment]
En [New Relic](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MjA4OTc4fEFQTXxBUFBMSUNBVElPTnw3MzAzOTc3MQ?account=208978&duration=86400000&state=890e45d6-b4fc-1232-9cd1-10a9151516b9) veo que el error se da al intentar enviar el correo, pero no alcanzo a identificar cual es el motivo:
```bash
Stack Trace
New
Error message:
OmegaUp\Exceptions\EmailVerificationSendException: errorWhileSendingMail in /opt/omegaup/frontend/server/src/Email.php:60
Stack trace:
#0 /opt/omegaup/frontend/server/src/Controllers/User.php(378): OmegaUp\Email::sendEmail()
#1 /opt/omegaup/frontend/server/src/Controllers/User.php(271): OmegaUp\Controllers\User::sendVerificationEmail()
#2 /opt/omegaup/frontend/server/src/Controllers/User.php(102): OmegaUp\Controllers\User::createUser()
#3 [internal function]: OmegaUp\Controllers\User::apiCreate()
#4 /opt/omegaup/frontend/server/src/Request.php(78): call_user_func()
#5 /opt/omegaup/frontend/server/src/ApiCaller.php(26): OmegaUp\Request->execute()
#6 /opt/omegaup/frontend/server/src/ApiCaller.php(103): OmegaUp\ApiCaller::call()
#7 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): OmegaUp\ApiCaller::httpEntryPoint()
#8 {main}
             in newrelic_notice_error called at /opt/omegaup/frontend/server/src/ApiCaller.php (353)
   in OmegaUp\ApiCaller::logException called at /opt/omegaup/frontend/server/src/ApiCaller.php (50)
           in OmegaUp\ApiCaller::call called at /opt/omegaup/frontend/server/src/ApiCaller.php (103)
in OmegaUp\ApiCaller::httpEntryPoint called at /opt/omegaup/frontend/www/api/ApiEntryPoint.php (5)

```

Parece que esto está ocurriendo muy a menudo, según reportan los usuarios.

CC @MiguelRomero

**Comment by darkmx** [comment]
MUY a menudo, ya nos está pegando a nosotros. El lunes inicia el trimestre y los alumnos (y profesores) ya se están poniendo nerviosos de que no pueden registrarse.

**Comment by pabloaguilar** [comment]
En el log en newrelic tampoco dice nada :( Solo aparece el nombre de la
excepción sin explicación alguna de por qué falló.

**Comment by pabloaguilar** [comment]
Ejemplo: https://onenr.io/0BQrKNzX3wZ

**Comment by pabloaguilar** [comment]
Resulta que estaba viendo el log equivocado. Este otro dice que es porque
no se puede conectar al servidor SMTP:  https://onenr.io/01wZKe6EXR6

Supongo que si fue la migración a kubernetes. Ya sea que las credenciales
no se copiaron bien o que algún ACL no le gustan los nuevos IPs.

@lhchavez ***@***.***>  cómo podemos confirmar?

**Comment by pabloaguilar** [comment]
Parece que igual hay problemas para mandar los correos para resetear
contraseñas, me imagino que por el mismo motivo.

**Comment by heduenas** [comment]
Halp! @lhchavez

**Comment by lhchavez** [comment]
échenme la mano porfa https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting posiblemente sea necesario un cambio en el código para meter ese debugging

**Comment by lhchavez** [comment]
ah! algo que acabo de darme cuenta: no será el 2FA? alguien puede ayudar a investigar si eso afectaría y cómo arreglar eso en caso de afectar?

**Comment by lhchavez** [comment]
a ver, ya le cambié el password a la cuenta de SMTP por uno específico a SMTP. a ver si con eso ya queda.

**Comment by pabo99** [comment]
Logré registrarme con una cuenta de gmail. No sé si debamos intentar más pruebas para garantizar que el error haya sido solucionado por completo.

Por otro lado, todos los usuarios que intentaron registrarse y obtuvieron ese error. Tendrán que volver a repetir el proceso. Al menos los que contactaron a @MiguelRomero y @darkmx se les puede enviar un mensaje de que intenten nuevamente.

**Comment by lhchavez** [comment]
> Logré registrarme con una cuenta de gmail.

cómo hiciste eso? mediante el botón de enlazar la cuenta de Google? o con usuario+contraseña? porque el primero no mandar correo nunca.

**Comment by darkmx** [comment]
Me pude registrar (a la antigüita, llenando los datos abajo) pero a medio camino me tiró un error:

![image](https://user-images.githubusercontent.com/19719969/155886820-b72445d7-bdba-4285-93c0-07ddaaa10ef2.png)

**Comment by pabo99** [comment]
> > Logré registrarme con una cuenta de gmail.
> 
> cómo hiciste eso? mediante el botón de enlazar la cuenta de Google? o con usuario+contraseña? porque el primero no mandar correo nunca.

Si fue la primera. Deja intento con otro correo

**Comment by pabo99** [comment]
Ya intenté con la opción de usuario+contraseña y me apareció el mismo mensaje que a Rodrigo. El correo también llegó.

**Comment by lhchavez** [comment]
bien! ahora hay que arreglar ese otro mensaje de error ya que los correos están fluyendo.

**Comment by darkmx** [comment]
No pude ver el JSON que el servidor respondió porque no tenía activada la pestaña de red en ese momento :( y ahorita no tengo otro correo para probar.

**Comment by pabo99** [comment]
El proceso normal sería que una vez que se regsistre el usuario pueda ingresar y que en lugar de que le aparezca la notificación como error, le aparezca como info, pero que le permita navegar dentro de su sesión. ¿Es correcto?

**Comment by lhchavez** [comment]
esa notificación es un error legítimo: algo mandó el servidor que debería ser JSON y no era JSON. hay que arreglar ese error.

no se le debería permitir navegar dentro de la sesión hasta que se valide el correo.

**Comment by pabo99** [comment]
Sigo sin poder ver el error en ambiente local. Y al igual que Rodrigo, me quedé sin correos para poder probar en producción.

Intentaré reproducirlo en el sandbox y poder soluconar el error.
