### ISSUE TITLE
[BUG] Los filtros en el tab de envíos de Cursos no funciona bien

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6374]
Hay varios problemas en el tab de envíos de Cursos: 

- La paginación no funciona, si tiene muchos envíos se activa el botón pero no se actualiza la información que se muestra
- No se puede filtrar por coder 
- Si se filtra por problema, no se muestran todos los envíos

![Envíos en un curso](https://user-images.githubusercontent.com/940007/154571811-4dc8170d-406b-424d-947f-ec64fec650d7.png)

**Comment by tvanessa** [comment]
+ En concursos se autocompleta el username en el campo "Coder", esto no funciona en cursos
