### ISSUE TITLE
Enviar correo con un problema nuevo cada semana

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#639]
Enviar un correo con un problema no resuelto a los usuarios que no han tenido cierta actividad durante algún tiempo.

Incluir la funcionalidad de optar por no recibir correos de este tipo.

**Comment by lhchavez** [comment]
La idea está súper chida, pero no lo hemos tocado en un año.

**Comment by alanboy** [comment]
Chale.

![image](https://cloud.githubusercontent.com/assets/527987/13885042/efb89438-eced-11e5-9df7-622325da3c49.png)

**Comment by rendon** [comment]
+1 por este feature, sí funciona, lo que me pasa con omega up es que se me olvida que existe por semanas o meses. Topcoder, Codeforces y HackerRank envian correos.
