### ISSUE TITLE
[FEATURE] Como un organizador de concursos, quiero poder recalificar una solución para corregir errores

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6393]
## Comportamiento Esperado

Se debería poder deshacer la accion de descalificar un envió

## Comportamiento Actual

Una vez descalificado un envió, no hay forma de deshacer esta acción.

## Posible Solución

Que salga la opción de deshacer descalificación, o que revalidar quite el status de descalificado.

## Contexto

Descalifique un envió equivocado por accidente y me gustaría deshacer este hecho.

**Comment by tvanessa** [comment]
Duplicado de #2119
