### ISSUE TITLE
[BUG] La edición de un concurso restablece la opción "Mostrar a todos [...] por defecto"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6398]
Hola amigos de omegaUp.

En la continuación de #5588, modificar algo del concurso (ej. descripción, fecha, etcétera) desactiva la opción "Mostrar a todos los concursantes en el scoreboard por defecto". Esto se puede reproducir activando la opción, guardando, modificando algo del concurso, recargando la página y viendo el estado de la opción.

![image](https://user-images.githubusercontent.com/19719969/155904173-db511757-78e4-418d-b8f8-0cc3f98dfd05.png)

**Comment by ahmedr2001** [comment]
Is this bug still up for fixing? If so, I'd like to work on it.

**Comment by darkmx** [comment]
Still relevant.

**Comment by heduenas** [comment]
@ahmedr2001, can you please confirm your omegaup username?

**Comment by ahmedr2001** [comment]
> @ahmedr2001, can you please confirm your omegaup username?

AhmedAbdelatty

**Comment by heduenas** [comment]
Thank you for confirming!

**Comment by ahmedr2001** [comment]
I think this fixes it.

**Comment by pabo99** [comment]
> I think this fixes it.

Thank you for fixing the issue. Soon we'll review the PR
