### ISSUE TITLE
[BUG] Error al mandar correo de verificación al crear cuenta en omegaup.com

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#6399]
## Comportamiento Esperado

Usuario debería poder recibir correo de verificación al crear una cuenta en omegaup.com.

## Comportamiento Actual

Al intentar crear una cuenta el usuario recibe el siguiente mensaje de error

> There was an error sending the verification email. Please try again later or contact omegaup-soporte@googlegroups.com for support. Your email is not verified yet.

Imagen:
![IMG_0800](https://user-images.githubusercontent.com/684205/156484322-0697a5fd-d621-4ddd-a9d8-df0be54dd5ac.JPG)

## Pasos para reproducir (para bugs)

1. Ir a omegaup.com
2. Introducir datos válidos para crear una cuenta
3. Mandar forma de creación de cuenta
4. Observar mensaje de error

## Contexto

Estudiantes de una clase en Washington, EEUU han intentado crear cuentas por las última semana sin éxito.

Hemos intentado usar 3 diferentes redes: wifi de la organización y dos hotspots de nuestros celulares y diferentes computadoras y celulares, y ninguna combinación nos ha permitido crear una cuenta.

Antes de empezar a ver este mensaje pudimos crear un par de cuentas sin ningún problema. Desde que vimos el mensaje por primera vez no hemos podido crear cuentas.

Yo pude crear una cuenta al llegar a mi casa.

## Tu ambiente

* Nombre del navegador: Chrome
* Sistema Operativo y versión (escritorio o móvil): Windows, iOS, Android
* Link al sitio en el que este problema pasa: omegaup.com

**Comment by MiguelRomero** [comment]
Hello @rcxr 
¿Han mandado un correo a soporte?

¿Puedes indicarme algunas cuentas para ver si fueron creadas correctamente? 

Saludos!

**Comment by rcxr** [comment]
Una cuenta fue creada con rafa@rcxr.mx

Las demás no tengo los correos, pero desde que empezamos a ver este mensaje no hemos podido crear ni una cuenta nadie en la clase.

**Comment by rcxr** [comment]
Mmm por alguna razón a mí si me llegó el correo de verificación y ya pude verificar mi cuenta. Mis estudiantes me cuentan que no han recibido el correo. Les voy a pedir que vuelvan a checar.

**Comment by rcxr** [comment]
Listo. Ya actualicé el bug.

Desde mi casa en Seattle, WA puedo crear una cuenta, pero desde 3 diferentes redes (el wifi de la escuela, y desde los hotspot de dos diferentes celulares) nos sale ese error de forma constante.
