### ISSUE TITLE
[BUG] Cuando se actualiza un zip de un problema, la version del problema se actualiza automáticamente en los concursos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6405]
Hola amigos de omegaUp.

Anteriormente, actualizar el zip de un problema que es usado en un concurso no tenía ningún efecto en los envíos de ese concurso, salvo que el administrador decidiera especificar manualmente que sí desea usar esa nueva versión (esto se puede hacer en la lista de problemas del concurso o en la lista de versiones del problema mediante un botón). Sin embargo, esto ya no está ocurriendo así. 

Tengo un concurso que está usando el problema https://omegaup.com/arena/problem/Evaluando-una-formula-gigante. Por fuera del concurso descargué el zip del problema y lo volví a subir. Esto hizo que todos los envíos del concurso se reevaluaran sin intervención mía:

![image](https://user-images.githubusercontent.com/19719969/156899468-4e8a16ad-e4f2-4acd-9800-10c5aa483acf.png)

![image](https://user-images.githubusercontent.com/19719969/156898795-3661f9cc-dffa-45eb-b66b-0e622de8f167.png)

Dentro del problema (fuera del concurso) parece que algunos envíos no se reevaluaron, pero los del concurso sí (¿será porque soy el admin de ese concurso, pero no de otros?). 

![image](https://user-images.githubusercontent.com/19719969/156899299-27af826d-2e61-4740-ad47-bd60daaece3a.png)

Lo realmente malo: una vez reevaluados, el tiempo de penalización se calculó sobre el tiempo de reevaluación y no sobre el tiempo del envío original.

![image](https://user-images.githubusercontent.com/19719969/156899863-246a5f41-d161-4eae-aa14-63bb57cc0ee2.png)

**Comment by tvanessa** [comment]
primero hay que arreglar lo del zip. 
Si la reevaluación falla cuando la pides explicitamente se pone en otro issue.

**Comment by darkmx** [comment]
Desconozco si la reevaluación explícita falla. Independientemente de si la reevaluación ocurrió por error o de forma intencional, la penalización debe calcularse bien.

**Comment by pabo99** [comment]
La primera parte del cambio que corresponde a conservar la versión de un problema en los concursos cuando a este probelma se actualiza el zip ya quedó.

Ahora sólo falta revisar la parte donde se reevalúan los envíos de este problema una vez que se edita. Ya que estoy revisando el código y parece que la condición que se tiene es que se reevaluen los envíos del problema cada vez que exista un nuevo commit. Entonces para arreglar eso, ¿tendríamos que también validar que los envíos no correspondan a un problema dentro de un problemset?

**Comment by darkmx** [comment]
Creo que antes se hacía así D: tengo la impresión de que estamos hablando de una regresión si ya no ocurre de esa forma.
Es decir, los envíos de un concurso deberían permanecer congelados aunque se actualice el problema, salvo que ocurra una de dos cosas:

1) Que el admin del concurso actualice la versión del problema.
![image](https://user-images.githubusercontent.com/19719969/157545519-f3d2837f-bd30-4053-a2cb-4e634785ca72.png)

2) Que el admin del problema le pique aquí para actualizar sus propios concursos:
![image](https://user-images.githubusercontent.com/19719969/157545307-4bcb9050-7895-47eb-9acb-e120063b2a63.png)
