### ISSUE TITLE
[BUG] Las imagenes de los problemas no cargan correctamente

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6406]
## Comportamiento Esperado

Las imagenes de los problemas no cargan siempre
## Comportamiento Actual

De vez en cuando (muy frecuente, como 1 de cada 2 veces) que cargo un problema, algunas imagenes del problema no cargan y salen con su texto alterno y el icono de foto rota.

Esto se corrige si recargas la pagina repetidas veces hasta que todas las imágenes carguen.

## Posible Solución

Hacer que funcione correctamente

## Pasos para reproducir (para bugs)

Abre un problema con imágenes (puede que esto sea exclusivo a curso, pero no creo). y hay una posibilidad de que la imagen no cargue.

Si no cargan algunas imágenes, recarga la pagina repetidas veces hasta que funcione.
## Contexto

Este issue ya lleva rato sucediendo. En problemas de Karel es super-critico porque la entrada y salida depende de imágenes.

## Tu ambiente
Me ha sucedido en dos diferentes redes y dos computadoras (ambas con windows).

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Versión 99.0.4844.51 (Build oficial) (64 bits)
* Sistema Operativo y versión (escritorio o móvil): Windows 10 escritorio 10.0.19044 Compilación 19044
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/OMIPS-2020-Karretera (Y muchos otros).
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/19498800/156934932-1f5a2fbf-a36f-48c6-8a2c-051db365ef58.png)

**Comment by tvanessa** [comment]
Esto pasa en casi todos los problemas o algunos en específico?

Si has creado un problema y le pasa esto, puedes compartirnos la extensión de tu archivo de la imagen?

**Comment by kishtarn555** [comment]
Hola, a mi me pasa con problemas creados por mi y por otros.
Sucede en casi todos los que tienen imagen, pero no siempre
Uso .png para mis fotos

**Comment by qihqi** [comment]
A mi tambien me ha pasado eso. Problema de ejemplo: https://omegaup.com/arena/problem/P4MATRICES/

**Comment by kishtarn555** [comment]
Sí, y es bastante molesto, también sucede con lecturas y eso dificulta mucho hacerlas. Creo que no solo sucede en los cursos.

Estaría bastante genial si lo arreglan porque creo que si afecta bastante a la experiencia.

**Comment by pabo99** [comment]
En ambiente local ya estuve agregando problemas con imágenes y en todos los casos se muestran correctamente, aún si actualizo varias veces la página. 

En producción si logro reproducir el error con el problema https://omegaup.com/arena/problem/OMIPS-2020-Karretera, pero lo único que se muestra en la consola de desarrollador es que no existe el recurso (404). Revisaré logs de New relic para ver si nos muestra más información que pueda ayudar a dar con el error de raíz.

**Comment by qihqi** [comment]
ya me sale el imagen, gracias!

**Comment by kishtarn555** [comment]
Yo sigo teniendo problemas con este bug hoy en día (10 julio 2022).

![image](https://user-images.githubusercontent.com/19498800/178148794-0bfc55da-f211-4075-b7db-4894c23d86c2.png)

Recargando:
![image](https://user-images.githubusercontent.com/19498800/178148815-a805f4f9-2c5b-4d6e-96da-7549d9213235.png)
