### ISSUE TITLE
Rankeo del organizador del concurso

### ISSUE THREAD

**Issue by sergio10barca** [omegaup/omegaup#642]
Sería bueno que cuando se organiza un concurso el organizador pueda opcionalmente aparecer en el ranking global :).

**Comment by lhchavez** [comment]
@alanboy también quiere esto y tenía ideas de cómo implementarlo. Asignándolo a él como dueño.

**Comment by alanboy** [comment]
Necesito verificar porque segun yo estoy ya esta.

**Comment by elendil326** [comment]
@alanboy @lhchavez esto ya esta o nel?

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/2064

**Comment by elendil326** [comment]
Cerrando como dupe
