### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ibrahim-muhummad10** [omegaup/omegaup#6429]
google summer of code discord channel doesn't exits which refered to in the contrubution guide.

**Comment by heduenas** [comment]
This is the link to the discord channel: https://discord.com/channels/832682734115094638/951215673424613486

Can you please share a link to the page you are looking at that doesn't have the correct link?

**Comment by ibrahim-muhummad10** [comment]
![dis](https://user-images.githubusercontent.com/54406390/158785407-b91b9749-5893-4d50-b2c9-540e55472bcf.PNG)
this the same thing!

**Comment by MohitOhlyan** [comment]
I think this occurs while opening the channel on web page if you don't get redirected to discord desktop app. I think there are two solutions you should try:
1st:- Try clearing cookies of discord on your web browser if you use Discord desktop app. 
2nd:- Try a invite link to the discord server instead. https://discord.gg/BhU5tu7f . I hope it does not matter If I share invite link here. But the admin can share a invite link directly on the wiki page.

**Comment by ibrahim-muhummad10** [comment]
thank you i got the invite
