### ISSUE TITLE
[FEATURE] make user ranking less confusing

### ISSUE THREAD

**Issue by denllx** [omegaup/omegaup#6434]
## Expected Behavior

1. Users with same score with have same rank.
2. User's rank on the ranking page should be consistent with their profile.

## your environment

* Browser name (e.g. Chrome 39, node.js 5.4): Chrome 99
* Operating System and version (desktop or mobile): desktop
* Link to the site where this problem happens: https://omegaup.com/rank/authors/?page=5
* Screenshot:
![image](https://user-images.githubusercontent.com/42374096/159007742-08241657-fd85-4043-961a-3bf8b654a9ac.png)
In this screenshot, 4 users have the same score: 2.98, but they have different rank: 401, 402, 402, 404.
![image](https://user-images.githubusercontent.com/42374096/159007990-05713567-17ba-444f-a0f3-5155bcc43290.png)
In this screenshot, the user SocratesH has ranking 1890 on his profile, but has 401 on the global ranking page.

**Comment by shiyw1209** [comment]
Hi, I'm interested in solving this bug. But I am completely new to this. Could you please give me some guidance on where to start? Thx in advance!

**Comment by heduenas** [comment]
![image](https://user-images.githubusercontent.com/597815/159826056-5d1ba879-b530-4987-bcd3-98a23d78da14.png)

@pabo99 is proposing adding the contributor rank to the user profile like shown in the image. I think we should do that. However, if a user has not made any constributions I think we should not show any contributor ranking for them.

Also, the contributor score might have several decimal places that are trucated when displaying the ranking in the UI. And that *might* be the reason why constributors with equal scores (considering only 2 decimal places) have different ranking. We should check if that's what's causing the issue. If that's not the case then it is indeed something we should fix.

**Comment by pabo99** [comment]
Check out this block of code:
https://github.com/omegaup/omegaup/blob/0840454399cbe247e52142ea3bbc9dbc363ce523/frontend/www/js/omegaup/components/user/SidebarMainInfo.vue#L19-L31

and 
https://github.com/omegaup/omegaup/blob/0840454399cbe247e52142ea3bbc9dbc363ce523/frontend/www/js/omegaup/components/user/MainInfo.vue#L20-L32

Here is where we print the ranking of the requested user profile. Now, inside the `profile.rankinfo` object we have the `author_rank` parameter too. You can reuse those blocks to implement the new feature.

**Comment by pabo99** [comment]
Sure.

**Comment by andyroberto321** [comment]
@heduenas "Also, the contributor score might have several decimal places that are trucated when displaying the ranking in the UI. And that might be the reason why constributors with equal scores (considering only 2 decimal places) have different ranking." That you said is correct, in which section is the range decided? Which .ts? to modify it

**Comment by andyroberto321** [comment]
@heduenas @pabo99 "Also, the contributor score might have several decimal places that are trucated when displaying the ranking in the UI. And that might be the reason why constributors with equal scores (considering only 2 decimal places) have different ranking." That you said is correct, I think the same. I have to modify it from where they start to order them from highest to lowest according to everyone's score, and I think that would be only in the backend.
![Captura](https://user-images.githubusercontent.com/70920376/163253918-6c43eefa-c971-4b43-96c7-7d2d80f52749.PNG)

**Comment by andyroberto321** [comment]
The range between people is different because of the decimals of each user, What do you think if when you put the cursor over the score of each user, the total score appears? and so the person can see why he is in a different position.

**Comment by heduenas** [comment]
I do like that proposal. @tvanessa to confirm if that UX is okay.

**Comment by andyroberto321** [comment]
![image](https://user-images.githubusercontent.com/70920376/163697098-e6e11171-453f-4c17-899c-9d600ccf71c4.png)
@tvanessa Here is an example of what it would look like, in this way people can already see their complete score and there would be no confusion about why one is not in a different range
![image](https://user-images.githubusercontent.com/70920376/163697085-f640ce80-fdae-4fef-9216-846d90cdee41.png)

**Comment by Anurag-Singh-04** [comment]
Hey @denllx , 
I believe that since this issue has not been closed till now, can I work on this issue.

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue

**Comment by Cronus1007** [comment]
Hi @pabo99 @heduenas , can I take up this issue?

**Comment by heduenas** [comment]
Hi @Cronus1007 have you had a chance to take the programming test at https://omegaup.com/arena/gsoc2023/#ranking ? That's a prerequisite before you can start fixing issues.

**Comment by AuroraPrz18** [comment]
Hi, I'm applying for GSoC2023, I have already completed the programming test (4/4). Can I be assigned to this issue?

**Comment by heduenas** [comment]
Thank you @AuroraPrz18 for helping with this issue. I've assigned it to you!

**Comment by AuroraPrz18** [comment]
Hey @heduenas Reading comments I noticed that here we have to requested features. The first one is to add the contributor rank into the profile, and the other one just make user ranking less confusing.
Which one should I focus on first?

And another question, I saw a proposal for this issue: that when cursor is over the rank shows completelly, but I don't see a confirmation for the UI. Is it okay to continue with that proposal or should I wait for a confirmation? Or another option could be to show the complete rank in a tooltip when the cursor is over.

**Comment by heduenas** [comment]
Good questions @AuroraPrz18 . I would say let's prioritize the "make user ranking less confusing" one. Unless @tvanessa disagrees, I like the idea of doing the tooltip with the full score.

**Comment by tvanessa** [comment]
I think you're right and there are two things to solve.
 - First, "make user ranking less confusing" would be easily solved by specifying the rank name in the profile bio. In this case changing the string `Rank` for `User ranking` and their translations. 
 ![bioomegaup](https://user-images.githubusercontent.com/13296248/224930452-f9447834-714e-4253-aa6b-db4b244e2d6d.png)

 - Now, regarding the complete rank. We always have to truncate numbers  and I see that we truncate differently in our existing ranks, but it should be consistent. My suggestion is to use the method (for truncation) in `https://omegaup.com/rank/` for the rest of the tables.  Also, for every ranking page we should have a link with the explanation of how the rank works.
 ![Screen Shot 2023-03-14 at 1 32 36 AM](https://user-images.githubusercontent.com/13296248/224929491-43a8cc74-cadf-4cf2-8e06-f284200154e2.png)
 Here are some links to the explanations: 
  - https://blog.omegaup.com/ranking-de-escuelas-en-omegaup/
  - https://blog.omegaup.com/el-nuevo-ranking-de-omegaup/

**Comment by AuroraPrz18** [comment]
Thanks @tvanessa , is there any link to the explanation of Contributor rank? 

And I see that you mention the link for school ranking, but I found this other link, which is most updated, should I use it? https://blog.omegaup.com/el-nuevo-ranking-de-escuelas-de-omegaup/

**Comment by AuroraPrz18** [comment]
I just created a new issue, as was suggested, in order to have all the information needed to end this feature #7008
