### ISSUE TITLE
[BUG]  Outdated command in "How to make a Pull Request" wiki page.

### ISSUE THREAD

**Issue by MohitOhlyan** [omegaup/omegaup#6435]
### Improve the Wiki Docs on Omegaup

Update the Git commands that are now outdated in Wifki Pages. I found one where the "git checkout master" doesn't work anymore and gives error. 

If we follow the "How to make a Pull Request" wiki page, after forking and cloning the omegaup repository, running the command "git checkout master" doesn't work and raises an error "error: pathspec 'master' did not match any file(s) known to git". 

There will be more possible new updates, I will add them as I find them. 

## Comportamiento Esperado
The command should normally checkout a user to the master branch on the local device using git workflow. But since the master branch is depreciated by git when you make a new fork. The master branch is replaced by main branch. 

## Comportamiento Actual

Raises error:- 
error: pathspec 'master' did not match any file(s) known to git.

## Posible Solución

Replace "master" to "main" in "git checkout master".  Updating the content on the git wiki pages should do it. 

## Contexto
As new users don't know the change of "master" begin renamed to "main" by github, they run into this error while trying to contribute to omegaup and it delays and creates confusion for new git users. 

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome
* Sistema Operativo y versión (escritorio o móbil): Linux, bash shell. 
* Link al sitio en el que este problema pasa:https://github.com/omegaup/omegaup/wiki/How-to-Make-a-Pull-Request-(English)
* Captura de pantalla:
![Screenshot from 2022-03-18 01-29-10](https://user-images.githubusercontent.com/63846699/159034380-932e69d9-46bd-4920-b933-e925b496af83.png)

**Comment by MohitOhlyan** [comment]
Done Editing the wiki pages. Do this require a PR too?

**Comment by pabo99** [comment]
For this change, PR is no needed. 


Thanks for your help.
