### ISSUE TITLE
Link roto a problemas

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#645]
El link a problemas aqui ya no funciona: http://blog.omegaup.com/2014/06/el-nuevo-ranking-de-omegaup/

Sera que new relic nos diga cuantos 404 estamos regresando a otros links que rompimos ?

**Comment by lhchavez** [comment]
newrelic no tiene memoria (si quieres ver el pasado por más de unos cuantos días, hay que pagar). Lo único que podemos hacer es parsear los logs, pero quién sabe cuándo fue la última vez que se borraron.

Ya arreglé ese link, así que cerraré este bug.
