### ISSUE TITLE
[FEATURE] (Concursos con subtareas) Pruebas automatizadas en Cypress

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#6453]
Concursos por subtareas

**Comment by heduenas** [comment]
No se van a poder hacer estas pruebas porque el entorno de las pruebas no tiene grader.

**Comment by pabo99** [comment]
En selenium teníamos una forma de actualizar los puntajes de los envíos:

- Se realizaba el envío como se hacen normalmente
- Se obtenía el `guid` para actualizar el score en la DB directamente
- Se utilizaba una API (que sólo funciona desde las pruebas si no mal recuerdo) para actualizar el scoreboard

Desconozco si en cypress podemos hacer algo similar, pero he visto que hay librerías para conectarnos a MySQL: https://gist.github.com/fityanos/0a345e9e9de498b6c629f78e6b2835f5

Ya le había cometnado a Shivam, que podía hacer algo similar

**Comment by heduenas** [comment]
Tienes una liga en nustro codigo a un ejemplo en selenium?

**Comment by pabo99** [comment]
Tengo el link al PR donde se borró ese código:

Aquí se mandan llamar las 2 funciones que nos interesan:
https://github.com/omegaup/omegaup/pull/7085/files#diff-55081f3df67944fde9309053f52b277f0b49a25e87a5593f720f7f06466e77a8L44-L48
```py
    with driver.login(user, password):
        create_run_user(driver, contest_alias, problem, 'Main_wrong.cpp17-gcc',
                        verdict='WA', score=0)

    update_scoreboard_for_contest(driver, contest_alias)
```

- La primera es `create_run_user`, que una vez creado el envío, se encarga de actualizar el score con estas funciones:
https://github.com/omegaup/omegaup/blob/4b9e94748778ca7747795226d8d356b957998552/frontend/tests/ui/conftest.py#L390-L416

y

https://github.com/omegaup/omegaup/blob/4b9e94748778ca7747795226d8d356b957998552/frontend/tests/ui/conftest.py#L342-L360

- La segunda es `update_scoreboard_for_contest` que se encarga de actualizar el scoreboard:
https://github.com/omegaup/omegaup/pull/7085/files#diff-55081f3df67944fde9309053f52b277f0b49a25e87a5593f720f7f06466e77a8L370-L380

```py
def update_scoreboard_for_contest(driver, contest_alias):
    '''Updates the scoreboard for a contest.
    This can be run without a session being active.
    '''

    scoreboard_refresh_url = driver.url(
        '/api/scoreboard/refresh/alias/%s/token/secret' %
        urllib.parse.quote(contest_alias, safe=''))
    driver.browser.get(scoreboard_refresh_url)
    assert '"status":"ok"' in driver.browser.page_source
```
