### ISSUE TITLE
[BUG] api/run/details/ está tardando mucho y a veces da error interno

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6459]
Hola amigos de omegaUp.

Tengo un programita que uso para descargar los códigos de mis alumnos y desde hace algunos meses noté que api/run/details/ estaba tardando mucho más de lo usual. Ahorita está tardando como 10 segundos en obtener los datos de diez envíos (antes era casi instantáneo), además de que a veces está tardando mucho más y se llega a algún tiempo límite de la plataforma, dando error interno como consecuencia. Esto ocurre de forma intermitente pero frecuente.

![image](https://user-images.githubusercontent.com/19719969/159608780-85bae7d9-00ba-4772-b56b-5db04420ffce.png)

Necesité intentar correr mi programa seis veces para lograr que se descargaran exitosamente los 33 envíos en la misma ejecución. Esto me ocurrió en el problema https://omegaup.com/arena/problem/El-ciclo-de-vida-de-las-bacteria y van los ID de errores que se generaron en mis intentos:

623a80c57c4b5615657240
623a7fe1c9491368883598
623a7f9f83e60709782865
623a7f5be4b7a667709495
623a7f3d14175504927289

**Comment by darkmx** [comment]
Follow-up: ahorita estaba intentando descargar los códigos de un examen que hice hoy y me estaba siendo imposible lograrlo (error interno una y otra vez). El código de mi programa arma múltiples peticiones cURL y espera a todas ellas usando curl_multi_getcontent de PHP. Normalmente intento descargar los códigos de 10 en 10, aunque eso es configurable. Acabo de moverle a mi código para descargarlos uno por uno y no tuve problemas (salvo la lentitud de la secuencialidad). Eso apunta a que el error en la plataforma se está provocando cuando hay múltiples peticiones en paralelo.

**Comment by lhchavez** [comment]
> Follow-up: ahorita estaba intentando descargar los códigos de un examen que hice hoy y me estaba siendo imposible lograrlo (error interno una y otra vez). El código de mi programa arma múltiples peticiones cURL y espera a todas ellas usando curl_multi_getcontent de PHP. Normalmente intento descargar los códigos de 10 en 10, aunque eso es configurable. Acabo de moverle a mi código para descargarlos uno por uno y no tuve problemas (salvo la lentitud de la secuencialidad). Eso apunta a que el error en la plataforma se está provocando cuando hay múltiples peticiones en paralelo.
> 

justo eso iba a mencionar: ese codepath es muy lento y le damos cuello si se excede cierto límite para no sobrecargar al servidor. las peticiones en paralelo estaban complicando las cosas :S

**Comment by darkmx** [comment]
X_X entonces le bajaré a la concurrencia de mi programa de manera definitiva.
De todos modos, conviene que mencione que la solicitud de un código individual anda tardando más o menos un segundo. Supongo que la tabla involucrada en la consulta es gigante y eso no ayuda; lo menciono sólo por si se llegara a identificar alguna forma razonable de acelerarla. 

No sabría si cerrar el issue o no (por lo de la posible aceleración del caso individual). Si se estima que eso no se puede mejorar mucho o fácilmente, entonces siéntanse libres de cerrar este issue.

Gracias!

**Comment by lhchavez** [comment]
ah ese código no vive en una tabla: vive en s3! eso es lo que lo hace más lento hoy en día

**Comment by darkmx** [comment]
omg! es cierto, entonces cerraré el issue.
Supongo que en el futuro se podría intentar acelerar, pero ya habrá tiempo para eso. No creo que valga la pena dejarlo abierto ahorita.
