### ISSUE TITLE
[FEATURE] Como un [aplicante], quiero [entrar en el servidor de discord] para [preguntar o proponer ideas]

### ISSUE THREAD

**Issue by Erev14** [omegaup/omegaup#6460]
## Comportamiento Esperado

Poder acceder al grupo de discord si estas o no en el desde la wiki https://github.com/omegaup/omegaup/wiki/Google-Summer-of-Code-2022/#ideas-list, tambien seria bueno que añadieran el mismo url a la pagina de https://www.omegaup.org/

## Comportamiento Actual

Si no estas dentro del canal y presionas cualquier enlace de [Discord channel](https://discord.com/channels/832682734115094638/951215673424613486)! te muestra la siguiente pantalla:
![image](https://user-images.githubusercontent.com/15682064/159643491-9d5c8787-4a8c-42ff-af07-7107623292b0.png)

## Posible Solución

Cambiar todos los enlaces de Discord channel por el enlace de la invitación a https://discord.gg/K3JFd9d3wk

## Alternativas consideradas

Añadir un enlace de join to discord channel con el link de la invitación a https://discord.gg/K3JFd9d3wk,
esto haría que pongan ambas opciones Discord channel o join to discord channel

## Contexto

Quiero aplicar en el Google Summer of Code 2022 y tuve que buscar cual era el link correcto, lo cual no fue tan fácil porque solo lo encontre en omegaup.com al final de la pagina, y para nuevos aplicantes o estudiantes actuales que no pertenecen al canal de discord puede ser dificil.

## Tu ambiente
Brave [Versión 1.36.119 Chromium: 99.0.4844.83 (Build oficial) (64 bits)](https://brave.com/latest/)

**Comment by AuroraPrz18** [comment]
Is this issue still needing fix? All the links on omegaUp are working well for me. Where can I found it not working?
