### ISSUE TITLE
[BUG] Error de tiempo de espera entre envíos durante un concurso

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6462]
Hola amigos de omegaUp.

Hoy tuve examen (concurso desde el punto de vista de la plataforma) y dos alumnos tuvieron problemas al hacer envíos en https://omegaup.com/arena/E1AED2022ICMIXT02
![image](https://user-images.githubusercontent.com/19719969/159800606-b8fcb947-6a83-41ba-907e-f13392cf96e8.png)

Ese contador (haciendo cuentas, el equivalente de 48 horas) les aparecería a pesar de que no habían hecho envíos. Es decir, eso de "entre cada envío del mismo problema" no aplica. Actualizar la página no funcionaba.

**Comment by darkmx** [comment]
Follow-up: hoy tuve examen otra vez y la mitad de las computadoras tenían mal la hora (disclaimer: en el comentario original los alumnos estaban usando sus propios equipos, en el de hoy usaron las computadoras del salón). El bug volvió a aparecer. Creí que si ponía el problema público y les pedía que lo resolvieran desde ahí no habría problemas. Grave error: aún fuera del concurso, ese letrero aparece. La consecuencia directa fue que la mitad de mis alumnos no pudieron hacer el examen.

**Comment by lhchavez** [comment]
cuando eso pase, https://hora.lhchavez.repl.co/ debería mostrar una tache, que indica que la hora local está mal configurada, y ajustarla hasta que muestre una palomita.

eso es solo un workaround: la solución es encontrar qué llamada a la API no está ajustando apropiadamente el offset entre la hora local y la hora real.

**Comment by darkmx** [comment]
Necesitaba la clave de administrador para poderles cambiar la hora a las compus (supongo que es a lo que te refieres con ajustarla) pero no la tenía. Estaba atado de manos.

**Comment by pabo99** [comment]
Lo que he encontrado hasta el momento es lo siguiente:

Todas las llamadas a la API donde se espera recibir fechas mandan llamar la función `remoteTimeAdapter`, y por lo que veo, esta función le agrega un `remoteDeltaTime` para obtener la fecha y hora de acuerdo a la hora del servidor. 

El problema es que cuando se recarga la página no se obtiene la información vía API, más bien se obtiene por medio del payload. 

Asi que si le intento aplicar la función `remoteDate` a `nextSubmissionTimestamp` no sé si se está calculando correctamente el delta, ya que no estoy mandándolo  llamar desde la API.

Seguiré intentando hasta encontrar la mejor solución.

**Comment by heduenas** [comment]
Juan Pablo puedes poner aqui las ligas a una de esas APIs donde se lalama a la funcion `remoteTimeAdapter` y la liga a donde se calcula el pyaload de la arena?

**Comment by pabo99** [comment]
Claro.

Lo que entiendo hasta ahora es lo siguiente:

Cuando realizas un envío, se manda llamar la siguiente API:
https://github.com/omegaup/omegaup/blob/f4c40f1bdf202c655c8018fa94cd1abfa2815194/frontend/www/js/omegaup/arena/contest_contestant.ts#L221-L259

la cual almacena tanto en el componente como en el store de problemas el valor de `nextSubmissionTimestamp` despupes de haber mandado llamar la función de `remoteTimeAdapter`:
https://github.com/omegaup/omegaup/blob/f4c40f1bdf202c655c8018fa94cd1abfa2815194/frontend/www/js/omegaup/arena/contest_contestant.ts#L227

Por otro lado, cuando acabas de ingresar a la arena o recargas la página, el valor de `nextSubmissionTimestamp` llega directo desde el payload de `ContestDetailsPayload` y se asigna en:
https://github.com/omegaup/omegaup/blob/f4c40f1bdf202c655c8018fa94cd1abfa2815194/frontend/www/js/omegaup/arena/contest_contestant.ts#L120

Hay otra cosa que revisé pensando que podía ayudar a resolver el error, que es el lugar en el cual se navega entre problemas, y se manda llamar la API de ProblemDetails:
https://github.com/omegaup/omegaup/blob/f4c40f1bdf202c655c8018fa94cd1abfa2815194/frontend/www/js/omegaup/arena/location.ts#L107-L110

Pero al agregar el llamado a `remoteTimeAdapter`, no vi que se corrigiera nada

**Comment by darkmx** [comment]
Hola, ¿tendrán algún estimado de cuándo estará el fix?

**Comment by heduenas** [comment]
Este issue es la prioridad numero 1 de Juan Pablo esta semana (aunque que va a ser corta para el), esperamos que quede arreglada en el release del proximo domingo.

**Comment by heduenas** [comment]
Aun tratando de hacer un 2do envio *sin* recargar la página, se reproduce el bug. Sospecho que la función `remoteTimeAdapter` no está funcionando como debería. Lo que te recomiendo es depurar esa función para asegurarnos de que sí esta funcionando como debería. En particular hay que checar si el [delta](https://github.com/omegaup/omegaup/blob/ea3e7486150d31dd77145e21b093ce739f1adf81/frontend/www/js/omegaup/time.ts#L212) que almacena es correcto.

**Comment by darkmx** [comment]
Follow-up: esto sigue ocurriendo:

![image](https://user-images.githubusercontent.com/19719969/182725667-1af60c75-ac46-4781-9a1a-f321f2c2ae64.png)

Un alumno (que ya aprobó el curso y entró a clase sólo a saludar y a platicar) se puso a resolver el examen que les puse a los alumnos que sí estaban tomando la materia. El concurso-examen en cuestión es https://omegaup.com/arena/E1PE2022PCSI06. Mi alumno se puso a resolver el examen desde su celular y antes de su primer envío le apareció lo de la imagen. La hora de su celular estaba bien.
