### ISSUE TITLE
[FEATURE] Hide schools with score 0 from school ranking

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6465]
![image](https://user-images.githubusercontent.com/597815/160186934-4cd43b1a-cd8f-432d-bbae-8384e4f396f9.png)

This was discussed in https://github.com/omegaup/omegaup/issues/6432

**Comment by anmode** [comment]
I want to work upon this issue. Please assign it to me.

**Comment by heduenas** [comment]
Assigned! Sorry about the delay.

**Comment by anmode** [comment]
May I know in which file I have to put the delete query so this problem of duplication may be solved. Help me to identify the file.

**Comment by heduenas** [comment]
Not 100% sure but I think it's this one https://github.com/omegaup/omegaup/blob/main/frontend/server/src/DAO/Schools.php#L77
