### ISSUE TITLE
[FEATURE] Add quality badge filter to list of problems

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6466]
In https://omegaup.com/problem/ we need to add a "Quality badge only" check box right before the "Search" button:
![image](https://user-images.githubusercontent.com/597815/160192303-7ef39801-4af7-4f95-abec-26520cd80ff0.png)

Back-end support for this is already in place. This feature consumes the `/api/problem/list` end point, which already takes a parameter `only_quality_seal`. So, only front-end work is necessary for this issue.

**Comment by David-Lazaro-Fernandez** [comment]
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖

**Comment by heduenas** [comment]
Hi David,
Are you interested in this for your application for GSoC? We ask that

**Comment by MohitOhlyan** [comment]
If available, can you assign me this Issue. I currently have 2 assigned issues, one which I have made a PR and just needs to be merged and the other one I will work after the First PR is merged( they are interlinked). I will wait if needed.

**Comment by heduenas** [comment]
Sorry for the delay @MohitOhlyan

**Comment by MohitOhlyan** [comment]
> Sorry for the delay @MohitOhlyan . Assigned to you!

Thank You. I will get started immediately.

**Comment by pabloaguilar** [comment]
Esto es lo mismo que #6061

**Comment by tvanessa** [comment]
> Esto es lo mismo que #6061

#6061 se tiene para el componente de ProblemFinder. Este es para toda la lista de problemas https://omegaup.com/problem/

**Comment by Anurag-Singh-04** [comment]
Hey @heduenas ,
Since this issue has not been closed till now, can I work on this issue.

**Comment by heduenas** [comment]
Hi Anurag, yes feel free to work on this issue. Thanks!

**Comment by ArijeetBanerjee** [comment]
I want to work on this issue. kindly give me permission and access to work on this issue

**Comment by neeraj542** [comment]
Hello sir, I'm Neeraj. Please assign me this issue so that I can work on it.

**Comment by OmarGO1** [comment]
@heduenas Hi, I want to work on this issue. 
I have already completed phase 1 of GSoC application. (OmegaUp Username: Smitty)

**Comment by heduenas** [comment]
Hi @OmarGO1!

Apologies for the delay replying. Thank you for completing phase one and confirming your username. I've assigned the issue to  you.

**Comment by Prathamesh72003** [comment]
Hey there! I just noticed the issue isn't closed yet and I would like to contribute to the issue.
I went through the issue and all the comments, there's a bit of confusion regarding the issue.
Kindly just brief the issue a bit so that we can look into the solution!!!
