### ISSUE TITLE
[FEATURE] Improve message asking to wait between submissions

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6467]
![image](https://user-images.githubusercontent.com/597815/160224758-f38535a5-a84d-4872-8c9c-eb9fd2e8d501.png)

It should instead say "You have to wait X seconds before you can make another submission to this problem." ("Tienes que esperar X segundos antes de puedas hacer otro envío a este problema." in Spanish)

**Comment by EmperorRP** [comment]
Please assign me this file @heduenas

**Comment by heduenas** [comment]
You got it!
