### ISSUE TITLE
[BUG] Si quiero ordenar los problemas por calidad y a la vez filtrar, no es posible

### ISSUE THREAD

**Issue by jose-tapia** [omegaup/omegaup#6476]
## Comportamiento Esperado

Al hacer click en el tag y después en la columna de calidad (o viceversa), esperaría que me ordene los problemas con el tag seleccionado de acuerdo a su calidad. 

## Comportamiento Actual

Hago click en el tag y después en la columna de calidad, y el tag se borra, pero si ordena por calidad.
Si ordeno primero por calidad y después hago click en el tag, se borra el ordenamiento por calidad.

## Posible Solución

Se pueden concatenar los filtros de tag y el ordenamiento (Este es un ejemplo https://omegaup.com/problem/?tag[]=problemRestrictedTagLanguage&language=all&query=&order_by=quality&sort_order=desc)

- Al hacer click  en un nuevo tag, agregarlo a la lista de tags (si es que existe)
- Al hacer click en el ordenamiento deseado, sobreescribir (si es que existe) (este sería un poco más complejo por el parse que se debe hacer)

## Pasos para reproducir (para bugs)

1. Ir a https://omegaup.com/problem/ y seleccionar cualquier tag, "lenguaje" por ejemplo (El nuevo url sería https://omegaup.com/problem/?tag[]=problemRestrictedTagLanguage)
2. Hacer click en ordenar por calidad (el nuevo url sería https://omegaup.com/problem?language=all&query=&order_by=quality&sort_order=asc)
3. Se borró el filtro de "lenguaje" y ya aparecen problemas sin el tag 

## Contexto

He querido buscar problemas calificados como buenos y que tengan un tag especifico. Con el nuevo buscador sí es posible tener filtro de tag + calidad, por eso no me ha afectado

## Tu ambiente

Usé Google Chrome Version 99.0.4844.83 (Official Build) (arm64)
En MacOs 12.3

**Comment by pabloaguilar** [comment]
Resuelto en #6563
