### ISSUE TITLE
Borrar administradores de concursos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#648]
Estimado Joe:

Hoy he comenzado a utilizar la plataforma de OmegaUp, y me atrevo a sugerirte que se permita borrar a un administrador, ya que me he dado de alta en un concurso como administrador y a pesar de ser yo el propietario del concurso no me permite eliminar uno de los duplicados con el que aparezco como director del concurso.

Atentamente
cir: Cirino Silva Tovar

**Comment by lhchavez** [comment]
Esto es un error cosmético solamente, porque no afecta a los permisos. Aún así deberíamos ni siquiera permitir _agregar_ un administrador si ya es dueño.
