### ISSUE TITLE
[BUG] Cuando una descripción incluye una imagen, se despliega mal en la lista de concursos

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6480]
Hola amigos de omegaUp.

En la ICPC acaban de dar luz verde para que omegaUp hospede de manera oficial un concurso espejo del la final regional ICPC 2021 para México, la cual ocurrirá el próximo sábado. El enlace al concurso público https://omegaup.com/arena/ICPCMX2021/ incluye el logo del ICPC:

![image](https://user-images.githubusercontent.com/19719969/161058519-cb12e293-f9c4-4235-b37f-e4b2f156616d.png)

Pero en la lista de concursos futuros de https://omegaup.com/arena/, la descripción está rota (se despliega el base64):
![image](https://user-images.githubusercontent.com/19719969/161058638-c5d6c169-6de7-45b8-9a61-fe67f1641290.png)

¿Habrá forma de mostrar el logo en la lista?, ¿habrá forma de que al menos no termine el base64 ahí todo feo?

**Comment by heduenas** [comment]
No habia notado ese problema antes (de hecho ni sabia que podian poner imagenes en la descripcion)
Estamos proximos a lanzar una nueva UX para la lista de concursos en la que no va a aparecer la descripcion en la lista. 
![image](https://user-images.githubusercontent.com/597815/161352928-d0839f08-23a7-4491-923d-85d43dd7cf48.png)

**Comment by pabloaguilar** [comment]
Esto quedó resuelto, entonces, cierto?
