### ISSUE TITLE
[BUG] No se pueden agendar cursos en Abril

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#6482]
## Comportamiento Esperado

Poder agendar concursos en Abril.

## Comportamiento Actual

En https://omegaup.com/course/new/, si se intenta seleccionar alguna fecha en Abril, automágicamente se cambia a Mayo.

## Posible Solución

/shrug.

## Pasos para reproducir (para bugs)

1. Ir a https://omegaup.com/course/new/
2. Elegir una fecha (de inicio o fin) que caiga en Abril.
3. La fecha se cambia a Mayo sin intervención del usuario.

## Contexto

Esto está rompiendo las pruebas de Cypress y evitando que la gente agende cursos este mes.

**Comment by pabo99** [comment]
Acabo de crear un concurso en mi ambiente local y si se guardó correctamente:

![image](https://user-images.githubusercontent.com/3230352/161089703-513911c2-87b0-4f16-951c-0cfdb5444b72.png)

También lo intenté en producción y no tuve problemas para crearlo.

Las pruebas las realicé en el navegador Chrome - Versión 99.0.4844.84 (Ubuntu 20.04.4 LTS)

**Comment by pabo99** [comment]
Ya lo intenté con dos navegadores distintos, el SO en inglés, pero todo funciona bien. Quizás la prueba de cypress que falla nos pueda dar más pistas

**Comment by darkmx** [comment]
El título del issue dice "concursos" pero de mi lado los concursos funcionan bien. Es en cursos donde está el problema (lo pude reproducir y el link que puso lhchavez está bien, porque es de cursos: https://omegaup.com/course/new/).

**Comment by darkmx** [comment]
Una diferencia rápida que veo: concursos es un "date-time local" y cursos es un "date".

**Comment by lhchavez** [comment]
GAAAAAH sorry a todos, es *cursos*, no _co _cursos.

**Comment by pabo99** [comment]
Ok, esto tiene mucho sentido. Y ahí si falla desde que intento elegir una fecha de abril.

Voy a revisar si la solución del PR #5707 (Que fue la que arregló el bug en los concursos) sirve para arreglar los cursos.
