### ISSUE TITLE
[BUG] En la lista de últimos envíos, a veces aparece "error del juez" cuando los envíos realmente están en "waiting"

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6484]
Hola amigos de omegaUp.

En https://omegaup.com/submissions/ se pueden ver los últimos envíos hechos en la plataforma. No es bonito lo que se ve:
![image](https://user-images.githubusercontent.com/19719969/161179008-c20fe21f-5153-42a9-94db-77dc60295df9.png)

**Comment by lhchavez** [comment]
huh, no repro. acá todo se ve bien. _posiblemente_ hubo un bug al momento de desplegar el status / veredicto.

![image](https://user-images.githubusercontent.com/168028/161181326-28eff579-dc1b-46b1-a44f-872bb6ce6742.png)

**Comment by darkmx** [comment]
Qué raro D: a mí un alumno me dijo que sus envíos se quedaron en "waiting" por muchos minutos y luego me enseñó esa lista.

**Comment by lhchavez** [comment]
dejémoslo abierto. seguro falta un `status = "ready"`.
