### ISSUE TITLE
[FEATURE] (ArenaV2) Fix Arena V2 pagination.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6490]
We always show several pages even regardless of how many pages there are actually.
![Screen Shot 2022-04-02 at 8 37 11 PM](https://user-images.githubusercontent.com/597815/161410269-55c38f7c-634d-40c5-b63c-21597cc25449.png)
We should query the number of pages from the API and limit the pagination to that number of pages like we do for problems for instance: https://omegaup.com/problem/collection/problemLevelAdvancedSpecializedTopics/. 

Steps to reproduce:
* Go to: https://omegaup.com/arenav2/?query=lakfjsdajsdfkl#past

**Comment by anmode** [comment]
Please assign this issue to me!
