### ISSUE TITLE
[FEATURE] (ArenaV2) Order by contest end date by default.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6491]
![Screen Shot 2022-04-02 at 8 40 47 PM](https://user-images.githubusercontent.com/597815/161410336-c7f54bbb-c9b3-4767-9014-744e2eab5132.png)

We should move "Finaliza" to the top of the dropdown options and it should be selected by default.
The corresponding controller should always sort by that field if unspecified.

Steps to reproduce:
Go to https://omegaup.com/arenav2

**Comment by mohdabbas955** [comment]
Can you please assigned me ? I want to work on this issue

**Comment by heduenas** [comment]
Can we please wait until you get your other issue fixed? I see that you have a PR under review, let's wait until it actually gets merged.

**Comment by mohdabbas955** [comment]
Okk, I will wait for it.

**Comment by LuisFer666** [comment]
Can you please assign me?

**Comment by mohdabbas955** [comment]
Hello , LuisFer 
I am working on this issue. 
I have almost solve this issue and will be sending PR soon. 
I was busy in proposal that's why it got delayed.
