### ISSUE TITLE
[FEATURE] (ArenaV2) Change filter by option names

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6492]
![Screen Shot 2022-04-02 at 8 43 34 PM](https://user-images.githubusercontent.com/597815/161410392-7c05645a-3c7f-464e-94dd-98b2c193e245.png)

We should:
* Add the option "Todos"/"All", put it at the top and select it by default.
* Replace "Inscrito" with "Soy participante" / "I am participant" to make it gender-free.
* Replace "Recomendados" with "Solo recomendados" / "Only recommended".

Steps to reproduce:
Go to https://omegaup.com/arenav2

**Comment by anmode** [comment]
I'll wanna work on it! Please assign this issue.

**Comment by heduenas** [comment]
Bumping to P1 because of the gendered word

**Comment by heduenas** [comment]
I forgot to mention that we should make this field a regular dropdown where only one option can be selected at a time, rather than a list of checkboxes (@darkmx mentioned the current UX was confusing)

**Comment by anmode** [comment]
> I forgot to mention that we should make this field a regular dropdown where only one option can be selected at a time, rather than a list of checkboxes (@darkmx mentioned the current UX was confusing)

Ohh that's the case! Okay.  Currently ig both are checkboxes now. So it should be regular dropdown with one more option `All`
