### ISSUE TITLE
[FEATURE] (ArenaV2) Improve message when list is empty

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6493]
![Screen Shot 2022-04-02 at 8 48 11 PM](https://user-images.githubusercontent.com/597815/161410504-f02f1879-f31f-4f3e-a17a-f65742658a7c.png)

Replace "No hay concursos en esta lista" with "No hay concursos con esas características"/"There are no contests that meet those characteristics" and add a button "Clear filters" that clears all the filters (Except for the "Actuales"/"Próximos"/"Pasados" panel).

Steps to reproduce:
Go to: https://omegaup.com/arenav2/?query=lakfjsdajsdfkl#past

**Comment by anmode** [comment]
I want to work upon this. May I?
