### ISSUE TITLE
[FEATURE] (ArenaV2) Launch new arena

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6494]
Move `/arenav2` -> `/arena` and `/arena` -> `/arenav1` (to keep it accessible in case users complain about the new UX). The old arena should be deprecated once we have confidence that the new arena meets our users needs and they won't need the old arena anymore.

The launch should happen only after all P1 issues have been fixed. That is, the issues in the list should have been fixed:
https://github.com/omegaup/omegaup/issues?q=is%3Aissue+is%3Aopen+ArenaV2+label%3AP1

**Comment by anmode** [comment]
I want to this,  please assign me this issue!
