### ISSUE TITLE
[FEATURE] (ArenaV2) Add buton to clear keywords textbox

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6496]
![Screen Shot 2022-04-02 at 8 57 40 PM](https://user-images.githubusercontent.com/597815/161410694-9456fb9f-6b07-4626-a1b9-5c28e7879386.png)

We should add an "X" button that clears the keywords textbox. Here's an example: http://dflourusso.com.br/v-reset-input/  

Steps to reproduce:
Go to https://omegaup.com/arenav2/?query=icpc#past

**Comment by anmode** [comment]
i want to work upon this!

**Comment by heduenas** [comment]
I see that you already have another issue assigned. Can we wait until you fix that one before we assign you another one?

**Comment by anmode** [comment]
> I see that you already have another issue assigned. Can we wait until you fix that one before we assign you another one?

sure! I will wait
