### ISSUE TITLE
contestcreate.php no tiene texto localizado

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#650]
@lhchavez me imagino que esto se resuelve con el getWords que hay en todos los demás phps.

**Comment by lhchavez** [comment]
Este bug es trivial.

**Comment by pabo99** [comment]
@alanboy ¿a que te refieres con el texto localizado?

**Comment by lhchavez** [comment]
ja, ese archivo ya ni existe. cerrando como obsoleto.
