### ISSUE TITLE
[BUG] Code of conduct and privacy policy disappears in firefox mobile view

### ISSUE THREAD

**Issue by anmode** [omegaup/omegaup#6501]
## Comportamiento Esperado
Code of conduct and privacy policy should be visible at bottom in footer in mobile view
Just like in Desktop version.
![webview1](https://user-images.githubusercontent.com/88332977/161428743-6ab3f4f9-4670-4364-a93d-102cde51579d.png)

## Comportamiento Actual
Code of conduc and privacy policy hyperlinks disappear in mobile view.

## Posible Solución

Just have to do some changes in css. in view property.

## Pasos para reproducir (para bugs)
1. Open omegaup.com on mobile or change the dimensions of your browser to Mobile style
2. Move to footer
3. You will unable to see code of conduct and privacy policy

## Contexto
Cannot see privacy polivy and code of conduct link because they disappears

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Firefox):
* Sistema Operativo y versión (Ubuntu 21.10l):
* Link al sitio en el que este problema pasa:https://omegaup.com/
* Captura de pantalla:
![mobileview1](https://user-images.githubusercontent.com/88332977/161428753-c0dc7e8a-b48f-4438-a199-838b11b0863e.png)

**Comment by carlosabcs** [comment]
I'm able to see it on my mobile. Using Brave browser.
![](https://user-images.githubusercontent.com/20785082/161449467-d18711f8-4719-44e7-b526-926cafd885f1.jpeg)

**Comment by anmode** [comment]
> I'm able to see it on my mobile. Using Brave browser. ![](https://user-images.githubusercontent.com/20785082/161449467-d18711f8-4719-44e7-b526-926cafd885f1.jpeg)

If you reduce window size more nothing dissappear but these two link will.
Try to reduce screen size in brave.

**Comment by anmode** [comment]
Yes this problem is coming in firefox only, what to do now?
:(

**Comment by arishmaurya** [comment]
@tvanessa is problem is in mobile view of all browsers at least in chrome and firefox it is there i want to fork this repo but github is showing fork limit is over can you please help me how should i fork this repo i will fix this issue in 1-2 days

**Comment by anmode** [comment]
> @tvanessa is problem is in mobile view of all browsers at least in chrome and firefox it is there i want to fork this repo but github is showing fork limit is over can you please help me how should i fork this repo i will fix this issue in 1-2 days

I'll fix it! As currently working on big issues so that's why it tooked time.
I'll solve it soon!

**Comment by arishmaurya** [comment]
@anmode i would love to work on this if you are not free right now because i have time and previously worked on footer of my personal project so it will be easy for me.  can you help me to setup this issue and  how should i fork and run this on my local pc

**Comment by anmode** [comment]
> @anmode i would love to work on this if you are not free right now because i have time and previously worked on footer of my personal project so it will be easy for me. can you help me to setup this issue and how should i fork and run this on my local pc

Did u know vue js?

**Comment by arishmaurya** [comment]
i know react js and typescript and i just learnt some basics of vue.js just a hour ago for this issue but i'm having problem to run this project

**Comment by anmode** [comment]
> i know react js and typescript and i just learnt some basics of vue.js just a hour ago for this issue but i'm having problem to run this project

That's cool!
Actually i m also making a tutorial to help new contributor so they can set up project.
Could you please wait a little!

**Comment by arishmaurya** [comment]
okay great and please do mention about fork limit 😊because when i forked it showing fork limit over you can't fork it

**Comment by arishmaurya** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/75907342/163021332-d25a3957-6809-4cc6-975b-0a9950bba3cf.png)
![Screenshot (145)](https://user-images.githubusercontent.com/75907342/163021380-675307c5-acfd-4696-9d77-755a2ef0e85e.png)
 
sir these are the screenshots and discord link is also invalid on gsoc page i'm not in the discord channel of omegaup please provide me link of that channel.
