### ISSUE TITLE
[FEATURE] Add link to discord server under Help menu

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6504]
![image](https://user-images.githubusercontent.com/597815/161456587-58886281-9c59-4c34-a57a-1f22273e835c.png)

 It should be the second item in the menu.

Link to discord: https://discord.gg/Y4JQ5HQd

Text for menu item: "Servidor de Discord" / "Discord server".

**Comment by mohdabbas955** [comment]
Hello @heduenas  I will be able to solve this issue. Please assigne me this issue.
