### ISSUE TITLE
[FEATURE] In create problem page UI.

### ISSUE THREAD

**Issue by anmode** [omegaup/omegaup#6507]
## Some UI improvement in Create problem page. Backend working nicely!

`Suggestion first`
![createproblem1](https://user-images.githubusercontent.com/88332977/161523877-168dff90-c45c-4337-9ce1-463d06baafda.png)

`Improvemnt 1`
The alignment of tag name and delete

`Improvement 2`
The ?logo in Delete in public tag should have hover css so user can know that it shows an important information. So a hover css should be there.

`Suggestion second`
![createproblem2](https://user-images.githubusercontent.com/88332977/161525114-b5e0dcd5-30d9-48d8-8b70-bb727a0ae1b9.png)

`Improvement`
[Here is how to write the file] used two time in this I think upper one is okay but near attach the zip file there is not needed, if there is then UI not looks good there should be space between. So it looks good

## Contexto
UI improvements. So website looks fantastic!

## Tu ambiente

* Nombre del navegador (e.g. Chrome):
* Sistema Operativo y versión (ubuntu 21.10):
* Link al sitio en el que este problema pasa:https://omegaup.com/

**Comment by anmode** [comment]
Could i work on this? Just want advics in 2nd suggestion.

**Comment by denllx** [comment]
I want to solve this issue. Please assign it to me.

**Comment by anmode** [comment]
> Hello, @tvanessa I want to solve this issue. Please assign it to me.

Will u apply for Gsoc?
