### ISSUE TITLE
[FEATURE] Quick Log out button.

### ISSUE THREAD

**Issue by anmode** [omegaup/omegaup#6516]
## Discription
Feature request regarding logout button at right most part of navbar so user can easily logout the website.
I used up the omegaup css instead using my own css code for the logout button.
I have attached a demo video I think it look fine!
Just want approval and if any suggestion then please! comment down. I will apply those.

## Environment
* Browser name (e.g. Chrome)
* Operating System and version (desktop Ubuntu 21.10)

https://user-images.githubusercontent.com/88332977/161996623-49b8f451-2bec-4d9f-ac22-615a9b33d41a.mp4

**Comment by heduenas** [comment]
@tvanessa please take a look as well.

**Comment by heduenas** [comment]
Maybe @darkmx and @frcepeda have opinions on this proposal as well.

**Comment by darkmx** [comment]
Anything that minimizes the number of clicks is good in my opinion, subject to having enough space in the UI (and the omegaUp website has a lot of empty space).

Two things to notice:
  - The logout button shouldn't appear when the user hasn't logged in.
  -  Currently, the logout button has a label explaining what it does. I find that the current button 
![image](https://user-images.githubusercontent.com/19719969/162207774-5280334d-f2bf-4908-bd7a-7b29989b90f9.png)
 without the label is not clear enough to explain what it does. I would prefer something like 
![image](https://user-images.githubusercontent.com/19719969/162208085-fcc2d7d7-b260-4f82-9011-4d8e987ad572.png)

**Comment by anmode** [comment]
Okay! Thanks for the suggestion I will try to implement those as soon as possible.

**Comment by tvanessa** [comment]
I don't have preference about icons, I just ask you to use the ones in https://fontawesome.com/search?m=free

**Comment by anmode** [comment]
> I don't have preference about icons, I just ask you to use the ones in https://fontawesome.com/search?m=free

Acha okay! I'll make two demos of two different suggested here.
Afterwards which suits more will be final.
Thanks!

**Comment by anmode** [comment]
> I don't have preference about icons, I just ask you to use the ones in https://fontawesome.com/search?m=free

In fontawesome the icon present is that one which is used by me in the video demo! To use the icon suggested by @darkmx i have to use svg then. what to do ? please
