### ISSUE TITLE
[BUG] User birthday could be later than today

### ISSUE THREAD

**Issue by denllx** [omegaup/omegaup#6521]
## Expected Behavior

In the Edit profile page, users could modify their birthday, but no later than current date.

## Current Behavior
![Screenshot from 2022-04-07 18-26-06](https://user-images.githubusercontent.com/42374096/162179932-0d4cd395-ba04-4473-811f-7a9d7bc8d0b8.png)

## Possible solution

Limit the data picker to only allow dates before today

## Steps to reproduce (for bugs)

1. open https://omegaup.com/profile/#edit-basic-information
2. find 'Birthday Date'
3. select a date later than today

## your environment

* Browser name (e.g. Chrome 39, node.js 5.4): Chrome 89.0.4389.82
* Operating System and version (desktop or mobile): Linux
* Link to the site where this problem happens: See above

**Comment by denllx** [comment]
Meanwhile, I want to solve this issue. Please assign it to me.

**Comment by MohitOhlyan** [comment]
Just curious, how can someone's birth date be later than today?

**Comment by anmode** [comment]
> Just curious, how can someone's birth date be later than today?

+1

**Comment by denllx** [comment]
> Just curious, how can someone's birth date be later than today?

That's also I'm curious about :)
