### ISSUE TITLE
[BUG] The new logout button in mobile view doesn't render in the right place.  

### ISSUE THREAD

**Issue by MohitOhlyan** [omegaup/omegaup#6534]
## Comportamiento Esperado
The new logout button in the top right corner doesn't render in the right place in mobile view.

## Comportamiento Actual

It it shown below the omegaup logo in mobile view.

## Posible Solución

Move the `<a>` tag inside the navigation bar or something else like adjacent to omegaup logo. 

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Open https://omegaup.com/ in mobile or swtich to mobile view. 
2. Notice the placement of the new logout button. 
3. 
4. 

## Contexto

It would be better to place it under the navigation button rather than omegaup logo. 

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador : Chrome 99
* Sistema Operativo y versión (escritorio o móvil): Ubuntu. 
* Link al sitio en el que este problema pasa:
* Captura de pantalla:
![Screenshot from 2022-04-14 14-59-33](https://user-images.githubusercontent.com/63846699/163434156-aa51ac6c-2581-4040-8b48-3bea50b2bed0.png)

**Comment by anmode** [comment]
I'll solve it!

**Comment by anmode** [comment]
I think it looks great! As quick logout.

**Comment by MohitOhlyan** [comment]
> 

Yes, It's a really great feature you have added. It's just the placement of the button in Mobile view is what I am referring to here. It would be better if it's either below the Navbar button or inside it and below the user button.

**Comment by anmode** [comment]
> > 
> 
> Yes, It's a really great feature you have added. It's just the placement of the button in Mobile view is what I am referring to here. It would be better if it's either below the Navbar button or inside it and below the user button.

For positioning, I think we should advice! 
We can have it on both places. Ya only below navbar button in fine!

**Comment by swatiinigam** [comment]
I want to work on this issue please assign me this issue

**Comment by pabo99** [comment]
Hello @swatiinigam, thank you for your interest in the GSoC program.

In order to be assigned an issue, all GSoC candidates must complete [Phase One](https://github.com/omegaup/omegaup/wiki/Google-Summer-of-Code-2023#phase-one-complete-our-test).

For more information, please contact @heduenas who can provide additional details and guidance.

**Comment by YannyTwoo** [comment]
Hey, I've completed the first phase of GSoC applications, I'm adirath2101 on OmegaUp(done 3/4). Can this issue be assigned to me?

**Comment by heduenas** [comment]
Thank you @YannyTwoo for completing phase one. I've assigned the issue to you.

**Comment by YannyTwoo** [comment]
A question regarding the design pattern to follow and which position to place the power-off/logout button in-

1. To the left of the hamburger menu(hamburger will be right corner)
2. To the right of the hamburger menu(our power-off/logout will be in the top right corner)
3. Place it inside the dropdown menu at (a) First position (b) Last position

I prefer (1) but would like to know which of these ways to go
