### ISSUE TITLE
cache no se invalida

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#654]
- entra a tu perfil de usuario
- edita tu nombre
- refresca la pagina de perfil

esperado: ver tu nuevo nombre
lo que pasa: vez el nombre antes de ser editado

pude reproducir esto en mi copia local, pero aun no encuentro el problema. si limpio el cache desde apc.php, el nuevo nombre editado ya funciona. mis dudas estan en apc_delete() por el momento.

**Comment by lhchavez** [comment]
También pasa si modificas un problema: los concursos donde están ese problema no necesariamente se invalidan.
