### ISSUE TITLE
[BUG] Problemas con un nombre de menos de 3 caracteres NO se pueden usar en concursos

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#6553]
## Comportamiento Actual
Cuando el NOMBRE del problema es de dos caracteres o menos NO se puede utilizar en CURSOS ni en CONCURSOS porque el sistema no lo reconoce, solo reconoce nombres de problemas de 3 caracteres o mas.

No tengo un ejemplo en este momento pero me ha pasado varias veces.

**Comment by pabloaguilar** [comment]
Hay 55 problema con alias de menos de 3 caracteres

**Comment by pabo99** [comment]
Lo más sencillo sería limitar a 2 caracteres la activación del typeahead (por el momento sólo sería para problemas). Actualmente lo tenemos configurado que se active a los 3 caracteres.

**Comment by pabo99** [comment]
> Hay 55 problema con alias de menos de 3 caracteres

Sabes si de esos 55 problemas, existe al menos alguno que sea de sólo un caracter? Para bajar el límite a 1, en lugar de 2
