### ISSUE TITLE
[BUG] Funcionamiento incorrecto cuando se buscan problemas.

### ISSUE THREAD

**Issue by licgerman** [omegaup/omegaup#6554]
## Comportamiento Actual

Cuando buscas un problema y eliges una etiqueta, por ejemplo "KAREL", la lista de problemas filtra adecuadamente pero si intentas ordenar esa lista por cualquiera de los filtros disponibles, la etiqueta se pierde.

Es muy complicado buscar problemas en omegaUp, hay muchos problemas pero este detalle no permite sacarle todo el provecho a la plataforma.

![image](https://user-images.githubusercontent.com/22159184/165531325-e14f9459-776a-408e-b574-bcc0a6c6624e.png)

**Comment by pabloaguilar** [comment]
También es confuso que el link que aparece al pasar el mouse sobre los botones para ordenar sea el link de la vista actual, porque no permite hacer ctrl-click o copiar la dirección a la que apunta. Tiene uno que darle click para saber dónde va a llegar.
