### ISSUE TITLE
[BUG] Botón "Importar" no funciona en karel.js

### ISSUE THREAD

**Issue by igurug** [omegaup/omegaup#6556]
## Comportamiento Esperado

En el entorno de Karel en linea (https://omegaup.com/karel.js/), entrando al dialogo "Importar MDO/KEC", selecionando los archivos correspondientes y dando click en el boton "Importar", el entorno debe de abrir el caso. 

## Comportamiento Actual

En el entorno de Karel en linea (https://omegaup.com/karel.js/), entrando al dialogo "Importar MDO/KEC", selecionando los archivos correspondientes y dando click en el boton "Importar", no hace ninguna accion. 

##  Solución

El codigo del dialogo correspondiente, es siguiente:

```JS
      <div>
        <form id="importar" name="importar">
          <div class="form-group">
            <label>MDO: <input id="importar_mdo" type="file" /></label>
            <label>KEC: <input id="importar_kec" type="file" /></label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <input class="btn" type="submit" value="Importar" />
      </div>
```

En este codigo, el elemento "submit" se encuentra afuera del form correspondiente. Para resolver el problema, es suficiente moberlo adentro del elemento form

```JS

        <form id="importar" name="importar">
          <div class="form-group">
            <label>MDO: <input id="importar_mdo" type="file" /></label>
            <label>KEC: <input id="importar_kec" type="file" /></label>
          </div>
          <div class="modal-footer">
               <input class="btn" type="submit" value="Importar" />
          </div>
      </form>
```

**Comment by tvanessa** [comment]
https://github.com/omegaup/karel.js/pull/147
