### ISSUE TITLE
[BUG] se desperdicia mucho espacio horizontal en móvil

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#6558]
## Comportamiento Esperado

Debería aprovecharse todo el espacio horizontal para desplegar contenido.

## Comportamiento Actual

Ha mejorado cómo se ve omegaUp en móvil, sólo hay que pulirlo. Ahorita casi la mitad del espacio horizontal está en blanco.

![Screenshot_20220429-082940_Chrome](https://user-images.githubusercontent.com/189223/165978071-d0fc7efc-2a8e-45b3-a94e-104ce05ccecf.jpg)

## Pasos para reproducir (para bugs)

Entrar a watermelon desde Chrome n móvil:
https://omegaup.com/arena/problem/Watermel/#problems

## Contexto

Estaba revisando envíos de un problema en móvil.

## Tu ambiente

* Chrome 101
* Android 12

**Comment by IngridRB** [comment]
Hola, me pueden asignar este issue @heduenas ?

**Comment by heduenas** [comment]
Claro!
