### ISSUE TITLE
Tener referencia de C++ en la arena

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#656]
Sería útil que arena.omegaUp.com tuviera una copia de la referencia para cuando estamos en modo de lockdown.

http://en.cppreference.com/w/Cppreference:Archives
http://es.cppreference.com/w/Cppreference:Archives

Hay referencia de Pascal?

**Comment by lhchavez** [comment]
https://omegaup.com/docs/cpp/en/

La versión en español en realidad está en inglés, así que no la subí :/

Falta pascal.

**Comment by frcepeda** [comment]
Pascal: http://sourceforge.net/projects/freepascal/files/Documentation/2.6.4/doc-html.zip/download

**Comment by lhchavez** [comment]
https://arena.omegaup.com/docs/pas/en/
