### ISSUE TITLE
[BUG] No se puede actualizar la penalizacion de las soluciones en un concurso cuando se cambia el modo de penalizacion

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#6560]
## Comportamiento Esperado

Cuando un concurso inicia con el modo "Contar tiempo desde que se abre un problema" a modo "Contar tiempo desde que iniciar el concurso", los tiempos de penalizacion deberian actualizarse de manera automatica o, por lo menos, de manera manual al dar click en la opcion "Rejuecear" en la lista de Envios del concurso.

## Comportamiento Actual

Los tiempos de penalizacion no se actualizacion de modo automatico ni tampoco de modo manual, ocasionando que el concurso tenga una mezcla entre una medicion de tiempo y otra.

## Posible Solución

Idealmente, al hacer este cambio, el concurso recalcularia automaticamente de nuevo todos los penalties, sin necesidad de re-evaluar las soluciones.

## Pasos para reproducir (para bugs)

1. Abre el concurso https://omegaup.com/arena/tecnm-culiacan-2022/#runs
2. Filtra por el usuario KapStormblessed
3. Localiza el envio #5 realizado en 2022-04-29 14:41 (AC para el problema G. Sumando todos los subarreglos)
4. El concurso empezo en 2022-04-29 14:15 y el penalty deberia de ser de 26 min, pero en el scoreboard aparece con un penalty de 9 min.

## Contexto

Concurso local con 24 participantes.

## Tu ambiente

N/A

**Comment by darkmx** [comment]
Mismo bug que #5805

**Comment by heduenas** [comment]
Vamos a darle seguimiento en #5805
