### ISSUE TITLE
[FEATURE] Hacer gender-free las cadenas de la administracion de admins

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6569]
Hay que cambiar a "admin" y "grupo de admins".

![annotely_image](https://user-images.githubusercontent.com/597815/166629136-018cf30b-85d1-4862-a937-e2c939644666.png)

**Comment by anmode** [comment]
I want to work upon this! Please assign it to me.

**Comment by anmode** [comment]
Please assign this to me!
