### ISSUE TITLE
[BUG] ArenaV2 es menos usable en móvil

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#6571]
## Comportamiento Esperado

No deberían encimarse botones y los títulos deberían leerse en forma horizontal

## Comportamiento Actual

![Screenshot_20220504-164454_Chrome](https://user-images.githubusercontent.com/189223/166842743-1c7898be-16df-4f43-895b-bc1643f86280.jpg)

Arena V1 se ve un poco mejor:
![Screenshot_20220504-165028_Chrome](https://user-images.githubusercontent.com/189223/166843005-925bf218-6a45-4e32-9ea2-778d7d43e504.jpg)

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de paso

1. Ir a https://sandbox.omegaup.com/arena

## Tu ambiente

* Chrome en Android

**Comment by anmode** [comment]
Oh yes!  Media queries are required. Has to be optimized for mobile.
I'll try to fix it up soon.

**Comment by H454NSec** [comment]
Hi @pabo99, I am interested in contributing to the project and I have already completed Phase One of the GSoC 2023 omegaUp Test. At this point, I would like to move onto Phase Two as soon as possible. Would it be possible for you to assign me the issue #6571 ?

**Comment by galovdev** [comment]
@pabo99 My omegaUp username is galovdev thanks
