### ISSUE TITLE
[BUG] Tarea de Ciclos en el curso de Introducción a C++ manda un error 500

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6592]
En el curso de [Introducción a C++](https://omegaup.com/course/introduccion_a_cpp/) la [tarea de ciclos ](https://omegaup.com/course/introduccion_a_cpp/assignment/ciclos)te manda un error 500.

**Comment by heduenas** [comment]
Despues de checar los logs veo que crashea al generar el scoreboard porque requiere demasiada memoria para generarlo (por la cantidad de alumnos y de tareas que hay en esta tarea).

Los scoreboards deberian de estar desactivados para cursos publicos. Asi que la solucion para este problema va a ser dejar de mostrarlos.

@pabo99 puedes encargarte de este issue por favor? Hay que quitar la pestaña de scoreboard en cursos publicos y en el servidor hay que asegurarnos de no hacer la peticion para generarlo.
