### ISSUE TITLE
[BUG] Se hace envío al hacer click en "Run" en Ephimeral

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6603]
Al hacer click en "Run" se corren los casos de prueba (como debería), pero también se hace un envío. En un concurso eso puede constarle muchos puntos al concursante.

![image](https://user-images.githubusercontent.com/597815/171941777-8504c062-0c99-47f2-8c74-7e94c35bc0b7.png)

**Comment by heduenas** [comment]
@pabo99 puedes intentar reproducir con este problema? https://omegaup.com/arena/problem/Matriz-Transpuesta/#problems

**Comment by pabo99** [comment]
Gracias. Lo intentaré con ese problema
