### ISSUE TITLE
[BUG] Cuando un caso de prueba arroja un error, el veredicto es WA en lugar de RTE

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#6604]
## Comportamiento Esperado

Cuando un caso de prueba arroje una excepcion, el veredicto debe ser RTE.

## Comportamiento Actual

Cuando un caso de prueba arroja una excepcion, el veredicto es WA.

## Posible Solución

Las excepciones se estan ignorando, por lo menos en Java, ya que antes no era asi.

## Pasos para reproducir (para bugs)

1. Visita un problema como https://omegaup.com/arena/problem/Digitos-Inteligentes--/#problems
2. Escribe una solucion en Java que solo arroje una excepcion: `throw new RuntimeException();`
3. El veredicto es WA con 0%
4. Da click en `Acciones` para abrir el detalle del veredicto
5. Da click en el veredicto individual de cada caso de prueba y confirma es WA para todos

## Contexto

Estaba resolviendo un [problema](https://omegaup.com/arena/problem/Digitos-Inteligentes--) de registro para un concurso, y la entrada era incorrecta de acuerdo a la descripcion del problema (el limite decia seria 100K pero era 1M), por lo que mi solucion en Java seguro estaba fallando con `ArrayIndexOutOfBoundsException` pero no lo pude notar por el mal veredicto.

Graciosamente, este problema yo ya lo habia resuelto hace 3 anos y tuve exactamente el mismo problema, pero en aquel entonces omegaUp si me dio RTE como veredicto (envio con GUID `392c6f7f`). Lo que indica que este comportamiento es una regresion.

## Tu ambiente

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/606680/172216235-5ab1623c-fd05-44ce-b59d-fd0cac3219f7.png">

**Comment by tvanessa** [comment]
@wkoder ahora tenemos otra estructura para los veredictos. Esto cambio en la version actual?

**Comment by wkoder** [comment]
@tvanessa justamente me paso la semana pasada, jaja, cuando fue el cambio?

**Comment by wkoder** [comment]
Bueno, esto es apenante pero, me voy dando cuenta esta mal la plantilla que uso para Java y se traga las excepciones :/ Acabo de probar corrigiendola y efectivamente me dio RTE, y probablemente siempre ha sido asi, una disculpa!

<img width="624" alt="image" src="https://github.com/user-attachments/assets/25f1fef0-522c-43f8-a49e-601bd97886b5">

Basicamente lo que pasa es que usaba un truco de crear un `Thread` para poder utilizar mas memoria en casos de recursion, ya que usualmente Java no tiene mucha memoria asignada al stack.

En fin, nada que ver aqui... Gracias!

**Comment by wkoder** [comment]
Cabe mencionar que efectivamente se escribe a `stderr`, que supongo omegaUp simplemente ignora. No estoy seguro si otros jueces lo ignoran tambien, ya mi experiencia con jueces actuales es limitada 😓
