### ISSUE TITLE
Navbar poco responsiva en algunas views de dispositivos móviles

### ISSUE THREAD

**Issue by oscark22** [omegaup/omegaup#6617]
Me encontraba navegando por el sitio a través del móvil y me encontré con una navbar más grande del ancho del dispositivo, lo que crea un espacio en blanco que se puede visualizar a través de toda la página.

Probé con otro dispositivo para ver si este error sólo ocurría con mi teléfono, pero no es así. El error se replica en diferentes dispositivos. También probé con distintos navegadores: el navegador por defecto del dispositivo, chrome y firefox en sus versiones más recientes. 

El sistema operativo de ambos dispositivos con los que visité la página es Android.

El error debería ser replicable al entrar a la pestaña por defecto del sitio: https://omegaup.com/
Adjunto imágenes del bug a continuación.

![omegaUpNavbar](https://user-images.githubusercontent.com/98506040/173279236-3c9749d5-df1b-4121-bcdb-9fa036f7e5db.jpg)
![omegaUpNavbar2](https://user-images.githubusercontent.com/98506040/173279249-f48c3e92-75d4-415d-8889-f5b585dd7443.jpg)

**Comment by heduenas** [comment]
Esto ya debe de estar arreglado con los cambios recientes que se hicieron
