### ISSUE TITLE
Las cuentas privadas no contribuyen al rank o se pierde el rank

### ISSUE THREAD

**Issue by flopezorozco** [omegaup/omegaup#6640]
**Edit**: Cuando la cuenta es privada no se contribuye al rank y si antes tenias color/rango, solo desaparece.
Al hacer la cuenta privada no se especifica que cambios se harán. Podemos agregar una descripción para dejarlo claro.
Agregar descripción en https://omegaup.com/profile/#edit-preferences que mencione "El rank de tu cuenta no sera visible" cuando se de click en "Ocultar detalles de perfil"

Otra alternativa para cuentas privadas es, no contribuir al rank, pero mostrarle al usuario que color/rango tendría.

Otra alternativa más elaborada es permitir al usuario que decida qué es privado en su perfil
 
------------------
Hola a todos,

tengo dos cuentas en omegaUp. Mi cuenta principal es: "flopezorozco" y la secundaria es: "francisco.orozco". 

La segunda cuenta la he usado principalmente para inscribirme como estudiante en cursos que imparto desde "flopezorozco". Sin embargo, se trata de la misma persona.

En estos días he estado haciendo muchas pruebas desde las dos cuentas y pienso me bloquearon de forma tal que ya no aparezco con RANK en "flopezorozco". Me gustaría me quiten este bloqueo y de ser posible eliminar la otra, la secundaria: "francisco.orozco".

En su defecto me pueden indicar si este bloque se quita al terminar el mes o cómo funciona.

Me disculpo por los inconvenientes.

Saludos.

F

**Comment by tvanessa** [comment]
Me parece que el problema es que el perfil es privado. Eso elimina los colores de usuario y los descarta del rank.
Si el  perfil se cambia a público, mañana deberia aparecer de nuevo el color/rank.

Cambiare el issue a una propuesta sobre mantener el rank aunque el perfil sea privado.
