### ISSUE TITLE
Las notificaciones de clarificación no desaparecen cuando se contestan.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#665]
Si alguien más contesta una clarificación, debería desaparecer el popup molesto.

**Comment by frcepeda** [comment]
Cuando tienes WebSockets, obvs.

**Comment by elendil326** [comment]
@lhchavez no se si poner esto en Contests o en PeerReview. Te lo asigno para que lo pongas donde mejor quede.

**Comment by pabo99** [comment]
@frcepeda ¿Esto sigue ocurriendo? ¿Puedes proporcionar más info?

**Comment by lhchavez** [comment]
sí, sigue ocurriendo. quizás lo mejor sea que cuando se conteste, se cierre ese popup y se abra uno nuevo con un timer de 5s de que ya se contestó que se autocierre.
