### ISSUE TITLE
[BUG] No se pueden descargar los templates de problemas interactivos

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#6652]
## Comportamiento Esperado

Al hacer click en el diálogo que deja bajar los templates, se descarga.

## Comportamiento Actual

400 - Bad Request.

## Pasos para reproducir

1. https://omegaup.com/arena/problem/COMI-Cola-Interactivo/
2. Ir a la parte de Evaluador
3. Descargar

![image](https://user-images.githubusercontent.com/468211/177216885-2504f264-19e7-4cbd-8a9d-fc0cb657504e.png)
![image](https://user-images.githubusercontent.com/468211/177216909-557a7d9e-c5dd-4f6b-b5ce-fc695a6e57ab.png)

## Tu ambiente

* Nombre del navegador: Firefox 101.0.1
* Sistema Operativo y versión: Windows 10

**Comment by lhchavez** [comment]
@pabo99 esto podría ser una regresión del cambio de la semana pasada?

**Comment by Juanito98** [comment]
También falla con MAC/Linux C++, por si les es útil

**Comment by tvanessa** [comment]
Sí, es mekor mandar el revert

**Comment by frcepeda** [comment]
Hay forma de agregar un test para esto? Estaría muy complicado? (No sé cómo están los tests de frontend)

Así cachamos la regresión antes de que en un concurso se ocupe un interactivo—creo que hace poco habíamos tenido la misma regresión

**Comment by pabo99** [comment]
Por lo pronto lo revertí. 

Habría que agregar una prueba de integración para evitar futuras regresiones.
