### ISSUE TITLE
Integración con Slack

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#667]
Sería la cosa más genial jamás integrar omegaUp con slack.

https://api.slack.com/

Imagina... un canal de clarificaciones. :O

**Comment by lhchavez** [comment]
:+1: pendiente de la decisión de seguir usando Slack a largo plazo

**Comment by frcepeda** [comment]
listo :white_check_mark:

**Comment by elendil326** [comment]
@lhchavez esto requiere un poco de explicitez en cuanto a que cosas deben ser trasmitadas por slack.

**Comment by lhchavez** [comment]
Ya está hecho :) (@frcepeda nunca lo cerró :P)
