### ISSUE TITLE
[BUG] La gráfica de envíos no se muestra durante un concurso privado

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#6676]
## Comportamiento Esperado

Que durante un concurso en la vista del Ranking como admin, se pueda ver la gráfica así 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/5167417/178339929-d336bf47-84d3-46c4-9abf-5f247527884d.png">

## Comportamiento Actual

Aparece en blanco

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/5167417/178339961-a76293a4-8a91-4aa8-9df3-43026dead9e2.png">

## Pasos para reproducir (para bugs)

1. Entrar a un concurso privado como admin mientras está abierto, ir a la pestaña de Ranking

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Version 103.0.5060.114 (Official Build) (arm64) 
* Sistema Operativo y versión (escritorio o móvil): macOS Monterey 12.4
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/Selectivo-EGOI-2022-2/#ranking (siempre y cuando esté abierto aún)
* Captura de pantalla:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/5167417/178340401-b70e2b94-304e-42da-9b7d-4a700a1e9f45.png">

**Comment by heduenas** [comment]
Logré reproducir este bug creando un concurso privado con las siguientes configuraciones:
<img width="1081" alt="Screenshot 2022-12-20 at 12 36 10 AM" src="https://user-images.githubusercontent.com/597815/208621244-6e63ac3d-3267-4bc5-b966-b36e2d2b365b.png">
<img width="1067" alt="Screenshot 2022-12-20 at 12 36 16 AM" src="https://user-images.githubusercontent.com/597815/208621251-656f9cb4-6980-4f27-9ce1-b9a9f6ecdbef.png">

Sospecho que como la configuración dice que no se va a mostrar el scoreboard a los concursantes, tampoco se le muestra a los admins.

**Comment by pabo99** [comment]
Ah, eso tiene mucho sentido. Intento reproducirlo en mi ambiente local para solucionarlo
