### ISSUE TITLE
Grupos

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#668]
Con el sistema actual de la OMI, todos los colaboradores compartimos una cuenta a la cual subimos problemas, sería mejor si tuvieramos un concepto de grupos, en donde OMI no es un usuario, sino un grupo, y asi tengamos mas control sobre quien sube qué y quien puede hacer que.

**Comment by alanboy** [comment]
suben problemas a un concurso? porque no crear varios usuarios y poner a esos usuarios como admins, eso se puede?

**Comment by darknut** [comment]
Todos subimos problemas a diferentes concursos, pero no todos estamos en cada examen.

**Comment by joemmanuel** [comment]
La idea es buena, pero necesitamos un mejor nombre. Sugerencias?

On Wed, May 20, 2015 at 3:20 PM, Felix Cuadrilla <notifications@github.com>
wrote:

> Todos subimos problemas a diferentes concursos, pero no todos estamos en
> cada examen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/668#issuecomment-104060077>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by dominoFire** [comment]
OmegaUp ACL ?

**Comment by lhchavez** [comment]
tenemos una implementación súper rudimentaria de RBAC que nunca se le dio mantenimiento y sí es bastante subóptima. :+1:. quién se anima a aventarse omegaUp ACL/RBAC de verdad?

**Comment by lhchavez** [comment]
de hecho ahora que lo pienso hay que matar el _usuario_ omi.

**Comment by darknut** [comment]
Pero ese usuario lo usamos todos D:

Perderemos el acceso a los exámenes pasados y eso no es cool.

**Comment by alanboy** [comment]
>Pero ese usuario lo usamos todos D:

con mayor razon hay que matarlo :P @lhchavez  que falta para un ACL/RBAC de verdad?

**Comment by lhchavez** [comment]
Todo :P Ahorita solo tenemos dos niveles de usuario (usuario de verdad y Admin, pero hay hacks para permitir Contest/Problem admin). No existen grupos.

Yo digo que lo que hay que hacer es tirar la implementación actual a la basura y usar una librería que ya implemente todo, porque es un relajo hacerlo a patín y no vale la pena.

**Comment by lhchavez** [comment]
Separando el task de hacer los permisos y abriendo #673 para que este bug sea solo para implementar los grupos de usuarios.

**Comment by joemmanuel** [comment]
+1.
No podemos matar al usuario OMI hasta que tengamos esto implementado.



On Fri, May 22, 2015 at 8:25 AM, lhchavez <notifications@github.com> wrote:

> Separando el task de hacer los permisos y abriendo #673
> <https://github.com/omegaup/omegaup/issues/673> para que este bug sea
> solo para implementar los grupos de usuarios.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/668#issuecomment-104689546>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by darknut** [comment]
Concuerdo con Joe.
