### ISSUE TITLE
[BUG] Agregar problemas a un curso siempre los pone al inicio de los preexistentes

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#6682]
## Comportamiento Esperado

Cuando un curso tiene ya problemas y se le agrega uno nuevo, este ultimo debe agregarse al final de la lista.

## Comportamiento Actual

Cuando se agrega un nuevo problema a la tarea de un curso, siempre se inserta al inicio de la lista, y se tiene que mover manualmente al final y despues darle click a `Guardar nuevo orden`.

## Posible Solución

N/A

## Pasos para reproducir (para bugs)

Crea un nuevo curso con una tarea con al menos un problema o visita uno existente.

1. Ve al curso para editarlo.
2. Dale click a a Editar contenido a una tarea con problemas.
3. Agrega un nuevo problema a la tarea.
4. Nota como se inserta al inicio de la lista en vez del final.

## Contexto

N/A

## Tu ambiente

En https://omegaup.com/course/intermedio-algo-tecnm-culiacan/edit/#content

Antes:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/606680/178896252-9876de31-9cbe-4a5a-8ed1-e32edee13e1b.png">

Despues:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/606680/178896334-79508c4c-e59f-494c-a4a1-1835c4dfa69c.png">

**Comment by wkoder** [comment]
Acabo de notar que si agrego un contenido nuevo y agrego problemas antes de guardar el nuevo contenido, los problemas si se van agregando al final. Esto significa este bug solo es reproducible cuando se editar un contenido de tarea.

**Comment by pabo99** [comment]
Assigned to: @mohannedah
