### ISSUE TITLE
[BUG] No se pueden buscar problemas por texto libre

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#6683]
## Comportamiento Esperado

En el buscador de problemas (https://omegaup.com/problem/), escribe un texto como `bits` y, sin seleccionar ninguna opcion, dale click a `Buscar` y mostrara los problemas que tiene `bits` como parte del titulo (o cualquier criterio que use omegaUp para buscar, como la descripcion).

## Comportamiento Actual

En el buscador de problemas (https://omegaup.com/problem/), escribe un texto como `bits` y, sin seleccionar ninguna opcion, dale click a `Buscar` y no muestra nada relacionado con bits. Ademas, el campo de busqueda se limpia y el parametro `query` en la URL tiene un valor vacio: https://omegaup.com/problem/?query=

Editar manualmente el parametro `query` en la URL funciona, pero es incomodo y el URL encoding faltante puede hacer que falle la busqueda.

*Describe lo que pasó en lugar de lo que se esperaba*

## Posible Solución

Permitir texto libre en el campo de auto-completado.

## Pasos para reproducir (para bugs)

1. Visita https://omegaup.com/problem
2. Escribe `bits` en el campo de busqueda
3. Sin selecciona ninguna opcion de auto-completado, dale click al boton `Buscar`
4. Los resultados no hacen match con la busqueda.

## Contexto

N/A

## Tu ambiente

N/A

**Comment by darknut** [comment]
Ya venía a abrir un issue sobre este bug. Que bueno que no soy el único que le molesta esto.

**Comment by pabo99** [comment]
Entendido. Pronto se tendrá que arreglar esto
