### ISSUE TITLE
Colección de problemas

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#669]
Buscar problemas dentro de omegaup es muy difícil porque lo único por lo que puedes filtrar es por nombre.

Si pudieramos hacer colecciones de problemas facilitaría la organización de los problemas.

Ejemplos:
http://www.cmirg.com/karelotitlan/Pantallas/problemasOMI.aspx 
https://lobishomen.wordpress.com/2014/07/23/omi-training-gate-en-omega-up/
https://lobishomen.wordpress.com/2014/07/23/problemas-del-omi-training-gate-en-clasificacion-tematica/

**Comment by alanboy** [comment]
eso ya se puede con logs tags. yo tengo todos los problemas de teddy, taggeados: 
https://omegaup.com/problem/?tag=teddy

**Comment by darknut** [comment]
Es una solución, aunque no creo que sea la mejor solución al problema

**Comment by alanboy** [comment]
cual seria una mejor solución?

**Comment by darknut** [comment]
Que la gente pueda hacer listas de problemas. :)

**Comment by alanboy** [comment]
cual es la diferencia entre tener problemas agrupados por un tag, o tener problemas agrupados por una lista ?

**Comment by darknut** [comment]
Que puedo tener problemas que no son de mi autoría en una lista, y que los problemas no acaban con N tags si es que lo quiero en N listas.

**Comment by joemmanuel** [comment]
Me gusta la idea de las listas puesto que tiene un sentido de pertenencia a un usuario. El tag puede ser usado para temas, mientras que la lista es para colecciones personales.
+1

**Comment by joemmanuel** [comment]
@darknut quieres dártela?

**Comment by darknut** [comment]
en estos momentos estoy haciendo otro proyecto para la OMI, pero en cuanto acabe, no tengo problemas en implementar este feature

**Comment by lhchavez** [comment]
Otra cosa que es muy similar-pero-no-realmente a tags. No me gusta la idea de pertenencia a un usuario porque terminas con exactamente el mismo problema que menciona @darknut: puedes tener una lista que _no_ es de tu autoría y sería genial agregar un nuevo problema, pero el dueño no lo hace.

Cuál es el problema con terminar con $N$ tags por problema? Clutter en la interfaz? A mí nuevamente me parece que StackOverflow lo ha resuelto bien.

**Comment by lhchavez** [comment]
(Una vez dicho esto, si alguien lo implementa y hace pull request y está bonita la interfaz, aceptaré el request y me callaré :P)

**Comment by alanboy** [comment]
siento que esto se puede resolver mejor con tags.

> Buscar problemas dentro de omegaup es muy difícil porque lo único por lo que puedes filtrar es por nombre.

y como mejora con que cada usuario pueda crear sus listas? tengo que entrar al perfil de cada quien para ver que listas tiene? esta genial que cada quien tenga sus listas, pero eso no ayuda en mucho.

si quisiéramos implementar listas: esto se puede implementar muy fácilmente usando los tags como backend asi que el trabajo es minimo.

1) agregar un UI a cada problema: "agregar a mi lista de favoritos"
2) asignarle un tag de `token_${username}_${nombre de lista}` 
3) en el api de tags, no regresar tags que comienzan con `token_`
4) en el UI de perfil, mostra tus listas

**Comment by alanboy** [comment]
prefiero mil veces que mejoremos los tags. que sean fáciles de crear, asociar, **agregar tags a los criterios de busqueda** seria critico. taggear un problema automáticamente una vez que se uso en algun concurso, etc.

**Comment by darknut** [comment]
Pero eso me limita a tener solamente una lista por username. La solución es crear un username por cada lista que quiera?

**Comment by lhchavez** [comment]
Según el punto 2) de @alanboy el tag contiene un nombre de lista, así que se podría tener más de una lista por username.

Y repito, el namespace por username es la parte _menos_ elegante de la idea y que en realidad no resuelve el problema de raíz :P pero no estoy en contra de hacer namespaced tags en general.

**Comment by limitedmage** [comment]
Crea un concurso y córrelo en modo práctica? :)

**Comment by lhchavez** [comment]
@limitedmage te faltó una trollface por ahí :P hacer un concurso tiene los mismos inconvenientes que los user-namespaces y mi principal queja en contra de la idea: terceras personas no pueden editarlas.

**Comment by elendil326** [comment]
@lhchavez quién es la mejor persona para definir este user scenario bien?

**Comment by elendil326** [comment]
Esta es una discusión larga e interesante. @lhchavez como cerramos #670 en favor a #672. Deberíamos cerrar este también y enfocarnos en definir #672?
