### ISSUE TITLE
[Plagiarism Detector]  Support the plagiarims_threshold in Contest Controller. 

### ISSUE THREAD

**Issue by MohitOhlyan** [omegaup/omegaup#6696]
## Topic
Update the contest controller to support the plagiarism_threshold. 

## Comments

For these changes, do we require a unit test too? Or just Validations are enough? 

## Contexto

Is Needed to check if a particular contest requires plagiarism or not and what is the similarity threshold for the same is. 

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4):
* Sistema Operativo y versión (escritorio o móbil):
* Link al sitio en el que este problema pasa:
* Captura de pantalla:

**Comment by pabo99** [comment]
> For these changes, do we require a unit test too? Or just Validations are enough?

Yes, we do. 

If you need some help to create the unit test, tell us!

**Comment by MohitOhlyan** [comment]
> > For these changes, do we require a unit test too? Or just Validations are enough?
> 
> Yes, we do.
> 
> If you need some help to create the unit test, tell us!

Okay. I will add those too. 

Will surely ask if I get struck somewhere. Thanks!
