### ISSUE TITLE
Temas por problema

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#670]
Sería interesante agregar a cada problema el tema del que se trata para que alguien que necesite mejorar en el tema X pueda buscar problemas que usen ese tema. 

Esto se puede desactivar para exámenes o prácticas en particular a las que no queramos darle información de más a los usuarios.

**Comment by alanboy** [comment]
eso ya lo platicamos hace mucho tiempo y en ese momento decidimos que encontrar que tipo de problema estas enfrentando es parte del reto de resolverlo.

**Comment by darknut** [comment]
Eso es depende de cómo quieras ver OmegaUp.

Cuando ya tienes algo de experiencia resolviendo problemas, concuerdo en que es parte del reto, pero cuando eres nuevo a la programación competitiva, solo vas a ver un montón de problemas que probablemente no estén a tu nivel. 

Si tuviéramos una clasificación de problemas como principiantes / fáciles / difíciles / etc, eso resolvería las cosas.

Hacer colecciones también ayudaría a esto.

**Comment by alanboy** [comment]
Para eso es el ratio o Points for ranking. Problemas ordenados según su dificultad:

https://omegaup.com/problem/?query=&order_by=points&mode=asc

Estoy deacuerdo con que no es intuitivo, y a mi me acaba de tomar varias "ordenadas" de points for ranking y ratio para darme cuenta masomenos que siginfican.

Podemos mejorar mucho la experiencia de usuario y hacer que los problemas faciles sean tambien los mas faciles de encontrar.

**Comment by darknut** [comment]
Aunque esto ayuda, cuánta gente ha hecho un problema no habla de su dificultad, sobre todo si yo no sé ciertos temas y lo que quiero es practicar los temas que ya conozco.

**Comment by lhchavez** [comment]
Los temas/niveles de dificultad son medio subjetivos y están bien modelados por los tags. No creo que sea buena idea hacer algo muy similar pero no realmente a los tags (aunque podría ser convencido de un mejor sistema de asignación de tags, como el que tiene stackoverflow).

**Comment by elendil326** [comment]
@lhchavez que procede con este issue? Won't Fix?

**Comment by lhchavez** [comment]
Won't fix porque siempre sí lo vamos a tener con tags.
