### ISSUE TITLE
Tags comunitarios

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#672]
Los tags pueden modelar bien y superceder a #669 y a #670. Hay unos problemas que habría que resolver:
- Clutter visual. Todos los tags se despliegan debajo de cada problema en la lista. Podemos elegir que algunos tags se desplieguen siempre y que otros no lo hagan. Por ejemplo, `karel` y `lenguaje` sí sería bueno que siempre estuvieran ahí, al menos. También si es un problema "oficial" o no.
- Permisos. Actualmente solo el dueño del problema puede editar los tags. Sería bueno levantar esta restricción (tal vez con un permiso de editar tags global, karma, o algo así). En un mundo óptimo, se podrían crear algunos tags solo para administradores y dar permisos a grupos o usuarios sobre esos tags, para evitar a toda costa atar los tags a un solo usuario. Esto depende de #673.
- Lista de tags. Los tags no tienen un índice para buscarlos y ahorita tienes que ir a los problemas y hacer click en un tag (o peor, acordarse del nombre del tag y escribirlo en el textbox).

**Comment by elendil326** [comment]
@lhchavez asignará apropiadamente para definir el diseño esperado.

**Comment by npave** [comment]
Estaría bien dar semántica a los tags cómo lenguaje de programación, idioma, dificultad, tema... Después podríamos utilizar esta información para crear un sidebar con diferentes opciones para que el usuario encuentre los problemas que se adecuen a sus necesidades.

**Comment by tvanessa** [comment]
Esto ya se puede cerrar? Por el proyecto de calidad y el problem finder?
