### ISSUE TITLE
[FEATURE] Como usuario/contribuidor me gustaría ver Karel.js actualizado

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6754]
## Comportamiento Esperado

[Karel.js](https://omegaup.com/karel.js/#) esta actualizado con el repo de [github](https://www.github.com/omegaup/karel.js)
 
## Comportamiento Actual

Karel se encuentra usando esta version/commit: [2777e2d](https://github.com/omegaup/karel.js/tree/2777e2d58eb118da1dfab54350347a0269b08a34)

## Posible Solución

Actualizar el modulo de git

## Contexto

Tiene features nuevas, bug fixes y varios dependency bumps.

Tambien, en lo personal, hay contribuciones mías que amaría ver en prod.

* https://github.com/omegaup/karel.js/issues/120
* https://github.com/omegaup/karel.js/issues/118

**Comment by kishtarn555** [comment]
Puedo hacerlo yo, pero no pude levantar la vm de docker.

![image](https://user-images.githubusercontent.com/19498800/197038082-b536345f-74ff-400e-ba3a-cc383ca4de30.png)

Segun yo lo que hay que hacer es nadamas 
1) clonar el repo.
2) Correr git submodule update frontend/www/karel.js
3) Correr los tests
4) PR.

Pero me trabe en el paso 1. Segui los pasos de https://github.com/omegaup/omegaup/wiki/Instalaci%C3%B3n-de-m%C3%A1quina-virtual

**Comment by kishtarn555** [comment]
Please, git submodule update, it has been two years.

**Comment by JACazares** [comment]
+1 !!

**Comment by heduenas** [comment]
@pabo99 puedes echarle un ojo a este issue por favor?

**Comment by pabo99** [comment]
Intenté lo siguiente en el repo de `karel.js`:

- `git fetch origin`
- `git merge origin/main`

y luego en el repo de `omegaup`:
- `git submodule update`

Pero al parecer no se actualiza la versión.

También intenté crear una nueva versión (v1.1.3), pero seguí sin poder actualizar el submódulo. 

@lhchavez: se nos está pasando algo?

**Comment by heduenas** [comment]
Acabamos de sacar un nuevo release de karel.js y acabo de armar https://github.com/omegaup/omegaup/pull/7668 para actualizarlo en omegaup.

**Comment by heduenas** [comment]
El sabado o domingo sale a producción la nueva versión de Karel
