### ISSUE TITLE
Mejorar el mensaje en cursos si la información de perfil está incompleta

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#6758]
En cursos, si se pide la información de los participantes, se desactiva el botón de Iniciar.

![image](https://user-images.githubusercontent.com/940007/189490304-dc9fcc03-3b2e-4652-b965-96b4a20c6743.png)

**Comment by tvanessa** [comment]
Esta bloqueado porque en este caso la persona que intenta ingresar no ha completado su perfil. Es decir, si la información es requerida y no hay información, no puede iniciar el curso.

@npave podemos cambiar algunas cadenas para hacerlo más claro. Las sugerencias son bienvenidas

**Comment by IngridRB** [comment]
@tvanessa puedo trabajar en este issue, cuales serían las nuevas cadenas de traducción?

**Comment by tvanessa** [comment]
Sugiero mover la cadena en cuestión a la sección de "Consentimiento de privacidad de curso". Además, agregar bullets a cada subsección.

Acá dejo un mock:

![189490304-dc9fcc03-3b2e-4652-b965-96b4a20c6743](https://user-images.githubusercontent.com/13296248/225825840-001821d3-fd69-4c20-9a10-f41aac22d557.png)

**Comment by pabo99** [comment]
Punto extra si el link te manda directo a la pestaña de "Información básica":

![image](https://user-images.githubusercontent.com/3230352/225826465-51f4ea6d-a3c7-4b7d-b859-ea079b956339.png)

De hecho, me parece que esa pestaña bien podría llamarse "Información básica" en lugar de "Editar perfil"

**Comment by IngridRB** [comment]
Hola @tvanessa @pabo99, me pueden indicar los pasos para reproducir el issue? Estoy intentando que me salga el texto de "Consentimiento de privacidad" pero no lo consigo. 

Por ejemplo, cree en un curso con esta configuración:
![image](https://user-images.githubusercontent.com/110271913/226143516-ce515af7-3574-480a-9856-098db77bb60a.png)

Al usuario cuando quiere acceder le sale así:
![image](https://user-images.githubusercontent.com/110271913/226143524-c424b04c-5728-4600-877e-b765835a5c59.png)
