### ISSUE TITLE
OFSHACKATHON: Cambiar lenguaje en editar perfil no funciona 

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#676]
Intente poner mi lenguaje como ingles, o pseudo-loc, pero siempre me muestra la pagina en español.

**Comment by alanboy** [comment]
Arreglado en https://github.com/omegaup/omegaup/pull/1094

**Comment by Yisusgamer20** [comment]
Como le cambio el idioma me aparece en ingles y lo quiero cambiar a español
