### ISSUE TITLE
Error al ver el código de un envío en un problema que administro

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6768]
Hola a todos. El problema https://omegaup.com/arena/problem/Matrices-concentricas es de mi autoría, pero omegaUp no me permite ver varios de los códigos que ocurrieron del 2022-04-13 al 2022-06-09. El mensaje dice que mi usuario no tiene permisos para ello.

![image](https://user-images.githubusercontent.com/19719969/191633164-a40e7547-88cd-41a0-a674-2c3e6ae74568.png)

`{"status":"error","error":"No tienes los permisos para realizar esa acci\u00f3n","errorname":"userNotAllowed","errorcode":403,"header":"HTTP\/1.1 403 FORBIDDEN","_id":"632bad849463a184716140"}`

**Comment by tvanessa** [comment]
Sólo te ocurrio en un problema? O en varios?
Otra cosa, primero si podías ver los detalles y después ya no? O más bien nunca te dejo?

**Comment by darkmx** [comment]
Ya me ocurrió en varios otros problemas.

Sobre lo otro, ese problema hace mucho no lo dejo de tarea (~2 años) y no estaba al tanto de los envíos que otros usuarios hicieron durante ese tiempo. Cuando corrí mi programa para bajar todos los envíos de este año, ocurrió eso.

**Comment by darkmx** [comment]
Este bug sigue ocurriendo y ahora también con envíos recientes:
https://omegaup.com/arena/problem/El-cuello-de-Alicia-y-los-nidos-?fromLogin=#runs

![image](https://github.com/omegaup/omegaup/assets/19719969/d9c9e7b9-32b4-4020-bbd1-8c309efdb93c)


`status: 'error', error: 'No tienes los permisos para realizar esa acción', errorname: 'userNotAllowed', errorcode: 403, header: 'HTTP/1.1 403 FORBIDDEN', …}
error
: 
"No tienes los permisos para realizar esa acción"
errorcode
: 
403
errorname
: 
"userNotAllowed"
header
: 
"HTTP/1.1 403 FORBIDDEN"
httpStatusCode
: 
403
status
: 
"error"
_id
: 
"648143be3d1cf741218972"`

Si bien me había dado cuenta de este bug con envíos viejos (y por eso, relativamente irrelevantes), esta vez me está causando problemas con envíos recientes de una tarea que aún no califico. ¿Habrá manera de darle prioridad?

**Comment by pabloaguilar** [comment]
Parece ser a propósito:
https://github.com/omegaup/omegaup/blob/main/frontend/server/src/Authorization.php#L130-L148

Si el envío se hizo a un concurso o tarea, tienes que tener acceso administrativo al concurso o tarea, no es suficiente ser admin del problema.

**Comment by darkmx** [comment]
De ver el código no me queda claro que sea intencional, sólo que por el momento es así.
¿En algún momento se decidió explícitamente que fuera así?, en caso afirmativo, ¿por qué? ya que pudo terminar siendo accidental y no intencional. Si en verdad fue intencional, no tiene mucho caso mostrarme envíos que no puedo ver.

**Comment by tvanessa** [comment]
Esa decisión se hizo hace más de 10 años. Podemos revisar si esa condición es necesaria ahora.

**Comment by darkmx** [comment]
Una cosa que me llama la atención es que la función se llama `canEditSubmission`, No sé en realidad qué se pueda editar del envío (tal vez reevaluarlo o descalificarlo se pueda considerar editarlo) y en todo caso está bien que el autor del problema no pueda andar reevaluando a su antojo los envíos que fueron hechos en tareas y cursos que no son suyos, pero creo que sí debería poder ver los envíos y su contenido.

**Comment by tvanessa** [comment]
El commit que mencionas solo le da permisos a un nuevo ACL. Acá es donde se introduce la condición https://github.com/omegaup/omegaup/commit/fc5d37c805f13afe709314900b803f62c20f9652

**Comment by pabo99** [comment]
> El edit que implementó ese cambio fue de septiembre 2022 ([9756c21](https://github.com/omegaup/omegaup/commit/9756c2150598805a4e060b850f363f3874f8f407)) y no menciona nada de qué debe pasar con el administrador del problema (sólo menciona cosas del "teaching asistant"). Ciertamente, antes de esa fecha no ocurría ese fenómeno y los usuarios nos acostumbramos al comportamiento de la plataforma, esto a pesar de que una decisión de diseño distinta tuviera tiempo de haberse tomado.
> 

Intentaré reproducir el bug con la información que nos proporcionas, y revisar si el problema viene desde ese commit.

**Comment by darkmx** [comment]
En el commit que menciona Vanessa yo veo lo siguiente en la función `CanEditRun`, líneas 42 a 44:
  `return $isContestAdmin || self::IsSystemAdmin($user_id) || $problem->getAuthorId() === $user_id;`
En este caso, el autor del problema es el que intenta ver el run. La función `CanViewRun` delega a `CanEditRun` cuando el run es de un usuario que no es el mismo que lo intenta ver.

El reporte inicial de bug lo publiqué en fecha de 21 de septiembre de 2022 y el commit que mencioné tiene fecha de 12 de septiembre de 2022. Es mucha coincidencia. Mis problemas suelen ser usados en muchos cursos (públicos y privados) y en concursos, y jamás había ocurrido que omegaUp me rechazara la descarga de un código que un usuario envió en un problema mío.
