### ISSUE TITLE
[BUG] Broken Link "See the tutorial" in home page 

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#6770]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5838427/192961592-b4b351de-540a-42af-8033-3683c144d818.png">

redirect to "This is not the page you were looking for". Also, Links driving to external page should open in a new tab. (Same for Join to Discord)

**Comment by tvanessa** [comment]
Creo que el link para ver el tutorial se rompió con la migración del blog (?)

 Este es el link correcto. https://blog.omegaup.com/introduccion-a-omegaup-parte-0/

@MikeMAMR puedes mandar 2 PRs? uno para arreglar el link y otro para abrir paginas externas en otra pestaña, por favor.

**Comment by MikeMAMR** [comment]
Si claro
