### ISSUE TITLE
[FEATURE] Soporte de Python3

### ISSUE THREAD

**Issue by sergio10barca** [omegaup/omegaup#678]
Hola sería posible tener la versión mas reciente de python, en partircular la 3.4.3, y que de alguna manera coexistiera con la que ya está (la 2.x.x), saludos!!!

**Comment by joemmanuel** [comment]
Hay razones para mantener ambas versiones? - hay breaking changes o cambios
de performance significativos?

2015-06-02 7:29 GMT-07:00 Sergio Luis Pérez <notifications@github.com>:

> Hola sería posible tener la versión mas reciente de python, en partircular
> la 3.4.3, y que de alguna manera coexistiera con la que ya está (la 2.x.x),
> saludos!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/678>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by lhchavez** [comment]
sí, hicieron cambios incompatibles en la sintaxis. puedes importar un
chingo de cosas para soportar tanto 2 como 3 en el mismo script, pero es
horrible.

**Comment by lhchavez** [comment]
Pues sí es un poco complicado, pero definitivamente se puede hacer. Hay que hacer todo lo siguiente:

* Agregar el paquete de Python3 de Ubuntu en https://code.launchpad.net/~omegaup/omegaup-minijail/packaging (en el archivo http://bazaar.launchpad.net/~omegaup/omegaup-minijail/packaging/view/head:/debian/control )
* Modificar https://github.com/omegaup/minijail/blob/master/mkroot para agregar un chroot para Python3 (ahí hay ejemplos para Ruby, Python, etc.)
* Crear scripts de llamadas de sistema permitidas por minijail tanto en x86_64 como en armhf en https://github.com/omegaup/minijail/tree/master/scripts
* Probar que funciona tanto en x86_64 como en armhf.

Como es una inversión significativa, solo estamos agregando nuevos lenguajes si alguien se compromete a subir muchos envíos en ese lenguaje (o si tú estás dispuesto a hacer el cambio, nosotros te apoyamos, sobre todo con lo de ARM).

**Comment by rysard** [comment]
Hola, veo que ya agregaron el paquete, y me gustaría saber como seguir, teniendo en cuenta que la extensión .py también funciona con python 3 (lo digo sobre todo con el script de llamadas de sistema)
