### ISSUE TITLE
No me permite cargar las soluciones, me pide volver a intentarlo 

### ISSUE THREAD

**Issue by abelmo770** [omegaup/omegaup#6780]
## Comportamiento Esperado
Aceptar el codigo escrito en el area de texto o cargar el codigo a evaluar

*Describe lo que esperabas que pasara*
Que se recibiera la solucion y evluara el codigo

## Comportamiento Actual
Me manda un mensaje que indica que no se puede cargar y que vuelva a intentarlo

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. el enlace https://omegaup.com/course/ISIC_ED/assignment/IED#problems
2. intento realizar un envio de solucion del problema
3. escribo el codigo o cargo el archivo de la solucion 
4. me muestra un mensaje que no se pudo cargar el envio y que lo intente nuevamente

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/course/ISIC_ED/assignment/IED#problems
* Errores en la consola: []
* Captura de pantalla:

**Comment by pabloaguilar** [comment]
Esto ya debería haberse arreglado. Podrías verificar intentándolo nuevamente?

**Comment by abelmo770** [comment]
Hola Pablo, Como lo mencionas ya se arreglo la situacion planteada, al siguiente dia ya estaba funcionando normalmente todo.

Muchas gracias.
