### ISSUE TITLE
[BUG] En la interfaz de modificación de problema, el tiempo de validador está deshabilitado para problemas con validador

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6812]
Hola a todos. La plataforma no permite editar (desde la interfaz) el tiempo límite del validador:
![image](https://user-images.githubusercontent.com/19719969/198890384-48da0c9a-6da7-405c-817a-44f95781b092.png)

Si se quita el disabled a mano y se solicita la actualización, sí se actualiza el valor.

**Comment by pabloaguilar** [comment]
Creo que va a ser que el tipo de validador no se actualiza propiamente. Puedes confirmar, @darkmx si un problema ya tiene su tipo como validador personalizado, al recargar la página se sigue viendo desactivado?

**Comment by darkmx** [comment]
Ése era uno de esos. Desde el inicio ese problema fue con validador y ya tiene más de un año (me metí ayer a moverle).
