### ISSUE TITLE
[FEATURE] Como un entrenador me gustaría poder crear cursos públicos

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6842]
## Comportamiento Esperado

Poder crear cursos que no sea necesario que el administrador los acepte para tener acceso, de forma similar a los cursos de C++, Python, etc.

## Comportamiento Actual

Si compartes un link de curso creado por un usuario, este solo puede ser accedido una vez el administrador del concurso acepte al que solicite entrar.

## Posible Solución

Habilitar la opción de crear cursos de acceso publico. No es necesario que estos aparezcan en la lista

## Alternativas consideradas

https://github.com/omegaup/omegaup/issues/5247

https://github.com/omegaup/omegaup/issues/6847

## Contexto

Quiero crear un curso de acceso publico para Karel, Algoritmos con un enfoque diferente a los ya creados.

**Comment by heduenas** [comment]
Hola Hector,

Muchas gracias por tu interés en crear contenido publico en omegaUp. Para hacer publico tu curso necesita pasar por un proceso de revision. Para ello, podrías por favor mandarnos a hello@omegaup.com un correo con el alias de tu curso para someterlo a revision?

**Comment by kishtarn555** [comment]
@heduenas Sí, creo que haré eso, pero el curso que quiero en este momento, pero en general

Pero en este issue en realidad es lo siguiente es otro modo de acceso a cursos (Un modo abierto):

Ahorita existe:

*  Featured (Los cursos que salen en: https://omegaup.com/course/ y que tienen la calidad garantizada)
* Por solicitud (Los usuarios piden permiso para tener acceso con el enlace)
* Manual (El admin añade usuarios)

Pero yo propongo
*  Featured (Los cursos que salen en: https://omegaup.com/course/ y que tienen la calidad garantizada)
* Abierto (Los cursos
* Por solicitud (Los usuarios piden permiso para tener acceso)
* Manual (El admin añade usuarios)

**Comment by kishtarn555** [comment]
> Hola Hector,
> 
> Muchas gracias por tu interés en crear contenido publico en omegaUp. Para hacer publico tu curso necesita pasar por un proceso de revision. Para ello, podrías por favor mandarnos a [hello@omegaup.com](mailto:hello@omegaup.com) un correo con el alias de tu curso para someterlo a revision?


Ya lo propuse?

Normalmente cuanto tiempo se tarda el proceso de evaluación?

Porque me gustaría tenerlo público cuanto antes para usarlo

**Comment by 5an7y** [comment]
Este issue lleva un año y algunos meses y sigo apoyando la nocion de Hector de tener una forma de poner un curso con acceso directo de link, sin la necesidad de tener que aceptar manualmente a cada uno de los usarios. Pero tampoco quiero poner el curso como algo de acceso directo desde la lista de cursos en OmegaUp.

**Comment by kishtarn555** [comment]
Otra posible implementación es una opción de auto-aceptar solicitudes para ciertos cursos

**Comment by pabo99** [comment]
Ok. Discutiremos este tema en la siguiente reunión y les comunico los resultados

**Comment by tvanessa** [comment]
Sugerencia: Crear sello de calidad para cursos públicos. Sólo los que tengan el sello aparecen en https://omegaup.com/course/. El resto se puede compartir libremente con el URL.

**Comment by pabo99** [comment]
Tareas a realizar (se les puede dar seguimiento en issues diferentes):

- Agregar campo `recommended` o `quality_seal` en la tabla de `Courses`
- Crear `omegaup.API.Course.setRecommended` o `omegaup.API.Course.setQualitySeal` (sólo el rol de administrador podrá realizar esta acción)
- Crear la interfaz para marcar como realizar la acción anterior a un curso (solo visible para administradores)
- Un administrador debrerá configurar todos los cursos públicos actuales con el distintivo.
- Mostrar sólo los cursos públicos con sello de calidad o recomendados en la vista de Cursos
- Habilitar la opción de "Crear cursos públicos" para todos los usuarios (Incluir mensaje de que el curso no aparecerá en la vista de cursos, sólo se podrá ingresar por medio de link. También deberá indicar el proceso para solicitar que su curso aparezca en el listado)

**Comment by kishtarn555** [comment]
Wooooo. Muchas gracias
