### ISSUE TITLE
[BUG] Problemas para iniciar sesion

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6846]
## Comportamiento Esperado

Inicias sesion perfectamente

## Comportamiento Actual

No inicia sesión y sale un mensaje diciendo "  SyntaxError: Unexpected token '<', " ".  Despues de varios intentos luego ya funciona, no se porque.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1.  Intenta iniciar sesion
2. Fracasa
3. Intentalo varias veces
4. Eventualmente puedes?

## Contexto

Mañana hay curso de olimpiada en el que voy explicar como usar omegaup, si este error se mantiene, será un problema. Pasa desde ayer.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Versión 107.0.5304.107 (Build oficial) (64 bits)
* Sistema Operativo y versión (escritorio o móvil): Windows 10 escritorio
* Link al sitio en el que este problema pasa: https://omegaup.com/login/?redirect=%2F
* Captura de pantalla:

Nota: En la captura borre mi contraseña como medida de seguridad, pero incluso escribiéndola bien sale ese error de Syntax error
![image](https://user-images.githubusercontent.com/19498800/202781666-9006854c-a63c-4bdc-b51c-da8ceea31207.png)

**Comment by tvanessa** [comment]
#6888
