### ISSUE TITLE
[BUG] Los alumnos pueden ver el scoreboard en un curso, incluso si esta configurado como que no.

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6849]
## Comportamiento Esperado

Si un curso tiene la opcion de: "Mostrar scoreboard" como "No", los alumnos no deberían poder ver el scoreboard
## Comportamiento Actual

El scoreboard es visible independientemente de esto.

## Pasos para reproducir (para bugs)

1.  Crea un curso con Mostrar el scoreboard como No
2.  Entra al curso como alumno
3.  Entra a una Tarea/Examen
4.  Ve el ranking

## Contexto
No quiero que los estudiantes vean el progreso de otros, eso crea un entorno competitivo cuando no es el objetivo.

**Comment by Sarthakparmar-04** [comment]
Vanessa, can you assign me to solve this issue?
