### ISSUE TITLE
[BUG] Error del juez al subir un problema con validador

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#6869]
Hola a todos.

Estoy intentando subir el problema https://omegaup.com/arena/problem/Analisis-sintactico-de-un-lengua/#problems y los envíos me están dando JE. Aparentemente, el juez está muriendo al intentar compilar el validador (pero no es CE).

![image](https://user-images.githubusercontent.com/19719969/206871216-58fab1be-6900-4a4e-895b-49d472deed59.png)

En https://racc.mx/ide/ estoy usando el mismo sandbox y ahí no hay problemas con el código del validador.

**Comment by lhchavez** [comment]
ah es porque el validador no compiló (ahi en el .zip con output viene `Unknown compile language "cpp20"`, es cosa de cambiar el lenguaje del validador como workaround)

**Comment by lhchavez** [comment]
según yo es esa que dices: `cpp20`, `cpp20-gcc`, `cpp20-clang`. no puedes usar `cpp` por ahora?

**Comment by darkmx** [comment]
Eso intentaré, pero tendré que reimplementar varias cosas :(

**Comment by darkmx** [comment]
No sé si hay se hizo deploy, pero sigue dando error :(
