### ISSUE TITLE
[FEATURE] Como un profesor, no se cual problema le estoy dando retroalimentación ni el contexto

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6875]
## Comportamiento Esperado

Cuanto me llega una notificación de que un estudiante quiere feedback en un curso. Le doy click y se  de cual problema se trata y el veredicto del código.

## Comportamiento Actual

Le doy clic y solo veo un código que no sé: 

* ¿De que problema es?
* ¿Cuanto saca y cual veredicto?

Me pierdo, no sé que estoy viendo.

## Posible Solución

Añadir eso: (Propuesta en la foto)

## Alternativas consideradas

Añadir más información en la notificación

## Contexto

Estoy dando clases y me pierdo dando retroalimentación.

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

* Captura de pantalla:
![image](https://user-images.githubusercontent.com/19498800/208222267-0eae5d4e-99ec-4aeb-94b7-35f0bc08a304.png)

**Idea**
![image](https://user-images.githubusercontent.com/19498800/208222474-80d51119-6148-412f-a26f-58787cdba051.png)

**Comment by kishtarn555** [comment]
También, si eres dueño del problema, ver en cuales casos funciono y cuales no.

**Comment by 5an7y** [comment]
+1
