### ISSUE TITLE
[BUG][Code Reviews] El botón, enviar retroalimentación no hace nada

### ISSUE THREAD

**Issue by kishtarn555** [omegaup/omegaup#6876]
## Comportamiento Esperado

Al darle al botón: "enviar retroalimentación" se envía la retroalimentación.

## Comportamiento Actual

No pasa nada, (o tal vez si y no hay feedback)

## Posible Solución

Si si hace algo, añadir feedback de que sucedió.

## Pasos para reproducir (para bugs)

Añade un comentario de feedback y dale a enviar
## Contexto

Dando clases de olimpiada, no funciona

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Versión 108.0.5359.125 (Build oficial) (64 bits)
* Windows
* omegaup.com/course/...
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/19498800/208223011-1d6a1d73-47b9-4a1e-9fec-6424e5ebfa14.png)

**Comment by heduenas** [comment]
Hola Hector,

Gracias por reportar este bug. El feedback linea por linea es un nuevo feature que estamos muy cerca de lanzar, pero aun no esta completamente listo.  Como solución temporal puedes usar el viejo feature de retroalimentación que te permite hacer comentarios generales sobre un código:

![Screenshot 2022-12-18 at 1 06 15 PM](https://user-images.githubusercontent.com/597815/208319359-56f31088-9182-4ade-9326-c55848f50370.png)

**Comment by kishtarn555** [comment]
> Hola Hector,
> 
> Gracias por reportar este bug. El feedback linea por linea es un nuevo feature que estamos muy cerca de lanzar, pero aun no esta completamente listo. Como solución temporal puedes usar el viejo feature de retroalimentación que te permite hacer comentarios generales sobre un código:
> 
> ![Screenshot 2022-12-18 at 1 06 15 PM](https://user-images.githubusercontent.com/597815/208319359-56f31088-9182-4ade-9326-c55848f50370.png)

Hola, sí, cuando le doy a dar retroalimentación con un botón. Solo puedo dejar retroalimentación por líneas. No sale el menú original.

**Comment by 5an7y** [comment]
Hola, tengo el mismo problema. No me deja enviar retroalimentacion de ninguna forma ni con el boton original, ni con la retroalimentacion linea por linea. Le das al boton y no hace nada.
[Video muestra.](https://drive.google.com/file/d/1JvYoTIfZS0G5D3o_OvlZhqAg3HDURCnC/view?usp=share_link)

**Comment by tvanessa** [comment]
@pabo99 se puede cerrar esto?

**Comment by pabo99** [comment]
Si, el campo de feedback general ya no existe.
