### ISSUE TITLE
[FEATURE][Code Reviews] Pedir confirmación antes de enviar solicitud de feedback.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6877]
Despues de dar click al boton para solicitar feedback hay que mostrar un modal que pida confirmar si se desea solicitar feedback. El usuario puede dar click por error o simplemente por curiosidad.

![Screenshot 2022-12-18 at 1 21 39 PM](https://user-images.githubusercontent.com/597815/208320233-bf111eb1-9c59-4104-bac6-eb99114c1bfb.png)

**Comment by pabo99** [comment]
Esto se resolvió en el PR #6892
