### ISSUE TITLE
[BUG][Concursos con subtareas] El puntaje del problema no toma en cuenta el nuevo metodo de evaluacion

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6878]
<img width="315" alt="Screenshot 2022-12-18 at 10 11 05 PM" src="https://user-images.githubusercontent.com/597815/208359693-00bb5af6-d24c-4528-9e26-cf9b8e3d1803.png">

El puntaje del problema A deberia de ser 75 en vez de 25.

Pasos para reproducir:
1. Crear un concurso con estos settings:
<img width="788" alt="Screenshot 2022-12-18 at 10 13 42 PM" src="https://user-images.githubusercontent.com/597815/208359856-c2e9af79-3e73-44e1-ab94-f8743a8e125f.png">
2. Agregar este problema al concurso: https://omegaup.com/arena/subtareas3/#problems/Clasificacion-Triangulos-Java
3. Hacer este envio como concursante:

```
#include <iostream>

int main() {
  std::cin.tie(nullptr);
  std::ios_base::sync_with_stdio(false);

  std::cout << "Escaleno\n";

  return 0;
}
```

5. Hacer este envio como el mismo concursante:

```
#include <iostream>

int main() {
  std::cin.tie(nullptr);
  std::ios_base::sync_with_stdio(false);

  std::cout << "Equilatero\n";

  return 0;
}
```

**Comment by heduenas** [comment]
Después de depurar un poco veo estos 2 pedazos de codigo que calculan el puntaje en un problema en un concurso:
* https://github.com/omegaup/omegaup/blob/faecb30ae27cbe6cd94a20a937db6ce884dc650f/frontend/www/js/omegaup/arena/ranking.ts#L251
* https://github.com/omegaup/omegaup/blob/0a9a05e5b47ca0a47e443acfe584dffc215af449/frontend/www/js/omegaup/arena/navigation.ts#L83

@pabo99 hay que actualizarlos para que calculen usando el nuevo metodo cuando el concurso sea por subtareas. Estoy casi seguro de que eso va a arreglar el bug.

**Comment by pabo99** [comment]
Perfecto. reviso si se puede hacer un refactor y todo se calcule en un sólo lugar

**Comment by heduenas** [comment]
![Screenshot 2023-05-01 at 10 39 52 AM](https://user-images.githubusercontent.com/597815/235498809-c49b1c1f-d3ff-4bce-91c3-57efb89439d4.png)

Ahora me "1/100" como puntaje en vez de "50" (como se muestra en el miniscoreboard).

**Comment by pabo99** [comment]
Perfecto, deja reviso a que se debe el problema

**Comment by heduenas** [comment]
Ahora se muestra como "NaN": 
![image](https://github.com/omegaup/omegaup/assets/597815/b7289cda-8c60-44d8-8e25-632e7f1873fd)

**Comment by heduenas** [comment]
Sigue pasando lo del NaN. Pero ya se por que es.

En esta linea:
https://github.com/omegaup/omegaup/blob/main/frontend/www/js/omegaup/arena/navigation.ts#L168
`runs[0]` no tiene definido `score_by_group` porque tiene veredicto `CE`.

En otra cuenta mi primer envio fue PA y me muestra puntaje 1.0. Y es que esa misma función no toma en cuenta el valor del problema, necesita recibirlo como parametro. https://github.com/omegaup/omegaup/blob/main/frontend/www/js/omegaup/arena/navigation.ts#L160
