### ISSUE TITLE
https://omegaup.com/api/contest/requests/contest_alias/{contest} es lento

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#688]
https://omegaup.com/api/contest/requests/contest_alias/CIIC2015Prueba/ tarda 15 segundos en regresar

**Comment by lhchavez** [comment]
Consistentemente? Es el único que tiene ese problema?

**Comment by lhchavez** [comment]
Ese sí es consistente. Ayer intenté abrir un par y no tenían ese problema.
En la noche veo qué pasa.

**Comment by alanboy** [comment]
consistente si, pero pues es el único que tiene muchos requests... voy a
revisar el código al rato.

-Alan

**Comment by lhchavez** [comment]
Creo que el problema es que como `ContestController::apiRequests` manda a llamar `UserController::getProfile` por cada usuario. La mayoría de la información del perfil está cacheada, _excepto_ el rankinfo, que es _bastante_ lenta de calcular. Voy a hacer un cambio para poder pedir el perfil sin esa información.

**Comment by alanboy** [comment]
aguanta, ya tengo el cambio local, solo no he hecho commit porque me faltan
las pruebas.

-Alan

2015-06-16 21:19 GMT-07:00 lhchavez <notifications@github.com>:

**Comment by alanboy** [comment]
Sera arreglado como parde de  #683. Gracias por la investigacion @lhchavez
