### ISSUE TITLE
[BUG][Concursos por subtareas] El scoreboard se cambia solo a modo de evaluacion parcial

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6882]
Pasos para reproducir:
1. Ir a https://omegaup.com/contest/subtareas3/edit?fromLogin= y hacer click en "Actualizar concurso" sin hacer ningun cambio.
2. Ir a https://omegaup.com/arena/subtareas3/#ranking y observar que el scoreboard esta evaluando correctamente por subtareas.
3. Ir a https://omegaup.com/arena/subtareas3 y hacer algun envio.
4. I ra https://omegaup.com/arena/subtareas3/#ranking y observar que el scoreboard esta evaluando con el metodo antiguo.
5. Si se repite el paso 1 el scoreboard vuelve a ser correcto.

**Comment by pabo99** [comment]
Esto también debería corregirse con los cambios en los PRs:

- https://github.com/omegaup/omegaup/pull/6898
- https://github.com/omegaup/quark/pull/121

ya que estos modifican la función en la que se procesan los rankings, calculando los nuevos puntajes con la función `getMaxPerGroupScore`. De cualquier forma habrá que revisar si después de que se haga merge, deja de presentarse esta falla
