### ISSUE TITLE
[FEATURE] Como un [profesor], quiero [ver el problema al cual se pide retroalimentacion] para [evaluarlo mas rapido]

### ISSUE THREAD

**Issue by 5an7y** [omegaup/omegaup#6886]
## Comportamiento Esperado

Cuando los alumnos solicitan retroalimentación a un problema este aparece en el centro de notificaciones. Al darle click en el centro de notificaciones debería llevarte a una interfaz donde puedas dar la retroalimentación y ver el problema que le corresponde a dicho envió.

## Comportamiento Actual

La interfaz de retroalimentación no provee el nombre, tag o preview del problema que se está pidiendo evaluar por lo que se tiene que intuir (teniendo contexto de todos los problemas en un curso) que problema se está intentando resolver.

![image](https://user-images.githubusercontent.com/34700620/211709824-fcfba4af-f09c-4f88-9a55-559f148f1a43.png)

## Posible Solución

Al inicio de la interfaz de retroalimentación poner el título del problema que se intenta resolver o el tag. Igual si este título pudiera tener el link a la descripción del problema y que se abriera en otra pestaña estaría genial.

## Contexto

Me encontré con este problema cuando mis alumnos me solicitaban retroalimentación, yo lo veía en mi centro de notificaciones, le daba click para ver el codigo y no sabia que estaba evaluando. Gracias a que yo cree los problemas me podía intuir que problema era el que estaban intentando resolver, pero no me parece un comportamiento adecuado. Se puede ver el tag del problema en la bitácora de ejecución pero me parece muy poco user friendly.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome Versión 108.0.5359.125 (Build oficial) (64 bits)
* Sistema Operativo y versión (escritorio o móbil): Windows 11

**Comment by kishtarn555** [comment]
https://github.com/omegaup/omegaup/issues/6875
