### ISSUE TITLE
CIIC: Siempre mostrar en el scoreboard los resultados del concursante independientemente del scoreboard show time

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#689]
@joemmanuel algún detalle de diseño visual?

**Comment by joemmanuel** [comment]
frankhg [05:39] 
Tengo una duda, los estudiantes no ven su nota. Debo cambiar algo en la admin

niquefa_diego [05:40] 
No ven su nota? Después de hacer un envío no les dicen que puntaje sacaron?

frankhg [05:40] 
En su pag no esta apareciendo por eso tengo la duda si yo debo cambiar algo que no hice al comenzar

joe [05:41] 
Los alumnos pueden ver sus propios puntajes al final de los enunciados.

Es intencional que los alumnos no vean el scoreboard general pero sí pueden ver los resultados de sus propios envíos.

joe [05:41]
En el scoreboard general todo se muestra como 0s, para ellos

frankhg [05:42] 
Me refiero a la tabla resumen que aparece a la izq. Aunque entiendo que el scoreboard general no lo vean

niquefa_diego [05:44] 
Pero siempre y cuando aparesca el puntaje de cada envío no hay problema.

joe [05:44] 
Por el momento esa tabla también va a estar en 0. En el futuro podemos hacer que muestre el puntaje del concursante en estos casos :simple_smile:

**Comment by elendil326** [comment]
El cambio es agregar solo los envíos del ususario actual desde java script.

**Comment by pabo99** [comment]
Esto aplica para el ranking

**Comment by lhchavez** [comment]
esto es similar al cambio que se hizo antes para el mini-ranking, pero este aplicaría para el scoreboard principal.

**Comment by elendil326** [comment]
[] Cambio en la UI
[] Prueba de Selenium donde el concurso siempre oculta
