### ISSUE TITLE
[FEATURE] Order students alphabetically in course progress table 

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6893]
Relevant code: https://github.com/omegaup/omegaup/blob/32377faf9b54e2bd1b5cb41871031fa276348eb8/frontend/server/src/DAO/Courses.php#L772

**Comment by Sarthakparmar-04** [comment]
Hi @heduenas @pabloaguilar, I would like to clarify the preferred method for organizing the list of student progress. Should it be arranged based on their percentage scores, with an example being [Sarthak: 45%, Heduenas: 30%, Pablo: 25%], or would it be more appropriate to sort them alphabetically with their corresponding percentage scores, such as [Heduenas: 30%, Pablo: 25%, Sarthak: 45%]?

**Comment by Sarthakparmar-04** [comment]
hey @pabo99 ,I am planning to add a two-filter button that allows users to choose between sorting student data by progress or alphabetical order. This feature can be a great way to give users control over how they want to organize the data according to their specific requirements. Sorting by progress can help users identify which students need extra support, and sorting alphabetically can make it easier to locate specific students in a large database. Overall, this two-filter button can be an efficient way to manage student data and improve the user experience.

**Comment by pabo99** [comment]
> hey @pabo99 @carlosabcs ,I am planning to add a two-filter button that allows users to choose between sorting student data by progress or alphabetical order. This feature can be a great way to give users control over how they want to organize the data according to their specific requirements. Sorting by progress can help users identify which students need extra support, and sorting alphabetically can make it easier to locate specific students in a large database. Overall, this two-filter button can be an efficient way to manage student data and improve the user experience.

Hi, @Sarthakparmar-04 

Great, it sounds like this issue could be assigned to you. Before we proceed, let me check with @heduenas to see if there are any additional steps you need to complete if you're interested in participating in the GSoC program.

**Comment by Sarthakparmar-04** [comment]
Hii @pabo99, Sure, please let me know if there are any additional steps that I need to complete to participate in the GSoC program. I am interested in participating and would like to ensure I have all the necessary information and requirements.

**Comment by heduenas** [comment]
Hi @Sarthakparmar-04

Thank you for your interest in collaborating with us as part of GSoC! We are asking candidates to first create an omegaup.com account, then sing up for this test https://omegaup.com/arena/gsoc2023#problems and solve at least 3 problems from there.

**Comment by Sarthakparmar-04** [comment]
@heduenas I don't know why this site is not working currently.

**Comment by heduenas** [comment]
@Sarthakparmar-04 sorry about that. The link should now work fine.

**Comment by Yougesh978** [comment]
Hello, can you assign this issue to me? or is it resolved already?  
 it may be beneficial to provide users with multiple sorting options, such as by progress, alphabetical order, or other relevant criteria. This would allow users to choose the sorting method that best suits their needs, and could improve the overall usability and efficiency of the course progress table,like the one used in the filtering of organizations in the GSoC site

**Comment by heduenas** [comment]
Hi @Yougesh978, have you had a chance to do the programming test at https://omegaup.com/arena/gsoc2023 ?
That test is a pre-requisite for getting an issue assigned.

**Comment by mayank-pathakk** [comment]
Hi @heduenas , I have completed the programming test as part of the phase one , and would like to work on this issue as my first issue . If it's still open can you assign it to me ? Thanks in advance

**Comment by heduenas** [comment]
You got it @mayank-pathakk!

**Comment by Yougesh978** [comment]
@heduenas hello sir, I completed the contest I was traveling so I couldn't reply but I have completed the test, please let me know the further steps

**Comment by Yougesh978** [comment]
![image](https://user-images.githubusercontent.com/109974757/224548625-bf56b56e-c103-4b3d-829f-3fba8df319c2.png)

**Comment by heduenas** [comment]
@Yougesh978,what's your omegaUp username?

**Comment by Yougesh978** [comment]
![image](https://user-images.githubusercontent.com/109974757/224567401-894a33b9-86b5-4015-99fd-bda362f7215d.png)

**Comment by heduenas** [comment]
Thank you for confirming your username @Yougesh978. Unfortunately this issue has been assigned to somebody else. Can you please look for another bug from our list https://github.com/omegaup/omegaup/labels/Good%20first%20issue ?

**Comment by Yougesh978** [comment]
@heduenas I'm sorry to hear that the issue has already been assigned to someone else. However, I understand that there are other good first issues available on the list. I will be happy to take a look and find another bug to work on.

**Comment by mayank-pathakk** [comment]
Hi @heduenas I have opened a PR #6933 that would solve this issue , please guide me if I am wrong and thanks in advance
