### ISSUE TITLE
[BUG] [Coder del mes] - La funcionalidad de Coder del mes no está mostrando a los mejores rankeados en la lista

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#6894]
## Comportamiento Esperado

El Coder del mes debería estar mostrando el listado de los mejores codificadores 
rankeados mes a mes.

## Comportamiento Actual

Al parecer, esto no está funcionando adecuadamente, de acuerdo al reporte de un
usuario de la plataforma.

## Posible solución

Por el momento, se puede considerar apagar el feature hasta que se revise por qué 
se están mostrando datos incorrectos, y una vez que quede resuelto volver a encenderlo

## Contexto

Por lo que se reportó en el Slack, el registro de la coder del mes apareció un día en 
la lista de los mejores rankeados, cosa que desapareció después y ya no fue posible 
encontrarla en ese listado.

**Comment by pabloaguilar** [comment]
Creo que el problema tiene que ver con que estamos mezclando usuarios con identidades.

`update_user_rank` hace una consulta agrupada por `identity_id`, pero cuando se guardan los valores en `User_Rank`  se hace por usuario.
Eso quiere decir que lo puntos que se asignan al usuario, no son los totales del usuario, sino los totales de **alguna de sus identidades**, en particular la última identidad en el orden que se procesó la consulta de puntajes.
Eso, a su vez, quiere decir que en una corrida "buena" de `update_ranks` se asigna al usuario los puntos de la identidad que tiene el máximo de puntos; y en una corrida "mala" se asigna al usuario los puntos de la identidad que tiene el mínimo de puntos. Como el orden de la consulta no es determinístico entre corrida y corrida (supongo que depende de un montón de ids que cambian cada que hay un envío, usuario o problema nuevo), el usuario puede fluctuar drásticamente entre corridas.

Claro está que esto afectaría solo a los usuarios que tengan múltiples identidades asociadas. Y no a la mayoría de los usuarios, por lo que me imagino que no se ha visto tan obvio el problema.

La solución, entonces es calcular los puntos por usuario, no por identidad. A fin de cuentas el rank que se asigna corresponde al usuario.
Hay que cambiar también la consulta de `update_problem_accepted_stats` para que cuente **usuarios** distintos y no **identidades** distintas.

Finalmente, creo que esta es la causa raíz de otro issue que nos reportaron en discord en diciembre en el que la escuela del mes fluctuaba mucho de un día para otro, dado que el puntaje de la escuela se calcula a partir del puntaje de los usuarios asignados a esa escuela.

**Comment by tvanessa** [comment]
> Creo que el problema tiene que ver con que estamos mezclando usuarios con identidades.

Desde que se diseñó el cronjob para coder del mes se contempló tomar en cuenta (**solo**) a las identidades que están asociadas a un usuario. No estoy segura de que sea tan directa esta solución.

**Comment by pabloaguilar** [comment]
Creo que necesitamos cambiar la cuenta total de soluciones a `Soluciones AC enviadas por usuarios o identidades libres`. Es decir, agregamos una solución al contador para un problema por:
* todos los envíos de todas las identidades de un mismo usuario
* todos los envíos de una misma identidad que no tenga usuario asociado

Creo que la consulta aquí abajo calcula eso correctamente.

```
WITH SolvedNonForfeitedProblems AS
            (
                SELECT
                    `i`.`user_id` AS user_id,
                    IF(ISNULL(`i`.`user_id`), i.identity_id, NULL) AS free_identity,  -- Ignoramos la identidad si esta asignada a un usuario
                    `s`.`problem_id` AS problem_id
                FROM
                    `Submissions` AS `s`
                INNER JOIN
                    `Identities` AS `i` ON  `i`.`identity_id` = `s`.`identity_id`
                INNER JOIN 
                    `Problems` AS `pp` ON pp.problem_id = s.problem_id
                WHERE TRUE
                    AND `s`.verdict = 'AC'
                    AND NOT EXISTS (
                        SELECT
                            `pf`.`problem_id`, `pf`.`user_id`
                        FROM
                            `Problems_Forfeited` AS `pf`
                        WHERE
                            `pf`.`problem_id` = `s`.`problem_id` AND
                            `pf`.`user_id` = `i`.`user_id`
                    )
                    AND NOT EXISTS (
                        SELECT
                            `a`.`acl_id`
                        FROM
                            `ACLs` AS `a`
                        WHERE
                            `a`.`acl_id` = `pp`.`acl_id` AND
                            `a`.`owner_id` = `i`.`user_id`
                    )
            )
        SELECT
            `p`.`problem_id`,
            p.alias,
            COUNT(DISTINCT sp.user_id) AS usuarios,
            COUNT(DISTINCT sp.free_identity) AS free_identity,  -- Ignora los NULL que se asignaron cuando si habia un usuario
            COUNT(DISTINCT sp.user_id) + COUNT(DISTINCT sp.free_identity) as accepted
        FROM
            `Problems` AS `p`
        LEFT JOIN
            SolvedNonForfeitedProblems AS `sp` ON p.problem_id = sp.problem_id
        GROUP BY
            p.problem_id
;
```

**Comment by pabloaguilar** [comment]
Un poco de sanity checking dice que sí calcula lo que queremos que calcule.

Revisé varios problemas con un usuario (y obviamente su identidad asociada), un usuario y una identidad libre, solo identidades libres.
