### ISSUE TITLE
[BUG] El scoreboard no se hace visible al finalizar cuando el porcentaje de tiempo para mostrarlo esta al 0%

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#6899]
## Comportamiento Esperado

Quiero poder tener un concurso donde no se pueda ver el scoreboard durante el concurso, pero se revele automaticamente al terminar. Para ello, configuro el concurso de la siguiente manera:
  - ¿Cuánto tiempo se mostrará el Scoreboard? (%)
    - 0
  - Scoreboard al finalizar el concurso
    - Si

## Comportamiento Actual

La opcion de `¿Cuánto tiempo se mostrará el Scoreboard? (%)` cuando esta en `0` hace que se ignore `Scoreboard al finalizar el concurso` cuando esta en `Si`, ya que si cambio el porcentaje a `1` si lo muestra.

## Posible Solución

Ignorar el porcentaje completamente cuando el concurso ya termino.

## Pasos para reproducir (para bugs)

1. Crea un concurso con la siguiente configuracion:
  - ¿Cuánto tiempo se mostrará el Scoreboard? (%)
    - 0
  - Scoreboard al finalizar el concurso
    - Si
2. Comprueba que el concurso no muestra el scoreboard mientras esta corriendo.
3. Comprueba que al terminarse el concurso este sigue sin mostrar el scoreboard.
4. Cambia `¿Cuánto tiempo se mostrará el Scoreboard? (%)` a cualquier valor mayor a `0` (incluso `1`) y comprueba que el scoreboard ahora si se ve.

## Contexto

Tengo un concurso de practica donde no queria nadie viera el scoreboard pero al finalizar si, y tuve que corregirlo manualmente para que se mostrara cuando termino. Esto fue reportado por los participantes.

## Tu ambiente

N/A

**Comment by wkoder** [comment]
Curiosamente, la grafica de progreso de arriba del scoreboard si tiene los puntajes, el detalle es solo con el scoreboard:

![image](https://user-images.githubusercontent.com/606680/217723363-b0e6d226-78f2-415e-ad04-d22803c91058.png)

**Comment by pabloaguilar** [comment]
Parece que se está comparando el porcentaje con 0, en lugar de con `null`:
https://github.com/omegaup/omegaup/blob/main/frontend/server/src/Scoreboard.php#L612

**Comment by pabloaguilar** [comment]
Y es que el dato está guardado como `int` no-nulo: https://github.com/omegaup/omegaup/blob/main/frontend/database/schema.sql#L187

**Comment by wkoder** [comment]
Parece que este fix introdujo una regresion y ahora siempre se muestra el scoreboard. La vez pasada no me di cuenta porque ya se habia terminado el ultimo concurso de este tipo que hacia, pero ahorita esta por terminarse uno similar con la siguiente config:
  - Concurso: https://omegaup.com/arena/velocidad-8-cas-2023
  - Config:
![image](https://user-images.githubusercontent.com/606680/230224238-6ea2fbfc-378b-4812-be33-fb1e35100890.png)

  - Scoreboard publico: https://omegaup.com/arena/velocidad-8-cas-2023/scoreboard/MHrq8V5YSfzNzRDqDmABC69X8pL3nB
  - Asi se ve el scoreboard pero no deberia mostrar los veredictos, pues el concurso esta configurado para mostrarlo el 0% del tiempo y no se ha terminado. Noten como esta en incognito y no estoy loggeado. Asi no se comportaba antes:
![image](https://user-images.githubusercontent.com/606680/230224576-84a26198-7cb2-4d72-8146-52180682f035.png)

**Comment by pabo99** [comment]
No he logrado reproducir el error. 

Esto es lo que he encontrado hasta el momento.

En el scoreboard público no se muestran los puntajes:
![image](https://github.com/omegaup/omegaup/assets/3230352/485ace51-d6ad-464b-9e4e-07960b334be6)

En el scoreboard de administradores si se muestran los puntajes:
![image](https://github.com/omegaup/omegaup/assets/3230352/d94a2965-777e-4d21-80fe-4046307c80d3)


Mismo caso sucede con el scoreboard en la arena como concursante, no se muestran los puntajes:
![image](https://github.com/omegaup/omegaup/assets/3230352/99b45914-be71-439f-b98b-454ff4b0fa04)

Y el scoreboard en la arena como administrador, si se muestran los puntajes:
![image](https://github.com/omegaup/omegaup/assets/3230352/042b7aba-a5b5-45bc-aa2b-e4b5320615a5)


¿Ese debería ser el comportamiento esperado? o ¿hay algo que se me esté pasando por alto a tomar en cuenta?

**Comment by wkoder** [comment]
Ese es el comportamiento esperado. Yo creo podemos cerrar el bug y se vuelvo a notar un comportamiento inesperado lo reabrimos para no perder contexto. Gracias!
