### ISSUE TITLE
[BUG] No funciona el botón "CONTACT US" y tampoco hay documentación de los términos y privacidad en https://www.omegaup.org/

### ISSUE THREAD

**Issue by SebasProgrammer** [omegaup/omegaup#6905]
## Comportamiento Esperado

*Describe lo que originalmente estabas intentando hacer y cómo esperabas que se comportara la plataforma.*
Quise contactame con ustedes a través de su página web y hice click en el botón "Contact us" y también quise ver los términos y provacidad. 

## Comportamiento Actual

*Describe lo que en realidad pasó en lugar de lo que se esperaba*

**Quise hacer click en el botón "Contact us", pero no hace nada, parece que no tiene funcionalidad alguna. Además, los términos y provacidad tampoco lleva a un link, donse se muestren la información del proveedor y términos y políticas aplicables.**

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug, o ideas
de cómo implementar la mejora*

En la etiqueta <a> del  "Contact us" del archivo html, se puede colocar un mensaje ya automatizado para hacer llegar su consulta o mensaje.

Ejemplo: <a class="Contactus__link" href="mailto:sebastian.arana2016@gmail.com?subject=Consulta" 

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
*El contexto que nos proporciones nos ayuda a encontrar la solución adecuada*

Mi objetivo principal es ayudar a la página a verse mejor y añadir funcionalidades futuras.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): edge
* Sistema Operativo y versión (escritorio o móvil): windows 11
* Link al sitio en el que este problema pasa: https://www.omegaup.org/
* Captura de pantalla:

**Comment by 456535688765** [comment]
I'll try to add this <a class="Contactus__link" href="mailto:sebastian.arana2016@gmail.com?subject=Consulta" in the Contact us button

**Comment by mayank-pathakk** [comment]
I would like to work on this issue , can it be assigned to me ?

**Comment by mayank-pathakk** [comment]
I would like to work on this issue , can it be assigned to me ?

**Comment by heduenas** [comment]
@mayank-pathakk you already have another bug assigned. You have to solve the other one first. Or you can also exchange the other one for this one.

**Comment by Yougesh978** [comment]
@heduenas hello can get this in English....i will try to work on it....as I mention I have completed the test ..could u assign this to me

**Comment by heduenas** [comment]
Actually, I just realized that this bugs pertains to the .org website, which is not managed through github. I'm sorry but this issue is not elegible for GSoC.

**Comment by tvanessa** [comment]
[nonprofit-web/#75](https://github.com/omegaup/nonprofit-web/issues/75)
