### ISSUE TITLE
El botón de Discord te lleva a discord pero no puedes entrar al grupo

### ISSUE THREAD

**Issue by SebasProgrammer** [omegaup/omegaup#6906]
## Expected Behavior

*Describe what you expected to happen*
Intenté entrar al grupo de discord
## Actual Behavior

*Describe what happened instead of what you expected*
No acepta la invitación y eso que había iniciado sesión
## Possible Solution
Permitir acceso al grupo de discord
*Not required, but if you can think of something, you can suggest a way to fix the bug.*

## Reproduction steps

*Provide a detailed list of steps of what you did to reproduce
this bug.  Include the code that reproduces it, if it is relevant.*

1. 
2. 
3. 
4. 

## Context

*How has this issue affected you? What were you trying to achieve?*

*Providing context helps us to find the right solution and priority.*

## Your environment

*Include the relevant details about the environment in which this bug was reproduced*

* Browser name (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.46
* Link to the site where this problem occurs: https://omegaup.com/course/home/?fromLogin=
* Console errors: []
* Screen capture:

**Comment by arishmaurya** [comment]
@SebasProgrammer  @pabo99   I am not able to find this issue on my side I am able to join discord from omega up website can you explain it bit more so that i can fix it

**Comment by arishmaurya** [comment]
@SebasProgrammer @pabo99 No puedo encontrar este problema por mi parte. Puedo unirme a Discord desde el sitio web de Omega Up. ¿Puede explicarlo un poco más para que pueda solucionarlo?

**Comment by pabo99** [comment]
It's possible that the issue has already been resolved by someone, thus it can be closed.

Thank you for review it!
