### ISSUE TITLE
[Badge Proposal] Nombre de la Insignia

### ISSUE THREAD

**Issue by 345-gip** [omegaup/omegaup#6907]
# Contenido

Este es el template para la propuesta de insignias en omegaUp, asegúrate de haber leído las consideraciones a tener en cuenta para proponer una insignia: [Guía para proponer insignias](https://blog.omegaup.com/guia-para-la-propuesta-de-insignias-en-omegaup/).

*Asegúrate de poner el nombre de la insignia que estás proponiendo, dentro del título de este Issue.*

## ¿Cuál es el nombre de la insignia que propones?
*Ejemplo: Usuario Histórico*

## ¿Qué debe haber realizado un usuario para recibir esta insignia?
*Ejemplo: El usuario realizó algún envío dentro del primer año desde el lanzamiento de omegaUp.*

## ¿Esta insignia tiene un ícono personalizado?
*De ser el caso, adjunta acá el archivo SVG con el ícono personalizado de la insignia.*

## (Opcional) Si tienes una idea de cómo implementar la consulta y prueba unitaria para esta insignia, puedes ingresarla acá:

*Ejemplo:
Para la consulta se debería obtener el primer inicio de sesión del registro de sesiones de usuarios y verificar si se encuentra dentro del primer año desde que omegaUp fue lanzado.
Para la prueba se deben crear dos usuarios, el primero debe iniciar sesión con fecha dentro del primer año de lanzamiento de omegaUp, el segundo debe tener un inicio de sesión con fecha actual, se espera que solo el primer usuario reciba la insignia.*

**Comment by heduenas** [comment]
este issue esta vacio
