### ISSUE TITLE
[FEATURE] Agregar la cadena "Mostrar a todos los concursantes en el scoreboard por defecto" en los archivos de localización

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#6909]
## Descripción

En el archivo `Publish.vue` aparece una cadena de texto:

```
"Mostrar a todos los concursantes en el scoreboard por defecto"
```
, la cual no debería agregarse de esa forma,  sino que debería localizarse 
en los archivos de traducción.

**Comment by akash-singh8** [comment]
Hi there, I noticed that there's a hardcoded text string in Publish.vue file that should be localized in the translation files. The text string in question is "Mostrar a todos los concursantes en el scoreboard por defecto".

@pabo99 Could you please let me know which translation file(s) I should modify to make this change?

Also, I would like to request to be assigned to this issue so that I can make the necessary changes to the codebase. Thank you!

**Comment by pabo99** [comment]
> Hi there, I noticed that there's a hardcoded text string in Publish.vue file that should be localized in the translation files. The text string in question is "Mostrar a todos los concursantes en el scoreboard por defecto".
> 
> @pabo99 Could you please let me know which translation file(s) I should modify to make this change?
> 
> Also, I would like to request to be assigned to this issue so that I can make the necessary changes to the codebase. Thank you!


We currently support three languages: English, Spanish, and Portuguese. If you wish to add translations for the following string, please modify the respective language file:

- English: "Show all contestants on the scoreboard by default." (File: [en.lang](https://github.com/omegaup/omegaup/blob/main/frontend/templates/en.lang))
- Spanish: "Mostrar a todos los concursantes en el scoreboard por defecto." (File: [es.lang](https://github.com/omegaup/omegaup/blob/main/frontend/templates/es.lang))
- Portuguese: "Mostrar todos os competidores no painel de avaliação." (File: [pt.lang](https://github.com/omegaup/omegaup/blob/main/frontend/templates/pt.lang))
After adding the translation string, run the following command outside your container:

```bash
./stuff/lint.sh
```

If you're not familiar with the development environment, you can refer to these articles:

How to Set Up Your Development Environment ([English](https://github.com/omegaup/omegaup/wiki/How-to-Set-Up-Your-Development-Environment-(English)))
How to Make a Pull Request ([English](https://github.com/omegaup/omegaup/wiki/How-to-Make-a-Pull-Request-(English)))
Finally, if you're interested in participating in the GSoC program, please complete a few steps before the issue can be assigned. For more information, please reach out to @heduenas."

**Comment by akash-singh8** [comment]
Sounds great.

**Comment by heduenas** [comment]
Hi @ShivamJhaa thank you for sending a PR for this issue. Have you had a chance to do the programming test at https://omegaup.com/arena/gsoc2023/#ranking ? If yes, what's your username?

**Comment by ShivamJhaa** [comment]
> Hi @ShivamJhaa thank you for sending a PR for this issue. Have you had a chance to do the programming test at https://omegaup.com/arena/gsoc2023/#ranking ? If yes, what's your username?

Yes, I have completed the test (solved 4/4). My username is sssvjha. I already have one PR merged as well.
https://github.com/omegaup/omegaup/pull/6919
