### ISSUE TITLE
[FEATURE] La solución de Google Signin que se utiliza en omegaUp quedará obsoleta en poco tiempo

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#6915]
Según lo descrito en la siguiente página:

https://developers.google.com/identity/sign-in/web/sign-in

El método de autenticación que se utiliza en omegaUp está cerca de quedar obsoleto, 
así que tenemos que migrar a la nueva versión antes del 31 de marzo del presente 
año (2023).

El link con la documentación de este nuevo método es el siguiente:

https://developers.google.com/identity/gsi/web/guides/overview

**Comment by anmode** [comment]
@pabo99 I think we should add sign-in with GitHub. As it is coding platform i think it will good to have GitHub login/signin
Just a suggestion!

**Comment by heduenas** [comment]
@anmode good suggestion can you plese file that as a separate issue so we can track it there?

**Comment by anmode** [comment]
Sure!!!

**Comment by heduenas** [comment]
These are the instructions for migration to the new thing: https://developers.google.com/identity/oauth2/web/guides/migration-to-gis

More specifically, I think we need to follow this example: https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#the_new_way_2

**Comment by heduenas** [comment]
@anmode offered to give this issue a try. Thank you Anmol and feel free to ping @pabo99 or me if you need help.

**Comment by anmode** [comment]
> @anmode offered to give this issue a try. Thank you Anmol and feel free to ping @pabo99 or me if you need help.

sure!!!
