### ISSUE TITLE
[FEATURE] Hacer obligatorio el argumento `duplicatedItemsInArray` en la clase `DuplicatedEntryInArrayException`

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#6924]
En el PR #6902 se sugiere agregar un nuevo argumento a la clase `DuplicatedEntryInArrayException`,
pero esta clase se manda llamar en distintos controladores. La idea es que dicho campo no sea opcional.

Para esto habrá que buscar todos esos lugares donde se llama para agregar los elementos duplicados.

**Comment by AlejandroGY** [comment]
Hola, me gustaría contribuir si es posible, pero no sé si alguien me podría asesorar ya que sería la primera vez que participo con ustedes. :)

**Comment by pabo99** [comment]
Hola @AlejandroGY, un gusto que estés interesado en contribuir con el equipo. Claro, cualquiera aquí te puiede ayudar a resolvre dudas.

 Sólo tengo un par de dudas:

- ¿Estás participando en el programa Google Summer of Code? 
- De ser así, ¿ya completaste los problemas del siguiente test: https://omegaup.com/arena/gsoc2023?, ¿nos puedes compartir tu username en omegaUp para validarlo?

Gracias de antemano.

**Comment by UlisesGallardo** [comment]
Hola, también estoy interesado en contribuir! mi username en el test de omegaUp es UlisesGallardo

**Comment by AlejandroGY** [comment]
Hola, no estoy participando en el Google Summer of Code, pero creo que aún podría participar, igual si ya tienen a alguien, puedo buscar otro issue :) 
Igual paso mi user: AlejandroGY

**Comment by Clanie1** [comment]
Buenos dias @heduenas, podria apoyar resolviendo este issue? soy parte de los aplicantes a Google Summer of Code

**Comment by pabo99** [comment]
Parece que @UlisesGallardo ya envió el PR #6969  para este issue

**Comment by Clanie1** [comment]
Entiendo, buscare otro issue para comenzar. Gracias @pabo99!
