### ISSUE TITLE
[FEATURE]  Remove Amazon and F5 from our list of sponsors

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6928]
Sponsors are shown here:
![Screenshot 2023-03-09 at 2 48 30 PM](https://user-images.githubusercontent.com/597815/224177763-51cb1da7-10de-4ddc-b9c2-e4f2616b8571.png)

And here:
<img width="517" alt="Screenshot 2023-03-09 at 2 49 55 PM" src="https://user-images.githubusercontent.com/597815/224177964-c43aa540-43cc-4478-9839-c860c0f28fc2.png">

**Comment by heduenas** [comment]
cc @joemmanuel

**Comment by IngridRB** [comment]
Hola, me pueden asignarme este issue @heduenas ?

**Comment by heduenas** [comment]
Listo, gracias Ingrid!

**Comment by Yougesh978** [comment]
Hello, can you assign this issue to me or is it resolved ?

**Comment by heduenas** [comment]
@Yougesh978 this issue is already assigned to somebody else.

**Comment by er-pratham** [comment]
Please assign me this issue
