### ISSUE TITLE
[ERROR] El menú desplegable del usuario del menú desplegable del menú de hamburguesas no muestra todos los elementos

### ISSUE THREAD

**Issue by YannyTwoo** [omegaup/omegaup#6929]
## Comportamiento esperado

*Describe lo que intentabas hacer originalmente y cómo esperabas que se comportara la plataforma.*

El menú desplegable del menú de hamburguesas tiene una opción de <nombre de usuario> que tiene un menú desplegable para los usuarios registrados. Todo su contenido debe ser visible para el cliente.

## Comportamiento actual

*Describe lo que realmente sucedió en lugar de lo que se esperaba*

En los tamaños de pantalla inferiores a los de un escritorio (en arranque, ancho de 992 px), aparece el menú de hamburguesas. Cuando hacemos clic en la opción "<nombre de usuario>" que tiene un menú desplegable, los elementos en la parte inferior son inaccesibles debido a la falta de desplazamiento, posicionamiento y tamaño del nuevo menú desplegable.

https://user-images.githubusercontent.com/79789927/224374694-97a7def0-bca8-4920-936a-e6cb3f93cf35.mp4

## Posible solución

*No es obligatorio, pero puedes sugerir una forma de solucionar el error, o ideas
cómo implementar la mejora*

Se puede hacer reposicionando, agregando y desbordando la propiedad o cambiando el tamaño o una combinación de los 3.

## Pasos para reproducir (para errores)

*Proporcione un enlace a un ejemplo o una lista de pasos detallados sobre cómo reproducir
este bicho. Incluir el código que lo reproduce, si procede*

1. Abra el sitio web de omegaup o su instancia local (sucursal principal)
2. Iniciar sesión
3. Ahora reduzca el tamaño de la pantalla al móvil (o por debajo de 992 px de ancho)
4. Haga clic en la hamburguesa, luego haga clic en <NOMBRE DE USUARIO> y observe el menú desplegable que aparece. No puedes acceder a todos sus elementos.

## Contexto

*¿Cómo te ha afectado este problema? ¿Cuál es el objetivo que originalmente quería lograr? El contexto que proporciona nos ayuda a encontrar la solución adecuada*

Encontré esto mientras trabajaba en otro problema. Extremadamente inconveniente para los usuarios móviles

## Tu entorno

*Incluye detalles relevantes sobre el entorno en el que te reproduciste
este error*

- Nombre del navegador (por ejemplo, Chrome 39, node.js 5.4): Chrome v110.0
- Sistema operativo y versión (de escritorio o móvil): macOs Ventura 13.0.1
- Enlace al sitio donde ocurre este problema: [https://omegaup.com/](https://omegaup.com/)
- Captura de pantalla: video added

**Comment by heduenas** [comment]
Yes you can! Thanks for filing this bug.
