### ISSUE TITLE
[FEATURE] Fix string in rank table

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#6939]
In https://omegaup.com/rank/authors we use `Authors` and `Contributor`.
Update the strings `Authors` for `Contributors`
![Screen Shot 2023-03-16 at 11 39 29 AM](https://user-images.githubusercontent.com/13296248/225707533-8b461e84-32e0-45ee-888d-fae94e7abef8.png)

**Comment by satishsahu25** [comment]
is this issue open?

**Comment by Krupalll20** [comment]
Hey @tvanessa @devbrianmedina @heduenas is this issue is still open? If nobody is working then can you assign it to me?

**Comment by satishsahu25** [comment]
I am working on it and i got the idea too, please assign it to me.

**Comment by heduenas** [comment]
@satishsahu25 @Krupalll20 have either one of you solved at least 3 problems from the programming test at https://omegaup.com/arena/gsoc2023 ? That's a prerequisite to getting an issue assigned.

**Comment by sohankamble** [comment]
Hello @tvanessa, Myself Sohan Kamble and my Omegaup username is KSohan. I have completed the first task i.e. to solve the three coding problems as mention in the documentation and I want to fix this issue. Can you assign this issue to me?

**Comment by devbrianmedina** [comment]
@sohankamble @satishsahu25 @Krupalll20 @heduenas I have it assigned, and it's already solved. I'm just waiting for it to be approved.
