### ISSUE TITLE
[BUG] when clicking on the notifications menu on mobile devices the other menus are not visible

### ISSUE THREAD

**Issue by MiguelRom3ro** [omegaup/omegaup#6942]
## Comportamiento Esperado

When clicking on the notifications menu the other menus should be visible

## Comportamiento Actual

The menus disappear when the notifications menu is clicked

## Posible Solución

Define the maximum size of the notification container when viewed on mobile

## Pasos para reproducir (para bugs)

1. Log in from a mobile device at omegaup.com
2. Select the option to display the menu that is in the upper right part
3. Select notification menu

## Contexto

People can get confused by not seeing the menus and have to refresh the page, the experience when using the notification menu is not to their liking

## Tu ambiente

* Nombre del navegador : Google Chrome
* Sistema Operativo y versión (escritorio o móvil): Windows 11, Android
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Captura de pantalla:
![image](https://user-images.githubusercontent.com/128170939/226073375-57073712-0dbe-4c5d-af96-97f42682e898.png)

![WhatsApp Image 2023-03-17 at 6 31 36 PM](https://user-images.githubusercontent.com/128170939/226073550-71f1340e-45b6-49b0-8b49-2e218053134e.jpeg)

**Comment by MiguelRom3ro** [comment]
I finished the necessary problems for the first phase my username in omegaup is miguelRomero, I would like to work on this

**Comment by heduenas** [comment]
Assigned to @MiguelRom3ro! Thank you Miguel for confirming your omegaup username.
