### ISSUE TITLE
[BUG] Disabling test_client_contest_with_duplicated_codes to prevent failures in Python tests.

### ISSUE THREAD

**Issue by devbrianmedina** [omegaup/omegaup#6943]
## Comportamiento Esperado
I made a pull request and expected all tests to pass.

## Comportamiento Actual
I made a pull request and the Python test test_client_contest_with_duplicated_codes is failing.
![image](https://user-images.githubusercontent.com/38367679/226157230-2164e5e9-15d4-4d6f-a9fd-ade5f4a79383.png)

## Posible Solución
Disable the test_client_contest_with_duplicated_codes test.

## Pasos para reproducir (para bugs)
The tests have failed in the last pull requests. (Examples #6940 #6941)

## Contexto
The problem is that it prevents the tests from being successfully fulfilled.

## Tu ambiente
* Nombre del navegador Google Chrome
* Sistema Operativo y versión Windows 11

**Comment by devbrianmedina** [comment]
I would like to make changes regarding this issue, to temporarily disable the Python test 'test_client_contest_with_duplicated_codes'. (Username on omegaup: DevBrianMedina)

**Comment by anmode** [comment]
@devbrianmedina we have an ongoing issue it would be great if we can continue to report all flaky tests there and not create another issue.
here's - #6927
