### ISSUE TITLE
[FEATURE] Add button for users to delete their account

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#6945]
The API endpoint to delete an account has been implemented in https://github.com/omegaup/omegaup/pull/6646.

We need to add a button in the user profile, and we need to ask for their confirmation before we perform the account deletion.

**Comment by pabo99** [comment]
We could reuse the styles of the page "Problem > Edit > Delete":

![image](https://user-images.githubusercontent.com/3230352/226268092-4cc73dff-bae2-4c68-afda-1b0469935d49.png)

**Comment by anmode** [comment]
Just tried! If it looks ok. @pabo99 @heduenas
