### ISSUE TITLE
[BUG] Correo de confirmación al suscribirse a recibir noticias y novedades de OmegaUp

### ISSUE THREAD

**Issue by SebasProgrammer** [omegaup/omegaup#6948]
## Comportamiento Esperado

Al momento de suscribirse  a recibir noticias de OmegaUp quiero recibir un correo de confirmación

## Comportamiento Actual

No recibe ningún correo de confirmación

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Edge
* Sistema Operativo y versión (escritorio o móvil): Windows 11
* Link al sitio en el que este problema pasa:  https://www.omegaup.org/
* Captura de pantalla: No es necesaria

**Comment by tvanessa** [comment]
Este va acá: https://github.com/omegaup/nonprofit-web/issues
