### ISSUE TITLE
[BUG] Tables Displaying Completed Exercises Exceed Screen Size.

### ISSUE THREAD

**Issue by devbrianmedina** [omegaup/omegaup#6950]
## Comportamiento Esperado
I was trying to view the tables displaying the exercises in the "My Completed Problems" section of the platform, and I expected them to fit properly within the screen.

## Comportamiento Actual
However, the tables are currently exceeding the screen size and causing bugs.

## Posible Solución
A possible solution could be to adjust the table size or layout so that it fits properly on the screen. Another solution could be to enable horizontal scrolling for the tables so that users can scroll through the content.

## Pasos para reproducir (para bugs)
To reproduce the bug, please follow these steps:
1. Log in to the platform and navigate to your profile in the 'Problems' section.
2. View the tables displaying the exercises.
3. Notice how the tables exceed the screen size and cause bugs.

## Contexto
This problem has affected my ability to view and keep track of the exercises I have completed on the platform. I was originally hoping to use this feature to keep track of my progress and review past exercises.

## Tu ambiente
* Browser name: Firefox
* Operating system and version: Ubuntu
* Link to the site where this issue occurs: https://omegaup.com/profile/#problems
* Screenshot:
<img src="https://user-images.githubusercontent.com/38367679/226774004-a07ce971-352b-4fd6-80a3-41f6df35fce6.png" alt="example" width="350">

**Comment by devbrianmedina** [comment]
@heduenas I would like to work on this task. I have completed the 4 exercises of the GSoC test. My username on omegaup is DevBrianMedina.

**Comment by heduenas** [comment]
Assigned to you @devbrianmedina
