### ISSUE TITLE
[BUG]  The table in the contributors section overflows when viewing it on mobile

### ISSUE THREAD

**Issue by MiguelRom3ro** [omegaup/omegaup#6957]
## Comportamiento Esperado

When viewing the table of contributors on mobile devices it must be responsive

## Comportamiento Actual

When viewing the table of contributors on mobile devices it must be responsive

## Posible Solución

Make the table responsive when viewing on mobile

## Pasos para reproducir (para bugs)

1.  Enter omegaup.com on mobile devices
2. Display the main menu
3. Select the ranking option
4. Select the contributor ranking option

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Google chrome
* Sistema Operativo y versión (escritorio o móvil): Windows and Android
* Link al sitio en el que este problema pasa: https://omegaup.com/rank/authors/
* Captura de pantalla:

<img src="https://user-images.githubusercontent.com/128170939/227614836-c2e191b8-11b0-4b12-a666-977e1e289097.png" 
    alt="example" width="400px">

**Comment by MiguelRom3ro** [comment]
I finished the necessary problems for the first phase of the GSoC test , my username in omegaup is miguelRomero, I would like to work on this

**Comment by pabo99** [comment]
Done, now the issue has been assigned to you. 

Out of curiosity, did you close another assigned issue? and if so, what was the reason?

**Comment by MiguelRom3ro** [comment]
@pabo99 Thank you
I closed it because I thought that it had not been assigned to me yet and that it was not a good idea,
although I think I have the solution.
