### ISSUE TITLE
[BUG] User ranking table overflows causing menu bar to scroll left.

### ISSUE THREAD

**Issue by devbrianmedina** [omegaup/omegaup#6960]
## Comportamiento Esperado
I wanted to see the user ranking on the platform but the table overflows.

## Comportamiento Actual
In the user ranking, the table overflows, causing the top menu bar to shift to the left along with the size of the table.

## Posible Solución
- Hide the Score and Solved problems columns.
- Make it fit within the container and slide to the left.

## Pasos para reproducir (para bugs)
To reproduce the bug, just go to the link https://omegaup.com/rank/

## Tu ambiente
* Nombre del navegador Firefox
* Sistema Operativo y versión (escritorio o móvil): Desktop
* Link al sitio en el que este problema pasa: https://omegaup.com/rank/
* Captura de pantalla:
<img src="https://user-images.githubusercontent.com/38367679/227689219-a436e39e-ac40-4f95-99bb-f89726a36df8.png" width="300px"/>

**Comment by devbrianmedina** [comment]
@heduenas @pabo99 Could you assign me to work on this issue and which of the two solutions I proposed would be the best?

**Comment by YannyTwoo** [comment]
Issue [#6957](https://github.com/omegaup/omegaup/issues/6957) is similar, can check out the PR for reference if not already solved

**Comment by pabo99** [comment]
Done, now this issue is assigned to you, @devbrianmedina
