### ISSUE TITLE
[BUG] Concursos Tab Overflows

### ISSUE THREAD

**Issue by galovdev** [omegaup/omegaup#6966]
## Comportamiento Esperado

*I want the information and buttons to be placed in a clear and orderly way as they are seen in the desktop version, so that they do not cover the others.*

## Comportamiento Actual

*The elements are not well ordered, they are not easy to read and sometimes they cover each other.*

## Solucion

*Arrange containers and elements so that they look good on small screens.*

## Pasos para reproducir (para bugs)

*Enter this link on a cell phone or using developer mode to display the web as if it were a cell phone: https://omegaup.com/arena/*

## Contexto

*Cómo te ha afectado este problema? Cuál es el objetivo que originalmente querías cumplir?*
*El contexto que nos proporciones nos ayuda a encontrar la solución adecuada*

## Tu ambiente

* Chrome | 111.0.5563.146
* macOS Big Sur | 11.7.5 using chrome developer mode
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/
* Captura de pantalla:

<img width="389" alt="Captura de pantalla 2023-03-28 a la(s) 12 05 49" src="https://user-images.githubusercontent.com/107520089/228333057-83c836fa-dcd2-4a40-90b9-710f8f7a0403.png">

**Comment by pabo99** [comment]
@galovdev, ¿nos puedes apoyar con tu username en omegaUp? para poder validar que ya resolviste los problemas y así poder aqsignarte el issue.

Gracias!

**Comment by H454NSec** [comment]
Hey @pabo99 Could you assign this issue to me I would like to contribute to this issue.

I'm interested in contributing to the project and I've already completed Phase One of the GSoC 2023 omegaUp Test. I would like to move onto Phase Two as quickly as possible, so could you please assign me this issue ?

**Comment by pabo99** [comment]
Dupe #6571 

Can we move on to the other issue to close this one?

**Comment by galovdev** [comment]
galovdevEl 28 mar 2023, a la(s) 12:44, Juan Pablo Gómez Aguilar ***@***.***> escribió:﻿
@galovdev, ¿nos puedes apoyar con tu username en omegaUp? para poder validar que ya resolviste los problemas y así poder aqsignarte el issue.
Gracias!

**Comment by galovdev** [comment]
> @galovdev, ¿nos puedes apoyar con tu username en omegaUp? para poder validar que ya resolviste los problemas y así poder aqsignarte el issue.
> 
> Gracias!

@galovdev gracias
