### ISSUE TITLE
[BUG] Text Overflows Container School Ranks

### ISSUE THREAD

**Issue by galovdev** [omegaup/omegaup#6967]
## Comportamiento Esperado

*I wanted to see the ranking of the schools, I can see it but it is presented in the wrong way, the text is out of the container.*

## Comportamiento Actual

*The text overflows the container*

## Possible Solución

*Set the space in the container so that all the elements fit, it could be 75% schools and 25% points.*

## Pasos para reproducir (para bugs)

* Enter this link on a cell phone or in developer mode with a small screen view: https://omegaup.com/rank/schools/ *

## Contexto

*I wanted to see the ranking in an orderly manner without seeing the points cut off or having to scroll to see them going out of their container*

## Tu ambiente

* Chrome | 111.0.5563.146
* macOS Big Sur | 11.7.5
* Link al sitio en el que este problema pasa: https://omegaup.com/rank/schools/
* Captura de pantalla:
<img width="390" alt="Captura de pantalla 2023-03-28 a la(s) 13 19 09" src="https://user-images.githubusercontent.com/107520089/228347689-fc74065d-58cb-40d2-a84f-b715fedf63e6.png">

**Comment by pabo99** [comment]
@H454NSec are you interested in solving this issue?

**Comment by H454NSec** [comment]
@pabo99 Yes I am interested.

**Comment by pabo99** [comment]
Done!

**Comment by H454NSec** [comment]
@pabo99 I was excited. Sorry, by mistake, I clicked on the Unassigned Me button!
