### ISSUE TITLE
[BUG] Coder del Mes Text Overflows Container

### ISSUE THREAD

**Issue by galovdev** [omegaup/omegaup#6968]
## Comportamiento Esperado

*I wanted to see the "coder del mes", I can see it but it is presented in the wrong way, the points are out of the container.*

## Comportamiento Actual

*The points overflow the container and look bad*

## Possible Solución

*Set the space in the container so that all the elements fit, it could be 75% coder and 25% fecha, also adjust the width of the container as has more padding than the other charts, for example, "Escuelas con mas puntaje" cover almost 90% of the width of the screen and Coder del mes cover like 60% so it looks non-symetrical

## Pasos para reproducir (para bugs)

* Enter this link on a cell phone or in developer mode with a small screen view: https://omegaup.com/coderofthemonth/*

## Contexto

*I wanted to see the ranking in an orderly manner without seeing the date cut off or having to scroll to see them going out of their container*

## Tu ambiente

* Chrome | 111.0.5563.146
* macOS Big Sur | 11.7.5
* Link al sitio en el que este problema pasa: https://omegaup.com/rank/schools/
* Captura de pantalla:

<img width="387" alt="Captura de pantalla 2023-03-28 a la(s) 13 24 31" src="https://user-images.githubusercontent.com/107520089/228349399-76a9727f-9f03-4b96-9eb3-cea0389db8b4.png">

**Comment by MiguelRom3ro** [comment]
@pabo99 If possible I would like to work on this, I have completed phase 1, my username at omegaup.com is miguelRomero.

**Comment by pabo99** [comment]
Done!
