### ISSUE TITLE
analizar https://influxdb.com/ para telemetria

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#697]
> An open-source distributed time series database with no external dependencies.
> InfluxDB is the new home for all of your metrics, events, and analytics.

**Comment by lhchavez** [comment]
Estuve checando varios y sí es buena idea tener métricas nosotros bicós
newrelic cobra. Lo que nos faltaba era tener un host dedicado para que
estuviera corriendo lo de telemetría y ahora tenemos deploy.omegaup.com ;)

**Comment by elendil326** [comment]
@lhchavez mencionaste que ya había telemetría. Esto aún se necesita?

**Comment by lhchavez** [comment]
No, usamos Prometheus / NewRelic para eso.
