### ISSUE TITLE
[FEATURE] Quitar todas las referencias a la ArenaV1

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#6975]
Ahora que ya se está trabajando en las vistas móviles de la Arena, y tomando en cuenta que la Arena Versión 1 tiene ya un tiempo considerable que ha permanecido oculta sin necesidad de regresar a usarla, sería excelente idea elimnar todo el rastro de ella.

Esto incluye lo siguiente:

- Eliminar el registro del archivo `nginx.rewrites` llamado: `arenav1`.
- Eliminar el archivo `/arena/index.php` que ya no se utiliará.
- Elimnar la función del controlador `Contest` llamada: `getContestListDetailsForTypeScript`.
- Eliminar el registro del archivo `webpack.config-frontend.js` llamado: `arena_contest_list`.
- Elimnar el archivo `/frontend/www/js/omegaup/arena/contest_list.ts` que ya no se utilizará.
- Eliminar el componente `/components/arena/ContestList.vue` que ya no se utilizará.
- Eliminar todas las pruebas que manden llamar algo de lo que se eliminó anteriormente.

Si es posible (aunque sea en un PR por separado) renombrar todas las funciones/archivos para que no inlcuyan el sufijo `v2` debido a que ahora sólo existirá una sola versión

**Comment by divyanshkul** [comment]
I want to work on this issue. Will send across a PR soon.
Quiero trabajar en este asunto. Enviaré un PR pronto. (Don't know spanish, used a translator)

**Comment by pabo99** [comment]
No problem with the language (we try to write in english for better comunication). Sure, can you provide us your username in omegaUp please? In order to validate you have solved the problems in the test

**Comment by chakra2017** [comment]
Hi ,I want to work on this issue.

**Comment by heduenas** [comment]
> I want to work on this issue. Will send across a PR soon. Quiero trabajar en este asunto. Enviaré un PR pronto. (Don't know spanish, used a translator)

@divyanshkul have you had a chance to complete the first phase of the application process? https://omegaup.com/arena/gsoc2023-2 what's your omegaup username

**Comment by subhajit20** [comment]
@pabo99  does this issue still exist?

**Comment by subhajit20** [comment]
@pabo99  hey! I have made all the required changes but could not pushed to my external branch 
This is error is showing given below
```
remote: Permission to omegaup/omegaup.git denied to subhajit20.
fatal: unable to access 'https://github.com/omegaup/omegaup.git/': The requested URL returned error: 403
```

**Comment by heduenas** [comment]
@subhajit20 you have to make a branch of the repository and push there. Please check out this instructions https://github.com/omegaup/omegaup/wiki/How-to-Make-a-Pull-Request-(English)

**Comment by subhajit20** [comment]
@heduenas Hey! Thanks for your concern, I am able to push my changes and made a pr request given above, you can check that.

**Comment by subhajit20** [comment]
> @subhajit20 you have to make a branch of the repository and push there. Please check out this instructions https://github.com/omegaup/omegaup/wiki/How-to-Make-a-Pull-Request-(English)

and Can you review that once?

**Comment by Alan502** [comment]
Este issue se puede cerrar? Me parece que ya se arreglo

**Comment by pabo99** [comment]
Cierto, esto ya se arregló!
