### ISSUE TITLE
[BUG] `team_group_alias` en la vista de editar concursos es un objeto y no un string

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#6978]
## Comportamiento Esperado

Al editar concursos que habilitan la participación por equipos, debería funcionar el alias de grupos adecuadamente.

## Comportamiento Actual

Ahorita se pueden crear concursos con alias por equipo pero no se pueden editar porque el campo `team_group_alias` que se extrae de la forma se extrae en forma de objeto y no de string:

![image](https://user-images.githubusercontent.com/189223/229266986-12e1ea19-1cf2-49fe-8d15-953f77405c73.png)

Esto, a su vez, hace que falle la edición del concurso.

## Posible Solución

Corregir la forma en que se extrae el campo en Vue.

## Pasos para reproducir

1. Crear un grupo para concursos por equipos
2. Crear un concuros que utiliza ese grupo
3. Inmediatamente después de crear el concurso, al ser redirigido a la forma de editar el concurso, presionar el botón de "Actualizar concurso" sin haber cambiado nada
4. Observar mensaje de error que se debe a que el campo se envía en formato incorrecto

**Comment by H454NSec** [comment]
@pabo99 
I would like to contribute to resolving this issue. Can you assign me?

**Comment by pabo99** [comment]
> @pabo99 I would like to contribute to resolving this issue. Can you assign me?

Sure!

**Comment by tvanessa** [comment]
Esta relacionado con #7178?

**Comment by pabo99** [comment]
> Esta relacionado con #7178?

Parece que si corresponden al mismo error. Lo corrijo
