### ISSUE TITLE
Crear un gestor de casos en omegaup separado de la redaccion

### ISSUE THREAD

**Issue by luisrodolfo** [omegaup/omegaup#700]
Tuvimos el caso de que un problemsetter se confundió de versión de la redacción de un problema, y la cambio por una versión antigua al actualizar los casos.

Para prevenir confusiones con la redacción correcta de los problemas, lo que se me ocurre es que de forma similar a la pestaña de edición de la descripción de los problemas, agreguen una pestaña para gestionar los casos y que permita subirlos por separado de la descripción del problema, así como descargarlos en caso de ser necesario (LHC propone descargar el zip https://github.com/omegaup/omegaup/issues/577). Esto ayudaría a hacer omegaup mas amigable para los problemsetters.

¡Saludos!

- Luis Rodolfo

**Comment by lhchavez** [comment]
Cerrando en favor de ya sea #577 o #612. Si es absolutamente necesario tener un modo en el que se deba ignorar las redacciones de un .zip, estoy en contra de agregar una sección explícita y distinta para ello porque de cualquier manera se podrían equivocar los problemsetters. Eventualmente, #701 es la solución definitiva para esto porque así es posible darle rollback a una versión de los casos.

**Comment by joemmanuel** [comment]
Desde mi punto de vista, ignorar la redacción tiene mucho mejor usabilidad
que #577 (2 pasos) o #612 (+2 pasos).
Sugiero reconsiderar @lhchavez.

On Tue, Aug 4, 2015 at 6:20 AM, lhchavez <notifications@github.com> wrote:

> Closed #700 <https://github.com/omegaup/omegaup/issues/700>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/700#event-373037734>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by luisrodolfo** [comment]
Considero que #700 seria una solución rápida al problema que planteo, tomando en cuenta de que sea en una sección a parte y considerando #577. Si en algún momento pueden implementar #701 estaría perfecto, pero es algo que llevara mucho mas tiempo.

**Comment by lhchavez** [comment]
@joe La cosa es que también alguna vez tuvimos problemas porque dos personas cambiaron los casos de un problema y se sobreescribieron los casos y fue un relajo regresarlos a un estado decente. cualquiera de las dos soluciones que describo al menos tiene la ventaja de que es relativamente atómica. pero bueno, el escenario de dos personas concurrentes haciendo ediciones apanicadas a los casos de un problema no es tan común así que vota en #701 que subir los casos por separado es un net-positive.

@luisrodolfo implementar esto no es tan rápido :P e insisto, tener una sección aparte es mala idea porque estás resolviendo el problema a medias e igual se va a equivocar la gente.
