### ISSUE TITLE
[BUG] Error en manejo de errores cuando agregas múltiples usuarios a un concurso

### ISSUE THREAD

**Issue by LaloRivero** [omegaup/omegaup#7005]
## Comportamiento Esperado

Funcionalidad de agregar múltiples usuarios a un concurso, agregando los nombres de usuarios separados por un espacio. No muestra el error y lo muestra un label de que la operación salió con éxito.

## Comportamiento Actual

Tratando de agregar múltiples usuarios en un concurso, das clic en agregar usuarios y pareciera que todo funciona correctamente. No aparecen errores al agregar múltiples usuarios, pero no se agrega ninguno de los participantes. Incluso funciona si tratas de agregar usuarios que no existen en la plataforma.

La petición a POST https://omegaup.com/api/contest/addUser/ devuelve un error 404.

Respuesta:
```
{
  "status": "error",
  "error": "Usuario o mail no encontrado",
  "errorname": "userOrMailNotFound",
  "errorcode": 404,
  "header": "HTTP/1.1 404 NOT FOUND",
  "userEmail": "carlosivan2410\nArturoBL\nsebastian09\njairors\namberab\nedwinbt\nlisapm\nkiaratr\ndaniacl\ndannavm\naxelhernandez\nsantiagodr\nmanuel2410\nnaimvq\nabdeldominguez\nerickmb\nhannaya\nalbertopb\nlucianopc\nEvan13\narturobl\nandrespl\nmarina2187\npatricio2187\nevoleth2187\nlupita2187\nkenia2187\nmateohernandez2187\nedgar2195\noscar2195\njesus2195\nmanuel2187\nyael2195\ndiego2195\nsocorro2195\nroberto2195\nsantiago2195",
  "_id": "6453cfefd8c59817317329"
}
```

## Pasos para reproducir (para bugs)

Crea un concurso y trata de agregar múltiples usuarios

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador Chrome
* Sistema Operativo: MacOS
* Captura de pantalla:

![imagen](https://user-images.githubusercontent.com/39440542/236258241-d7e29af7-5720-43cf-a752-7da514dd9f1d.png)
![imagen](https://user-images.githubusercontent.com/39440542/236258402-440548ea-2a51-46db-8a12-d579682f5dcf.png)

**Comment by imjpfeliciano** [comment]
Hola @tvanessa si no está asignado aún, puedo tomar este ticket?

**Comment by tvanessa** [comment]
> Hola @tvanessa si no está asignado aún, puedo tomar este ticket?

Claro! Si en tu propuesta se incluyen los nombres de usuario que no se pudieron agregar, sugiero limitar el número de elementos y poner un botón de "Ver todos"
Gracias.

**Comment by imjpfeliciano** [comment]
Si perfecto, pensaba hacer algo como un parse por espacio en lugar de saltos de linea y usar de este tipo de componentes:
![image](https://github.com/omegaup/omegaup/assets/6007230/5f0e6297-a043-465e-b057-a80741c5029c)

Después hacer la validación de los usuarios y marcar con algun color distintos los usuarios que no existen, y dar opcion de eliminarlos, que opinas?

**Comment by imjpfeliciano** [comment]
Igual @tvanessa si pudieses darme un poco de contexto acerca de como es que se usa ese componente, y porque aceptamos unicamente coma y saltos de linea, para ver que no vaya a romper la funcionalidad original 🙏🏼

**Comment by heduenas** [comment]
Hola @imjpfeliciano , probablemente @pabo99 tenga detalles del contexto del que preguntas. Perdon por la tardanza en responder aquí.

**Comment by pabo99** [comment]
> Hola @imjpfeliciano , probablemente @pabo99 tenga detalles del contexto del que preguntas. Perdon por la tardanza en responder aquí.

Hola @imjpfeliciano, el componente que mencionas está excelente. No creo que haya inconveniente en usarlo. 

De cualquier forma, te pongo en contexto del porqué decidimos dejar las dos cajas de texto para agregar usuarios.

Originalmente sólo usabamos el typeahead de bootstrar, con ese podíamos elegir sólo entre usuarios/correos que existen en la DB. 

En algún punto nos solicitaron que se pudieran agregar varios usuarios en una sola acción, esto debido a que los organizadores ya tenían armada su lista de participantes en archivos .csv o .xls. Entonces, la manera más sencillla de implementar dicha funcionalidad era copiar y pegar. Si los tienen en renglones, se pegan separados con un salto de linea. Si copian el .csv se pegan en un sólo renglón separados por coma (aunque el csv se puede configurar para que delimites con otros caracteres también). Por eso lo tenemos de esa forma.

Después implementamos el typeahead de [Voerro](https://github.com/voerro/vue-tagsinput)  el cual nos permite seleccionar multiples elementos:

![AddMultipleParticipants](https://github.com/omegaup/omegaup/assets/3230352/41848d30-edea-4f4d-baf8-62a3024fcb11)


 Pero al no poder copiar y pegar desde excel en este nuevo componente, decidimos mantener la caja de texto multiarea.

En caso de que implementes el componente que sugieres, primero revisa si es posible copiar y pegar infromación tal como te mencioné. Y para que podamos solucionar por completo el issue reportado aquí, una vez que se pega la información, sería importante mostrar en un listado:
- En color verde los usuarios/correos que si existan
- En color rojo los que no

De esta forma, el organizador del concurso sabrá cuáles se tienen que corregir antes de intentar guardarlos.


Un último comentario. Para el registro de los usuarios en batch utilizamos `Promises`, se supone que si alguna petición nos arroja `rejected` la UI debería mostrar un mensaje de error con el listado de los correos que no se agregaron correctamente. En algún cambio eso se perdió y todas las peticiones están devolviendo `fulfilled`. Si nos puedes ayudar a revisar esto estaría genial

**Comment by pabo99** [comment]
@imjpfeliciano , veo que ya subiste un draft arreglando el problema con los usuarios que no existen para que se muestren en el mensaje de error. Entonces, lo único que faltaría aquí sería ver si el componente que estás agregando permita copiar y pegar texto de un archivo de excel o un CSV, para no afectar a los organizadores que cargan los usuarios de esa forma.

**Comment by tvanessa** [comment]
> @imjpfeliciano , veo que ya subiste un draft arreglando el problema con los usuarios que no existen para que se muestren en el mensaje de error. Entonces, lo único que faltaría aquí sería ver si el componente que estás agregando permita copiar y pegar texto de un archivo de excel o un CSV, para no afectar a los organizadores que cargan los usuarios de esa forma.

Si es posible, pasemos este comentario al draft. Por favor

**Comment by imjpfeliciano** [comment]
Perfecto, muchas gracias por las respuestas, creo que el componente que tengo ya hace bien la validación, y agregué el comportamiento de que detecte igual los espacios vacíos, me falta dar el feedback visual para los elementos que no pudieron ser agregados correctamente
