### ISSUE TITLE
[FEATURE] Crear un post con link público en donde se explique cómo funciona el rank de Contribuidor

### ISSUE THREAD

**Issue by AuroraPrz18** [omegaup/omegaup#7008]
*Crear un post en el blog de omegaUp con link público en donde se explique cómo funciona el rank de Contribuidor para hacer menos confuso los diferentes tipos de ranking*

*Como un usuario es necesario entender de qué forma su participación en la plataforma impacta para asignarles un nivel de ranking en https://omegaup.com/rank/authors/ *

## Comportamiento Esperado

Tener en blog.omegaup.com un post que especifique cómo el ranking de contribuidor funciona.

## Comportamiento Actual

Actualmente existen dos links públicos en donde se explica como funcionan los ranking de escuelas y de usuarios, pero no existe uno para los contribuidores. Esto afecta el hecho de que el issue  #6434 no se pueda concretar completamente, pues el cambio que en él se plantea involucra el hecho de tener enlaces a la explicación del funcionamiento de los 3 diferentes rankings. Actualmente no se cuenta con ninguna explicación al usuario sobre los diferentes tipos de ranking en la plataforma de omega Up, sólo en el blog arriba mencionado (sólo explicando el dde usuarios y escuelas, no contribuidores), por lo que puede ser complicado para el usuario encontrar información al respecto, afectando la experiencia del mismo.
Debido a esto es que se sugirió la mejora mencionada en #6434

## Posible Solución

Crear una nueva publicación en el blog similar a la explicaciones del ranking de usuario y escuelas (link abajo), en donde se explique cómo funciona el ranking de contribuidor.
https://blog.omegaup.com/el-nuevo-ranking-de-escuelas-de-omegaup/
https://blog.omegaup.com/el-nuevo-ranking-de-omegaup/

**Comment by Vishalydv07** [comment]
I'm eager to contribute to the "Contributor Rank" blog post. Confident I can provide a solution. Can you guide me on the next steps?

**Comment by Vishalydv07** [comment]
I'm eager to contribute to the "Contributor Rank" blog post. Confident I can provide a solution. Can you guide me on the next steps?

**Comment by axsseldz** [comment]
Hola!, yo podria realizar este issue si aun nadie lo ha realizado(:

**Comment by dhruvishah122** [comment]
can you pls assign me this task

**Comment by axsseldz** [comment]
@pabo99 @heduenas Holaa(: Ya se le asigno a alguien este issue?

**Comment by pabo99** [comment]
Listo @axsseldz! 

Y una disculpa por la demora en asignarte el issue. ¿Te queda claro en que consiste el issue?

**Comment by axsseldz** [comment]
Perfecto, gracias!(:
