### ISSUE TITLE
[FEATURE] Versiones de problemas

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#701]
a.k.a. actualización no-destructiva de casos. Cuando se actualizan los casos/configuración de un problema, es deseable tener un diff de todos los scores de los envíos para ese problema. Una vez que se determina que los casos tienen el comportamiento aceptado, se pueden establecer como los correctos para el problema y el scoreboard puede cambiar atómicamente.

Para lograr esto es necesario:
- Exponer el concepto de versiones de los problemas.
- Guardar la configuración del problema en el mismo repositorio que los casos.
- Hacer una nueva prioridad para la reevaluación concurrente de envíos (background-rejudge).
- Rediseñar la interfaz para actualizar el problema y mostrar un diff de scores/veredictos.
- Opcional (posiblemente innecesario si se implementa #612)
  - Guardar las redacciones en un repositorio separado.
  - Dar la opción de subir únicamente los casos o los casos y las redacciones.

**Comment by elendil326** [comment]
@lhchavez qué se decidió con respecto a #700?

**Comment by lhchavez** [comment]
esto sí se va a hacer así como fue planteado.

**Comment by pabloaguilar** [comment]
Esto ya quedó, no?

**Comment by lhchavez** [comment]
sí!
