### ISSUE TITLE
[BUG] Error genérico tratando de crear identidades en un grupo

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#7016]
Al tratar de crear identidades para un grupo, en ciertas ocasiones me manda el siguiente error genérico:

![image](https://github.com/omegaup/omegaup/assets/123875/91ac01e1-78d5-4732-bcc8-b80c9797446a)

El error es ocasionado por algo en el lugar de las escuelas, ya que si borro ese campo, las identidades se crean sin problema. 

Este error ha estado presente durante los ultimos años y vuelve muy complicado el proceso de crear las identidades.

Adjunto el archivo que genera el error.

[OMIS.csv](https://github.com/omegaup/omegaup/files/11557806/OMIS.csv)

EDIT: Atrapar el campo donde se genera el error.

**Comment by heduenas** [comment]
@Karyme-Nava sabes si este issue ya esta resuelto o falta hacer algo mas?

**Comment by heduenas** [comment]
@Karyme-Nava sabes si este issue ya esta resuelto o falta hacer algo mas?

**Comment by Karyme-Nava** [comment]
> @Karyme-Nava sabes si este issue ya esta resuelto o falta hacer algo mas?

Cuando estuve trabajando en este issue no me salía el error con el archivo compartido, así que lo que se agregó en el PR [#7203](https://github.com/omegaup/omegaup/pull/7203) puede ser sólo una parte de la solución, también [habíamos comentado](https://github.com/omegaup/omegaup/pull/7203#pullrequestreview-1594752749) que se seguiría monitoreando este problema para ver si ya se había resuelto
