### ISSUE TITLE
[FEATURE] [omegaUp for Desktop] - CONCURSOS

### ISSUE THREAD

**Issue by galovdev** [omegaup/omegaup#7025]
**Cambios Concursos:**

- Tamaño y espaciado letras de titulos
- Width container que se ajuste al width general de la nav y footer/links
- En el div donde esta (Palabra clave, X, Buscar, Ordenar Por y Filtrar por) quitar el border radius de las esquinas izquierdas y la esquina inferior izquierda que hace que no se vea redondeado donde no debe
- En el div de las cartas agregar padding en la parte de abajo para que no choque con los concursos o se vean cortadas las tarjetas de cada concurso
- Concusros > Pasados - "No hay concursos con esas características" que tenga menos tamaño de font
- En pasados que el Scoreboard y el botón de entrar este pegados a la derecha, no que el scoreboard este chueco
- En la barra inferior donde vienen los números para buscar concursos anteriores ( <, 1, 2, 3, 4, > ) agregar padding arriba para que no pegue con las demás secciones, o “añadirla al div’ para que quede unida como el div de los filtros, que sea igual a las demas, cambiar también el tamaño de letra de los numeros/botones de esa misma barra.
- Seccion de Actuales, Pasados y Proximos, checar el tono gris que se usa ahi si lo puedo añadir a los botones de Filtrar por y Anadir por, para que no haya tres tonos de grises
- Color Boton buscar que sea el mismo azul que el de inscribirme
- Doble Scrollbar, que solo se pueda scrollear la seccion de concursos, lo demas que sea estatico

## Tu ambiente

* Nombre del navegador: macOs Ventura
* Sistema Operativo y versión: Escritorio 
* Link al sitio en el que este problema pasa: https://omegaup.com/
* Captura de pantalla: !
![CONCURSOS_OMEGAUP](https://github.com/omegaup/omegaup/assets/107520089/1b2fa9d7-c09c-4da2-927d-149a2f4f8ba1)

**Comment by pabo99** [comment]
Aprovechando que se le van a corregir los estilos a esta vista, ¿Hay posibilidad que se evite el doble scrollbar? 

![DoubleScrollContestsList](https://github.com/omegaup/omegaup/assets/3230352/9a9b7a75-5731-4384-abdd-85e1be64e4bb)

**Comment by galovdev** [comment]
> Aprovechando que se le van a corregir los estilos a esta vista, ¿Hay posibilidad que se evite el doble scrollbar?
> 
> ![DoubleScrollContestsList](https://user-images.githubusercontent.com/3230352/242086822-9a9b7a75-5731-4384-abdd-85e1be64e4bb.gif)

Dejame añado eso
