### ISSUE TITLE
Identificar código en lockdown mode

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#703]
Cuando en arena.omegaUp.con no puedes ver los códigos de tus submissions, pero sería útil poderlos identificar como quiera. Tal vez mostrar el SHA1 del código en vez del código en si?

**Comment by lhchavez** [comment]
qué tal si guardo los códigos que envías en memoria y los despliego best-effort? si das F5 desaparecen en el éter y eso es un feature ;)

**Comment by frcepeda** [comment]
Oh, eso gusta
+1
