### ISSUE TITLE
[BUG] Escuelas nuevas no pueden ser agregadas en el perfil

### ISSUE THREAD

**Issue by omarpaladines** [omegaup/omegaup#7037]
## Comportamiento Esperado

Se espera que el estudiante pueda agregar su escuela en su perfil, incluso si esa escuela no ha sido creada aún.

## Comportamiento Actual

Estudiantes cuya escuela no ha sido creada aún no pueden agregar su escuela en su perfil. Les da error School::InvalidParameter o algo similar.

**Comment by heduenas** [comment]
@pabo99 puedes por favor checar si este issue se reproduce localmente? Si se reproduce localmente yo creo que va a ser fácil de reparar.
