### ISSUE TITLE
No hay submissions para el problema veintiuno

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#705]
Tengo un bug raro en el problema veintiuno, no importa qué es lo que mande, no aparece nada en la sección de submissions, sí lo evalúa, pero no aparece en submissions

**Comment by lhchavez** [comment]
El markdown tenía un `</div>` que causaba que todas las cosas después de la redacción se desplegaran raro.

**Comment by alanboy** [comment]
Eso suena como que podemos hacer algo para que no vuelva a pasar. No podemos meter todo eso dentro de un iframe para que si algo esta feo ahi dentro no se rompa el html de omegaup?
