### ISSUE TITLE
Problema con el boton de concurso publico/privado

### ISSUE THREAD

**Issue by luisrodolfo** [omegaup/omegaup#706]
La pestaña individual destinada a poner el concurso publico o privado, no funciona desde hace unas dos-tres semanas.

**Comment by luisrodolfo** [comment]
@joemmanuel @lhchavez sigue sin funcionar. Ya recibí correos y mensajes de usuarios de omegaup, pidiéndome ayuda por esto.
Saludos.

**Comment by alanboy** [comment]
Acabo de confirmar esto. Por lo pronto en la pestaña de "editar concurso", la ultima opcion es si el concurso es publico o no.
