### ISSUE TITLE
El texto de mail verificado no esta localizado

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#708]
![image](https://cloud.githubusercontent.com/assets/527987/10068198/3d4460fa-6257-11e5-853d-01f6710b2346.png)
![image](https://cloud.githubusercontent.com/assets/527987/10068199/402c74d8-6257-11e5-96ed-67f24ee68588.png)

La pagina esta en español, pero el texto esta en ingles. Ademas hay que quitar el mail de @joemmanuel por el de soporte aca freson. Yo una vez le mande correo para salvar mi cuenta viejita y solo me ignoro como por 6 meses hasta que lo hice yo desde el pma:P

**Comment by pabloaguilar** [comment]
Esta resuelto parcialmente, ya no apunta a @joemmanuel.
Pero el texto en es.lang sigue estando en ingles:
https://github.com/omegaup/omegaup/blob/45b0765f44a0ca90bd7302f3d1aee502fe905f04/frontend/templates/es.lang#L233
