### ISSUE TITLE
[FEATURE] Como un desarrollador Frontend, quiero tener una libreria para el despliegue de componentes para no necesitar navegar dentro de la plataforma al desarrollar nuevos componentes

### ISSUE THREAD

**Issue by imjpfeliciano** [omegaup/omegaup#7087]
# [FEATURE] Como un desarrollador Frontend, quiero tener una libreria para el despliegue de componentes para no necesitar navegar dentro de la plataforma al desarrollar nuevos componentes

## Comportamiento Esperado

Muchas aplicaciones de frontend moderno utilizan herramientas para el despliegue de componentes similar a https://storybook.js.org/ para el desarrollo ágil de componentes web, lo que permite a los desarrolladores agilizar el proceso de creación y desarrollo de pruebas unitarias más sencillas.

## Comportamiento Actual

- Al crear un componente nuevo y querer visualizarlo en acción, debemos de loguearnos al entorno local de omegaup
- Al querer agregar pruebas unitarias, tenemos que hacer primero una validación manual, y en algunas ocasiones, para acceder a la sección de la cual estamos desarrollando tenemos que navegar durante algunas secciones antes de encontrar el componente

## Alternativas consideradas

- Storybook tiene una interfaz compatible con Vuejs, lo que nos permitiria hacer una configuración y desplegar los componentes de una manera má

**Comment by imjpfeliciano** [comment]
@tvanessa @pabo99 @heduenas que opinan de hacer esta integración a la plataforma, dicha herramienta nos puede ayudar de igual manera para todo el esfuerzo de responsive design, 

De aceptarlo, creo que puedo trabajar en la propuesta y crear guías de desarrollo de historias para la librería 🤩

**Comment by pabo99** [comment]
> @tvanessa @pabo99 @heduenas que opinan de hacer esta integración a la plataforma, dicha herramienta nos puede ayudar de igual manera para todo el esfuerzo de responsive design,
> 
> De aceptarlo, creo que puedo trabajar en la propuesta y crear guías de desarrollo de historias para la librería star_struck

+1 a la implementación de la librería
