### ISSUE TITLE
Mucho ruido en el log cada que alguien escribe mal su contraseña

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#710]
229963 2015-10-02T04:16:03+00:00 [ERROR]: /login.php?redirect=%2Fpreguntas%2F exception 'InvalidCredentialsException' with message 'usernameOrPassIsWrong' in
229964 Stack trace:Â¶
229965 #0 [internal function]: UserController::apiLogin(Object(Request))Â¶
229966 #1 /opt/omegaup/frontend/server/libs/Request.php(73): call_user_func('UserController:...', Object(Request))Â¶
229967 #2 /opt/omegaup/frontend/www/api/ApiCaller.php(32): Request->execute()Â¶
229968 #3 /opt/omegaup/frontend/www/login.php(16): ApiCaller::call(Object(Request))Â¶
229969 #4 {main} (/opt/omegaup/frontend/www/api/ApiCaller.php:34)~Â¶

**Comment by elendil326** [comment]
@alanboy @lhchavez Esto sigue siendo un problema?

**Comment by elendil326** [comment]
#1545 le dará seguimiento
