### ISSUE TITLE
Atrapar el caso donde el envio de correo falla

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#711]
Usuario:

```
Olvidé mi contraseña, ingreso mi correo y dice que las instrucciones 
para recuperarla ya fueron enviadas a mi correo, pero no me llega
correo alguno, ni en la bandeja de entrada ni en spam.
```

Log:

[ERROR]: /api/user/create/ Failed to send mail: SMTP Error: Data not accepted.<p>SMTP server error: 5.4.5 Daily user sending        quota exceeded. (ALAN: EDITADO)</p>
   (/opt/omegaup/frontend/server/controllers/UserController.php:240)~
2015-10-01T05:40:52+00:00 [ERROR]: /api/user/create/ exception 'EmailVerificationSendException' with message 'errorWhileSendingMail' in /opt/omegaup/fr       ontend/server/controllers/UserController.php:241Â
Stack trace:
#0 /opt/omegaup/frontend/server/controllers/UserController.php(99): UserController::sendVerificationEmail(Object(Request))¶
#1 [internal function]: UserController::apiCreate(Object(Request))
#2 /opt/omegaup/frontend/server/libs/Request.php(73): call_user_func('UserController:...', Object(Request))
#3 /opt/omegaup/frontend/www/api/ApiCaller.php(32): Request->execute()
#4 /opt/omegaup/frontend/www/api/ApiCaller.php(53): ApiCaller::call(Object(Request))¶
#5 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()¶
#6 {main} (/opt/omegaup/frontend/www/api/ApiCaller.php:34)~

**Comment by lhchavez** [comment]
gsmtp es el servidor de correo de google. no se si podamos hacer algo para
subir la quota nosotros.

**Comment by elendil326** [comment]
@lhchavez un retry logic al rededor de esta lógica sería una solución viable? o se espera algo de UI como decirle al usuario que lo intente más tarde?

**Comment by lhchavez** [comment]
Esto en particular no ha hecho repro desde hace más de un año.
