### ISSUE TITLE
hay muchos problemas a+b

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#712]
me puse a resolver todos los problemas de omegaup en esta lista:
https://omegaup.com/problem/?query=&order_by=accepted&mode=desc

y me di cuenta que hay muchos, muchos, problemas "hola mundo" o "a+b".

**Comment by pabloaguilar** [comment]
Si tuvieramos soluciones oficiales... podriamos correr las soluciones oficiales de problemas publicos vs. un problema que alguien este creando y sugerir el problema publico (como le hace stackoverflow "otra gente ha preguntado X, estas seguro que quieres continuar con tu pregunta X' que es muy parecida?")

**Comment by lhchavez** [comment]
eso suena muy O(n²) D:

**Comment by elendil326** [comment]
@lhchavez diseño requerido

**Comment by lhchavez** [comment]
Nah, esto es parte de lo del sistema de revisiones.
