### ISSUE TITLE
[BUG] La posición en el ranking se muestra en un tamaño muy pequeño

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7127]
Al mostrar los listados de ranking la columna de la posición de los usuarios
no ocupa el espacio suficiente para mostrarse y aparece de la siguiente forma:

![Screenshot from 2023-07-21 15-08-45](https://github.com/omegaup/omegaup/assets/3230352/55352ad9-262b-4fa8-beed-b24cac58865e)

# Posible solución

Dar un tamaño automático para que esto no vuelva a suceder.

Hay que revisar todos los listados para ver que en todos se arregle el error

**Comment by pabo99** [comment]
@galovdev Esto lo pudo haber ocasionado los cambios que subiste. ¿Puedes revisar para arreglarlo?

**Comment by galovdev** [comment]
> @galovdev Esto lo pudo haber ocasionado los cambios que subiste. ¿Puedes revisar para arreglarlo?

https://github.com/omegaup/omegaup/pull/7137 Ya quedo
