### ISSUE TITLE
No se puede deployear vagrant

### ISSUE THREAD

**Issue by shopClerk** [omegaup/omegaup#713]
Hola, cuando hago vagrant up da un error que dice
```
==> default: Error: Could not find dependency File[/etc/omegaup/grader] for File[/etc/omegaup/grader/omegaup.conf] at /etc/puppet/modules/omegaup/manifests/grader.pp:33
```
Luego dice que
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Mi versión de vagrant es 1.7.4 y la de virtualbox es 4.3.30.  Seguí [estas intsrucciones] (https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar).

**Comment by lhchavez** [comment]
Vuelve a descargar el repositorio omegaup/deploy (sobreescribe los archivos viejos) y haz `vagrant up --provision` o `vagrant up` seguido de `vagrant provision`.

**Comment by joemmanuel** [comment]
@shopClerk, si esto no funciona, mándanos el output completo de `vagrant up`

**Comment by lhchavez** [comment]
ya lo arreglé en el otro repositorio :P
