### ISSUE TITLE
Mover <script src='https://www.google.com/recaptcha/api.js'></script> a antes del </head>

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#715]
https://github.com/omegaup/omegaup/pull/714/files#r41594696

**Comment by elendil326** [comment]
@alanboy @lhchavez  Esto ha sido solucionado con #714?

**Comment by lhchavez** [comment]
al contrario, esto fue _introducido_ en #714. es un `TODO`.

**Comment by princepurohit153** [comment]
lhchavez i will want to work on this issue please assign me this task
