### ISSUE TITLE
[BUG] Error interno al hacer un envío

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#7162]
Hola a todos.

El juez anda regresando error interno al hacer envíos (lo probamos con dos usuarios distintos y dos problemas distintos).

![image](https://github.com/omegaup/omegaup/assets/19719969/6ba7e118-087d-4f5b-933d-ff8201c1b2e3)

{"status":"error","error":"Oops. Ocurri\u00f3 un error interno. Por favor int\u00e9ntalo nuevamente.","errorname":"generalError","errorcode":500,"header":"HTTP\/1.1 500 INTERNAL SERVER ERROR","_id":"64cbe657491e1029034951"}

**Comment by InesLlergo** [comment]
Igual, me anda dando error para poder enviar mi código en cualquier parte de la plataforma. Me aparece lo mismo de "Opps. Ocurrió un error interno."

**Comment by pabloaguilar** [comment]
Ya debería funcionar nuevamente
