### ISSUE TITLE
[BUG] Add light text for present section 

### ISSUE THREAD

**Issue by Brijesh1963** [omegaup/omegaup#7164]
PROBLEM "Add light text for present directory..."

GO TO "https://omegaup.com/course/home/"

![light_text](https://github.com/omegaup/omegaup/assets/98037970/028c981d-ea56-4824-9c74-3f01c03dd1c4)

**Comment by Praveen14641** [comment]
PLease can you explain this clearly and then assign it to me.....

**Comment by dhruvishah122** [comment]
please can you assign me this project
