### ISSUE TITLE
Dismiss all clarifications

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#717]
Quitar una clarificación ya de por sí es lento, pero cuando hay miles y miles de clarificaciones y das F5 (porque ocurre mucho cuando el internet es basura), es muy tardado y molesto tener que quitar una por una con la animación que tienen.

Si bien sería lindo que también se guardaran qué notificaciones ya se vieron y cuáles no, sería muy útil poder borrar todas las notificaciones de la pantalla.

**Comment by lhchavez** [comment]
La segunda parte (guardar qué notificaciones has visto) ya quedó arreglada en b2cc2d73f3e2dcff856dd49e0136cda6672d4245. El bug original lo está resolviendo @mikebsg01
