### ISSUE TITLE
[BUG] El scoreboard es muy angosto y no se ve completo

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#7180]
## Comportamiento Esperado

El scoreboard deberia verse completo, sin scrollbar horizontal.

## Comportamiento Actual

El scoreboard tiene un scroll horizontal porque el concurso tienes muchos problemas y/o el nombre de equipo es largo.

## Posible Solución

Dejar que la tabla crezca de tamano a como necesite, sin scrollbar.

## Pasos para reproducir (para bugs)

1. Crea un concurso por equipos, para que los equipos tengan nombre largo
2. Agregar al menos 10 problemas al concurso
3. Resuelve algunos problemas en el concurso, para que las celdas crezcan de tamano por el puntaje obtenido
4. Observa que el scrollbar horizontal aparece y ya no se puede ver, a simple vista, el resultado total.

## Contexto

En un concurso por equipos (https://omegaup.com/arena/ep-1-cas-2023/#ranking) se ve asi porque los nombres de los equipos son largos por el prefijo:

<img width="922" alt="image" src="https://github.com/omegaup/omegaup/assets/606680/d8e2d80d-f4c8-44f6-a4c0-d4b3d679757d">

## Tu ambiente

N/A

**Comment by DT3264** [comment]
Como nota, el contest que mencionas parece ser privado,
sin embargo, al parecer no estaría mal proponer o definir cual seria la manera más adecuada de ver el scoreboard de manera movil

[Aqui](https://i0.wp.com/css-tricks.com/wp-content/uploads/2016/03/types-of-responsive-tables.gif) hay un ejemplo de las maneras que podría mostrarse la tabla.

De momento parece que se muestra con Scroll, y aunque Squish podría servir, imagino que no seria lo más adecuado porque cada cuadro se podría saturar relativamente rápido

Sin embargo, podría proponer un intermedio de la opción "Collapsing rows", parecido a lo siguiente.

![image](https://github.com/omegaup/omegaup/assets/45462106/f5ab07c4-6fe0-46d9-b7cd-dfedfe5af592)

Nota: Dado que bootstrap maneja hasta 12 columnas, para evitar comprimir todo el scoreboard en una sola fila, se podrian dividir de 6 problemas por fila

**Comment by wkoder** [comment]
Aca esta el admin link donde se puede reproducir el mismo problema: https://omegaup.com/arena/ep-1-cas-2023/scoreboard/Rt6LfunHbAuLgRyS4WBPQMupLjMmLB

Yo siento que hacer un wrapping the los problemas en scoreboards no es estandar y yo en lo particular nunca lo he visto. En el caso de omegaUp, siento el mayor problema es que se desperdicia muchisimo espacio a los costados del scoreboard, por tener un max-width tan pequeno de 900px (CSS class `omegaup-scoreboard`).

Si se elimina `max-width: 900px` de `omegaup-scoreboard` y el maximo de 1140px del grid (CSS class `container-lg`) se mira asi:
<img width="1499" alt="image" src="https://github.com/omegaup/omegaup/assets/606680/082fe000-62fe-438f-81e2-af90949b963c">

No estoy sugiriendo simplemente se haga eso, solo que seria bueno el equipo de omegaUp rediseñara como se usa el espacio. Si sirve de algo, asi se ve un scoreboard del ICPC region SWERC: https://swerc.eu/2021/theme/scoreboard/public/

**Comment by imjpfeliciano** [comment]
Agregando a esto, creo que solo cambiando el `font-size` a `small` se observaría la tabla correctamente ^ al menos la de ejemplo, pero creo que si es importante buscar una alternativa para que lo que sea scrollable sea el contenido de los problemas y dejar el total fijo para una mejor visibilidad.

![image](https://github.com/omegaup/omegaup/assets/6007230/5843d123-6330-4565-9cea-c1028b84a8fe)

**Comment by imjpfeliciano** [comment]
Y +1 al comentario de @wkoder para alinear el contenido de la tabla:

Estamos dejando mucho espacio en ambos lados,

Izquierda:
![image](https://github.com/omegaup/omegaup/assets/6007230/238d6cec-aea0-4ffc-ba33-2791e52a4517)

Derecha:
![image](https://github.com/omegaup/omegaup/assets/6007230/5ce6a205-6fc6-4ab7-a2f1-b4b8ddf842b2)

**Comment by pabo99** [comment]
I like the idea of moving the total column before the problems columns. Additionally, you can try implementing the solution proposed in the PR https://github.com/omegaup/omegaup/pull/7434.

One last thing to consider is utilizing the full width of the window. Please ensure that the "Problems" tab is displayed correctly after making these adjustments.

**Comment by kai824** [comment]
Ok, I'll work on moving the total column before the problems, as well as making longer team names word wrap as done in PR https://github.com/omegaup/omegaup/pull/7434.
