### ISSUE TITLE
Revamp de las modalidades del concurso

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#719]
Resulta que la disposición actual de separar visibilidad y registro/no registro es un poco confuso. Se propone lo siguiente:
- Cambiar ambas banderas por un enum llamado 'modalidad' con tres opciones:
  - Privado: El concurso no sale en ninguna lista y no puedes acceder a él a menos que hayas sido invitado explícitamente a priori (te sale 404).
  - Registro/open: Cualquiera puede participar después de haberse registrado, pero solo las personas previamente admitidas pueden participar "oficialmente" en el concurso. Se mostrarán dos scoreboards con solo los invitados oficiales y otro con todos. Esto es un superconjunto de #699.
  - Público: Todos pueden participar.
- Mostrar el intersticial a todas las personas, independientemente de su status como administrador.
- El modo de práctica estará abierto al público en las modalidades registro/open y público una vez terminado el concurso. Los participantes de un concurso privado también pueden acceder a ese concurso en modo práctica al terminar.
  - El intersticial de un concurso terminado te debe mostrar el scoreboard y tener una liga al modo de práctica.

**Comment by joemmanuel** [comment]
+1.
El modo práctica también tiene sentido para los concursos privados, hay que
agregarlo al último punto.

2015-10-12 19:54 GMT-07:00 lhchavez <notifications@github.com>:

> Resulta que la disposición actual de separar visibilidad y registro/no
> registro es un poco confuso. Se propone lo siguiente:
>
>    - Cambiar ambas banderas por un enum llamado 'modalidad' con tres
>    opciones:
>       - Privado: El concurso no sale en ninguna lista y no puedes acceder
>       a él a menos que hayas sido invitado explícitamente a priori (te sale 404).
>       - Registro/open: Cualquiera puede participar después de haberse
>       registrado, pero solo las personas previamente admitidas pueden participar
>       "oficialmente" en el concurso. Se mostrarán dos scoreboards con solo los
>       invitados oficiales y otro con todos. Esto es un superconjunto de
>       #699 <https://github.com/omegaup/omegaup/issues/699>.
>       - Público: Todos pueden participar.
>    - Mostrar el intersticial a todas las personas, independientemente de
>    su status como administrador.
>    - El modo de práctica estará abierto a las modalidades registro/open y
>    público una vez terminado el concurso.
>       - El intersticial de un concurso terminado te debe mostrar el
>       scoreboard y tener una liga al modo de práctica.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/719>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by lhchavez** [comment]
aguanta. no hagas cambios a los privados o la gente se va a enojar. hay que
buscar cómo incentivar que los hagan públicos poco a poco.

**Comment by joemmanuel** [comment]
No cambios a los privados, /practice debe funcionar como práctica sólo para
los que tenian acceso originalmente.

On Tuesday, October 13, 2015, lhchavez <notifications@github.com> wrote:

> aguanta. no hagas cambios a los privados o la gente se va a enojar. hay que
> buscar cómo incentivar que los hagan públicos poco a poco.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/719#issuecomment-147750234>.
>


-- 
Saludos,
Joemmanuel Ponce

**Comment by lhchavez** [comment]
ah eso debe estar pasando en este momento. si eso no es cierto, abre otro
bug y mueve esa discusión allá para no contaminar (más) este bug
controversial.

**Comment by joemmanuel** [comment]
OK, interpreté tu punto 3 como 'excluir /practice de los  concursos
privados'.
+1 a todo entonces.

On Tue, Oct 13, 2015 at 9:20 AM, lhchavez <notifications@github.com> wrote:

> ah eso debe estar pasando en este momento. si eso no es cierto, abre otro
> bug y mueve esa discusión allá para no contaminar (más) este bug
> controversial.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/719#issuecomment-147766566>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by elendil326** [comment]
@lhchavez esto aún es necesario?

**Comment by pabo99** [comment]
Actualmente esta opción aparece hasta que estás editando un concurso, y por default se registran todos los nuevos concursos como privados. ¿Esto seguirá siendo igual?

Y tengo otra duda, cuando se da de alta un concurso con el Registro/open, ¿a quien se le solicita el registro? ¿a todos o sólo a los que dio de alta el administrador?

**Comment by pabo99** [comment]
¿Hace falta corregir algo en este PR?
