### ISSUE TITLE
Funcionalidad para marcar problemas como "mal redactados"

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#724]
Un problema asi no es aceptable:
![image](https://cloud.githubusercontent.com/assets/527987/11071225/859d85c2-8794-11e5-8532-372c89a1cead.png)

**Comment by joemmanuel** [comment]
LOL

On Tue, Nov 10, 2015 at 10:19 AM, Alan Gonzalez <notifications@github.com>
wrote:

> Un problema asi no es aceptable:
> [image: image]
> <https://cloud.githubusercontent.com/assets/527987/11071225/859d85c2-8794-11e5-8532-372c89a1cead.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/724>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by lhchavez** [comment]
Esto es lo que mencionaba César de los problemas aprobados.

Tenemos dos opciones:

* Dejamos los problemas como están y después que personas aprobadas lo
resuelven, _pueden_ promover ese problema como aprobado de que pasó la
barra de calidad. Le ponemos una estrellita y ya contribuye para el score.
* Para publicar un problema, tienes que seguir un proceso para certificarte
como que no subes basura. Karma/score/manual/como sea.

LHC

**Comment by elendil326** [comment]
@lhchavez quizá esto ya este resuelto con peer review?

**Comment by lhchavez** [comment]
sí!
