### ISSUE TITLE
[BUG] Validador con tokens numericos no lee correctamente flotantes en notacion exponencial

### ISSUE THREAD

**Issue by wkoder** [omegaup/omegaup#7242]
## Comportamiento Esperado

Usualmente, cuando un problema tiene salidas en coma flotante y se elige la opcion de validador de "Tokens numericos con tolerancia de 1e-9" es porque se asume que las soluciones intentaran imprimir el resultados con precision completa, lo cual, la mayoria de los lenguajes hacen de manera predeterminada para conservar la precision maxima posible y no redondear. Por lo tanto, se espera que `1E-9 == 0.000000001`.

## Comportamiento Actual

omegaUp ignora cualquier caracter que no sea `-`, `.` o digito, por lo que `1E-9` no es interpretado como `0.000000001`, [vease aqui](https://github.com/omegaup/backend/blob/996629bc14106a3995cfa3d5119f669c47f23ce1/grader/src/main/scala/com/omegaup/grader/OutputValidator.scala#L482).

## Posible Solución

`E` deberia ser aceptado [aqui](https://github.com/omegaup/backend/blob/996629bc14106a3995cfa3d5119f669c47f23ce1/grader/src/main/scala/com/omegaup/grader/OutputValidator.scala#L482), considerado [aca](https://github.com/omegaup/backend/blob/996629bc14106a3995cfa3d5119f669c47f23ce1/grader/src/main/scala/com/omegaup/grader/OutputValidator.scala#L305), y probado [aca](https://github.com/omegaup/backend/blob/996629bc14106a3995cfa3d5119f669c47f23ce1/grader/src/test/scala/ValidatorTests.scala#L161).

## Pasos para reproducir (para bugs)

Puedo crear uno de prueba pero creo que con la prueba unitaria y los links de arriba es suficiente.

## Contexto

Problemas en las evaluaciones del problema B del Coding Cup TecNM 2023.

## Tu ambiente

N/A

**Comment by heduenas** [comment]
Este es el repositorio actual del grader: https://github.com/omegaup/quark

**Comment by wkoder** [comment]
Lo copio alla entonces! Gracias, Hugo!
