### ISSUE TITLE
[BUG] Concursos futuros no deben de mostrar 404 si estoy inscrito

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7245]
Hay que seguir el mismo enfoque que seguimos para tareas futuras en cursos: https://github.com/omegaup/omegaup/issues/7181

**Comment by Karyme-Nava** [comment]
En ese PR se muestran los títulos de los problemas de la asignación ¿ese no sería un problema para los concursos que reutilizan problemas?

**Comment by tvanessa** [comment]
> En ese PR se muestran los títulos de los problemas de la asignación ¿ese no sería un problema para los concursos que reutilizan problemas?

Solo es una referencia. Lo ideal es solo mostrar la UI de bienvenida y que boton de `ir a concurso` este bloqueado

![Screen Shot 2023-09-14 at 5 32 54 PM](https://github.com/omegaup/omegaup/assets/13296248/49b92463-bcc9-4a74-934a-4de820c9e402)
