### ISSUE TITLE
[FEATURE] Actualizar los ejemplos de alias de concurso

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7258]
En https://omegaup.com/contest/new/ se muestran ejemplos de concurso de hace mas de 10 años.
![image](https://github.com/omegaup/omegaup/assets/597815/bae58e6d-30c0-431f-b13c-321a96d51fe7)

Podemos poner por ejemplo CodingCup2023, OFMI2024, CopaCentroAmericana2024.

**Comment by aarishshahmohsin** [comment]
Can I solve this issue?

**Comment by uraj323** [comment]
please assign this issue to me i want to work on it

**Comment by Varlight** [comment]
@heduenas  me gustaria trabajar en este issue

**Comment by iqbalcodes6602** [comment]
hello @heduenas I have done as u said can u plz consider this PR for merging
