### ISSUE TITLE
Columna "Ratio" debería mostrar los porcentajes sobre 100%

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#726]
Sólo hace falta multiplicarlos por 100 :P

![screenshot from 2015-11-24 20 34 29](https://cloud.githubusercontent.com/assets/597815/11388433/0b321bf6-92eb-11e5-8b16-31b5becb8b63.png)

**Comment by lhchavez** [comment]
No quieres hacer el pull request y ganarte un badge? :D 

https://github.com/omegaup/omegaup/blob/master/frontend/templates/problem.list.tpl#L35
