### ISSUE TITLE
[BUG] En vista de ADMINS sólo se pueden listar los 100 envíos más recientes y ya no se pueden buscar

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#7304]
Hola a todos.

Con el cambio en la lista de envíos, ahora cada página es de siete filas (lo cual es algo bajo, porque obliga a dar muchos clics).
![image](https://github.com/omegaup/omegaup/assets/19719969/9ab5dd05-f673-4425-97bc-3df942121d94)

El paginado sólo soporta 15 páginas.
![image](https://github.com/omegaup/omegaup/assets/19719969/1d619a00-619c-4d64-afe5-d3375cb0baf4)

Ya no se pueden buscar envíos.
![image](https://github.com/omegaup/omegaup/assets/19719969/5ccb4daf-21bb-414b-9404-e64546eee989)

Durante este par de años he estado usando el buscador de envíos como *workaround* de #6033 (aunque mis envíos no aparecían en la tabla de mis envíos, sí aparecían en la lista de todos los envíos), pero al eliminar el buscador de envíos esto ya no funciona.
![image](https://github.com/omegaup/omegaup/assets/19719969/5d259b7e-c5db-4132-b744-008913cfdaa3)

Es decir, #6033 ahora es más grave y la pérdida de funcionalidad también preocupa.

**Comment by mrrahulkrr** [comment]
can u make it in english

**Comment by darkmx** [comment]
With the modifications made to the submissions list, now each page is 7 rows long (a small amount; now you have to click too often), the pagination supports 15 pages only (100 submissions in total, you can't access older submissions) and the submission search functionality was removed.

Submissions sent by the author of a problem are not shown in the problem page due to #6033. However, they still appeared in the complete submission list, so the submission search functionality could be used as a workaround. Since such functionality was removed, #6033 is worse than before and I am worried about the removal of functionality.

**Comment by pabloaguilar** [comment]
+1 on @darkmx 's comments. The new paginated list seems much harder to go through.

Can we please:
* add back the search functionality
* add a way to select the page length I want to use (including an ALL option)

**Comment by darkmx** [comment]
The "ALL" option may be dangerous (server overload), unless something like smooth infinite scrolling is implemented.

**Comment by tvanessa** [comment]
@OmarGO1 Ya veo la confusión. Para las vistas de estudiantes deben hacerse estas limitaciones, es decir las vistas:
 - de problema
 <img width="645" alt="Screenshot 2023-11-01 at 3 52 19 PM" src="https://github.com/omegaup/omegaup/assets/13296248/51d116fd-a4fe-4bf4-b619-79bdc5626351">
 - y de cursos
 
<img width="1036" alt="Screenshot 2023-11-01 at 3 54 01 PM" src="https://github.com/omegaup/omegaup/assets/13296248/ca318a4c-9306-44f2-8f8d-f5cd37eaec00">
 
tienen las filas de 10 y el limite de 150 envios.

Pero para admins de problemas, o docentes no podemos seguir esas mismas especificaciones. Entonces todas las vistas de "Envios" para admins se regresan al formato que tenian, creo que son 100 filas, se muestran todos los envios, y no quites los buscadores. Puedes actualizar el paginador, pero no lo limites de la misma forma.
<img width="1605" alt="Screenshot 2023-11-01 at 3 54 57 PM" src="https://github.com/omegaup/omegaup/assets/13296248/c5ff459f-501c-466d-82cd-377b9eb9ca23">

**Comment by OmarGO1** [comment]
@darkmx Lo que mencionas "El paginado sólo soporta 15 páginas." en que vista sucede eso? Y en cuanto a "Ya no se pueden buscar envíos." Te refieres a que en la vista de problema en la pestaña de envíos desaparecieron los filtros?

**Comment by darkmx** [comment]
Efectivamente me refiero a la pestaña de envíos de un problema que administro o del que soy autor.
