### ISSUE TITLE
[BUG] Error al actualizar el tiempo de un problema.

### ISSUE THREAD

**Issue by 5an7y** [omegaup/omegaup#7307]
## Comportamiento Esperado

Al actualizar el tiempo de un problema se haga la actualizacion con el nuevo tiempo.

## Comportamiento Actual

![BadRequestOmegaUp](https://github.com/omegaup/omegaup/assets/34700620/013176f6-cbdc-42ee-8152-c62f1af40b97)

## Pasos para reproducir (para bugs)

1.  Crear un problema.
2. Editar el problema cambiando el tiempo.
3. Agregar una descripcion del cambio e intentar actualizar el problema.

## Contexto

Estoy intentando ajustar los limites de un problema para que las soluciones den el tiempo esperado.

## Tu ambiente

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome 118.0.5993.117 (Official Build) (64-bit)
* Sistema Operativo y versión (escritorio o móvil): Windows 11

## English

Error while trying to update the time limits in a problem. When hitting the "update" button, it sends me a Bad Request and it doesn't update the problem.

**Comment by sudarsan2k5** [comment]
I would like to work on this issue.

**Comment by iqbalcodes6602** [comment]
Intenté resolver esto pero parece que cualquier valor superior a 60000 en el límite de tiempo total (ms) no es aceptable, porque los valores inferiores a 60000 no dan error y la actualización funciona correctamente.

**Comment by iqbalcodes6602** [comment]
@5an7y 
también si vas a front-end>servidor>src>Problem Params.php
Verá que global_wall_time_limit tiene un límite superior de 60000, por lo que el error es 400, código de error incorrecto, por lo tanto, no podemos tener un valor de >60000, se requiere un cambio de interfaz para evitar que los usuarios ingresen cualquier valor >60000, esto podría resolver la cuestión
