### ISSUE TITLE
[BUG] Revertir nueva tabla de veredictos de vista de concursos

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7309]
La nueva tabla de veredictos solo debe de aplicar a cursos y a la vista de problemas.

**Comment by pabloaguilar** [comment]
La nueva vista está algo confusa:

<img width="836" alt="image" src="https://github.com/omegaup/omegaup/assets/189223/f5df2d11-a5d2-46ef-a4ef-a3c001f5104d">


En un mismo renglón tengo "Salida correcta", "veredicto WA" pero y porcentaje 0 resaltado en verde.

**Comment by OmarGO1** [comment]
> La nueva vista está algo confusa:
> 
> <img alt="image" width="836" src="https://user-images.githubusercontent.com/189223/278825662-f5df2d11-a5d2-46ef-a4ef-a3c001f5104d.png">
> En un mismo renglón tengo "Salida correcta", "veredicto WA" pero y porcentaje 0 resaltado en verde.
Hola, buen día. Lo del color ya se está arreglando pero me parece curioso que aparezca "Salida correcta".  ¿Me puede dar mas información para replicar el bug? O no se si me pueda pasar el código que mandó para revisar que está pasando.
