### ISSUE TITLE
[FEATURE] Como un usuario, quiero ver cuándo fue la última actualización del ranking para poder continuar motivado.

### ISSUE THREAD

**Issue by samdsmx** [omegaup/omegaup#7328]
## Comportamiento Esperado

Propuesta:
<img width="1003" alt="image" src="https://github.com/omegaup/omegaup/assets/5838427/78591d68-f979-4738-acea-319771a2bfd0">

## Comportamiento Actual
No se cuenta con ningún indicador para los usuarios

**Comment by sudarsan2k5** [comment]
Hi @samdsmx I would like to work on this issue.

**Comment by samdsmx** [comment]
Great! @sudarsan2k5, Let us know if you need something

**Comment by sudarsan2k5** [comment]
Thanks  @samdsmx  Based on the title, it looks like we need to create a new column showing when a user's rank was last updated. I think the screenshot below is what we're aiming for. Can you confirm if this is right? If not, can you advise on what we should do to achieve the desired result?

![WhatsApp Image 2023-11-14 at 17 57 02_8599f69d](https://github.com/omegaup/omegaup/assets/108286640/4ac97c90-f805-4dbc-92a3-4bd7095b7cb3)

**Comment by samdsmx** [comment]
The last update value is for the whole ranking, not for individual user.. The idea is: (Last Update => Ultima actualización)
![image](https://github.com/omegaup/omegaup/assets/5838427/8df404dc-6dc8-4ba3-a3a8-549f438150fd)
