### ISSUE TITLE
mostrar un error cuando los puntos de un test plan suman 100

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#734]
https://youtu.be/7HykBhEk2I0?t=208

**Comment by lhchavez** [comment]
pero no es un error u_u no pasa nada malo si no suman 100, se re-escala.

**Comment by alanboy** [comment]
del video : "no te marca error, pero falla"

**Comment by lhchavez** [comment]
el video esta mal, no falla :P

**Comment by alanboy** [comment]
este es un bug en el video, no en el software.
