### ISSUE TITLE
[BUG] mi puntuaje y problemas resueltos en el ranking no aumenta (tampoco se me otorgan insignias)

### ISSUE THREAD

**Issue by EXCEDEER-CODE** [omegaup/omegaup#7353]
Desde hace unos dias estuve resolviendo problemas y me di con la sorpresa de que a pesar de tener 115 problemas resueltos
no se me otorgo la insignia de 100 problemas resueltos de OmegaUp ni tampoco la insignia de experto en C++ o Python...

![Anotación 2023-11-19 143110](https://github.com/omegaup/omegaup/assets/129354114/16c98fa0-63ee-4bc3-a30a-43bba477d2f9)

si busco mi cuenta en el ranking solo me acreditaron 5 problemas y 51 puntos...

![Anotación 2023-11-19 143111](https://github.com/omegaup/omegaup/assets/129354114/5316f349-f1eb-4993-a570-8315692422f7)

esta es mi cuenta:

https://omegaup.com/profile/EXCEDEER/

¿ alguien sabe como solucionar el problema ?

**Comment by pabo99** [comment]
Tendremos que revisar si están corriendo todos los cronjobs que aplican el ranking  asignan los badges.
