### ISSUE TITLE
[FEATURE] [Diplomas] Actualizar el valor de certificates_status

### ISSUE THREAD

**Issue by Karyme-Nava** [omegaup/omegaup#7374]
## Comportamiento Esperado

El campo `certificates_status` debería ser actualizado al menos una vez para cada uno de sus valores (`uninitiated`, `queued`, `generated`, `retryable_error`, `fatal_error`).

## Comportamiento Actual

Actualmente sólo se tienen los valores `uninitiated` y `generated` para este campo.

## Contexto

La [API `generateContestCertificates`](apiGenerateContestCertificates) es en donde se agrega el mensaje a la cola de RabbitMQ y [`contest_callback.py`](https://github.com/omegaup/omegaup/blob/main/stuff/pipelines/contest_callback.py) es en donde se agregan los registros de los diplomas a la BD.

**Comment by Karyme-Nava** [comment]
@heduenas ¿sabes en dónde puedo agregar el valor de `retryable_error` y `fatal_error`?

**Comment by heduenas** [comment]
> @heduenas ¿sabes en dónde puedo agregar el valor de `retryable_error` y `fatal_error`?

basicamente tenemos que hacer un try-catch alrededor de toda [esta funcion](https://github.com/omegaup/omegaup/blob/c6ae1b2119afa91db6387107aa09722adc6307ef/stuff/pipelines/contest_callback.py#L51). Si se captura una exepcion, ponemos el estado como `retryable_error`.

Por ahora creo que con eso seria suficiente. Como no hemos probado este feature, no sabemos que errores realmente serian fatales y que errores se deben a bugs que debemos de arreglar nosotros.
