### ISSUE TITLE
[BUG] Website is not fully responsive.

### ISSUE THREAD

**Issue by MiirzaBaig** [omegaup/omegaup#7388]
[screen-capture (1).webm](https://github.com/omegaup/omegaup/assets/115091610/97d89c64-f800-475a-9103-50d90d47c581)

**Comment by Prs0307** [comment]
Could You please assign me Good first issue....

**Comment by MrBlackGhostt** [comment]
@MiirzaBaig i want to work on this issue and make it responsive can you assign it to me

**Comment by MiirzaBaig** [comment]
@MrBlackGhostt Alright, you can work on it!

**Comment by MrBlackGhostt** [comment]
Ok

**Comment by zahidhussain998** [comment]
i'm already working on it

**Comment by MrBlackGhostt** [comment]
i also doing the work

**Comment by uwaiszaki** [comment]
Whats the update on the work
