### ISSUE TITLE
In Coding Guidelines English Version, some content is still in Spanish

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7393]
## Comportamiento Esperado

Coding Guidelines for TypeScript and Python are still in Spanish in https://github.com/omegaup/omegaup/wiki/Coding-guidelines-(English-version)

## Comportamiento Actual

Coding Guidelines for TypeScript and Python must be in English

## Posible Solución

Translate Spanish instructions to English

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1.  Go to https://github.com/omegaup/omegaup/wiki/Coding-guidelines-(English-version)
2.  Go to Typescript and Python section
3.  See the error
4. 

## Contexto

I wanted to know the guidelines for Typescript and I cannot understand the instructions

## Tu ambiente

In github wiki

**Comment by MayaSatishRao** [comment]
@samdsmx I will raise a PR with the translated guidelines. Can I work on this?

**Comment by MayaSatishRao** [comment]
@samdsmx @pabloaguilar I edited Wiki directly and did not raise a PR, since we cannot make pr for changes in the Github wiki

**Comment by pabo99** [comment]
No problem, it's okay. Thanks for translating these missing sections into the correct language.

Just one comment: could you please change the definition of the function in Python to the following:
```py
def updateProblem(
  *,
  problem: Problem,
  previous_version: str,
  current_version: str,
  points: Optional[int] = None,
) -> None:
``` 
?

**Comment by MayaSatishRao** [comment]
@pabo99 I have changed it.

**Comment by pabo99** [comment]
Thank you, @MayaSatishRao .
