### ISSUE TITLE
Signup is successful even when T&C is not accepted

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7394]
## Comportamiento Esperado

While signing up, even when the terms and conditions are not accepted, we can create the account. And we also receive the verification mail.

## Comportamiento Actual

An alert saying that terms and conditions must be accepted. It must be made mandatory.

## Posible Solución
If the checkbox is not selected then an alert must be raised and account verification mail must be sent only if it is checked.

## Pasos para reproducir (para bugs)

1.  Go to signup page (https://omegaup.com/login/)
2.  Add all the details (username, email address and password)
3.  Do not check the T&C checkbox 
4. Click on Signup
5. See the error.

## Contexto
It is crucial for all the users of a platform to agree to the terms and conditions

## Screenshot
![Screenshot 2024-01-10 234517](https://github.com/omegaup/omegaup/assets/67920373/4feb3b85-6225-4cd2-95bb-945af7320e80)

**Comment by MayaSatishRao** [comment]
@pabo99 can you assign this issue to me?

**Comment by pabo99** [comment]
> @samdsmx @pabo99 can you assign this issue to me? I have already setup the development environment in my system and I would love to contribute.

Assigned!

**Comment by MayaSatishRao** [comment]
@pabo99 I did make the changes and when I was testing it, docker is giving this error and now I cannot see the login components anymore. The error in Docker build is referring to this page: https://github.com/browserslist/update-db#readme 
I dont know what changes are to be made to dockerfile to remove this error.
Docker error:
![Screenshot 2024-01-11 013054](https://github.com/omegaup/omegaup/assets/67920373/0cd3132d-c0a8-4b6b-8a73-281e4bc72803)
Login screen which was working earlier is not working:
![Screenshot 2024-01-11 013944](https://github.com/omegaup/omegaup/assets/67920373/c2eb9c1c-bbc1-4e8e-9d84-3dc59adf3058)

**Comment by pabo99** [comment]
I don't think this message is important.

Actually, I received the same message. Take a look:
![image](https://github.com/omegaup/omegaup/assets/3230352/a0af9017-dd22-4da3-bc09-cb4eaea1dd16)

The really important thing to consider is waiting for the compilation to finish. You should wait until you see something like this in your console:
```
frontend_1     | [webpack-cli] Compilation finished
frontend_1     | frontend:
frontend_1     |   209 assets
frontend_1     |   2526 modules
frontend_1     |   frontend (webpack 5.8.0) compiled successfully in 44462 ms
frontend_1     | 
frontend_1     | style:
frontend_1     |   1 asset
frontend_1     |   3 modules
frontend_1     |   style (webpack 5.8.0) compiled successfully in 14621 ms
frontend_1     | 
frontend_1     | grader:
frontend_1     |   77 assets
frontend_1     |   1290 modules
frontend_1     |   grader (webpack 5.8.0) compiled successfully in 43969 ms
frontend_1     | [webpack-cli] watching files for updates...
```
In some cases, it takes a long time to finish the compilation.

I have a question for you: What computer are you using for development?

**Comment by MayaSatishRao** [comment]
I am receiving the same error over and over again. It tried to resolve more than 10 times. I am using Windows machine and WSL2 to run the project.

**Comment by MayaSatishRao** [comment]
@pabo99 it's working now. I have another query. The changes I make in the code are not reflected immediately. I have rerun the docker command again to see the changes (just doing refresh in the browser is not working). For running the project I am running this command, 
`docker-compose up --no-build`
Do I have to execute anything else? What should I do?

**Comment by pabo99** [comment]
Running that command is sufficient. Just be patient; every code change (especially in files with extensions .ts, .vue, .scss) will trigger a new compilation.

**Comment by MayaSatishRao** [comment]
@pabo99 I need to change the message in the popup. What files should I changed? I have only changed lang.es.ts. Should I also change lang.en.json? (I don't how these 2 files differ). I will do the same for other 2 languages as well.

**Comment by pabo99** [comment]
Oh, that might be why you can't see the code changes.

Here's the correct way to modify a string:

- Open the files `frontend/templates/en.lang`, `frontend/templates/es.lang`, and `frontend/templates/pt.lang`.
- If you're altering an existing string, locate the index and update the message in all language files.
- After saving your changes, run the following command:
```bash
./stuff/lint.sh
```
This command will help propagate the changes in the `.ts` and `.json` files.

**Comment by MayaSatishRao** [comment]
@pabo99 I have created the PR. Please review it.
