### ISSUE TITLE
Readme file must have information in English

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7398]
## Comportamiento Esperado
Readme file of this repository has content in Spanish only. The information must also be in English so that everyone can contribute easily.

## Comportamiento Actual
The information must also be in English so that everyone can contribute easily.

## Posible Solución

Add a section to include English translation

## Pasos para reproducir (para bugs)

 View the Readme file of this repository.

**Comment by Vijaykv5** [comment]
@pabo99  ¿Puedo trabajar en ello ya que veo una inactividad en la resolución de estos problemas?

**Comment by MayaSatishRao** [comment]
@Vijaykv5 I will make a PR soon

**Comment by pabo99** [comment]
> @pabo99 ¿Puedo trabajar en ello ya que veo una inactividad en la resolución de estos problemas?

@Vijaykv5 Thank you for your interest in helping us with translations in the documentation. I noticed that @MayaSatishRao is already working on this particular issue. However, feel free to explore the entire wiki section. If you find any articles that are only translated into Spanish, you can propose translations for other supported languages (primarily English).

**Comment by MayaSatishRao** [comment]
@pabo99 I have made a new PR because the last one had changes from other PR as well. Can you please review it?
