### ISSUE TITLE
Slack channel link is not working

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7399]
## Comportamiento Esperado

Slack channel link in How to get help wiki page is not working

## Comportamiento Actual
Link should lead to Omegaup Slack channel

## Posible Solución
Update the link in Wiki page

## Pasos para reproducir (para bugs)

1.  Go to Wiki of this repository
2.  Go to How to get Help wiki page
3.  Click on Slack channel link
4.  See the error

## Screenshots

![Screenshot 2024-01-15 211444](https://github.com/omegaup/omegaup/assets/67920373/58370ba9-b149-4f77-ae29-079fbaa61b0d)

**Comment by MayaSatishRao** [comment]
@pabo99 Can you assign this issue to me? I'll update the wiki page but I need the link to Slack channel.

**Comment by tvanessa** [comment]
Slack is deprecated. It should be [Discord](https://discord.com/invite/K3JFd9d3wk) in channel #dev_training

**Comment by MayaSatishRao** [comment]
@pabo99 @tvanessa I have updated the wiki page https://github.com/omegaup/omegaup/wiki/How-to-Get-Help If any changes are required do let me know.

**Comment by pabo99** [comment]
One more thing, could you please replace the word 'vagrant' with 'docker' in that document? I don't think we'll be using Vagrant anymore

**Comment by MayaSatishRao** [comment]
@pabo99 I have made that change as well.
