### ISSUE TITLE
[BUG] Los asistentes de enseñanza de un curso (TAs) no pueden ver el curso en su listado

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7416]
## Comportamiento Esperado

Una vez  que un usuario es agregado como TA de un curso, este debería
poder ver dicho curso en su listado de cursos. Ya sea que pertenece a un
grupo de TAs o que lo agregaron por username.

## Comportamiento Actual

No hay un lugar donde se pueda ver que el usuario pertenece al curso con 
el rol de TA.

## Posible Solución

Agregar los cursos de los cuales el usaurio logueado es TA en el listado de
"Mis cursos" o, en la vista de "Ver cursos". 

En cualquiera de los dos casos, se puede agregar un nuevo tab con estos 
cursos para poder identificar que el usuario tiene un rol distinto

## Pasos para reproducir (para bugs)

1. Agregar TAs, ya sea por username o por grupo:
![image](https://github.com/omegaup/omegaup/assets/3230352/889d3593-3280-483f-b6cb-f16ed8a8c683)
![image](https://github.com/omegaup/omegaup/assets/3230352/239947db-dba6-4b87-8b49-66e454b1d3f9)

2. Ingresar con la cuenta de alguno de estos usuarios y buscar los cursos en los cuales tienen el rol de TA:
![image](https://github.com/omegaup/omegaup/assets/3230352/9c13514e-ce99-467e-b7dc-686cb28b8b17)
![image](https://github.com/omegaup/omegaup/assets/3230352/52a34aeb-84a5-4794-b9b2-0b1411b2fe88)

## Contexto

Se pretende liberar la funcionalidad próximamente, pero al hacer las pruebas
manuales, notamos que esta parte no está funcionando correctamente.

**Comment by zahidhussain998** [comment]
hey @pabo99 i got it this issue plase assigne to me this issue so that i can start working on it thanks

**Comment by pabo99** [comment]
Actually, you already have three open PRs. Could you please work on them before we assign you new issues?

Thank you.

**Comment by Vijaykv5** [comment]
@pabo99 Sorry for mentioning here 
I was having trouble in setting up the project locally as I encountered some issue which were out from the `setup.md`
I've gone through the `contributing guidelines` also. I also asked for help in discord but sadly no one responded and I see that all conversations in discord are spanish.
Is there any way how to resolve this? or does omegaup have another communication platforms?
