### ISSUE TITLE
[BUG] Lista de envíos no muestra el botón de Acciones

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#7418]
## Current Behavior

Al parecer, cuando hay envíos de usuarios con un nombre muy grande, la tabla no resizea bien la columna Coder y eso hace que las columnas de la derecha no se rendereen bien.

![image](https://github.com/omegaup/omegaup/assets/123875/6fc11a81-89ce-44d1-b306-a4eb8697950a)

## Expected Behavior

Con un nombre de usuario más pequeño si se ve el botón:

![image](https://github.com/omegaup/omegaup/assets/123875/d0038e5c-746e-47c3-9fe2-890066a11c90)

Browser: Chrome Version 120.0.6099.225 (Official Build) (64-bit)

**Comment by iqbalcodes6602** [comment]
@darknut @pabo99  i think the action button is rendering but u need to scroll horizontally in order see the it,
can you tell me exactly what you want?

**Comment by darknut** [comment]
I hadn't seen the bar, if I had seen it, I would have used it. The problem is that how was I supposed to know there was a bar in the bottom of the list when the list has dozens of entries. If I wanted to check the code of an entry in the middle, I would have to go all the way to the bottom, scroll, and then find again where I was. What I've been doing is filtering the user I need and hoping the user has a short name.

I think the better solution here is to make sure the 'Coder' column has a fixed or maximum width and break or add '...' to user names that are too big.

**Comment by axsseldz** [comment]
@pabo99 @darknut Me puedo encargar del issue, solo que no encuentro exactamente donde se da el problema, es en la pagina de OmegaUp, en el apartado de "Problems/View Latest Sumissions"?

**Comment by pabo99** [comment]
> @pabo99 @darknut Me puedo encargar del issue, solo que no encuentro exactamente donde se da el problema, es en la pagina de OmegaUp, en el apartado de "Problems/View Latest Sumissions"?

@axsseldz: It seems this issue has already been fixed by @iqbalcodes6602. Thank you guys for your interest in collaborating with omegaUp.
