### ISSUE TITLE
[BUG] Las listas de envíos ya no muestran el estado de ejecución o salida

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#7419]
## Current Behavior

Antes decía exactamente qué pasó, pero ahora solo dice "No disponible"

![image](https://github.com/omegaup/omegaup/assets/123875/5e9f2899-d9fe-40f3-a6f2-964a786b8488)

No importa si son nuevos envíos o viejos, siempre dice "No disponible"

Tampoco importa si son tus enviós en un problema o los envíos que alguien hizo en tu problema.

![image](https://github.com/omegaup/omegaup/assets/123875/64d4b48c-c79a-48b8-9189-638d2baacfb1)

**Comment by tvanessa** [comment]
#7377
