### ISSUE TITLE
Overlapping the navbar[BUG]

### ISSUE THREAD

**Issue by nithinkatta** [omegaup/omegaup#7428]
## Current Behavior
When the home page window size is minimized the navigation bar is getting overlapped with the logo

## Expected Behavior
The nav bat shouldn't overlap.
*Describe what you were originally trying to do and how you expected the platform to behave.*
When the window is minimized the navigation bar need to be convert into menu bar for better view

*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4): Chrome
	* Operating System and version (desktop or mobile): Windows 11
	* Link to the site where this issue occurs:https://www.omegaup.org/
	* Screenshot:
![Screenshot 2024-02-03 001359](https://github.com/omegaup/omegaup/assets/88046362/7b304727-1150-4518-895a-7fc4faa913c3)

**Comment by SubhashThenua** [comment]
Hi, @nithinkatta Can I work on this issue? Can you pls assign this to me?
Thanks!

**Comment by SubhashThenua** [comment]
Hi, @nithinkatta I have tried to reproduce the issue, But I am not able to find the same page(As you have shown above) on my local development. When I sign in Omega it shows me 

![image](https://github.com/omegaup/omegaup/assets/100484672/a70c6929-d2ad-47d7-adb5-07d4cae9a759)

This issue is on production (https://www.omegaup.org/).

Can you pls help me with how I get to the same page as you have shown above in your comment?

**Comment by pabo99** [comment]
Hi, everyone!

There's a little confusion: the issue describes a bug in https://omegaup.org, but this repository corresponds to https://omegaup.com.

Unfortunately, we don't have enough information about https://omegaup.org.

**Comment by SubhashThenua** [comment]
Ah! I see.
Sorry, I am just new to this org so I mistakenly think they are the same.
Thanks @pabo99 for your clarification.  Should we close this issue if it is not related to us?

**Comment by tvanessa** [comment]
> Ah! I see. Sorry, I am just new to this org so I mistakenly think they are the same. Thanks @pabo99 for your clarification. Should we close this issue if it is not related to us?

Post it in the correct repository: [here](https://github.com/omegaup/nonprofit-web/issues)
