### ISSUE TITLE
Permitir restringir el tamaño de un submit

### ISSUE THREAD

**Issue by kukogit** [omegaup/omegaup#743]
Hay problemas de Karel, bastante ingeniosos en su solución pero se ven afectados por que la solución se puede precargar.

**Comment by elendil326** [comment]
@lhchavez necesitamos números precisos de cuánto sí es aceptable.

**Comment by lhchavez** [comment]
Al igual que el tamaño máximo de salida, esto se puede hacer como tamaño máximo de entrada, y ponerlo como opción al crear el problema.

**Comment by pabo99** [comment]
1.- Crear campo (int) en DB (Problems)
2.- Cambiar la interfaz de crear/editar para pedirlo
3.- Poner el default de 10Kb (Máx)
