### ISSUE TITLE
[FEATURE] [Cypress] Add test for the actions "Disqualify submission" and "Requalify submission"

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7432]
As a developer I want to be sure that the actions disqualify and requalify 
a submission work properly.

![RunRequalify](https://user-images.githubusercontent.com/3230352/156894873-f167ae25-042d-4d0c-beb7-318bf1922885.gif)

**Comment by pabo99** [comment]
@ShivamJhaa, @heduenas

**Comment by SubhashThenua** [comment]
Hi, @pabo99 I am interested in working on this issue. Can I work on this issue?

**Comment by pabo99** [comment]
Sure! I suggest starting with only one issue at a time.
