### ISSUE TITLE
[FEATURE] [Cypress] Add test for the action "Rejudge submission" 

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7433]
As a developer I want to be sure that the action Rejudge a submission works properly.

**Comment by pabo99** [comment]
@ShivamJhaa @heduenas

**Comment by SubhashThenua** [comment]
Hi, @pabo99 I am interested in working on this issue. Can I work on this issue?

**Comment by SubhashThenua** [comment]
Hi, @pabo99 
we have two **Rejuge**

1)
![image](https://github.com/omegaup/omegaup/assets/100484672/b377c782-3070-4bd1-bf4c-d6ac1058a9de)
2)
![image](https://github.com/omegaup/omegaup/assets/100484672/f23c5f8e-b306-4536-aa3d-95866ce04e30)

Did I need to write the test for both?
Thanks!

**Comment by pabo99** [comment]
If you add a test for each of them, that would be great!

 Thank you so much in advance!
