### ISSUE TITLE
[BUG] Graduation date not working

### ISSUE THREAD

**Issue by antedotee** [omegaup/omegaup#7448]
## Current Behavior
*When I am trying to click on graduation year,It is just displaying `dd/mm/yy` and nothing is happening.*

## Expected Behavior

*On clicking it,it should be able to act as a date and not a text.*

*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs: https://omegaup.com/profile/#manage-schools
	* Screenshot: 
![CleanShot 2024-02-25 at 08 39 49@2x](https://github.com/omegaup/omegaup/assets/151192805/2fa4458e-1679-4216-ba8f-296853279608)

**Comment by antedotee** [comment]
Can this issue be assigned to me?

**Comment by Vijaykv5** [comment]
Hey @antedotee 
This is not a bug!
it's set like this : `if user is currently enrolled i.e, not graduated yet, they didn't have to enter the graduation date`


https://github.com/omegaup/omegaup/assets/94985341/97500faf-38b2-49ef-858a-2f43d4776cff

**Comment by antedotee** [comment]
thanks,didn't see that.
