### ISSUE TITLE
Dar la opción de crear passwords a Facebook-only o Google-only users

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#745]
Tuvimos un caso donde un concursante ya no pudo entrar a omegaUp por que su escuela decidió bloquear FB.com...

**Comment by elendil326** [comment]
@joemmanuel @lhchavez esto aún es necesario?

**Comment by lhchavez** [comment]
Únicamente hay que confirmar si ya está, pero _creemos_ que ya está.

**Comment by lhchavez** [comment]
Que siempre sí está hecho.
