### ISSUE TITLE
[BUG] content in the ephemeral graderα editor should be copied over to the modal showing when making new submission

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7450]
## Current Behavior

when trying to make a new submission, a modal appears with empty textarea -area where you type code- and language is unset even though code is already present in the editor with specified language.
## Expected Behavior

i shouldn't have to copy paste code from editor to modal, instead contents of editor should be carried over to the modal when clicking the new submission button.
## If necessary, add the following information (otherwise delete this section):
here is a video showing what i mean, i have to copy code from editor, paste it in the modal and change coding language (recorder did not show tabs being opened at the end)

https://github.com/omegaup/omegaup/assets/59091536/e83686a9-dead-4299-870e-20aae062e7a2

*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4): chrome 121
	* Operating System and version (desktop or mobile): windows 10
	* Link to the site where this issue occurs: https://omegaup.com/arena/gsoc2024/#problems/IsItATree
	* Screenshot: video above is sufficient

**Comment by HNOONa-0** [comment]
I would like this issue to be assigned to me

**Comment by Vijaykv5** [comment]
> @HNOONa-0, Thank you for your help in creating this issue and for your interest in solving it. I recommend that you resolve all the problems in the [contest](https://omegaup.com/arena/gsoc2024) (I can see you have already resolved 2 out of 3 of them), and then we can assign this issue to you!

Hi @pabo99, may I can give it a try?
Also how can we see that we have attempted the contest. I solved 3 of them but where can I see its results? Or even O solved?

**Comment by HNOONa-0** [comment]
hello @pabo99, I have finished that last problem after trying many different approaches.
I just want to add a small note, in phase 1 of [this link](https://github.com/omegaup/omegaup/wiki/Google-Summer-of-Code-2024#ideas-list), it says that solving 2 problems is enough. I suggest making small update saying that it's necessary to solve entire problemset.
I'm now ready to work on my first issue 🙏

**Comment by pabo99** [comment]
Hello @HNOONa-0!

You're right, It was necesary solving only 2 problems. I think it's okay!

Now, this issue is assigned to you!
