### ISSUE TITLE
[FEATURE] Eliminar problemas que he creado y tuvieron un error al cargar el archivo .zip

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7452]
Como un creador de problemas, quiero eliminar problemas desde la vista del listado para quitar los que se han creado con error.

## Contexto

Recientemente se reportó el issue #7449 en el cual no se podía crear un porblema debido a que el archivo .zip no se había armado correctamente. 

El detalle en este caso es que el porblema si se crea, pero al momento de ingresar a la vista de edición, marca un error `500`, así que la única forma de borrarlo sería desde la vista del listado de problemas del usuario logueado

**Comment by iqbalcodes6602** [comment]
helllo @pabo99 sir,
i have added a PR to fix this issue, can you please review it. Thank you

**Comment by pabo99** [comment]
> helllo @pabo99 sir, i have added a PR to fix this issue, can you please review it. Thank you

Sure!

Just let me ask you one question: Are you willing to participate in the GSoC 2024 program? If so, could you provide us with your username on https://omegaup.com/? This way, we can consider the PR as part of your application process.

**Comment by iqbalcodes6602** [comment]
> > helllo @pabo99 sir, i have added a PR to fix this issue, can you please review it. Thank you
> 
> Sure!
> 
> Just let me ask you one question: Are you willing to participate in the GSoC 2024 program? If so, could you provide us with your username on https://omegaup.com/? This way, we can consider the PR as part of your application process.

yes I am willing to participate in gsoc 24 and will be willing to do so, as of now i havent yet created the account, but will definitely share once i do so, in the meanwhile can u check the PR?

**Comment by pabo99** [comment]
Done!

**Comment by iqbalcodes6602** [comment]
> > helllo @pabo99 sir, i have added a PR to fix this issue, can you please review it. Thank you
> 
> Sure!
> 
> Just let me ask you one question: Are you willing to participate in the GSoC 2024 program? If so, could you provide us with your username on https://omegaup.com/? This way, we can consider the PR as part of your application process.

hello,
i have completed the phase one already now my omegaup username is - iqbal6602
also i have made a PR with all the requiremnts done with the addtional feature for extra points already, just some review is required from your end.
