### ISSUE TITLE
Miembros de grupo no pueden hacer envios

### ISSUE THREAD

**Issue by rsolisuaz** [omegaup/omegaup#7454]
## Comportamiento Esperado

Al entrar a un problema y dar click en Nuevo Envio, deberia aparecer un cuadro de dialogo donde puede ya sea copiarse el codigo o seleccionar el archivo con el codigo

## Comportamiento Actual

Redirecciona a la pagina principal de omegaup

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. Usuario ZACPS2024:E01 hace login 
2. entra por ejemplo al problema https://omegaup.com/arena/problem/Avanza-Karel-OMICHH/  
3. da click en el boton de nuevo envio y en vez de abrirse un cuadro de dialogo para poder poner el codigo , redirecciona a https://omegaup.com/
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*
Soy actualmente el delegado de Zacatecas para la OMI y este problema me impide que mis estudiantes puedan usar las cuentas que les genero, de hecho el año pasado me pasó algo similar, aunque el año pasado los primeros meses estuvieron funcionando las cuentas que cree y a medio ciclo de entrenamiento ya no pudieron hacer envios. 

*Proveer contexto nos ayuda a encontrar la solución adecuada*
Estoy suponiendo que los dos puntos que se generan como parte del nombre de usuario son los causantes del problema, pero no tengo la certeza de ello, si entro con un usuario creado de manera norma, si me deja hacer envios, si entro con un usuario creado mediante la opcion de crear identidades en un grupo, no puedo hacer envios.
## Tu ambiente

ESTO SUCEDE EN TODOS TANTO EN CHROME COMO EN FIREFOX

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/problem/Avanza-Karel-OMICHH/
* Errores en la consola: []
* Captura de pantalla:

**Comment by pabo99** [comment]
Hola, acabo de hacer una prueba con mi usuario y funciona correctamente:

![ShowRunPopUp](https://github.com/omegaup/omegaup/assets/3230352/c149a2cd-2774-456c-833e-81faf25b33e5)

¿Sábes si tienen alguna particularidad los usuarios que presentan este problema? Como por ejemplo si son identidades creadas masivamente o osuarios que fueron agregados a un grupo. Entre más pistas tengamos, más fácil será dar con el problema y más rápido lo podremos solucionar

**Comment by rsolisuaz** [comment]
Hola, tengo el problema con identidades creadas de manera masiva, subiendo un archivo CSV a un grupo, el proceso que hago (y de hecho he hecho por varios años es el siguiente):1. Creo un nuevo grupo en https://omegaup.com/group/new/(el grupo que cree mas recientemente se llama )
2. Seleccionando el grupo, me voy a la opcion de Crear identidades en https://omegaup.com/group/ZACPS2024/edit/#identities , donde proporciono un archivo CSV con el formato solicitado (para este ultimo grupo, solo subi un usuario para hacer una prueba, que resulta ser el usuario ZACPS2024:E01) 
3. Se crean los usuarios, y pueden entrar, pero no pueden hacer envios, si gusta puede probar con el usuario que cree hace un par de horas para que compruebe lo que pasa, el usuario es ZACPS2024:E01  y la contraseña es vpcANmMJ  






===================================================== 
Dr. Roberto Solís Robles Profesor InvestigadorResponsable del Programa de Ingeniería en Computación
=====================================================   "Es mucho mejor intentar y fallar que no hacer nada por miedo al fracaso"

  

    On Wednesday, February 28, 2024 at 11:02:50 AM CST, Juan Pablo Gómez Aguilar ***@***.***> wrote:  
 
 


Hola, acabo de hacer una prueba con mi usuario y funciona correctamente:

ShowRunPopUp.gif (view on web)

¿Sábes si tienen alguna particularidad los usuarios que presentan este problema? Como por ejemplo si son identidades creadas masivamente o osuarios que fueron agregados a un grupo. Entre más pistas tengamos, más fácil será dar con el problema y más rápido lo podremos solucionar

**Comment by rsolisuaz** [comment]
Reitero que el problema se da solo con usuarios creados de manera masiva usando un CSV en la sección de Crear Identidades en un grupo, con un usuario normal no se presenta ese problema. Pueden ver el comportamiento en el siguiente video

https://github.com/omegaup/omegaup/assets/6720669/e873f0f6-38a2-4230-9d0d-97e1e05a5de3

**Comment by pabo99** [comment]
Perfecto, con esta información nos podemos enfocar en usuarios creados de manera masiva.

Gracias por tomarte el tiempo de generar el video!
