### ISSUE TITLE
Cuando un usuario FB/GOOG hace login nativo, el msg dice que el usuario está desactivado

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#746]
Debería decir que el usuario no tiene password... el msg de usuario desactivado era para los logins nativos.

**Comment by elendil326** [comment]
@joemmanuel @lhchavez aún necesario?

**Comment by pabo99** [comment]
Aún se reproduce?

**Comment by lhchavez** [comment]
Esto ya no repro. @pabo99 acaba de probarlo :D
