### ISSUE TITLE
Problem zip file input can accept any file

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7462]
## Current Behavior

When we try to upload zip file of the problem, file manager opens and we can select any type of file

## Expected Behavior

Only zip files must be accepted as input.

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1.  Login into omegaup.com
	2.  Go to Problems-> Create Problem
	3.  Click on Attack zip file input
	4. See the error

*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

**Comment by MayaSatishRao** [comment]
@pabo99 Can you assign this issue to me?

**Comment by pabo99** [comment]
Sure!

Just one quick question: Could you please provide us with your username on https://omegaup.com/? This will allow us to consider the pull request as part of your application process for the GSoC 2024 program

**Comment by MayaSatishRao** [comment]
Username is Maya25 on Omegaup. I haven't taken the contest yet.

**Comment by MayaSatishRao** [comment]
@pabo99 I have made the PR. Please review it.
