### ISSUE TITLE
No error type if school not selected while creating a new course

### ISSUE THREAD

**Issue by iqbalcodes6602** [omegaup/omegaup#7470]
## Current Behavior

I user just types a school name and doesn't select the school from the drop down (selecting from dropdown would make it a tag else it would just be plain text) then its gives error, but in the frontend 

![image](https://github.com/omegaup/omegaup/assets/111554475/5a1e7887-c242-468d-b26a-9b4a6377f55a)

the console log is-
ui.ts:120 TypeError: Cannot read properties of null (reading 'key')
    at Promise.then.request.school_id (new.ts:52:1)
    at new Promise (<anonymous>)
    at submit (new.ts:51:1)
    at invokeWithErrorHandling (vue.common.dev.js:1859:1)
    at VueComponent.invoker (vue.common.dev.js:2184:1)
    at invokeWithErrorHandling (vue.common.dev.js:1859:1)
    at Vue.$emit (vue.common.dev.js:3885:1)
    at VueComponent.onSubmit (Form.vue:153:1)
    at submit (Form.vue:22:1)
    at invokeWithErrorHandling (vue.common.dev.js:1859:1)
apiError @ ui.ts:120
Promise.catch (async)
submit @ new.ts:80
invokeWithErrorHandling @ vue.common.dev.js:1859
invoker @ vue.common.dev.js:2184
invokeWithErrorHandling @ vue.common.dev.js:1859
Vue.$emit @ vue.common.dev.js:3885
onSubmit @ Form.vue:153
submit @ Form.vue:22
invokeWithErrorHandling @ vue.common.dev.js:1859
invoker @ vue.common.dev.js:2184
original._wrapper @ vue.common.dev.js:7543
Show 7 more frames
Show less
new/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received 

## Expected Behavior

it should tell exactly what the error is instead of just saying error

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. click on create a new contest from the navbar
	2. fill up all details
	3. in school field type any school just dont select the drop down sugegstion
	4. click "schedule course"
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

**Comment by Vijaykv5** [comment]
> ```
> 1. click on create a new contest from the navbar
> 2. fill up all details
> 3. in school field type any school just dont select the drop down sugegstion
> 4. click "schedule contest"
> ```
> 



@iqbalcodes6602 The problem seems on course, not on contest. please update it.
Also are you taking over this issue, or else I can work on it.
Thanks!

**Comment by Vijaykv5** [comment]
I'm getting this while reproducing the issue.
<img width="1183" alt="Screenshot 2024-03-09 at 12 04 45 AM" src="https://github.com/omegaup/omegaup/assets/94985341/edd33dbb-713c-40dd-9166-1d528a4c9eb6">

**Comment by iqbalcodes6602** [comment]
> I'm getting this while reproducing the issue. <img alt="Screenshot 2024-03-09 at 12 04 45 AM" width="1183" src="https://private-user-images.githubusercontent.com/94985341/311332597-edd33dbb-713c-40dd-9166-1d528a4c9eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjMyMTgsIm5iZiI6MTcwOTkyMjkxOCwicGF0aCI6Ii85NDk4NTM0MS8zMTEzMzI1OTctZWRkMzNkYmItNzEzYy00MGRkLTkxNjYtMWQ1MjhhNGM5ZWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE4MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYTBhNzY5NDRkY2UxNjQ3MjE1MmJlYTEwMTJhZGEwYzYxYzE4MGMxMzFjZjEyMDllYTFkYzBjN2U0NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQU3gVC8-7JeT5kxw5Q1Pv6fF9bqnKQ0_XJJcCG2vfU">

ya i am trying to solve this as well basically its giving error but not telling what the error actually is
