### ISSUE TITLE
[BUG] UI Enhancement : Add Space between Icons

### ISSUE THREAD

**Issue by Vijaykv5** [omegaup/omegaup#7471]
## Current Behavior
The Date Icons and the no of people's (group's icon) are conjusted, disturbing the UI experiance

## Expected Behavior

Instead we can have a `4px` on distance of x axis on both the date as well as group icon

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. click in competitions from navbar
	2. select see contest
	3. now you'll notice the bug here
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4): Chrome
	* Operating System and version (desktop or mobile): Mac. OS
	* Link to the site where this issue occurs: https://omegaup.com/arena/
	* Screenshot: 
<img width="989" alt="Screenshot 2024-03-09 at 12 11 33 AM" src="https://github.com/omegaup/omegaup/assets/94985341/a8ff2a5a-0c87-41d5-a8f3-279ca965c3be">

**Comment by Vijaykv5** [comment]
I tried to reproduce locally but I figured out that this issue is only in production.
It's working fine locally!

<img width="1299" alt="Screenshot 2024-03-09 at 5 26 18 PM" src="https://github.com/omegaup/omegaup/assets/94985341/1fd1854b-f95d-413d-a455-020475430bfc">

**Comment by RingoTC** [comment]
I can do this.

**Comment by pabo99** [comment]
> I can do this.

@RingoTC: Assigned to you!
