### ISSUE TITLE
Add background colors to each of the verdicts [WA,TLE,MLE]

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7472]
## Current Behavior

The verdicts [WA,TLE,MLE] appear just as text.

## Expected Behavior

I suggest we add a color to each of the verdicts like in the picture below, to help with readability:
![verdict-colors](https://github.com/omegaup/omegaup/assets/59091536/1d968178-548d-4def-9fa3-11e092cdee16)

**Comment by HNOONa-0** [comment]
I have already made changes locally and I'm ready to push them

**Comment by pabo99** [comment]
Go ahead!
