### ISSUE TITLE
[FEATURE] Rediseño/Modernización de la UX de omegaUp

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#749]

**Comment by npave** [comment]
Trabajo en una propuesta.

**Comment by elendil326** [comment]
@npave @lhchavez quizá sea mejor romper esto en features por vista/módulo/caso de usuario, dependiendo de la propuesta. También, no se en que proyecto poner esto. Features separados podrían ir en diferentes proyectos.

**Comment by npave** [comment]
Voy a partir este feature en pedacitos.
