### ISSUE TITLE
[BUG] Contest start date validation failure when updating contest

### ISSUE THREAD

**Issue by Franco1010** [omegaup/omegaup#7490]
## Current Behavior
It's not possible to update any contest details/settings once the contest start time has passed. So, in order to do any updates you also need to update start time to your current local time, and you can't update start time if at least one participants have submissions

## Expected Behavior
All settings should be open to updates even if the contest has started, such things like score visibility, end time, name, description, are things that we usually change after the contest has began

## Screenshot
<img width="1209" alt="Screenshot 2024-03-16 at 12 59 13 p m" src="https://github.com/omegaup/omegaup/assets/28017456/6f87c608-cc78-43e7-a97d-02bd3e4e9dda">

## Update
`<input data-v-271c8c32="" required="required" size="16" type="datetime-local" min="2024-03-16T12:53" class="form-control" data-start-date="">`
This seems to be an error on front-end validator, when changing min value to an older date, we can do all updates witihout problem

## Expected Solution
Remove minimum value validator for start date when updating a contest

## Related PR
#7411

**Comment by Vijaykv5** [comment]
I would love to work on this issue

**Comment by heduenas** [comment]
thank you @Vijaykv5 for the interest, but this issue is kind of urgent and not the best fit for a newcomer.
