### ISSUE TITLE
[BUG] The editor does not load properly because of "reading properties of null" exception.

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7493]
## Current Behavior
Sometimes when loading a problem, the editor bugs out.

![editor-error](https://github.com/omegaup/omegaup/assets/59091536/e803f548-f0a3-4b09-adb2-1765e11612e3)

## Expected Behavior

The editor should load normally at all times without bugging.

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. go to any problem
	2. refresh a couple of times and this bug occurs
	3. 
	4. 
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

**Comment by RingoTC** [comment]
I can't reproduce this problem, but it seems like due to the network.
