### ISSUE TITLE
[FEATURE - Arena UX] Mostrar todas las opciones de editar concurso (regresar los tabs como estaban anteriormente) 

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7495]
It should show like in Courses:

![image](https://github.com/omegaup/omegaup/assets/3230352/ae8b33ce-3333-4d2d-bde7-0968ed3b6c3d)

**Comment by Aritra8438** [comment]
Hi, can you assign this issue to me?

**Comment by pabo99** [comment]
> Hi, can you assign this issue to me?

Done!

**Comment by Aritra8438** [comment]
Hi @pabo99,

<img width="953" alt="image" src="https://github.com/omegaup/omegaup/assets/64671908/4ff5e380-c827-4dc3-98be-29bfd9559a57">

This is the current behaviour in the dev setup which is very (if not exactly) similar to the image in the issue.

**Comment by Aritra8438** [comment]
Oh, sorry I got the issue wrong.
NVM, working on it.

**Comment by pabo99** [comment]
You're correct; that's the Course Edit view. Therefore, you'll need to adjust the Contest Edit view, which currently appears as follows:

![image](https://github.com/omegaup/omegaup/assets/3230352/4b1362ad-f033-46a6-99f0-3c74e1602dc3)

As you can see, there are more tabs for the contest (which was the initial intention behind using a dropdown). You could slightly reduce the size by modifying the following strings:

- Edit contest -> Edit
- Add problem -> Problems
- Add contestant -> Contestants
- Add admin -> Admins

**Comment by Aritra8438** [comment]
Hey, @pabo99.

![Uploading image.png…]()

PTAL!

**Comment by pabo99** [comment]
> Hey, @pabo99.
> 
> <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/64671908/316181533-cf25a08e-af28-4347-8d28-35a823d7a199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzAzNDUsIm5iZiI6MTcxMTE3MDA0NSwicGF0aCI6Ii82NDY3MTkwOC8zMTYxODE1MzMtY2YyNWEwOGUtYWYyOC00MzQ3LThkMjgtMzVhODIzZDdhMTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MTcyMjIyYmFkZGYzNmFmYTBjY2Q1NzE1ODE1NjkyYjU0Mjk1OWZiMzI3YTJkODVmYjVmMWE5YjQ4ZGU1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UrnK3k7T1Z3-sCT3z6GWTH8GR96VTT5ktsd4J4zr54">
> PTAL!

It looks great! 

But I can't see any related PR. Have you had trouble creating it?

**Comment by Aritra8438** [comment]
Hi @pabo99, I created a draft PR. I was trying to change the words in different languages, I will probably be done with it by afternoon.
