### ISSUE TITLE
[BUG] El paginador de Lista de concursos no se actualiza al aplicar filtros

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7497]
## Current Behavior

Al aplicar algún filtro en la vista de lista de concursos, el paginador no se actualiza
correctamente. Además de que al seleccionar una página distinta, se reestablece
el filtro

## Expected Behavior

Al aplicar un filtro se tendría que actualizar el paginador

## If necessary, add the following information (otherwise delete this section):

![ContestListFiltersAndPaginatorFail](https://github.com/omegaup/omegaup/assets/3230352/49717b05-722a-4bfb-95d2-41646abb3d60)

**Comment by alemanjosh7** [comment]
Could this be assigned to me please?

**Comment by pabo99** [comment]
Este issue aún no se corrige hasta que se apliquen todos los cambios en la nueva versión del componente `ContestList`

**Comment by pabo99** [comment]
Aún faltan un par de cambios, así que se reabre este issue
