### ISSUE TITLE
[FEATURE] Agrupar usuarios y poder agregarlos a concursos en grupo

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#750]
@joemmanuel incluirá más detalles del diseño/usabilidad necesaria para soportar esto.

**Comment by joemmanuel** [comment]
https://omegaup.com/preguntas/674/insertar-varios-usuarios-a-un-concurso

**Comment by elendil326** [comment]
@joemmanuel @lhchavez aún necesario?

**Comment by pabloaguilar** [comment]
Esto ya se puede agregando grupos de participantes
