### ISSUE TITLE
Lista de concursos: mostrar # de días cuando el concurso dura más de 24h

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#751]
@joemmanuel incluirá más detalles de repro steps.

**Comment by Briaares** [comment]
Yo lo hago :P

**Comment by lhchavez** [comment]
Este bug es que en https://omegaup.com/arena/ la columna de duración tiene valores ridículos como `1641h 00m`, en vez de `68d 9h 00m`

**Comment by pabloaguilar** [comment]
Asignado a miguelromero

**Comment by elendil326** [comment]
@joemmanuel @lhchavez still reproes?

**Comment by pabloaguilar** [comment]
Si
![long contests](https://user-images.githubusercontent.com/189223/27015957-cdd6f65e-4ece-11e7-8e72-4fd90341ed56.png)

**Comment by raks097** [comment]
I'd like to work on this issue.

**Comment by lhchavez** [comment]
@raks097 are you working on this? I just assigned it to you. Let me know if you're no longer working on it to un-assign it.

**Comment by dgarvit** [comment]
I would like to work upon this.
