### ISSUE TITLE
[BUG] The most recent notifications should be displayed at the top of the list

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7512]
## Current Behavior

When viewing the list of notifications, I notice that the latest ones are displayed at the top.

![image](https://github.com/omegaup/omegaup/assets/3230352/4a671f3f-685d-4925-8678-3339c77d0f94)

## Expected Behavior

The behavior should be the opposite: Display the most recent ones at the top.

**Comment by Ashish-003** [comment]
@pabo99 I can start with this

**Comment by pabo99** [comment]
> @pabo99 I can start with this

Excellent. The issue is all yours!
