### ISSUE TITLE
[FEATURE] The notifications should include the time when they were created

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7513]
Currently, we are displaying the date, but showing the time will provide more information to users.

![image](https://github.com/omegaup/omegaup/assets/3230352/4a671f3f-685d-4925-8678-3339c77d0f94)

**Comment by antedotee** [comment]
I would love to give this a try.

**Comment by pabo99** [comment]
> I would love to give this a try.

Done!

**Comment by Ashish-003** [comment]
I accidentaly made this feature while testing for other Issue

**Comment by antedotee** [comment]
I unassigned it.Go ahead.
