### ISSUE TITLE
[FEATURE] For contests with admission mode set to: "Registration/open" users should be notified at every step of the proccess

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7514]
For the following processes, all involved users should receive a notification:

- Admin creates a contest and updates the admission mode to 'Registration/open':
![AdmissionModeRegistration](https://github.com/omegaup/omegaup/assets/3230352/388f163c-52f7-49f0-9f0f-0e16a9bf288d)
(No notification is needed here.)

- Contestant requests access to the contest:
![UserRequesAccessToContest](https://github.com/omegaup/omegaup/assets/3230352/ccc76923-fc56-42ca-9b47-e5fe87ec61d3)
(admins should receive a notification)

- Admins accept/reject the user request:
![AdminRejectsUserRequest](https://github.com/omegaup/omegaup/assets/3230352/c5e03018-76bd-49a5-bce8-e6a6af9429f3)
(The contestant should receive a notification with the request response).

**Comment by iqbalcodes6602** [comment]
hello @pabo99 since nobody is taking this up can u assign it to me?

**Comment by pabo99** [comment]
> hello @pabo99 since nobody is taking this up can u assign it to me?

Assigned to you!

**Comment by Aritra8438** [comment]
Can you assign the second part to me @pabo99?

> * Admins accept/reject the user request:
>   ![AdminRejectsUserRequest](https://private-user-images.githubusercontent.com/3230352/316250761-c5e03018-76bd-49a5-bce8-e6a6af9429f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDQ4OTMsIm5iZiI6MTcxMjgwNDU5MywicGF0aCI6Ii8zMjMwMzUyLzMxNjI1MDc2MS1jNWUwMzAxOC03NmJkLTQ5YTUtYmNlOC1lNmE2YWY5NDI5ZjMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDMwMzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTcwNzI4NjA3ODRlMzg0ZmQ3OTI3ZTZhN2NiYmVlMmRjYTJkYTYyZDg4NjE0N2RlNmY1NzdhYWFiNTY4MzkzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EroVBozQAEbM0VEO3sU6uoyCDcEQMNPwZn7hzNWj_Og)
>   (The contestant should receive a notification with the request response).

As I already modified the UI to allow additional feedback on contest registration rejection.
