### ISSUE TITLE
Cannot submit rating in rate problem popup

### ISSUE THREAD

**Issue by MayaSatishRao** [omegaup/omegaup#7515]
## Current Behavior

Cannot submit the problem when the rating for either quality was very bad or difficulty was very easy

## Expected Behavior

Must be able to submit the problem when the rating for either quality was very bad or difficulty was very easy

*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1.  Solve any problem on Omegaup
	2. Click on Rate problem
	3.  Select quality as very bad and difficulty as very easy
	4. See the error
	
*Screenshot:*

![Screenshot 2024-03-24 021432](https://github.com/omegaup/omegaup/assets/67920373/6b626a04-f43e-4244-ab70-11b548a86f07)

**Comment by MayaSatishRao** [comment]
@pabo99 Can you assign this issue to me?

**Comment by pabo99** [comment]
> @pabo99 Can you assign this issue to me?

Done
