### ISSUE TITLE
Lista de concursos: invertir los links de [Practice] y [Concurso]

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#752]
Cuando un concurso ha terminado y haces click en el título de concurso te lleva a los resultados mientras que el modo Práctica está en la derecha - IMHO el objetivo principal es que los usuarios practiquen con concursos pasados. Propongo invertir los links: que el título del concurso te lleve al modo práctica y que el link de [Practice] se convierta en [Resultados].

**Comment by joemmanuel** [comment]
@lhchavez @alanboy qué opinan de este issue?

**Comment by joemmanuel** [comment]
@lhchavez @alanboy @rcxr @npave reviviendo este issue, qué opinan?

**Comment by alanboy** [comment]
concuerdo que si se puede mejorar, pero cambiar los links puede ser confuso, como vez algo mas explicito:

    titulo del concurso [resultados] [practicar]

**Comment by lhchavez** [comment]
defer to @npave.

**Comment by rcxr** [comment]
De acuerdo con @alanboy de que será confuso, si cambiamos los links debiera ser suficientemente diferente para hacer explícito que algo cambió.

**Comment by npave** [comment]
Apoyo la idea de Alan,  se vería algo así
![pastcontest](https://cloud.githubusercontent.com/assets/940007/26385434/92cff6f2-3ff4-11e7-98a7-8e2c1fe52050.png)

Ahorita tanto el titulo del problema como "Practicar" te llevan a donde mismo, a donde te debería llevar resultados?

**Comment by lhchavez** [comment]
Supongo que al scoreboard público.

**Comment by lhchavez** [comment]
acá está el código que genera eso: https://github.com/omegaup/omegaup/blob/master/frontend/templates/arena.contest_list.tpl

y el link estaría en https://omegaup.com/arena/

**Comment by pabo99** [comment]
Excelente, cualquier cosa en la que te pueda apoyar, me avisas.

**Comment by Mart-97** [comment]
Hola, estoy teniendo un problema al querer interactuar con mi entorno local, probé en meterme a cualquiera de las secciones pero sale este error
 ¿Alguien sabe que podría ser ? 
![image](https://user-images.githubusercontent.com/12377916/48297010-e090ff80-e46c-11e8-9dd7-9217307d9be0.png)

**Comment by lhchavez** [comment]
parece que hay que actualizar los contenidos de la VM. primero intenta correr `./stuff/bootstrap-environment.py --purge` (eso limpia la DB y la pone en un estado sano) y si eso no funciona, `vagrant provision` desde afuera de la VM (eso actualiza TODO, e internamente corre el primer comando).

**Comment by Mart-97** [comment]
Ya puedo navegar entre las secciones, pero, ahora me marca error al hacer el **yarn run dev** :(  [
![screenshot from 2018-11-10 11-13-09](https://user-images.githubusercontent.com/12377916/48303575-bf1a2d00-e4d9-11e8-80f4-baf7945c20e5.png)
](url)

**Comment by Mart-97** [comment]
Hola, una pregunta, el link que irá en resultados, sería el de esta vista? 
![screenshot from 2018-11-17 17-28-15](https://user-images.githubusercontent.com/12377916/48666374-39285400-ea8e-11e8-905d-1d9a3fd59e2b.png)

**Comment by pabo99** [comment]
Es correcto, sólo revisa que sea la `url` correcta, ¿Cómo saber eso? Existen dos `url's` para scoreboards. Puedes revisar en `/contest/mine/` la `url` que se genera para el público: 

![2018-11-17](https://user-images.githubusercontent.com/3230352/48666549-f3698c80-ea89-11e8-9707-0206a976405c.png)

**Comment by Mart-97** [comment]
Hola, he checado, pero no encuentro como obtener el link del score público, revisé en contest/mine, pero me parece que eso ya está vueficado y me parece que lo ocupa este componente [contestlist](https://github.com/omegaup/omegaup/blob/master/frontend/www/js/omegaup/components/contest/ContestList.vue), y desde ahí obtienen la url de score público , y la parte de **Arena**, aún no está en Vue, y no logro ver como obtener esa url y estaba pensando en mejor pasarlo , antes de hacer este cambio. Ya que creo que así podría posteriormente obtener esa url y colocarla en el cambio de esta vista.

En caso  que me den luz verde para vueficar, lo coloco como otro issue, no ?

**Comment by lhchavez** [comment]
siempre tienes luz verde para vueificar :D

**Comment by Mart-97** [comment]
Hola, me disculpo por retomar este issue hasta ahora. Ahora ha cambiado un poco la interfaz, ya que ahora está la modalidad virtual,entonces quisiera saber si para añadir la liga de resultados estaría bien solo añadir una columna más para colocar el link que lleve al scoreboard público?

![image](https://user-images.githubusercontent.com/12377916/58674543-efaaa280-8315-11e9-9c98-17be87eb8d8c.png)
