### ISSUE TITLE
[BUG] ephemeral.js is not reflecting changes after successful compilation

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7524]
## Current Behavior

Making any change to `www/js/omegaup/grader/ephemeral.js` takes a long time to be reflected. Only files in the `grader` directory seem to have this issue, below in the video I tried to log a line, and after successful compilation, no lines were logged! (video was edited because compilation took too long)

https://github.com/omegaup/omegaup/assets/59091536/cfcdd230-c7de-46c5-8077-2cc64ead0bd1

## Expected Behavior

The changes should be reflected immediately

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. go `ephemeral.js` and make any local changes.
	2. save and recompile. find out that changes did not take place.

**Comment by iqbalcodes6602** [comment]
We need to hard refresh the Brower for seeing the changes, this means re loading the page without cache, in chrome it can be down by pressing ctrl + f5 Or ctrl+ shift + r

**Comment by RingoTC** [comment]
I will try to solve this problem.

**Comment by HNOONa-0** [comment]
> I will try to solve this problem.

Thanks but I'm trying to solve it at the moment.
