### ISSUE TITLE
[BUG] User is not informed about the error while creating course

### ISSUE THREAD

**Issue by Ashish-003** [omegaup/omegaup#7528]
## Current Behavior
![image](https://github.com/omegaup/omegaup/assets/73078401/4d156cf8-8ac7-4c4c-87ac-5acd1b85bf38)

Error is not described to the user if no school is selected

## Expected Behavior

Instead each error should be shown to the user. In this Case It should quote "Please select a school"

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. Enter Create Courses and add all the required  fields except school

*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

**Comment by Ashish-003** [comment]
@pabo99 Should this be an error or should it accept null

**Comment by Ashish-003** [comment]
Added a PR if school==NULL is the way to go

**Comment by Aritra8438** [comment]
@pabo99, for every error, do we not show it in the format `parameter name: the reason for the error`? Then why is this an exception?

**Comment by iqbalcodes6602** [comment]
Hello @Ashish-003 , there is one more problem when u dont select the issue from drop down it also gives error but doesn't tell which error is it but i hve already fixed it including box of the errors

the issue has already been raised and the pr has already been made for this just waiting to get it merged, 
#7474 is the pr number for this,

**Comment by Ashish-003** [comment]
Oh Cool.
Closing this issue then
