### ISSUE TITLE
Las pestañas de editar concurso se despliegan mal en español

### ISSUE THREAD

**Issue by mikebsg01** [omegaup/omegaup#753]
Desborde de las pestañas en http://omegaup.com/problem/[problem]/edit/

![omegaup_02](https://cloud.githubusercontent.com/assets/5126150/13000967/81b0978e-d126-11e5-9ed0-e2aa043364e2.png)

**Comment by mikebsg01** [comment]
Ya quedó arreglado, incluso con un nuevo diseño.
![screenshot_26](https://cloud.githubusercontent.com/assets/5126150/13384267/9957f306-de59-11e5-8f18-8de3fa069e5e.png)

**Comment by pabloaguilar** [comment]
Fixed via #758
