### ISSUE TITLE
[BUG] Active tab gets changed when refreshed - Contest edit page

### ISSUE THREAD

**Issue by Aritra8438** [omegaup/omegaup#7530]
## Current Behavior

As a result of PR #7505, a new bug was introduced where the active tab of the contest edit page gets changed when refreshed.

Please refer to [this](https://github.com/omegaup/omegaup/pull/7527#pullrequestreview-1959453919) comment of @pabo99. 

## Expected Behavior

When the page is refreshed, the selected tab should remain active, similar to the behaviour on the CourseEdit page.

##  Steps to reproduce this bug.  
  <video src="https://private-user-images.githubusercontent.com/64671908/316864624-76e0a85d-fb60-4f13-863b-52491e226acb.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTk1MzIsIm5iZiI6MTcxMTQ1OTIzMiwicGF0aCI6Ii82NDY3MTkwOC8zMTY4NjQ2MjQtNzZlMGE4NWQtZmI2MC00ZjEzLTg2M2ItNTI0OTFlMjI2YWNiLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzMjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYWRkNDcxY2NlNzdkMWU1ZjJhZWVkMzZjY2JkYzA4NWVkZThjNGEzMDc4ZTQ5N2YyOGU4NTU2Zjk2OTc3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKZmvELY4sMBydfvBicYM8Jj_P5rz2A3YbT0tf-YzqQ" data-canonical-src="https://private-user-images.githubusercontent.com/64671908/316864624-76e0a85d-fb60-4f13-863b-52491e226acb.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTk1MzIsIm5iZiI6MTcxMTQ1OTIzMiwicGF0aCI6Ii82NDY3MTkwOC8zMTY4NjQ2MjQtNzZlMGE4NWQtZmI2MC00ZjEzLTg2M2ItNTI0OTFlMjI2YWNiLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzMjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYWRkNDcxY2NlNzdkMWU1ZjJhZWVkMzZjY2JkYzA4NWVkZThjNGEzMDc4ZTQ5N2YyOGU4NTU2Zjk2OTc3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKZmvELY4sMBydfvBicYM8Jj_P5rz2A3YbT0tf-YzqQ" controls="controls" muted="muted" class="d-block rounded-bottom-2 border-top width-fit" style="max-height:640px; min-height: 200px">

  </video>

**Comment by Aritra8438** [comment]
@pabo99, can you assign this to me?

**Comment by Gajendrasuman** [comment]
You can create a session or for this. and in the session provide the link of the current page with #currentTab to open when page is refreshed. And when page opened up first time create the session once the session is created update it whenever the user select the section like editProblem or editStatement... . And You must have to check for the active session first when ever page starts loading. if the session is not present then create the new one. With this approach Current Tab will not  be changed even after page gets refreshed
