### ISSUE TITLE
[BUG] Only One Page of latest submissions are shown

### ISSUE THREAD

**Issue by Ashish-003** [omegaup/omegaup#7532]
## Current Behavior
Only first 100 submissions are shown on View Problem Submssions page
![image](https://github.com/omegaup/omegaup/assets/73078401/8da5c8fc-9606-4bb4-a49f-376b26fb0270)

## Expected Behavior

Should contain more pages for submissions in last 24 hours.

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. 
	2. 
	3. 
	4. 
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:

**Comment by Ashish-003** [comment]
@pabo99 It would be better to go with pagination right rather than returning a list of submissions

**Comment by arnabnath01** [comment]
I think using infinity scrolling could resolve this.

**Comment by pabo99** [comment]
+1 to the infinity scroll

**Comment by aditi-star123** [comment]
@pabo99 please assign me this issue
