### ISSUE TITLE
[FEATURE] Unify the width of both buttons in Past contest list

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7533]
The width of the buttons in Past Contest List are not unified:

![image](https://github.com/omegaup/omegaup/assets/3230352/8ca0a25e-14ee-492d-b500-8b4d1d40938f)

Maybe it should be necessary to move the f"number of contestants" field  to another position in order to allow aligning the buttons.

**Comment by Aritra8438** [comment]
Hi @pabo99, can you assign me this issue?

**Comment by pabo99** [comment]
I've assigned another issue to you. Could you try working on that one instead and leave this one for other contributors?

**Comment by pabo99** [comment]
@23danielsuh Do you want to try to resolve this issue?

**Comment by Aritra8438** [comment]
> I've assigned another issue to you. Could you try working on that one instead and leave this one for other contributors?
> 
> 

Sureee!

**Comment by aditi-star123** [comment]
Hi can you also assign any issue to me I am new to gsco and want to contribute in it.@pabo99

**Comment by pabo99** [comment]
Done!

> Hi can you also assign any issue to me I am new to gsco and want to contribute in it.@pabo99

**Comment by thenikhilsharma** [comment]
hi @pabo99 I'm a new contributor and I want to contribute to this project so can you please assign me this issue

**Comment by pabo99** [comment]
> hi @pabo99 I'm a new contributor and I want to contribute to this project so can you please assign me this issue

Done!

**Comment by DhruvLamba** [comment]
Hi @pabo99 can you assign me this issue, I am a beginner
