### ISSUE TITLE
[BUG] Google login button not working

### ISSUE THREAD

**Issue by F4bbi** [omegaup/omegaup#7534]
## Current Behavior
When I click on the Google login button, a new window opens, but it remains blank indefinitely, preventing from logging in with Google. I have attempted this on multiple devices, but the issue persists.

![image](https://github.com/omegaup/omegaup/assets/75183735/91709dfd-6695-4ed5-8cee-bb58c88a2db6)

**Comment by Aritra8438** [comment]
Uploading login-omegaup.mp4…

Hi @F4bbi, it's working on my end. Can you please check again? Can you use Google authentication on other sites?

**Comment by Aritra8438** [comment]
https://github.com/omegaup/omegaup/assets/64671908/a964bdbc-d408-4e98-a951-4dbf5f57fff8

Hi @F4bbi, it's working on my end. Can you please check again? Can you use Google authentication on other sites?

**Comment by F4bbi** [comment]
I've done some investigation and I discovered that the issue only occurs on Google and on my most frequently used devices.
Curiosly, it works fine on other browsers or devices that I don't use. By the way, Google authentication works correctly on other websites. For now, I would say to keep the issue open for a while to see if anyone else encounters this problem.

**Comment by tvanessa** [comment]
Not able to reproduce
