### ISSUE TITLE
[BUG] Mixed Warning Content from run/submit button

### ISSUE THREAD

**Issue by Ethanneece** [omegaup/omegaup#7542]
## Current Behavior
Website gives warnings about mixed content warning when loaded in. 

*Describe what happened instead of what was expected.*

When the SVG spinner is loaded for the run and submit button, it is loaded over http which causes a chrome to give a mixed content warning. 

![image](https://github.com/omegaup/omegaup/assets/34079301/d96d84af-07d2-4617-8c69-416f34f7b5c8)

## Expected Behavior

Website gives no warning when loaded.

**Comment by heduenas** [comment]
This issue doesn't repro anymore. Thank you @Ethanneece !
