### ISSUE TITLE
El texto en el Rank Top5 del index se desborda fuera de la caja

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#755]

**Comment by mikebsg01** [comment]
Ya quedo arreglado en mi último commit :smiley:  :+1:

**Comment by joemmanuel** [comment]
YEAH!

On Sun, Feb 28, 2016 at 6:24 PM, Michael Serrato <notifications@github.com>
wrote:

> Ya quedo arreglado en mi último commit [image: :smiley:] [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/755#issuecomment-190004528>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by samdsmx** [comment]
Y luego?? Abra que cerrar el  issue

**Comment by lhchavez** [comment]
Ah para cerrar un issue desde el commit hay que ponerle "Fixed #755" en la descripción del Pull Request. Así cuando se hace merge se cierra solito.
