### ISSUE TITLE
[BUG] Print contest not working / Imprimir concurso no funciona

### ISSUE THREAD

**Issue by 5an7y** [omegaup/omegaup#7552]
## Current Behavior

When I click the "print" button in one of my contest it doesn't show me the printable version of the contest. It just shows me a blank page.

Cuando presiono al boton de imprimir en uno de mis concurso no me muestra la version imprimible del concurso. Unicamente me muestra una pagina en blanco.

<img width="400" alt="image" src="https://github.com/omegaup/omegaup/assets/34700620/8e498941-81ac-4b58-bce2-40b3e7fbea3c">
<img width="400" alt="image" src="https://github.com/omegaup/omegaup/assets/34700620/eaeb24c1-3434-4133-89e5-2fb0aa5d35f4">

## Expected Behavior

The printable version of the contest.
Una version imprimible del concurso.

*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. Create a contest and add some problem (maybe add ones that are in private)
	2. In "Your constest" section click the print button on the contest you just created.
	1. Crea un concurso y agrega algunos problema (quiza agrega algunos que esten en privado)
	2.  En la pestaña de "Tus concurso" haz click en el boton de impresora del concurso que acabas de crear.

**Comment by Aritra8438** [comment]
I can reproduce this issue.
I will be working on fixing this.
