### ISSUE TITLE
[BUG] No se está preseleccionando correctamente el lenguaje por omisión

### ISSUE THREAD

**Issue by darkmx** [omegaup/omegaup#7554]
Hola a todos.
En mi perfil tengo seleccionado C++20 GCC como mi lenguaje preferido

https://omegaup.com/profile/rcc
![image](https://github.com/omegaup/omegaup/assets/19719969/8ed77ca9-47d7-40b4-9005-bb0bd03253ee)

pero al intentar enviar un código, se preselecciona C++17:
![image](https://github.com/omegaup/omegaup/assets/19719969/7bb9aead-ab9b-4b00-b4d5-2f172ca16011)

**Comment by HNOONa-0** [comment]
I can investigate this issue

**Comment by darkmx** [comment]
It is happening everywhere.
