### ISSUE TITLE
Reinicio de cuenta regresiva en concursos

### ISSUE THREAD

**Issue by Briaares** [omegaup/omegaup#756]
https://www.youtube.com/watch?v=omoUZa5ywO0&feature=youtu.be
La prueba :S

**Comment by npave** [comment]
El link no sirve, pueden explicar cuál es el problema?

**Comment by Briaares** [comment]
El problema era en su momento, que cuando el contador del tiempo restante para el inicio del concurso llegaba a 0, entonces se reiniciaba en -24:00 horas.

**Comment by lhchavez** [comment]
sigue ocurriendo algo similar? porque según yo ya arreglé varios bugs con
la cuenta regresiva.

**Comment by lhchavez** [comment]
Posiblemente esto ya no ocurra. Cerrémoslo.
