### ISSUE TITLE
Problemas para asignar coders del mes

### ISSUE THREAD

**Issue by ama13do** [omegaup/omegaup#7562]
## Comportamiento Esperado
Los coders del mes deberían ser asignados según su puntaje, pero siempre que sea justo, que los rankings se actualicen a la misma hora para asignar los coders del mes, y que el puntaje sea en tiempo real y no cada día

## Comportamiento Actual

Los coders del mes no son los que hacen mas puntajes mas bien es en muchos casos el segundo, todos los días el top 1 y 2 desaparecen y no son tomados en cuenta en caso de quedar primeros, de igual forma no esta claro los puntos que te da cada problema, el raking de coders se actualiza a las 02:00 am horario Mexico, pero el coder del mes se asigna a las 00:00 horas por tanto los problemas que hagas el ultimo día no valen para nada, al igual que el mes esta mal esta adelantado.

## Posible Solución

Verificar a los 4 coders del mes este año para verificar que su puntaje haya sido mayor, que el sistema de candidatos a coder del mes sea en tiempo real, asegurarse que los problemas dan el puntaje que dice, y verificar que horario usan para su actualización de datos

## Pasos para reproducir (para bugs)

https://omegaup.com/coderofthemonth/

1. Ir a aspirantes para coder del mes
2. verificar cuales son los primeros lugares
3. Volver al día siguiente y ver que el top 1 desapareció y apareció uno que no salía en el top 1
4. el ultimo día del mes gana el coder del mes la persona que aparezca en numero 1, si un día antes apareciste no recibirás el reconocimiento por la hora en que se actualiza la lista

## Contexto

en mi caso mi nombre de usuario es AmadoJos en el mes de enero hice la mayor cantidad de puntos y no fui el ganador simplemente porque ese mi usuario desaparecía de la lista de aspirantes y los problemas del día 31 los tomo para febrero y eso no deber. me gustaria que verifiquen a todos los 4 coders del mes de este año para estar completamente seguros de que ellos hicieron el mayor puntaje, y si no corregir su error

## Tu ambiente

Al estar buscando ser coder del mes note que cuando llegas al top 1 despareces un dia y al dia siguiente apareces y asi se van turnando, es injusto porque no gana el que tiene la mayor cantidad de puntos gana el que quede en top 1 y no desaparezca 

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): edge Versión 123.0.2420.97
* Link al sitio en el que este problema pasa: https://omegaup.com/coderofthemonth/
* Errores en la consola: []
* Captura de pantalla:
Mis envíos en el mes de enero para corroborar que tuve mayor puntaje
![AmadoJos](https://github.com/omegaup/omegaup/assets/64999273/b48d581b-2c65-4077-b825-82b752292d73)
envios de la coder del mes que quedo
![Nikkacf_24](https://github.com/omegaup/omegaup/assets/64999273/d841a96d-6850-4736-8730-d60f95d7864e)

**Comment by tvanessa** [comment]
@pabo99 podemos agregar una prueba para revisar que en la lista de candidatos si guarda por varios dias al mismo candidato?

**Comment by pabo99** [comment]
> @pabo99 podemos agregar una prueba para revisar que la lista de candidatos si guarda por varios dias al mismo candidato?

Ok, habrá que agregar esta prueba que comentas

**Comment by ama13do** [comment]
Siguen estando los bugs ahora van desapareciendo los coders

**Comment by ama13do** [comment]
El coder del mes no fue quien mas puntos hizo, y tampoco aparecen los demás en el toop del mes pasado  
![Imagen de WhatsApp 2024-04-24 a las 11 25 37_ec5bf960](https://github.com/omegaup/omegaup/assets/64999273/e9202658-1194-4c33-be77-72b560b623bb)
aquí sale otro coder que ni siquiera aparece, si lo van a corregir o mejor ya ni nos esforzamos por ser coders

**Comment by tvanessa** [comment]
#7728
