### ISSUE TITLE
Rename `isGroupTeachingAssistantMember`

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7565]
The logic on that function is not specific to teaching assistant groups. It should be renamed to `isMemberOfAnyGroup` or something like that.

https://github.com/omegaup/omegaup/blob/da4967121483a533f223696ecfbcbbab4859c685/frontend/server/src/Authorization.php#L492

**Comment by Aritra8438** [comment]
Can I work on this?

**Comment by heduenas** [comment]
Yes. Thanks @Aritra8438
