### ISSUE TITLE
[BUG] Feedback dismissal doesn't work on courses

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7570]
Steps to reproduce:
1. Go to https://omegaup.com/course/introduccion_a_cpp/assignment/hola_mundo#problems/Hola-Mundo-c
2. Make any submission
3. Click the "X" to close the feedback modal.
4. Refresh the page and go to the problem again.
5. See the modal show up again.

5. Shouldn't happen once you have done 3.

**Comment by HNOONa-0** [comment]
Hello @heduenas, I can work on this.

**Comment by HNOONa-0** [comment]
Hmmm I could not reproduce this issue.

[a1.webm](https://github.com/omegaup/omegaup/assets/59091536/265824c0-38da-47d0-aa48-6d9026c2dc70)

**Comment by heduenas** [comment]
@HNOONa-0 have you been able to reproduce the issue?

**Comment by HNOONa-0** [comment]
> @HNOONa-0 have you been able to reproduce the issue?

Yes I did I actually managed to fix it it was a small silly error, I will try to make a pr now
