### ISSUE TITLE
Add markdown editor to the writing (problem statement) tab and write `Jest` tests.

### ISSUE THREAD

**Issue by Aritra8438** [omegaup/omegaup#7587]
As part of CDP migration, the `writing` tab of the [creator page](https://omegaup.com/problem/creator/) should render the markdown editor where the user can write the problem.

<img width="959" alt="image" src="https://github.com/omegaup/omegaup/assets/64671908/d5acdefd-3ba8-486f-891c-37c0f8b1fa38">

**Comment by carlosabcs** [comment]
They are actually `Jest` tests.
