### ISSUE TITLE
[Code Reviews] Agregar GIF de demostracion

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7591]
<img width="1189" alt="Screenshot 2024-05-18 at 12 08 24 AM" src="https://github.com/omegaup/omegaup/assets/597815/87cbe9c9-c9b0-4b60-9155-70bce6c25c1b">

Borrar el botón de dejar retroaliimentación y poner este gif en su lugar.

![feeback](https://github.com/omegaup/omegaup/assets/597815/f4c12700-538e-4f7a-87a2-57291ac6343c)

Cuando no hay retroalimentación, dejar de mostrar esta leyenda:
<img width="488" alt="Screenshot 2024-05-18 at 12 09 43 AM" src="https://github.com/omegaup/omegaup/assets/597815/97b6e126-ef13-44d6-b719-f3fdd9b2c5c0">

Cuando hay retroalimentación global (de un envío viejo), seguirla mostrando.

**Comment by pabo99** [comment]
¿Cuál sería el gif a mostrar?

**Comment by heduenas** [comment]
El GIF que puse en la descripción del issue. Esta es su URL https://private-user-images.githubusercontent.com/597815/331773427-f4c12700-538e-4f7a-87a2-57291ac6343c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDEyMzQsIm5iZiI6MTcxNjI0MDkzNCwicGF0aCI6Ii81OTc4MTUvMzMxNzczNDI3LWY0YzEyNzAwLTUzOGUtNGY3YS04N2EyLTU3MjkxYWM2MzQzYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMTM1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGQ0ZDk1ZmQ5YWY4YzM5ZTkwMTQwNzE4ZmJhMjA3YjkxNDczY2ZiZTk4MmE5MDk3NThmYjAyMGUwM2QxNjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0o2EVwPaTcxf9MwgORJW18dZ7kd71VNQcZR-ZMLr020
