### ISSUE TITLE
Cambiar cadena "Fuente" por "Codigo"

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7603]
<img width="1142" alt="Screenshot 2024-05-19 at 2 35 43 PM" src="https://github.com/omegaup/omegaup/assets/597815/ca2cb638-0db3-402e-a944-94d34f302316">

**Comment by poojatalele** [comment]
Hey! @heduenas I would like to work on this issue, kindly assign

**Comment by poojatalele** [comment]
Also, please guide me on how to start working on this issue.

**Comment by Barfasushmita** [comment]
@heduenas Hello, I want to work on this issue please assign me this issue!
