### ISSUE TITLE
Align IDE store implementation with TypeScript definitions

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7639]
This is how state is defined for current IDE store:
https://github.com/omegaup/omegaup/blob/8b0cb4d5fdc5456cdd5a6f8aef12b2cdf3326623/frontend/www/js/omegaup/grader/GraderStore.js#L34-L53

When we try to `setSettings` of the IDE:
https://github.com/omegaup/omegaup/blob/8b0cb4d5fdc5456cdd5a6f8aef12b2cdf3326623/frontend/www/js/omegaup/grader/ephemeral.js#L892-L919

We should instead match the IDE store with Typescript definition in this [pr](https://github.com/omegaup/omegaup/pull/7634), then define `getters` and `mutations` for any attribute we would like. This will help with migration process, access to all attributes we would like in the future and ensure consistency.

**Comment by MiirzaBaig** [comment]
Can I work on this?

**Comment by HNOONa-0** [comment]
@MiirzaBaig Thanks but I'm still working on this issue, it will be resolved soon.

**Comment by MiirzaBaig** [comment]
@HNOONa-0 
Alright sir...!👍
