### ISSUE TITLE
Define remaining functionality from `util.js` inside `util.ts`

### ISSUE THREAD

**Issue by HNOONa-0** [omegaup/omegaup#7640]
There are some functions inside of `util.js` not present in `util.ts`. We should add **typed** version of these functions over to `util.ts`.

**Comment by HNOONa-0** [comment]
Hey @pabo99, would you like to continue merging this [pr](https://github.com/omegaup/omegaup/pull/7489) or should I start a new one?

**Comment by pabo99** [comment]
> Hey @pabo99, would you like to continue merging this [pr](https://github.com/omegaup/omegaup/pull/7489) or should I start a new one?

You can start a new PR since it has no revisions; it's okay
