### ISSUE TITLE
[BUG] Todos los problemas tienen un caso "long" en su editor ephemeral

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#7669]
## Current Behavior

Al entrar a ver cualquier problema, el editor en la vista del problema tiene los casos que vienen en la tabla de ejemplos pero además siempre incluye un caso de título "long":

![image](https://github.com/omegaup/omegaup/assets/189223/8d492d3c-6ff4-41d4-adb2-11ceab444081)

## Expected Behavior

Solo deberían aparecer los casos que vienen en la tabla de ejemplos.

## If necessary, add the following information (otherwise delete this section):

Entrar a cualquier problema. Por ejemplo:
  
	1.  https://www.omegaup.com/arena/problem/Filtrando-multiplos/
	2.  https://www.omegaup.com/arena/problem/El-perrito-que-quiere-un-hueso/
	3.  https://www.omegaup.com/arena/problem/Vector-dominante/

**Comment by heduenas** [comment]
@HNOONa-0 can you please investigate? It has been reported that this issue is happening again.

**Comment by HNOONa-0** [comment]
> @HNOONa-0 can you please investigate? It has been reported that this issue is happening again.

On it!
