### ISSUE TITLE
Los nombres de los problemas de un concurso se enciman con sus puntos.

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#767]
![screen shot 2016-02-14 at 8 18 11 pm](https://cloud.githubusercontent.com/assets/5167417/13038404/24e2d5e2-d358-11e5-95a6-7b0d04cd706f.png)

**Comment by elendil326** [comment]
@lhchavez esto podría variar de acuerdo a la resolución y device usado. Hay muchas maneras de resolver esto, pero se tiene que escoger una manera y describir aquí.

**Comment by lhchavez** [comment]
esto nada más necesita un `max-width`

**Comment by pabo99** [comment]
![captura de pantalla 2017-09-27 a la s 17 30 54](https://user-images.githubusercontent.com/3230352/30941166-c06f9c52-a3a9-11e7-86e7-af6bad114331.png)

Con el `max-width`queda listo.
