### ISSUE TITLE
[BUG] El editor en linea ya no muestra la plantilla de los problemas interactivos

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#7670]
## Comportamiento Actual

Ahorita el editor en la vista de problemas muestra una plantilla generica

## Comportamiento Esperado

Segun yo, hasta hace poco mostraba la plantilla del problema interactivo.

**Comment by HNOONa-0** [comment]
It used to display the same generic templates before I made any changes.

I made a video in #7663 talking about similar issue. After fixing a small bug with the editor, another two editors appear. In that video, if you take a look at the **third** editor, it loads the actual template for the `triangulos` problem. But these two extra editors are inactive and serve no functional purpose.

I'm don't know what the intended behavior is, there may be a specific reason for this setup but I will try and fix it.
