### ISSUE TITLE
Problema con el ranking de coder del mes

### ISSUE THREAD

**Issue by Francisco-Xavier-Nieto-Orozco** [omegaup/omegaup#7698]
## Comportamiento Esperado

Aumentar mis puntos de Ranking aproximadamente a 1086 pts aprox.

## Comportamiento Actual

Desaparecí del ranking.

## Posible Solución

Podrían volverme a poner en el ranking con los puntos que se supone debo tener (1086).

## Pasos para reproducir (para bugs)

Esto justo le paso a mi hermana también, al parecer, resolver varios problemas permaneciendo en primer lugar causa que desaparezca del ranking, quizás esto funcione para recrear el bug.

1. Estar en primer lugar ya sea en coder del mes general o coder del mes para ellas.
2. Resolver varios problemas, no importa cuales
3. En la siguiente actualziación de OmegaUp se eliminara la cuenta del Ranking

## Contexto

Me propuse ser coder del mes, pero el día de hoy he desaparecido del ranking sin razón aparente.

*Proveer contexto nos ayuda a encontrar la solución adecuada*

Me esforcé casi todo el día estos días para mantener una puntuación alta pero fui eliminado del Ranking.

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Chrome (No sé la versión)
*https://omegaup.com/coderofthemonth/
* Captura de pantalla:
Mi usuario es Mixer6151.
Estas son fotos de hace 3 días al día de hoy.
![WhatsApp Image 2024-07-04 at 10 52 26 AM](https://github.com/omegaup/omegaup/assets/107452405/278cc4b0-f951-4ca1-ba8e-7f676f2d377a)
![WhatsApp Image 2024-07-03 at 6 45 28 PM](https://github.com/omegaup/omegaup/assets/107452405/dc69a2c0-1488-4c42-b52f-f5f92dae1f5b)
![WhatsApp Image 2024-07-02 at 9 19 17 AM](https://github.com/omegaup/omegaup/assets/107452405/133eda0b-fd4b-49d3-8361-2bb257d9334d)
![Captura de pantalla 2024-07-05 073919](https://github.com/omegaup/omegaup/assets/107452405/b81a81e8-4599-41be-b323-768bed68aa6b)

**Comment by tvanessa** [comment]
#7728
