### ISSUE TITLE
Ranking de aspirantes a coder del mes

### ISSUE THREAD

**Issue by Francisco-Xavier-Nieto-Orozco** [omegaup/omegaup#7708]
## Comportamiento Esperado

Esperaba una actualización del ranking. 

## Comportamiento Actual

No se ha actualizado nada desde hace días.

## Posible Solución

Actualizar el ranking de aspirantes a coder del mes.

## Pasos para reproducir (para bugs)

No hay pasos, solo no se ha actualizado el ranking en días, hoy se actualizo el general pero no el de los aspirantes a coder del mes.

## Contexto

Quiero saber como van las posiciones para saber como voy en mi meta de ser coder del mes.

## Tu ambiente

Chrome
https://omegaup.com/coderofthemonth/
* Captura de pantalla:

![Captura de pantalla 2024-07-11 083934](https://github.com/omegaup/omegaup/assets/107452405/a0813d88-32f1-4613-b643-29e0397626f5)

**Comment by tvanessa** [comment]
#7728
