### ISSUE TITLE
Problemas en el ranking para coder del mes general

### ISSUE THREAD

**Issue by Francisco-Xavier-Nieto-Orozco** [omegaup/omegaup#7709]
## Comportamiento Esperado
Aumentar mis puntos de Ranking.
## Comportamiento Actual
Desaparecí del ranking.
## Posible Solución
Podrían volverme a poner en el ranking con los puntos que se supone debo tener.
## Pasos para reproducir (para bugs)
Resolver varios problemas permaneciendo en primer lugar causa que desaparezca del ranking, quizás esto funcione para recrear el bug.
*Estar en primer lugar ya sea en coder del mes general o coder del mes para ellas.
*Resolver varios problemas, no importa cuales
*En la siguiente actualización de OmegaUp se eliminará la cuenta del Ranking
## Contexto
Me propuse ser coder del mes, pero el día de hoy he desaparecido del ranking sin razón aparente.
## Proveer contexto nos ayuda a encontrar la solución adecuada
Me esforcé casi todo el día estos días para mantener una puntuación alta, pero fui eliminado
del Ranking.
## Incluye los detalles relevantes acerca del ambiente en el que reprodujiste este bug
Chrome (No sé la versión)
*https://omegaup.com/coderofthemonth/
* Captura de pantalla:
Esta captura es de hace días, ayer yo tenia 1099 puntos e hice como otros 100-200 puntos en el tiempo que no se actualizaba el ranking
![Captura1](https://github.com/user-attachments/assets/f85ac8fb-3fcb-4c30-ad13-a1172440d328)

Y en esta otra es la captura del ranking de hoy, donde yo no aparezco
![Captura2](https://github.com/user-attachments/assets/cd6e8807-e294-46af-a85b-ca18376f0dbd)

**Comment by tvanessa** [comment]
#7728
