### ISSUE TITLE
profile.php gasta demasiados recursos

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#771]
`UsersDAO::GetRankByProblemsSolved2` hace un full table scan con un cursor y luego un sort de toda la tabla y es imposible optimizarlo.

**Comment by lhchavez** [comment]
Arreglado en 3474073e34cfbfacb7057f6382ec8305a9b70e96

**Comment by joemmanuel** [comment]
Thnx. No sabía que teníamos un issue abierto.

On Sat, Feb 27, 2016 at 7:03 AM, lhchavez <notifications@github.com> wrote:

> Arreglado en 3474073
> <https://github.com/omegaup/omegaup/commit/3474073e34cfbfacb7057f6382ec8305a9b70e96>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/771#issuecomment-189658561>.
>



-- 
Saludos,
Joemmanuel Ponce
