### ISSUE TITLE
Falla en el ranking de coder del mes general

### ISSUE THREAD

**Issue by Francisco-Xavier-Nieto-Orozco** [omegaup/omegaup#7717]
## Comportamiento Esperado

Aumentar mis puntos de Ranking.

## Comportamiento Actual

Desaparecí del ranking.

## Posible Solución

Podrían volverme a poner en el ranking con los puntos que se supone debo tener.

## Pasos para reproducir (para bugs)

Resolver varios problemas permaneciendo en primer lugar causa que desaparezca del ranking, quizás esto funcione para recrear el bug.
*Estar en primer lugar ya sea en coder del mes general o coder del mes para ellas.
*Resolver varios problemas, no importa cuales
*En la siguiente actualización de OmegaUp se eliminará la cuenta del Ranking

1. 
2. 
3. 
4. 

## Contexto

Me propuse ser coder del mes, pero el día de hoy he desaparecido del ranking sin razón aparente.

*Proveer contexto nos ayuda a encontrar la solución adecuada*

Me esforcé casi todo el día estos días para mantener una puntuación alta, pero fui eliminado
del Ranking.

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

Chrome (No sé la versión)
https://omegaup.com/coderofthemonth/

* Captura de pantalla:
Esta es la captura antes de que fuera eliminado
![WhatsApp Image 2024-07-13 at 10 03 49 PM](https://github.com/user-attachments/assets/bd7eedd5-703b-4172-86b0-7e7352fde237)

Esta es la actual
![WhatsApp Image 2024-07-14 at 8 13 37 AM](https://github.com/user-attachments/assets/0fbcef46-e92b-4d7b-a8a8-ec8889a62caa)

**Comment by tvanessa** [comment]
#7728
