### ISSUE TITLE
La sesión a veces se cierra inesperadamente

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#773]
No hay repro steps :(

**Comment by joemmanuel** [comment]
No hay aunque sea un timestamp en este reporte?

On Saturday, February 20, 2016, lhchavez <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/773>.
>


-- 
Saludos,
Joemmanuel Ponce

**Comment by lhchavez** [comment]
Lamentablemente esto jamás volvió a ocurrir. Lo cual puede ser bueno porque pudo haber sido un bug que ya se arregló.
