### ISSUE TITLE
Problemas con el ranking coder del mes general y coder del mes para ellas.

### ISSUE THREAD

**Issue by camilaorozco0** [omegaup/omegaup#7730]
## Comportamiento Esperado

Esperaba subir puntos en el ranking.

## Comportamiento Actual

No se actualizaron los puntos en el ranking.

## Posible Solución

Actualizar los rankigs.

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

He enviado problemas correctamente pero mis puntos no aumentan.

## Contexto

He enviado problemas correctamente pero mis puntos no aumentan.

## Tu ambiente
No conozco todo pero use google chrome y este es el link de los rankings
https://omegaup.com/coderofthemonth/female/
https://omegaup.com/coderofthemonth/
* Captura de pantalla:
No tengo capturas de pantalla

**Comment by tvanessa** [comment]
Los puntos suelen actualizarse al dïa siguiente, sino es el caso reabrimos el issue.
