### ISSUE TITLE
Error en el coder del mes

### ISSUE THREAD

**Issue by Francisco-Xavier-Nieto-Orozco** [omegaup/omegaup#7735]
## Comportamiento Esperado

En la pestaña de coder del mes el comportamiento es correcto, pero no la selección.

## Comportamiento Actual

Se le dio la insignia y el reconocimiento a alguien que no es el coder del mes

## Posible Solución

Cambiar por el verdadero coder del mes o darme la insignia correspondiente.

## Pasos para reproducir (para bugs)

No tengo idea, solo se que a veces en la tabla desaparecíamos varios coders y al otro volvíamos a aparecer y se repetía ese ciclo 

## Contexto

Buenos días, disculpen la molestia, hubo un error al poner el nuevo coder del mes general, la persona que esta obtuvo una puntuación de 1444, mientras que yo hice 1900 y algo, casi 2000 puntos sin embargo, la plataforma ha presentado fallas al actualizar la tabla ya que un día podía aparecer y al siguiente desaparezco completamente del ranking y al otro vuelvo a aparecer, eso se los hice saber en los issues de github y tengo varias capturas de como fui subiendo mis puntos y siendo eliminado de la tabla de coders y me preguntaba si me pueden poner a mí como coder ya que soy el que cumplió con el requisito, les adjunto las ultimas dos capturas del ranking en la que aún salía y en la final.

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

Google chrome
https://omegaup.com/coderofthemonth/
https://omegaup.com/

* Captura de pantalla:
Estas son las últimas dos capturas en las que se muestran mis puntos y las puntuaciones "finales", tengo más capturas por si las requieren

![WhatsApp Image 2024-07-28 at 11 16 21 PM](https://github.com/user-attachments/assets/5932d433-e8d7-4e0c-a571-453428818947)
![WhatsApp Image 2024-08-01 at 7 02 02 AM](https://github.com/user-attachments/assets/7a8fd0da-6b25-4932-b679-5567e6939462)

**Comment by pabo99** [comment]
Hola @Francisco-Xavier-Nieto-Orozco,

Agradecemos mucho tu reporte acerca de esta falla. 

Para solucionar el error que has mencionado, vamos a revisar y depurar la forma en que se está calculando la lista día a día. 

Mientras trabajamos en esta solución, deshabilitaremos temporalmente el programa.

Gracias por tu comprensión y paciencia.

Saludos cordiales,

**Comment by Francisco-Xavier-Nieto-Orozco** [comment]
Gracias, disculpe la molestia, será posible que con las capturas que he proporcionado se me pueda dar la insignia de coder del mes?

**Comment by tvanessa** [comment]
#7728
