### ISSUE TITLE
[FEATURE] Terminar de migrar a docker-compose V2

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7742]
Probar si estos 3 funcionan con `docker compose` en vez de `docker-compose`:

<img width="1010" alt="Screenshot 2024-08-04 at 12 48 29 PM" src="https://github.com/user-attachments/assets/66b34a32-73f3-4c1b-bcaa-7eaabf027704">

Si no funcionan con `docker compose`, mas temprano que tarde hay que arreglar lo que sea necesario arreglar para que funcionen con `docker compose`

**Comment by pabo99** [comment]
Documentar cada uno de los lugares donde se modificará el comando

**Comment by pabo99** [comment]
Ya se actualizaron los comandos en los tres archivos. 

- Lo que tuve que hacer fue actualizar la versión de `docker compose` en mi maquina local.
- Después ejecutar los tres scripts donde se aplicaron modificaciones. Sólo me faltó probar `./stuff/database_utils.py` debido a que no cuento con permisos necesarios (Quizás se tenga que arrgeglar eso antes de aprobar el PR).
- Una vez que los scripts funcionaron, se actualizaron los posts en la wiki para que los nuevos contribuidores comiencen a trabajar con `docker compose 2`.

Para los contribuidores que ya tienen levantado su ambiente será necesario actualizar la versión de `docker-compose`. En este link pueden encontrar la ayuda necesaria: https://docs.docker.com/compose/migrate/
