### ISSUE TITLE
[FEATURE] Tomar en cuenta el mensaje de feedback general a la hora de calcular el numer de retroalimentaciones.

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7744]
Una ultima mejora antes de que declaremos este proyecto como concluido

El icono actualmente solo muestra el numero de retroalimentaciones que en hilos. Pero cuando un estudiante 
solicita feedback (eso se guarda como feedback general), eso no se toma en cuenta actualmente.

El objectivo es que el profesor pueda identificar facilmente cuales son los envios con solicitud de feedback al navegar la lista de envios en https://omegaup.com/course/<ALIAS>/assignment/<ALIAS>/#runs

**Comment by pabo99** [comment]
¿Quieres que se exprese de una forma distinta la solicitud de retroalimentación a los comentarios realizados?

Hago esta pregunta porque podría ser un poco confuso si un organizador revisar el código de algún envío y escribe una sóla sugerencia, este también estará indicando un globo con (1) comentario. Podemos intentar manejar distintos colores. 

De hecho se me ocurre que al organizador le es mas útil saber en cuantos comentarios ya tuvo interacción el estudiante, que sólo saber cuantos comentarios realizó el mismo, ya que puede revisar varias veces el mismo envío sin que este tenga actividad nueva.
