### ISSUE TITLE
Admin ve 404 cuando un concurso aún no comienza

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#777]
https://twitter.com/JonathanPerazaF/status/700737046558543872?cn=bWVudGlvbg%3D%3D&refsrc=email

**Comment by lhchavez** [comment]
Dupe de #747

**Comment by joemmanuel** [comment]
@alanboy puedes confirmar que 777 y 747 son dupes? Creo que habías
determinado que no...

On Tuesday, March 1, 2016, lhchavez <notifications@github.com> wrote:

> Closed #777 <https://github.com/omegaup/omegaup/issues/777>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/777#event-574132391>.
>


-- 
Saludos,
Joemmanuel Ponce
