### ISSUE TITLE
[BUG] Al llenar la información básica en perfil no se colorea el campo que contiene errores

### ISSUE THREAD

**Issue by pabo99** [omegaup/omegaup#7781]
Por ejemplo: El username no debe llevar espacios, pero eso no se indica en ningún lugar:
![image](https://github.com/user-attachments/assets/a74f49df-12cf-4cab-96ae-58b0791ed125)

Además de que se debe pintar en rojo el campo que está fallando al llenar la  informacion, como por ejemplo:
![image](https://github.com/user-attachments/assets/05ca2211-c6a2-434f-b01f-366d89064341)

**Comment by sudarsan2k5** [comment]
@pabo99 Is this what you expected?



https://github.com/user-attachments/assets/fee465e1-3fb0-45fb-afac-d71b2564678c

**Comment by pabo99** [comment]
Sure, that's exactly the expected behavior. @sudarsan2k5  Do you want to fix this issue?
