### ISSUE TITLE
/rank no funciona a la perfección

### ISSUE THREAD

**Issue by Briaares** [omegaup/omegaup#780]
https://omegaup.com/rank/ te dirije a una página vacía, sin usuarios, en cambio https://omegaup.com/rank/?page=1 ya te dirige a la página con los usuarios.

**Comment by joemmanuel** [comment]
Looking...

2016-03-02 7:39 GMT-08:00 Briaares <notifications@github.com>:

> https://omegaup.com/rank/ te dirije a una página vacía, sin usuarios, en
> cambio https://omegaup.com/rank/?page=1 ya te dirige a la página con los
> usuarios.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/780>.
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by joemmanuel** [comment]
El bug está en rank.php, forza page 0, debe ser 1

2016-03-02 7:40 GMT-08:00 Joemmanuel Ponce Galindo <joemmanuel@gmail.com>:

> Looking...
>
> 2016-03-02 7:39 GMT-08:00 Briaares <notifications@github.com>:
>
>> https://omegaup.com/rank/ te dirije a una página vacía, sin usuarios, en
>> cambio https://omegaup.com/rank/?page=1 ya te dirige a la página con los
>> usuarios.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/omegaup/omegaup/issues/780>.
>>
>
>
>
> --
> Saludos,
> Joemmanuel Ponce
>
>


-- 
Saludos,
Joemmanuel Ponce
