### ISSUE TITLE
[BUG] Scrollbar no está presente en un problema (tal vez mas)

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#7807]
Al cargar este problema en Chrome o Firefox no aparece la scrollbar, lo que hace que el problema sea imposible de interactuar.

https://www.omegaup.com/arena/problem/OMI-2022-fuentes

![Screenshot 2024-09-10 181514](https://github.com/user-attachments/assets/640f7dfe-0692-4578-8f74-83aa190c0ee0)

**Comment by darknut** [comment]
Tampoco se pueden scrollear en los cursos
https://www.omegaup.com/course/OMIexamenes/assignment/omi2022d1/#problems/OMI-2022-fuentes

**Comment by darknut** [comment]
efectivamente son los solo salida

https://omegaup.com/arena/problem/Parientes/

en este problema mas corto se puede ver que la redaccion se corta justo cuando viene la parte de descargar los casos

**Comment by pabo99** [comment]
@HNOONa-0 ^

Steps to reproduce:

- Create a problem. The problem type should be `Only input`.
- Go to the problem. The scrollbar is broken due to an undefined object.

**Comment by HNOONa-0** [comment]
Goti

> @HNOONa-0 ^
> 
> Steps to reproduce:
> 
> * Create a problem. The problem type should be `Only input`.
>   ![image](https://private-user-images.githubusercontent.com/3230352/366260235-b2b00e9b-164b-489a-9ea0-baa910490e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzM5NjEsIm5iZiI6MTcyNjAzMzY2MSwicGF0aCI6Ii8zMjMwMzUyLzM2NjI2MDIzNS1iMmIwMGU5Yi0xNjRiLTQ4OWEtOWVhMC1iYWE5MTA0OTBlNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDU0NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU4ZTdlM2JhZGU5ODVlZDllZmYyZGUxZjdmYTdkYTBiNTg5NGI1YmQ2ZWNmN2RiNmM0NTMxNTBjM2QzMGM1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FyO7y8FMTl8vdhzGcAiVUPV5bRo8O8kA2lm9qYSmXQ8)
> * Go to the problem. The scrollbar is broken due to an undefined object.
>   ![image](https://private-user-images.githubusercontent.com/3230352/366260324-090f5fbb-e4b2-4b5d-a76b-6f86ede9508d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzM5NjEsIm5iZiI6MTcyNjAzMzY2MSwicGF0aCI6Ii8zMjMwMzUyLzM2NjI2MDMyNC0wOTBmNWZiYi1lNGIyLTRiNWQtYTc2Yi02Zjg2ZWRlOTUwOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDU0NzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE0ODgwM2Y2ZWVkZWM0NmZlNDc0N2VhNDkyNDBjNzAxOWIwODZlZGE2ZTA0Yjg4YjFiMWY1OTUzNjQzN2VhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tSfmUIP3PrJq-uKCKIGAmOGGDh3AHmU6bXPIY2PMfGQ)

The problem is that the language in this type of problem is `cat`. `cat` is an actual language that should be supported? That was not the case before I think, I will fix it now.

**Comment by darknut** [comment]
Buenos días, habrá un estimado de cuándo se arreglará este problema? La OMI es en un mes y necesitamos entrenar.

**Comment by darknut** [comment]
Esto ya hizo deploy? Porque aún veo el bug en el sistema :/

**Comment by pabo99** [comment]
Al parecer el deploy se realizó el domingo. Así que ya debería de desaparecer el bug. 

Si todavía te aparece, puedes reabrir el issue y darnos mas información para ver si existe algún caso esquina que no se consideró
