### ISSUE TITLE
Automáticamente borra un ')' al escribir una variable en Karel.js

### ISSUE THREAD

**Issue by msclecram** [omegaup/omegaup#781]
Después de escribir "iterate()", pongo el cursor en medio de los paréntesis y al agregar una variable 'n' me borra automáticamente el paréntesis que cierra quedando "iterate(n".

Este es el código con el que pasa:

`class program {

```
define quita100(n){

}

define cosa(n){

    if(nextToABeeper){
        pickbeeper();
        quita100(n);
    }else{
        iterate(n   // <- aquí pasa
    }

}

program () {
    // TODO poner codigo aqui
    turnoff();
}
```

}`

**Comment by msclecram** [comment]
Recargué Karel.js y ya no pasa.
Nota: no tenía activado el insert.  Lo verifiqué.

**Comment by lhchavez** [comment]
cerrando porque nunca fue posible reproducirlo :(
