### ISSUE TITLE
[BUG] Ephemeral is not showing output

### ISSUE THREAD

**Issue by tvanessa** [omegaup/omegaup#7816]
Some users had reported that the tab `files.zip` stopped showing output produced by the user's code

![Screenshot 2024-09-12 at 2 03 26 PM](https://github.com/user-attachments/assets/f8af0653-09ba-4069-8165-0acb049caea7)

**Comment by HNOONa-0** [comment]
I have noticed that bug. This commit fixes that bug:
https://github.com/omegaup/omegaup/pull/7799/commits/93b0fa4c82369f03b24a3461af9c01333999502a

**Comment by pabo99** [comment]
> I have noticed that bug. This commit fixes that bug: [93b0fa4](https://github.com/omegaup/omegaup/commit/93b0fa4c82369f03b24a3461af9c01333999502a) #7799

If those lines help resolve this issue, could you add them in a new PR? This way, the review would be faster, and we could merge it sooner

**Comment by pabo99** [comment]
Forget it. The PR was approved and soon will be merged to main branch! 

Thank you for solve this issue!
