### ISSUE TITLE
Cada vez que se intenta subir un ejercicio a la plataforma de OmegaUp aparece el mensaje OmegaUp dice "Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.". Hemos probado desde diferentes computadoras y el error es el mismo. Saludos

### ISSUE THREAD

**Issue by caro-sinelli** [omegaup/omegaup#7848]
## Comportamiento Esperado

*Describe lo que esperabas que pasara*

## Comportamiento Actual

*Describe lo que pasó en lugar de lo que se esperaba*

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
* Link al sitio en el que este problema pasa: https://omegaup.com/course/AulaVirtual23AT24/assignment/RepetitivaWhile/#problems
* Errores en la consola: [{"status":"error","error":"Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.","errorname":"generalError","errorcode":500,"header":"HTTP/1.1 500 INTERNAL SERVER ERROR","_id":"66ffe0368683e386389947","httpStatusCode":500},{"status":"error","error":"Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.","errorname":"generalError","errorcode":500,"header":"HTTP/1.1 500 INTERNAL SERVER ERROR","_id":"66ffe166b0315594398551","httpStatusCode":500}]
* Captura de pantalla:

**Comment by gfdfranco** [comment]
Same here, it's not working :disappointed: .
It's not working for any problems in any course.

Message: Oops. I've encountered an internal error. Please try again.

**Comment by gfdfranco** [comment]
Ty! is working again :smiley:
