### ISSUE TITLE
API SetRecommended no borra el cache de la lista de concursos

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#785]
@joemmanuel @lhchavez describirán el problema y posible diseño de solución.

**Comment by elendil326** [comment]
Quitando el ready. ¿A qué cache se refiere esto @joemmanuel @lhchavez ? En el codigo de [apiSetRecommended](https://github.com/omegaup/omegaup/blob/5672db86f2b6ac119bfd4b65b9423e3699fdb530/frontend/server/controllers/ContestController.php) no veo nada relacionado a un cache.

**Comment by elendil326** [comment]
ping @lhchavez @joemmanuel

**Comment by lhchavez** [comment]
ese es precisamente el problema: https://github.com/omegaup/omegaup/blob/5672db86f2b6ac119bfd4b65b9423e3699fdb530/frontend/server/controllers/ContestController.php#L51-L75 usa un cache, y `apiSetRecommended` cambia lo que se debería mostrar, pero no invalida ese cache.
