### ISSUE TITLE
Log de transiciones de problema público->privado 

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#786]
https://omegaup.com/preguntas/692/estan-depurando-problemas

**Comment by elendil326** [comment]
@joemmanuel @lhchavez esto aún es necesario? Se requiere cambiar la UI, o es solo lógica de negocio?

**Comment by heduenas** [comment]
I think it's just a matter of logging whenever a problem becomes private.
An example of logging is in https://github.com/omegaup/omegaup/blob/f25f768ddb6f9066eb9549a1ebc6dbcb3e345a58/frontend/server/controllers/InterviewController.php#L63

I'm going to ask @tahirs95 to solve this issue.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/572
