### ISSUE TITLE
[BUG] OmegaUp is not showing any contest when using the search box 

### ISSUE THREAD

**Issue by ericksav21** [omegaup/omegaup#7860]
## Current Behavior

OmegaUp is not showing any contest when using the search box and is also throwing the following error message: "contest_id: Parameter must be a number."

This is observed for current, future and past contests.

## Expected Behavior

If used a valid search term the UI has to show any contest that matches the search term.

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. Go to "Contests" -> "View Contests".
	2. Paste a valid search term (a contest prefix that you know it exists).
	3. Click on "Search" button

*Relevant details about the environment in which you encountered this bug:*

	* Browser name Chrome 129.0.6668.103
	* Link to the site where this issue occurs: https://omegaup.com/arena/?query=#past
	* Screenshot:

*Relevant details about the environment in which you encountered this bug:*

	* Browser name Chrome 129.0.6668.103
	* Link to the site where this issue occurs: https://omegaup.com/arena/?query=#past
	* Screenshot: Attached below

 ![Screenshot 2024-10-25 at 6 07 17 p m](https://github.com/user-attachments/assets/d8956611-921a-456a-9a1a-293304c3e677)

**Comment by pabo99** [comment]
Hi Erick! Thank you for reporting the issue. 

A new version of the contest listing view was recently released, which fixed the sorting and filtering functionalities. It is possible that we missed some testing regarding the searches.

**Comment by pabo99** [comment]
I haven't been able to reproduce the bug. 

I'm sharing a screencast with a couple of searches I performed, both of which worked as expected:


https://github.com/user-attachments/assets/9bcfac4e-ce85-452d-9fb5-80d811ea69ca

Could you try clearing the cache and see if that helps resolve the issue?

Or if you're still experiencing the error, could you share more information so we can reproduce it?

**Comment by ericksav21** [comment]
Hi Pablo,

After clearing my browser's cache and trying again I can confirm I no longer see this issue. Thanks!
