### ISSUE TITLE
Si en la búsqueda de problemas solo aparece un resultado, que se brinque la búsqueda y te lleve directo al problema.

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#788]

**Comment by samdsmx** [comment]
No estoy del todo de acuerdo con este request, dado que asi no se podra ver las estadisticas de dicho problema (Punto para el ranking, Cuantos envios / resueltos). A menos que se inculya en el encabezado de todos los problemas esta info.

**Comment by elendil326** [comment]
@lhchavez esto aún es necesario?

**Comment by lhchavez** [comment]
No, @samdsmx tiene razón.
