### ISSUE TITLE
[FEATURE] El titulo de "Crear Concurso" debe de ser gris como el de "Crear Curso"

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#7893]
<img width="1101" alt="Screenshot 2024-11-07 at 10 41 28 PM" src="https://github.com/user-attachments/assets/bd281728-cde1-45c4-9310-4029d29a1047">

<img width="1093" alt="Screenshot 2024-11-07 at 10 41 15 PM" src="https://github.com/user-attachments/assets/c0c02cf0-7fc7-4156-88d5-331f12de5ec5">

**Comment by sudarsan2k5** [comment]
@heduenas, please assign this to me. I am working on this issue.
