### ISSUE TITLE
[BUG] Los problemas no están disponibles

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#7908]
## Current Behavior

 No se puede acceder a los problemas 

## Expected Behavior

*Describe what you were originally trying to do and how you expected the platform to behave.*

## If necessary, add the following information (otherwise delete this section):
*Provide a link to an example, or a detailed list of steps to reproduce this bug.*  
  
	1. https://omegaup.com/problem/?query=Funcion+totienica+de+euler
	2. https://omegaup.com/arena/problem/Funcion-totienica-de-euler/
	3. 
	4. 
*Relevant details about the environment in which you encountered this bug:*

	* Browser name (e.g., Chrome 39, node.js 5.4):
	* Operating System and version (desktop or mobile):
	* Link to the site where this issue occurs:
	* Screenshot:
![image](https://github.com/user-attachments/assets/f2c08f06-a8c1-4157-a145-cb4189100055)
![image](https://github.com/user-attachments/assets/60167f0f-d714-43be-8efd-07b888d39259)

![image](https://github.com/user-attachments/assets/50071503-ca28-4eee-8f5b-7d70fcb0d9ed)

**Comment by pabo99** [comment]
@andreasantillana Gracias por reportarnos esta incidencia grave. 

Reiniciamos un par de pods para que volvieran a correr los servicios que estaban caidos y la plataforma ya está funcionando. 

Cerramos este issue de momento.
