### ISSUE TITLE
Error en prueba INBRH26040377 - C. Chicharronera

### ISSUE THREAD

**Issue by jssDavis** [omegaup/omegaup#7917]
## Comportamiento Esperado
Entrada: 
1 1 -6
Salida:
2 -3

*Describe lo que esperabas que pasara*

Obtengo las salidas considerando que las soluciones siempre son reales y el resultado es el esperado por la aplicación: 
2 -3

Y me marca como incorrecto y que no tal vez no considere todas las opciones

## Comportamiento Actual

No valida correctamente la salida del programa

*Describe lo que pasó en lugar de lo que se esperaba*

Marca error cuando la salida es correcta

## Posible Solución

*No es obligatorio, pero puedes sugerir una manera de arreglar el bug*

## Pasos para reproducir (para bugs)

*Provee un link a un ejemplo, o una lista de pasos detallada de cómo reproducir
este bug.  Incluye el código que lo reproduce, si es relevante*

1. 
2. 
3. 
4. 

## Contexto

*Cómo te ha afectado este issue? Cuál es el objetivo a cumplir?*
Estoy realizando una prueba de admisión para una empresa y necesito saber o tener mas casos de uso para saber en cual se supone que no es correcto mi codigo

*Proveer contexto nos ayuda a encontrar la solución adecuada*

## Tu ambiente

*Incluye los detalles relevantes acerca del ambiente en el que reprodujiste
este bug*

* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
* Link al sitio en el que este problema pasa: https://omegaup.com/arena/INBRH26040377/startfresh/?fromLogin=#problems
* Errores en la consola: []
* Captura de pantalla:

**Comment by tvanessa** [comment]
Después de la descripción del problema, hay un botón para reportar el problema. Puedes enviar tu sugerencia llenando ese formulario:

![Screenshot 2024-12-16 at 5 02 49 PM](https://github.com/user-attachments/assets/5c5fa0f9-fa5b-4ecc-87ff-5bc43d180215)
