### ISSUE TITLE
Regresión: Los admins aparecen en el scoreboard después de elegir Ingresar Concurso

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#792]

**Comment by frcepeda** [comment]
@alanboy pls

**Comment by joemmanuel** [comment]
Pánico. A menos que el fix sea trivial hay que dejarlo así para el Día 1 :(

On Monday, March 7, 2016, Freddy Román <notifications@github.com> wrote:

> @alanboy <https://github.com/alanboy> pls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/792#issuecomment-193604560>.
>


-- 
Saludos,
Joemmanuel Ponce

**Comment by frcepeda** [comment]
Al scoreboard no le importa, pero se ve feo :c

**Comment by lhchavez** [comment]
nonono, esto no es necesario arreglarlo ahorita :P post-omi.

**Comment by joemmanuel** [comment]
Safo parchar los reportes.
Hay que intentar el fix para el día 2, está muy deprimente salir con bugs
en nuestro concurso más público.

On Monday, March 7, 2016, lhchavez <notifications@github.com> wrote:

> nonono, esto no es necesario arreglarlo ahorita :P post-omi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/792#issuecomment-193605597>.
>


-- 
Saludos,
Joemmanuel Ponce

**Comment by elendil326** [comment]
@lhchavez @joemmanuel esto aún hace repro?

**Comment by elendil326** [comment]
Esto ya se arreglo con #2185
