### ISSUE TITLE
[FEATURE] In the create problem section, the input field remained filled with the previously entered Public tag

### ISSUE THREAD

**Issue by k-vijay-05** [omegaup/omegaup#7922]
In the `create problem` section, after adding a `public tag` , the input field remained filled with the previously entered tag, rather than being cleared, which reduced the ease of use for the user.

***Before*** : The input field for adding a public tag remained filled with the previously entered tag, instead of clearing after the tag was added

https://github.com/user-attachments/assets/0caa2378-3eb1-4744-992e-c97a92adc113

***After*** : The input field is cleared automatically after a public tag is added, improving the ease of use for the user

https://github.com/user-attachments/assets/6604588d-bcca-43a7-9b11-f23725b60d52

I would like to hear your suggestion on this change. Can I go ahead and raise a PR for this improvement?

**Comment by pabo99** [comment]
Great! We're excited to have you working with us! We'd love for you to help us implement this change. 

You'll also earn extra points if you remove the error style (the red borders in the input field and the exclamation mark in red) once there's at least one public tag

**Comment by k-vijay-05** [comment]
@pabo99 Thank you for the warm greeting! I'm truly excited to contribute to the project and make meaningful improvements that enhance the user experience.
