### ISSUE TITLE
Usar los prefijos correctos en los límites de memoria

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#798]
Los prefijos estándar del SI son para potencias de 10, no como omegaUp los usa. Para eso hay https://en.wikipedia.org/wiki/Binary_prefix.

La alternativa es reportar los límites de memoria usando base 10. (Cómo lo hacen otros jueces?)

**Comment by lhchavez** [comment]
les vale madres y usan los prefijos mal.

**Comment by frcepeda** [comment]
:<

**Comment by joemmanuel** [comment]
Freddy, quieres intentar un PR con este fix?

On Thu, May 5, 2016 at 12:45 PM, Freddy Román <notifications@github.com>
wrote:

> :<
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/798#issuecomment-217256687>
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by frcepeda** [comment]
Podría intentar pero hasta Junio

**Comment by joemmanuel** [comment]
Suena bien.

On Thu, May 5, 2016 at 6:58 PM, Freddy Román <notifications@github.com>
wrote:

> Podría intentar pero hasta Junio
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/omegaup/issues/798#issuecomment-217329853>
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by elendil326** [comment]
@lhchavez que procede con este request?

**Comment by SpaceWhite** [comment]
Can anyone assign me this issue?

**Comment by lhchavez** [comment]
assigned to @SpaceWhite !
