### ISSUE TITLE
Backfill recruitable_optin column

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#816]
From @joemmanuel 

> Hay que armar un plan para hacer el backfill - cómo le hacemos para que los usuarios ya creados actualicen su perfil.
> Opciones:
> Soft-reminder no-invasivo (los cuadros azules que salen cuando tienes muchos problems privados, por ejemplo)
> Reminder invasivo de vez en cuando (en general esto no es ideal pero lo dejo a discusión).
> Les mandamos un email y no ponemos ningún reminder. (En cualquier opción hay que anunciar este cambio en el perfil en un email general, ábreme un issue para hacerlo cuando esto este en prod porfas).

**Comment by lhchavez** [comment]
-1 a los emails. Cuál es la diferencia entre un reminder invasivo y los cuadros azules? Según yo son bastante invasivos :P

**Comment by alanboy** [comment]
no enviaba @joemmanuel un email de todas maneras con la ultimas noticias de OmegaUp ?

podemos acomodar el cuadro azul para que no sea tan invasivo.

**Comment by elendil326** [comment]
@joemmanuel @lhchavez esto aún se quiere implementar?

**Comment by pabloaguilar** [comment]
Si, es necesario para omegaUp for Work que segun yo sigue en el roadmap

**Comment by pabo99** [comment]
¿Esto aún se necesita? Por que ese campo ya ni siquiera existe en la base de datos, se eliminó en este issue  https://github.com/omegaup/omegaup/issues/1989

**Comment by lhchavez** [comment]
No :D
