### ISSUE TITLE
[BUG] Contest DAO regresa start_time como datetime por default en vez de unixtimestamp

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#818]
Esta diferencia es propensa a errores, hay que buscar la forma de que el framework evite que cometamos errores de comparación.

**Comment by elendil326** [comment]
@joemmanuel @lhchavez esto aún hace repro?

**Comment by pabo99** [comment]
Voy a revisar si esto se corrigió con los cambios del issue #1475, en caso de ser así, se va a cerrar este.

**Comment by pabo99** [comment]
En `ContestsDAO`, todas las consultas que muestran información de los concursos se obtienen de una variable estática en la cual ya se aplica la función `UNIX_TIMESTAMP`, así que ya no se corre ese riesgo.

**Comment by lhchavez** [comment]
la cosa es que hay que buscar una manera en la que esto no pueda ocurrir jamás. así como están las cosas ahorita puede ser que cambie algo y regrese el problema :(

**Comment by lhchavez** [comment]
ya tenemos un poco más de soporte para que cuando algo se obtiene de MySQL usando `TIMESTAMP` como tipo de datos, esto se propaga hasta el frontend (mediante el API) para que sea una fecha de verdad (un `Date` de JavaScript).

Faltan algunas cosas:

- Ver cómo distinguir entre APIs que necesitan que la fecha sea la "real" (como cuando se va a agendar un concurso en el futureo) y la fecha sea la ajustada con respecto al servidor (como cuando se está en un concurso).
- Arreglar _todos_ los APIs para que usen este feature.

**Comment by lhchavez** [comment]
Esto ya ha sido atendido lentamente. Las fechas ya se exponen como fechas de verdad en JavaScript, y hay funciones que se pueden usar para marcar una fecha como "remota".
