### ISSUE TITLE
Poder definir hints en problemas

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#821]
un competidor en etapa de aprendizaje, quiere poder recibir feedback mas valioso sobre lo que falla, para poder aprender identificar las cosas que tiene que considerar a la hora de resolver un problema.
y al finar poder obtener aprendizaje de un PA. 

esto se podria definir en el test plan donde en cada linea se pueda agregar una cadena para que se muestre cuando al evaluar falla en ese caso. siempre mostrando solo un mensaje por envio.

**Comment by lhchavez** [comment]
No estoy 100% seguro de que el testplan sea el lugar correcto. Por un lado es bueno tenerlo junto con la "fuente de la verdad" de los casos, pero por otro lado pierdes i18n. También, cambiar el tesplan causa un rejueceo y agregar soporte para otro idioma entonces sería caro ^^;

qué te parece un `es.hints` junto al `es.markdown`?

**Comment by elendil326** [comment]
@lhchavez hay diseño final para implementar esto?

**Comment by pacharrin** [comment]
btw, todos los problemas del curso ya tienen un tutorial.markdown (https://github.com/ComiteMexicanoDeInformatica/workshop/blob/master/Programacion%20Basica/A%2BB/statements/tutorial.markdown)

tal vez seria mejor que hubiera un link al tutorial y que si le dan click se marqué como que resolvió el problema después de ver el tutorial?

**Comment by lhchavez** [comment]
Esto suena bien mostrar ese link si se está viendo el problema como un problema standalone, en un concurso en modo de práctica, o en un curso.

y también advertirle al usuario que una vez que haga click en el link, se va a marcar como que vio la pista.

**Comment by lhchavez** [comment]
Esto se necesita tener para Mayo.

**Comment by tvanessa** [comment]
Esto se implementó en solution writeups.
