### ISSUE TITLE
Sale "null (undefined)" cuando se niega un registro

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#823]
Cuando se niega una solicitud de registro el campo de last update aparece como "null (undefined)"

**Comment by elendil326** [comment]
@alanboy @lhchavez esto aún hace repro?

**Comment by elendil326** [comment]
Traté de hacer repro registrando un nuevo usuario con un email repetido y no vi el null. Cerrando como no repro. @alanboy ábrelo si puedes hacerle repro junto con los repro steps.
