### ISSUE TITLE
Permitir a administradores ver qué usuarios han hecho optin a la opción de reclutamiento

### ISSUE THREAD

**Issue by rcxr** [omegaup/omegaup#825]
Exponer en la UI la lista de usuarios que han hecho optin a la opción de reclutamiento.
Limitado solamente a administradores.

**Comment by elendil326** [comment]
@rcxr @lhchavez mockup/descripción del diseño y comportamiento esperado necesarios para completar este feature.

**Comment by pabo99** [comment]
Este campo ya desapareció del esquema de la base de datos.
