### ISSUE TITLE
Poder filltrar problemas por traducciones que tiene disponible

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#842]
yo, como usuario de otros paises quiero poder buscar problemas en mi idioma

**Comment by samdsmx** [comment]
Te refieres a idoma? En nuestro contexto lenguaje.. para referirse a lenguaje de programación.

**Comment by lhchavez** [comment]
sí se entendía (por lo del "usuario de otros países") :P pero ya está clarificado.

**Comment by elendil326** [comment]
@lhchavez asumo que esto aún no es posible.

**Comment by elendil326** [comment]
Quitando el ready porque falta definir más el scope. Parece que hay que cambiar desde subir un problema, el esquema de la base de datos y un plan para actualizar los problemas que ya existen, para relacionarlos con un idioma.

**Comment by elendil326** [comment]
@lhchavez esta lista de cambios para resolver este issue esta completa?

- Cambiar el esquema de la base de datos para relacionar un problema con idiomas
- Cambiar el formato de "subir el problema" para especificar un lenguaje
- Correr los problemas existentes contra un API público detector de idioma para obtener información de los problemas actuales y actualizarlos de manera correspondiente
- Cambiar el UI de listado de problemas para permitir filtrar por idioma.

**Comment by pabloaguilar** [comment]
El formato de problemas ya soporta lenguaje. Los primeros dos puntos no son necesarios (ver la seccion de statements/ en https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-escribir-problemas-para-Omegaup) 
El 3er punto estaria interesante, pero creo que no es necesario en una primer version de esto, que puede confiar ciegamente en lo que hayan subido los creadores de los problemas.
El cambio de la UI es la parte que hay que implementar ahorita.

**Comment by lhchavez** [comment]
El primer punto quizás sí sea necesario: ahorita el idioma del problema es algo que se obtiene del sistema de archivos, así que no lo podemos usar para hacer filtros.

1) sería pre-req y 4) sería exactamente este bug, como menciona Pablo.

**Comment by pabloaguilar** [comment]
Entonces, la idea es denormalizar la info del sistema del archivos a la BD?
Si si, entonces tambien tenemos que hacer un backfill, como el punto 3) (sin deteccion de lenguaje, solo con lo que haya en el sistema de archivos)

**Comment by elendil326** [comment]
Creé el issue #1463 para hacer tracking de los puntos 1) y 3). Este issue solo cubre el punto 4). El punto 2) no es necesario hacerlo porque ya está implementado.
