### ISSUE TITLE
Cambiar de modo de penalty / puntuación de un problema debe causar un rejueceo/recálculo

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#849]
El penalty y el `contest_score` se calculan cada que se evalúa un run, sólo una vez y es perpetuo basado en las reglas. Si las reglas cambian, el penalty / puntaje de los runs pasados no se actualiza. Podemos hacer que cambiar las reglas cause rejudge \* o implementar un recalculo lightweight (preferred) para no pagar el costo de los jueces por algo simple.

**Comment by lhchavez** [comment]
Para el rejueceo de los puntos ya está #1651, pero para el penalty hay que hacer lo siguiente:

* Si `penalty_type` es `'runtime'`, hay que simplemente establecer `penalty = runtime`: https://github.com/lhchavez/quark/blob/14405e9a676e7d6b3cbe738ee4bc3f0025409230/cmd/omegaup-grader/v1compat_handler.go#L56-L73
* Si el `penalty_type` es cualquier otra cosa, hay que simplemente establecer `penalty = submit_delay`: https://github.com/omegaup/omegaup/blob/efc9b14bf2f8082f693faf0cd2e0f0509c360ead/frontend/server/controllers/RunController.php#L292-L309

**Comment by lhchavez** [comment]
Falta el penalty

**Comment by pabo99** [comment]
Se agrega el recalculo de penalty. También se agregan las pruebas.
