### ISSUE TITLE
[FEATURE] Poder distinguir entre alumnos y profesores mediante una opción en el signup/perfil

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#858]
Hasta el momento hemos considerado que todas las personas son 'concursantes', pero en realidad hay gente que son maestros, y estaría bueno a ellos preguntarles si podemos contactarlos para darles noticias de omegaup for schools (o al menos para poderlos identificar fácilmente).

**Comment by pabo99** [comment]
@MiguelRomero   La propuesta es agregar un checkbox que indique si el usuario es maestro, y al seleccionarlo, que aparezca otro donde se le pregunte si desea ser contactado por el equipo de `omegaUp for Schools`.

¿Qué opinas?

**Comment by pabloaguilar** [comment]
Fixed
