### ISSUE TITLE
Agregar un archivo de configuración con defaults a db-migrate.py

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#875]
En producción no tenemos `omegaup-test`, en Travis no tenemos `omegaup`, y en Vagrant queremos pasarle `--developer-environment`. Andar cambiando los argumentos de la línea de comandos es medio peligroso, así que es mejor que la configuración se quede en un archivo estable.

**Comment by pabloaguilar** [comment]
Esto es lo que está implementado en `boostrap-environment.py` + `bootstrap.json`?

**Comment by lhchavez** [comment]
oh! es cierto!
