### ISSUE TITLE
Script whitespace-purge.py no funciona con remote diferente de origin

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#877]
Con remote apuntando a mi fork el push falla con un error en este script, pero si le cambio el remote a que se llame origin el push funciona sin problema.

devagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ git push nancy master:prueba
Username for 'https://github.com': npave
Password for 'https://npave@github.com':
fatal: bad revision 'nancy'
Traceback (most recent call last):
  File "/opt/omegaup/stuff/whitespace-purge.py", line 105, in <module>
    sys.exit(main())
  File "/opt/omegaup/stuff/whitespace-purge.py", line 66, in main
    ['/usr/bin/git', 'diff', '--name-only', args.remote, '--']
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'diff', '--name-only', 'nancy', '--']' returned non-zero exit status 128
error: failed to push some refs to 'https://github.com/npave/omegaup.git'
vagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ git remote set-url origin https://github.com/npave/omegaup.git
vagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ git branch -u origin/master
Branch master set up to track remote branch master from origin.
vagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
vagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': npave
Password for 'https://npave@github.com':
Counting objects: 15, done.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 2.79 KiB | 0 bytes/s, done.
Total 15 (delta 13), reused 0 (delta 0)
remote: Resolving deltas: 100% (13/13), completed with 13 local objects.
To https://github.com/npave/omegaup.git
   f17feff..c901d0a  master -> master
vagrant@vagrant-ubuntu-wily-64:/opt/omegaup$ echo "

**Comment by lhchavez** [comment]
El script tiene varios problemas. El primero es que efectivamente únicamente toma en cuenta `origin` como nombre del remote. El segundo es que resulta que con la manera en la que lo estoy corriendo (haciendo un diff entre lo que está en working directory y `origin`), no funciona bien para las ramas. Y claro, si quieres empujar a un remote distinto al que está configurado la rama (como lo intentas hacer en el primer ejemplo), _tampoco_ va a hacer lo que quería que hiciera.

Creo que lo que tengo que hacer es leer la entrada estándar del pre-push hook para ver en qué commit está el remote al que estás intentando empujar. Si es el commit vacío (`00000....0000`), que valide todo, pero luego tengo que imprimir eso para que puedas llamar `whitespace-purge.py` con los parámetros correctos.

Yo lo arreglo a menos que alguien esté muy motivado y quiera aprender de git :P
