### ISSUE TITLE
Migrar backendv2 a la cuenta de omegaup

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#879]
Actualmente el código de backendv2 está en https://github.com/lhchavez/quark , pero hay que migrarlo a que reemplace https://github.com/omegaup/backend (o hacer https://github.com/omegaup/quark ) una vez que estén listos todos los componentes.

**Comment by elendil326** [comment]
@lhchavez Esto aún es necesario?

**Comment by pabloaguilar** [comment]
Fixed
