### ISSUE TITLE
no puedo editar mis datos personales

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#899]
cuando inicio sesión por primera vez con google, no puedo editar mis datos personas como escuela, graduación, etc y tampoco puedo ver la opción de dar mis datos a reclutadores.

una vez que edite mi usuario, e hice una contraseña, cerrar sesion, iniciar sesion, ahora si ya pude editar esos datos.

**Comment by lhchavez** [comment]
Dupe de https://github.com/omegaup/omegaup/issues/1630
