### ISSUE TITLE
Lista de estudiantes y su avance en el curso: servidor

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#902]
El profesor puede ver la lista de estudiantes inscritos a un curso y ver los problemas que ellos han resuelto.
- Consultas en los DAOs y CourseController. Es casi lo mismo que un scoreboard de un grupo.

**Comment by elendil326** [comment]
@npave @lhchavez detalles del diseño y el workflow (por donde entra el profesor a esta vista, etc).

**Comment by pabloaguilar** [comment]
Esto ya esta hecho. Es la API para View Progress + la API para Scoreboard.
Creo que podemos cerrar este issue dado que solo falta mejorar la interfaz del scoreboard en #1022
