### ISSUE TITLE
Lista de estudiantes y su avance en el curso: front-end

### ISSUE THREAD

**Issue by npave** [omegaup/omegaup#903]
El profesor puede ver la lista de estudiantes inscritos a un curso y ver los problemas que ellos han resuelto.
- Crear template de la vista
  - Cada examen y cada tarea debe tener una columna separada.
    - Debe aparecer número de problemas resueltos y entre paréntesis el porcentaje de avance que llevan.

**Comment by rcxr** [comment]
Hay algún mockup de esta vista?
Hay algún asignado?

Tomando este issue

**Comment by npave** [comment]
Está libre, aquí están los mockups. [ofsMockups.zip](https://github.com/omegaup/omegaup/files/797513/ofsMockups.zip)

**Comment by joemmanuel** [comment]
@npave los mockups están épicamente chidos!
@omegaup/frontend FYI ^

**Comment by joemmanuel** [comment]
@npave , sólo para confirmar, este issue ya quedó resuelto con la tabla de progreso que tenemos actualmente, cierto?

**Comment by npave** [comment]
si, ya quedó resuelto
