### ISSUE TITLE
Editar Concursos

### ISSUE THREAD

**Issue by cope-quintana** [omegaup/omegaup#909]
Al editar un concurso que ya tiene soluciones revisadas no permite editar nada del concurso, ni hacerlo publico, ni cambiar descripción, solo permite agregar usuarios o administradores, en general ningún cambio que requiera utilizar el botón de "Actualizar Concurso" es aceptado.
Todo esto en la edición completa del concurso.

**Comment by lhchavez** [comment]
Hacerlo público si es un escenario que nos gustaría conservar, pero todo lo demás suena razonable.

**Comment by joemmanuel** [comment]
Siguiendo esta conversación, comentario de Manuel sobre cambiar el tiempo:

> siempre es alargarlo, hay veces que por algunas razones debemos extender el tiempo del examen para que mas concursantes puedan participar.

**Comment by lhchavez** [comment]
ya arreglamos el bug que impedía que se pudieran editar cosas no-relacionadas con los tiempos.
