### ISSUE TITLE
Evaluar PHP7

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#914]
Según esto es similar en desempeño a HHVM y necesitaríamos menos hacks para mantenerlo (como el plugin de New Relic).

**Comment by pabloaguilar** [comment]
Estoy ya quedo, no? O solo es Travis el que esta usando PHP 7 ?

**Comment by lhchavez** [comment]
ni Travis está usando PHP 7 :P es un truco para poder correr las pruebas de JavaScript en paralelo.

**Comment by lhchavez** [comment]
Llevamos meses usando PHP 7 ;)
