### ISSUE TITLE
[BUG] Intentar encontrar un escenario de reproducción para #945

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#946]
El pull request #945 arregló un bug que sólo ocurría en producción. Es claro _por qué_ ocurre, pero no qué pasos concretos son necesarios para reproducirlo en una prueba.

**Comment by elendil326** [comment]
@lhchavez Esto aún es importante?

**Comment by pabo99** [comment]
Encontrar la configuración o que otro aspecto del entorno no esté aceptandose en producción para poder reproducirlo.

**Comment by lhchavez** [comment]
creo que esto jamás lo vamos a atender.
