### ISSUE TITLE
Error con alias autogenerados de problemas

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#948]
Al momento de crear un nuevo problema, se autocalcula un alias que sirve como ID y también para la URL. Sin embargo, a veces el alias autocalculado es rechazado. Esto ocurre cuando el alias generado es muy largo (pero el mensaje de error no da pistas sobre el problema)

**Comment by elendil326** [comment]
@alanboy @lhchavez esto es solo mejorar logging? notificar al usuario? cambiar la manera en que se autogenera el alias?

**Comment by elendil326** [comment]
Esto es cambiar la manera en que se autogenera el alias y mejorar el logging y reporte del error.
