### ISSUE TITLE
[FEATURE] Reconsiderar poner los diffs de salidas en los detalles de un run para salidas pequeñas

### ISSUE THREAD

**Issue by joemmanuel** [omegaup/omegaup#990]
Hacer diffs manuales bajando casos es muy tedioso.

**Comment by lhchavez** [comment]
no en el server. se podría hacer en javascript.

**Comment by lhchavez** [comment]
rationale: GNU Diff usa este algoritmo que es O(ND): http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.4.6927

tendrían que ser muy pequeños los casos para no tener spikes accidentales en el servidor.

**Comment by elendil326** [comment]
@joemmanuel @lhchavez esto sería para todos los problemas con output pequeño? o solo si el ussuario así lo elige? Qué tan pequeño es pequeño?

**Comment by lhchavez** [comment]
creo que podríamos hacerlo para todos los problemas: vamos a exponer un API donde los problem admins pueden obtener casos individuales, así que si le hacen click a un botón podrían ellos decidir cuándo hacer el diff local y cuándo no.

**Comment by lhchavez** [comment]
necesitamos tener el backendv2.

**Comment by pabo99** [comment]
Aquí el documento: https://docs.google.com/document/d/1namOpwMAgNEDuboxtQf1-0YF-Q5ZxsLAHDnpO0Ps2q0/edit?usp=sharing
